include/triton/Conversion/TritonGPUToLLVM/TargetInfoBase.h
lib/Conversion/TritonGPUToLLVM/PrintOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/SPMDOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/ScanOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.h
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.h

This commit updates various methods in `TargetInfo` to be consistent regarding `rewriter` and `loc`.

[backend] NFC: Make TargetInfo methods consistent with parameters

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
test/TritonGPU/loop-pipeline.mlir

<git-pr-chain>
[Backend] Allow dot operand pipelining in more circumstances.
PR #3472 partially rolled back PR #3415 due to internal test failures.  This PR
rolls forward the change as much as we currently can, allowing *most* but not
all relevant loads to be pipelined.
There is still a TritonGPU -> LLVM codegen bug in Triton that we have not been
able to fix, but now we catch it with asserts, PR #3549.
1. 👉 #3561 👈 **YOU ARE HERE**

[Backend] Allow dot operand pipelining in more circumstances.

---

python/test/unit/language/test_decorator.py
python/triton/runtime/jit.py

Under certain conditions where we apply another decorator on top of triton.jit, there is a small chance that in the decorator body there's a "def" substring in it. This is problematic when JITFunction parses function def using str.find('def'). This causes an issue compiling some pytorch model when we happened to decorate a jit function with a hash string argument which has "def" in it.
This diff tries a bit harder to locate the real "def" position using a more complex regex which should further reduce the chance to hit this error.

[frontend] Improve function def parsing with stacked decorators.

---

python/test/unit/language/test_core.py
python/triton/runtime/interpreter.py

I found with `TRITON_INTERPRET=1`, `tl.dot` almost always gives wrong result for INT8 input, due to `np.matmul` use inputs' dtype as result dtype by default:
```
>>> a = np.array([[10, 20]], np.int8)
>>> np.matmul(a, a.transpose())
array([[-12]], dtype=int8)
>>> np.matmul(a, a.transpose(), dtype=np.int32)
array([[500]])
```

[INTERPRETER] Use acc's dtype as computation dtype in `tl.dot`

---

bin/triton-llvm-opt.cpp

Add an `-o` option to allow specifying output file name. This is useful for separating IR output from pass printings which will be added later.

[BACKEND] Add -o for triton-llvm-opt

---

.github/workflows/integration-tests.yml

Per cache scoping: "the cache is scoped to the key, version, and branch. The default branch cache is available to other branches." We need to have cache generated for the main branch so that all pull requests can use, instead of each pull request doing its own caching that cannot be shared. Until then, disable caching.

[ci] Disable cache until we can automate generation on main

---

.github/workflows/integration-tests.yml

This has two effects.
1. We get test results when pre-commit fails, which is nice.
2. We speed up CI by about 30-60s, which is how long pre-commit was taking to
run.  Now pre-commit runs in parallel with builds/tests.

[CI] Move pre-commit to separate CI job.

---

.github/workflows/integration-tests.yml

This lets us see how long they take.

[CI] Split out `pip install` and `apt-get install` into separate build steps.

---

.github/workflows/integration-tests.yml

These tests are passing. Enable them to make sure
we don't see regression for the AMD backend.

[ci][amd] Enable running C++ tests

---

.github/workflows/integration-tests.yml

We have separate paths for AMD and NVIDIA backends in the integration tests so the if conditions for the NVIDIA part is just dead code.
Also unified environment variables into global scope when possible; and updated `$PATH` handling.

[ci] Clean up condition and environment variable usage

---

.github/workflows/integration-tests.yml
python/test/unit/language/test_block_pointer.py
python/triton/runtime/interpreter.py

This would make debugging kernels using block pointer easier.

[INTERPRETER] Support padding_option of tl.load

---

lib/Analysis/Allocation.cpp
python/test/unit/runtime/test_autotuner.py
python/triton/ops/matmul_perf_model.py
python/triton/runtime/autotuner.py

Otherwise any variables passed with `<name>=<value>` are not visible in the `early_config_prune` callback

[AUTOTUNER] Pass `kwargs` to `early_config_prune` callback

---

.github/workflows/integration-tests.yml
lib/Analysis/Utility.cpp
python/triton/ops/flash_attention.py
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUTransforms/RemoveLayoutConversions.cpp

This commit fixes the lowerMfmaToDotOperand function by removing the packing of vecSize elements into LLVM structs. This was previously done because dot lowering required operands of the dot operation to be packed in this way, which was later changed. This commit also adds FA tests to AMD CI.

[AMD] Enable Flash Attention Tests

---

include/triton/Conversion/TritonGPUToLLVM/Utility.h

Macros for which the definition was added in https://github.com/openai/triton/pull/3522, but the declaration was forgotten

Add missing declarations for LLVM macros to Utility.h

---

python/tutorials/03-matrix-multiplication.py

Few small tweaks to get good perf out of fp8 matmul tutorial.
Make sure to use 3 source dot and pre-transpose b to get good performance. Also add more configs that work well for fp8.
Results on H100:
```
matmul-performance-fp8:
M       N       K       Triton
0    256.0   256.0   256.0     0.483438
1    384.0   384.0   384.0     1.768588
2    512.0   512.0   512.0     4.390792
3    640.0   640.0   640.0     9.194164
4    768.0   768.0   768.0    15.353337
5    896.0   896.0   896.0    24.886629
6   1024.0  1024.0  1024.0    37.882509
7   1152.0  1152.0  1152.0    51.427067
8   1280.0  1280.0  1280.0    73.470854
9   1408.0  1408.0  1408.0    96.225503
10  1536.0  1536.0  1536.0   125.411082
11  1664.0  1664.0  1664.0   158.921188
12  1792.0  1792.0  1792.0   193.992213
13  1920.0  1920.0 …
```

[TUTORIAL] Improve fp8 performance in matmul tutorial

---

test/Conversion/amd/load_store.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp

Current implementation for load vectorization uses segmented short-vectorized loads instead of a full 128-bit load. Using multiple copies of shorter load creates a dependency on the LLVM backend (esp. the load and store vectorizer) for full vectorization. This could be fragile as I saw in some cases the vector combine pass and the jump threading pass screwed it up and resulted in non-ideal vectorization
This is a backport of https://github.com/ROCm/triton/pull/445/

[BACKEND][AMDGPU] Use full-vectorized load instructions for load vectorization

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/PipelineExpander.cpp

This was not really causing any issues, but double visit was not intended.
Rely on the fact that walk also visits the op that it has been called on.

[BACKEND] Fix double visit during walk in the Pipeline Expander

---

README.md
include/triton/Tools/Sys/GetEnv.hpp
python/src/ir.cc
python/triton/compiler/compiler.py

This can help us analyzing the mapping from ttgir to llir/ptx. When used with performance tools, it can provide a breakdown on ttgir instructions.
Added one env variable:
"USE_TTGIR_LOC": will not emit location information in the dumped ttgir, will re-parse the ttgir file and use ttgir line numbers as debug info
When running on vector-add with USE_TTGIR_LOC=1:
ttgir: #loc = loc("/cache-path/add_kernel.ttgir":2:1)
llir: !3 = !DIFile(filename: "add_kernel.ttgir", directory: "/cache-path")

Use ttgir line number instead of source line number to help matching from ttgir to llir/ptx

---

.github/workflows/integration-tests.yml
python/test/unit/language/test_line_info.py

This commit enables test_line_info.py. It's mostly about finding the proper disassembler for hsaco and disassemble it with the necessary command line options.

[backend][amd] Enable line info test

---

.github/workflows/integration-tests.yml
python/test/unit/operators/test_matmul.py
python/test/unit/runtime/test_subproc.py

This PR 
- enables test_matmul by skipping fp8 input and tf32x3.
- fixes test_subproc on MI300.

[AMD] Enable test_matmul on CI and fix test_subproc on MI300

---

python/test/unit/language/test_core.py
third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp

This PR is to turn on the memory ordering in lowering the atomic ops and fix the UT `test_core.py::test_atomic_cas`. Also increased the number blocks in the kernel of the test for more pressure.

[AMD backend] enable atomic memory ordering in lowering atomic ops

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/PipelineExpander.cpp

Verifier was not catching the cases where the improperly scheduled op was nested in another op - so far we were looking only at the top level operations.
I have checked the perf tests to make sure we are not preventing any currently pipelined kernels from pipelining. Everything looks green.

[PIPELINER] Schedule verifier improvements

---

python/test/unit/language/test_core.py
python/triton/compiler/compiler.py

This is a TTGIR test for the bug worked around in PR https://github.com/openai/triton/pull/3561.
While we're here, we also do a minor cleanup in test_core.py.
A previous version of this patch needed us to fix the regex for parsing an MLIR
file to find the individual arguments.  Previously it would include the
function's closing paren in the argument type.  We keep this because it's a
reasonable fix.
I am extremely frightened by this test; if you comment out the skip() at the
beginning, many tests fail due to OOB memory accesses or wrong results, in
addition to the asserts added in PR https://github.com/openai/triton/pull/3561.  Who knows if we hit this today?

[Tests] Add test for local_load to #mma layout.

---

python/triton/compiler/compiler.py
python/triton/runtime/jit.py
third_party/amd/backend/compiler.py
third_party/nvidia/backend/compiler.py
third_party/nvidia/backend/driver.py

The extra overhead of extracting kernel metadata from a NamedTuple object results in a small regression (6% geomean) on torchbench: https://github.com/pytorch/pytorch/issues/123597.
We can claw most of that back by asking the backend to pack the metadata into a plain tuple, so that we can extract it with `ParseTuple`

[FRONTEND] Pack metadata into tuples to improve launch latency

---

python/triton/runtime/jit.py

This improves kernel launch latency by 2.2x (from 108us to 49us using @bertmaher's benchmarking script in issue https://github.com/openai/triton/issues/3619 ). Thanks also to @liboyue's analysis and suggestions.
See the discussion in the third-party PR https://github.com/openai/triton/pull/3503#issuecomment-2047718096

attempt to substantially reduce kernel launch overhead

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
test/TritonGPU/loop-pipeline.mlir

When analyzing dependencies for dist1Uses we need to look at all the operands of the ops in nested blocks, otherwise we end up with incorrect schedule.
Adding a test that fails to pipeline without the proposed fix.

[BACKEND][PIPELINER] Fixing an incorrect schedule generated for a loop with dependencies with ops on different levels of nesting

---

.github/workflows/integration-tests.yml
python/src/ir.cc
python/test/unit/language/test_reproducer.py
third_party/amd/backend/compiler.py

This PR is to fix the unit test `test_reproducer.py`. 
Reason of the failure is that compiler in amd backend calls the function `pm.run(mod)` multiple times, reproducer is only for the passes in the last call of the function `pm.run(mod)`, so ttgir->llvm pass is not included in the last call. 
Fix is to call the `pm.run(mod)` only once in the function `make_llir()`.

[AMD backend] fix test reproducer

---

test/TritonGPU/amd/amd-reorder-instructions.mlir
third_party/amd/lib/TritonAMDGPUTransforms/ReorderInstructions.cpp

This commit moves all LocalAlloc and LocalLoad ops after their operands.
This is useful in flash attention case. This way,
Q tensor is moved out of the main loop and is kept in the registers throughout the computation.

[AMD] Fix ReorderInstructions Pass

---

lib/Conversion/TritonGPUToLLVM/PrintOpToLLVM.cpp
test/Conversion/tritongpu_to_llvm.mlir

Printing of pointers used to crash because we were checking for LLVM::PointerType instead of LLVM::LLVMPointerType

[BACKEND] Fix printing of pointer types

---

python/triton/runtime/jit.py

This is a further 2.7x speedup (from 49us to 18us) of kernel launch overhead compared with the previous PR, with help from cProfile to find the hotspots.
Also fixes an old compiler bug where the `None`-ness of arguments didn't enter into the cache key, leading to scary bugs.

Faster jit

---

python/test/unit/language/test_core.py
python/triton/compiler/code_generator.py

https://github.com/openai/triton/commit/99b024bb3a81e9aa5c94d4a63fc9e2c60da5e6da introduced a bug in debug mode where `assert isintance(..., list)` fails in `tl.interleave` with
```
assert isinstance(c.shape, list)
^
NameError('list is not defined')
```
This was reported to PyTorch as https://github.com/pytorch/pytorch/issues/123967

[FRONTEND][Easy] Fix assert list bug

---

third_party/amd/backend/driver.c
third_party/amd/backend/driver.py

This commit changes the AMD backend to perform dynamic loading of the HIP runtime library. This is better because of various reasons, including but not limited to:
* We can be consistent with PyTorch regarding the library used
* We can give explicit control to developers as which dylib to use
* We can trim down the dependencies in Triton
* etc.
The dynamic loading procedure will try to load the `libamdhip64.so` directory from the current process if exists. Otherwise, it goes through the following steps:
* If we are told explicitly what HIP runtime dynamic library to use with the `TRITON_LIBHIP_PATH` environment variable, obey that. Do not attempt any other library locations.
* Otherwise, first search the HIP runtime dynamic library packaged with PyTorch. It's very likely that we run …

[backend][amd] Change to dynamically load libamdhip64.so

---

third_party/amd/backend/compiler.py
third_party/amd/python/triton_amd.cc

This allows us to always get a copy of the amdgcn assembly from in the compilation stages, which is quite useful for readability and debugging and various other purposes.

[backend][amd] Create separate stages for amdgcn and hsaco

---

third_party/amd/backend/compiler.py
third_party/amd/backend/driver.py

similar to https://github.com/openai/triton/pull/3633
This PR made the AMD backend to use packed metadata

make AMD compiler and driver use packed metadata

---

python/triton/runtime/jit.py

avoid import in hot code; use `self.cache[device].get(key, None)` instead of testing presence before retrieving (halving the number of times we need to hash and string-compare when accessing the hashtable); only retrieve the target when the device changes.

Further latency improvements (15us --> 12us)

---

third_party/proton/csrc/lib/Profiler/CuptiProfiler.cpp

e.g., cublas/cutlass gemm kernels like `sm90_xmma_gemm_f16f16_f16f32_f32_tn_n_tilesize128x128x64_warpgroupsize1x1x1_execute_segment_k_off_kernel__5x_cublas`

[PROTON] Support kernels launched with `cudaLaunchKernelExC` and `cuLaunchKernelEx` on sm>=90

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td

Transposed operand will be accessed in an opposite order from the original operand. Enabling swizzling seems to help performance. I'm seeing 10% performance improvement for our internal model.
This is a backport of https://github.com/ROCm/triton/pull/474.

[BACKEND][AMD] Enable swizzling SMEM for transposed operand

---

python/src/llvm.cc
third_party/amd/backend/compiler.py
third_party/amd/python/triton_amd.cc

This PR adds `InReg` attributes to all kernel arguments. This tells the backend compiler to try to set things up so that the firmware will set kernel args to user SGPRs instead of using `s_load` at the beginning of the kernel.
Note that though we set `InReg` to all kernel args,  the backend compiler will decide the actual number of args that can be pre-set.
Performance context: this PR can improve kernel execution time by about 5 ~ 10 us.

[AMD] Hint the compiler to preload kernel arguments

---

third_party/amd/backend/compiler.py

Required for triton wheels as part of ROCm-pytorch's migration to use upstream triton.
In https://github.com/pytorch/pytorch/pull/121801 we package libraries and ld.lld into `third_party/amd/backend`. This change will look for the linker in `third_party/amd/backend/llvm/bin` before looking out to `/opt/rocm`

[AMD] Search backend for ld.lld before /opt/rocm

---

.github/CODEOWNERS

This commit adds code owners for the third_party/amd directory so we can have automatic reviewer assignment.

Add third_party/amd code owners

---

python/triton/runtime/autotuner.py

The example code in [autotune](https://triton-lang.org/main/python-api/generated/triton.autotune.html#triton.autotune) fails because of incorrect argument name. 
The issue can be easily reproduced by
```python
>>> import triton
>>> triton.Config(meta={'BLOCK_SIZE': 128}, num_warps=4),
TypeError: Config.__init__() got an unexpected keyword argument 'meta'
```
1. Fix the inline documentation of argument name
2. Fix example code

[DOC][easy] Fix outdated triton.Config argument doc and example

---

.github/workflows/integration-tests.yml
python/test/unit/hopper/test_gemm.py

This PR is to turn on the UT `test/unit/hopper/test_gemm.py`. Previous error caused by a cuda backend specific input parameter `num_ctas`. After skipping this input for AMD backend, all tests can pass.

[AMD backend] turn on `hopper/test_gemm.py` for amd backend

---

.github/workflows/integration-tests.yml
python/test/unit/hopper/test_persistent_warp_specialized_fused-attention.py

This PR is to turn on the test `hopper/test_persistent_warp_specialized_fused-attention.py` by increasing the tolerance on MI200 (due to the denorm issue related to [reduced precision on MI200](https://pytorch.org/docs/stable/notes/numerical_accuracy.html#reduced-precision-fp16-and-bf16-gemms-and-convolutions-on-amd-instinct-mi200-devices)) .

[AMD backend] turn on persistent fused attn by increasing atol for MI200

---

.github/workflows/integration-tests.yml
python/test/unit/operators/test_blocksparse.py

It seems like the test `test_blocksparse.py` pass by increasing the `atol` from 1e-5 to 1e-3, so turn it on in CI.

[AMD backend] turn on test_blocksparse.py

---

python/setup.py

The assignment operator := not supported in Python 3.7, which Triton still releases wheels for.
Failing nightly wheels build[ here](https://github.com/openai/triton/actions/runs/8718345542/job/23915395650#step:7:179).
> File "/tmp/pip-build-env-i3hksojj/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
exec(code, locals())
File "<string>", line 312
if cuda_root := get_env_with_keys(["CUDA_HOME", "CUDA_ROOT"]):
^
SyntaxError: invalid syntax

[Build] Fix nightly wheel build.

---

.github/workflows/integration-tests.yml
.github/workflows/integration-tests.yml.in

We were checking for builds in the last N hours, but specifically we need to
check on branch main, not just any branch.
Also we were getting false failures on builds on `main` because the matrix-CUDA
(or matrix-HIP) variable was empty when we didn't want to run any tests.  Try
to fix this.

Attempt to fix new CI caching.

---

third_party/proton/csrc/include/Data/TreeData.h
third_party/proton/csrc/lib/Profiler/CuptiProfiler.cpp

Otherwise g++ 13 throws errors like this:
```
FAILED: third_party/proton/CMakeFiles/proton.dir/csrc/lib/Profiler/CuptiProfiler.cpp.o 
ccache /usr/lib/ccache/bin/c++ -Dproton_EXPORTS -I/home/vitalyr/projects/dev/cpp/triton/python/build/cmake.linux-x86_64-cpython-3.11/third_party/proton -I/home/vitalyr/projects/dev/cpp/triton/third_party/proton -I/home/vitalyr/projects/dev/cpp/triton/include -I/home/vitalyr/projects/dev/cpp/triton/. -I/usr/local/opt/llvm-triton/include -I/home/vitalyr/projects/dev/cpp/triton/python/build/cmake.linux-x86_64-cpython-3.11/include -I/home/vitalyr/projects/dev/cpp/triton/third_party -I/home/vitalyr/projects/dev/cpp/triton/python/build/cmake.linux-x86_64-cpython-3.11/third_party -I/home/vitalyr/projects/dev/cpp/triton/python/src …
```

[PROTON] Add missing C++ includes

---

.github/workflows/integration-tests.yml
.github/workflows/integration-tests.yml.in

from 13 m to 11m (it's mainly contributed by hopper/test_gemm)

[AMD] Run hopper/ tests in parallel to reduce CI time

---

third_party/amd/backend/compiler.py
third_party/amd/python/triton_amd.cc

Device libs are only needed in the following cases
- tl.math functions need ocml.bc or ockl.bc
- extra.cuda.libdevice functions need cuda2gcn.bc
- Some functions in cuda2gcn is lowered into opencl.bc
Linking to these device libs can increase CI time for about 3 minutes. This PR adds a simple logic to check if extern device lib functions are in the module and only link to proper *.bc code when necessary.
Now CI time is reduced from 11 min (after https://github.com/openai/triton/pull/3686) to 8 min.

[AMD] Only link device libs when necessary

---

python/triton/runtime/autotuner.py

Return single inf value after failed bench attempt
in case of use_cuda_graph to properly compare it to other results

[AUTOTUNER] Fix return value of `use_cuda_graph` when `OutOfResources` is raised

---

README.md
include/triton/Tools/Sys/GetEnv.hpp
python/src/ir.cc

This is for reducing the noise from using TRITON_ENABLE_LLVM_DEBUG.

[DEBUG] Add support for a Triton envvar to enable LLVM's -debug-only

---

.github/workflows/integration-tests.yml
.github/workflows/integration-tests.yml.in

We now have ccache, clang, and lld installed in the nvidia docker images.
Usually apt-get install'ing these is fast, but sometimes it is slow or hangs, e.g. https://github.com/openai/triton/actions/runs/8754510491/job/24026456975, so using the versions from the docker removes a failure mode in CI.

Remove apt-get install from CI.

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td

Turns out our understanding of shared-layout swizzling was incorrect.  I wrote
a testcase (reproduced here) that writes into shared memory and then hackily
uses inline asm to read out of shared memory in exactly the order Triton wrote
vaoues.  Then I updated the comment to reflect what Triton actually does.
```
def test_shmem_indices(device):
N = 8
M = 4
asm = f"""{{
.reg.b32 %tmp<3>;
mov.b32 %tmp0, %tid.x;
and.b32 %tmp0, %tmp0, {N*M-1};
shl.b32 %tmp0, %tmp0, 2;
mov.b32 %tmp1, global_smem;
add.u32 %tmp2, %tmp0, %tmp1;
ld.shared.b32 $0, [%tmp2];
}}"""
asm = textwrap.dedent(asm).replace("\n", " ")
ir = f"""
module attributes {{"triton_gpu.num-warps" = 4 : i32, "triton_gpu.num-ctas" = 1 : i32, "triton_gpu.threads-per-warp" = 32 : i32}} {{
tt.func public @kernel_0d1d(%out_ptr: !tt.ptr<i32> …
```

Fix comment about shared-layout swizzling.

---

python/setup.py

Otherwise if a user execute `python python/setup.py install` it fails to find related version files

[BUILD][NIT] Using base dir instead of hardcoded path

---

python/test/unit/hopper/test_gemm.py
python/test/unit/hopper/test_persistent_warp_specialized_fused-attention.py
python/test/unit/language/assert_helper.py
python/test/unit/language/print_helper.py
python/test/unit/language/test_conversions.py
python/test/unit/language/test_core.py
python/test/unit/language/test_line_info.py
python/test/unit/operators/test_blocksparse.py
python/test/unit/operators/test_matmul.py
python/test/unit/tools/test_aot.py
python/triton/backends/compiler.py
python/triton/compiler/compiler.py
python/triton/ops/flash_attention.py
python/tutorials/06-fused-attention.py
third_party/amd/backend/compiler.py
third_party/amd/backend/driver.py
third_party/nvidia/backend/compiler.py
third_party/nvidia/backend/driver.py

This commit changes the target description to be a dataclass so that we can use attributes to access various fields instead of magic array indices. This makes it more readable.

[frontend] Use a structured dataclass for target description

---

third_party/amd/backend/compiler.py
third_party/amd/python/triton_amd.cc

* Define AMD target triple in `triton_amd.cc` for better isolation.
* Make `triton_amd.cc` function parameter names more consistent.
* Drop unused function in `compiler.py`.

[backend][amd] Minor improvements definitions and comments

---

lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
test/TritonGPU/combine.mlir

We need to keep track of which yield operands needs to be rewritten as the same value may be used with different layouts.
---------
Co-authored-by: Manman Ren <mren@fb.com>

[BACKEND] Fix bug in backward remove layout conversion

---

bin/RegisterTritonDialects.h
include/triton/Conversion/TritonToTritonGPU/Passes.td
include/triton/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.h
include/triton/Dialect/TritonGPU/IR/TritonGPUDialect.td
lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp
python/src/passes.cc
test/Conversion/amd/decompose-unsupported-conversions.mlir
test/Conversion/amd/fp_to_fp.mlir
test/Conversion/amd/load_store.mlir
test/Conversion/amd/tritongpu_wmma_dot_to_llvm.mlir
test/Conversion/triton_to_tritongpu.mlir
test/TritonGPU/amd/accelerate-amd-matmul-wmma.mlir
third_party/amd/backend/compiler.py
third_party/amd/include/TritonAMDGPUToLLVM/Passes.h
third_party/amd/include/TritonAMDGPUToLLVM/Passes.td
third_party/amd/include/TritonAMDGPUToLLVM/TargetUtils.h
third_party/amd/include/TritonAMDGPUTransforms/Passes.h
third_party/amd/include/TritonAMDGPUTransforms/Passes.td
third_party/amd/lib/TritonAMDGPUToLLVM/CMakeLists.txt
third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/PatternTritonGPUOpToLLVM.h
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.h
third_party/amd/lib/TritonAMDGPUToLLVM/TargetUtils.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/TritonGPUToLLVM.cpp
third_party/amd/python/triton_amd.cc

This commit improves how target architecture are handled in the AMD backend.
Previously we have three ways of specifying the target: 1) the `gfx*` target architecture, 2) a compute capability number that matches the CDNA generation, e.g., 300/200/100, 3) a compute capability number that tries to pretend to be CUDA equivalence, e.g., 80/90. These three schemes are quite inconsistently used and not all the places are properly seeing the target it should be--it can be quite confusing.
In general, for CodeGen towards AMD GPU, the `gfx*` target architecture should be the original source of capability and feature information. Further, for AMD, there is no exact correspondance of NVIDIA CUDA compute capability numbers.
So this commit changes to base on the `gfx*` target, and adds utility …

[backend][amd] Make target specification and usage consistent

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/SoftwarePipeliner.cpp

Doing some basic sanitize checking on `num_stages` before piplining a loop. User may specify `num_stages` in a way below which fails the compilation :
`for i in tl.range(0, XBLOCK, num_stages=1):`

[BACKEND] Sanitize on num_stages before piplining a loop.

---

lib/Dialect/Triton/IR/Ops.cpp

After PR #3587, LoadOp's build methods have been altered and no longer use getLoadOpResultType. This is a cleanup change.

[IR] Dropping getLoadOpResultType since it is no longer used

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Dialect/TritonGPU/IR/Dialect.cpp

To dispatch the call to new the interface `getContigPerThread` of the `DistributedEncodingTrait`.
It gives capability to the third_part plug-in to define the new layout attributes and reuse the common TritonGPU utils.

Decouple the implementation of the Triton GPU `getContigPerThread` API

---

CMakeLists.txt
bin/CMakeLists.txt

* Add TRITON_BUILD_UT(Default: ON) option to enable a the ability for disabling unit-test build when use triton as thirdparty project.
* Fix  llvm build bugs in bin/CMakeLists.txt when using triton in other projects.

[Build] fix some bugs in cmake when use triton as thirdparty lib

---

python/test/unit/language/test_compile_errors.py
python/test/unit/language/test_random.py
python/triton/compiler/code_generator.py

<git-pr-chain>
[Frontend] Disallow access to globals that are not tl.constexpr.
We've found that users often accidentally access global vars from inside a
Triton kernel that they don't mean to.  Moreover, they sometimes *change* these
global vars after they first run the kernel, but Triton does not notice this
(the initial value of the global is baked into the compiled kernel). As a
result, the following runs have a stale value for the global.
We hope that making users annotate their globals with tl.constexpr will remind
them that they are kernel arguments that they should not change.
In a separate PR, we will additionally explore the possibility of raising an
error when the value of one of these globals changes.
This is a breaking change, so we allow you to opt out of it by setting …

[Frontend] Disallow access to globals that are not tl.constexpr.

---

python/test/unit/language/test_core.py
python/triton/runtime/interpreter.py

Named arguements were not copied to and from the host like positional arguments. This was causing crash when passing gpu tensors as named arguments.

[INTERPRETER] Handle named arguments copies to host

---

CMakeLists.txt

This allows us to disable building proton if directly configuring from the top level CMakeLists.txt. Right now Proton has various dependencies that are only configured through the Python setup.py entry point.

[cmake] Add option to control building proton

---

.gitignore

We were creating libproton.dylib, which was not being gitignored.

gitignore proton's shared library on mac.

---

README.md

This commit updates the testing instructions in the readme file. The two missing packages are used by triton in "triton/testing.py". Without these dependencies users get the following error:
```
File "/home/..../test/test.py", line 133, in <module>
benchmark.run(print_data=True, show_plots=True)
File "/home/..../triton/python/triton/testing.py", line 346, in run
result_dfs.append(self._run(bench, save_path, show_plots, print_data, **kwargs))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/..../triton/python/triton/testing.py", line 272, in _run
import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

[DOC] Update the testing instructions.

---

README.md

This commit updates the LLVM build instructions in the readme file. The current instructions result in a triton build that fails at load-time with the following error:
```
ImportError: /home/.../triton/python/triton/_C/libtriton.so: undefined symbol: LLVMInitializeSparcTarget
```
This flag is used in the triton docker files.

[DOC] Update LLVM build instructions.

---

lib/Dialect/TritonNvidiaGPU/Transforms/TMALowering.cpp
python/test/unit/hopper/test_experimental_tma.py
python/triton/language/core.py
third_party/nvidia/backend/driver.c
third_party/nvidia/backend/driver.py
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/BarrierOpToLLVM.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp

Add a test to exercise matmul with TMA experimental loads. This ensure we generate correct code for this cases. The next step will be to enable pipelining.
Fix few bugs in the codegen found in the process.

Add TMA matmul test

---

python/triton/language/__init__.py
python/triton/language/core.py

As promised, these were just for temporary backwards compat.

[Frontend] Remove tl._experimental_join and tl._experimental_split.

---

python/test/unit/language/test_core.py
python/triton/runtime/interpreter.py

The interpreter had a bug where it would raise an exception if tl.max() or
other reductions returned 0.

[Interpreter] Fix tl.max() in interpreter when it returns 0.

---

test/TritonGPU/amd/amd-optimize-epilogue.mlir
third_party/amd/lib/TritonAMDGPUTransforms/OptimizeEpilogue.cpp

The optimize epilogue pass tries to use #mma layout directly when doing tt.store. Basically it has two steps:
- It starts from tt.store and goes backward to collect a chain of ops until it reaches the convert_layout(#mma, #blocked). 
- Then it starts from the convert_layout(#mma, #blocked) and "fix" the collected ops in a forward manner.
Previously, we only have at most one op in the chain (usually it's the truncf op), so the order in the "fix" step does not matter. However, when we have more ops (more fused elementwise op before tt.store, it does not compile (type of operand and result does not match) since we are using the wrong order.
This PR fixes this problem by simply reversing the chain in the "fix" step.

[AMD] Fix a bug in optimize epilogue pass

---

README.md
include/triton/Tools/Sys/GetEnv.hpp
python/src/llvm.cc

`DISABLE_LLVM_OPT` will disable llvm optimizations for make_llir and make_ptx if its value is true when parsing as Bool. Otherwise, it will be parsed as a list of flags to disable llvm optimizations. One usage case is
`DISABLE_LLVM_OPT="disable-lsr"`
Loop strength reduction is known to cause up to 10% performance changes for certain kernels with register pressure.

Use DISABLE_LLVM_OPT to selectively disable llvm optimizations

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
test/TritonGPU/loop-pipeline.mlir

After introducing ordering clusters to the loop pipeline, we now need to take care that ops scheduled to the last stage at the very end respect the ordering of their dependencies.

Scheduling downstream dependencies of ops in the last stage correctly

---

include/triton/Tools/Sys/GetEnv.hpp
third_party/nvidia/backend/compiler.py

This is just a simple env var in the same vein as MLIR/LLVM_IR_ENABLE_DUMP. It has been helpful to me for reading the 
PTX output directly from the console instead of having to hunt for it in the Triton cache.

[DEBUG] Add NVPTX_ENABLE_DUMP option to dump PTX after it's generated by LLVM

---

third_party/amd/backend/driver.c
third_party/nvidia/backend/driver.c

Exposing more hardware properties. These can be used to determine thread occupancy when computing grid size for persistent kernels.

Expose more hardware properties

---

third_party/proton/csrc/include/Context/Context.h
third_party/proton/csrc/lib/Context/Context.cpp

For some reason this was causing duplicate-definition errors for me when I
built with DEBUG=1 on macos.  Just move the variable to be out-of-line.

[Proton] Make `inline static thread_local` variable non-inline.

---

README.md
python/triton/compiler/compiler.py

When you work on the triton compiler itself, you'd want to compile kernels always. So far, we had to remove `$TRITON_CACHE_DIR` or the default triton cache directory. This PR introduces a quick environment variable that forces to kernel compilation always, regardless of cache hit.
```
TRITON_ALWAYS_COMPILE=1 python3 tutorials/01-vector-add.py
```

[DEBUG] Add TRITON_ALWAYS_COMPILE to force compilation

---

bin/RegisterTritonDialects.h
third_party/amd/lib/TritonAMDGPUToLLVM/CMakeLists.txt
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandWMMA.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/MFMA.cpp
third_party/amd/lib/TritonAMDGPUTransforms/CMakeLists.txt

In the PR I removed all `USE_ROCM` guard that is no longer necessary since HIP/Cuda are separate backends. This PR has no functional impact to the existing code base. 
Note that `RegisterTritonDialects.h` would already register both Cuda or HIP only passes out of box as by default `-DTRITON_BACKENDS_TUPLE="(nvidia,amd)"`

[AMD] Removing redundant USE_ROCM guard

---

third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/Utility.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/Utility.h

Even though we are using 1D blocks so our threadId.x is uniform, ptxas emits a loop around `cp.async.bulk.tensor` predicated with `threadId.x == 0` as it fails to recognize that predicate will be uniform. To avoid that, we `and` the predicate with a result of an `elect.sync` instruction that returns single active channel, and forces the instruction to be recognized as uniform.

Using elect to make ptx realize TMA copies are uniform

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp

`IfOp` pipelining PR changed the logic around selecting which ops to pipeline to separate `LoadOp` discovery and selecting which of them to pipeline. What I have missed in that PR is that now we need to make sure that we don't leave root users of `loads` that don't make the cut in the coarse schedule, as this may result in incorrect schedule.

[BACKEND][PIPELINE] Do not add root users of loads that we won't pipeline to the coarse schedule.

---

python/tutorials/02-fused-softmax.py

Rewriting the tutorial softmax kernel in a persistent way. 
Some perf numbers on H100:
1. Before (non-persistent):
```
softmax-performance:
N       Triton  Torch (native)  Torch (jit)
0     256.0   809.086437      840.205157   341.111242
1     384.0  1043.013292     1054.198425   438.123694
2     512.0  1236.528308     1224.971964   489.074621
3     640.0  1323.959634     1356.852972   541.843731
4     768.0  1432.480902     1461.769457   579.537226
..      ...          ...             ...          ...
93  12160.0  1900.754134     1668.141169   619.802865
94  12288.0  1907.079736     1623.706355   621.746785
95  12416.0  1909.006619     1610.588287   621.224670
96  12544.0  1922.336989     1613.700487   622.428454
97  12672.0  1929.822731     1594.314727   621.224030
```
2. After …

Persistent softmax kernel

---

include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td
lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp
lib/Dialect/TritonNvidiaGPU/Transforms/TMALowering.cpp
python/test/unit/hopper/test_experimental_tma.py
test/TritonNvidiaGPU/tma_lowering.mlir
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/BarrierOpToLLVM.cpp

According to PTX spec this is needed before the shared memory can be re-used. This is suspected to be causing sporadic memory corruptions.

[BACKEND] Invalidate mbarrier after their last use.

---

third_party/proton/csrc/Proton.cpp
third_party/proton/csrc/include/Data/Data.h
third_party/proton/csrc/include/Data/Metric.h
third_party/proton/csrc/include/Data/TraceData.h
third_party/proton/csrc/include/Data/TreeData.h
third_party/proton/csrc/include/Session/Session.h
third_party/proton/csrc/lib/Data/TraceData.cpp
third_party/proton/csrc/lib/Data/TreeData.cpp
third_party/proton/csrc/lib/Session/Session.cpp
third_party/proton/proton/scope.py
third_party/proton/test/test_api.py

Different from "metrics" that can be aggregated, "properties" in proton cannot.
This is particularly useful for fine-grained IR analysis for GPU kernels. We need to know the file path of each kernel to get the path to IR files. Using the existing approach, a file path has to be appended to a scope name, which is not something that the user wants to know. Instead, by setting a `file_path` property, the path will be hidden from users. Given that each triton kernel corresponds to a unique file path, the solution should work.

[PROTON] Support setting scope/op properties

---

third_party/proton/csrc/include/Driver/Dispatch.h
third_party/proton/csrc/lib/Driver/GPU/Cuda.cpp
third_party/proton/csrc/lib/Profiler/CuptiProfiler.cpp

https://forums.developer.nvidia.com/t/wsl2-libcuda-so-and-libcuda-so-1-should-be-symlink/236301
On WSL, "libcuda.so" and "libcuda.so.1" may not be linked, so we use "libcuda.so.1" instead.

[PROTON] Fix libcuda symbol look up problem on WSL

---

include/triton/Conversion/TritonGPUToLLVM/Utility.h
test/Conversion/dedup-by-constancy.mlir

We've encountered issues on AMDGPU and A100 GPUs not raised in CI.

Disable linear layouts.

---

third_party/nvidia/backend/driver.c
third_party/nvidia/backend/driver.py

This is consistent with pytorch
> As `libcuda.so` is only installed on dev environment (i.e. when CUDAToolkit is installed), while `libcuda.so.1` is part of NVIDIA driver.
https://github.com/pytorch/pytorch/commit/3be0e1cd587ece8fa54a3a4da8ae68225b9cbb9b

[RUNTIME] `dlopen` loads `libcuda.so.1` instead of `libcuda.so`

---

third_party/proton/csrc/include/Profiler/CuptiProfiler.h
third_party/proton/csrc/include/Profiler/Profiler.h
third_party/proton/csrc/lib/Profiler/CuptiProfiler.cpp

`CuptiProfiler.h` needs to be included in `Session.cpp`, which will also include `RocTracerProfiler.h`, mixing `cupti.h` and `roctracer_hip.h` will cause problems because some variables in hip and cuda have the same name.
Thus, `CuptiProfiler.h` shouldn't include anything specific to nvidia, and `RocTracerProfiler.h` shouldn't include anything specific to amd.

[PROTON] Remove cupti/cuda header files in CuptiProfiler.h

---

third_party/amd/backend/compiler.py
third_party/amd/python/triton_amd.cc

This reverts commit ebb065f2e54d55a1f7ef80e1e0dababed8991f67.
On MI300, test_dot(32, 32, 128, 16, False, True, 'none', 'ieee', 'float32', 'float32', 1, 1, 'cuda') failed due to this commit. We'll re-enable InReg attribute after we figured out the reason for the failure.
Some observations
- It passes if we change num_warps from 16 to 8
- It passes if we change K from 128 to 64
- It passes if we only add `InReg` to 4 kernel args. (5 will fail)

Revert "[AMD] Hint the compiler to preload kernel arguments (#3632)"

---

python/tutorials/02-fused-softmax.py

Smaller shapes only needs up to `n_rows` number of threads.

[TUTORIAL][softmax] Avoid creating exessive threads for small shapes.

---

python/test/unit/language/test_core.py
python/triton/language/semantic.py

We hacked scalar tensor's `__bool__` method so that `if (scalar tensor)` can be executed in the interpreter mode.
https://github.com/openai/triton/blob/main/python/triton/runtime/interpreter.py#L700
But scalar tensors shouldn't be evaluated in `semantic.py`.
We could have `tl.load(..., mask=tl.tensor([False]), other=tl.tensor([1.0])`. It is still valid. Only when `mask=None, other!=None` it is invalid.
Without this PR, `not tl.tensor([False])` is evaluated as True and raises the wrong `ValueError`. 
So we should instead check if the tensor is None or not.

[INTERPRETER] Fix scalar mask when the value is False 

---

include/triton/Conversion/TritonGPUToLLVM/Utility.h
lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp
test/Conversion/dedup-by-constancy.mlir

Revert "Disable linear layouts. (#3867)"
This reverts commit 987dd045c0af345d26f98dcd451189ef47646030, with a fix for
the breakage (which was caused by the fact that order of argument evaluation in
C++ is undefined).

Re-enable linear layouts.

---

include/triton/Conversion/TritonGPUToLLVM/TargetInfoBase.h
python/test/unit/hopper/test_experimental_tma.py
test/Conversion/tritongpu_to_llvm_hopper.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.h
third_party/nvidia/backend/driver.c
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ConvertLayoutOpToLLVM.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.h

When copying from mma layout to swizzled shared layout we can use stmatrix to avoid bank conflicts and reduce the number of instructions.

[BACKEND] Support stmatrix for swizzle distributed to shared

---

python/test/unit/language/print_helper.py
python/test/unit/language/test_subprocess.py
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp

For AMD backend we need to cast the pointer to
i64 in order to pass to the ockl library function.

[backend][amd] Support print pointer and add test

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
python/test/unit/hopper/test_experimental_tma.py
test/Conversion/tritongpu_to_llvm_hopper.mlir
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DecomposeUnsupportedConversions.cpp

Also improve the coverage of TMA load/store by testing multiple block size that will use different swizzling formats.

[BACKEND] Add fallback for TMA used with MMAv2

---

include/triton/Analysis/Allocation.h
lib/Analysis/Allocation.cpp
test/Analysis/test-allocation.mlir

* Increment buffers just past max interference buffer

[Alloc] Fixed alignment for shared memory allocation

---

include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td
lib/Conversion/TritonGPUToLLVM/MemoryOpToLLVM.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
test/Conversion/tritongpu_to_llvm.mlir

Fixing the assert in lowerDistributedToShared to allow rank 1 tensor stores.
Fix for trying to get shared memory base based on the incorrect op (not the alloca).

[BACKEND][TMA] Fixing two bugs related to _experimental_descriptor_store lowering

---

python/src/llvm.cc
third_party/amd/backend/compiler.py
third_party/nvidia/backend/compiler.py

This PR adds target triple (only for AMD backend) to llvm module so that some optimizing passes are aware of the target. 
Without this PR, the following code 
```llvm
%sitofp = sitofp i8 %x to float
%exp2 = call float @llvm.exp2.f32(float %sitofp)
```
will be lowered by the `InstCombine` pass to
```llvm
%1 = sext i8 %x to i32
%ldexpf = call float @ldexpf(float 1.000000e+00, i32 %1)
```
which leads to runtime error since `@ldexp` is not recognized on AMD backend.

[AMD] Add target triple to llvm module during `optimize_module`

---

third_party/nvidia/backend/compiler.py

Follow up to #3910
There's no reason we can't tell llvm to generate an older ptx version than the version we give to ptxas.

[Backend] Decouple ptx version for llvm from ptxas

---

python/tutorials/02-fused-softmax.py

Using the `warmup` interface hides parameter/configure details, and is flexible for supporting different data types.

[TUTORIAL][softmax] Use jit warmup interface for pre-compilation.

---

python/triton/language/standard.py

I noticed that there was an error in the documentation of `swizzle2d` function. Updated it to reflect the true meaning. I hope I am interpreting it correctly!

Small fix in the documentation of swizzle2d

---

include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td
lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
lib/Dialect/TritonGPU/Transforms/Pipeliner/PipeliningUtility.cpp
lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp
lib/Dialect/TritonNvidiaGPU/Transforms/TMALowering.cpp
python/test/unit/hopper/test_experimental_tma.py
test/Conversion/tritonnvidiagpu_to_llvm.mlir
test/TritonGPU/loop-pipeline.mlir
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/BarrierOpToLLVM.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp

Allow re-using barriers for multiple copies to reduce the number of barriers op.

[BACKEND] Optimize TMA barriers when pipelining

---

third_party/proton/csrc/lib/Context/Python.cpp
third_party/proton/test/test_profile.py

We should return the call path from the root to the leaf by reversing the unwound frames

[PROTON] Fix python call path

---

third_party/amd/python/triton_amd.cc

Follow-up to #3933.
This might be copied from llvm/lib/Target/AMDGPU/AMDGPUAsmPrinter.cpp.
`setUseAssemblerInfoForParsing` was only used for -mattr=dumpcode and
should not be needed here.
The llvm-project plan is to continue improving the integrated assembler
and remove `setUseAssemblerInfoForParsing`.
While here, drop the byte-order mark.

[backend][amd] Remove unneeded setUseAssemblerInfoForParsing

---

lib/Conversion/TritonGPUToLLVM/FuncOpToLLVM.cpp
python/src/llvm.cc
python/test/unit/language/test_core.py
python/triton/runtime/autotuner.py
python/triton/runtime/interpreter.py
third_party/amd/backend/compiler.py
third_party/nvidia/backend/compiler.py

<git-pr-chain>
1. Add maxnreg kernel config.
Like num_stages and num_warps, this tunes the generated kernel, controlling the
maximum number of registers that one thread can consume.
1. Don't pass maxnreg to the kernel if it's None.
1. Add maxnreg to interpreter reserved_kws
1. Add debugging printfs for AMD
1. Don't use check_cuda_only, which does not skip HIP.
1. Use linkage to find kernel functions
1. 👉 #3944 👈 **YOU ARE HERE**

Add maxnreg kernel config.

---

python/test/unit/language/test_core.py

Reduce usages of `check_cuda_or_hip`, so that more tests can be run for downstream backends by default.

[CI] Reduce usages of `check_cuda_or_hip`

---

python/tutorials/03-matrix-multiplication.py

Correct a few issues in example code for the naive (row-major) ordering. I verified the corrected code using `torch.allclose()`.

[docs] Fix comment in 03-matrix-multiplication.py

---

include/triton/Conversion/TritonGPUToLLVM/Utility.h
third_party/nvidia/lib/NVGPUToLLVM/NVGPUToLLVMPass.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/WGMMA.cpp
unittest/Conversion/TritonGPUToLLVM/DumpLayout.cpp
unittest/Conversion/TritonGPUToLLVM/EmitIndicesTest.cpp

<git-pr-chain>
1. Emit code so LLVM knows the range of `threadid`.
This recovers a bit of performance lost from linear layouts, by letting LLVM
optimize code better.
1. Work around ptxas bug.
1. 👉 #3956 👈 **YOU ARE HERE**

Emit code so LLVM knows the range of `threadid`.

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td

This commit updates the Triton GPU attribute docs to be more clear. Also along the way fixed some style issue.

Improve Triton GPU attribute documentation

---

include/triton/Conversion/TritonGPUToLLVM/Utility.h
include/triton/Dialect/TritonGPU/IR/Dialect.h
lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/ScanOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/Utility.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
python/test/unit/language/test_core.py
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp

Hopper forces a [0,1] order of warps for mma_v3 layouts
(https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#matrix-fragments-for-wgmma-mma-async-m64nnk8) while keeping a [1,0] order for threads so these two things have to be requested separately.
This resolves https://github.com/triton-lang/triton/issues/3467

Fix warp order calculations for MMA_V3 layouts.

---

.github/workflows/integration-tests.yml
.github/workflows/integration-tests.yml.in

I added -vvv to our build and pytest calls because occasionally the build or
test would hang, and without -vvv it's hard to tell what's going on.
OTOH -vvv is super noisy normally, and the github web UI does not handle long
logs super-well.
One possibility is to pass -vvv only when you enable github logging.  But since we don't hit hangs very often, it's simpler just to remove -vvv entirely.

[CI] Don't pass -vvv to CI builds

---

lib/Analysis/Utility.cpp
test/TritonGPU/amd/accelerate-amd-matmul.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/WMMA.cpp
third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp

- Fixed int8 tests for Navi31
- Generate wmma instructions for int8 or int4 operands
- Convert operands to fp32 if initial type more than int8
- Convert result back to initial type after dot
- Add lit tests

[AMD] Support int DotOp for RDNA3

---

python/tutorials/05-layer-norm.py

1. Based on the formula and the actual computation code, the `B` and `eps` are *not* used in `def _layer_norm_bwd_dx_fused` and are thus removed for clarity.
2. Some other minor clean-ups.
Changes have tested on GPU, execution parity.

[TUTORIALS] Minor update and clean up the tutorial05

---

include/triton/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVMBase.h
include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
python/test/unit/language/test_core.py
test/Conversion/amd/dedup-by-constancy.mlir

This PR fixes the following two issues
1. `getContigPerThread()` for sliceLayout should erase the `dim` after getting the vector from its parent
2. `maybeDeduplicate()` should use `getContigPerThread()` instead of `getSizePerThread()` 
Note that `sizePerThread` and `contigPerThread` are the same for blocked layout and sliceLayout with blocked layout as parent. But they are different for mfma layout. Using sizePerThread in maybeDeduplicate causes an issue when we do masked store with mfma layout. Because the `constancy` is not adjusted properly, mask values that are not supposed to be duplicated are duplicated, which leads to out-of-bound memory access.

[AMD] Fix an issue with deduplication with mfma layout

---

test/TritonGPU/amd/amd-stream-pipeline.mlir
third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp

The iteration in the Epilogue of the pipelined loop was starting from the upper bound of the **non-pipelined** loop. if the original loop was:
```
for k = 0:K:
%stage0[k] = f(%in[k])
%stage1[k] = g(%in[k])
```
This should be pipelined to:
```
// Prologue
%stage0[0] = f(%in[0])
for k = 0:K-1:
%stage0[k+1] = f(%in[k+1])
%stage1[k] = g(%in[k])
// Epilogue
%stage1[K-1] = g(%in[K-1])
```
While the epilogue was emitted like:
```
%stage1[K] = g(%in[K])
```
Because the upper bound of the original loop was used.

[AMD] Fix stream pipeline epilogue upper bounds

---

python/triton/language/extra/hip/libdevice.py
third_party/amd/lib/TritonAMDGPUToLLVM/BuiltinFuncToLLVM.cpp

This PR adds `fast_dividef` extra op to the hip backend

[AMD] enabled `fast_dividef` op for the amd backend

---

python/setup.py
third_party/proton/README.md

Proton is a third_party component and not necessarily always needed for everybody. So allow disabling building it with an environment variable.

[BUILD] Allow disabling Proton from Python build

---

third_party/amd/backend/include/roctracer/roctracer_hip.h

This header contains a bunch of `operator<<` definitions for print effectively. We don't use them. It's not good to touch public headers but the problem is it uses `__locale_struct` which is missing on macOS and breaks builds.

[PROTON] Drop hip_ostream_ops.h in roctracer headers

---

python/triton/runtime/autotuner.py

This caching seems to be responsible for some CUDA OOMs we encountered in Meta-internal builds. I haven't got a reduced repro, but this change does seem to fix things. My hypothesis is that the cached stream is causing the memory allocated for the graph to be retained.

[AUTOTUNER] Don't cache benchmarking stream

---

include/triton/Conversion/MLIRTypes.h
lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp

There was a bug in lowering `arith.constant` where only "regular" FP types and BF16 were allowed as initializers (we couldn't even lower 0 init for FP8).
I have included all the FP8 types in the `isFloat` helper. Let me know if it makes sense.

Allow FP8 types in `arith.constant` initializers

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
lib/Dialect/TritonGPU/Transforms/Pipeliner/PipeliningUtility.cpp

Two fixes around pipelining `if`s:
* Schedule prologue and epilogue dependencies in stage order - we should always do that (see `scheduleDependencies`) otherwise we may end up with incorrect schedule
* Properly handle if predication (needed if there are memory ops in the `if`)

`If` pipelining fixes

---

.github/workflows/integration-tests.yml
.github/workflows/integration-tests.yml.in

https://github.com/LLNL/hatchet/pull/125#issuecomment-2130102636
Previously `no-build-isolation` is used to take advantage of the incremental build.
Now that we have containerized the CI, it probably doesn't help much.

[CI] Remove `--no-build-isolation`

---

python/triton/language/core.py

The `tl.dot` docs have a couple of typos and seem to be missing mention of lower precision dtypes
I'm not sure these changes are complete (and not really sure what is going on with `input_precision`, so please double check)

[DOCS] fixes to tl.dot

---

python/test/unit/language/test_core.py
python/triton/compiler/code_generator.py

When processing loops we were incorrectly setting all the local def as livein.
Since part of the code assumes that only livein variable can be loop carried dependency that was causing a mismatch in the logic. Change it to enforce that local def not livein cannot be loop carried.

[FRONTEND] Fix wrong livein set in loop codegen

---

include/triton/Dialect/TritonGPU/Transforms/Passes.td
include/triton/Dialect/TritonGPU/Transforms/Utility.h
lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
python/src/passes.cc
test/TritonGPU/accelerate-matmul.mlir
test/TritonGPU/loop-pipeline-hopper.mlir
test/TritonGPU/pipeline-hopper-remove-wait.mlir
third_party/nvidia/backend/compiler.py

The TritonGPUPipeline pass has unused pass options and the TritonGPUAccelerateMatmul pass option could instead be read from the module attributes, where the data already exists. The goal is to reduce redundancy.

Remove redundant options from passes

---

third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/MFMA.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp
third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp

These changes are not necessary for OpenAI's build setup, but they are marginal improvements. We are interested in merging those to simplify our integration process.

[AMD] Fix clang warnings in AMD backend.

---

python/src/ir.cc

We already raise exceptions in other cases but where missing this one path.
This extends what was added in https://github.com/triton-lang/triton/pull/3221

[FRONTEND] Add missing check for out of range func arg

---

third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.cpp

print strings that don't end with '\0' may cause invalid mem access

[BACKEND] Append '\0' for `__assertfail`'s str param

---

third_party/amd/backend/compiler.py

I was stuck for some time trying to get Triton to run because ROCm is installed in a different path on our HPC system. I only realized the environment variable existed when I looked at Triton's code. A note about the TRITON_HIP_LLD_PATH in the exception message would have been very helpful.

Adding note regarding TRITON_HIP_LLD_PATH environment variable

---

include/triton/Conversion/TritonGPUToLLVM/TargetInfoBase.h
lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.h
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.h

The reduce lowering pattern, ReduceOpConversion, calls the backend target-specific interface to generate a high-performance operation for horizontal warp reduction across lanes. If the backend target doesn't support this, it falls back to the common horizontal warp reduction with the ShuffleXor operation, which might be suboptimal.
There is a parameter interleave in warpReduce that is not defined in the TargetInfoBase interface warpReduce.
The backend may generate incorrect code without information about how to reduce the value across lanes with an interleave stride.
This issue doesn't impact the in-tree backends, AMD and NV GPU.
- The AMD backend always uses ShuffleXor for horizontal warp reduction.
- The NV backend only generates high-performance horizontal warp reduction when …

Add parameter `interleave` to the `warpReduce` interface of `TargetInfo` which was missed.

---

include/triton/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVMBase.h

The logic of maybeDeduplicate doesn't seem to handle nv mma layouts. Fix the check we have to prevent it to be used for layouts that are nv mma or sliced of nv mma

[BACKEND] Fix workaround for unsupported cases in maybeDeduplicate

---

python/triton/runtime/autotuner.py

The dictionary merge operator was introduced in Python 3.9 and unfortunately PyTorch still supports 3.8. I think for this use case there is no downside to unpacking, other than that it's a bit ugly.

Use dictionary unpacking instead of merge operator for python 3.8 compatibility

---

python/test/unit/runtime/test_bindings.py
python/triton/runtime/jit.py

fix visit_call builtin func judge, so python builtin funcs can be used in triton func def

[FRONTEND] Fix builtin function ast visit

---

lib/Dialect/TritonGPU/Transforms/Prefetch.cpp
test/TritonGPU/prefetch.mlir

While analyzing performance of tf32 gemm on A100,  I found a surprising number of stalls on ldmatrix.  Looking at the ttgir:
```
local_load
tt.dot
tt.dot
async_copy, etc...
local_load
```
suggested that the prefetching wasn't really helping to hide latency
Instead, we want to delay the second `dot` until after the second `local_load`:
```
local_load
tt.dot
async_copy, etc...
local_load
tt.dot
```
With this scheduling tweak tf32 perf is more or less on par with cuBLAS:
```
matmul-performance-fp32:
M       N       K      cublas  triton prev    triton now
0    256.0   256.0   256.0    2.502568     3.057073      2.953735
1    384.0   384.0   384.0    7.643507     8.406043      8.759763
2    512.0   512.0   512.0   18.078896    14.413416     15.477137
3    640.0   640.0   640.0   30.284659 …
```

Improve scheduling of prefetched dot

---

python/test/unit/language/test_core.py
python/triton/language/core.py

Updated 1 test in test_core.py and 2 docs in core.py.
[`python/test/unit/language/test_core.py`](diffhunk://#diff-ac90f00a03feff6747a9c9ac5af1f44bb67e56bf911e05db71a2c1e818e897e7R1097-R1099): The `kernel` function has been updated to include a test for the `trans` function without specifying the `dims` parameter.
[`python/triton/language/core.py`](diffhunk://#diff-1d96a0ed473569188c00d6e16c54dd7050e0a66040438ac630c889aef7cbbbe8L1182-R1182): The `TRITON_MAX_TENSOR_NUMEL` constant in the `arange` function has been updated to be consistent  with https://github.com/triton-lang/triton/blob/03b84666a1991a0addd6b0d80c911de98b7e6c31/python/triton/language/core.py#L19. 
[`python/triton/language/core.py`](diffhunk://#diff-1d96a0ed473569188c00d6e16c54dd7050e0a66040438ac630c889aef7cbbbe8L1271-R1272): …

[DOCS] Fix docs and improve a test case

---

lib/Dialect/TritonGPU/IR/Dialect.cpp
test/Conversion/tritongpu_to_llvm.mlir

`getThreadsPerWarp` is used to compute the master thread owning the reduction result inside a warp. Previously it only supported 2D slice layout. I'm fixing that by propagating the thread count for the removed dimension to the nearest dimension after removal.

[BACKEND] Fix getThreadsPerWarp for MD sliced encoding

---

python/triton/language/core.py
python/triton/runtime/interpreter.py

operand should be casted to the type provided by the user (ie, either `int64` or `uint64`) rather than always `uint64`

[INTERPRETER] fixed `int_to_ptr` / `ptr_to_int` bug

---

python/triton/language/core.py

1. Add 3d descriptions
2. Add `acc` variable description and supported types.

[DOC] Improve `tl.dot` documentation

---

lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp

Generalize a bit accelerate matmul pass to prepare for future work.
* Make sure we have the right list of supported MMA ops in getMMAVersionSafe.
* Return failure if BlockedToMMA if the version is currently not handled.

[BACKEND][NFC] Simple refactor of accelerate matmul

---

python/tutorials/05-layer-norm.py

1. The tensor _dw, _db should be initialized to zero (instead of uninitialized as torch.empty) since they are for `read` in line https://github.com/lancerts/triton/blob/main/python/tutorials/05-layer-norm.py#L182
2. replace the hard coded device.
contributor (less than 3 PRs merged) we ask that you fill out the following
checklist and include it in your PR description.**
Fill out the checklist by replacing `[ ]` with `[x]`.
Fix tutorial 05, passed the execution of tutorial 05 …

[TUTORIAL] Minor fix on tutorial-05

---

.github/workflows/integration-tests.yml
.github/workflows/integration-tests.yml.in

Otherwise when there's a problem (such as a crash) we don't get stdout from the
test.

Run pytest with -s.

---

.github/workflows/integration-tests.yml
.github/workflows/integration-tests.yml.in

About 1 out of 10 runs of the CI test have failed tests in test_subprocess.py on AMD backend. This PR disables this test until we find a solution.

[AMD] Disable test_subprocess.py on AMD backend

---

python/test/unit/language/test_core.py
python/triton/language/core.py

* python/test/unit/language/test_core.py::test_vectorization is improved to actually compare the src and dst. There was no value comparison before.
* [`python/triton/language/core.py`](diffhunk://#diff-1d96a0ed473569188c00d6e16c54dd7050e0a66040438ac630c889aef7cbbbe8L1327-R1328): The comment in the `cat` function has been updated to clarify that the current implementation only supports `can_reorder=True`. 
If set False or leave as default, compilation error.
Due to 
https://github.com/triton-lang/triton/blob/b0faf9b202846434bdd67d7ffec17c8924abe316/python/triton/language/semantic.py#L571
* python/triton/language/core.py: The `cache_modifier` parameter in the `load` function now includes more detailed information about the accepted values and their meanings, linking to external …

[DOC] Improve core doc and test_core

---

lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp
python/test/unit/language/test_core.py
unittest/Dialect/TritonGPU/LinearLayoutConversionsTest.cpp

These are all passing (with one small change to the conversion routine) now that we have linear layouts.

Enable previously-failing convert2d tests.

---

lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp
python/test/unit/language/test_core.py
unittest/Dialect/TritonGPU/LinearLayoutConversionsTest.cpp

These tests work now that we use linear layouts in codegen.

Enable previously-broken reduction tests.

---

python/src/main.cc
unittest/Analysis/UtilityTest.cpp
unittest/Conversion/TritonGPUToLLVM/EmitIndicesTest.cpp
unittest/Conversion/TritonGPUToLLVM/PTXAsmFormatTest.cpp
unittest/Dialect/TritonGPU/DialectTest.cpp
unittest/Dialect/TritonGPU/LinearLayoutConversionsTest.cpp
unittest/Dialect/TritonGPU/SwizzleTest.cpp
unittest/Tools/LinearLayoutTest.cpp

I noticed that triton-opt printed a stack but our Python and C++ unit tests
didn't.  After some digging I figured out how LLVM was turning on stacktraces.
This PR turns them on for our C++ unit tests and Triton when run from Python
(!!).

Print a stacktrace on fatal signal.

---

third_party/proton/csrc/include/Driver/GPU/HipApi.h
third_party/proton/csrc/include/Driver/GPU/HsaApi.h
third_party/proton/csrc/lib/Driver/GPU/HipApi.cpp
third_party/proton/csrc/lib/Driver/GPU/HsaApi.cpp
third_party/proton/csrc/lib/Profiler/RoctracerProfiler.cpp

Roctracer reports (global) agent ids for the location of async ops, e.g. kernels and copies.
The profiler would be better suited with gpu indexes (zero based).
Created a mapping function to apply to values stored in KernelMetric::DeviceId.
Caveat: if devices are hidden using HIP_VISIBLE_DEVICES then the hip device id, e.g. via hipGetDevice()/hipSetDevice(), will not match the reported unfiltered id.  Additional support in hip will be needed to map through the filtering correctly.

[PROTON] Roctracer: convert agent id to gpu id for gpu ops

---

lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
test/TritonGPU/combine.mlir

In the current implementation, when backward rematerialization encounters a loop argument that has already been rematerialized, the process short-circuits the collection of yield operations, leaving the value in the slice. However, if another loop argument is present in the same slice, the loop is collected again, resulting in the duplication of the first argument without generating the corresponding yield.
To address this issue, this fix removes values from the slice that are skipped during collection, ensuring they are not reduplicated. This adjustment ensures that the number of yield operands and loop iter_args remain synchronized.
cc @peterbell10 
you!).  To help us review your code more quickly, **if you are …

[BACKEND] Prevent for/yield argument number drift

---

include/triton/Dialect/Triton/IR/Traits.h
lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp

Remove some unnecessary restrictions on code related to DotLike.
Only Hopper Dot can take shared memory operands so remove some redundant checks.

[NFC] Generalize some DotTrait handling

---

python/triton/language/extra/hip/libdevice.py

These math functions are used in pytorch inductor but missing in the current list of hip libdevice.

[AMD] Add more math functions in libdevice

---

python/test/unit/language/test_core.py
python/test/unit/operators/test_flash_attention.py
python/test/unit/tools/test_aot.py

This PR skips 13 tests which currently fail on GPUs with less than 128 KB of shared memory per SM, including the RTX 4090 (compute capability 8.9) and other consumer GPUs. These tests pass on datacenter GPUs with compute capabilities 8.0 (A100), 8.7 (some Jetson products), and 9.0 (H100), which have 128 KB or more of shared memory per SM. 
instructions necessary to exercise the bug.  (Usually running Python code

Skip 13 tests that fail on GPUs with less than 128 KB of shared memory

---

docs/python-api/triton.testing.rst
python/test/unit/language/test_core.py
python/triton/language/core.py
python/triton/testing.py

Update the docs and a test case to cover more dtypes.
instructions necessary to exercise the bug.  (Usually running Python code

[DOCS] Improve docs and minor fixes for testing.py and core.py

---

include/triton/Tools/LinearLayout.h
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/Utility.cpp
lib/Tools/LinearLayout.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp
unittest/Tools/LinearLayoutTest.cpp

<git-pr-chain>
Resolve ambiguity differently in LinearLayout::invertAndCompose.
For example, suppose we're computing C = A.invertAndCompose(B) and we have
A(thread=1, block=0) = 1
A(thread=2, block=0) = 2
A(thread=0, block=1) = 0
B(thread=1, block=0) = 2
B(thread=2, block=0) = 1
B(thread=0, block=1) = 0
we will now choose
C(thread=1, block=0) = (thread=2, block=0)
C(thread=2, block=0) = (thread=1, block=0)
C(thread=0, block=1) = (thread=0, block=1),
whereas before we would have chosen C(thread=0, block=1) = (thread=0, block=0).
The new behavior is better because it means we prefer to load data from the
same block, instead of the old behavior where we would load data from the
lowest-valued possible block.
1. 👉 #4115 👈 **YOU ARE HERE**

Resolve ambiguity differently in LinearLayout::invertAndCompose.

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Dialect/TritonGPU/IR/Dialect.cpp
test/TritonGPU/invalid-attributes.mlir

This guards us against unsupported cases without asserts. Along the way slightly improved the MFMA/WMMA doc a bit.

[AMD] Add basic verification to MFMA encoding

---

python/test/unit/operators/test_matmul.py
python/test/unit/runtime/test_cublas.py

Enable FP8 matmul tests on NVIDIA Ada GPUs (compute capability 8.9). These tests now pass with CUDA 12.4 and PTX ISA 8.4.
Issue #3041 
instructions necessary to exercise the bug.  (Usually running Python code

Enable FP8 matmul tests on NVIDIA Ada GPUs

---

include/triton/Conversion/TritonGPUToLLVM/TargetInfoBase.h
include/triton/Conversion/TritonGPUToLLVM/Utility.h
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.h

We have identified a 20% perf regression in our downstream flash attention perf kernel after switching to linear layout. Initial analysis shows register pressure is increased to cause spills. Further analysis is still ongoing.
So this commit introduces a minimal way to selectively disable linear layout only on AMD backend to avoid affecting NVIDIA backend while contining bring it up on AMD side.

[BACKEND][AMD] Disable linear layout due to perf regression

---

include/triton/Tools/Sys/GetEnv.hpp
python/src/llvm.cc
python/src/main.cc

Used to disable stacktrace handler registration in the python module.
fixes #4129
The stacktrace handler disrupts normal signal propagation, introduce an environment variable to disable registration at import time.
- …

[FRONTEND] Add TRITON_DISABLE_PYTHON_STACKTRACE envvar

---

test/Conversion/amd/tritongpu_wmma_dot_to_llvm.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/WMMA.cpp

- Pack bf16 elements to int16 vectors;
- Add a lit test;
- BF16 testcases from test_core.py::test_dot are passed for now;

[AMD][gfx11] Fix BF16 wmma instr generation

---

include/triton/Conversion/TritonGPUToLLVM/TargetInfoBase.h
include/triton/Conversion/TritonGPUToLLVM/Utility.h
lib/Conversion/TritonGPUToLLVM/Utility.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.h
third_party/amd/lib/TritonAMDGPUToLLVM/Utility.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/Utility.h
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.h
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/Utility.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/Utility.h

<git-pr-chain>
s/ConversionPatternRewriter/RewriterBase/ in utils (NFC)
You can't create a ConversionPatternRewriter in C++ unit tests, so this means
that anything which is touched from a C++ unit test cannot transitively touch
anything which uses a ConversionPatternRewriter.
This is a simple search+replace, there's no functional difference between these
types for our purposes.
1. 👉 #4140 👈 **YOU ARE HERE**
1. #4141

s/ConversionPatternRewriter/RewriterBase/ in utils (NFC)

---

lib/Dialect/TritonGPU/Transforms/OptimizeThreadLocality.cpp
test/TritonGPU/optimize-locality.mlir

If definingOp for the reduce operands is nullptr, bail out instead of seg fault.

thread-locality: Do not segfault for reduce on forOp arguments

---

python/test/unit/language/test_core.py

There is a precision bug in test_core.py::test_dot for chain-dot cases.
Inside the kernel, it does fp8xfp8->fp32 dot-product (`z=xy`) first.
Then, for chain-dot, it casts the output `z` back to fp8 and do the fp8xfp8->fp32 dot-product again `z=zw`.
However, the reference numpy computation *does not* cast the intermediate output `z_ref` to fp8.
Therefore, the second dot-product becomes fp32xfp8->fp32, whose result is different from the kernel output.
In some fp8 setup (float8e4nv in our case), it sometimes causes a test failure due to this precision issue.
I have fixed the reference computation to reduce the precision of the intermediate output. …

[TEST] Fixing precision bug in fp8 test_dot

---

python/tutorials/09-persistent-matmul.py

Setting fp16 as a default mode, as fp8 is compatible only with sm90.
Disabling TMA test for sm80 and below.
There is still the issue of shapes not fitting into shmem for some platforms, to be addressed as a follow-up.

Fixes for running the 09-persistent-matmul tutorial on SM80

---

lib/Analysis/Allocation.cpp
lib/Analysis/Utility.cpp
test/Conversion/amd/math-denorm-handling.mlir
test/Conversion/amd/mfma-shortcut.mlir
third_party/amd/backend/compiler.py
third_party/amd/include/TritonAMDGPUToLLVM/Passes.h
third_party/amd/include/TritonAMDGPUToLLVM/Passes.td
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/PatternTritonGPUOpToLLVM.h
third_party/amd/lib/TritonAMDGPUToLLVM/TritonGPUToLLVM.cpp
third_party/amd/python/triton_amd.cc

These need to be in this order to apply cleanly.
Cherry pick #3816 and #3790 for release/3.0.x.

[AMD] Move MFMA shortcut check to not compute scratch buffer shape if it is not needed

---

include/triton/Dialect/TritonGPU/Transforms/Passes.td
include/triton/Dialect/TritonGPU/Transforms/Utility.h
lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
lib/Dialect/TritonGPU/Transforms/Prefetch.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
python/src/passes.cc
test/TritonGPU/accelerate-matmul.mlir
test/TritonGPU/loop-pipeline-hopper.mlir
test/TritonGPU/pipeline-hopper-remove-wait.mlir
third_party/nvidia/backend/compiler.py

These need to be in this order to apply cleanly
Cherry pick #4000 and #4015 for release/3.0.x

Remove redundant options from passes (#4015)

---

python/triton/compiler/code_generator.py

While developing a kernel, I was given the error message "AssertionError()" without much helpful context on how to proceed with debugging. I could only solve it by understanding that part of the triton source code and spending half a day.
That's why I'm (1) adding an error message to this part of the code, and (2) making the error message above it clearer (like it is in visit_While).
This should allow the end user to debug this error without the need to dive into the triton source code.
---
Complete the …

Tiny change: Added/Improved error message in visit_For

---

python/test/unit/hopper/test_experimental_tma.py
python/test/unit/language/test_pipeliner.py
python/triton/tools/experimental_descriptor.py
python/tutorials/09-persistent-matmul.py
third_party/nvidia/backend/driver.c

We need to potentially flush the TMA cache when re-using TMA memory. In order to make it safe we flush the cache for every TMA descriptor created.

[FRONTEND] Wrap experimental TMA descriptor creation into a helper

---

include/triton/Conversion/TritonGPUToLLVM/TargetInfoBase.h
include/triton/Conversion/TritonGPUToLLVM/Utility.h
include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/Utility.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
python/test/unit/language/test_core.py
test/Conversion/amd/tritongpu_wmma_dot_to_llvm.mlir
test/TritonGPU/invalid-attributes.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandWMMA.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/WMMA.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.h
third_party/proton/csrc/include/Driver/Device.h
third_party/proton/csrc/include/Driver/GPU/HipApi.h
third_party/proton/csrc/include/Driver/GPU/HsaApi.h
third_party/proton/csrc/include/Profiler/CuptiProfiler.h
third_party/proton/csrc/include/Profiler/GPUProfiler.h
third_party/proton/csrc/include/Profiler/RoctracerProfiler.h
third_party/proton/csrc/include/Utility/Atomic.h
third_party/proton/csrc/lib/Driver/GPU/CudaApi.cpp
third_party/proton/csrc/lib/Driver/GPU/HipApi.cpp
third_party/proton/csrc/lib/Driver/GPU/HsaApi.cpp
third_party/proton/csrc/lib/Profiler/CuptiProfiler.cpp
third_party/proton/csrc/lib/Profiler/RoctracerProfiler.cpp
third_party/proton/proton/viewer.py
third_party/proton/test/example_cuda.json
third_party/proton/test/example_hip.json
third_party/proton/test/test_viewer.py

Cherry picks for release/3.0.x
General:
- e8bc45df9 [BACKEND][AMD] Disable linear layout due to perf regression (#4126)
- 9a0a7c2cc [AMD] Add basic verification to MFMA encoding (#4117)
for RDNA:
- 100e2aaca [AMD][WMMA] Support dot3d (#3674)
- 4a1ea8e10 [AMD][gfx11] Fix BF16 wmma instr generation (#4135)
Proton HIP PRs:
- 328b86d72 [PROTON] Refactor GPU profilers (#4056)
- 60613fb35 [PROTON] Roctracer: convert agent id to gpu id for gpu ops (#4090)
- c1776fadc [PROTON][AMD] Add Proton HIP GPU Utilization Metrics (#4119)

[RELEASE] [AMD] Additional AMD cherry-picks

---

python/src/llvm.cc

The LLVM signal handler appears to supersede the Python signal handler. Calling PyErr_SetInterrupt is equivalent to raising SIGINT and ensures the program terminates after the stack trace is printed. This Python function is also thread safe. It might be better to raise the original signal, but LLVM does not appear to pass the signal to its handler when captured, and the Python function to raise a specific signal is only supported in 3.10+.
Using the repro from #4129:
<details><summary>Before this change:</summary>
```
$ python repro.py abort                                                                                               
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0 …
```

Use custom stacktrace signal handler w/ python interrupt

---

lib/Tools/LinearLayout.cpp

When running [convert_blocked1d_to_slice0](https://github.com/triton-lang/triton/blob/0ba5f0c3cd029d5c3d1f01b9bf29dac32c27345e/test/Conversion/tritongpu_to_llvm.mlir#L924) Triton ends up computing a rank of a matrix with 0 columns during linear layout lowering, which trips up f2reduce, and causes undefined behavior, detectable through [UBSAN](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html).
Fix this by returning the rank (0) early in these cases, without calling f2reduce.
<details><summary>Stack trace</summary>
<p>
```
third_party/triton/third_party/f2reduce/f2reduce.cpp:421:30: runtime error: shift exponent 18446744073709551615 is too large for 64-bit type 'unsigned long long'
#0 0x556ee2fea3be in inplace_rref_small third_party/triton/third_party/f2reduce/f2reduce.cpp:421:30 …
```

Avoid underflow in f2reduce

---

lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
test/TritonGPU/combine.mlir

We shouldn't propagate to the `operand` of a while op, which contradicts the **forward** propagation rule.
In addition, this PR also changes the queue implementation from *vector* to *deque* when rewriting regions to ensure parent regions are visited first.

[TRANSFORM] Fix while op layout propagation

---

README.md
python/src/ir.cc
python/test/unit/test_debug_dump.py

A pytorch run can consist of lots of triton kernel runs. Adding the functionality to allow for dumping the IRs for a particularly interesting kernel.

[FrontEnd] Allow MLIR dumping a single kernel

---

python/triton/compiler/compiler.py

Truncate cached file names to 150 letters when names are too long to avoid overlong file paths that are beyond the system limit (255).

[FrontEnd] Truncate cached file names when names are too long

---

test/Conversion/amd/amd-convert-builtin-func.mlir

This is a follow-up to https://github.com/triton-lang/triton/pull/4176#issuecomment-2182949566
I am now counting the number of blocks with (17) and without (31) block merging. I double checked to make sure this does not pass when we use an aggressive region simplification strategy.

Add a more meaningful check to make sure we are not merging blocks

---

include/triton/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVMBase.h

The workaround introduced in https://github.com/triton-lang/triton/pull/4048 "forgot" to skip mfma layout.

[AMD] Skip mfma layout in maybeDuplicate

---

python/triton/language/core.py

1. f-string cannot be used as docstrings in Python.
2. URLs should follow the reStructuredText format.
3. Code snippets in a code block should be indented.
Tested and passed on a local machine.

[DOCS][NFC] Fix doc formatting problems

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
test/TritonGPU/loop-pipeline.mlir

During some previous refactoring we changed the logic and started pipeling cases that had incompatible shared encoding. This was missed because one of the lit test had not been updated :(

[BACKEND] Fix regression in pipeliner pre-checks.

---

third_party/amd/lib/TritonAMDGPUTransforms/OptimizeEpilogue.cpp

`val.getDefiningOp()` can return `nullptr`. In this case, we must fail the `BypassEpilogueSMEM` rewrite pass for the given op. This prevents run-time crashes.
Closes https://github.com/ROCm/triton-internal/issues/148

[AMD] quick fix of `BypassEpilogueSMEM` rewrite

---

README.md

Document the existence of `TRITON_HOME` environment …

Document TRITON_HOME

---

python/test/unit/language/test_core.py
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.cpp

Recent refactoring broke i1 shared memory load.

[BACKEND] Fix regression in i1 reduction

---

lib/Analysis/AxisInfo.cpp
test/Analysis/test-alignment.mlir

Divisibility does not ensure that a value is not 0 therefore we cannot use divisibility as a minimum shifted values.

[BACKEND] Fix divisibility analysis for shift ops

---

include/triton/Conversion/MLIRTypes.h
lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp
python/triton/language/semantic.py
test/Conversion/tritongpu_to_llvm_hopper.mlir

To unblock the compilation of kernels like below which don't operate arithmetically on FP8.
```
@triton.jit
def triton_poi_fused__scaled_mm__to_copy_constant_pad_nd_lift_fresh_2(in_ptr0, out_ptr0, xnumel, XBLOCK : tl.constexpr):
xnumel = 400624
xoffset = tl.program_id(0) * XBLOCK
xindex = xoffset + tl.arange(0, XBLOCK)[:]
xmask = xindex < xnumel
x0 = xindex % 784
x1 = (xindex // 784)
x2 = xindex
tmp0 = x0
tmp1 = tl.full([1], 769, tl.int64)
tmp2 = tmp0 < tmp1
tmp3 = tl.load(in_ptr0 + (x0 + (769*x1)), tmp2 & xmask, other=0.0)
tmp4 = tmp3.to(tl.float8e4nv)
tmp5 = tl.full(tmp4.shape, 0.0, tmp4.dtype)
tmp6 = tl.where(tmp2, tmp4, tmp5)
tl.store(out_ptr0 + (x2), tmp6, xmask)
```

Support FP8 constant

---

third_party/proton/csrc/lib/Profiler/CuptiProfiler.cpp

Casting from a generic `void *` object to other types should use `static_cast` instead of `reinterpret_cast`

[PROTON] Fix improper use of `reinterpret_cast`

---

third_party/nvidia/include/NVGPUToLLVM/NVGPUToLLVMPass.h
third_party/nvidia/lib/NVGPUToLLVM/NVGPUToLLVMPass.cpp

OpenXLA would like to reuse code from `NVGPUOpPatternBase` for Sparsity lowering. Currently this is done by patching `NVGPUToLLVMPass.cpp` to add an extra pattern deriving from `NVGPUOpPatternBase`. Instead, we would like to move this pattern to the downstream OpenXLA repository. 
This change removes the `NVGPUOpPatternBase` base class and exposes the core lowering code as a utility function (`rewriteAsPtxAsm()`) instead. The existing patterns now directly inherit from `mlir::OpRewritePattern` and use this utility function.
I hope that exposing an extra function is acceptable. I tried to balance it with cleaning up the code a bit (e.g., no more CRTP, but of course that's subjective).

[nvgpu] Expose helper code from NVGPU to LLVM lowering (NFC).

---

include/triton/Conversion/TritonGPUToLLVM/TargetInfoBase.h
include/triton/Conversion/TritonGPUToLLVM/Utility.h
lib/Conversion/TritonGPUToLLVM/Utility.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.h

1. Split LinearLayout conversion in block+warp+thread and register parts
2. Move block+warp+thread part out of register loop in emitIndicesUsingLinearLayouts
LLVM optimizes generated IR better and number of required registers is lowered.

Optimize code generated by EmitIndices for LinearLayout

---

python/setup.py
python/triton/runtime/build.py

Enhance triton functionality to allow use of custom cuda toolkit at runtime

---

python/src/ir.cc
python/test/unit/runtime/test_subproc.py
python/triton/compiler/compiler.py

This PR disables multithreading in MLIR context after compilation ends. This is done to safely finalize thread pool implemented in MLIRContext. Not properly finalized thread pool can hang or crash in child process after fork.

Fix conflicting multithreading and fork management

---

test/Conversion/amd/fp_to_fp.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp

**Added missing handling of tt.fp_to_fp in FpToFpOpConversion::createDestOps when type of src operand is bf16 and type of dst operand is fp32.**
When having tt.fp_to_fp with src type bf16 and dst operand of type fp32,
there were following error message:
error: failed to legalize operation 'tt.fp_to_fp' that was explicitly marked illegal
BF16 to FP16 (FP32) was not handled neither in 
FpToFpOpConversion::createDestOps nor in getConversionFunc,
thus conversion is added directly in FpToFpOpConversion::createDestOps, 
similarly, as for the case when source and destination operands are of the same type.
---------------------------------------------------------------------
you!).  To help us review your code more …

[AMD] Fix an issue with lowering of tt.fp_to_fp

---

third_party/amd/backend/driver.py

Previously Triton cannot find the HIP runtime bundled in PyTorch if the wheel
is installed with `--user`. Searching the user site-packages directory may
solve this problem.

[AMD] Search libamdhip64.so in PyTorch user site installation

---

python/test/unit/language/test_core.py
python/tutorials/07-extern-functions.py

1 Updated the doc of 07-extern-functions tutorial
tl.math.fn no longer works in the nightly (following change as a reference)
https://github.com/triton-lang/triton/pull/3172/files#diff-8bb547c8082ddf083d49bdb5e6f126c1cebae899390c95afc0f713229982f516L35
2 Added an example of extern_lib path (just use the default path explicitly to showcase the usage).
3 Added a unit test. In the case of future backward breaking changes of extern math function usage, the unit test should break.
Picked tanh since it is heavily used in gelu.
Executed in cuda.

Update the 07-extern-functions tutorial and include a unit test for extern function

---

python/tutorials/06-fused-attention.py

This PR fixes a simple matplotlib error - if `HAS_FLASH_ATTN` & `torch.float8` is available the color array goes out of possible colors.

Tutorial - 06-fused-attention.py - plotting

---

.github/workflows/integration-tests.yml
.github/workflows/integration-tests.yml.in
python/test/unit/language/test_core.py
python/test/unit/language/test_pipeliner.py

This PR updates CI script to enable integration tests for MI300.
This only enables coverage the same as the MI250 machine.
There is one test failure left as TODO in test_core.py to be
figured out and fixed.

[AMD] Enable integration tests for MI300

---

python/src/ir.cc

Flags used by the CXX compiler during RELWITHDEBINFO …

[BUILD] Fix compilation errors under RelWithDebugInfo

---

test/Conversion/nvgpu_to_llvm.mlir

Add back check to introduce dummy dependency in wgmma.wait. Also move back ops within llvm functions.

[TEST][NFC] Add back check for wgmma wait

---

.github/workflows/documentation.yml
docs/conf.py

Added a `print` statement in `conf.py` for debugging purposes. Apologies for the back-and-forth on this issue.

[CI] Preserve environment variables when building docs

---

include/triton/Conversion/TritonGPUToLLVM/Utility.h
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.cpp

<git-pr-chain>
Make load/storeDShared handle large vectors.
Previously we errored out when given a vector of >4 elements or >128 bits.  Now
we handle this properly by merging elements (e.g. 16xi8 -> 4xi32) or splitting
the vector (e.g. 16xi32 -> four 4xi32 loads/stores).
1. 👉 #4189 👈 **YOU ARE HERE**

Make load/storeDShared handle large vectors.

---

python/tutorials/02-fused-softmax.py
third_party/amd/backend/driver.c

This PR fixes occupancy calculation for AMDGPU so number of waves does not exceed
maximum number of waves that can execute in parallel on a CU. Additionally, 
it fixes number of regular purpose registers available on CU.

[AMDGPU] Fix occupancy calculation in softmax tutorial.

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
test/TritonGPU/loop-pipeline-hopper.mlir

During pipelining operations that do not depend on or being dependent by anchor operations are considered remaining ops and will be scheduled into the last stage. These ops do not present in the existing stages but can be visited by other staged ops. Fixing an ICE when looking for clusters for them.

[BACKEND] Fix an issue with the pipeliner

---

third_party/proton/csrc/lib/Profiler/CuptiProfiler.cpp
third_party/proton/csrc/lib/Session/Session.cpp
third_party/proton/test/test_profile.py

To ensure that metrics from kernels launched before are not attributed to the current active session.

[PROTON] Flush ops before activating sessions

---

include/triton/Dialect/Triton/IR/TritonOps.td
lib/Dialect/Triton/IR/Ops.cpp
test/Triton/combine.mlir
test/Triton/invalid.mlir

Summary: This PR adds a verifier for tt.broadcast primitive to provide early error detection for incorrect usage.
Test Plan: New test
Reviewers: @htyu 
Subscribers:
Tasks:
Tags:
including the …

[IR] Add verifier for tt.broadcast

---

python/tutorials/09-persistent-matmul.py

It looks like the operand pointers are not advanced in the baseline and persistent kernels.

[Tutorial] Fix a pointer not advanced issue in the persistent kernels.

---

python/triton/runtime/cache.py

there've been multiple issues discussing around the `FileNotFoundError` on compilation when `CompiledKernel` is trying to read from the listed ASM files. #2688 #4002 https://github.com/vllm-project/vllm/issues/6103 etc. and there have been some attempts to address it such as #3544 . This PR attempts to explain the root cause and suggest a fix.
When a kernel is being compiled, triton first writes IRs to triton cache dir ([ref](https://github.com/triton-lang/triton/blob/78091647fccb6825ed9956ff7c0300859856d261/python/triton/compiler/compiler.py#L289)). Inside of the write operation, the process first writes it to a temp file unique to the current process (plus a uuid to distinguish between multiple processes with same PID on different hosts sharing the same underlying FS) …

[FRONTEND] let CacheManager write to temp dir instead of temp file

---

test/Conversion/tritongpu_to_llvm.mlir
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ElementwiseOpToLLVM.cpp

This PR removes some special handling for int->bf16 and bf16->int conversions in the TritonNVIDIAGPU->LLVM lowerings, in order to support, e.g. `cvt.bf16.s32` and `cvt.s32.bf16` instructions that are now available on Hopper.
Before this PR - there was some special handling for conversions to and from bf16; for int->bf16, the conversion would be done as a int->fp32 followed by fp32->bf16. Presumably, this was done because, before sm90, the ptx "cvt" instruction doesn't support conversions to/from bf16.
However, sm90 _does_ support direct conversions to/from bf16; so this PR removes this special handling in order to make use of the direct cvt instructions. For Ampere, it looks like the special handling is no longer needed and llvm handles the details of different hardware implementations …

[BACKEND] Remove special handling for bf16 in fp->int, int->fp handling

---

python/test/unit/language/test_core.py
python/test/unit/language/test_random.py

In newer versions of numpy, converting python integers that are out of bounds results in a failure - e.g. see this warning that currently appears in CI:
```
DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 67830198458 to uint32 will fail in the future.
```
This PR fixes two tests which fail when using numpy 2.0.0:
* test_randint - explicitly truncate the integer that was too large
* test_reduce1d: previously, the test would set `x[3:10] = argmax(x)`. However: (1) this now errors due to overflow, e.g. if argmax() returns a value >= 256; and (2) it appears that the intent is actually to set x[3:10] = x[argmax(x)], so that there are duplicate elements with the max value. I've changed this line to `x[3:10] = …

[TEST] Fix numpy out-of-bound warnings/failures

---

README.md

The command to run C++ unit tests, `ninja test`, was failing with the
following error:
```
ninja: error: build.ninja:1002: multiple outputs aren't (yet?) supported
by depslog; bring this up on the mailing list if it affects you
```
CI uses `ctest -j32` to run C++ unit tests, so this changes the failing
command to the one used by CI.
---
- …

Update README instruction to run C++ unit tests

---

lib/Dialect/TritonGPU/IR/Dialect.cpp
test/TritonGPU/canonicalize.mlir

Currently, we create a new op at the location of the ConvertLayout op during canonicalization. For pure ops, it is fine, but for LocalLoad op, we need to create the new op at the location of the LocalLoad op (as memory could have been changed in between)
- [ X] I have run `pre-commit run --from-ref origin/main --to-ref HEAD`.
- Select one of …

[BACKEND] Fix canonicalization of LocalLoad op

---

lib/Dialect/TritonGPU/Transforms/Utility.cpp
test/TritonGPU/repro/sort_with_index.mlir

Fixes pytorch/pytorch#130101
In the linked issue `getConvertBackwardSlice` is returning a slice that requires two different layouts for the same operation, which isn't supported. There is a guard that checks `layouts.find(currentValue)` and bails out when this doesn't match, however this check came after the `visited` check so we would skip the queue item before we ever got to the check.
To fix this I change the visited check to only apply if the current `(value, encoding)` pair has been enqueued previously and apply this uniformly to everywhere we want to update a layout.
The reproducer is admittedly long, but I was able to reduce it down to the exact slice that was triggering the failure.

[OPTIMIZER] Fix layout error after backward remat

---

.github/workflows/integration-tests.yml
.github/workflows/integration-tests.yml.in

These tests are somewhat hopper related and may
grow even more like so given we are enabling more
there so not suitable for AMD side.

[CI][AMD] Drop testing hopper specific tests

---

python/test/unit/language/test_core.py
python/triton/language/semantic.py
python/triton/runtime/interpreter.py
third_party/amd/backend/compiler.py
third_party/nvidia/backend/compiler.py

This is my first PR in Triton, and it is trying to fix the limitation on `dot` to support sizes bigger than `(M,N,K)==(16,16,16)`. 
I modified `semantic.py` to relax the `tt.dot` limitations on the size of the matrices (for `gfx9` architectures). Please note that there is a [supportMFMA function](https://github.com/triton-lang/triton/blob/d7c8b3d7890125f5fc1b9f046e3189baa2665be4/lib/Analysis/Utility.cpp#L458)  that only accepts `MN` sizes multiple of 16 and `K` sizes multiple of 8.
Based on that, I relaxed the restriction in `semantics.py` to support `(M,N,K)>=(16,16,8)`.  This is the minimal change. 
If we want to push further, we would need change `supportMFMA` and add tests for smaller layouts (many of those smaller layouts are broadcast layouts. Do we support this in the AMD backend?) …

[AMD] Support K=8 cases for dot

---

python/src/llvm.cc
third_party/amd/backend/compiler.py
third_party/amd/python/triton_amd.cc

This makes sure all following transformation/optimization steps sees it so not limited to on/after the optimization step. It also makes the `optimize_module` cleaner.
This changes https://github.com/triton-lang/triton/pull/3901 effectively.

[BACKEND][AMD] Attach triple right after converting to llvm

---

.github/workflows/integration-tests.yml
.github/workflows/integration-tests.yml.in
python/test/unit/language/test_line_info.py
python/triton/runtime/interpreter.py

1. Use the builtin `ast.increment_lineno` function to make it more robust
2. Clean up function rewrite logic
3. Resolve global variable reference issues
4. Enable line info tests

[INTERPRETER] Refactor function rewriter

---

third_party/nvidia/backend/driver.c

That is only present in CUDA-12 compatible drivers, and is missing in CUDA-11 ones
Spiritual follow up after https://github.com/triton-lang/triton/pull/2771 allows for dynamic query of the symbol and if run on an older driver, it will return an error. 
Also, fix `occupancyMaxActiveClusters` behavior when symbol is not found (before this change it would crash with null pointer deref, now it should return a structured exception) …

[Runtime] Dynamically load cuTensorMapEncodeTiled

---

python/test/unit/language/print_helper.py
python/test/unit/language/test_subprocess.py

**This pull request adds the use of the `device` fixture to the test to make it not only CUDA specific. This simplifies testing of various devices in the downstream, without having to modify the test code itself.**
~- [ ] I am not making a trivial change, such as fixing a typo in a comment.~

Use `device` fixture for `test_subprocess.py::test_print`

---

third_party/nvidia/backend/driver.c

There was a function pointer lookup missing in the previous patch. https://github.com/triton-lang/triton/commit/f9f2960deef376da4ebc1ff8b1546051c66894a4

[RUNTIME] Fix the function lookup problem for CUDA 11 driver

---

lib/Conversion/TritonGPUToLLVM/FuncOpToLLVM.cpp
test/Conversion/tritongpu_to_llvm.mlir

nvvm.reqntid has a stronger semantic and should allow better optimization in the finalizer.

[BACKEND] Use nvvm.reqntid instead of nvvm.maxntid

---

third_party/nvidia/backend/driver.c

Cherry Pick of : 
https://github.com/triton-lang/triton/pull/4330
https://github.com/triton-lang/triton/pull/4335
to release/3.0.x branch

[Runtime] Dynamically load cuTensorMapEncodeTiled (#4330)

---

python/test/unit/hopper/test_experimental_tma.py
python/triton/tools/experimental_descriptor.py
python/tutorials/09-persistent-matmul.py

This PR fixes the bug demonstrated [here](https://github.com/embg/triton/blob/ed125e4a44e397e9a40e691bb7ce40c698120a1a/tma_repro.py), which is the probable root cause of https://github.com/triton-lang/triton/issues/4332.
NVIDIA docs [recommend](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#using-tma-to-transfer-multi-dimensional-arrays) that TMA descriptors should be passed through immutable device memory, but Triton currently passes them through mutable device memory. This is unsafe unless the TMA descriptor cache is flushed *on every SM*.
The current implementation attempts to flush the cache by launching a [dedicated TMA flush kernel](https://github.com/triton-lang/triton/blob/3aeb223819d632303dd2b45f4dc533d6af90dc46/python/triton/tools/experimental_descriptor.py#L34). …

Short-term solution for TMA descriptor cache management

---

python/test/unit/language/assert_helper.py
python/test/unit/language/print_helper.py
python/test/unit/language/test_subprocess.py
python/test/unit/runtime/test_autotuner.py
python/test/unit/runtime/test_bindings.py
python/test/unit/runtime/test_cache.py
python/test/unit/test_debug_dump.py

This makes it easier to reuse the tests for other non-CUDA backends.
-----
and using the instructions it …

Make tests more device-independent using the device fixture

---

python/triton/runtime/interpreter.py

538556a added assertion in semantic checking of `dot`. 
This commit defines `min_dot_size` for interpreter, 
so kernels including `dot` can be run correctly for interpreter.

[INTERPRETER] Define `min_dot_size`

---

include/triton/Dialect/TritonGPU/Transforms/Utility.h
lib/Analysis/Utility.cpp
python/test/unit/language/test_core.py

Also enhanced the test case (i.e., `test_dot3d`) with a larger block size to trigger the problem

[BACKEND] Fallback to MMAv2 for batch matmul on hopper GPUs

---

python/triton/language/core.py

The comment of `program_id` has a typo. It may make user confused.
and using the instructions it generates is not …

[DOC] fix comment of program_id typo

---

python/setup.py

remove unused requirement 'filelock'

---

.github/workflows/integration-tests.yml
.github/workflows/integration-tests.yml.in
python/test/unit/conftest.py
python/test/unit/runtime/test_cache.py
python/test/unit/runtime/test_subproc.py

I've made the cache dir a fixture-managed temporary directory instead of
a global constant.

Make runtime tests safe to run in parallel

---

python/src/llvm.cc
python/test/unit/language/print_helper.py
python/test/unit/language/test_subprocess.py
third_party/nvidia/backend/compiler.py

Changes to pass target machine DataLayout to llir creation. Fixes issue [4060.](https://github.com/triton-lang/triton/issues/4060)
Triton was passing in the default DataLayout to llir creation and the target machine DataLayout to the llir->asm translation.
This makes the llvm optimization passes use default alignments from llvm/lib/IR/DataLayout.cpp instead of the target machine's alignment.
For i64 on nvidia, this results in alignment of 4(abi)/8(pref) instead of the 8(abi)/8(pref) target alignment expected by functions like vprintf.
This PR adds a attach_datalayout function that allows a backend to create a target DataLayout and attach it to a llvm::Module.
This PR also adds print_device_scalar tests to cover the bug reported in issue 4060.
Complete the following tasks before sending …

[backend] Pass target machine DataLayout to llir creation. Fix for issue 4060.

---

test/TritonGPU/loop-pipeline.mlir

Software pipeling should be not using them. This makes it cleaner and prepares reusing the same test inputs for AMD side.

[TEST] NFC: Drop irrelevant NVIDIA specific attributes

---

third_party/proton/proton/viewer.py
third_party/proton/test/test_viewer.py

Added a specific derived metric in the viewer for `avg_time`, which is the time divided by count. This is a more meaningful metric than just looking at the sum of the time spent on all kernel executions.
For inner nodes of the profiling tree, the metric is omitted as a `nan`. The reasoning is as follows:
`count(inner_node)  = sum(count(kernel_i_within_node))`, meaning that the count for the inner node isn't necessarily how many times the inner_node was executed, but the sum of all the kernels it contains. 
Therefore, the `avg` statistic is not as meaningful here.
--- …

[PROTON] Added avg_time metric

---

python/triton/runtime/autotuner.py
python/triton/testing.py

This makes its interface more similar to `do_bench`, making it easier to switch between the two.

Add quantiles parameter to do_bench_cudagraph

---

python/test/unit/language/test_compile_errors.py
python/test/unit/language/test_core.py
python/triton/language/semantic.py

This would silently do nothing right now. Having this error prevents this behavior.

[FRONTEND] Add error when max_num_imprecise_acc is smaller than K dim

---

lib/Dialect/TritonGPU/Transforms/Utility.cpp
test/TritonGPU/combine.mlir

Summary: When scf.if is marked as live in ForOpDeadArgElim, we should mark its condition as live too. Without this fix, with the test case added in this patch, the scf.if will be removed.

Fix an issue in DeadArgElim where we fail to mark condition op of scf.if as live

---

CMakeLists.txt

[cmake] fix CMAKE_C_FLAGS to CMAKE_CXX_FLAGS

---

third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp

This commit changes the AccelerateAMDMatmul pass to use common target utils to avoid duplication.
While here, cleaned up `using` namespaces and symbols.

[Backend][AMD] Use common target ISA utils in AccelerateAMDMatmul

---

third_party/proton/proton/viewer.py
third_party/proton/test/test_viewer.py

Fixed FLOPS viewer (which wasn't showing before since flops have a width)

[PROTON] Fixed flops viewer and refactored unit tests

---

include/triton/Tools/Sys/GetEnv.hpp
python/src/llvm.cc

Intead of using an env var to disable it we will use one to enable it.

Disable stack trace handler by default

---

lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/MemoryOpToLLVM.cpp

It was separated from the previous PR because we felt it was too long, and splitting it up would make things clearer

[NFC][BACKEND] Move `LocalLoadOpConversion` to `MemoryOpToLLVM.cpp`

---

python/test/unit/runtime/test_subproc.py

It's an unused parameter. Seems like it was used in the first iteration of this test, but that changed along the way. Removing this query makes the test portable across backends.

[TEST] Remove unnecessary capability query in test_subproc.py

---

python/setup.py

When building withou proton (`TRITON_BUILD_PROTON=NO`), `setup.py` still try to include its directory, `triton/profiler` and raise an error during packaging.
This PR fixes it by do not add `triton/profiler` to python package when proton is not built.
- …

[BUILD] Do not package proton if not built.

---

include/triton/Analysis/Membar.h
lib/Analysis/Membar.cpp
python/test/unit/runtime/test_subproc.py

tt.cond_br may jump to the containing block. In such a case, we cannot place this block into its successors during the analysis, because the same block would be added back to blockList and cause an infinite loop.
- Select …

[ANALYSIS] Fixed an infinite loop for Membar pass

---

python/setup.py

In e.g. Nixpkgs (probably in other similar distributions as well) it's important to be able to inject dependencies rather than use vendored/locked dependencies. When we fail to provide complete dependencies for triton we want to get an immediate error, rather than an attempt to download a substitute from the internet (which fails after a timeout anyway, because we the actual builds offline). Sometimes we'd also try to override a recipe with a different version of a dependency than declared upstream, so e.g. we tend to treat strict semantic version checking as an optional feature.
This PR proposes an additional boolean environment variable meant to disable vendoring and fetching attempts in favour of either an immediate error ("input declared but not defined") or a later compile/link time …

setup.py: introduce TRITON_OFFLINE_BUILD

---

python/test/unit/language/test_compile_errors.py
python/triton/compiler/code_generator.py

When initializing defaults in reverse order, the default values are
not use in correctly order.
(However, the defaults are not actually used to set defaults, which
just causes a compile error.) …

[FRONTEND] Check defaults value in correct order

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Dialect/TritonGPU/IR/Dialect.cpp
test/TritonGPU/amd/accelerate-amd-matmul-wmma-gen1.mlir
test/TritonGPU/amd/accelerate-amd-matmul-wmma-gen2.mlir
test/TritonGPU/invalid-attributes.mlir
test/TritonGPU/ops.mlir
third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp

- Added bitfield based version detector for matrix core AccelerateAMDMatmulPass
- Specify kWidth parameter according to the version
- For the first iteration fp8 operands are unsupported, no new operand configuration are added for now
- Added lit tests

[AMD][gfx12] Support WMMAv2 in AccelerateAMDMatmulPass

---

lib/Conversion/TritonGPUToLLVM/FuncOpToLLVM.cpp

`FailureOr<T>` should be checked against whether it contains a failure before using its value. This PR fixes one such misuse.
I also checked all functions returning `FailureOr<T>` in Triton code base and did not find other misuses.

fix a misuse of `FailureOr<T>`

---

python/test/unit/language/test_compile_errors.py
python/triton/compiler/code_generator.py

fix a bug with not const AnnAssign
eg:
```python
import triton
@triton.jit
def kernel(N: int=1):
pass
triton.compile(triton.compiler.ASTSource(fn=kernel, signature={'N': 'i32'}, constants={}))
'''
AttributeError("'AnnAssign' object has no attribute 'targets'")
'''
```
Check if node is `AnnAssign` in `visit_Assign` …

[FRONTEND] Fix not const ann assign in func args

---

python/setup.py

`is_offline_build()` now uses `check_env_flag()` like the rest of the `setup.py` code. `TRITON_OFFLINE_BUILD=YES` and
`TRITON_OFFLINE_BUILD=NO` work as expected.
Offline builds now disable unit test builds. The default `TRITON_BUILD_UT=YES` triggers a download of `googletests` code from GitHub.
See: #4414

Improve offline builds

---

python/setup.py

A small bug fix for `input_defined` variable used in `setup.py`.
I think the only case for downloading shall satisfy all following requirements:
1. `is_offline_build()` is False
2. `input_defined = p.syspath_var_name in os.environ` is False, which means using the cache dir.
3. `input_compatible` is False, which means the current cached version is not correct.
However, the current codes have following issues:
1. `input_defined = p.syspath_var_name not in os.environ`, which is not consistent with the variable name.
2. When `p.syspath_var_name in os.environ` and version is correct in that path, it still downloads.
The bug is introduced in commit https://github.com/triton-lang/triton/commit/0503565f57fbf2571ee15ce00b2a9587c2ac96b0
Codes with bug after …

[BUILD] Fix `input_defined` bug

---

.github/workflows/integration-tests.yml
.github/workflows/integration-tests.yml.in
python/test/unit/language/assert_helper.py
python/test/unit/language/print_helper.py
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp

There was a reported test failure https://github.com/triton-lang/triton/actions/runs/9357367045/job/25756933587 and test_subprocess.py has been skipped in AMD-CI. 
We've investigated that it was caused by a missing GPU/host synchronization before test checking the stdout/err in the test. Normally Triton use case rely GPU/host synchronization on torch tensor but printf test doesn't write output to the tensor and test needs to wait until driver finishes the job. This PR adds `torch.cuda.synchronize()` at the end of the tests which require the synchronization.
Also, we found one more change needed in the AMD backend - set block barrier before we call llvm::trap, guarantees all the assertion message to be printed out before the abortion. This issue has been found after stack trace was …

Fix dynamic failure in `test_subprocess.py`

---

README.md
include/triton/Tools/Sys/GetEnv.hpp
python/triton/compiler/compiler.py

I renamed `USE_TTGIR_LOC` -> `USE_IR_LOC`, which takes a string indicating which IR to assign line numbers to. This allows us to use it for other backends which may not have TTGIR (e.g. CPU has TTCIR). It also allows us to use it for TTIR.

Allow location rewriting to apply to any part of IR lowering

---

python/triton/testing.py

Removed hard-coded references to "cuda" in the do_bench function of testing.py in favour of using PyTorch's `DeviceInterface` object
The existing do_bench hard codes references to a `cuda` device type, making the implementation not flexible to other device types in torch. PyTorch has a `DeviceInterface` class that is a generic interface to different device types. Using the device interface we can continue using the `cuda` device by default in do_bench, but the implementation is now flexible to be used with other device types e.g. out-of-tree backends. 
---
tasks and …

[FRONTEND] Use PyTorch device_interface in do_bench

---

python/triton/runtime/autotuner.py
python/triton/testing.py
third_party/proton/tutorials/matmul.py

Per https://github.com/pytorch/pytorch/pull/9938, which fixes https://github.com/pytorch/pytorch/issues/9646, CUDA streams are now cheap to create under PyTorch. Let's have the benchmarking function create one per run instead of requiring its callers to do so.

[FRONTEND] Have do_bench_cudagraph create its own benchmarking stream

---

python/triton/testing.py

Since H100s have a power throttling depending on the kernel, it is important to see how the TFLOPs change over time. I have this patch in my internal codebase and found it useful to see the cyclic patterns of different kernels and see how long it takes before reaching a steady state.
- [x ] I am not making a trivial change, such as fixing a typo in a comment.
- [  x] I have written a PR description following these
- [x ] This PR does not need a test because do_bench does not have unit tests LOL.
- Select …

feat: add return all for do_bench

---

third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.cpp

This avoids a `Vector Type not specified properly` warning from ptxas.

[backend] NFC: Fix ptx `st` argument order

---

test/TritonGPU/amd/amd-reorder-instructions.mlir
third_party/amd/lib/TritonAMDGPUTransforms/ReorderInstructions.cpp

This pass was blindly moving `local_load` instructions to just after the corresponding `load` instruction. This can violate access order when there are `local_store` ops that get crossed.
Also fixed insertion at the beginning of a block.

[AMD][Reorder] Remove reorder pattern that violates memory access order

---

include/triton/Conversion/TritonGPUToLLVM/Patterns.h
lib/Conversion/TritonGPUToLLVM/DecomposeUnsupportedConversions.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/DecomposeUnsupportedConversions.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DecomposeUnsupportedConversions.cpp

Change the template function `decomposeTensorCoreToDotLayoutConversion` to a normal C++ function.
The template function `decomposeTensorCoreToDotLayoutConversion` is defined in cpp file which is not visible for the out of tree third party backends.
Change it to a normal C++ function to make it available for the out of tree backends.

[NFC] Make the decomposeTensorCoreToDotLayoutConversion to be useable for the third party backend.

---

python/triton/testing.py

Copy/pasted the estimation loop from `do_bench` into `do_bench_cudagraph` in favor of the original create graph -> measure replay methodology. Creating a graph is expensive (~300ms on A100 for me), even if the kernel is relatively inexpensive. Since we just want a rough estimation of the runtime, we can probably go the same route `do_bench` does and save 50% of the overhead in `do_bench_cudagraph` by reducing the total number of graphs created from 2 to 1. Keeping inline with the original function of `do_bench_cudagraph` I removed the L2 cache flush from the estimation loop, which seems fine since there is already no L2 cache flush in the actual benchmarking loop.
you!).  To help us review your code more quickly, …

[do_bench_cudagraph] estimate runtime without creating a graph

---

include/triton/Conversion/TritonGPUToLLVM/Utility.h
lib/Conversion/TritonGPUToLLVM/Utility.cpp
lib/Dialect/Triton/IR/Ops.cpp
lib/Dialect/Triton/Transforms/Combine.cpp
lib/Dialect/TritonGPU/Transforms/OptimizeThreadLocality.cpp
lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
third_party/amd/lib/TritonAMDGPUTransforms/OptimizeEpilogue.cpp

When using `getDefiningOp()` we are often missing to check whether the result is null. Using `getDefiningOp<OpTy>()` helps avoid those latent bugs.

[BACKEND] Fix common mistake of missing checks for null pointer

---

python/test/unit/language/test_core.py

Add tl.debug_barrier to perform a sync in the atomic_cas test implementing spinning lock.
Detailed analysis and discussion can be found [here](https://github.com/triton-lang/triton/pull/4504)
This is a quick fix to avoid failures in the CI until the `tl.debug_barrier` is renamed.

[TEST] Insert barriers in test_atomic_cas to sequence store and atomic

---

.github/workflows/llvm-build.yml

The llvm build check is trying to get http://ftp.de.debian.org/debian/pool/main/g/gcc-defaults/gcc-aarch64-linux-gnu_13.2.0-7_amd64.deb, which does not exist and therefore fails. Updating the version to an existing one (14.1.0-2).
[x] I am not making a trivial change, such as fixing a typo in a comment.
[x] I have written a PR description following these
[x] I have run `pre-commit run --from-ref origin/main --to-ref HEAD`.
[x] This PR does not need a test because it is not a functional change, should fix git checks builds.
[x] I have not added any `lit` tests.

[BACKEND] Update gcc debian package to point to a version 14.1.0-2 which exists in gcc-defaults.

---

python/triton/runtime/cache.py

Not sure this is worthy to make it? I was annoyed by long sha256-based cache directory names, mostly 64 chars. So I quickly added base64-based shorter cache directory names.
Instead of fixing a dozen places that use `hashlib.sha256`, I patched the cache manager. 64-char names are mostly reduced to 43-44 chars.
A comparison:
```
> % ls -l $TRITON_CACHE_DIR
total 0
drwxr-xr-x 1 minjang users  40 Aug 21 19:02 44ae4aee7ef0ee0dd54e860cf44627e3b6cedabe87a228ac75988301b8a6bf60
drwxr-xr-x 1 minjang users  26 Aug 21 19:02 82dc2c9a5508bf07c72e02353c1e751dc54aae85666f139b2867b0a1e95e0e7b
drwxr-xr-x 1 minjang users 226 Aug 21 19:02 b8e240968a85711ba57b17bf8450f1ffbc85a8de8cd1f47aa87b241b53f9bf60
drwxr-xr-x 1 minjang users  26 Aug 21 19:03 gtwsmlUIvwfHLgI1PB51HcVKroVmbxObKGewoeleDns
drwxr-xr-x 1 …
```

Use base64 for shorter cache directories

---

python/test/unit/runtime/test_bindings.py
python/triton/backends/compiler.py
python/triton/compiler/code_generator.py
python/triton/compiler/compiler.py
python/triton/language/extra/libdevice.py
third_party/amd/backend/compiler.py
third_party/nvidia/backend/compiler.py

This is motivated by #4509. The crux of the problem is that the Triton code generator needs to inspect a function's arguments / attributes / types in order to determine how it should be called. This meant that "implementation details" like whether a function is a builtin needed to be exposed in the "interface" `tl.extra.libdevice` module, instead of just residing in `tl.extra.cuda.libdevice`. Moreover, this meant that libdevice functions marked as `@core.extern` in the interface could not be implemented via JitFunctions.
Allowing each backend to provide its own module map solves this problem as the code generator can inspect the actual function implementation.

Add mechanism for remapping device-specific module imports

---

lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp

The knob is only for debugging purposes and should be removed once we've figured out the issue

[BACKEND] Add a knob to fall back to the legacy mma layout conversion code

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/PipelineExpander.cpp

Merging 7c90081: '[SCF][PIPELINE] Handle the case when values from the peeled prologue may escape out of the loop' from the upstream LLVM into Triton Pipeline Expander
"Previously the values in the peeled prologue that weren't treated with the predicateFn were passed to the loop body without any other predication. If those values are later used outside of the loop body, they may be incorrect if the num iterations is smaller than num stages - 1. We need similar masking for those, as is done in the main loop body, using already existing predicates."

[BE][PIPELINE] Handle the case when values from the peeled prologue may escape out of the loop

---

python/test/unit/language/test_core.py

Proposing this change because we use these tests for CPU backend here: https://github.com/microsoft/triton-shared/ and these clauses lead to wrong assumptions about supported features. …

IEEE is common and TF32 is specific to CUDA

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp

If the subview for the mma operand is in the previous iteration of the loop, it would be skipped by the code that looks for it, if it feeds directly into the loop yield. This PR fixes that issue allowing for them subview to be found and enabling the pipelining in some cases skipped previously.

[BE][PIPELINE] Add fix for the wgmma pipelining bug with subview dist 1

---

python/setup.py
test/Conversion/amd/amd-convert-builtin-func.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/BuiltinFuncToLLVM.cpp

* Cherry-pick 06e6799f4eba6035ec35c528e8fefd3d4d724b6f to 3.0.x to fix build issue
* Cherry-pick cf2ad02324fc253970c3ab2666e775406405f213 to fix hang while running flex attention on AMD gpus
*  Fix build issue with cherry-pick of cf2ad02324fc253970c3ab2666e775406405f213
* `enableRegionSimplification` was changed from boolen type to enum in mainline branch

[AMD] Cherry-pick commits from mainline to support Flex attention on AMD gpus

---

test/Conversion/tritongpu_to_llvm.mlir
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp

When `other` is there we should use it to initalize the reg before doing the load instead of initializing the reg with 0.
Note that this does add a scoreboard dependency between the `other` def and the load but user can remove it by using a select if other comes from a high latency op.

[BACKEND] Optimize code generation for load with other arg

---

README.md

The command in readme isn't correct, I finally come out to get the compile command with `find python/build -name 'compile_commands.json' | xargs readlink -f`. I think although the improvement in readme is trivial but it is helpful for other new comer go through the environment setup easier.

[Readme] Fix command to get compile command

---

python/src/llvm.cc

This PR adds verbosity to assembly code after LLVM backend passes.
Regarding the AMDGPU backend, the PR results in leaving references to the source code. For example:
```bash
.LBB0_11:                               ;   in Loop: Header=BB0_13 Depth=1
.loc    1 131 18                        ; gemm.py:131:18
v_lshl_add_u64 v[6:7], v[14:15], 0, v[18:19]
.loc    1 126 22                        ; gemm.py:126:22
v_lshl_add_u64 v[2:3], v[16:17], 0, v[18:19]
.loc    1 128 20                        ; gemm.py:128:20
global_load_dwordx4 v[2:5], v[2:3], off
s_nop 0
global_load_dwordx4 v[10:13], v[6:7], off
.loc    1 127 20                        ; gemm.py:127:20
s_nop 0
global_load_dwordx4 v[6:9], v[20:21], off offset:32
v_mov_b64_e32 v[24:25], v[22:23]
```
Additionally, the PR results in adding …

Enable verbose asm

---

third_party/nvidia/backend/compiler.py

According to the [table](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#release-notes-ptx-release-history), both CUDA 12.5 and 12.6 use PTX ISA 8.5

[CODEGEN] Support CUDA 12.6

---

include/triton/Conversion/TritonGPUToLLVM/Utility.h
lib/Conversion/TritonGPUToLLVM/Utility.cpp
lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/DecomposeUnsupportedConversions.cpp

- Supported linear layout for the 2nd version of WMMA
- Supported legacy emit indices related helper functions for now
- Removed remaining assertions related to WMMAv2

[AMD][gfx12] Support emit indices logic WMMAv2 layout

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp

Get ready to separate scheduling out of SWP, so we can move scheduleLoads and schedulePrologueAndEpilogue to a separate scheduling pass. Lowering will happen after inside SWP.

[SWP] move schedulePrologueAndEpilogue to be before lowering

---

third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ElementwiseOpToLLVM.cpp

Hopper has very low throughput of conversion instructions that cause this operations to quickly become an ALU bottleneck. Restating it in terms of bitwise ops and SIMD bf16 instructions increases the throughput significantly and translates to meaningful speedups (e.g. 10% end-to-end on one matmul I was looking at).

[nvidia backend] Replace cvt instructions with bitwise operations in s8->bf16 conversions

---

include/triton/Dialect/Triton/IR/Utility.h
test/Analysis/test-alignment.mlir

Prevent highestPowOf2Divisor() from producing an underflow when the argument is INT_MIN.

Fix underflow in highestPowOf2Divisor()

---

python/triton/language/core.py

Per https://en.wikipedia.org/wiki/Double-precision_floating-point_format, it should be 52 bits.

Fix mantissa width for fp64

---

include/triton/Dialect/Triton/IR/TritonTypes.td
lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/TypeConverter.cpp
lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
python/src/ir.cc
test/Conversion/tritongpu_to_llvm_hopper.mlir
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/MMAv2.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/WGMMA.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ElementwiseOpToLLVM.cpp

Fix MLIR type used for e4m3 fp8 type in NVIDIA PTX codegen.
https://github.com/triton-lang/triton/issues/3681

[backend][fp8] Float8E4M3FNUZ -> Float8E4M3FN for NVIDIA PTX

---

lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp

The support of toLinearLayout of DotOp is not yet implemented upstream,
so this PR allows fallback to legacy layout for DotOp instead of error
out. When the support of toLinearLayout of DotOp is implemented, this
change can be reverted.
There is a general issue in Triton lowering for the nested layout
slice->dot. This combination of the layout is not hit for NV and AMD
backends while it is possible for Intel backend after some optimization.

Allow fallback to legacy layout for DotOp layout

---

python/triton/compiler/compiler.py

`iter_modules` doesn't recurse into modules it finds, so we weren't including the contents of `tl.extra` other than the top level `__init__.py` file.

[Frontend] Recursively include triton.language modules in triton_key()

---

python/triton/language/core.py

On the current doc, it is unclear what the behavior is when axis=None, this PR adds the explanation.

[doc] Elaborate param axis for reduce ops

---

third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp

When lowering tt.load to PTX we need to generate a mov instruction to set default value into the register for value that are not masked.
For small types (pred, u8, 16) we use vector registers with 2 or 4 value and issue one mov instruction. For example, a lot of u8 tensor will have mov.u16. This mean the default splat value should be concantenated to set multiple value in the vector register.
The current loops uses a hard coded mov width of 32, always does 1 iteration too many and runs inside the loop, so the splat value is shifted more times than necessary.
If the "other" value is 0x1, current code can generate:
mov.u16 $0, 0x101010101;
mov.u16 $0, 0x101010101010101;
We want:
mov.u16 $0, 0x101;
The splat loop should be hoisted even higher, but that would be a much bigger code motion.

[backend][nvidia] Fix shift exponent is too large ASAN error.

---

lib/Dialect/Triton/IR/Ops.cpp
test/TritonGPU/invalid.mlir

The Triton `tt.dot` operation maybe materialized by `MMA` encoding defined by the out-of-tree dialect. 
The verifier of the `tt.dot` operation dispatches the verification to the dialect of the A and B operands which are mostly `DotOp` layout defined in-tree TritonGPU dialect. 
The TritonGPU dialect only verifies the `tt.dot` operation for in-tree backend.
To use the dialect of the C operand layout verifying the `tt.dot` operation for out-of-tree backends. (And also works for NV and AMD's `MMA` which are defined in-tree TritonGPU dialect.)
and using the instructions it …

Verify the `tt.dot` operation thru the dot verification interface of the dialect which defines the C layout.

---

python/test/unit/language/test_compile_errors.py
python/test/unit/language/test_conversions.py
python/test/unit/language/test_core.py
python/triton/language/core.py
python/triton/language/semantic.py
python/triton/runtime/interpreter.py
third_party/amd/backend/compiler.py
third_party/nvidia/backend/compiler.py

We unify the support rules for `fp8` dtypes within triton on a per-backend basis.
While doing that, we heavily simplify the check code for `tl.dot`, given that we now have much stronger preconditions on the possible dtypes.

[frontend] Improve error messages about the support of fp8 types

---

.gitignore
python/setup.py
third_party/proton/CMakeLists.txt
third_party/proton/csrc/include/Driver/Dispatch.h
third_party/proton/csrc/lib/Driver/GPU/CudaApi.cpp
third_party/proton/csrc/lib/Driver/GPU/CuptiApi.cpp
third_party/proton/csrc/lib/Driver/GPU/HipApi.cpp
third_party/proton/csrc/lib/Driver/GPU/HsaApi.cpp
third_party/proton/csrc/lib/Driver/GPU/RoctracerApi.cpp
third_party/proton/proton/profile.py

Previously, we would search for `libcupti.so` in the `LD_LIBRARY_PATH`. However, we already have `libcupti.so` downloaded from the conda package, and it is the version that exactly matches the CUPTI header file. Therefore, we can simply copy and paste `libcupti.so` to `third_party/nvidia/lib/cupti` and search there first. This eliminates the need to set `LD_LIBRARY_PATH` in many cases.

[PROTON] Improve user experience on the CUPTI backend

---

python/src/llvm.cc
third_party/amd/backend/compiler.py

In a recent change to the [LLVM AMD backend](https://github.com/llvm/llvm-project/pull/83131), we moved the  `AMDGPUAttributor` pass into the optimization pipeline (as opposed to the codegen pipeline). 
Since this is a pass specific for `AMD` targets, we want to pass the `TargetMachine` when building the pipeline, i.e.,  during the call to `optimize_module`. 
Failure to do so will result in an increase of number of registers used. Also, we spoke with our LLVM backend team, and they advised to always pass the `TargetMachine` when building the LLVM optimization pipeline. 
This PR is addressing this issue, in the following way:
- I added optional parameters to the `optimize_module` funciton (similar to those passed to `translate_to_asm`)
- if those params are passed in, then we will create …

Pass the target machine to the LLVM pass builder

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/TMAStoresPipeline.cpp
test/TritonGPU/loop-pipeline-hopper.mlir

If the loop has multiple TMA stores we can re-use the allocation as long as we wait for the store to be finished before starting to use the alloc. We were already doing that so re-using shared memory allocation is a net win.
There may be more trade-off to do in the future between shared memory usage and latency hiding.

[BACKEND] Reduce shared memory usage when pipelining multiple TMA stores

---

lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
test/Triton/invalid.mlir
test/TritonGPU/combine.mlir

Remove the restriction that the split dim needs to be the fastest moving one. As long as all the registers are within a thread we can implement splitOp as a no-op. This allows more layout propagation.

[BACKEND] Relax layout supported by SplitOp

---

python/tutorials/09-persistent-matmul.py

This adds a 4th variant to the persistent matmul tutorial that uses the device-side tensormap creation API. 
When running the tutorial I do see a small reduction in utilization, but I suppose this is to expected. The result is still superior to not using tma though:
```
├─ 0.244 matmul_kernel [M=8192, N=8192, K=512]
├─ 0.285 matmul_kernel_device_tma_persistent [M=8192, N=8192, K=512]
├─ 0.259 matmul_kernel_persistent [M=8192, N=8192, K=512]
├─ 0.288 matmul_kernel_tma_persistent [M=8192, N=8192, K=512]
```

[Tutorial] Add device side tensormap update to persistent matmul tutorial

---

README.md

When running kernel compilation with`MLIR_ENABLE_DUMP=1`, the dump doesn't always work when the compiled kernel is the triton cache. 
Repro:
```
MLIR_ENABLE_DUMP=1 python3 python/triton/tools/compile.py \
--kernel-name add_kernel \
--signature "*fp32,*fp32,*fp32,i32,64" \
--grid=1024,1024,1024 \
python/tutorials/01-vector-add.py
```
prints MLIR, However, running it a second time results in no dump.
Adding this to README since it was not obvious to me and took me some time to figure this out.

Workaround for MLIR_ENABLE_DUMP being ignored

---

python/triton/runtime/interpreter.py

The behavior for INTERPRET mode is different from the expected behavior in the test_reduce1d. For numpy <2.0 this difference does not matter, but for version >=2.0 an error occurs. This change fixes it. …

Fix test_reduce1d test with numpy-2.0

---

docs/index.rst
docs/python-api/triton-semantics.rst
python/test/unit/language/test_core.py
python/triton/_internal_testing.py
python/triton/compiler/code_generator.py
python/triton/language/core.py
python/triton/language/extra/cuda/_experimental_tma.py
python/triton/language/math.py
python/triton/language/semantic.py
python/triton/runtime/interpreter.py

The idea here is that if you have a tensor `t` of dtype `uint8` and you want
to do `t << 2`, the result should be of dtype `uint8`, not `int32`!
We do this for all dunder ops that don't output booleans.
This follows roughly the semantics of PyTorch, JAX and NumPy 2.0.
I would like to document this behaviour, but it's not clear to me where
is the best place to say so.
The PR has much more churn than I would like, as I had to move the
`to_tensor` method to `semantic` (which is where it belongs anyway).
For reviewers, the only two relevant changes are in `computation_type_impl` and
in `bitwise_op_type_checking_impl`, where we say that we do perform casting
for bitwise ops.

[Frontend] [BC breaking] Implement PyTorch/JAX/NumPy 2.0 typecast semantics for scalars

---

python/src/llvm.cc

https://github.com/triton-lang/triton/pull/4655 sets the TargetMachine primarily for the AMD backend but we want it to remain nullptr when using LLVM IR level plugins as well.
This PR just adds an additional check when adding TargetMachine value.

Don't set target machine in LLVM pass builder when using LLVM IR level plugins

---

include/triton/Analysis/Membar.h
lib/Analysis/Membar.cpp
test/Analysis/test-membar.mlir
test/lib/Analysis/TestMembar.cpp
third_party/nvidia/include/TritonNVIDIAGPUToLLVM/Utility.h
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TritonGPUToLLVM.cpp

With block level kind of operations like TMA it is possible that some ops access the shared memory but don't require barriers. This adds a lambda that backends can pass to explicitly skip barriers in between some ops.

[BACKEND] Allow backend to specify special rules for membar insertion

---

third_party/nvidia/backend/driver.c

Incrementing refcount for Py_None in TMA descriptor runtime helpers to avoid deallocating the None object. This fixes a runtime failure like
Fatal Python error: none_dealloc: deallocating None

[TMA] Increment refcount for Py_None in TMA descriptor runtime helpers

---

test/TritonGPU/amd/amd-canonicalize-pointers.mlir
third_party/amd/lib/TritonAMDGPUTransforms/CanonicalizePointers.cpp

There was a bug in how we were splitting the uniform/non-uniform offset contribution for addptr. 
Consider this IR (where U is a uniform value, e.g., , coming from a splat and NU is non-uniform, coming e.g., from a `make_range`). 
```
%a = %U+%NU
%b = %a + %NU
%c = addptr %ptr, %b
```
It would have been rewritten to
```
%b = %NU+%NU
%basePtr = addptr %basePtrOld, %U
%c = addi %offset, %b
```
The main issue here is that `%b`'s operand #0 has changed, i.e., the scalar contribution has been removed. This is fine if `addptr` is the only operation that uses `%b`. If any other operation uses `%b`, they need the "old" `%b`. 
The solution is to accumulate both the uniform and non-uniform contributions in a separate IR and leave the original `%b` untouched. Possible duplications will be removed by …

[AMD] Fix uniform offset computation

---

lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp
test/Analysis/test-membar.mlir
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TritonGPUToLLVM.cpp

Also enable the special rules by default in lowering.
Problem caught by @Jokeren during code review.

[BACKEND] Fix potential bug in membar TMA rules

---

include/triton/Dialect/Triton/Transforms/Passes.h
include/triton/Dialect/Triton/Transforms/Passes.td
lib/Dialect/Triton/Transforms/CMakeLists.txt
lib/Dialect/Triton/Transforms/LoopUnroll.cpp
python/src/passes.cc
test/Triton/loop-unroll.mlir
third_party/nvidia/backend/compiler.py

Adding a loop unroller pass which applies to only loops with unroll annotation.
An annotated loop will look like:
```
scf.for %arg5 = %c0_i32 to %arg3 step %c32_i32 : i32 {
...
} {tt.loop_unroll_factor = 2 : i32}
```

[BACKEND] Add a loop unroller pass

---

python/triton/compiler/compiler.py

Currently triton filters out parts of the stack trace that come from inside the compiler itself which is great for not confusing users. However this adds the ability to disable it by setting `TRITON_DEV_MODE=1` in the environment (open to bikeshedding on the name) for when you're trying to debug the frontend itself.

[Frontend] Add TRITON_DEV_MODE for easier debugging of frontend errors

---

lib/Dialect/TritonGPU/Transforms/OptimizeThreadLocality.cpp

The pattern optimizing thread locality for reductions in a loop makes assumptions that the reduction is happening on the most inner dim. This seems deeply engrained in the code so I didn't try to fix it at the moment. It's unclear to me if this code is working as expected in general as it makes assumptions on how reshape with allow_reorder=True will move data around.

[BACKEND] Turn off thread locality optimization based on assumptions

---

.github/workflows/wheels.yml
python/setup.py
python/triton/__init__.py

1. Set build version to 3.1.0
2. Remove: https://github.com/triton-lang/triton/pull/4354 change deployed to build ``wheel-1``

[Release 3.1.0] Bump version to 3.1.0 and remove temporary change

---

test/Conversion/tritongpu_to_llvm.mlir
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMMAv2.cpp

Previously, a "mma16816 data type not supported" error would be thrown if an int16 or int32 dtype was moved from shared memory into registers. This fixes the error.
Use case: tl.dot(fp16_input, int16_input.to(tl.float16)) for MMA v2
Triton does this by: (a) loading the inputs into shared memory; (b) loading from shared memory into registers (in the input layout expected by MMA v2); (c) for the int16 input, converting from i16 to f16; and finally, (d) do the MMA. This means that in step (b), there's a int16 tensor copied from shared memory into MMA layout in registers, which is the scenario fixed by this PR.
contributor (less than 3 PRs merged) we …

[BACKEND] Support integers in MMA-operand layouts

---

test/TritonGPU/loop-pipeline.mlir
third_party/amd/lib/TritonAMDGPUTransforms/StreamPipelineV2.cpp

This change puts `tt.dot` in a predicated `scf.if` based on pipeline peeled iteration.
The result is that the final stage is conditional and the peeling `select` is optimized away in the backend.

[AMD] Predicate tt.dot to override select in pipeline epilogue

---

include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td
lib/Dialect/TritonGPU/Transforms/OptimizeAccumulatorInit.cpp
lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/WGMMA.cpp

If max_num_imprecise is set on a WGMMA, the code handling partial accumulation is not prepared for the case that the accumulator use is being controlled at runtime.
To avoid need for adding a select in this very performance-sensitive code, disable the acc init optimization in this case.

[BE] Accumulator Init Optimization - disable optimization if max_num_imprecise_acc is used for WGMMA

---

lib/Analysis/Utility.cpp
test/TritonGPU/accelerate-matmul.mlir

When K is smaller than the native size supported by wgmma we should fallback to mmav2 otherwise we would crash when creating mmav3 ops.

[BACKEND] Don't use MMAV3 when K dim is smaller than native size

---

python/triton/compiler/code_generator.py

This PR sorts arguments by name to get stable argument order in IR.
Without this change Triton IR is slightly different from run to run.

[Frontend] Fix scf argument order

---

test/Conversion/amd/decompose-unsupported-conversions-cdna.mlir
test/Conversion/amd/decompose-unsupported-conversions-gfx9.mlir
test/Conversion/amd/decompose-unsupported-conversions.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/DecomposeUnsupportedConversions.cpp

This PR introduces:
- Use common code, simplify pass code
- Support 3d tensors in mfma -> dot conversion(supported in common code from item above)
- More tests for decompose-unsupported-amd-conversions pass

[AMD] Refactor decompose-unsupported-amd-conversions pass

---

test/TritonGPU/amd/amd-reorder-instructions.mlir
third_party/amd/lib/TritonAMDGPUTransforms/ReorderInstructions.cpp

For the case of two dot instructions in a single block reorder instructions produces following code:
```
load v
load k
rk = dot(q, k)
rv = dot(rk, v)
```
This patch fixes the order of load instructions (`load k` before `load v`) to make possible load v instruction hiding to avoid waiting for the first dot.
Provided fix is based on the contract between passes, that loads operations are right behind corresponding dots and such chains are not mixed before `AMDGPUReorderInstructionsPass`.
TODO: modify this logic, make decision based on the Dominator analysis.

[AMD] Fix order of load instructions in `AMDGPUReorderInstructionsPass`

---

lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp

Fix crash when lowering `arith.index_cast` to llvm when the cast truncates or extends the i32 index.
`createDestOps` should not `replaceOpWithNewOp` but simply `createOp` because the call-site (`matchAndRewrite`) calls `replaceOp` later on.

[Backend] Fix arith.index_cast lowering to LLVM.

---

python/src/llvm.cc

Fixes `pessimizing-move` warning.

[python] Fix moving a temp object

---

third_party/amd/lib/TritonAMDGPUTransforms/CanonicalizePointers.cpp

[BACKEND][AMD] NFC: Fix initialization order.

---

python/test/unit/language/test_line_info.py
test/Conversion/amd/load_store.mlir
test/Conversion/amd/tritongpu_to_llvm.mlir
third_party/amd/backend/compiler.py
third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/Utility.cpp
third_party/amd/lib/TritonAMDGPUTransforms/CanonicalizePointers.cpp

This PR is doing two things:
- We are using the new `llvm.masked{load/store}` intrinsics. This means that the backend will take responsibility to lower the stores/loads. 
- We are enabling the canonicalization pointer pass on the Triton IR. I extensively run testing and corrected a couple of minor issues still present in the implementation. 
The reason why I am enabling both at the same time is because I saw a minor regression with `llvm.masked{load,store}` which seems to go away when using the pointer canonicalization. Also, this combination seems to reduce the numbers of vgprs used (at least for GEMM kernels).

[AMD] Enable masked load and pointer canonicalization pass

---

third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TMAToLLVM.cpp

The fence turns out to be fairly expensive, and it's cheaper to perform the fence on a single warp and use a barrier to synchronize the remaining threads.

[BACKEND] Improve perf of tensormap_fenceproxy_acquire

---

lib/Dialect/Triton/Transforms/RewriteTensorPointer.cpp
test/Triton/rewrite-tensor-pointer.mlir

---
Hello, maintainers and reviewers!
While reading the …

[BACKEND] Optimize code style in rewrite-tensor-pointer and add more tests

---

python/triton/testing.py

This PR cherry picks a device agnostic change to `do_bench` to use the `DeviceInterface` over the hard-coding of the device type onto the release/3.1.x branch:
* https://github.com/triton-lang/triton/commit/36789d2e2ee8053f7d512a7302ea078bf5629637
This will allow for further device agnostic changes in PyTorch Inductor.
---
you!).  To help us review your code more quickly, **if you are a new contributor (less than 3 PRs merged) we ask that you complete the following
and …

[RELEASE] Cherry-pick use of device-agnostic `DeviceInterface` in `do_bench`

---

include/triton/Dialect/Triton/IR/TritonAttrDefs.td
python/src/ir.cc
python/test/unit/language/test_core.py
python/triton/language/semantic.py
third_party/amd/lib/TritonAMDGPUToLLVM/BuiltinFuncToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/Utility.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/Utility.h

- Supported load CV cache modifier. It corresponds to `flat load sc0 sc1`
- Added unit test for `gfx94` arch

[AMD] Add load CV cache modifier

---

python/test/unit/language/test_compile_errors.py

An unexpected 'test_where_warning' failure occurred if the test was restarted. This happens because the compiler uses the cache and does not write a warning. The environment parameter 'TRITON_ALWAYS_COMPILE' is now used to skip the cache.

Fix the unstable behavior of 'test_where_warning'

---

test/TritonGPU/loop-pipeline-hip.mlir
third_party/amd/lib/TritonAMDGPUTransforms/StreamPipelineV2.cpp

When loop pipelining, do not predicate gpu.barrier. It should be unconditional.

[AMD] Pipeline support for gpu.barrier in epilogue

---

python/tutorials/01-vector-add.py
python/tutorials/02-fused-softmax.py
python/tutorials/05-layer-norm.py
python/tutorials/06-fused-attention.py

Align resulting computation of GBs, TFLOPs in tutorials

---

test/TritonGPU/amd/amd-canonicalize-pointers.mlir
third_party/amd/lib/TritonAMDGPUTransforms/CanonicalizePointers.cpp

This PR is fixing some issues with the `CanonicalizePointer` pass and the new pipeliner:
- Don't traverse twice the same nodes
- Don't assume the operation to delete are in the correct order, but force dropping the reference of the ops before we delete them
- Add support for select operation (+test), which is used when dealing with multiple buffer (this part has been coauthored with @sjw36 )

[AMD][CanonicalizePtr] Add a series of fixes for the new pipeliner

---

python/test/unit/tools/test_disasm.py
python/triton/compiler/compiler.py

This is less tedious than having to manually import `get_sass` and call `get_sass(h.asm["cubin"])`. Moreover, this is done lazily the first time that we want the SASS, so there is no overhead.

Allow h.asm["sass"] to work

---

python/test/unit/language/test_core.py
python/triton/compiler/code_generator.py
python/triton/language/core.py

This change exposes the scf For Loop attribute used in PR #4645 the frontend. It does this by adding a field to tl.range (the same `as num_stages`), this will allow setting loop unrolling factors like so:
```
@triton.jit
def _kernel(dst, v):
pid = tl.program_id(axis=0)
for i in tl.range(0, 10, loop_unroll_factor=2):
tl.atomic_add(dst + pid, i + pid)
```
Unroll factors of less than 2 do nothing, but 2 or more results in the loop body being replicated that number of times (similar to a clang `#pragma unroll`). 

[FRONTEND] Adding unroll loops count to tl.range for scf for

---

python/src/ir.cc
python/test/unit/language/test_core.py

Temporarily turn off log for now to deal with precision problem.

Turn off fast log

---

third_party/proton/proton/proton.py
third_party/proton/test/test_cmd.py

Previously, if both the subcommand (e.g., pytest) and proton had the same option (e.g., -k), proton would fail due to an option conflict. By using argparse.REMAINDER—though its behavior is not well documented in the Python documentation—we now allow proton to parse the -k option only before the subcommand.

[PROTON] Fix option conflict with subcommands

---

lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
python/src/ir.cc
python/test/unit/language/test_core.py
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ElementwiseOpToLLVM.cpp

This reverts commit 84fe9dadad9633421d020b3fa5dea14367b19ea8.

Revert "Use fast math function for tl.math.log as exp (#4723)"

---

test/Conversion/tritongpu_to_llvm.mlir
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.cpp

When we don't have predicates we can use llvm.load. Using inline asm for i8 types can cause inefficient code generation in llvm due to the interaction with DAG legalizer.

[BACKEND] Switch back to use llvm.load for shared memory load

---

lib/Dialect/TritonGPU/Transforms/Prefetch.cpp
test/TritonGPU/prefetch.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp

We've investigated tritongpu-prefetch on the amdgpu and it shows positive result in some cases.
This change allows the prefetch pass to rewrite the loop with the `tt.dot` using `amd_mfma` with a fix in the sharedmem offset.
- Current change doesn't insert the pass to the compilation pipeline yet. 
- The pass is supposed to be placed just after the pipelining pass.

[AMD] Support mfma layout in the prefetch pass

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/PipelineExpander.cpp
test/TritonGPU/loop-pipeline.mlir

This fixes loop iteration count calculation if the step is
a negative value, where we should adjust the added
delta from `step-1` to `step+1` when doing the ceil div.

[Pipeliner] Fix loop iteration calculation for negative step

---

include/triton/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVMBase.h
third_party/amd/backend/driver.py

Per @jataylo :
* libamdhip64.so discovery:
* https://github.com/triton-lang/triton/commit/13edc4547957b9ec3a3c731e94ffa441e59c47b
* https://github.com/triton-lang/triton/commit/e0613c64b9bb872e4fa47dbce15ffa6770a1032b
* wmma: https://github.com/triton-lang/triton/commit/4a1ea8e10f2dae94087ec90cfcafda5ffb889811 (already cherry-picked)
* mfma: https://github.com/triton-lang/triton/commit/0a66c1bd16313690c1eb5440cb89eaa072f1827b

AMD requested cherry-picks for release/3.1.x

---

.github/workflows/integration-tests.yml
.github/workflows/integration-tests.yml.in

This PR enhances dependency checks with the following changes:
- Checks if all dependency files exist; if not, the GitHub action will fail.
- Calculates a hash to determine if any NVIDIA dependencies have changed.
- Extracts only the hash when using `sha256sum` (by default, its output is `<hash> <filename>`).

[CI] Fix dependency checks

---

include/triton/Dialect/Triton/IR/TritonOps.td
lib/Conversion/TritonGPUToLLVM/AssertOpToLLVM.cpp
python/src/ir.cc
python/triton/language/core.py
python/triton/language/semantic.py
python/triton/runtime/interpreter.py
test/TritonGPU/combine.mlir

Currently, `device_assert` takes in separate `filename`, `funcname`, `lineno`  and it gets them by inspecting python frames in core.py. It's clunky and in practice it is often unknown. Since the loc information is already in the builder, it could be used directly, which is what this PR does.

Get file, line and col from MLIR instead of inspecting python frames. Function name will be always set to "unknown" for now.

---

third_party/amd/backend/compiler.py
third_party/amd/include/Dialect/TritonAMDGPU/IR/TritonAMDGPUOps.td
third_party/amd/include/TritonAMDGPUToLLVM/Passes.h
third_party/amd/include/TritonAMDGPUToLLVM/Passes.td
third_party/amd/lib/TritonAMDGPUToLLVM/CMakeLists.txt
third_party/amd/lib/TritonAMDGPUToLLVM/SchedInstructions.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/TritonGPUToLLVM.cpp
third_party/amd/python/triton_amd.cc

Some backends (e.g., AMDGPU) may have [special intrinsics](https://llvm.org/docs/AMDGPUUsage.html#llvm-ir-intrinsics) which provide hints to the compiler backend to adjust instruction scheduling. This PR targets only `tt.dot` operations which are often the most intensive ones and may demand fine-tuning to achieve better performance.

[AMD] Add basic instruction scheduling control

---

lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/ReduceScanCommon.h
lib/Conversion/TritonGPUToLLVM/ScanOpToLLVM.cpp
python/test/unit/language/test_core.py

Currently the reduction codegen unconditionally executes the combine region which can create problems because we conditionally load from shared memory, so this uses uninitialized registers.
Generally combine regions should be pure, so this shouldn't be observable but with the overflow sanitizer the frontend injects assertions into the combine region.
This changes the `accumulate` function to take a predicate and if the combine region isn't speculateble we only run it on threads where the predicate is true. In the common case, the codegen is unchanged.

[Backend] Fix device assert inside reduction/scan region

---

python/test/unit/runtime/test_autotuner.py
python/triton/runtime/autotuner.py

The autotuner uses the index of the arguments of the Triton kernel signature to look up the value to be used as the key for the config cache.
There is an issue if the user pass the kernel arguments as keyword args in arbitrary order.
The name of the argument should be used to look up the value of the args passed by the user instead of the `key_idx`.
This prevents the autotuner from using a mismatched value as the key for caching when the arguments are passed in arbitrary order as keyword args.
and using the …

[AUTOTUNER] Fix issue in autotuner which may use the wrong value as the key of config cache.

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
test/TritonGPU/loop-pipeline.mlir

Summary: split loads so each group of uses with the same shared encoding will have a corresponding load. This enables pipelining loads with incompatible shared encoding.
AMD has its own version of assignMemoryLayouts, so the test case load_two_users_incompatible_layouts will have different results for AMD.

[SWP] split loads to handle incompatible shared encoding

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
test/TritonGPU/loop-pipeline-indirect-load.mlir

For indirect loads, we try to assign them to later stages
```
unsigned stagesBetweenLoads =
ceil<unsigned>(numStages - 2, maxIndirectionLevel + 1);
int stage = (maxIndirectionLevel - indLevel) * stagesBetweenLoads;
schedule.insert(loadOp, stage, loadsClusters[indLevel]);
```
If numStages is 2, there is no later stage to assign the indirect loads to. The fix is to not pipeline the indirect loads.
We also generalize to not pipeline an indirect load if the indirection level >= numStages - 1

[SWP] When num_stages = 2, do not pipeline indirect loads

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
test/TritonGPU/loop-pipeline.mlir

Triton LLVM codegen has a bug where local_loads from #shared to #mma layout can lead to invalid code if the loaded shape is smaller than the mma tile. Remove the workaround.
See https://github.com/triton-lang/triton/pull/3561.
Verified that with test case: https://pastebin.com/xxP3cFmy (test.mlir), running
triton-opt test.mlir -tritongpu-pipeline=num-stages=3 --convert-scf-to-cf  --allocate-shared-memory --convert-triton-gpu-to-llvm
has no issue.
Unit test case added in https://github.com/triton-lang/triton/pull/4798 also shows no issue.

[SWP] attempt to remove a workaround for a triton llvm codegen bug

---

python/tutorials/09-persistent-matmul.py

Currently we sleep between each rep for Triton kernels, but not for the cuBLAS kernel. This may improve cuBLAS performance on fp8 due to thermal issues.

09-persistent-matmul.py bugfix

---

python/test/unit/hopper/test_experimental_tma.py
python/triton/language/core.py

Fixing an compile error like below when passing dtype through kernel arg for `tl._experimental_descriptor_load`:
AttributeError: 'constexpr' object has no attribute 'to_ir'

[FRONTEND] Support passing dtype as constexpr for tma load

---

include/triton/Dialect/TritonGPU/IR/Dialect.h
lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp
third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp
unittest/Dialect/TritonGPU/DialectTest.cpp
unittest/Dialect/TritonGPU/LinearLayoutConversionsTest.cpp

This PR
- Fixed the issue with getOrder for mfma layout
- Fixed the issue with reduceOp when dealing with mfma.transposed layout
In general, getOrder and getThreadOrder can return different values, and this is the case for mfma.transposed layout. Therefore, we shouldn't assume order and threadOrder are always the same.

[AMD] Always swap operands of mfma and use mfma.transposed layout

---

python/setup.py

LLD is not supported on macOS. This addresses failures like
> clang: error: invalid linker name in argument '-fuse-ld=lld'
See https://github.com/triton-lang/triton/actions/runs/11099205977/job/30833066194#step:10:61

[BUILD] Avoid using lld as the linker on macOS

---

third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/Utility.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/Utility.h

I think we should always set the right alignment to the `maskedload`/`maskedstore` instructions.

[AMD] Add alignment information to maskedLoad/maskedStore

---

.github/workflows/integration-tests.yml
.github/workflows/integration-tests.yml.in
python/setup.py

Pinned LLVM to v19; cannot do the same for LLD though.
This allows us to revert #4827.

[CI][macOS] Pin LLVM version and install lld

---

test/TritonGPU/amd/amd-loop-pipeline-v1.mlir
third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp

Previously, if an arg inside the loop was marked as a depArg, then a new iter_arg would be added to the for loop to handle the arg; but any usages of these variables _after_ the for loop would not be updated; those usages would get the wrong value. This PR fixes this by updating the return mapping. See the comment added in StreamPipeline.cpp for an example.

[AMD] StreamPipeline V1: fix depArg return mapping

---

python/setup.py

It's very common that we need to figure out the exact commit from which the current installed triton package is compiled. Right now it will just show a version number like `3.0.0` which isn't quite helpful.
With this commit we have
```
> pip show triton
Name: triton
Version: 3.0.0+git78e4f837
```

Add git commit to the version as a suffix

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/PipelineExpander.cpp
test/TritonGPU/amd/amd-canonicalize-pointers.mlir
third_party/amd/lib/TritonAMDGPUTransforms/CanonicalizePointers.cpp

This is fixing the issue where the IR was not properly vectorized in Triton (and we were relying on a backend pass which was not always able to do the right thing). 
The general issue was that we were not propagating the attributes of the operation we were rewriting. The specific issue was that block argument attributes are in the for of `tt.property_argi` for the i-th block argument, so we needed to do a bit more work to propagate those correctly. 
This PR is trying to address this problem by adding a vector of attributes to the `FatPtr` structure. We are not propagating the attributes, but only setting them whenever the IR had them set.

[AMD][CanonicalizePointers] Propagate the attributes during the rewrites

---

lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp
unittest/Dialect/TritonGPU/LinearLayoutConversionsTest.cpp

This commit implements dotOperandMfma layout to linear layout conversion under following conditions: 
- opIdx == 1
- kWidth == 8
- warpsPerCTA[0] == 1.
This serves as a preparation for a next PR, which will add a bypassLDS pass.

[AMD] Implement dotOperandMfma to linear layout conversion

---

third_party/proton/csrc/lib/Profiler/Cupti/CuptiPCSampling.cpp

Fix lack of `<stdexcept>` header file for `std::runtime_error`
and using the instructions it generates is not …

[PROTON] Fix build with clang-17

---

python/test/unit/runtime/test_bindings.py
python/test/unit/runtime/test_subproc.py
python/triton/backends/compiler.py
python/triton/compiler/__init__.py
python/triton/compiler/code_generator.py
python/triton/compiler/compiler.py
python/triton/runtime/jit.py
python/triton/tools/compile.py
third_party/amd/backend/compiler.py

In this PR I am trying to refactor the specializations that we apply to the signature of a given function in Triton. 
Basically, given a kernel there are some argument properties that can help compilation. E.g., divisibility by 16 and the fact that an integer is equal to 1. 
In a previous PR: https://github.com/triton-lang/triton/pull/4716, I needed other specializations to add buffer support in the AMD backend (and get back some performance when we were using unaligned masked loads). 
So this is my attempt to redesign the specialization support to introduce per-backend specializations. The idea is that `AttrsDescriptor` is now the class that is taking care of doing the analysis of the parameters and adding the specialization. It also has a function table where more specializations can be …

Refactor compiler specializations to consider backend

---

lib/Tools/LinearLayout.cpp

Moving the access of a `std::optional` after the check if it has a value. This does cause a crash right now when running with `TRITON_ENABLE_LLVM_DEBUG=1` in combination with some test cases.

[Backend] Fix access to empty std::optional in LinearLayout debug code

---

python/test/unit/language/test_core.py

This PR fixes condition in test_dot3d that failed on systems without GPU:
If test is run in interpreter mode on system with no GPU, `torch.cuda.current_device()` does not return valid value.

[Interpreter] [Tests] Fix condition in test_dot3d

---

test/TritonGPU/amd/amd-canonicalize-pointers.mlir
third_party/amd/lib/TritonAMDGPUTransforms/CanonicalizePointers.cpp

We need to take a bit of extra care to canonicalize scalar pointers. 
- When `createTensorPointer` don't splat anything (because it is scalar)
- When we update the `addPtr` we need to make sure to update the pointer field
(coauthor @sjw36 )

[AMD][CanonicalizePtr] Fix the scalar pointer canonicalization

---

python/triton/compiler/code_generator.py
python/triton/language/core.py

<git-pr-chain>
[Frontend] Separate tensor and ir value into two different concepts
Currently in the frontend all IR values are tensors, but for the TMA
work I would like tensor descriptor to be it's own distinct type.
This just adds a new base class representing a generic IR value and
makes tensor inherit from it.
1. 👉 #4854 👈 **YOU ARE HERE**
1. #4855

[Frontend] Separate tensor and ir value into two different concepts

---

third_party/amd/backend/compiler.py
third_party/amd/python/triton_amd.cc

This reverts ad9afc8 since the issue was fixed by https://github.com/llvm/llvm-project/pull/104743

[AMD] Add back "Hint compiler to preload kernel args"

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
test/TritonGPU/loop-pipeline.mlir

Duplicating loads will significantly increase the shared memory usage which is likely to cause out of memory problem. We should find an alternative to not have to duplicate shared memory allocations.

Revert https://github.com/triton-lang/triton/pull/4784

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
test/TritonGPU/loop-pipeline.mlir

This change is causing failures in some internal tests. There must still be some miscompile associated with this.

revert https://github.com/triton-lang/triton/pull/4774

---

.gitignore

Address an issue caused by https://github.com/triton-lang/triton/commit/53166efa2494764e11734d57de681cc4d2486981 after which we will see extra libraries after building from source each time, such as `python/triton/language/extra/cuda`.

[BUILD] Add language extras to `.gitignore`

---

lib/Analysis/AxisInfo.cpp
python/test/regression/test_functional_regressions.py
test/Analysis/test-alignment.mlir

Contiguity is used to issue wide load operations instead of multiple loads.
This always assumes that the address of the first element in a sequence can
be used to load the sequence of elements. If a sequence is diminishing, it
leads to a wrong wide load operation.
This patch fixes that by not preserving a contiguity of RHS for SubIOp
operation.

[ANALYSIS] Don't consider descending sequences as contiguous in AxisInfoAnalysis

---

python/setup.py
python/triton/backends/compiler.py

Use typing instead on bare Python type to avoid using subscript operation on built-in Python type
Fix "TypeError: 'type' object is not subscriptable" error on Python 3.8
including the "tests …

Fix type hint on Python 3.8

---

python/triton/compiler/compiler.py

To support loading a kernel using TMA descriptors from ttgir we need to parse the attribute out of the signature to get the proper type.

[frontend] Parse nv_tma_desc attribute when compiling from ttgir

---

third_party/nvidia/backend/compiler.py

Super quick quality-of-life improvement: on `ptxas` failure we were just dumping the repro command as a list, and joining it before printing makes it much easier to copy-and-paste for debugging.

[frontend] Pretty-print `ptxas` command on failure

---

python/triton/language/extra/__init__.py

Before 53166efa2494764e11734d57de681cc4d2486981, `importing triton/language/extra/__init__.py` used to import `cuda` and `hip`: https://github.com/triton-lang/triton/commit/53166efa2494764e11734d57de681cc4d2486981#diff-20c816668bef8f6f25f90585e3cf909d86c209cbb2281c49938de1a2e6729c5dL1-L4
After the commit it no longer imports them because submodules in triton.language.extra are moved to /third_party and copied during setup.py. This change breaks code that relies on such behavior:
```python
from triton.language import extra
extra.cuda
>>> <cuda submodule>
from triton.language import extra
extra.cuda
>>> Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: module 'triton.language.extra' has no attribute 'cuda'
```
To keep the compatibility, this commit is to …

Auto import backends in `triton.language.extra`

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Dialect/TritonGPU/IR/Dialect.cpp

According to https://en.cppreference.com/w/cpp/algorithm/clamp
If lo is greater than hi, the behavior is undefined.
Without this fix, we found that `CTAsPerCGA[i]` can be 0.

[BACKEND] Avoid undefined behavior in `std::clamp` when `shapePerCTA[i] < sizePerThread[i]`

---

python/setup.py

Use Nullable type hint for the field added in
53166efa2494764e11734d57de681cc4d2486981
and using the instructions …

Fix type hint in setup.py

---

CMakeLists.txt
include/triton/Dialect/Triton/IR/TritonDialect.td
lib/Dialect/Triton/IR/Dialect.cpp
python/src/ir.cc
python/test/unit/language/test_core.py
python/triton/compiler/code_generator.py
third_party/amd/lib/TritonAMDGPUToLLVM/TritonGPUToLLVM.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TritonGPUToLLVM.cpp

`LLVM::UndefOp` only supports LLVM native types, so instead this uses the closest equivalent in mlir which is `ub::PoisonOp`. As the name implies, this lowers to poison in llvm instead of undef but I'm not sure the difference matters to us as we don't have a UB policy anyway.

[IR] Add poison value to triton IR and use in frontend in place of undef

---

python/tutorials/02-fused-softmax.py

This PR fixes a typo in the comments of the softmax kernel function, where "piepling" was mistakenly used instead of "pipelining". The change ensures that the term accurately reflects the correct meaning of "pipelining" in software stages.
- (Note: While this change fixes a typo, it corrects an important technical term—'pipelining'—which is crucial for understanding the kernel's functionality.)

Fix typo: Correct 'piepling' to 'pipelining' in kernel comments for clarity in software optimization.

---

lib/Dialect/Triton/Transforms/RewriteTensorPointer.cpp
test/Triton/rewrite-tensor-pointer.mlir

I ran into an error in the RewriteTensorPointer pass when testing the HSTU kernel. In my IR, there's an scf.if that produces a non-pointer result. The rewriteIfOp() created a new scf.if, but the use of scf.if result is still referencing the old one, which caused a compile error. In this patch, I updated all uses of scf.if with the results of the new if-op.

[Backend] Update scf.if result uses in RewriteTensorPointer pass

---

test/TritonGPU/amd/amd-reorder-instructions.mlir
third_party/amd/lib/TritonAMDGPUTransforms/ReorderInstructions.cpp

Adjust the placement of LDS writes and reads to immediately follow the
definition of their operands in case where LDS write is in the loop but it's operand is not. This is a heuristic for optimizing fused attention by hoisting Q tensor LDS read/write operations outside of the loop, as Q is a loop invariant and can be loaded once before entering the loop.
In the previous implementation, the heuristic incorrectly assumed that the operand of the LDS write had to be a load operation, which is unnecessary. Additionally, there was no explicit check to verify whether the LDS write was in the loop while its defining operand was not. This PR addresses both issues.

[AMD] Fix "keep Q tensor in VGPRS" optimization

---

test/TritonGPU/amd/amd-sched-2nd-load.mlir
third_party/amd/lib/TritonAMDGPUTransforms/ReorderInstructions.cpp

This helps backend to interleave global load and mfma instructions and can reduce global load issue latency.

[AMD] Sink the 2nd tt.load after local_load's

---

python/triton/language/core.py

https://github.com/triton-lang/triton/pull/4589 mistakenly deactivated
these and reverted to the previous always-cast-to-int32 semantics.

Re-enable NumPy 2.0 semantics for add, sub, mul.

---

include/triton/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVMBase.h
third_party/amd/backend/compiler.py

This adds a missing exception to the warp size and fixes dot test for m or n > 32 when using wmma.

[AMD] Fix gfx12 warp size and fix wmma in maybeDeduplicate

---

include/triton/Dialect/TritonGPU/IR/LinearLayoutConversions.h
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp
unittest/Dialect/TritonGPU/LinearLayoutConversionsTest.cpp

Note that the current implementation uses `DotOperandEncodingAttr::getWarpsPerCTA`, which was buggy for cases where the warps are not of the form `[numWarps, 1]` or `[1, numWarps]`. This PR bundles a fix for this issue.
We will activate its use for a subset of `DotOperandEncoding`s in a PR coming soon.

[Linear Layouts] Implement LL conversion for DotOperand(version=2)

---

.github/workflows/integration-tests.yml
.github/workflows/integration-tests.yml.in

Currently PRs only get CI when the base branch is main or starts with `dev-` but this changes it to run on all PRs which works better for when using `git-pr-chain` where the base branch usually isn't main.

[CI] Run CI on all PRs

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/PipelineExpander.cpp
python/test/unit/language/test_pipeliner.py
test/TritonGPU/loop-pipeline.mlir

- The epilogue ramp-down indexing must start at zero or greater (total_iterations - max_stage) to ensure alignment with the prologue ramp-up stages.
- If total_iterations < max_stage, the trailing stages will be masked.
* This PR adds a functional test for correctness with num_stages=1,2,3,4

[Pipeliner] Fix epilogue peeling for num_stages=3+

---

include/triton/Dialect/TritonGPU/IR/LinearLayoutConversions.h
lib/Analysis/Allocation.cpp
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/DecomposeUnsupportedConversions.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp
lib/Dialect/TritonGPU/IR/Ops.cpp
lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
lib/Dialect/TritonGPU/Transforms/ReduceDataDuplication.cpp
python/test/unit/language/test_core.py
python/triton/language/semantic.py
test/Analysis/test-allocation.mlir
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/MMAv2.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/UpcastMXFPToLLVM.cpp
unittest/Dialect/TritonGPU/LinearLayoutConversionsTest.cpp

This PR includes https://github.com/triton-lang/triton/pull/4891 and https://github.com/triton-lang/triton/pull/4895. I will rebase once those have landed.
It includes a number of hacks to work around bugs in `DotOperandEncodingAttr`. All these are marked as `FIXME [Dot LL]` to be easy to grep for. @Jokeren is working on a comprehensive revamp of `DotOperandEncodingAttr` which will get rid of all these. https://github.com/triton-lang/triton/pull/4895 is the first step in this direction.

[Backend] Implement `scaled_dot(mxfp4, fp8)`

---

.github/workflows/llvm-build.yml

14.1.0-2 was gone from the debian ftp server.

Update GCC aarch64 toolchain to 14.2.0-1

---

third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/PTXAsmFormat.cpp

The predicate wasn't being added to the instruction representation when `onlyAttachMLIRArgs` was set to true

Add the predicate to the instrRepr before returning it when onlyAttachMLIRArgs=true

---

.gitignore

Otherwise, we may include `libGPUInstrumentationTestLib.so` into the commit

[BUILD] Add instrumentation libs to `.gitignore`

---

include/triton/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.h

This makes the dependence more obvious since `const std::string &target` is used in this file.

[NFC] Add `#include <string>` into `TritonToTritonGPUPass.h`

---

python/test/unit/language/test_compile_errors.py
python/test/unit/language/test_subprocess.py

Minor changes that reuse Python's capabilities for writing platform-independent code.

[NFC] Make some tests platform independent

---

python/test/unit/runtime/test_cache.py
python/triton/backends/compiler.py
python/triton/runtime/jit.py
third_party/amd/backend/compiler.py

This is a PR stemming from #4716 . I am adding an attribute in the HIP backend to test for a tensor storage to be within 2GB. This will enable support of buffer operations.

[AMD] Add a tt.pointer_range_32 specialization

---

include/triton/Dialect/Triton/IR/TritonOps.td
lib/Dialect/Triton/IR/Ops.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/OptimizeThreadLocality.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
test/Conversion/tritongpu_to_llvm.mlir
test/Triton/combine.mlir
test/Triton/invalid.mlir
test/Triton/ops.mlir
test/TritonGPU/canonicalize.mlir
test/TritonGPU/combine.mlir
test/TritonGPU/loop-pipeline-hip.mlir
test/TritonGPU/loop-pipeline.mlir
test/TritonGPU/optimize-locality.mlir

Make `allow_reorder` and `efficient_layout` `UnitAttr` for a cleaner interface.
This way, the operation exposes a `bool getEfficientLayout()` member to check for that attribute and a constructor receiving `bool` arguments for both of these attributes (defaulted to `false`).
- `/unittest` …

[Triton] Use `UnitAttr` in `tt.reshape` definition

---

bin/CMakeLists.txt

- [ x] This PR does not need a test because `it is a non functional change that simply removes duplicated call to a cmake function`.
including the "tests should be minimal" section. (Usually …

[NFC] Remove duplicated call to function `mlir_check_link_libraries`

---

include/triton/Dialect/Triton/IR/TritonOps.td
test/Triton/invalid.mlir

Add `SameOperandsShape` to `tt.reduce` to verify all operands have the same shape.
This matches `triton.language.reduce` (and similar) semantics.
This change may enable further optimizations and even may help simplify
the code dealing with this operation. Followup PRs will tackle this.
- …

[Triton] Verify all `tt.reduce` operands have the same shape

---

lib/Tools/LinearLayout.cpp

fix MSVC compilation support `__builtin_ctz`, `__builtin_ctzll` 
based on https://gist.github.com/pps83/3210a2f980fd02bb2ba2e5a1fc4a2ef0

win: __builtin_ctz* for MSVC

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp

Not only does this have issues with iterator invalidation, it also runs out of bounds if the last element is erased. We should just use the functions for doing this rather than worrying about how to implement it correctly ourselves.
- `/python/test` for …

Replace open-coded indirect load elimination loop

---

lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/DecomposeUnsupportedConversions.cpp
lib/Conversion/TritonGPUToLLVM/MemoryOpToLLVM.cpp
lib/Dialect/TritonGPU/Transforms/ReduceDataDuplication.cpp
python/test/unit/language/test_core.py
python/test/unit/language/test_pipeliner.py

We allow DotOperand within MemoryOpToLLVM in the buggy ampere case via
LLs. This allows us to remove two workarounds that we added in a previous PR.
We add tests in test_pipeliner.py
We also remove some implementation-defined behaviour (overflows / NaNs)
in test_core.py, thus making the tests more resilient and realistic.

Pipeline scale_dot

---

lib/Conversion/TritonGPUToLLVM/CMakeLists.txt

Note, there are no uses of `nvgpu::` in this lib. Unblocks building `*-opt` tools with "custom" LLVM that was built with `-DLLVM_TARGETS_TO_BUILD="host;AMDGPU"` (i.e., no `NVPTX`).

[Build] Remove unnecessary `NVGPUIR` from `TritonGPUToLLVM`

---

test/Conversion/tritongpu_to_llvm.mlir
test/Conversion/tritongpu_to_llvm_hopper.mlir
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp

Hopper supports vectorized atomics for add, max, and min. This PR adds support for generating these instructions.
Note: atomic add/min/max also have packed instructions for f16x2 and bf16x2. Packed instructions were used prior to this PR, but vectorized instructions weren't. When vectorized instructions are available, this PR switches to using vectorized instructions (like .v2.f16 instead of .f16x2, or .v8.f16 instead of .v4.f16x2). When vectorized instructions aren't available, packed instructions will be used instead.
This PR also adds a check for mask alignment, which wasn't previously checked.

[BACKEND] Use vectorized atomics on Hopper

---

python/triton/testing.py
third_party/amd/backend/driver.py
third_party/nvidia/backend/driver.py

This is a quick follow-up for the recent autotuner/testing changes as in https://github.com/triton-lang/triton/pull/4496. This PR moves the empty cache creation into the driver code to make the code more device independent.

[AUTOTUNER] A quick follow-up for more device-independent do_bench

---

lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp

Hit by @apgoucher. Putting this up to unblock him, but I find absolutely
bizarre that we end up with a tensor of pointers in mma format. I
haven't investigated where this is created though. We should probably
look into it.

Fix when trying to convert an mma<!tt.ptr<f32>> into blocked

---

test/Conversion/amd/builtin_func_to_llvm.mlir
third_party/amd/backend/compiler.py
third_party/amd/include/TritonAMDGPUToLLVM/Passes.h
third_party/amd/include/TritonAMDGPUToLLVM/Passes.td
third_party/amd/language/hip/libdevice.py
third_party/amd/lib/TritonAMDGPUToLLVM/BuiltinFuncToLLVM.cpp
third_party/amd/python/triton_amd.cc

This PR added `fast_expf` operator under libdevice for AMD hardwares.
Aligning with other operators in the exp family, the way to deal with
denorm inputs is controled by `__HIP_FTZ`, which currently is fixed to be
True.
- If `__HIP_FTZ = 1`, the operator uses `llvm.amdgcn.exp2.f32`, which will
flush denorms in inputs and outputs;
- If `__HIP_FTZ = 0`, the operator uses `llvm.exp2.f32`, which will not
flush denorms.
Ref: https://github.com/ROCm/llvm-project/blob/amd-staging/amd/device-libs/cuda2gcn/src/precision.cl 
Fixes https://github.com/ROCm/triton-internal/issues/314

[AMD] Add fast_expf to libdevice

---

include/triton/Conversion/TritonGPUToLLVM/TargetInfoBase.h
test/Conversion/tritongpu_to_llvm_hopper.mlir
test/Conversion/tritongpu_to_llvm_hopper_ptx80.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.h
third_party/nvidia/backend/compiler.py
third_party/nvidia/include/TritonNVIDIAGPUToLLVM/Passes.h
third_party/nvidia/include/TritonNVIDIAGPUToLLVM/Passes.td
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.h
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TritonGPUToLLVM.cpp
third_party/nvidia/triton_nvidia.cc

Vectorized atomics on NVIDIA (https://github.com/triton-lang/triton/pull/4971) are only available on Hopper (>=sm90) and PTX >= 8.1. It's possible to be running with PTX 8.0 on a Hopper machine. This PR passes ptx-version to the ttgir->llir conversion pass for NVIDIA, and uses the ptx version to determine whether vectorized atomics should be used.

[BACKEND][NVIDIA] pass ptx-version to ttgir->llir conversion pass and use it for vectorized atomics

---

test/TritonGPU/loop-pipeline-hip.mlir
third_party/amd/lib/TritonAMDGPUTransforms/StreamPipelineV2.cpp

`add_optimize_dot_operands` may introduce a immutable shared buffer for transposed dot operands. Our stream-pipeliner then replaces the immutable buffer with a mutable buffer to be able to reuse it across iterations (pre-fetching). This will then produce incorrect transOps because the input is mutable but the result is immutable.
This PR rewrites those transOps to output a mutable layout.
and using …

[AMD] Rewrite transpose ops in pipeliner to mutable memory

---

third_party/proton/README.md
third_party/proton/proton/profile.py

Based on the feedback from AMD, the device mapping problem has to be addressed by the ROCm team, so we emit an error for now.

[PROTON] Emit an error for the roctracer backend if `HIP_VISIBLE_DEVICES` is set

---

bin/RegisterTritonDialects.h
include/triton/Tools/Sys/GetEnv.hpp
python/test/unit/language/test_core.py
test/TritonGPU/amd/amd-canonicalize-pointers.mlir
test/TritonGPU/amd/amd-convert-buffer-ops.mlir
third_party/amd/backend/compiler.py
third_party/amd/include/TritonAMDGPUTransforms/Passes.h
third_party/amd/include/TritonAMDGPUTransforms/Passes.td
third_party/amd/lib/TritonAMDGPUToLLVM/BufferOpsEmitter.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUTransforms/CMakeLists.txt
third_party/amd/lib/TritonAMDGPUTransforms/CanonicalizePointers.cpp
third_party/amd/lib/TritonAMDGPUTransforms/ConvertToBufferOps.cpp
third_party/amd/python/triton_amd.cc

This is part 3 of the redesign stemmed from #4716 (which I am closing) . Instead of rebasing that PR, I opened a new one, since the differences were significant. 
This PR is only introducing a ttgir pass to convert `tt.load`/`tt.store` to `amdgpu.buffer_load`/`amdgpu.buffer_load`, _when this is possible_ : this means we need to check for 3 conditions:
1. The pointer arithmetic has been canonicalized (`scalarPtr->splat->addptr->load/store`)
2. The offsets are 32-bits
3. The offsets are non-negative. We use a mix of analysis and assumptions to verify this condition

[AMD] Add pass to convert tt.load/tt.store to buffer operations

---

lib/Conversion/TritonGPUToLLVM/MemoryOpToLLVM.cpp
test/Conversion/amd/compute-base-ptr.mlir
test/Conversion/amd/tritongpu_to_llvm.mlir
test/TritonGPU/combine.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp

This PR:
- Introduces fallback from normal TTG->LLVM converter in case it does not support given local_load.
- Enables conversion of MFMA dot layout to Linear Layout in local_load pattern.

[AMD] Enable shared->MFMA dot operand conversion through LinearLayout

---

python/triton/compiler/compiler.py
third_party/nvidia/backend/driver.py

Change to improve platform independence.
How it works?
On Windows:
```python
>>> import sysconfig
>>> sysconfig.get_config_var("EXT_SUFFIX")
'.cp310-win_amd64.pyd'
>>> sysconfig.get_config_var("EXT_SUFFIX").split(".")[-1]
'pyd'
```
On Linux:
```python
>>> import sysconfig
>>> sysconfig.get_config_var("EXT_SUFFIX")
'.cpython-310-x86_64-linux-gnu.so'
>>> sysconfig.get_config_var("EXT_SUFFIX").split(".")[-1]
'so'
```

[NFC] Use `get_config_var('EXT_SUFFIX')` instead of using `so` directly

---

python/test/unit/language/test_core.py

This adds float16 to the list of dtypes tested in test_tensor_atomic_rmw. Note that the numerics were previously bad for this test when run in float16; this PR "fixes" the numerics by internally doing the sum in float32 (upcast, sum, downcast). Since the purpose is to test the atomic_rmw, and the numerical issues of doing sums in low-precision dtypes are generally know, I think this strategy should be fine for this test.

[TEST] float16 test for test_tensor_atomic_rmw

---

python/triton/language/semantic.py
test/Conversion/amd/tritongpu_to_llvm.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp

In the case of 16 bit floats operands for tt::AtomicRMWOp, construct only one LLVM::AtomicRMWOp but use vector of elements.
Such approach allows to generate packed intrinsics and process 2 elements at once.
Added a lit test for f16 vectorized case.

[AMD] Emit vectorized 16-bit float LLVM atomic ops

---

include/triton/Analysis/Utility.h
include/triton/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVMBase.h
include/triton/Conversion/TritonGPUToLLVM/Utility.h
lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/MemoryOpToLLVM.cpp
lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp
lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp
lib/Tools/LinearLayout.cpp
test/Analysis/test-allocation.mlir
test/Analysis/test-membar.mlir
test/Conversion/tritongpu_to_llvm.mlir
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ConvertLayoutOpToLLVM.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DecomposeUnsupportedConversions.cpp
unittest/Dialect/TritonGPU/LinearLayoutConversionsTest.cpp

This PR fixes the `cvtReordersRegisters` method, which previously could not return true for two layouts with different numbers of registers. With this update, we can remove the legacy `isMmaToDotShortcut` and its associated shortcut conversion.
Additionally, we store the dot operand results in the access order to improve code clarity.
Going forward, we intend to eliminate unnecessary shortcut conversions and replace them with the use of `transferWithinThread`.

[BACKEND] Replace `isMmaToDotShortcut` with linear layout based logic

---

python/src/interpreter.cc

`#include <atomic>` is already used in other triton files, so I believe it's not a cardinally change.
Changes come from https://github.com/triton-lang/triton/pull/4045

[INTERPRETER] Replace GCC `__ATOMIC*` built-ins with std::atomic for `interpreter.cc`

---

third_party/amd/lib/TritonAMDGPUTransforms/ReorderInstructions.cpp

This commit restructures the ReorderInstructions pass to be
more modular and cleaner with utility functions and guard
rule applications against their intended usage rather than
always being globally on. Along the way, dropped some
unnecessary local_load sink given it's later hoisted again.
Fixes https://github.com/ROCm/triton-internal/issues/280

[AMD] Restructure ReorderInstructions pass

---

include/triton/Analysis/Utility.h
lib/Analysis/Allocation.cpp
lib/Analysis/Utility.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/DecomposeUnsupportedConversions.cpp

This PR removes special cases for MFMA -> Dot Operand LDS shortcuts.
Now it is supported by common linear layout infrastructure.
No tests are added, [mfma-shortcut.mlir](https://github.com/triton-lang/triton/blob/main/test/Conversion/amd/mfma-shortcut.mlir) already testing this.

[AMD] remove redundant LDS bypass checks

---

python/test/unit/language/test_core.py

`scaled_dot` is not yet implemented on `gfx11` and `gfx12` so disable unit tests for now.

[AMD] Skip scaled_dot tests for gfx11 and gfx12

---

python/triton/backends/compiler.py

The string representation allows PyTorch Inductor to serialize/derserialize the `AttrsDescriptor` to the `@triton.heuristics` block in the generated code.

Add string representation for AttrsDescriptor

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp
test/Conversion/tritongpu_to_llvm_hopper.mlir
test/TritonGPU/dot-operands.mlir
test/TritonGPU/invalid-attributes.mlir
test/TritonGPU/loop-pipeline-hopper.mlir
test/TritonGPU/pipeline-hopper-remove-wait.mlir
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/CMakeLists.txt
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ConvertLayoutOpToLLVM.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMMAv2OrV3.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/MMAv2.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/WGMMA.cpp

Allows for upcasting in DotOp encoding in RF.
This lowering path is not currently in use; pending https://github.com/triton-lang/triton/pull/5003

[BACKEND][NVIDIA] Add Lowering for Shared-to-MMAv3-DotOp Copy

---

docs/python-api/triton.language.rst
include/triton/Dialect/Triton/IR/TritonAttrDefs.td
include/triton/Dialect/Triton/IR/TritonOps.td
include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td
lib/Dialect/TritonGPU/IR/Ops.cpp
lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
python/src/ir.cc
python/test/unit/language/test_core.py
python/triton/language/core.py
python/triton/language/semantic.py
test/TritonGPU/accelerate-matmul.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/UpcastMXFPToLLVM.cpp
third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/UpcastMXFPToLLVM.cpp

In the passing we also improve a few other things:
- Now `scaled_dot` accepts both uint8/uint16 fp8/bf16 as inputs (before you had to cast it to uint8, which was weird when extending it to bf16).
- Add `scaled_dot` to the docs and improve the docs overall (have not render them, might need a few further tweaks)

[Frontend][Backend] Implement support for scale_dot(-, bf16)

---

include/triton/Dialect/TritonGPU/Transforms/Schedule.h
lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp

We call assignMemoryLayouts and set up distToUse right before lowering.
During scheduling, we call a helper function that checks if a load can be pipelined.
loadOpToIndLevelAndUse is used during scheduling and also in assignMemoryLayouts. The next step is to clean up that logic so lowering will not use loadOpToIndLevelAndUse, instead it checks the schedule and finds out which loads are pipelined (i.e uses for loads are in different stages from the loads).

[SWP] separate logic in assignMemoryLayouts that should belong to scheduling

---

docs/python-api/triton-semantics.rst
python/test/unit/language/test_core.py
python/triton/_internal_testing.py
python/triton/language/semantic.py
python/triton/runtime/interpreter.py

Continuation of the work from @lezcano https://github.com/triton-lang/triton/pull/4698
> With this PR, we make `%` always follow C semantics, similar to `//`. We update the type promotion docs fixing some inaccuracies. It is still not entirely precise though. For a discussion of the current semantics see https://github.com/triton-lang/triton/issues/4697
Pretty sure all that was left were changes for the frem function to emit `np.fmod` instead of `np.remainder` and to ignore ('uint16', 'float64') mod computations in the tests. I believe this combination is ill-conditioned but I could be wrong about that.
contributor (less than 3 PRs merged) we ask …

[Frontend] [BC breaking] Always follow C semantics on %

---

lib/Conversion/TritonGPUToLLVM/AssertOpToLLVM.cpp
test/Conversion/tritongpu_to_llvm.mlir

Add a barrier to avoid a race condition in case an assert is followed by an op that may trap if the assert condition is true. Since the tensor in those two operations may have different layout we need to make sure all the threads are done executing the assert before going to the next op.

[BACKEND] Add barrier after assert op to avoid race condition

---

python/test/unit/test_debug.py
python/triton/language/core.py
python/triton/runtime/jit.py

Reported in https://github.com/triton-lang/triton/pull/5033/files#r1825438371
This was broken by #4589

[FRONTEND] Fix @triton.jit(debug=True)

---

include/triton/Conversion/TritonGPUToLLVM/Utility.h
lib/Conversion/TritonGPUToLLVM/Utility.cpp
python/test/unit/language/test_core.py
python/triton/_internal_testing.py
third_party/amd/lib/TritonAMDGPUToLLVM/UpcastMXFPToLLVM.cpp
third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/UpcastMXFPToLLVM.cpp

This commit adds support for mxfp4 typed A tensor
for sacled dot in the AMD backend.
We moved the `convertMxfp4x2ToBf16x2` impl
from NVIDIA side to a common path to reuse.

[AMD] Add support for scaled_dot(mxfp4, -)

---

include/triton/Dialect/Triton/IR/TritonOps.td
lib/Conversion/TritonGPUToLLVM/AssertOpToLLVM.cpp
python/triton/language/semantic.py
test/Conversion/tritongpu_to_llvm.mlir

support asserts with scalar condition and only emit barrier for assert of tensors.
Thanks to @peterbell10 for the suggestion.

Add back barrier after asserts

---

include/triton/Dialect/TritonGPU/IR/Dialect.h
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/MMAv2.cpp
unittest/Dialect/TritonGPU/LinearLayoutConversionsTest.cpp

We also clean a bit `TritonGPU/IR/Dialect.cpp` using some auxiliary functions to make the intentions a bit clearer.
We add a few asserts in the `LainearLayoutConversion` to make sure it's clear why we do certain things here and there.
We also kill `getCvtOrder`, as it was not used anywhere

[BACKEND]Fix DotOperand(Ampere) LinearLayoutConversion

---

python/test/unit/language/test_core.py
python/triton/language/semantic.py

In the interpreter mode, we cannot use `not tensor` to check if `tensor` is None or not because the interpreter directly evaluates the tensor.
Also consolidated the test cases for `tl.store`.

[INTERPRETER] Correct `None` tensor check logic

---

third_party/amd/include/Dialect/TritonAMDGPU/IR/Dialect.h
third_party/amd/lib/TritonAMDGPUTransforms/CMakeLists.txt

TritonAMDGPUTransforms now depends on it.

[AMD] Add missing dependency to TritonAMDGPUIR

---

lib/Dialect/TritonGPU/Transforms/CombineTensorSelectAndIf.cpp
test/TritonGPU/combine-select-if.mlir

The CombineTensorSelectAndIf pass currently doesn’t work correctly **when the user of select is inside the scf.if block**.
For example:
```mlir
%select = arith.select %cond, %trueVal, %falseVal : i32
%if = scf.if %cond -> (i32) {
%sub = arith.subi %select, %val1 : i32
scf.yield %sub : i32
} else {
%mul = arith.muli %select, %val2 : i32
scf.yield %mul : i32
}
use %select
```
In this case, dom.dominates(ifOp, user) will return true, but directly using replaceAllUsesWith would lead to incorrect replacement behavior. 
```mlir
// without this pr (the user in ifOp use the result of ifOp) 
%if:2 = scf.if %cond -> (i32, i32) {
%sub = arith.subi %if#1, %val1 : i32
scf.yield %sub, %trueVal : i32, i32
} else {
%mul = arith.muli %if#1, %val2 : i32
scf.yield %mul, %falseVal : i32, i32
}
use %if#1
``` …

[BACKEND] Fix the combineSelectAndIf when the user of select in ifOp.

---

lib/Dialect/TritonGPU/IR/Dialect.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMMAv2OrV3.cpp

Two bugfixes following https://github.com/triton-lang/triton/pull/5009.
- When `BLOCK_M=64` and `num_warps > 4`, the order of warps for DotOpEncoded tensor should be M-major instead of N-major, since WGMMA expects the 4 warps in each warp group to be stacked along the M dimension.
- Should use `mmaBitwidth` instead of `bitwidth` when calculating `numRep` in `SharedToDotOperandMMAv2OrV3`. This was missed in a bad rebase.
@lezcano I encountered these bugs when attempting to locally test the [DotOp hoisting PR](https://github.com/triton-lang/triton/pull/5003) after rebasing (they normally would be caught by `test_core.py` but that path was not yet enabled in the last PR). With these fixes added, I was able to successfully validate against pytorch.

[BACKEND] Minor Bugfixes for SharedToDotOperand MMAv3

---

python/test/unit/language/test_compile_errors.py
python/test/unit/language/test_conversions.py
python/test/unit/language/test_core.py
python/test/unit/language/test_pipeliner.py
python/triton/_internal_testing.py

This commit enables pipeliner test for scaled dot
on the AMD backend.
Along the way, unified some target/arch probe
utilities into the common `_internal_testing` file.

[AMD] Enable pipeliner test for scaled_dot

---

lib/Dialect/Triton/Transforms/LoopUnroll.cpp
test/Triton/loop-unroll.mlir

The epilog loop created by the loop unroller may not be run if the main unrolled loop covers all original loop iterations, thus pipelining it non-speculatively may not be beneficial. It can also cause some correctness issue when combined with the downstream PTXAS optimizer.

[LoopUnroll] Do not pipeline epilog loops generated by loop unrolling

---

lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
python/test/unit/language/test_core.py

Reductions have special handling for side effectful "combine ops" (e.g. "add" for a sum reduction). In the presence of side effects, a predicate is computed to determine whether a thread should participate in the reduction, to ensure that invalid/uninitialized data is not operated on. See #4811 for more details.
~Previously, the predicate logic was incorrect for 2D reductions. This PR fixes the logic and adds a python test.~
Edit: after additional discussion with @peterbell10, we removed the lanePred logic. Here's our thinking on why this is valid:
* lanePred info is computed based entirely on the blocked layout info and properties of the reduction
* the blocked layout won't tell you which threads do or don't have uninitialized data
Instead, it sounds like the motivation for #4811 is …

[Backend] Fix predicates for device assert inside reduction/scan region

---

lib/Conversion/TritonGPUToLLVM/ScanOpToLLVM.cpp
python/test/unit/language/test_core.py

This is a follow up to #5033 but for scan ops, and also improving the testing as it was clearly insufficient before.

[BACKEND] Fix asserts in 2d scan and add assert mode to layout tests

---

CMakeLists.txt
python/setup.py

It's a bit annoying to have to remember to pass `TRITON_BUILD_WITH_CCACHE` every time you invoke `pip install`.
This changes the default to check if ccache is installed and use it if it's found, with the option to manually disable ccache if it's not wanted for some reason.

[BUILD] Build with ccache by default if available

---

python/test/unit/language/test_core.py

These two tests causes significant CI runtime increase (10x)
so disabling them to unblock while figuring out issues.

[AMD] Disable overflow check while fixing issues

---

python/test/unit/language/test_core.py

https://github.com/triton-lang/triton/pull/5062 enabled
upcasting fp8E4M3FN to bf16; so now we can support
that variant too.

[AMD] Enable all existing scaled_dot data type tests on MI300

---

python/test/unit/language/test_libdevice.py
python/triton/compiler/code_generator.py

Context: in `CodeGenerator.__init__`, globals for a given triton function are modified to handle remapping the libdevice module to cuda or hip (from https://github.com/triton-lang/triton/pull/4539). In particular, this logic:
```python
for k, v in gscope.items():  # gscope is a dict of fn.__globals__
...
self.gscope[k] = getattr(module_map[module_name], k)
```
was failing if you do this in the global scope: `from triton.language.extras.libdevice import fast_dividef as my_fast_dividef`.

[FRONTEND] Fix handling of `from m import x as y` in CodeGenerator

---

test/Conversion/tritongpu_to_llvm.mlir
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/MMAv2.cpp

```
within split at ./test.mlir:1 offset :23:10: error: 'llvm.bitcast' op result #0 must be LLVM-compatible non-aggregate type, but got 'f8E5M2'
%D = tt.dot %AA_DOT, %BB_DOT, %cst0 : tensor<16x16xf8E5M2, #dot_operand_a> * tensor<16x16xf8E5M2, #dot_operand_b> -> tensor<16x16xf32, #mma0>
^
```
fp8E5M2 should be converted to i8 in the LLVM backend

[BACKEND] Fix mmav2 for fp8

---

test/TritonGPU/amd/optimize-lds-usage.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/OptimizeLDSUsage.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/OptimizeLDSUtility.cpp

This is a draft for a patch which fixes an assertion being hit when the wrong number of pipeline stages is set.
More discussion at: https://github.com/pytorch/pytorch/issues/139621 
============================================================
- [ x] I have run `pre-commit run --from-ref origin/main --to-ref HEAD`. …

[AMD] Fix issue with rank=1 in tryFitCvtIntoLDS

---

include/triton/Analysis/Utility.h
include/triton/Conversion/TritonGPUToLLVM/Utility.h
include/triton/Dialect/TritonGPU/IR/Dialect.h
include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Analysis/Allocation.cpp
lib/Analysis/AxisInfo.cpp
lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/ScanOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp
lib/Dialect/TritonGPU/Transforms/ReduceDataDuplication.cpp
test/Conversion/amd/load_store.mlir
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DecomposeUnsupportedConversions.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/MMAv2.cpp

This partially reverts commit 38a11b859fff79ea214256d3f1cfe43d54e36c2c.
Supersedes https://github.com/triton-lang/triton/pull/5085
It also documents that we are implicitly choosing a way to tile a
full tensor depending on the layout. See https://github.com/triton-lang/triton/pull/5085#issuecomment-2460925683

Consolidate `getOrder` as "element order" and implement `getRepOrder` for general and NVIDIA layouts

---

lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/MemoryOpToLLVM.cpp
lib/Dialect/TritonGPU/IR/Ops.cpp
lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
python/test/unit/language/test_core.py

Even though this refactor allows for sharing the code for choosing warps
and mma version with the regular `DotOp`, we don't activate any of the
two paths yet, given that we still have to fix a couple things for them
to work.
Putting this preliminary PR up to avoid packing too many things in one PR

[BACKEND] Implement generic code to allow for dot_scaled(mmav3) and warp choices

---

include/triton/Dialect/Triton/IR/TritonOps.td
lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
python/src/ir.cc
python/test/unit/language/test_core.py
python/triton/language/semantic.py
test/TritonGPU/accelerate-matmul.mlir

This enables support for scaled_dot with rhs scale. It still only supports one scale either on lhs or rhs at the moment.
For simplicity we just transpose operands for this case for MMAv2 and sync the transpose op on the destination. This prepares us for MMAv3 support where the scales should always be on lhs.

Support scaled_dot with rhs scale

---

python/test/unit/language/test_core.py
python/triton/_internal_testing.py

Cuda converts `tt.store` to `inline_asm` command, and xpu converts it to `llvm.store`. Then the LLVM optimizer for the SROA function removes `llvm.store` with the poison value, but ignores the cuda assembly instruction.

[TEST] Skip poison when checking llvm ir for xpu

---

.github/workflows/integration-tests.yml
.github/workflows/integration-tests.yml.in

The issue has been fixed and pre-commit configuration has been updated to use a newer yapf version, so the workaround is no longer required.

[CI] Remove a workaround for yapf issue

---

lib/Conversion/TritonGPUToLLVM/AssertOpToLLVM.cpp
python/test/unit/test_debug.py

This will fix the following problem:
```bash
python: /home/runner/work/triton/triton/llvm-project/llvm/include/llvm/ADT/ilist_iterator.h:168: llvm::ilist_iterator::reference llvm::ilist_iterator<llvm::ilist_detail::node_options<mlir::Operation, true, false, void, false, void>, false, false>::operator*() const [OptionsT = llvm::ilist_detail::node_options<mlir::Operation, true, false, void, false, void>, IsReverse = false, IsConst = false]: Assertion `!NodePtr->isKnownSentinel()' failed.
Aborted (core dumped)
```
The problem was found when using PyTorch on Intel gpu:
<details>
<summary> Simplified reproducer #1:</summary>
```python
from torch._inductor.async_compile import AsyncCompile
async_compile = AsyncCompile()
triton_per_fused_add_embedding_native_layer_norm_0 = …
```

Fix barrier insertion after `assert` op

---

test/Conversion/amd/tritongpu_to_llvm.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp

In the case of unpaired f16 elements utilize dpp instructions to accelerate atomics. Here is an algorithm of lowering `tt::atomicRmwOp(%ptr, %val, %mask)`:
0. Group thread by pairs. Master thread is (tid % 2 == 0);
1. All the threads send `%val` to `(tid - 1)` thread via `dppUpdateOp shl`, so all the masters recieve value from secondary threads;
2. Take into account parity in the `%mask` value, build CF structures according to it;
3. Generate `llvm::atomicRmwOp` in the threads enabled by `%mask` value;
4. All the threads send result of generated operation to `(tid + 1)` thread via `dppUpdateOp shl`, so all secondary thread also recieve their result.
This approach is alternative to https://github.com/triton-lang/triton/pull/5028. DPP approach has ~5% perf improvment so use this one in the …

[AMD] Add atomicRMW dpp logic

---

.github/workflows/llvm-build.yml

If a directory with LLVM exists in the runner (for example, a leftover from a previous run for the same LLVM commit id), then the new LLVM build will be copied to `install` subdirectory. To avoid this case we should remove the existing LLVM installation directory.
Fixes #5096.
- …

Fix llvm-build for almalinux

---

include/triton/Dialect/Triton/IR/TritonOps.td
lib/Dialect/Triton/IR/Ops.cpp
lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
test/Triton/canonicalize.mlir
third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp

Now that fp_to_fp is marked as elementwise we may have scalar version of this op.

[BACKEND] Support scalar fp_to_fp

---

test/TritonGPU/amd/amd-sched-2nd-load.mlir
third_party/amd/lib/TritonAMDGPUTransforms/ReorderInstructions.cpp

This avoids us to scan across functions when
considering optimizations. Right now we have
one function in the module so it's NFC; but
it should be cleaner this way.

[AMD] NFC: change to func walk in ReorderInstructions

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Dialect/TritonGPU/IR/Dialect.cpp
test/Conversion/tritongpu_to_llvm_hopper.mlir

Fixes https://github.com/triton-lang/triton/issues/5102
The logic in `getTotalElemsPerThreadForOperand` should now directly match that in `SharedToDotOperandMMAv2OrV3`

[BACKEND][NVIDIA] Remove NvidiaMma::getTotalElems...ForOperand

---

third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/BarrierOpToLLVM.cpp

I discovered it while I was looking at https://github.com/triton-lang/triton/pull/5114#discussion_r1838855910.
Looks like `bar_id` attribute is no longer used. The attribute setting was removed in: https://github.com/triton-lang/triton/commit/dd2a32363baac6b8b7b6c3b02e56fce5bb2dab14.
cc @ThomasRaoux

[BACKEND][NVIDIA][NFC] Remove `BarrierOpConversion` conversion as dead code

---

python/test/unit/language/test_core.py
test/Conversion/amd/load_store.mlir
test/Conversion/amd/tritongpu_to_llvm.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp

Flat instructions could be a reason of significant slowness of workloads due to undefined addresspace of pointers, so llvm passes can not apply some of optimizations to these instructions.
This patch removes addresspace casting to keep original addresspace for pointers and generate proper loads/stores.

[AMD] Get rid of flat load/store instructions

---

include/triton/Conversion/TritonGPUToLLVM/Utility.h
include/triton/Dialect/Triton/IR/TritonOps.td
lib/Dialect/Triton/IR/Ops.cpp
test/Conversion/amd/tritongpu_to_llvm.mlir
third_party/amd/include/TritonAMDGPUToLLVM/TargetUtils.h
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/Utility.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/Utility.h
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.cpp

[AMD] Support Cross-Lane Reduction With DPP

---

python/triton/runtime/autotuner.py

Printing out config when autotune fails under `TRITON_DEBUG`. This will allow kernel developers to narrow down a problematic config and remove it to unblock themselves. This could also help compiler developers focus on debugging that config.

[Frontend] Print out config when autotune fails

---

include/triton/Analysis/Allocation.h
lib/Analysis/Allocation.cpp
test/Analysis/test-allocation.mlir
test/lib/Analysis/TestAllocation.cpp

Allow passing a functor to `ModuleAllocation` constructor to override
`getScratchValueSize` in the allocation analysis. This parameter will
be a default implementation by default.
including …

[Triton][Allocation] Enable `getScratchValueSize` specialization

---

python/test/regression/test_cast_matmul.py

This prevents surprises when some value may go above the tolerance threshold

[TEST] Make mixed matmul test deterministic

---

cmake/AddTritonUnitTest.cmake

`gtest_discover_tests` runs the built unittest executable to create a distinct CMake target for every individual unittest in each executable. However, this was previously noted to time out on MacOS frequently (because MacOS scans newly built executables for viruses, or something...) but the timeout argument was incorrectly specified.

Fix `gtest_discover_tests` timeout argument

---

lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
test/Conversion/triton_to_tritongpu.mlir

Upstream handling of splatted bools in `DenseElementsAttr` was fixed, so the workaround can be removed when lowering `arith.constant` to TritonGPU.

[Triton] Remove upstream bug workaround (NFC)

---

README.md
python/src/ir.cc

By setting a reproducer path, the pass manager will dump a standard MLIR reproducer before each pass manager invocation. This PR also enables additional local crash reproducer generation (to the same path set through the env var), which tries to narrow down the specific pass that failed, if the pass pipeline fails at any point.

[Triton] Generate local MLIR reproducers when possible

---

include/triton/Dialect/Triton/IR/TritonOps.td
lib/Dialect/Triton/IR/Ops.cpp
test/Triton/canonicalize.mlir
test/TritonGPU/loop-pipeline-hopper.mlir

I noticed this rather obvious pattern was missing. It might come up for example if you have an expression like:
```python
ptrs = ptr + y_stride * tl.arange(0, YBLOCK)[:, None]
```
and the `YBLOCK` is set to 1 during autotuning.

[BACKEND] Add folder for `addptr(ptr, 0) -> ptr`

---

python/test/regression/test_cast_matmul.py

This commit enables mixed precision matmul test
for AMD backend. For FP8 E4M3, we test
`fp8e4m3fnuz` given that's natively supported on
MI300 series.

[AMD] Enable mixed precision matmul test

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Dialect/TritonGPU/IR/Dialect.cpp

Implement RepOrder methods for MFMA and WMMA layouts. Both layouts have row major rep layout. Also,
isTranspose flag in MFMA layout does not affect RepOrder, meaning RepOrder is row major in both cases.

[AMD] Implement RepOrder for AMD MMA layouts

---

lib/Analysis/AxisInfo.cpp
test/TritonGPU/coalesce.mlir

Fixes #5122.
The `ProgramPoint` [here](https://github.com/triton-lang/triton/blob/0bd30a2f3192204c5a50d5ffde27ad8493f6c026/lib/Analysis/AxisInfo.cpp#L1087) is created on the stack. Then its address is [passed](https://github.com/triton-lang/triton/blob/0bd30a2f3192204c5a50d5ffde27ad8493f6c026/lib/Analysis/AxisInfo.cpp#L1088-L1089) to the MLIR `SparseAnalysis` code, where it is [added as a dependency](https://github.com/llvm/llvm-project/blob/33ff9e43b4c5bdc3da31c6b11ad51d35a69bec5f/mlir/lib/Analysis/DataFlow/SparseAnalysis.cpp#L311) and later [dereferenced](https://github.com/llvm/llvm-project/blob/33ff9e43b4c5bdc3da31c6b11ad51d35a69bec5f/mlir/lib/Analysis/DataFlow/SparseAnalysis.cpp#L90). By the time the `ProramPoint` is dereferenced in the `AbstractSparseForwardDataFlowAnalysis::visit`, …

[BACKEND] Fix ProgramPoint passing in AxisInfoAnalysis

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Dialect/TritonGPU/IR/Dialect.cpp
python/test/regression/test_cast_matmul.py
test/Conversion/tritongpu_to_llvm_hopper.mlir
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMMAv2OrV3.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/MMAv2.cpp

In mmav3 case the number of elements per threads should be independent of the element type, we should only consider kWidth.
TODO: it should also be true for MMAv2 but the logic is a bit more complicated.
Also enable larger block_m in mixed mode tests to exercise MMAv3 case

[BACKEND] Fix getElemsPerThread for mmav3 dot operand

---

python/triton/runtime/interpreter.py

`tensor_shape` is a confusing name and doesn't match block pointer's semantic.
`block_shape` is much clearer.

[INTERPRETER][NFC] Rename `tensor_shape` -> `block_shape` in interpreter

---

lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp
unittest/Dialect/TritonGPU/LinearLayoutConversionsTest.cpp

We also rewrite the way we implement DotOperand(Ampere) and mma Ampere
to promote code reusing. I also started using what I believe is a rather
compact pattern to write these things, where you first call `identiyND`
with the `repOrder`, which gives you an LL with the dims in the correct
order, and then you construct the final layout by specifying the tiles
by multiplying `identity1D` maps. Using this allowed me to heavily
simplify the handling of the `warps` of `DotOperand` which used to be a
tad messy.

[LAYOUTS] Implement LL conversion for DotOperand(Hopper)

---

python/test/unit/language/test_block_pointer.py
python/triton/runtime/interpreter.py

We forgot to check `offset >= 0` previously.
Now that it should match the semantic in the GPU backend
https://github.com/triton-lang/triton/blob/7bce3613755e26953518962d02315dfd343dc50c/lib/Dialect/Triton/Transforms/RewriteTensorPointer.cpp#L136

[INTERPRETER] Fix lower bound check for block pointers

---

lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp

The auxiliary function `identityND` used to take an `order` parameter,
that comes from triton, and a set of dimensions. Now, the order in
triton is defined wrt. `dim0..dim<rank-1>`, so the dimension arg was
redundant. This was quite confusing.
We see that in all the uses of `identiyND`, we would pass the canonical
dimensions, other than in one that we simply remove as it was not
necessary.
We remove the dims arg and simply return a layout with output dims
`dim0..dim<rank-1>`.

[LLs] [BE] Simplify identityND

---

lib/Dialect/TritonGPU/IR/Dialect.cpp

The util function `getDistributedLayoutStr` uses the `DistributedLayout` attribute interface, which is not flexible for third-party extensions.
Use the `getInDimSize` of the `LinearLayout`, which is better since the legacy layout has been converted to the `LinearLayout`.
There is no new test case since it is only a change in API usage.

[BACKEND] Use the LL API to replace the using of legacy layout attribute API.

---

.github/workflows/integration-tests.yml
.github/workflows/integration-tests.yml.in

This improves a warm-cache macOS build from ~25 mins to 2 mins.

[CI] Fix ccache cache restoration to improve build times

---

.github/workflows/integration-tests.yml
.github/workflows/integration-tests.yml.in

Follow up to #5202
It's currently failing with the error
```
du: /Users/runner/.triton/**: No such file or directory
Error: Process completed with exit code 1.
```
which happens because even though the `.triton` directory exists, it is empty. This instead uses du on `.triton` with a depth of 1.

[CI] Fix `du` failling if cache restore fails

---

CMakeLists.txt
python/setup.py

<git-pr-chain>
[Build] Add option to limit number of parallel link jobs
1. 👉 #5212 👈 **YOU ARE HERE**
1. #5213

[BUILD] Add option to limit number of parallel link jobs

---

.github/workflows/integration-tests.yml
.github/workflows/integration-tests.yml.in

<git-pr-chain>
[CI] Run tests when CI is manually triggered
Currently you can manually call a workflow dispatch, but it won't
actually run the tests because the variable enable_integration isn't
set.
1. 👉 #5216 👈 **YOU ARE HERE**

[CI] Run tests when CI is manually triggered

---

test/TritonGPU/amd/amd-reorder-instructions.mlir
third_party/amd/lib/TritonAMDGPUTransforms/ReorderInstructions.cpp

The pass was reordering scf.if operations without checking the extra dependencies coming from the region.
For now just prevent this case although this part of the code might still be fragile.

[AMD] Prevent wrong reordering of scf operations

---

third_party/amd/lib/TritonAMDGPUTransforms/MfmaGroup.cpp

If you build using the `CMakeLists.txt` and not `setup.py` and you build in `Release` then you get
```
/__w/triton/triton/third_party/amd/lib/TritonAMDGPUTransforms/MfmaGroup.cpp: In function ‘std::pair<mlir::Type, mlir::Type> mlir::TypesFromMfmaId(MLIRContext*, MfmaTypeId)’:
Warning: /__w/triton/triton/third_party/amd/lib/TritonAMDGPUTransforms/MfmaGroup.cpp:240:1: warning: control reaches end of non-void function [-Wreturn-type]
```

[AMD] cover default case in MfmaGroup

---

lib/Dialect/TritonGPU/Transforms/Utility.cpp
test/TritonGPU/combine.mlir

While working on some higher dimension tensor kernels, I noticed poor performance due to the fact that layouts wouldn't propagate to local loads. Since we do allow layout folding with local store and local alloc, this seems like a bit of an oversight. 
The change gives a 40% speed improvement on certain kernels for NVidia GPUs.
This also removes asserts in lowering for higher dimensional kernels. As far as I can tell, those restrictions aren't required in practice.

Allow Layouts to propogate to local_load

---

lib/Dialect/TritonGPU/IR/Dialect.cpp

We simplify the implementation of `getElemsPerThread` and strengthen the preconditions of `getRepForOperand`.
More generally, we should try to minimise the calls to `isAmpere` and
`isHopper` throughout the codebase. I'll do a pass fixing many of these
once we land LLs for `ldmatrix` and Hopper.

[LAYOUTS] [BE] Simplify Ampere/Hopper paths introduced in #5189

---

CMakeLists.txt

If you build with `-DTRITON_BUILD_UT=OFF` on Mac you will get something like
```
-- Looking for histedit.h
CMake Error at /opt/homebrew/Cellar/cmake/3.30.5/share/cmake/Modules/CheckIncludeFile.cmake:90 (try_compile):
Unknown extension ".c" for file
-- Looking for histedit.h - not found
/Users/runner/work/triton/triton/triton-build/CMakeFiles/CMakeScratch/TryCompile-QA06d6/CheckIncludeFile.c
try_compile() works only for enabled languages.  Currently these are:
CXX
See project() command to enable other languages.
Call Stack (most recent call first):
llvm-bd9145c8-macos-arm64/lib/cmake/llvm/FindLibEdit.cmake:28 (check_include_file)
llvm-bd9145c8-macos-arm64/lib/cmake/llvm/LLVMConfig.cmake:177 (find_package)
llvm-bd9145c8-macos-arm64/lib/cmake/mlir/MLIRConfig.cmake:10 (find_package)
``` …

[CMake] Add C as project language

---

python/test/unit/language/test_core.py

https://github.com/triton-lang/triton/pull/5153 fixed
the issue; but we missed enabling one of the disabled
case.

[AMD] Re-enable overflow test in test_reduce_layouts

---

python/setup.py

Currently the llvm path changes every time the pin updates which makes it annoying to use the included tools. e.g. I use the tablegen language server, but currently need to update my editor config every time the llvm pin changes.
This adds a stable symlink which for me is `~/.triton/llvm/llvm-macos-x64`. This will always point to the most recent version of llvm used to build triton.
As a bonus this also refactors the symlink update code which was copy-pasted a few times.

[BUILD] Add a stable symlink to llvm in the triton cache

---

lib/Dialect/TritonGPU/Transforms/Utility.cpp
test/TritonGPU/combine.mlir

recommit of https://github.com/triton-lang/triton/pull/5219
While working on some higher dimension tensor kernels, I noticed poor performance due to the fact that layouts wouldn't propagate to local loads. Since we do allow layout folding with local store and local alloc, this seems like a bit of an oversight.
The change gives a 40% speed improvement on certain kernels for NVidia GPUs.
This also removes asserts in lowering for higher dimensional kernels. As far as I can tell, those restrictions aren't required in practice.
including the "tests should be minimal" section. (Usually running …

Allow Layouts to propogate to local_load (#5219)

---

python/setup.py

[BUILD] Ensure parent directory exists before creating symlinks

---

.gitignore
include/triton/Conversion/TritonGPUToLLVM/TargetInfoBase.h
include/triton/Dialect/TritonGPU/IR/LinearLayoutConversions.h
include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/MemoryOpToLLVM.cpp
lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp
python/test/unit/language/test_core.py
test/Conversion/tritongpu_to_llvm_hopper.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.h
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ConvertLayoutOpToLLVM.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.h

The legacy path has some bugs for cases like `kWidth=1`. I'm starting to
port Hopper to use LLs to try to isolate them.

[LAYOUTS] Use LLs for Hopper whenever we wouldn't use ldmatrix

---

third_party/amd/include/Dialect/TritonAMDGPU/IR/Dialect.h
third_party/amd/include/TritonAMDGPUToLLVM/GCNAsmFormat.h
third_party/amd/include/TritonAMDGPUToLLVM/Passes.h
third_party/amd/include/TritonAMDGPUToLLVM/PatternTritonAMDGPUToLLVM.h
third_party/amd/lib/TritonAMDGPUToLLVM/BuiltinFuncToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/DecomposeUnsupportedConversions.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/GCNAsmFormat.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/TritonGPUToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/UpcastMXFPToLLVM.cpp
third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp

Refactored namespace hierachy by squeezing separate namespace hierachy together.

[AMD] NFC: Cleanup namespace hierachy

---

third_party/proton/csrc/lib/Profiler/RocTracer/RoctracerProfiler.cpp

Fixes proton unit tests when upgrading to rocm 6.2 by adding missing event handlers.
Magic number is replaced with the corresponding enum value which was added by upgrading the HIP headers https://github.com/triton-lang/triton/pull/5077.

[AMD] Fix unhandled profile event in RoctracerProfiler

---

python/tutorials/02-fused-softmax.py

The fused softmax implementation in the tutorial precompiles the kernel to query the register usage of the kernel, based on the parameters used to specialize the kernel. On top of this, it implements a simple caching system for this step based on just the block size.
As noted in https://github.com/triton-lang/triton/issues/4739, this caching is incorrect, because it's also not keyed on the `num_stages` constexpr argument or the shapes of the tensors. Since triton already has its own JIT compilation cache, and this caching bit is not really relevant to the tutorial, just remove it to get rid of the footgun.

[Tutorial] Remove incorrect caching from softmax tutorial

---

CMakeLists.txt
cmake/AddTritonUnitTest.cmake

This adds a CMake target `check-triton-unit` that builds an runs all Triton unittests written in gtest. This makes it more conveninent to rebuild and run all unittests at once with finer granularity (instead of `ninja; ctest`).

Create an aggregate `check-triton-unit` target

---

python/test/unit/language/test_libdevice.py

Just a port of one of our tests. I didn't find any similar ones in Triton itself, this should increase the test coverage.

[NFC] Add `test_bessel` into `test_libdevice.py`

---

python/test/regression/test_functional_regressions.py

This kernel was obtained using PyTorch inductor some time ago.

[NFC] Add functional regression test for cummax with bool type

---

.github/workflows/integration-tests.yml
.github/workflows/integration-tests.yml.in

As discussed in #5005 this PR just lands the updated docker image and fixes for proton test cases for rocm6.2. 
This also switches to ubuntu's default clang toolchain instead of using the one which comes with rocm.

[AMD] Upgrade AMD CI docker image

---

lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
test/Conversion/tritongpu_to_llvm.mlir

Resolves #5272
- Fixes logic for walking result struct from LLVM InlineAsm in case of multiple sub-32bit results
- Adds lit test

[BACKEND] Fix inline asm bug for multiple packed <32bit output

---

include/triton/Conversion/TritonGPUToLLVM/Utility.h
include/triton/Dialect/TritonGPU/Transforms/Passes.td
include/triton/Dialect/TritonGPU/Transforms/Utility.h
lib/Conversion/TritonGPUToLLVM/Utility.cpp
lib/Dialect/TritonGPU/Transforms/CMakeLists.txt
lib/Dialect/TritonGPU/Transforms/CoalesceAsyncCopy.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
python/src/passes.cc
test/TritonGPU/coalesce-async-copy.mlir
third_party/nvidia/backend/compiler.py

This is a follow-up to the dotOp hoisting optimization for WGMMA (MMAv3). See https://github.com/triton-lang/triton/pull/5003#discussion_r1841730886
In short, when upcasting operand A in registers prior to WGMMA and when pipelining is enabled, `AsyncCopyGLobalToLocal`'s src gmem blocked encoding will have `sizePerThread` > smem view's `vec` (along the contiguous dimension). This will resulting in multiple `cp.async` instructions being generated for a contiguous global data segment, resulting in uncoalesced loads. This was previously confirmed in ncu. See above comment for an example.
I've added a generalized fix in a new pass after the pipeliner. I've reused the logic in the LLVM lowering for `AsyncCopyGlobalToLocal` to calculate the max contiguous copy size. I compare that to the …

[NVIDIA][Backend] Add CoalesceAsyncCopy Pass for in-DotOpEnc Upcasting

---

python/setup.py

Warning:
```bash
CMake Warning:
Manually-specified variables were not used by the project:
CMAKE_VERBOSE_MAKEFILE
```

[NFC] Remove `CMAKE_VERBOSE_MAKEFILE` var

---

CMakeLists.txt
third_party/proton/CMakeLists.txt

This component is missing from the wheel building image, so we need to make the requirement more specific.
https://github.com/triton-lang/triton/actions/runs/12081047335/job/33689420657#step:6:332

[Build] Don't require Development.Embed python component

---

include/triton/Dialect/TritonGPU/Transforms/PipeliningUtility.h
lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
lib/Dialect/TritonGPU/Transforms/Pipeliner/PipeliningUtility.cpp
lib/Dialect/TritonGPU/Transforms/Pipeliner/Schedule.cpp

<git-pr-chain>
[NFC] Remove unused forOp argument from `setStageCluster`
1. 👉 #5288 👈 **YOU ARE HERE**
1. #5289
1. #5290

[NFC] Remove unused forOp argument from `setStageCluster`

---

.github/workflows/integration-tests.yml
.github/workflows/integration-tests.yml.in
python/setup.py

This way, the dependencies needed for testing are localized in one place - `setup.py` (instead of several), which makes maintenance easier.

Define `pytest-forked` and `pytest-xdist` as `tests` target deps

---

.github/workflows/integration-tests.yml
.github/workflows/integration-tests.yml.in

https://github.com/triton-lang/triton/pull/5292 failed because of macOS build. Since we don’t run any tests on macOS anyway, it’s fine to simply skip them.

[BUILD] Skip installing test related python packages

---

test/TritonGPU/loop-pipeline-hip.mlir

PR #5231 was authored before the `triton_gpu` -> `ttg` rename and CI is currently broken.

[TESTS] Forward fix for CI break

---

python/triton/_internal_testing.py

For other backends, `ptxas` may not be installed.

Search for `ptxas` only for cuda backend in `supports_tma` function

---

.github/workflows/llvm-build.yml

Right now we are hitting the following issues in
https://github.com/triton-lang/triton/actions/runs/12148740919/job/33877869004:
> The macOS-12 environment is deprecated, consider switching to
> macOS-13, macOS-14 (macos-latest) or macOS-15. For more details,
> see https://github.com/actions/runner-images/issues/10721

[BUILD] Bump macOS runner to macos-13

---

include/triton/Conversion/TritonGPUToLLVM/Utility.h
lib/Conversion/TritonGPUToLLVM/Utility.cpp
lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp

Introduce `emitHardwareTuple` helper that emits the code to compute the blockId, warpId, and laneId for a thread and returns them. This PR uses this helper in a few places.

[Backend] Tiny cleanup/refactor (NFC)

---

third_party/amd/backend/driver.py
third_party/nvidia/backend/driver.py

For `uint64_t` the literal `K` is used, which means `unsigned long long` according to https://docs.python.org/3/c-api/arg.html#numbers. It seems logical and correct to use literal `L` for type `int64_t`, which means `long long` C type.

Use `L` integer literal for `int64_t`

---

include/triton/Tools/LinearLayout.h
lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
lib/Tools/LinearLayout.cpp
test/Conversion/tritongpu_to_llvm.mlir
unittest/Tools/LinearLayoutTest.cpp

In this PR, we remove the need fro a few hacks in `invertAndCompose`,
namely the need for `getInjectiveMat` which did not work in cases where
the input and the output had a different number of registers (same with
different number of blocks) and led to the implementation of hacks on
top of it like the gymnastics with `getFreeVariable`.
We now just compute the `invertAndCompose` as the matrix `X` which is
the solution to the system `AX = B`. We add enough asserts to check that
this system has at least one solution (i.e. A is surjective) and we make
explicit the heuristic we use to minimise data-movement (not consider
dimensions that are the same, and otherwise incentivise broadcasting via
choosing the solution of minimal norm). For an explanation of how to solve
this system, see …

[LAYOUTS] Use least squares solution in invertAndCompose

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp

The insertion point for a `LocalLoadOp` after a `LocalAllocOp` op is erased could be invalid. Setting it explicitly right after the new `MemDescSubviewOp`.

[Pipeliner] Fix a dangling insertion point issue.

---

include/triton/Dialect/TritonGPU/Transforms/Utility.h
lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp

`Attribute` is already nullable, so there is no need to wrap it in an optional unless the API wants to indicate a tri-state (such as in optional parsing). This will also make a subsequent PR that enhances the layout transfer functions to support ops that don't have the same operand and/or result encodings easier to implement.

[TritonGPU] `optional<Attribute>` -> `Attribute` in transfer functions (NFC)

---

python/triton/language/core.py

[DOCS] fix formatting for dot_scaled

---

include/triton/Analysis/Utility.h
lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
test/Conversion/amd/mfma-shortcut.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM.cpp

This relands https://github.com/triton-lang/triton/pull/5139:
Adding a shortcut case for fp8 MFMA to dot operand layout conversion that avoids using shared memory, to speed up FP8 attention kernels.

[AMD] Use warp shuffle for fp8 MFMA to dot operand layout conversion

---

bin/CMakeLists.txt

All deleted libraries are either in `${triton_libs}` or in `${conversion_libs}`.

[NFC] Remove duplicate libraries in `bin/CMakeLists.txt`

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp

`local_load` should be in the same stage that the `subview` that it is using.

[PIPELINING] Fix stage for the local_load in the TMA pipelining

---

python/test/unit/language/test_compile_errors.py
python/triton/language/semantic.py
third_party/amd/backend/compiler.py
third_party/nvidia/backend/compiler.py

1. Fix the problem that [m, k, n] but not [m, n, k] is returned on the nvidia backend
2. Check both int8 and float8
3. Add a new compiler error test

[FRONTEND] Fix and improve minimum dot size checks

---

include/triton/Conversion/TritonGPUToLLVM/Utility.h
lib/Conversion/TritonGPUToLLVM/GatherOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/Utility.cpp

@lezcano pointed out in another PR that the order is confusing because typically we list the lane ID, warp ID, and blockID in this order.

[Backend] Reorder return values in `emitHardwareTuple` (NFC)

---

README.md
python/triton/compiler/compiler.py

Enable the TRITON_KERNEL_OVERRIDE feature to work on AMD assembly and binary. Currently, for the backends, it only works on Nvidia `ptx` and `cubin`.

Allow TRITON_KERNEL_OVERRIDE on .amdgcn and .hsaco files

---

include/triton/Tools/LinearLayout.h
lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/GatherOpToLLVM.cpp
lib/Tools/LinearLayout.cpp
test/Conversion/allocate_shared_memory.mlir
test/Conversion/gather_to_llvm.mlir

The original implementation side-skirts the issue of dealing with broadcasting layouts. In trying to implement layout selection for gather in the middle end, I found that it's pretty common to have tensors that are too small to avoid broadcasting. E.g. for 4 warps and 32 threads, the tensor needs to have at least 128 elements. 
It turns out that "enabling" broadcasting support is pretty trivial. Since we know that in a broadcasted layout, broadcasted threads can just index into any other "group" of threads mapped to the same gather column, and that the codegen does not vary based on the broadcasted warps, we can use the pseudo-inverse of the source layout, regardless of what it is computed to.

[Backend] Support broadcasted layouts in warp shuffle gather codegen

---

python/setup.py

For release we are not looking for something like :
``
pytorch_triton-3.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
``
not:
``
triton-3.2.0+git35c6c7c6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
``

[Release Only Changes] Remove git commit hash in wheel name

---

python/test/unit/runtime/test_cache.py
python/triton/runtime/jit.py

Also fixes an issue where the kernel would 'remember' the first backend encountered and assume that for subsequent compilations

Avoid unnecessary overhead in hot codepath

---

include/triton/Dialect/TritonGPU/Transforms/Utility.h
lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
test/CMakeLists.txt
test/TritonGPU/combine.mlir

This PR enables reusing existing `convert_layout` ops in the backwards pass if they didn't get removed through some other means. This enables the compiler to remove some tricky layout conversions by recognizing that the same computations can be reconstructed using other layout conversions.

[Layouts] Reuse existing rematerializations in backwards pass

---

include/triton/Conversion/TritonGPUToLLVM/Utility.h
include/triton/Dialect/TritonNvidiaGPU/Transforms/TMAUtilities.h
test/TritonGPU/samples/simulated-grouped-gemm.mlir
test/TritonNvidiaGPU/tma_lowering.mlir
third_party/nvidia/language/cuda/_experimental_tma.py
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TMAToLLVM.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.h

There is a bug in the version of `ptxas` we have which treats `global_stride` values as if they are 16-byte strides instead of single byte strides (presumably because the tensormap structure packs them in this format).
This centralizes the workaround to one point in the code and gates it on the current ptx version.

[TMA] Move ptxas bug workaround to TMAToLLVM and gate on ptx version

---

test/TritonGPU/amd/amd-block-pingpong.mlir
third_party/amd/lib/TritonAMDGPUTransforms/BlockPingpong.cpp

Start pingpong from the first warp.
The original PR mistakenly filed with the experiment that second warp enters into the pingpong status first. That doesn't break any functionality but performance is slightly better with starting from the first warp since it's already prioritized by default and likely to be advancing.

[AMD] Fix warp starting order in the block ping-pong #5018

---

include/triton/Dialect/TritonGPU/Transforms/Utility.h
lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
test/CMakeLists.txt
test/TritonGPU/combine.mlir

Reverts triton-lang/triton#5410
This is causes hangs/crashes in more complex examples. Reverting until a better solution is found since the follow-up doesn't fix the issue either.

Revert "[Layouts] Reuse existing rematerializations in backwards pass"

---

python/triton/runtime/jit.py

This makes the code slightly simpler, more robust, and shaves an extra microsecond from the hot (kernel cache hit) codepath.

Further simplify jit.py hot codepath

---

python/test/unit/language/test_annotations.py
python/triton/language/semantic.py

Hi triton friends ! This is my first PR here: I've tried to be thoughtful in my presentation and implementation. If I'm doing anything clearly inappropriate don't hesitate to mention so. This PR originally approached solving the problem listed below differently than it does now. Have a look at the posts edit history for the original idea.
Currently the frontend lowers arguments to signless types regardless of the signedness the user provides (see e.g. [`dtype.to_ir`](https://github.com/triton-lang/triton/blob/main/python/triton/language/core.py#L507-L508)). I'm reading a little bit between the lines here, but this seems like a conscious design decision to align with how LLVM handles integers.
While the signedness of the arguments does affect how certain operations are lowered (e.g. …

[FRONTEND] Insert zext prior to addptr with unsigned offset

---

third_party/amd/lib/TritonAMDGPUTransforms/ReorderInstructions.cpp

Re-enable reordering across ops with nested regions.
- This PR reverts the changes in [PR5203](https://github.com/triton-lang/triton/pull/5203) that prevents reordering across scf ops
- Passes  [_omitUsesFromAbove=false_ ](https://github.com/llvm/llvm-project/pull/113478) to mlir::getBackwardSlice(). This ensures that the backward slice captures the values used from above, in ops with nested regions, like scf ops.
- [x ] I have not added any `lit` tests.

[AMD] Enable reordering across ops with nested regions

---

third_party/amd/backend/compiler.py

Add a comment to clarify the usage of waves_per_eu.

[AMD] Explain waves_per_eu with comments

---

.github/workflows/wheels.yml
.github/workflows/wheels_v2.yml
python/setup.py

Add manylinux2014_x86_64 for PyTorch release 2.6
Add ability to upload build wheels to github

[release-only] Add manylinux2014_x86_64 for PyTorch release 2.6

---

test/Conversion/tritongpu_to_llvm.mlir
third_party/nvidia/include/TritonNVIDIAGPUToLLVM/PTXAsmFormat.h
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp

This splits `getRedundantDataMask` into two functions, `getFreeVariableMasks` and `emitRedundantThreadPredicate`. The returned predicate doesn't include the register index, and instead you use the free variable mask to de-duplicate the registers while looping over them (i.e. we don't emit the instruction at all).
This also allows us to fix predication for `AsyncCopyGlobalToLocal`, as we can explicitly zero out the block dim mask before calling `emitRedundantThreadPredicate`.
I also return null values if the predicate is always true, which allows us to omit the predicate entirely if there is no redundant data.

[BACKEND] Rework load-store redundant data masking

---

test/TritonGPU/amd/amd-convert-buffer-ops.mlir
third_party/amd/lib/TritonAMDGPUTransforms/ConvertToBufferOps.cpp

Hello AMD triton friends! I want to emphasize that this is an RFC. I understand the work wasn't discussed ahead of time, so it may or may not align with what you folks are doing/planning.
Buffer ops have an obvious advantage of reducing register pressure, as well as various other improvements over stanard load/store ops.
We want to start using them over at Meta. We found that the current implementation in triton is very strict, and because of this weren't able to use buffer ops without *heavy* usage of `tl.assume`.
We were able to improve the situation by expanding `verifyNonNegativeExpr` to be less conservative (eliding details on the exact changes here in favor of conversation over code). With the changes in the PR we're able to (more often) successfully convert to buffer ops. For …

[AMD] Enhance non-negative proof for buffer ops

---

third_party/amd/lib/TritonAMDGPUToLLVM/UpcastMXFPToLLVM.cpp

In gfx9 architectures, we don't have bf16 VALU ops. So instead
we handle v * scale multiplication using fp32 VALU ops. LLVM
backend can do it for us, just with unnecessary overheads.

[AMD] Use f32 arithmetic to scale bf16 for mxfp

---

test/TritonGPU/amd/amd-sched-2nd-load.mlir
third_party/amd/lib/TritonAMDGPUTransforms/ReorderInstructions.cpp

Previously the pass required a single for loop with a single dot. This doesn't work well for nested loops used for example in persistent matmul kernels.
The pass is updated to search for for-loops without other for-loops contained inside, and that contain a single tl.dot operation. Then, the transformation is applied to matching loops. The scheduleGlobalLoadLocalStore operates on the parent of the for op. This ensures it captures both the loop body and global loads that have been peeled out into a loop prologue by the pipeliner.
including the "tests should be minimal" section. (Usually …

[AMD] Generalize matmul detection in reorder instructions pass

---

python/test/unit/language/test_standard.py
python/triton/language/standard.py
python/triton/runtime/interpreter.py

Fixes #5439
Currently we end up doing `0 * inf = nan`, the fix is to bitcast to int first where `x * 0 == 0` holds.

[STANDARD] Fix inf handling in tl.flip

---

include/triton/Dialect/Triton/IR/Dialect.h
lib/Dialect/Triton/IR/Ops.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/IR/Ops.cpp
lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
unittest/Dialect/TritonGPU/DialectTest.cpp

This PR also:
- Enables backward rematerialisation and hoisting for LLs
- Adds a fold reshape(cvt) -> reshape when the layouts are structurally the same
- Removes an assert that was disallowing the use of LLs across broadcast. When this happens, the LL will not have the same shape as the tensor. We do this to match the legacy behaviour and avoid the proliferation of new layouts
- Removes the layout-specific tests from before and instead we create functional tests that test the axioms for the reshape function. We see that all the legacy layouts pass these tests.
- Temporarily tested that the legacy path and the new path agree in CI in https://github.com/triton-lang/triton/pull/5389/commits/e93638b98409f8dc4c7c41aa644d0501f2630a77

[LAYOUTS] Implement generic layout propagation through ReshapeOp

---

python/test/unit/language/test_core.py
python/triton/runtime/jit.py
third_party/amd/backend/compiler.py
third_party/nvidia/backend/compiler.py
third_party/nvidia/backend/driver.py

This change sets the launch grid attribute before calling cuLaunchKernelEx.
This change is intended to pair with load/store atomics from https://github.com/triton-lang/triton/pull/5187
and is intended to add grid synchronization similar to what cooperative groups do.
@ptillet Any recommendations on the UI for using this in code would be most welcome :-) 
- [?] This PR does not need a test because: 
I am not entirely sure how to test the use of one driver API attr versus another for this case yet.
I did add a test that exercises the launch_cooperative_grid=True launch flag but I am not confirming that the plumbing triggers the use of the API attr in test, although I did …

[NVIDIA][Launcher] NV Cooperative Grid Launching (CU_LAUNCH_ATTRIBUTE_COOPERATIVE)

---

python/tutorials/09-persistent-matmul.py

As discussed in the [multi-buffering PR], the persistent matmul should be kept as an apples-to-apples performance comparison. In particular, the existing perf results make tensor-descriptors look bad. With this updated tutorial I get results like (`K=4096, prec=fp8`):
```
├─ 1278.215 4731.062 cublas [M=8192, N=8192, K=4096]
│  └─ nan 4731.062 sm90_xmma_gemm_e4m3e4m3_e4m3f32_f32_tn_n_tilesize128x128x128_warpgroupsize1x1x1_bias_f16_execute_segment_k_off_kernel__5x_cublas
├─ 1208.855 454.774 matmul_kernel [M=8192, N=8192, K=4096]
├─ 1285.360 427.706 matmul_kernel_persistent [M=8192, N=8192, K=4096]
├─ 1330.667 413.143 matmul_kernel_descriptor_persistent [M=8192, N=8192, K=4096]
└─ 1347.254 408.057 matmul_kernel_tma_persistent [M=8192, N=8192, K=4096]
```
So on H100 tensor descriptor is a …

[TUTORIAL] Remove grouped gemm simulation from 09-persistent-matmul

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/PipeliningUtility.cpp

A failure now looks like:
```
/home/peterbell10/test.py:157:8: error: pipeliner doesn't know how to predicate this op.
tl.debug_barrier()
^
/home/peterbell10/test.py:157:8: note: see current operation: "gpu.barrier"() : () -> ()
LLVM ERROR: Fatal pipeliner error
<stack trace>
```

[BACKEND] Emit a better error when predicateOp fails

---

lib/Tools/LinearLayout.cpp
unittest/Tools/LinearLayoutTest.cpp

I found a counterexample where `invertAndCompose` was giving an incorrect result. Thanks for @lezcano for pointing out a possible solution: if input dim 0 and 4 are identity dimensions, then they are added back to the reduced inverse as dimensions 3 and 4. Them reshaping the result will assign the wrong bases to the wrong dimensions. Use a transpose instead to order the input and output dimensions correctly instead.

[Layouts] Fix `invertAndCompose` when there are identity dimensions

---

test/Conversion/nvgpu_to_llvm.mlir
third_party/nvidia/include/Dialect/NVGPU/IR/NVGPUOps.td
third_party/nvidia/lib/NVGPUToLLVM/NVGPUToLLVMPass.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMMAv2OrV3.cpp

Following @ThomasRaoux's suggestion, this way we ensure that the trans attribute is not discarded and keeps the IR clear

[IR][BACKEND] Add the trans attribute to `LoadMatrix` and `StoreMatrix` ops

---

lib/Dialect/TritonGPU/Transforms/LoopScheduling.cpp
lib/Dialect/TritonGPU/Transforms/Pipeliner/SoftwarePipeliner.cpp
test/TritonGPU/pipeline-schedule-loop.mlir

Pipelining loops containing `gpu.barrier` may not always be possible because pipeliner reorders the operations in the loop. It is would be possible to analyze if schedule allows for pipelining that would preserve the order between ops issued before the barrier and ones issued after the barrier, however for now we will simply skip such cases.

Skip pipelining loops with gpu.barrier

---

lib/Conversion/TritonGPUToLLVM/Utility.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
test/Conversion/tritongpu_to_llvm.mlir

LinearEncodingAttr's interpretation of `elemsPerThread` appears to be different from that of the TypeConverter. For `register=[[0,0],[0,0],[0,0],[0,0]]` for example, LinearEncodingAttr thinks there is 1 element per thread, but the lowering thinks there are 16 (and some for `tt.reshape`).
This fixes that by not skipping broadcasted bases when calling `::getElemsPerThread` for registers.

[LAYOUTS] Fix LinearEncodingAttr interpretation of `elemsPerThread`

---

lib/Analysis/Utility.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
test/Conversion/reduce_to_llvm.mlir
test/TritonGPU/combine.mlir

ReduceOp's lowering does not support linear layouts yet, so propagation of linear layouts across `tt.reduce` ops will cause codegen to crash. The codegen routine is generic enough to support linear layouts, so just enable it and add a few tests.

[LAYOUTS] Enable ReduceOp lowering with LinearEncodingAttr

---

.github/workflows/wheels.yml
python/setup.py

This should enable python 3.13 and 3.13t wheels and disable building python 3.8 wheels.
Related to: https://github.com/pytorch/pytorch/issues/143654
cc @ptillet @Jokeren @albanD @malfet

Enable python 3.13 wheels, remove python 3.8

---

python/triton/runtime/autotuner.py

Running the example given in the [autotune docstring](https://triton-lang.org/main/python-api/generated/triton.autotune.html) gives the error
```python
import triton
import torch
@triton.autotune(configs=[
triton.Config(kwargs={'BLOCK_SIZE': 128}, num_warps=4),
triton.Config(kwargs={'BLOCK_SIZE': 1024}, num_warps=8),
],
key=['x_size'] # the two above configs will be evaluated anytime
)
@triton.jit
def kernel(x_ptr, x_size, **META):
BLOCK_SIZE = META['BLOCK_SIZE']
if __name__ == '__main__':
x = torch.ones(8, device="cuda")
kernel[lambda _: (1,)](x, x.numel())
```
```
File "...", line 18, in <module>
kernel[lambda _: (1,)](x, x.size)
File ".../triton/runtime/jit.py", line 345, in <lambda>
return lambda *args, **kwargs: self.run(grid=grid, warmup=False, …
```

[DOCS] Correct autotune/heuristics docstrings

---

python/triton/runtime/interpreter.py

Fixes #5484. Since python objects can arbitrarily override `__contains__`, using `inspect.ismodule` seems to be the most general solution, beyond numpy arrays. Overriding a module's `__contains__` would be very strange.
```python
>>> import triton.language as tl
>>> import inspect
>>> inspect.ismodule(tl)
True
>>> inspect.ismodule(tl.core)
True
```

[INTERPRETER] Patch globals more carefully

---

python/triton/runtime/autotuner.py

I accidentally deleted a newline in https://github.com/triton-lang/triton/pull/5487 which causes the [website](https://triton-lang.org/main/python-api/generated/triton.heuristics.html) to not have the code block... oops.
Generated locally and can confirm the syntax is now correct.

[DOCS] Fix syntax in heuristics docstrings

---

include/triton/Conversion/TritonGPUToLLVM/Patterns.h
include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Conversion/TritonGPUToLLVM/DecomposeUnsupportedConversions.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/DecomposeUnsupportedConversions.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DecomposeUnsupportedConversions.cpp

Also create the `getThreadsPerWarpForOperand` interface.
This PR doesn't completely remove the decompose method because `getThreadsPerWarpForOperand` hasn't been implemented yet for some AMD specific encodings

[BACKEND] Remove mma->dot decomposition from NVIDIA backend

---

third_party/nvidia/include/cublas_types.h

https://github.com/triton-lang/triton/pull/4085 now makes it impossible to build Triton without downloading cuda libraries (see https://github.com/triton-lang/triton/issues/5449). This PR adds dummy cuda headers (not vendoring the actual ones for legal reasons), making it possible to build a functional Triton without downloading cuda for backends that don't require cuda at runtime (e.g. amd, cpu).
Note that `setup.py`'s `download_and_copy` will replace the dummy headers with downloaded headers in a normal build.
https://github.com/triton-lang/triton/blob/c1166e537552e73392d26b055ea1b505277ca242/python/setup.py#L297-L330
Fixes https://github.com/triton-lang/triton/issues/5449. See also https://github.com/triton-lang/triton-cpu/issues/202, https://github.com/triton-lang/triton-cpu/pull/203. …

[NFC] Remove dependency to cuda headers in Triton build

---

python/test/unit/language/test_core.py
python/triton/runtime/interpreter.py

This PR lowers minimal size of dot matrices available in interpreter and enables related tests.

[INTERPRETER] Enable small dot in interpreter

---

python/test/unit/language/test_core.py
python/test/unit/runtime/test_cache.py
python/triton/compiler/code_generator.py
python/triton/compiler/compiler.py
python/triton/runtime/jit.py

caveat: not serializable - i.e. doesn't work with `preload`

[FRONTEND] add support for function arguments ; enforce use of `_unsafe_update_src` to modify the source-code of a JITFunction

---

python/triton/compiler/compiler.py

This line is somewhat expensive since it reads a file from disk.
As far as I can tell it is a duplicate of this line (which is actually used):
https://github.com/triton-lang/triton/blob/d9facf3a6edbc819c80d58b87e689bc0c2632756/python/triton/compiler/compiler.py#L360

[FRONTEND] Remove unused json parse in triton.compile

---

Makefile
README.md
python/build_helpers.py
python/setup.py
test/TritonGPU/samples/descriptor-matmul-pipeline.mlir
test/TritonGPU/samples/descriptor-matmul-pipeline.mlir.in
test/TritonGPU/samples/simulated-grouped-gemm.mlir
test/TritonGPU/samples/simulated-grouped-gemm.mlir.in

It's a bit annoying to type `ninja -C python/build/cmake-.../` to run
build commands. This adds a top-level makefile that just forwards
commands down to the ninja build system so you can just type `make`.
Building and running the tests from a fresh install should now be as
simple as `make dev-install && make test`.
I also add `make golden-samples` to regenerate the golden sample tests,
which should make it fairly painless to accept a failing sample.

[DEV] Add makefile to run common dev commands

---

python/triton/_utils.py
python/triton/compiler/code_generator.py
python/triton/language/__init__.py
python/triton/runtime/jit.py
third_party/amd/backend/driver.py
third_party/nvidia/backend/driver.py

this simplifies our JIT a bunch and will make it quite a bit easier to add support for namedtuples in the future

[FRONTEND][JIT] don't stringify tuples early when computing signatures

---

include/triton/Analysis/Membar.h
include/triton/Dialect/Triton/IR/TritonOps.td
include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td
include/triton/Dialect/TritonGPU/Transforms/Passes.td
include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandFMA.cpp
lib/Conversion/TritonGPUToLLVM/FuncOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/ReduceScanCommon.h
lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp
lib/Dialect/Triton/Transforms/RewriteTensorPointer.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp
lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
lib/Dialect/TritonGPU/Transforms/F32DotTC.cpp
lib/Dialect/TritonGPU/Transforms/OptimizeThreadLocality.cpp
lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
lib/Dialect/TritonGPU/Transforms/Pipeliner/TMAStoresPipeline.cpp
lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
python/src/llvm.cc
python/test/unit/language/test_core.py
python/test/unit/runtime/test_autotuner.py
python/triton/language/semantic.py
test/TritonGPU/invalid-attributes.mlir
unittest/Dialect/TritonGPU/LinearLayoutConversionsTest.cpp
utils/generate-test-checks.py

```
codespell --ignore-words-list=ans,conver,destop,dout,interm,latops,nd,olt,repid,subtile,valu \
--skip="./third_party/*,*.mlir,*.pdf"
```
https://pypi.org/project/codespell
`conver` should be removed from the `ignore-words-list` and the following line should be cleaned up:
https://github.com/triton-lang/triton/blob/25732f0a063f025a4eb6f01a2e0939ef43a8afc7/include/triton/Dialect/TritonGPU/Transforms/Passes.td#L122
Should codespell be added to pre-commit and/or GitHub Actions?
and using the instructions it …

Fix typos discovered by codespell

---

lib/Tools/LinearLayout.cpp
third_party/f2reduce/f2reduce.cpp

The shift exponent in `uint64_t final_b = (1ull << (cols - 1)) - 1;` underflows for `cols == 0`. We can skip converting to rref for `cols <= 1` as well to avoid the issue.

Fix UB in f2reduce for cols == 0

---

python/test/unit/language/test_core.py

`_set_promotion_state` is removed in NumPy 2.0. We just turn the
contextmanager into a noop when the user has a newer NumPy version.
I tested this locally. At some point we should add NumPy 2.0 support to
CI, I guess.

Fix test_bin_op in NumPy 2.0

---

third_party/nvidia/lib/NVGPUToLLVM/NVGPUToLLVMPass.cpp

Trying to build main with clang per the readme currently hits 
`error: non-void function does not return a value in all control paths [-Werror,-Wreturn-type]`
Turning the assert into an llvm_unreachable fixes the error.

Fix build with clang

---

third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ElementwiseOpToLLVM.cpp

I noticed that some of the tests were failing when I was testing on a workstation with a consumer RTX card. Turns out that sm_89 supports fp8, but doesn't support cvt.bf16.f16
From the ptx spec:
```
cvt.bf16.{u8/s8/u16/s16/u32/s32/u64/s64/f16/f64/bf16}, cvt.{u8/s8/u16/s16/u32/s32/u64/s64/f16/f64}.bf16, and cvt.tf32.f32.{relu}.{rn/rz} require sm_90 or higher.
```
This adds a path to first convert to fp32 and then bf16 if compute compatibility is < 90,
This is already hit in the tests (specifically several test cases in test core, many variations on dot_scaled in particular).

[Nvidia] Support fp8 to bf16 casting on RTX 4000 series

---

docs/python-api/triton.language.rst

add docs for `tl.assume` as described in title.
the relative code is in `python/triton/language/core.py`  line: 2435

[Docs] add doc for `tl.assume`

---

test/Conversion/tritongpu_to_llvm.mlir
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DecomposeUnsupportedConversions.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/MemoryOpToLLVM.cpp

Get rid of special pattern that was handling previously unsupported load lowering from mmav3 shared layout to dot operand layout.
Fix lowering, so it won't go down unsupported ldmatrix path, until we add support for ldmatrix with mmav3.

Remove special handling of mmav3 -> dot load. Use ld.shared for lowering.

---

include/triton/Dialect/TritonGPU/IR/Dialect.h
include/triton/Dialect/TritonGPU/IR/TritonGPUDialect.td
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp

It was reported that triton compilation times have heavily increased
lately. The cause of this is that we very often create the associated LL
to check properties of a given Layout. We do this thousands of times,
and this gets very expensive.
In this PR, we implement a thread-safe cache for LinearLayouts. We clear this
cache after we are done with the TTGIR -> LLVM conversion.
In the future, we will make `DistributedEncoding` inherit from
`LinearLayoutEncoding`, which will mean that `DistributedEncoding`s
will always have access to their associated LinearLayout. Even in this
scenario I still think that caching will be good, as there is no real
1-to-1 correspondence between `DistributedEncoding`s and `LinearLayout`s
due to broadcasting, where we tile a layout along the tensor or we make
it …

[LAYOUTS] Cache LinearLayout creation

---

python/triton/testing.py
third_party/amd/backend/driver.py
third_party/nvidia/backend/driver.py

Currently, torch is required for importing triton and performing autotuning. This seems like a relatively heavy runtime dependency in the context of the cpu backend, as numpy can easily be used instead.
Opening here as suggested in https://github.com/triton-lang/triton-cpu/pull/205 to minimize future merge conflicts.
Ideally there would be a test for this, but with the cpu backend out-of-tree this seems hard to test.
See also https://github.com/triton-lang/triton-cpu/issues/204, https://github.com/triton-lang/triton-cpu/pull/205.
including the "tests should be minimal" section. (Usually …

[RUNTIME] Reduce runtime dependency on torch

---

include/triton/Tools/Sys/GetEnv.hpp
python/test/unit/language/test_core.py
third_party/nvidia/backend/compiler.py

Adding an option to force NV compute capability for triton. This can be done either with global env flag `TRITON_OVERRIDE_NV_CAPABILITY`, or per-kernel with `override_nv_compute_capability=` launch argument.

Adding an option to force target nv compute capability for triton

---

include/triton/Conversion/TritonGPUToLLVM/Utility.h
test/Conversion/amd/math-denorm-handling.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp

In this commit, we handled the denorm flushing behaviors of math.sqrt and math.sqrt_rn. They read HIP_FTZ to determine whether denorms should be preserved or flushed to zero.
| Backend | sqrt non-ftz                   | sqrt ftz             | sqrt_rn non-ftz | sqrt_rn ftz                            |
| ------- | ------------------------------ | -------------------- | --------------- | -------------------------------------- |
| CUDA    | sqrt.approx.f32                | sqrt.approx.ftz.f32  | sqrt.rn.f32     | sqrt.rn.ftz.f32                        |
| AMD     | scaling + llvm.amdgcn.sqrt.f32 | llvm.amdgcn.sqrt.f32 | llvm.sqrt.f32   | llvm.amdgcn.rsq.f32 + mul + refinement |
`math.sqrt` provides approximation of SQRT. In AMD backend, we use `llvm.amdgcn.sqrt.f32`, which provides direct …

[AMD] Handling denorms in lowering math.sqrt and math.sqrt_rn

---

python/test/unit/language/test_conversions.py
third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp

This commit supported upcasting FP8E4M3NV to FP16

[AMD] Support Upcasting FP8E4M3NV to FP16

---

include/triton/Dialect/Triton/IR/TritonOps.td
lib/Dialect/Triton/IR/Ops.cpp
test/Triton/invalid.mlir

The tensor type must always match the tensordesc's block type (ignoring layout). Add an MLIR verifier for that.

[Triton] Verify DesciptorLoad/StoreOp block types

---

python/test/unit/language/test_conversions.py
third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp

The logic is incorrect; we previously missed it due to test skip conditions disabling the tests. So this commit also restructures the test skip conditions.

[AMD] Disable FP8E4M3FN to FP16 upcast

---

include/triton/Dialect/Triton/IR/Utility.h
lib/Dialect/TritonGPU/Transforms/LoopScheduling.cpp
lib/Dialect/TritonGPU/Transforms/Pipeliner/AssignLatencies.cpp
lib/Dialect/TritonGPU/Transforms/ReorderInstructions.cpp

These have been contributed upstream. Also switch a few `std::` usages to `llvm::`.

[Triton] Remove unused `min/max_element` helpers (NFC)

---

test/Conversion/amd/tritongpu_to_llvm.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp

Atomics in triton have two optional attributes:
1) `sem` -- describing the memory semantics of the operation
2) `scope` -- describing which threads will see the effect of a memory operation (e.g., GPU, CTA)
Presently, the `scope` is ignored by the AMD backend and defaults to `agent`-scope in the emitted LLVM (which roughly corresponds to `gpu` memscope in triton). This is correct (in most cases? maybe not all?), as this is a "stricter" scope than CTA (and I'm guessing it is rare that system scope is needed for AMD kernels, so no bugs have shown up). That being said, emitting atomics at CTA scope can be more efficient since there can be fewer cache invalidations/barriers.
I think that this is fixable by just passing through the attribute to the generated `llvm.atomicrmw` op. There are some …

[AMD][Atomics, BugFix] Atomics should use the user-provided memscope

---

python/triton/compiler/compiler.py
third_party/amd/backend/compiler.py
third_party/nvidia/backend/compiler.py

there is currently a weird bug causing capability overrides to persist when users pass `arch=None`. Rather than making `CUDABackend.sw_capability` stateful, we now retrieve capability lazily from compilation options
also fix an amd bug encountered in the wild

[FRONTEND] capability override bugfix

---

third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp

We found regressions for moe kernel with fp8 inputs. This PR effectively reverts part of #4767 and disables the swap-operand feature for fp8 inputs matmul kernels for now while we investigate the regression.

[AMD] Disable swap operands for fp8 matmul

---

include/triton/Analysis/Allocation.h

I was seeing non-deterministic SMEM allocation sizes and offsets across compilations with same source and compiler. It seems due to scratch buffers processed in a non-deterministic order, due to the use of `DenseMap`. Using `MapVector` should fix it.

[backend] Ensure a deterministic allocation order of scratch smem buffers

---

README.md

This update adds information about the `MLIR_ENABLE_DIAGNOSTICS` option to the README. Enabling this option allows for the emission of IR and stack traces, which is useful for debugging purposes. As future diagnostic information may not automatically include emitted IRs, this update ensures that users are informed about how to enable this feature if they wish to view the IRs with diagnostics.

[README] Adds explanation of `MLIR_ENABLE_DIAGNOSTICS`

---

lib/Analysis/Allocation.cpp
test/Analysis/test-allocation.mlir

Allocating smem buffers in size descending order instead of their creation order seems to reduce smem usage by 10% in general, which allows our kernel to use bigger tile size. The rationale behind this is to reduce the fragmentation caused by bigger buffers decomposing small buffers.

[backend] Allocating smem buffers in size descending order

---

python/test/unit/language/test_conversions.py
python/test/unit/language/test_core.py
third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp

This commit fixed and enabled fp8e4m3nv to fp16 upcasting.
In order to properly handle denorms with LUT, this operation is no longer vectorized.

[AMD] Fix and enable upcasting fp8e4m3nv to fp16

---

include/triton/Dialect/Triton/IR/Dialect.h
lib/Analysis/Utility.cpp
lib/Dialect/Triton/IR/Ops.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/IR/Ops.cpp
lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
test/Conversion/reduce_to_llvm.mlir
test/Conversion/tritongpu_to_llvm.mlir
test/TritonGPU/combine.mlir
unittest/Dialect/TritonGPU/DialectTest.cpp

I will first reland the three PRs that were originally reverted in https://github.com/triton-lang/triton/pull/5528
Then, I will put up a forward fix + regression test for the errors we were seeing
when doing reduce(LinearLayout).
This reverts commit 3ed479f2f91a1d94dacb547115d357f5ce3219d8.

[LAYOUTS] Reland ReshapeOp propagation + Enable reduce(LinearLayout).

---

include/triton/Conversion/TritonGPUToLLVM/Utility.h
include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/Utility.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
python/test/unit/language/test_core.py

To do so, we implemented three things:
- Implement `delinearize` for arbitrary LinearLayouts
- Generalisations of ReduceOpHelper methods
- Use `getNumWarps(mod)` rather than `getWarpSize(srcLayout)`
The first error was already noted in https://github.com/triton-lang/triton/pull/5477#issuecomment-2557720717
The last issue is a bit more problematic. It turns out that the current
implementation of `LinearEncodingAttr::getWarpSize` actually implements
`getWarpsPerCTAWithUniqueData`. Now, this is what we want 99% percent of
the time, so I think this is correct. That being said, after this PR is
merged, I will put up a PR removing `getWarpSize` and
`getNumWarpsPerCTA` in favour of the module-level ops. In the future, we
should simply remove all uses of `.*WithUniqueData` functions in favour
of …

[LinearLayouts] Fix Reduce(LinearEncodingAttr)

---

lib/Conversion/TritonGPUToLLVM/Utility.cpp
lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
python/test/unit/language/test_core.py

We also skip the LinearLayout test for HIP as it's currently failing.
Regarding the use of `getWarpSize` and `getNumWarpsPerCTA`, which are not correct for LinearLayouts with broadcasting as noted in https://github.com/triton-lang/triton/pull/5617, we found almost all the uses are in AMD land. Changing these into calling the functions that act on the module is tricky, as the module is not currently accessible at the caller site in most of them. As such, we leave this refactor up to AMD folks.

[LinearLayouts] Faster pext algorithm

---

.flake8
python/setup.py
python/test/unit/language/test_core.py
third_party/proton/proton/__init__.py

[NFC] Cleanup `flake8` related code as unused

---

include/triton/Analysis/Utility.h
include/triton/Dialect/TritonGPU/IR/LinearLayoutConversions.h
include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
include/triton/Dialect/TritonGPU/IR/TritonGPUDialect.td
include/triton/Dialect/TritonGPU/Transforms/Utility.h
lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/GatherOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/Utility.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp
lib/Dialect/TritonGPU/IR/Ops.cpp
lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
lib/Dialect/TritonGPU/Transforms/CoalesceAsyncCopy.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp
unittest/Dialect/TritonGPU/DialectTest.cpp

We now support LL conversions for all our layouts, and so does XPU
downstream. As such, we now make `toLinearLayout` support mandatory
in line with our progressive transition of our IR towards LLs.

[NFC] Make toLinearLayout not return an Optional

---

include/triton/Conversion/TritonGPUToLLVM/Utility.h
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandFMA.cpp
lib/Conversion/TritonGPUToLLVM/MemoryOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/TypeConverter.cpp
lib/Conversion/TritonGPUToLLVM/Utility.cpp
lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp
test/Conversion/tritongpu_to_llvm.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandHelper.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandHelper.h
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandWMMA.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMMAv2OrV3.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/WGMMA.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/MemoryOpToLLVM.cpp

After this PR, we no longer extract strides from llvm struct. Instead, we can get the strides through the `getStrides(memdesc, loc, rewriter)`, which extracts constant numbers from the allocation shape.

[BACKEND] Deprecate the `strides` field in `SharedMemoryObject`

---

python/test/unit/language/test_conversions.py
python/test/unit/language/test_core.py
third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp

This commit supported FP16 to FP8E4M3NV(FP8E4M3FN) conversion on AMD backend.

[AMD] Support FP16 to FP8E4M3NV Conversion

---

python/test/unit/language/test_core.py
third_party/amd/lib/TritonAMDGPUToLLVM/UpcastMXFPToLLVM.cpp

A minor bug used the same logic for sharing scales between threads in both the MFMA16 and MFMA32 paths. Needed a div by 8 for the MFMA16 path instead of 16 (used for the MFMA32 path).
Also enable AMD tests for `test_scaled_dot`.

Fix bug in upcast mxfp -> fp16

---

third_party/amd/lib/TritonAMDGPUToLLVM/UpcastMXFPToLLVM.cpp

This PR improves the logic to upcast mxfp4 to bf/fp16 values. Previously, we process 4 mxfp4 values at a time with about 23 instructions. Therefore, it takes **46** instructions to upcast 8 mxfp4 elements. This PR processes 8 mxfp4 values at a time with **20** instructions.

[AMD] [mxfp upcast] Reduce instructions to upcast mxfp4

---

lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
test/TritonGPU/accelerate-matmul.mlir
test/TritonGPU/combine.mlir

We remove the SinkTranspose. This was initially put in place to
circunvent the issue of not being able to propagate the MMA layout past
a transpose. This was landed in
https://github.com/triton-lang/triton/pull/5403 so this pass not
necessary anymore.
The next step will be to get rid of the `transposeDot` part of the pass
and instead integrate it into a different more generic pass that checks
whether a dot operand inputs should be transposed to take advantage of
the reg x shmem MMAv3 op.

[ScaledDot] Remove SinkTranspose from ScaledDot

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
python/test/unit/hopper/test_experimental_tma.py
test/TritonGPU/loop-pipeline-hopper.mlir

When we determine the SMEM encoding for a multi-buffered SMEM, we should reuse the encoding of the operand SMEM created by `AccelerateMatmul`. We do have such logic in the code, but currently there is additional MMAv3-specific code path before it that creates a fresh encoding which, in practice, always coincides with the existing operand encoding.  
https://github.com/triton-lang/triton/blob/main/lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp#L337-L361
The exception to this is multi-buffering of TMA load. `AccelerateMatmul` may create an encoding [whose `order` is an transpose of the register `order`]( https://github.com/triton-lang/triton/blob/main/lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp#L151-L159). We cannot use such encoding as the destination of TMA. …

[SWP] Remove redundant SMEM encoding creation for MMAv3

---

python/test/unit/runtime/test_driver.py
third_party/nvidia/backend/driver.py

If a kernel is launched on a thread which has not initialized a CUDA context (as can happen in the linked issue), it will throw an error. A simple fix is to call `cudaFree(0)` to establish a device context.
Fixes #3729

[3.2 cherry pick] Ensure device context before launching kernel (#3731, #5276)

---

include/triton/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVMBase.h

This pass seems buggy when we have some types of broadcasting. We
deactivate it for now so that it doesn't bite us and we'll reimplement
it generically at a later point.

[LAYOUTS] Deactivate maybeDuplicate pass for LLs

---

third_party/amd/lib/TritonAMDGPUTransforms/BlockPingpong.cpp

It has been broken since #5625, GEMM generates incorrect result with pingpong enabled.
Fixed by updating the way creating MemDescType for the subviews.

[AMD] Quick fix to the regression with pingpong

---

lib/Dialect/Triton/IR/Ops.cpp
lib/Dialect/TritonGPU/IR/Ops.cpp
test/Triton/combine.mlir
test/TritonGPU/canonicalize.mlir
test/TritonGPU/optimize-locality.mlir

Don't fold allow_reorder reshape ops. This preserves the reshape and importantly the allow_reorder bit so that OptimizeThreadLocality knows it may chose a layout for the reduction in the case when the src and dst shape of the reshape is the same.
Change CanonicalizeConvertFromReshape to run on efficient_layout. This allows removal of the convert layout op between the reshape and reduction.

Improve thread locality for reduction ops

---

.github/workflows/wheels_v2.yml

We are ready for release 3.2.x hence enable promotion to pypi

Release Only - Enable pypi promotion for 3.2.x release

---

lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
test/TritonGPU/combine.mlir

This PR implements a transform in `TritonGPURemoveLayoutConversions` that is similar to how conversions are hoisted above exts or broadcasts -- conversions are hoisted into conditionals if only one of the two branches can be rematerialized.
E.g.
```mlir
%0 = scf.if %cond {
%1 = tt.load %ptr
yield %1
} else {
yield %cst
}
%2 = ttg.convert_layout %0
use(%2)
// Becomes
%0 = scf.if %cond {
%1 = tt.load %ptr
%2 = ttg.convert_layout %1
yield %2
} else {
yield %cst
}
use(%2)
```
This can occur in kernels with fused outer loops: conversions in the inner loop don't get hoisted into the prologue.

[Layouts] Propagate layouts into conditionals

---

python/test/unit/language/test_core.py
test/Conversion/amd/tritongpu_to_llvm.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp

- Does not require shared memory
- Grouping is done using O(n) algorithm
Algorithm description:
1. Detect groups and gather additional info related to relative position within the group
in a greedy maner within a single wavefront
2. Rearange data between threads to form continuous groups using `permute` instructions
3. Reduce groups to their leading threads via `bpermute` instructions
4. Leading threads perform global atomic operation

[AMD][Atomic] Implement intrawave reduction algorithm for atomic operation

---

lib/Dialect/TritonGPU/Transforms/FuseNestedLoops.cpp

The order of evaluating of function arguments unspecified according the standard.
It caused a lit test failure on my local and all AMD machines I tried.
Create `cmpi sge` and `cmpi slt` operation separatly to determine the order of them.
Fixed `fuse-nested-loops:multiple_loops` lit test.

[AMD] Fix `fuse-nested-loops` lit test
