- CMakeLists.txt
see link for similar issue: https://github.com/tensorflow/tensorflow/issues/12998
> fix llvm build inside conda environment

- include/triton/runtime/function.h
- lib/runtime/function.cc
- python/src/bindings.cc
- python/tests/test_blocksparse.py
- python/tests/test_matmul.py
- python/triton/kernel.py
- python/triton/ops/blocksparse/matmul.py
- python/triton/ops/blocksparse/softmax.py
- python/triton/ops/conv.py
- python/triton/ops/matmul.c
- python/triton/ops/matmul.py
- tutorials/01-matmul.cc
This PR contains a set of bug-fixes in the auto-tuning module as well as some improvements of the auto-tuning API. Also include benchmark function for existing ops.
> Improvements w/ Auto-Tuning and standard benchmarks

- include/triton/codegen/selection/generator.h
- include/triton/ir/context_impl.h
- include/triton/ir/type.h
- lib/codegen/selection/generator.cc
- lib/ir/context.cc
- lib/ir/type.cc
- python/src/triton.cc
- python/triton/__init__.py
- python/triton/code_gen.py
- python/triton/language.py
This add some preliminary tl.float8 support along with float8 => float16 casting on NVIDIA GPU. Buggy and should only be used with care for now.
> [LANG] Preliminary FP8 support

- lib/codegen/selection/generator.cc
- lib/ir/dispatch.cc
* Added fp32 -> fp8 for ConstantFP = 0
* Added some more robust semantic check for atomic_add
> [codegen] small bugfix

- python/triton/code_gen.py
> Update TensorWrapper with device attribute

- lib/codegen/selection/generator.cc
- lib/driver/kernel.cc
Current version of masked load on master uses branch. Which works "okay" but (1) makes the resulting PTX hard to read, and (2) has lower affinity with ptxas 11.3. This PR converts the masked load to inline predicated `ld.global.cg` instructions.
> [CODEGEN] Switching to predicated inline PTX for LDGs

- include/triton/driver/module.h
- lib/driver/module.cc
- python/tutorials/02-fused-softmax.py
> [DRIVER] Now giving the option to use system ptxas through environment variable

- include/triton/codegen/analysis/layout.h
- include/triton/codegen/transform/membar.h
- include/triton/ir/utils.h
- lib/codegen/pass.cc
- lib/codegen/transform/membar.cc
- lib/ir/utils.cc
Membar pass on top of master is buggy with asynchronous copy. For example, it doesn't wait for asynchronous copies to complete before recoalescing accumulator in GEMM, which leads to undefined behavior when the program doesn't enter the loop. This PR proposes
> [CODEGEN] Bugfix in membar pass

- include/triton/codegen/pass.h
- include/triton/codegen/selection/generator.h
- lib/codegen/pass.cc
- lib/codegen/selection/generator.cc
- python/src/triton.cc
- python/triton/code_gen.py
- python/triton/ops/blocksparse/softmax.py
/!\ USE CAREFULLY - THIS CAN BREAK CORRECTNESS IF MISUSED /!\
> [FRONTEND] Added compilation flag to force use of `.nc` cache modifier in DRAM loads. 

- .ci/build-website.yml
- python/triton/testing.py
- python/tutorials/01-vector-add.py
- python/tutorials/02-fused-softmax.py
- python/tutorials/03-matrix-multiplication.py
Some grammar fixes in the tutorial, and also more informative plots. Also, now the CI will build the website daily automatically.
> [DOCS] Improved documentation and integration in CI

- .github/workflows/documentation.yml
- docs/getting-started/installation.rst
- python/setup.py
Update references to the old repository owner/URL.
> Update `ptillet` to `openai`

- README.md
> [README] GitHub format

- python/triton/code_gen.py
> [PYTHON] Improved error message for CPU

- CMakeLists.txt
> [BUILD] More portable detection of terminfo

- python/tutorials/01-vector-add.py
- Expanded variable naming for clarity
- Added more comments explaining how the blocking and `program_id` parts work
> Improve tutorial readability

- python/tutorials/02-fused-softmax.py
Renaming, adding intermediate variables, and adding some explanation. Re-ran the benchmark and got same results as original.
> Improve readability of 02-fused-softmax.py

- include/triton/ir/dispatch.h
- include/triton/ir/metadata.h
- include/triton/tools/sys/exec.hpp
- lib/codegen/analysis/align.cc
- lib/driver/module.cc
- lib/ir/dispatch.cc
- python/src/triton.cc
- python/triton/language.py
* switched to system `ptxas` when present in `PATH`
* added `max_contiguous` compiler hint
> [CODEGEN/DRIVER] Tweaks for performance optimization

- python/triton/code_gen.py
> [FRONTEND] Added option to `reset_to_zero` arguments before each autotuner run

- python/test/test_matmul.py
- python/triton/ops/matmul.py
Most of the configs were actually disabled for triton.ops.matmul in the 1.0.0 release :scream:
> [PYTHON] re-activated auto-tuner configurations for triton.ops.matmul

- docs/conf.py
- docs/python-api/triton.language.rst
- docs/python-api/triton.rst
- python/triton/code_gen.py
- python/triton/language.py
- python/tutorials/03-matrix-multiplication.py
- Added docstr for `autotune`, `Config`, `heuristics`
- Added docstr for atomics
- Hiding internal `_builder` argument used for built-in language primitives
- Re-factor docstr to use common templates between similar functions.
> [DOCS] Various improvements

- python/tutorials/01-vector-add.py
So that add works for any dimensional tensor
> Use numel for num_elements

- python/test/unit/operators/test_blocksparse.py
Minor, but making sure that a couple more configurations are covered (more block sizes and torch.dtype for some of the tests). Does not change any logic
> [minor][blocksparse] Unit testing / safeguarding a couple more configurations

- python/triton/code_gen.py
Should be robust against programs being abruptly killed while writing  to cache
> [FRONTEND] Compute cache now supports atomic writes

- python/triton/__init__.py
> [PYTHON] Fix up __version__

- python/triton/code_gen.py
argument to be specialized for cache_key
> [FRONTEND] Add do_not_specialize argument to triton.jit to prevent

- python/triton/code_gen.py
Seems to be causing issues when the current device is not 0. No bandwidth to fix this right now, but I will soon be working on examples and improvements for peer-to-peer communication in Triton.
> [FRONTEND] Disable P2P

- .github/workflows/integration-tests.yml
- lib/codegen/analysis/layout.cc
- lib/codegen/selection/generator.cc
- lib/ir/instructions.cc
- python/src/triton.cc
- python/test/unit/language/test_core.py
- python/test/unit/language/test_random.py
- python/triton/code_gen.py
- python/triton/language/core.py
- python/triton/language/random.py
- Now JIT specializes kernels for `int` arguments when they can't fit in 32-bits
- Fixed bug in arange
- RNG now supports 64-bit seeds properly
> [LANG] Various (relatively minor) improvements

- lib/codegen/transform/pipeline.cc
- python/test/unit/language/test_core.py
* Fix an issue that occurs when `dot` doesn't depend on `load`.
> Pipeline fixup

- python/test/unit/language/test_random.py
- python/triton/language/random.py
> [LANGUAGE] Fixed issue with duplicates in large arrays of random uniform numbers

- python/triton/code_gen.py
> Revert "[FRONTEND] Disabling cache by default"

- python/setup.py
- python/src/triton.cc
- python/triton/code_gen.py
- python/triton/language/core.py
There may still be room for improvement.
> [FRONTEND] Significantly reduce kernel launch time

- lib/driver/llvm.cc
Using `tmpnam` and also deleting temporaries when an exception is raised
> [DRIVER] Fixed some issue in how ptxas is used

- include/triton/ir/builder.h
- include/triton/ir/dispatch.h
- include/triton/ir/instructions.h
- lib/codegen/selection/generator.cc
- lib/codegen/transform/peephole.cc
- lib/codegen/transform/pipeline.cc
- lib/ir/builder.cc
- lib/ir/dispatch.cc
- lib/ir/instructions.cc
- python/src/triton.cc
- python/triton/language/core.py
> [FRONTEND] Added `volatile` flag for load

- .github/workflows/integration-tests.yml
- .isort.cfg
- python/setup.cfg
- python/setup.py
- python/test/regression/test_performance.py
- python/triton/__init__.py
- python/triton/code_gen.py
- python/triton/language/core.py
- python/triton/ops/blocksparse/matmul.py
- python/triton/tools/disasm.py
- python/tutorials/02-fused-softmax.py
Also a fix a few more style issues from the "aggressive" mode of autopep8.
> add isort and autopep8 config files and check on CI

- .github/workflows/integration-tests.yml
- python/bench/bench_matmul.py
- python/setup.cfg
- python/setup.py
- python/test/regression/test_performance.py
- python/test/unit/language/test_core.py
- python/test/unit/language/test_random.py
- python/triton/__init__.py
- python/triton/code_gen.py
- python/triton/language/__init__.py
- python/triton/language/core.py
- python/triton/ops/__init__.py
- python/triton/ops/blocksparse/__init__.py
- python/triton/ops/cross_entropy.py
- python/triton/ops/matmul.py
- python/triton/tools/disasm.py
- python/tutorials/01-vector-add.py
I've been using this locally to find errors without running tests, and now that we're using autopep8, it passes with minimal suppressions. This is also what turned up the issues with the tutorials, which were fixed in #422.
> check python with flake8

- python/test/unit/language/test_core.py
- python/test/unit/operators/test_matmul.py
- python/triton/code_gen.py
- python/triton/ops/matmul.py
- python/triton/ops/matmul_perf_model.py
- python/triton/testing.py
> V2.0 bf16 test

- lib/codegen/pass.cc
- lib/ir/dispatch.cc
- python/src/triton.cc
- python/test/unit/language/test_core.py
- python/test/unit/runtime/test_cache.py
- python/triton/code_gen.py
- python/triton/language/core.py
- python/triton/language/random.py
default argument, GIL, constexpr bugfixes, etc.
> [FRONTEND] Bunch of fixes here and there

- include/triton/ir/dispatch.h
- include/triton/ir/instructions.h
- include/triton/ir/module.h
- lib/codegen/selection/generator.cc
- lib/ir/dispatch.cc
- lib/ir/instructions.cc
- python/src/triton.cc
- python/triton/code_gen.py
- python/triton/language/core.py
IEEE-style rounding is *slow*. Using `div.full` on PTX resolves a lot of perf issues and has a maximum ULP of 2.
> [BACKEND] float division is now approximate by default

- python/triton/code_gen.py
stream when enqueueing kernels
> [FRONTEND] Added possibility for users to change how to querry current

- python/tutorials/05-layer-norm.py
Comments are still scarce. Significant efforts  on improving docs will come later.
> [TUTORIALS] Layer norm tutorial now uses residency control

- include/triton/ir/instructions.h
- include/triton/ir/type.h
> Add empty return value and remove protect for contained_tys_vec_t

- python/triton/code_gen.py
> Default cache dir to /tmp/triton_$USER

- python/triton/code_gen.py
Simplified mangling. Restored behavior that always initialized device to avoid invalid context when the first op in backward pass is with Triton (e.g., unit tests).
> [FRONTEND] A couple of bugfixes

- include/triton/codegen/analysis/layout.h
- include/triton/codegen/transform/coalesce.h
- include/triton/codegen/transform/cts.h
- include/triton/ir/builder.h
- include/triton/ir/function.h
- include/triton/ir/instructions.h
- include/triton/ir/utils.h
- lib/codegen/analysis/allocation.cc
- lib/codegen/analysis/layout.cc
- lib/codegen/analysis/liveness.cc
- lib/codegen/analysis/swizzle.cc
- lib/codegen/pass.cc
- lib/codegen/selection/generator.cc
- lib/codegen/transform/coalesce.cc
- lib/codegen/transform/cts.cc
- lib/codegen/transform/inline.cc
- lib/codegen/transform/peephole.cc
- lib/ir/basic_block.cc
- lib/ir/builder.cc
- lib/ir/instructions.cc
- lib/ir/utils.cc
- python/test/unit/language/test_core.py
- python/triton/code_gen.py
- python/triton/language/core.py
- python/triton/language/semantic.py
- python/tutorials/06-fused-attention.py
Some backend compiler improvements
> [BACKEND] Compiler improvements

- python/triton/code_gen.py
> Fix f-string for older python

- python/tutorials/05-layer-norm.py
This improves ln backward perf in tutorial for smaller (more common) sizes from 
```
layer-norm:
N      Triton       Torch
0    1024.0  140.434291  323.368435
1    1536.0  165.309420  368.640009
2    2048.0  207.392405  402.885254
3    2560.0  244.780886  435.744691
4    3072.0  284.664100  460.800012
5    3584.0  322.157308  407.658756
6    4096.0  357.469093  406.214885
7    4608.0  380.041232  408.088565
8    5120.0  410.969891  412.348995
9    5632.0  438.857160  423.724120
10   6144.0  463.698105  427.408686
11   6656.0  488.513781  432.910585
12   7168.0  512.000004  406.695045
13   7680.0  534.260858  406.887430
14   8192.0  556.963156  429.275114
15   8704.0  566.113842  419.469872
16   9216.0  583.598937  432.000001
17   9728.0  600.185100  435.582084
18  10240.0  617.487431 …
```
> adjust heuristics for dwdb kernel in layer_norm tutorial

- python/test/unit/language/test_core.py
- python/triton/language/semantic.py
Output informative error message when broadcast does not work for unmatched shapes.
> Raise broadcast error

- lib/codegen/selection/generator.cc
- lib/codegen/transform/coalesce.cc
- python/test/unit/language/test_core.py
- python/triton/language/core.py
This should fix #558 , #573  and #574
> [BACKEND] Fix some bugs (atomics, a segfault...)

- include/triton/codegen/analysis/layout.h
> Fix inconsistent struct declaration instead of class.

- cmake/FindLLVM.cmake
- docs/programming-guide/chapter-2/related-work.rst
- include/triton/codegen/analysis/layout.h
- lib/codegen/selection/generator.cc
- lib/driver/llvm.cc
- lib/ir/print.cc
- python/src/functions.h
- python/test/regression/test_performance.py
- python/test/unit/language/test_core.py
- python/triton/code_gen.py
- python/triton/language/core.py
- python/triton/ops/blocksparse/matmul.py
- python/triton/testing.py
- python/triton/tools/disasm.py
- python/tutorials/02-fused-softmax.py
- python/tutorials/03-matrix-multiplication.py
This PR applies minor spelling fix in comments and string literals to `master`.  It shouldn't hurt anything.
> [Triton] Fix spelling

- cmake/FindLLVM.cmake
- docs/programming-guide/chapter-2/related-work.rst
- include/triton/Conversion/TritonGPUToLLVM/PtxAsmFormat.h
- lib/Conversion/TritonGPUToLLVM/PtxAsmFormat.cpp
- lib/Dialect/TritonGPU/Transforms/Pipeline.cpp
- lib/driver/llvm.cc
- python/src/triton.cc
- python/triton/compiler.py
- python/triton/language/core.py
- python/triton/ops/blocksparse/matmul.py
- python/triton/tools/disasm.py
- python/tutorials/02-fused-softmax.py
- python/tutorials/03-matrix-multiplication.py
This PR corrects spelling like #664 for Triton-MLIR. It should not break anything.
> [Triton-MLIR][DOCS] Correct spelling

- python/triton/compiler.py
Fix for this error coming from TorchInductor + hf_GTP2:
```
File "/tmp/torchinductor_jansel/co/ccolscz653s5yh7sb7jtf5aivftaordcns7f2lnxrn5yglog3bws.py", line 1378, in call
kernel0[grid(2048)](gt_2, addmm_1, gt, embedding, embedding_1, gt_5, addmm_5, gt_3, addmm_3, gt_8, addmm_9, gt_6, addmm_7, gt_11, addmm_13, gt_9, addmm_11, gt_14, addmm_17, gt_12, addmm_15, gt_17, addmm_21, gt_15, addmm_19, gt_20, addmm_25, gt_18, addmm_23, gt_23, addmm_29, gt_21, addmm_27, gt_26, addmm_33, gt_24, addmm_31, gt_29, addmm_37, gt_27, addmm_35, gt_32, addmm_41, gt_30, addmm_39, gt_35, addmm_45, gt_33, addmm_43, gt_36, addmm_47, getitem_85, reciprocal_36, getitem_78, reciprocal_33, getitem_71, reciprocal_30, getitem_64, reciprocal_27, getitem_57, reciprocal_24, getitem_50, reciprocal_21, getitem_43, …
```
> Fix filename too long error in new runtime

- .gitmodules
- CMakeLists.txt
- python/setup.py
- python/src/pybind11/attr.h
- python/src/pybind11/buffer_info.h
- python/src/pybind11/cast.h
- python/src/pybind11/chrono.h
- python/src/pybind11/common.h
- python/src/pybind11/complex.h
- python/src/pybind11/detail/class.h
- python/src/pybind11/detail/common.h
- python/src/pybind11/detail/descr.h
- python/src/pybind11/detail/init.h
- python/src/pybind11/detail/internals.h
- python/src/pybind11/detail/type_caster_base.h
- python/src/pybind11/detail/typeid.h
- python/src/pybind11/eigen.h
- python/src/pybind11/embed.h
- python/src/pybind11/eval.h
- python/src/pybind11/functional.h
- python/src/pybind11/gil.h
- python/src/pybind11/iostream.h
- python/src/pybind11/numpy.h
- python/src/pybind11/operators.h
- python/src/pybind11/options.h
- python/src/pybind11/pybind11.h
- python/src/pybind11/pytypes.h
- python/src/pybind11/stl.h
- python/src/pybind11/stl/filesystem.h
- python/src/pybind11/stl_bind.h
> Revert "[pybind11] Use git-submodule for pybind11"

- .github/workflows/integration-tests.yml
- .gitmodules
- CMakeLists.txt
- python/setup.py
- python/src/pybind11/attr.h
- python/src/pybind11/buffer_info.h
- python/src/pybind11/cast.h
- python/src/pybind11/chrono.h
- python/src/pybind11/common.h
- python/src/pybind11/complex.h
- python/src/pybind11/detail/class.h
- python/src/pybind11/detail/common.h
- python/src/pybind11/detail/descr.h
- python/src/pybind11/detail/init.h
- python/src/pybind11/detail/internals.h
- python/src/pybind11/detail/typeid.h
- python/src/pybind11/eigen.h
- python/src/pybind11/embed.h
- python/src/pybind11/eval.h
- python/src/pybind11/functional.h
- python/src/pybind11/iostream.h
- python/src/pybind11/numpy.h
- python/src/pybind11/operators.h
- python/src/pybind11/options.h
- python/src/pybind11/pybind11.h
- python/src/pybind11/pytypes.h
- python/src/pybind11/stl.h
- python/src/pybind11/stl_bind.h
> Revert "[Triton-MLIR][pybind11] Update pybind11 to 2.10.0"

- lib/Dialect/TritonGPU/Transforms/Combine.cpp
More work incoming to avoid infinite loops in a more principled way.
> [OPTIMIZER] Added `DotOp` to the list of expensive ops we don't want to rematerialize.

- python/src/triton.cc
Without this patch, a debug version of python complains that:
```
Fatal Python error: Python memory allocator called without holding the GIL
Python runtime state: initialized
```
The diff looks bad but it is only indenting the whole function and moving all the python-related code at the bottom.
> Make sure to hold the gil when creating python objects

- lib/codegen/analysis/layout.cc
`is_multistage_pipe_phi()` assumes that "a value" selected by a phi node is defined in its incoming basic block. This assumption is wrong (`PHI` would choose `%x` that appears in `BB0` when the incoming basic block is `BB1`), however.
This breaks `shared_layout::extract_N_bufferable()`, which assumes that `values_0` (return values of `is_multistage_pipe_phi()`) are all defined in `bb0` (i.e., an incoming basic block of the phi node) (https://github.com/openai/triton/blob/master/lib/codegen/analysis/layout.cc#L430-L437)
This problem happens if two matmul kernels (in a tutorial) is invoked consecutively in a single Triton function.
Return `false` (no optimization) if if the parent basic block is different from the incoming basic block (though perhaps there is a way to handle it properly).
> [CODEGEN] Fix extract_N_bufferable in layout analysis

- python/test/unit/language/test_core.py
- python/triton/language/semantic.py
Fixes #532, all 3 inputs to where have to be broadcast together.
> fix broadcasting for where

- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- python/tests/test_gemm.py
- python/triton/compiler.py
- test/Conversion/tritongpu_to_llvm.mlir
ConvertLayout blocked->shared & mma->blocked hasn't been verified for correctness yet. 
Just merge this PR to align with other folks.  The verification for correctness is ongoing right on the moment.
> [Triton-MLIR][Backend] Support ConvertLayout blocked->mma

- python/test/unit/language/test_core.py
- python/triton/language/semantic.py
Sorry forgot this case in #729, and our tests are crashing
> properly broadcast scalar where condition

- lib/driver/llvm.cc
This also makes codegen simpler by avoiding special handling of eviction policies
> [DRIVER] Bumped CUDA requirement to 11.4+. This is to avoid bad performance surprises as older `ptxas` are much slower.

- lib/Conversion/TritonToTritonGPU/TritonToTritonGPU.cpp
Fix LoadOp Triton->TritonGPU conversion when there is only mask in LoadOp.
> Fix LoadOp Triton->TritonGPU conversion

- lib/Analysis/AxisInfo.cpp
- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
- python/tests/test_gemm.py
- python/triton/compiler.py
1, Disable static loop unrolling in the frontend by default;
2, A minor fix in axisAnalysis in order to support scf;
3, A minor fix in TritonGPUToLLVM to support swizzling.
> [Triton-MLIR] Minor fixes related with scf/swizzling support

- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
- lib/Conversion/TritonToTritonGPU/TritonToTritonGPU.cpp
- python/src/triton.cc
- python/tests/test_core.py
Disabled modulo test (due to change in behavior for `frem` in nvptx between llvm-11 and llvm-14) and bfloat16 (will require some work to emulate in software similar to how it's done in `master`)
> [FRONTEND] Enhanced support for binary operators

- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
- python/src/triton.cc
- python/tests/test_core.py
- python/triton/compiler.py
- python/triton/language/semantic.py
- Fixed bugs on layout conversions for int1 data (we should use int8 internally for int1 data to prevent llvm from using vec<i1> which has different semantics)
- Fixed semantics of some casts to bool in the frontend
> [FRONTEND][BACKEND] Fixed various bugs

- .gitignore
- CMakeLists.txt
- README.md
- include/print_helper.h
- include/triton/codegen/target.h
- include/triton/driver/dispatch.h
- include/triton/driver/llvm.h
- include/triton/external/hip.h
- include/triton/ir/builder.h
- lib/codegen/analysis/layout.cc
- lib/codegen/pass.cc
- lib/codegen/selection/generator.cc
- lib/codegen/target.cc
- lib/driver/dispatch.cc
- lib/driver/llvm.cc
- lib/ir/builder.cc
- python/setup.py
- python/src/triton.cc
- python/test/unit/language/test_core.py
- python/triton/compiler.py
- python/triton/language/semantic.py
- triton_rocm_20-52.Dockerfile
This PR brings the ROCM branch more inline with recent master.
> ROCM Upstream PR 11/2/2022

- .github/workflows/integration-tests.yml
This avoids trying to install missing pytorch wheels after the latest runner image update
> [CI] macos-latest -> macos-10.15

- docs/programming-guide/chapter-2/related-work.rst
- lib/Analysis/Alias.cpp
- lib/Analysis/Allocation.cpp
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- lib/Dialect/TritonGPU/Transforms/CanonicalizeLoops.cpp
- lib/Dialect/TritonGPU/Transforms/Combine.cpp
- lib/Dialect/TritonGPU/Transforms/Pipeline.cpp
- lib/Dialect/TritonGPU/Transforms/TritonGPUConversion.cpp
- python/src/triton.cc
- python/tests/test_vecadd.py
- python/triton/compiler.py
- python/triton/language/core.py
- python/triton/language/semantic.py
- python/tutorials/01-vector-add.py
- python/tutorials/02-fused-softmax.py
- python/tutorials/06-fused-attention.py
> [Triton-MLIR] Fix some typos

- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
- lib/Conversion/TritonToTritonGPU/TritonToTritonGPU.cpp
- python/src/triton.cc
- python/tests/test_core.py
minor fix to backend and frontend of atomics, we can pass 1 test without mask and the shape aligned with CTA size now
> [Triton-MLIR][FRONTEND] [BACKEND] fix atomics

- include/triton/Dialect/TritonGPU/Transforms/Passes.h
- include/triton/Dialect/TritonGPU/Transforms/Passes.td
- lib/Dialect/TritonGPU/Transforms/Combine.cpp
- python/src/triton.cc
- python/triton/compiler.py
- python/triton/tools/aot.py
- test/Target/tritongpu_to_llvmir.mlir
add compute capability from python frontend to backend.
> [Triton-MLIR] add compute capability

- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
- python/tests/test_gemm.py
This PR
1. Fix wpt overflow issue in mma v2
2. Refine transpose logic
TODOs:
1. the transA and transB attributes in DotOp seems not activated.
> [Triton-MLIR][BACKEND] Fix wpt overflow issue in mma v2

- lib/Analysis/Allocation.cpp
- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
- python/src/triton.cc
- python/tests/test_core.py
- python/triton/language/semantic.py
> [TRITON-MLIR][BACKEND]AtomicRMWOp supports scalar

- include/triton/Dialect/Triton/IR/TritonAttrDefs.td
- lib/Analysis/Allocation.cpp
- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
- lib/Conversion/TritonToTritonGPU/TritonToTritonGPU.cpp
- python/src/triton.cc
- python/tests/test_core.py
1. support atomics-cas
2. add xchg support in atomic_rmw
> [TRITON-MLIR][BACKEND]support atomic_cas

- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- test/Conversion/tritongpu_to_llvm.mlir
The e2e verification of mma v1 is not done yet. 
Get this merged in advance just to prevent more conflicts.
> [Triton-MLIR][Backend] support MMA v1 in ConvertLayout

- .github/workflows/integration-tests.yml
- lib/Conversion/TritonGPUToLLVM/DotHelpers.h
- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
This PR:
- Several fix on MMAV1 code
- Remove the env `TRITON_STATIC_LOOP_UNROLLING` in v100 CI since the pipeline pass works now
- some code clean
> [Triton-MLIR][BACKEND] Tiny patch for MMAv1 and code clean

- python/src/triton.cc
- python/triton/language/semantic.py
compiler still has pitfalls even in master branch
> [TRITON-MLIR][FRONTEND] Add possibility for user to force a GPU threadsync barrier

- python/triton/language/__init__.py
This is a hotfix for issue 1 in https://github.com/openai/triton/issues/1017
@ptillet @crutcher We can resume reviewing this [PR](https://github.com/openai/triton/pull/952) so that many frontend related problems can go away
> [Frontend] Fix import for libdevice

- python/triton/compiler.py
- python/triton/language/core.py
Not totally sure the best way to solve this, this seemed the cleanest (handles any type of constexpr).
> Fix #1032 and add logical operations on constexprs

- python/test/unit/language/test_core.py
- python/triton/language/core.py
Fixing problem 2 in https://github.com/openai/triton/issues/1017
> [Frontend] Convert constexpr to value for store and load ops

- include/triton/Target/LLVMIR/LLVMIRTranslation.h
- lib/Target/LLVMIR/LLVMIRTranslation.cpp
- lib/Target/PTX/PTXTranslation.cpp
- python/triton/language/semantic.py
- Also make it cleaner. 
- And mark out the code needs to be fixed in `semantic.py`.
> [Backend] Rewrite code for linking external library to expose more inlining opportunities

- lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
- lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.h
- lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp
- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
- lib/Conversion/TritonGPUToLLVM/Utility.h
- test/Conversion/tritongpu_to_llvm.mlir
Added a utility function and also comments
> [BACKEND] Clean-up our way of getting swizzled shared memory pointers, and make it compatible with other distributed layouts

- bin/CMakeLists.txt
- bin/triton-translate.cpp
- lib/Target/LLVMIR/CMakeLists.txt
The tool would still need some more work to become useful, but this at least makes it build and call into the right hooks.
> Fix build issues of triton-translate tool

- include/triton/Dialect/Triton/IR/TritonOps.td
- include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td
- lib/Dialect/TritonGPU/Transforms/Combine.cpp
- test/TritonGPU/combine.mlir
And a hotfix for incorrect convert_layout construction in the GPU combine pass.
> [BACKEND] Verify the same operand and result element type for convert_layout

- lib/Conversion/TritonGPUToLLVM/CMakeLists.txt
- lib/Conversion/TritonGPUToLLVM/DotOpHelpers.cpp
- lib/Conversion/TritonGPUToLLVM/DotOpHelpers.h
This is the remaining work of the former Backend File Partition work.
> [Backend] Split declaration and defitions of functions in DotOpHelpers.h

- python/test/unit/language/test_core.py
The line is duplicate of the line 1097 - seems like the typo.
> [TEST] Fix typo.

- python/triton/compiler.py
latest commit check TRITON_PTXAS_PATH is a valid file
> check TRITON_PTXAS_PATH is a valid file

- python/triton/language/semantic.py
Fix issue https://github.com/openai/triton/issues/633
> [FRONTEND] Add error messages for load/store

- lib/Target/LLVMIR/LLVMIRTranslation.cpp
- python/triton/language/libdevice.py
- python/triton/tools/build_extern.py
we may compile kernels on remote machines which do not have local libdevice.10.bc.
> [FRONTEND][BACKEND] add env variable TRITON_LIBDEVICE_PATH

- lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
- python/test/unit/language/test_core.py
pass named attributes (e.g., tt.contiguity) from Triton to TritonGPU
> Fix conversion

- CMakeLists.txt
- python/setup.py
> [BUILD] Bump cmake requirement to >= 3.20 and format CMakeLists.txt

- lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp
- python/test/unit/language/test_core.py
- test/Conversion/tritongpu_to_llvm.mlir
> [BACKEND] Mask out wrapped threads in store ops

- lib/Target/PTX/PTXTranslation.cpp
stack-use-after-scope is reported by LLVM AddressSanitizer at stream flush happening in PassManager's destructor.
> Fix stack-use-after-scope in translateLLVMIRToPTX.

- python/triton/testing.py
`_triton.runtime.num_sm`, `_triton.runtime.clock_rate`, `_triton.runtime.cc` seem no longer exist. 
use the corresponding methods from `get_max_tensorcore_tflops` in the same file.
> [testing] fix get_max_simd_tflops

- python/triton/compiler.py
Fixes https://github.com/pytorch/pytorch/issues/97076
Signed-off-by: Edward Z. Yang <ezyang@meta.com>
> Don't use HOME envvar to get HOME

- .pre-commit-config.yaml
- lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp
- python/test/regression/test_performance.py
- python/test/unit/language/test_core.py
- python/test/unit/operators/test_blocksparse.py
- python/test/unit/operators/test_cross_entropy.py
- python/test/unit/operators/test_flash_attention.py
- python/test/unit/operators/test_inductor.py
- python/test/unit/operators/test_matmul.py
- python/triton/__init__.py
- python/triton/compiler.py
- python/triton/ops/blocksparse/matmul.py
- python/triton/runtime/jit.py
- python/triton/testing.py
- python/triton/utils.py
`assert triton.testing.allclose` -> `torch.testing.assert_allclose`
`triton.testing.assert_almost_equal` -> `torch.testing.assert_allclose`
> [FRONTEND] Removed torch dependency and cleaned up testing

- python/triton/compiler.py
llir_to_ptx returns a str not a Tuple.
> Fixed a pytype annotation. 

- python/triton/runtime/jit.py
May I suggest this? I wrote it on 'main' but it seems useful for a refactor involving multiple files.
It's a little less hardcoded, so more easily adaptable for future extension.
Also, it folds the hashing of all files into a single digest, rather than concat-ing one hash per file, which creates unwieldy cache keys, esp when subpackages are involved. These are visible at the very least in every error traceback.
I wasn't sure whether the intention was to leave a visible hash for each contained file. I assumed it wasn't.
More generally, I'm not sure whether the approach of hashing source code and binaries is maintainable, portable or user-friendly in the long run. It certainly doesn't help with the runtime of `import triton` (compare to `import torch`, or `import numpy` which are near …
> `triton.jit.version_key()` more structured implementation + shorter hash

- lib/Dialect/TritonGPU/Transforms/Prefetch.cpp
https://github.com/openai/triton/issues/1432
> [OPTIMIZER] Do not create yield if yieldValues is empty

- lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
- python/test/unit/language/test_core.py
https://github.com/openai/triton/issues/1438
https://github.com/openai/triton/issues/1360
> [BACKEND] Fix tl.exp for fp16

- python/triton/runtime/autotuner.py
now keyword arguments can be parts of autotune keys
see issue #1446
> kwargs as autotune key

- python/triton/compiler/code_generator.py
Handled TODOs that were waiting for the circular import issue to be resolved
> `code_generator.py` TODOs fixed & removed

- lib/Dialect/TritonGPU/Transforms/Utility.cpp
- test/TritonGPU/combine.mlir
Loads are now consider cheap to rematerialize when there are more threads than elements in the tensor
> [OPTIMIZER] Tweaked layout removal conversion heuristics

- python/tutorials/08-experimental-block-pointer.py
Found some rendering issues here: https://triton-lang.org/main/getting-started/tutorials/08-experimental-block-pointer.html, sorry for not checking carefully in the last PR.
> [TUTORIALS] Fix rendering issues in the block pointer tutorial

- python/test/unit/language/test_core.py
- python/triton/language/core.py
Also reverts #1541 that breaks this test.
> Test pow with mixed dtypes

- python/triton/compiler/compiler.py
Use ttgir num-warps attribute instead of default value.
> [FRONTEND] Use ttgir module num-warps instead of default value

- lib/Dialect/TritonGPU/Transforms/Pipeline.cpp
directly rematerialize for loop with the right values, instead of replacing unpipelined load uses a posteriori
> [OPTIMIZER] simplified pipeline pass

- include/triton/Dialect/Triton/IR/TritonOps.td
- lib/Dialect/TritonGPU/Transforms/Pipeline.cpp
These should be safe and good to merge into main.
> Integrate fixes from llvm-head branch

- lib/Dialect/TritonGPU/Transforms/Pipeline.cpp
> [OPTIMIZER] Fix crash in loop pipelining.

- lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
- lib/Dialect/TritonGPU/Transforms/Utility.cpp
ConvertLayoutOp can be folded in other ConvertLayoutOp
> [OPTIMIZER] Clean-up Utility.cpp and fixed bug in RematerializeForward

- python/test/unit/language/test_core.py
[TEST] Added convert layout test from/to sliced blocked/mma
> [TEST] Added convert layout test from/to sliced blocked/mma

- include/triton/Analysis/Utility.h
- lib/Analysis/Utility.cpp
- lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
- python/test/unit/language/test_core.py
Re-enabled reduce test after fixing the %cst stride in the ttgir, and modifying the sweep parameters to make sure the shape per CTA to be less than or equal to the tensor shape.
> [TEST] Fixed and re-enabled reduce test

- lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
Fixes fused attention with D_HEAD=128
> [OPTIMIZER] adjusted selection heuristics for when `mmaLayout.warpsPerTile[1] = 1`

- lib/Analysis/AxisInfo.cpp
- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.cpp
- lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
Remove unused variables, fix member initializer list order.
> NFC: build fixes

- python/test/unit/language/test_core.py
- python/triton/compiler/code_generator.py
https://github.com/openai/triton/issues/1690
> [FRONTEND] Refactor contains_return_op into an independent AST

- python/test/unit/language/test_core.py
- python/triton/language/core.py
> [FRONTEND] fixed issue for fp64 literals and added tests

- python/triton/language/core.py
@peterbell10  @Jokeren I believe that the current argmax reduction code is overly complicated. Am I missing something here?
> [FRONTEND] simpler/faster argmax code

- python/triton/__init__.py
test case:
`next_power_of_2(2**33 + 1)`
> [FRONTEND] Fix `next_power_of_2` for large integers

- lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
- lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
Fix for: https://reviews.llvm.org/D151520
> Integration forx for MLIR change D151520

- python/triton/language/core.py
Haven't tested the docs (they don't seem to compile on my machine when I use the makefile)
> [DOCS] update debug docs

- include/triton/Dialect/Triton/IR/TritonOps.td
- lib/Dialect/Triton/IR/Ops.cpp
- test/Conversion/invalid.mlir
Add verifier to enforce that kWidth attributes match between A and B operands.
> [TEST] Add verifier to DotOp

- include/triton/Dialect/Triton/IR/TritonAttrDefs.td
- lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp
- python/src/triton.cc
- python/test/unit/language/test_core.py
- python/triton/language/semantic.py
Plumb through store cache modifiers.
> [BACKEND] Add store cache modifiers

- lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
- lib/Dialect/TritonGPU/Transforms/Utility.cpp
- test/TritonGPU/combine.mlir
https://github.com/openai/triton/issues/1846
> [OPTIMIZER] Fix push conversion forward for reduce ops

- lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp
- test/TritonGPU/dot-operands.mlir
We need to make sure to convert the whole slice of operations in order to make sure the types are always consistent.
> [OPTIMIZER] Fix mismatching type when optimizing kWidth

- lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
- python/test/unit/language/test_core.py
https://github.com/openai/triton/issues/1883
> [BACKEND] Recover the correct axis in the parent layout for reduce ops

- python/test/unit/operators/test_cross_entropy.py
- python/triton/runtime/backends/cuda.c
> [backend] make sure we always bind to primary context in loadBinary

- .github/workflows/integration-tests.yml
- python/test/kernel_comparison/kernels.yml
With this PR, we find the latest merged PR that successfully passed "Integration Tests".
> [CI] Fix CI kernel compare

- lib/Dialect/TritonGPU/Transforms/Pipeline.cpp
- test/TritonGPU/loop-pipeline.mlir
counterintuitively seems to have better perf on many A100 workloads
> [OPTIMIZER] RemSI -> RemUI in pipeline pass

- lib/Dialect/TritonGPU/Transforms/Pipeline.cpp
- test/TritonGPU/loop-pipeline.mlir
This is strange. Using RemUI should be strictly better, but it can cause up to 20% performance regression in some cases. I am reverting to RemSI pending investigation
> [OPTIMIZER] Falls back to using RemSI in the pipeline pass for now

- lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
- python/test/unit/language/test_core.py
We had a number of complains that the previous packed format was error-prone and may not yet be worth the 2 SASS instruction saved per 4 conversions
> [FRONTEND][BACKEND] no longer serialize float8e4b15

- python/triton/runtime/jit.py
None is not a type, so you get:
```
self.constexprs = [self.arg_names.index(name) for name, ty in self.__annotations__.items() if 'constexpr' in ty]
E   TypeError: argument of type 'NoneType' is not iterable
```
> Fix error with -> None return annotation

- .github/workflows/integration-tests.yml
cc @EikanWang . I'm disabling this for now since it broke with the H100 merge, but please feel free to fix the compilation errors and submit a PR.
> [CI] disable XPU tests (not compiling)

- python/test/unit/language/print_helper.py
- python/test/unit/language/test_subprocess.py
- python/triton/compiler/make_launcher.py
- python/triton/runtime/jit.py
Issue https://github.com/openai/triton/issues/1973
> [FRONTEND] Support jit functions without arguments

- python/triton/language/semantic.py
Improve error messaging for block shape and value shape mismatch.
> [FRONTEND] improve error message for shape mismatch

- python/triton/runtime/jit.py
Realised I could do this right after my first PR got merged. This saves another 100ms
> [FRONTEND] further improve version_key speed

- python/test/unit/hopper/test_persistent_warp_specialized_fused-attention.py
- python/test/unit/hopper/test_persistent_warp_specialized_gemm.py
remove unnecessary skips. decompose UTs in persistent-warp-specialized-gemm into vintage and stylish
> [TESTS] refactor test-persistent-warp-specialized-gemm UTs

- python/test/unit/hopper/test_persistent_warp_specialized_gemm.py
- remove auto-tune for test_user_defined_persistent_warp_specialized_gemm.
- remove unnecessary perf evaluation parts.
- add  test cases of num-CTA > 1 for test_user_defined_persistent_warp_specialized_gemm.
> Update test_user_defined_persistent_warp_specialized_gemm for num-CTA > 1

- lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
- python/test/unit/language/test_core.py
- python/triton/language/semantic.py
`offset + ptr` and `ptr + offset` both work now
> [FRONTEND] Fix addptr code generation

- lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
- python/test/regression/test_performance.py
- python/test/unit/language/test_core.py
- python/triton/language/core.py
- python/triton/testing.py
Also stop promoting integer types as it doesn't give better perf this will allow more vectorization oportuinity in the future.
> [FRONTEND][BACKEND] Add a performance test for reductions

- .github/workflows/compare-artifacts.yml
> [CI] Fix bug in Compare Artifacts workflow

- .github/workflows/compare-artifacts.yml
> [CI] Fix PR comment

- include/triton/Dialect/Triton/IR/TritonOps.td
- lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
- lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
- lib/Dialect/Triton/IR/Ops.cpp
- lib/Dialect/TritonNvidiaGPU/Transforms/PlanCTA.cpp
- python/src/triton.cc
Use getEffect instead to tell passes whether the op has side effects or not. This doesn't change functionality otherwise.
> [BACKEND] Merge TT_ElementwisePureExtern and TT_ElementwiseImpureExtern

- lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
> [OPTIMIZER] Remove dead code

- README.md
- lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
Revise the logics to assign MMA layout for serialized dots. This is a hueristic rule for FlashAttention.
> [Optimizer][Hopper] change mmaV3InstrN for flash attention

- lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandFMA.cpp
https://github.com/openai/triton/issues/2156
> [BACKEND] Fix BF16 dot operand type mismatch

- lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
- test/TritonGPU/combine.mlir
Handle cases of reduce with multiple operand returning scalars
> [BACKEND] Handle more cases of folding convert into reduce op

- lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
- test/TritonGPU/combine.mlir
Support forward propagation through while loops.
> [BACKEND] Add support for propagating convert op through while loops

- lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
- lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMMAv1.cpp
- lib/Conversion/TritonGPUToLLVM/TypeConverter.cpp
- lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp
- test/TritonGPU/dot-operands.mlir
* Fix bug in V100 convert layout
* Do not push elementwise between convert and dot for V100
> [BACKEND] More minor backend fixups

- lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp
- lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
> [BACKEND] Fix several bugs related to multiCTA

- python/test/unit/runtime/test_cache.py
- python/triton/runtime/jit.py
https://github.com/openai/triton/issues/2231
> [FRONTEND] Fix specialization on triton integer types

- .github/workflows/integration-tests.yml
> [CI] Attempt to fix submodule issue

- include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
* Improved heuristics for RemoveLayoutConversion; 
* add LayoutConversionOp canonicalizer for ViewOps
> [OPTIMIZER] improvements to layout conversion removal

- lib/Conversion/TritonGPUToLLVM/ScanOpToLLVM.cpp
- To make the development on AMD GPUs a little easier
-  Also changed `laneId` to `laneIdAxis` in some helper functions in scanOp lowering
> [NFC] Remove hard-coded warpSize=32 in scanOp lowering

- python/triton/compiler/compiler.py
- python/triton/runtime/cache.py
Low tech but very useful way to override kernels on the fly. This can be use for debugging functionality or performance problems this lets user dump modify and feed back IR into the jit compiler.
> [FRONTEND] Override prototype

- include/triton/Dialect/TritonGPU/Transforms/Utility.h
- include/triton/Dialect/TritonNvidiaGPU/IR/Dialect.h
- lib/Analysis/CMakeLists.txt
- lib/Conversion/TritonGPUToLLVM/CMakeLists.txt
- lib/Dialect/TritonGPU/Transforms/Utility.cpp
- lib/Dialect/TritonNvidiaGPU/IR/Dialect.cpp
This fixes few problems that were preventing me to use lld linker.
> [BUILD] Fix few dependencies and layering issues to make lld work

- python/triton/runtime/interpreter.py
this improves the debugging experience
> [RUNTIME][INTERPRETER] now also override __str__ and __getitem__ method for tensors

- README.md
I tested these locally, seems to work for me.
> Add instructions for building with custom LLVM

- include/triton/Analysis/Utility.h
- lib/Analysis/Utility.cpp
- lib/Conversion/TritonGPUToLLVM/ScanOpToLLVM.cpp
- python/test/unit/operators/test_inductor.py
https://github.com/openai/triton/issues/2298
> [BACKEND] Handle repetitive threads in scan op when the tensor dim is small

- lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/WGMMA.cpp
- python/test/unit/language/test_core.py
- test/Conversion/tritongpu_to_llvm_hopper.mlir
Also add a test for MMA v3 reduction.
> [BACKEND] Optimize wgmma with accumulator source equal to 0

- lib/Conversion/TritonGPUToLLVM/ScanOpToLLVM.cpp
- python/test/unit/language/test_core.py
Make sure we accumulate in the right order for scans so that non commutative operations are handled correctly.
> [BACKEND] Handle scan of function non commutative

- python/test/unit/language/test_core.py
- python/triton/language/semantic.py
this is a combination of #1774 and #2006, which I cannot edit but fail CI pre-commit hook
> [FRONTEND] improved error messages

- lib/Conversion/TritonGPUToLLVM/ScanOpToLLVM.cpp
- lib/Conversion/TritonGPUToLLVM/Utility.cpp
- python/test/unit/operators/test_inductor.py
Otherwise, llvm pass could generate very weird structure of CFG and yield incorrect results.
https://github.com/openai/triton/issues/2361
> [BACKEND] `shfl` ptx insts should have side effects

- lib/Conversion/TritonGPUToLLVM/Utility.cpp
- test/Conversion/tritongpu_to_llvm.mlir
This will ensure we get the proper "convergent" semantic for those instructions
> [BACKEND] Use shuffle intrinsics instead of inline asm

- README.md
- python/setup.py
- Note `wheel` as a build-time dependency.
- Add tips for getting a faster build.
- Add instructions for running tests.
- Add flag to build with ccache.
(Thanks to @ThomasRaoux for most of these instructions!)
> Update build instructions, and add testing instrs.

- include/triton/Dialect/TritonGPU/Transforms/Utility.h
- lib/Analysis/Utility.cpp
- lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
- lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/WGMMA.cpp
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
- lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp
- lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
- lib/Dialect/TritonGPU/Transforms/Utility.cpp
- python/tutorials/06-fused-attention.py
- test/TritonGPU/accelerate-matmul.mlir
Support having chain of mma with mixed size.
Serialize the different block calculation in backward attention to workaround problem with ptxas and wgmma.
> [OPTIMIZATION] Fix performance for attention backward path with mma v3

- lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
Remove ad hoc patterns. This will help LLVM transition.
> [BACKEND][NFC] Simplify conversion to TritonGPU

- python/tutorials/11-grouped-gemm.py
Depend on https://github.com/openai/triton/pull/2419 to fix the documentation workflow
> [TUTORIALS] Add missing docstrings

- lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
- python/test/unit/language/test_core.py
I would like to get some input on whether this is the right approach to do Fp8E4M3Nv to Bf16 conversion. Thanks.
> Support of Fp8E4M3Nv to Bf16 conversion

- .github/workflows/wheels.yml
- python/src/triton.cc
there's a typo in the previous commit
> [CI] disable pypy wheel (continued)

- python/tutorials/06-fused-attention.py
Improves performance of fwd pass from 420 to 440 TF
> Better tuning for H100 flash attention.

- bin/triton-translate.cpp
- test/Triton/print.mlir
Enabling per-pass IR printing such as `--mlir-print-ir-after-all`
> [Triton-translate] Enable per-pass IR printing

- python/tutorials/06-fused-attention.py
Here are the results from the tutorial on H100:
```
~/triton/python $ python ./tutorials/06-fused-attention.py                                                                                                                                                                                                                          
fused-attention-batch4-head48-d64-fwd-causal=True:                                                                                                                                                                                                                                  
N_CTX      Triton     Flash-2 …
```
> Enable causal=False in FA fwd kernel

- lib/Dialect/TritonNvidiaGPU/Transforms/WSMaterialization.cpp
This seems to have worked fine in opt mode (although it may be producing undefined behavior), but in debug mode on a newer version of llvm, it segfaults without this PR as the iterators get invalidated.
This is also consistent with other places it is done in this file.
> Erase ops after use in iterator

- python/test/unit/language/test_core.py
- python/triton/language/core.py
https://github.com/openai/triton/issues/2470
> [FRONTEND] Fix math for constant values

- lib/Target/LLVMIR/LLVMIRTranslation.cpp
This reverts commit b1bc9b20a0165a4af3c5810be7324249ee75acd3.
> Revert "[BACKEND] Disable BreakPhiStruct pass (#2458)"

- .github/workflows/test-backends.yml
This is the same as https://github.com/openai/triton/pull/2619 but created on the openai/triton instead of my fork.
> Fix Backend CI Issue

- lib/Dialect/TritonNvidiaGPU/Transforms/MaterializeLoadStore.cpp
- python/test/unit/operators/test_flash_attention.py
- test/TritonGPU/materialize-load-store.mlir
> [BACKEND]MaterializeLoadStorePass enable mbarrier_wait phase flip

- lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
- test/TritonGPU/accelerate-matmul.mlir
When we have a chain of dot we want to pick the same mma layout to avoid extra conversion.
> [BACKEND] Prevent mismatch mma layout in chained dot

- include/triton/Analysis/AxisInfo.h
- lib/Analysis/AxisInfo.cpp
- test/Analysis/test-alignment.mlir
Add propagation for for op induction variable and improve min/max propagation
> [BACKEND] Improve axis analysis

- python/triton/runtime/interpreter.py
Update name from create_view to create_reshape
> [FRONTEND] Fix interpreter after reshape changes

- lib/Dialect/TritonGPU/Transforms/Utility.cpp
- test/TritonGPU/combine.mlir
Backward rematerialization could generate wrong IR when rematerializing ops with multiple results as not all the results may have had their encoding updated.
> [BACKEND] Fix backward rematerialization for ops with multiple results

- lib/Dialect/TritonGPU/Transforms/Pipeliner/PipelineExpander.cpp
The software loop pipeline used the wrong predication for each stage in pre-epilogue.
1. Using the array to keep reference to each predication value when created.
2. Refer the correct predication value for the ops in each stage which is just like the ops iterated before pipelining.
No change to the stage scheduling sequence. There should no impacting on the performance.
> [BACKEND] Fix the bug in software loop pipeline 

- python/triton/language/standard.py
This will avoid potential bad problem with special floating point values as well as allow optimizing multiplication by 0.
> [FRONTEND] Change sort to use integer types for tensor slicing.

- docs/python-api/triton.language.rst
- include/triton/Dialect/Triton/IR/TritonOps.td
- lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- python/src/triton.cc
- python/test/unit/language/test_core.py
- python/triton/language/core.py
Allow inline_asm_elementwise to return a tuple.
> [FRONTEND] Multiple returns from an inline asm op.

- python/test/unit/operators/test_matmul.py
- python/triton/ops/matmul.py
In this PR we are just adding tests between int8 and bf16 and between float16 and int8.
> [TESTS] Add matmul tests between int8, bf16 and int8, f16

- include/triton/Dialect/Triton/IR/TritonOps.td
- lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp
- lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
- lib/Dialect/Triton/IR/Ops.cpp
- lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
- lib/Dialect/TritonGPU/Transforms/Utility.cpp
- python/src/triton.cc
- python/test/unit/language/test_core.py
- python/triton/language/__init__.py
- python/triton/language/core.py
- python/triton/language/semantic.py
- test/Triton/invalid.mlir
This lets you combine two tensors by alternating them in the most minor
dimension.  For example interleave([1,2,3], [4,5,6]) = [1,4,2,5,3,6].
> Add experimental_interleave op.

- python/triton/compiler/compiler.py
* The frozenset is unordered set. The serialization of the frozenset maybe in random order.
Remove the `frozenset` in serializing the env for the key.
> [FRONTEND] Fix the issue that the key of JIT function maybe random.

- docs/meetups/12-13-2023/notes.md
December meetup minutes and recording link.
> Create notes.md for December meetup

- lib/Dialect/TritonGPU/Transforms/Pipeliner/PipelineExpander.cpp
In the long term, we aim to avoid duplication between Triton and MLIR once MLIR's Loop Pipelining pass becomes stable enough for our use cases.
> [OPTIMIZER] Sync with MLIR loop pipelining code

- lib/Dialect/TritonGPU/Transforms/Coalesce.cpp
Summary:
Test Plan:
Reviewers:
Subscribers:
Tasks:
Tags:
> NFC: simplify code in Coalesce.cpp, also add DEBUG_ONLY support

- python/triton/testing.py
This is in case of error in unit test of triton based project
#2873 https://github.com/openai/triton/issues/2873
> [TESTING] Close report file after benchmark

- python/src/interpreter.cc
- python/src/passes.cc
There seems to be a hidden character (<EF><BB><BF>) at the beginning of the file which is interfering with my building on another system.
> Remove odd character at beginning of file

- docs/getting-started/installation.rst
Fixes https://github.com/openai/triton/issues/2894 .
> [Doc] Update installation.rst to remove specific llvm version

- python/setup.py
Init submodule before trying to check if something is in it
> [BUILD][FRONTEND] Fixing the order of actions in _copy_backends in setup.py

- python/test/unit/language/test_core.py
Those tests are deprecated, since we have comprehensive test_conversions now
> [TEST] Deprecating old conversion tests from test_core

- docs/conf.py
- python/setup.py
- python/triton/__init__.py
The release branch is on 2.2.0, and we plan for our next release to
break bw compatibility, so calling it 3.0.0.
Fixes #2940.
> Update version to 3.0.0.

- lib/Dialect/TritonNvidiaGPU/Transforms/WSMaterialization.cpp
- lib/Dialect/TritonNvidiaGPU/Transforms/WSPipeline.cpp
> chore: Fix multiple typos

- python/triton/compiler/compiler.py
Add back some debugging hooks to allow overriding the IR at different level during compilation. This can be used to debug compiler problems and try out the impact of different IR without having to change the compiler.
> [FRONTEND] Add back kernel override instrumentation

- lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.cpp
- python/setup.py
copying file before install is messy, and doesn't work with editable installations. With this PR, we now create symlinks -- which will be resolved or not by setuptools depending on the installation method
> [SETUP] fix editable install issues

- python/test/unit/language/test_core.py
- python/triton/language/semantic.py
- third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp
This PR adds casts of accumulator value in mfma dot accelerateAMDMatMul pass.
This fixes test_dot in test_core.py.
> [AMD] Dot op test fixes

- include/triton/Analysis/Utility.h
- include/triton/Dialect/Triton/IR/TritonOps.td
- lib/Dialect/Triton/IR/Ops.cpp
- lib/Dialect/Triton/Transforms/Combine.cpp
Fold is supposed to be faster than a full matcher.  Also it's a bit
simpler.
Follow-up to
https://github.com/openai/triton/pull/2959#discussion_r1468262277.
> [IR] Change some transpose patterns to fold (NFC).

- python/test/unit/language/test_core.py
- third_party/amd/backend/compiler.py
This PR enables optimize_epilogue pass and
more dot tests that did not fit into LDS before.
> [AMD] Enable optimize_epilogue pass 

- lib/Dialect/TritonGPU/IR/Dialect.cpp
Bug introduced in 8e61b7212e7d32c85f448490260c6293d2f1885a.
> [IR] Fix stringification of #shared layouts.

- python/triton/runtime/interpreter.py
fix #3068
@Jokeren @ThomasRaoux
> [interpreter] add handler for slice

- python/triton/runtime/interpreter.py
fix #3071
cc @Jokeren @ThomasRaoux @ptillet
> [interpreter] fix reduce

- lib/Conversion/TritonGPUToLLVM/Utility.h
Isolate immediate constant on Hopper like we do on Ampere. This allows taking advantage of setting immediate offset in asyc.cp instruction which reduces pressure and arithmetic.
> [BACKEND] Optimize swizzling arithmetic for Hopper

- lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
- test/TritonGPU/loop-pipeline-hopper.mlir
When deciding whether we can pipeline the wgmma we need to check that both operands of the dot have been double buffered.
> [BACKEND] Fix bug causing race condition with wgmma

- .github/workflows/llvm-build.yml
Fixed issue that occured with ubuntu arm64 builds, here is a run where this workflow was run
[LLVM build](https://github.com/danikhan632/triton/actions/runs/7916642692/job/21610914919)
> [BUILD] fix ubuntu arm64 build

- python/test/unit/language/test_core.py
- python/triton/language/semantic.py
I am impressed we didn't have a check for this anywhere in the frontend.
> [Frontend] Raise an error on illegal reshape.

- include/triton/Dialect/Triton/IR/TritonOps.td
- python/src/ir.cc
- python/test/unit/language/print_helper.py
- python/test/unit/language/test_subprocess.py
- python/triton/language/core.py
- python/triton/language/semantic.py
- test/Conversion/triton_ops.mlir
- test/TritonGPU/combine.mlir
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/PrintOpToLLVM.cpp
Lets you print values as hex instead of decimal.
> Add `hex` field to tl.print.

- include/triton/Dialect/Triton/IR/TritonOps.td
- lib/Dialect/Triton/IR/Ops.cpp
- test/Triton/invalid.mlir
Addresses the discussion at https://github.com/openai/triton/pull/3111#discussion_r1488366197
> [BACKEND] Stronger checks on ScanOp and ReduceOp

- lib/Dialect/TritonGPU/IR/Dialect.cpp
- test/Conversion/tritongpu_to_llvm_hopper.mlir
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/WGMMA.cpp
Generalize conversion to LLVM and support fp8 operands from register that can be enabled at some point.
> [BACKEND] Generalize wgmma conversion to llvm

- include/triton/Dialect/TritonGPU/Transforms/Utility.h
- lib/Dialect/TritonGPU/Transforms/Utility.cpp
- lib/Dialect/TritonNvidiaGPU/Transforms/FenceInsertion.cpp
- test/TritonGPU/fence-inserstion.mlir
- third_party/amd/include/TritonAMDGPUTransforms/Utility.h
Avoid having the fence in a loop if it can be pulled out.
> [BACKEND] Optimize placement of async_fence

- python/test/unit/language/test_core.py
- python/triton/language/core.py
- python/triton/language/semantic.py
Previously split(x) failed if x had shape 2, and join(x, y) failed if x and y
were scalars.
Note that because the impl for split uses core.reduce, it has to live inside
core.py, not semantic.py.  Bummer.
> [Frontend] Make split() and join() work on scalars.

- .github/workflows/integration-tests.yml
<git-pr-chain>
Run CI on branches named 'dev-**'.
I hope this will allow chaining of PRs while also getting CI runs.
1. 👉 #3185 👈 **YOU ARE HERE**
1. #3186
1. #3187
> Run CI on branches named 'dev-**'.

- python/test/unit/language/test_compile_errors.py
- python/triton/compiler/code_generator.py
<git-pr-chain>
[Frontend] Stop parsing after we hit a `return` statement.
Suppose you have something like the following.
```
@jit
def fn(x, y):
return x
return y
```
Clearly this function returns `x` and not `y`, but before this patch, we'd say
that the function's last_ret_type was `y`.  This would cause assertions inside
the C++ side of code generation.  The IR would correctly return x, but the type
of `fn` would match the shape of y.
While we're here, we also fix the reported location for these and other errors
reported by the code_generator.  We frequently do something like the following.
```
def visit_Foo(node):
assert(self.last_node == node)  # passes
self.visit(node.operand)
do_stuff()
```
If do_stuff() raises an exception, we should attach the exception to `node`,
not to whatever …
> [Frontend] Stop parsing after we hit a `return` statement.

- .github/workflows/llvm-build.yml
fixing the apt-get update issue
> added apt-get update

- include/triton/Conversion/TritonGPUToLLVM/Utility.h
- lib/Conversion/TritonGPUToLLVM/Utility.cpp
- unittest/CMakeLists.txt
- unittest/Conversion/TritonGPUToLLVM/DumpLayout.cpp
MLIR does not allow this after https://github.com/llvm/llvm-project/pull/82244
> [NFC][BACKEND] Do not use ConversionPatternRewriter outside of dialect conversion.

- include/triton/Analysis/AxisInfo.h
- include/triton/Dialect/TritonGPU/Transforms/Utility.h
- lib/Analysis/AxisInfo.cpp
- lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
- test/lib/Analysis/TestAxisInfo.cpp
<git-pr-chain>
[Backend] Clean up AxisInfo (NFC).
- Remove unused member variables.
- Clarify and reformat comments.
- Move code out of header.
- Add namespaces.
1. 👉 #3240 👈 **YOU ARE HERE**
> [Backend] Clean up AxisInfo (NFC).

- python/test/unit/language/test_core.py
- third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp
- third_party/amd/lib/TritonAMDGPUToLLVM/ReduceOpToLLVM.cpp
This PR fixed unit tests `test_chain_reduce` and other `test_tensor_atomic_tests`
> [amd backend] fix unit tests test_chain_reduce and test_tensor_atomic_cas

- python/test/unit/language/test_core.py
- test/TritonGPU/optimize_epilogue.mlir
- third_party/amd/lib/TritonAMDGPUTransforms/OptimizeEpilogue.cpp
This PR adds support of following pattern in optimize epilogue pass:
->ConvertLayout -> ElementwiseOp -> StoreOp
> [AMD] Generalize optimize epilogue pattern

- python/test/unit/language/test_core.py
This PR limits layouts in a way to guarantee scratch buffer fits into LDS.
> [AMD] Fix rest of convert2d tests in test_core.py

- lib/Dialect/TritonGPU/IR/Dialect.cpp
- third_party/amd/lib/TritonAMDGPUTransforms/OptimizeEpilogue.cpp
This PR adjusts comment in OptimizeEpiloguePass
and adds printing of M and N dimensions of MFMA.
> [AMD] Cleanup comments and fix MFMA printing

- lib/Dialect/TritonGPU/IR/Dialect.cpp
- test/Conversion/amd/tritongpu_wmma_dot_to_llvm.mlir
- third_party/amd/lib/TritonAMDGPUToLLVM/CMakeLists.txt
- third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM.cpp
- third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/WMMA.cpp
-Add WMMA conversion logic for dot operation
-Fix helper hunctions for WMMA layout
-Add lit test for WMMA dot operation conversion
See also: 10e1560cf85840ddbfc56de0b8cd72d3fc384683
> [AMD][Navi31] Convert WMMA dot op to LLVM - rebased

- lib/Analysis/Allocation.cpp
- test/Conversion/tritongpu_to_llvm.mlir
When doing a convert from mma -> blocked with a transpose using a vector size for the load back is more efficient.
> [BACKEND] Tweak heuristic for convert layout shape

- third_party/nvidia/backend/compiler.py
We've been trying to share cached compilations across machines, but libdevice isn't always in the same place (we actually package it into python archive files so we don't rely on the system CUDA installation).  By hashing the file instead of its path we can make this hash consistent; and we really do care more about the contents of libdevice than its path, anyways.
> Use libdevice file hash rather than path

- include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td
See https://github.com/openai/triton/pull/3327#discussion_r1519755419
> Add documentation explaining how dealloc is optional.

- lib/Conversion/TritonGPUToLLVM/TypeConverter.cpp
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- python/test/unit/language/test_core.py
- third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
- third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/MFMA.cpp
> Revert "[AMD backend] Fix unit test `test_dot_without_load` "

- include/triton/Dialect/Triton/IR/TritonOps.td
- python/src/ir.cc
- test/Conversion/tritongpu_to_llvm.mlir
- test/TritonGPU/optimize-locality.mlir
- third_party/amd/lib/TritonAMDGPUToLLVM/SPMDOpToLLVM.cpp
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/SPMDOpToLLVM.cpp
Hardened `get_num_programs` axis by using `ProgramIDDim` enum
Ref: #1721
> [FRONTEND][BACKEND] Hardened `get_num_programs` axis

- test/Conversion/amd/tritongpu_wmma_dot_to_llvm.mlir
- third_party/amd/lib/TritonAMDGPUToLLVM/CMakeLists.txt
- third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM.cpp
- third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandHelper.cpp
- third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandHelper.h
- third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
- third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandWMMA.cpp
Convert shared to WMMA layout.
Reuse MFMA related logic. Move it to SharedToDotOperandMatrixCore lib.
> [AMD][Navi31] Support SharedToDotOperandWMMA conversion

- include/triton/Conversion/TritonGPUToLLVM/Utility.h
- test/Conversion/tritongpu_to_llvm.mlir
<git-pr-chain>
[Backend] Vectorize loads/stores from/to unswizzled shmem.
Previously we only vectorized loads/stores from/to shmem if the `vec` parameter
of the shared layout was > 1.  But actually we can vectorize even if vec == 1
if there's no swizzling.
Successful vectorization requires two things.
1. Create LLVM vector ops.
2. Set alignment on the relevant load/store.
Without (2) LLVM will break up the vectorized loads/stores if it can't prove
that the load/store is aligned, which unfortunately happens with simple
double-buffered cases like this.
// https://gcc.godbolt.org/z/G849nd3nd
#include <stdint.h>
__global__ void test(int* array, int n) {
__shared__ __attribute__((aligned(16))) int8_t shared[1024];
int accum = 0;
int8_t* ptr = shared;
for (int i = 0; i < n; i++) {
// This load …
> [Backend] Vectorize loads/stores from/to unswizzled shmem.

- python/test/unit/language/test_random.py
- python/triton/language/core.py
- python/triton/language/random.py
- Otherwise, frontend crashes for non-tensor arguments.
Fixes #3390
> [FRONTEND] Add _to_tensor for philox parameters (#3390)

- python/tutorials/06-fused-attention.py
This change the tutorial to full fp8 attention for Hopper. This matches the implementation described in this paper:
https://research.colfax-intl.com/adding-fp8-to-flashattention/
> [TUTORIAL] Change attention tutorial to do full fp8 for Hopper

- python/triton/language/core.py
<git-pr-chain>
[Docs] Fix documentation for `range`'s `num_stages` attr.
1. 👉 #3425 👈 **YOU ARE HERE**
> [Docs] Fix documentation for `range`'s `num_stages` attr.

- unittest/Conversion/TritonGPUToLLVM/EmitIndicesTest.cpp
-Add LayoutVisualizer_Wmma
-Add WmmaSingleCTA
> [AMD][Navi31] Add WMMA tests to EmitIndicesTest

- python/test/unit/language/test_core.py
Fix layout definition for convert1d testcases
> [AMD][Navi] Fix test_convert1d

- lib/Dialect/TritonGPU/Transforms/Utility.cpp
We found that we are visiting the same nodes multiple times which quickly increases the number in the queue exponentially when there are many nested `if`s.
Since this change only makes the algorithm more efficient and doesn't change the resulting MLIR, I do not have a lit test. However, you can see that this is getting hit by adding a print statement and running test/TritonGPU/combine.mlir.
> Do not revisit nodes for layout propagation 

- lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
- test/TritonGPU/loop-pipeline.mlir
<git-pr-chain>
[Backend] Disable pipelining change from https://github.com/openai/triton/pull/3415.
Effectively roll back https://github.com/openai/triton/pull/3415 due to
internal test failures.
1. 👉 #3472 👈 **YOU ARE HERE**
1. #3473
> [Backend] Disable pipelining change from https://github.com/openai/triton/pull/3415.

- test/TritonGPU/invalid.mlir
<git-pr-chain>
[IR] Add tests for memdesc_subview verifier.
I wrote these as part of 96cd2c9a2, I just neglected to `git add`!
1. 👉 #3499 👈 **YOU ARE HERE**
> [IR] Add tests for memdesc_subview verifier.

- python/triton/language/core.py
This was removed in 47a35b6ead3f, but we'd meant to keep it temporarily.
This change also restores the default precision back to tf32 where supported.
> [Frontend] Add `allow_tf32` param back to tl.dot.

- .gitignore
- README.md
- docs/conf.py
- docs/getting-started/installation.rst
- docs/python-api/triton.language.rst
- docs/python-api/triton.testing.rst
- python/triton/language/math.py
- python/triton/testing.py
- python/tutorials/04-low-memory-dropout.py
Added new ops to docs along with other docs fixes.
> [Docs] Docs update

- python/triton/language/extra/cuda/__init__.py
- python/triton/language/extra/cuda/utils.py
- third_party/nvidia/backend/compiler.py
Partially revert previous PR to avoid breaking V100
> [FRONTEND] Fix float8 sw conversion for V100

- python/triton/language/core.py
- python/triton/language/semantic.py
- python/triton/language/standard.py
- python/triton/runtime/jit.py
1. Address some flake8 issues like "don't call a function in argument defaults".
2. Replace some `assert False` by `TypeError` with more informative messages.
3. Remove unused variables
> [FRONTEND][NFC] Frontend cleanup

- .github/workflows/integration-tests.yml
- third_party/amd/backend/driver.py
Add missing mappings for AMD target
> [AMD] Fix test_annotations.py

- lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
- test/TritonGPU/combine.mlir
Now that we have a caching mechanism we can prevent even more duplicated IR.
> [BACKEND] Add to the caching during backward rematerialization

- .github/workflows/integration-tests.yml
These tests are passing. Enable them for AMD
CI testing too to avoid regression.
> [ci][amd] Turn on LIT tests

- lib/Dialect/Triton/IR/Ops.cpp
Triton IR should not dependent on anything from Triton GPU
> Remove wrong dependency between TTIR and TritonGPU

- .github/workflows/integration-tests.yml
> Revert "[CI] Disable A100 build temporarily"

- lib/Dialect/TritonGPU/Transforms/Pipeliner/PipelineExpander.cpp
Merging change "[MLIR][SCF] Add checks to verify that the pipeliner schedule is correct. #77083" by ThomasRaoux from the llvm repo
co-authored-by: Thomas Raoux <thomasraoux@openai.com>
> Merge Pipeline Expander Verifier from LLVM upstream

- .github/workflows/integration-tests.yml
This PR is to turn on all the unit tests that passed on AMD backend.
> [AMD backend] turn on more unit tests for better coverage

- docs/conf.py
I'd like to add a favicon too, but my image editing skills are not great.
> Add Triton logo to docs.

- .github/workflows/integration-tests.yml
This removes a dedicated step for operators to have better parallelism.
> [ci] Merge operators test into the main step for parallelism

- include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
- python/test/unit/language/test_core.py
- third_party/amd/backend/compiler.py
- third_party/amd/include/TritonAMDGPUTransforms/MfmaGroup.h
- third_party/amd/include/TritonAMDGPUTransforms/Passes.h
- third_party/amd/include/TritonAMDGPUTransforms/Passes.td
- third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/MFMA.cpp
- third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp
- third_party/amd/lib/TritonAMDGPUTransforms/MfmaGroup.cpp
- third_party/amd/python/triton_amd.cc
Upstream https://github.com/ROCm/triton/pull/476
> [AMD] Add kpack and enable larger lds vecSize

- python/triton/runtime/jit.py
This further reduces kernel launch overhead from 18us to 15us.
> Even faster jit

- python/triton/runtime/interpreter.py
- python/triton/runtime/jit.py
* `if x:` was to check None-ness is incorrect for e.g. x==0
*  argreduce index type should be int32
*  interpreter should copy back into data to handle cases where tensors can't be modified in-place
> [INTERPRETER] fixed some bugs

- .github/workflows/integration-tests.yml
- python/tutorials/06-fused-attention.py
- third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandHelper.cpp
- third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandHelper.h
- third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
Fix address computation for cases swizzle pattern do not fit into one block of warps.
> [AMD] General Shared to dot op conversion

- lib/Analysis/Utility.cpp
FunctionOpInterface support tt.func and func.func
> [Utility] extend FuncOp to FunctionOpInterface

- python/triton/ops/matmul_perf_model.py
For strange systems-y reasons most of Meta's prod machines don't have `nvidia-smi` installed.  So if that's not found, try pynvml.
> [ops] Fallback to pynvml if nvidia-smi isn't available

- .github/workflows/integration-tests.yml
- .github/workflows/integration-tests.yml.in
- python/triton/runtime/interpreter.py
This allows running attention tutorial through the interpreter.
> [INTERPRETER] Fix multiply_of for induction var

- .github/workflows/wheels.yml
- python/setup.py
Reverts openai/triton#3712
The changes were causing failures on our internal gcc build.
> Revert "[CI] Upgrade CI wheel build to many_linux_2_28."

- .github/workflows/wheels.yml
- python/setup.py
Reverts openai/triton#3720. Restores #3712.
> Restore "[CI] Upgrade CI wheel build to many_linux_2_28."

- include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td
- lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp
- python/test/unit/hopper/test_experimental_tma.py
- test/Conversion/tritonnvidiagpu_to_llvm.mlir
- third_party/nvidia/backend/driver.c
- third_party/nvidia/backend/driver.py
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/BarrierOpToLLVM.cpp
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp
This adds the low level pieces to support TMA load in triton. This is not hooked to the front end yet but can be tested with TTGIR test.
This is part of an experimental effort to support TMA operations on hopper without breaking Triton programming model.
> [BACKEND] Add TTGIR operations to support TMA load

- third_party/proton/proton/scope.py
- third_party/proton/test/test_api.py
- third_party/proton/tutorials/matmul.py
> [PROTON] And add an example usage to annotate autotuned configurations

- python/test/unit/runtime/test_cache.py
- python/triton/runtime/jit.py
Consider the following code.
GLOBAL_VAR = 1
@triton.jit
def kernel():
a = GLOBAL_VAR
kernel[(1,)]()
GLOBAL_VAR=2
kernel[(1,)]()
Before this patch, the code above would run without error, but the second time
it ran, `a` would get the old value of `GLOBAL_VAR`, i.e. 1.  This is because
the value of GLOBAL_VAR "baked in" to the kernel that Triton compiles.
Now this instead raises an error on the second invocation.
> [Frontend] Error on changes to global vars used in kernels.

- python/tutorials/03-matrix-multiplication.py
- python/tutorials/06-fused-attention.py
This PR adds some tuned configs in the gemm and fa (only the fwd path) tutorial for f16 inputs. Therefore, users can get a decent performance (not optimal) out of the tutorials.
> [AMD] Add tuned configs in gemm and FA tutorials

- test/Conversion/amd/decompose-unsupported-conversions.mlir
- third_party/amd/backend/compiler.py
- third_party/amd/include/TritonAMDGPUToLLVM/Passes.h
- third_party/amd/include/TritonAMDGPUToLLVM/Passes.td
- third_party/amd/lib/TritonAMDGPUToLLVM/DecomposeUnsupportedConversions.cpp
- third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp
- third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.h
- third_party/amd/lib/TritonAMDGPUToLLVM/TritonGPUToLLVM.cpp
- third_party/amd/python/triton_amd.cc
This avoids us to have random magic numbers floating around in different passes.
> [backend][amd] Get shared memory limit from TargetInfo

- third_party/amd/lib/TritonAMDGPUTransforms/CMakeLists.txt
This caused a race condition caught in documentation build.
> Add missing cmake dependency

- python/tutorials/06-fused-attention.py
> Remove unnecessary empty from flashattention tutorial

- third_party/nvidia/backend/compiler.py
Fixes https://github.com/triton-lang/triton/issues/3899.
> [Backend] Increase max PTX version from 8.0 to 8.3.

- python/triton/compiler/backends/cuda.py
- python/triton/language/semantic.py
(cherry picked from commit 39f4473f9cf431a1890ffcfcbbdc5fffbe4c7984)
> [FRONTEND] fix default `max_num_imprecise_acc` (#2804)

- python/setup.py
- python/triton/__init__.py
- python/triton/common/backend.py
Same as: https://github.com/triton-lang/triton/commit/e2f1b5890cf77b891b1e986a36fa8f6a5cb7d24c
> Version: 2.3.1

- python/tutorials/02-fused-softmax.py
A100 has smaller SMEM, so reducing num_stages correspondingly.
> [TUTORIAL][softmax] reduce num_stages to accommodate A100

- lib/Analysis/Utility.cpp
- test/TritonGPU/amd/accelerate-amd-matmul-wmma.mlir
- third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp
Convert operands to fp16 and apply fp16 wmma instruction.
Add lit test.
> [AMD][Navi31] Apply WMMA for fp8

- python/test/unit/language/test_core.py
This matches the behavior of the function.
> [CI] Rename check_cuda_only() to check_cuda_or_hip().

- python/test/unit/language/test_core.py
- Add wmma layouts building to test_core
- Patch filtering to get applicable layouts for different archs
- Fix test_reduce_layouts for Navi31
> [AMD] Test WMMA layout on RDNA3 devices

- lib/Dialect/TritonGPU/Transforms/CombineTensorSelectAndIf.cpp
- test/TritonGPU/combine-select-if.mlir
When multiple selects gets merged to the same ifop we need to make sure we don't use a stale IfOp during transformation.
> [BACKEND] Fix crash in combine select and if op

- include/triton/Tools/LinearLayout.h
- Correct some indices errors.
> [DOCS] improve Triton Linear layout doc

- include/triton/Dialect/Triton/IR/TritonTypes.td
- include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
- include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td
- lib/Analysis/Alias.cpp
- lib/Analysis/Allocation.cpp
- lib/Conversion/TritonGPUToLLVM/DecomposeUnsupportedConversions.cpp
- lib/Conversion/TritonGPUToLLVM/MemoryOpToLLVM.cpp
- lib/Dialect/Triton/IR/Ops.cpp
- lib/Dialect/Triton/IR/Types.cpp
- lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
- lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp
- lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
- lib/Dialect/TritonGPU/Transforms/Pipeliner/TMAStoresPipeline.cpp
- lib/Dialect/TritonGPU/Transforms/Prefetch.cpp
- lib/Dialect/TritonGPU/Transforms/ReduceDataDuplication.cpp
- lib/Dialect/TritonNvidiaGPU/Transforms/TMALowering.cpp
- python/test/unit/hopper/test_experimental_tma.py
- python/test/unit/language/test_core.py
- test/Analysis/test-alias.mlir
- test/Analysis/test-allocation.mlir
- test/Analysis/test-membar.mlir
- test/Conversion/amd/decompose-unsupported-conversions.mlir
- test/Conversion/tritongpu_to_llvm.mlir
- test/TritonGPU/loop-pipeline-hopper.mlir
- test/TritonGPU/loop-pipeline.mlir
- test/TritonGPU/reduce-data-duplication.mlir
- test/TritonNvidiaGPU/membar.mlir
- third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMMAv2.cpp
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DecomposeUnsupportedConversions.cpp
Currently only shared memory is supported but this will allow supporting different kinds of local memory (like private) or others.
> [BACKEND] Add memory space to memdesc type.

- python/tutorials/06-fused-attention.py
Based on 
`@pytest.mark.parametrize("Z, H, N_CTX, HEAD_DIM", [(1, 2, 1024, 64)])`
`BATCH, N_HEADS, HEAD_DIM = 4, 32, 64`
the HEAD_DIM is `64` in both pytest and benchmark, which triggers assertion failure from `tl.static_assert(BLOCK_N <= HEAD_DIM)` since BLOCK_N can be `128` in the tunning.
Therefore, change the tunning size for `BN` as `[32, 64]`.
Both pytest and benchmark runs fine on GPU after the fix.
> [TUTORIALS] Minor fix for tutorial 06

- lib/Analysis/AxisInfo.cpp
- python/triton/ops/cross_entropy.py
fix #3992 and an additional typo
> [DOCS] fix issue #3992 and an additional typo

- lib/Dialect/TritonGPU/Transforms/Prefetch.cpp
- third_party/nvidia/backend/compiler.py
This will enable prefetching for mma-v2 dots on H100.
> Run prefetch on mma-v2 dots

- .github/PULL_REQUEST_TEMPLATE.md
- Reduce nesting of the checklist to make it a little easier to read.
- Link to external suggestions for writing a good PR description.
- Suggest that people run their code and comments through an LLM if they need
help writing idiomatic English.
> Edit PR template.

- lib/Dialect/Triton/Transforms/RewriteTensorPointer.cpp
- test/Triton/rewrite-tensor-pointer.mlir
> [Backend] fix RewriteTensorPointer opInFor

- .github/PULL_REQUEST_TEMPLATE.md
Based on feedback in https://github.com/triton-lang/triton/pull/4050.
> Attempt to make the PR template more actionable.

- .github/workflows/integration-tests.yml
- python/test/unit/language/test_standard.py
- python/triton/language/standard.py
- python/tutorials/03-matrix-multiplication.py
Fix #4008 
The proposal in the issue is indeed correct.
```
new_i = off_i + ((ij % size_gj) % size_g)
new_j = (ij % size_gj) // size_g
```
Details
```
ij = ij % size_gj
new_i = off_i + ij % size_g    -> row index (ij % size_g) wrt the first element in this group 
-> plus the row index of the first element itself.
new_j = ij // size_g               -> column index (ij // size_g) wrt the first element in this group
```
Added `test_swizzle2d` in `/python/test/unit/language/test_standard.py`.
checks passed
> Fix the swizzle2d traversal order

- python/test/unit/language/test_standard.py
- python/triton/language/standard.py
Improve the python/triton/language/standard.py and python/test/unit/language/test_standard.py
Minor update to the tests.
instructions necessary to exercise the bug.  (Usually running Python …
> Update doc and test for standard

- python/tutorials/09-persistent-fp8-matmul.py
- third_party/proton/csrc/lib/Profiler/CuptiProfiler.cpp
Including performance comparison between naive matmul (improved version of tutorial matmul), cuBLAS implementation, persistent kernel w/o and w/ TMA.
> Adding tutorial for persistent kernel - fp8 matmul

- python/triton/language/standard.py
- python/triton/testing.py
- python/tutorials/09-persistent-fp8-matmul.py
Improve docs and minor fixes in testing.py.
Add the hopper check for tutorial 09.
instructions necessary to exercise the bug.  (Usually running Python code
and using the instructions it …
> [DOCS] Improve docs and minor fixes in testing.py

- include/triton/Conversion/TritonGPUToLLVM/Utility.h
- lib/Conversion/TritonGPUToLLVM/Utility.cpp
<git-pr-chain>
Convert `emitOffsetForLayout` to use LLs.
1. 👉 #4110 👈 **YOU ARE HERE**
> Convert `emitOffsetForLayout` to use LLs.

- python/tutorials/09-persistent-fp8-matmul.py
`Could not find docstring in file "/home/runner/actions-runner/_work/triton/triton/python/tutorials/09-persistent-fp8-matmul.py". A docstring is required by sphinx-gallery unless the file is ignored by "ignore_pattern"
`
https://github.com/triton-lang/triton/actions/runs/9432384769/job/25982058790
Add a summative description.
> [DOC] Fix documentation pipeline

- python/test/unit/language/test_block_pointer.py
- python/test/unit/language/test_conversions.py
- python/triton/language/math.py
Improve docs and minor fixes in test_block_pointer and test_conversions
and using the instructions it generates …
> [DOCS] Improve docs and minor fixes in test_block_pointer and test_conversions

- python/triton/language/core.py
Add parameter types and improve docs for core.py
> [DOCS] Add parameter types and improve docs for core.py

- include/triton/Analysis/Utility.h
- include/triton/Tools/LinearLayout.h
- lib/Analysis/Allocation.cpp
- lib/Analysis/Utility.cpp
- lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
- lib/Tools/LinearLayout.cpp
- test/Analysis/test-allocation.mlir
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ConvertLayoutOpToLLVM.cpp
- unittest/Tools/LinearLayoutTest.cpp
<git-pr-chain>
1. [WIP] Use LLs for register-to-register convert-layout ops.
1. Add additional LL tests.
1. Update test to avoid nop conversions
1. 👉 #4125 👈 **YOU ARE HERE**
> Use LLs for register-to-register convert-layout ops.

- lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp
- third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.h
- unittest/Dialect/TritonGPU/LinearLayoutConversionsTest.cpp
This commit adds WMMA to linear layout conversion.
> [AMD] Support convert WMMA to linear layout

- third_party/proton/README.md
- third_party/proton/csrc/include/Data/Data.h
- third_party/proton/csrc/include/Data/TraceData.h
- third_party/proton/csrc/include/Data/TreeData.h
- third_party/proton/csrc/include/Driver/GPU/CuptiApi.h
- third_party/proton/csrc/include/Profiler/GPUProfiler.h
- third_party/proton/csrc/lib/Data/TraceData.cpp
- third_party/proton/csrc/lib/Data/TreeData.cpp
- third_party/proton/csrc/lib/Driver/GPU/CuptiApi.cpp
- third_party/proton/csrc/lib/Profiler/CuptiProfiler.cpp
- third_party/proton/csrc/lib/Profiler/RoctracerProfiler.cpp
- third_party/proton/proton/hook.py
- third_party/proton/test/test_profile.py
- third_party/proton/tutorials/matmul.py
> [PROTON] Supoprt cuda graph profiling for nvidia gpus

- .github/workflows/integration-tests.yml
- .github/workflows/integration-tests.yml.in
- python/setup.py
Cherry Pick of https://github.com/triton-lang/triton/pull/4138 to release/3.0.x branch
> [BUILD] Change hatchet as an extra dependency (#4138)

- python/triton/language/extra/hip/libdevice.py
Cherry pick #4086 for release/3.0.x
> [AMD] Add more math functions in libdevice (#4086)

- lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
- test/TritonGPU/combine.mlir
Cherry pick #4097 for release/3.0.x
> [BACKEND] Prevent for/yield argument number drift (#4097)

- include/triton/Tools/LinearLayout.h
- lib/Tools/LinearLayout.cpp
- unittest/Tools/LinearLayoutTest.cpp
<git-pr-chain>
Add LinearLayout::sublayout.
This is used in a future LLs PR.
1. 👉 #4180 👈 **YOU ARE HERE**
1. #4181
> Add LinearLayout::sublayout.

- include/triton/Tools/LinearLayout.h
- lib/Tools/LinearLayout.cpp
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.cpp
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/Utility.cpp
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/Utility.h
- unittest/Tools/LinearLayoutTest.cpp
<git-pr-chain>
Fix bugs in load/storeDShared.
Unfortunately we can't test this directly today.  But all of these bugs were
found by a WIP PR running existing unit tests.
1. #4180
1. 👉 #4181 👈 **YOU ARE HERE**
> Fix bugs in load/storeDShared.

- lib/Dialect/TritonGPU/IR/Dialect.cpp
- test/Conversion/tritongpu_to_llvm.mlir
Cherry-picking  https://github.com/triton-lang/triton/pull/4061  for release/3.0.x
> [RELEASE][BACKEND] Fix getThreadsPerWarp for MD sliced encoding (#4061)

- include/triton/Dialect/Triton/IR/TritonOps.td
- lib/Dialect/Triton/IR/Ops.cpp
- test/Triton/canonicalize.mlir
add a folder pattern for AdvanceOp: advance(ptr, 0, 0) -> ptr
> [BACKEND] add folder for AdvanceOp

- third_party/amd/lib/TritonAMDGPUToLLVM/DecomposeUnsupportedConversions.cpp
ReduceOp promotion was introduced in https://github.com/triton-lang/triton/pull/3153 to fix `test_reduce1d` and `test_reduce`. This is not necessary. And it doesn't work if there is a callOp in the body of the reduceOp, since the type of the callee function definition is not promoted.
> [AMD] Remove promotion for reduceOp

- README.md
This commit change the main README.md only. I updated AMD GPUs to the officially support hardware.
CC: @antiagainst
> [AMD] NFC:Adding AMD GPUs to official support in main branch

- README.md
This commit change the main `README.md` only. I updated AMD GPUs to the officially support hardware.
CC: @antiagainst
> [AMD] NFC:Adding AMD GPUs to official support in release branch

- python/setup.py
To incorporate latest changes and release 3.0.0-post1
Same as:
https://github.com/triton-lang/triton/commit/ea70d7715816eb912de41be3e13ef0bae11ede79
> [VERSION] Bumped to 3.0.0-post1

- .github/workflows/wheels.yml
- python/setup.py
Cherry-pick of 4383d2835d8533bedacac95915b6b740c9fa40d8 and 5eb4ba518eb5b07084562ed584f336a926f6ace3 from 2.0.X to 3.0.X branch
> Repack wheels with build-number 1

- third_party/nvidia/backend/compiler.py
Drop an unnecessary indirection through the shell when running `ptxas`, and run `subprocess.run` with arguments that are compatible with internal use of `posix_spawn` (rather than `fork` + `exec`) which is safer in the presence of RDMA-registered memory. See https://blog.nelhage.com/post/a-cursed-bug/.
Tested by:
- patching `subprocess.py` to log which one it was using, and confirming it was following the `posix_spawn` path (on Ubuntu 20.04)
- patching the call to `ptxas` to have bad arguments and checking the error output to make sure I didn't mangle the error-file handling
Answers to form questions:
- I am not making a trivial change, such as fixing a typo in a comment.
- I have written a PR description following these [rules](https://cbea.ms/git-commit/#why-not-how).
- I have run …
> use posix_spawn to launch ptxas

- python/src/ir.cc
Add get_bool_attr binding. This is useful in getting out bool attributes from ir
> Add get_bool_attr binding

- .github/workflows/integration-tests.yml
- .github/workflows/integration-tests.yml.in
This PR temporarily disables the MI300 CI node since there are some issues regarding the machine that need to be resolved.
> [AMD] Temporarily disable MI300 CI

- third_party/proton/proton/viewer.py
- third_party/proton/test/example_cuda.json
- third_party/proton/test/test_viewer.py
> [PROTON] Set non-derivable metrics as `nan`

- test/TritonGPU/amd/optimize-lds-usage.mlir
- third_party/amd/lib/TritonAMDGPUToLLVM/OptimizeLDSUsage.cpp
This PR fixes processign of shared memmory shortcuts in OptimizeLDSUsage pass and adds related test.
> [AMD] Fix assert in OptimizeLDSUsage pass

- third_party/nvidia/backend/compiler.py
Currently when `ptxas` segfaults, Triton prints a message asking the user to confirm the crash by running `ptxas the_bad_input.ptx`. However:
* the exact repro command is not shown to the user
* the bad `.ptx` file is not preserved
This PR preserves the bad `.ptx` file and prints the exact repro command. This makes it possible to actually repro the segfault and report the bug upstream.
```
$ python test.py
...
RuntimeError: Please run `ptxas /tmp/tmpzt0bfsko.ptx` to confirm that this is a bug in `ptxas`
```
Necessary files are not preserved:
```
$ ptxas /tmp/tmpzt0bfsko.ptx
ptxas fatal   : Input file '/tmp/tmpzt0bfsko.ptx' could not be opened
ptxas fatal   : Ptx assembly aborted due to errors
```
```
$ python test.py
...
RuntimeError: `ptxas` raised SIGSEGV
`ptxas` stderr:
Repro command: …
```
> Preserve information needed for repro when ptxas segfaults

- python/test/unit/runtime/test_cache.py
- python/triton/runtime/jit.py
This gives finer grain control on specialization.
> [FRONTEND] Add control to disable specialization on alignment

- include/triton/Conversion/TritonGPUToLLVM/Utility.h
- include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
- lib/Conversion/TritonGPUToLLVM/Utility.cpp
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp
- python/test/unit/language/test_core.py
- test/Conversion/amd/decompose-unsupported-conversions.mlir
- test/Conversion/amd/tritongpu_wmma_dot_to_llvm.mlir
- test/TritonGPU/amd/accelerate-amd-matmul.mlir
- test/TritonGPU/invalid-attributes.mlir
- test/TritonGPU/ops.mlir
- third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandWMMA.cpp
- third_party/amd/lib/TritonAMDGPUToLLVM/DecomposeUnsupportedConversions.cpp
- third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/WMMA.cpp
- third_party/amd/lib/TritonAMDGPUToLLVM/OptimizeLDSUtility.cpp
- third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp
- unittest/Dialect/TritonGPU/LinearLayoutConversionsTest.cpp
- Introduced version field for AMDWmmaEncodingAttr
- Fixed methods related to replicated data
- Added simple unit tests for AMDWmmaEncodingAttr::version=2
- Refactored AMDWmmaEncodingAttr methods naming
- Added required asserts for WMMAv2 compilation pipeline
> [AMD][gfx12] Introduce 2nd version of WMMA layout

- docs/meetups/08-06-2024/notes.md
> Create notes.md for August 2024 meetup

- python/test/unit/language/test_core.py
There doesn't seem to be any test coverage for this.
> [TEST] Check return value of atomic_rmw

- test/Conversion/amd/tritongpu_wmma_dot_to_llvm.mlir
- third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandWMMA.cpp
- Added separate method for tensor element mapping specific for WMMAv2
- Added a lit test to verify number of llvm instructions
> [AMD][gfx12] Support Shared to dot WMMAv2 operand conversion

- .github/workflows/integration-tests.yml
- .github/workflows/integration-tests.yml.in
The machine still have internet connection issues. So taking down. This reverts commit d55edef38113d71a12709a0b77c8e944d6507ce5.
> Revert "[CI][AMD] Reenable MI300 CI (#4453)"

- lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
- lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
- test/TritonGPU/combine.mlir
Propagating layouts of a DotWaitOp operand to its corresponding result instead of all results.
> [BACKEND] Fix DotWaitOp layout propagation.

- python/test/unit/runtime/test_cache.py
- python/triton/runtime/jit.py
Add new hook to signal to user thar compilation is done. In combination to the cache_hook this will allow user to know when compilation starts and when it ends.
> [FRONTEND] Add hooks to signal that compilation is done

- .github/workflows/integration-tests.yml
- .github/workflows/integration-tests.yml.in
Disable to update firmware on the machine.
> [CI][AMD] Disable MI200 CI

- .github/workflows/integration-tests.yml
- .github/workflows/integration-tests.yml.in
Firmware updated after upgrading kernel-mode driver to the newer version 6.2.0
Tested test_randn and test_ptx_cast for an hour as a usual reproducer and no longer shows any failure.
> [CI][AMD] Re-enable MI200 CI

- python/test/unit/language/test_core.py
Missed this one test the last time.
> [TEST] Use device fixture for test_math_extern

- python/test/unit/language/test_core.py
- python/triton/compiler/code_generator.py
> [testing] Complete test_const with the rest of the failing tests.

- lib/Dialect/TritonGPU/Transforms/Pipeliner/PipelineExpander.cpp
Mirrored from upstream change:
https://github.com/llvm/llvm-project/pull/107442
> [Pipeliner] Properly fail instead of assert if cannot predicate op

- python/test/unit/language/test_compile_errors.py
- python/test/unit/language/test_conversions.py
- python/triton/language/core.py
- python/triton/runtime/interpreter.py
- third_party/amd/backend/compiler.py
- third_party/nvidia/backend/compiler.py
> [frontend] Warn on usage of fp8e4b15 on Hopper rather than error

- python/test/unit/language/test_compile_errors.py
- python/test/unit/language/test_core.py
- python/triton/language/extra/cuda/libdevice.py
- python/triton/language/extra/hip/libdevice.py
- python/triton/language/semantic.py
- python/triton/language/standard.py
Explicit is better than implicit
> [Frontend] Warn on implicit casting in the condition in tl.where

- python/triton/language/semantic.py
> [Frontend] Improve the error when doing tensor[uint32] * -3

- lib/Dialect/TritonGPU/Transforms/Utility.cpp
- test/TritonGPU/repro/sort_with_index.mlir
Cherry Pick of #4311 to
release/3.1.x branch
> Cherry Pick of #4311 to release/3.1.x branch

- lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
- test/TritonGPU/loop-pipeline-hopper.mlir
Cherry Pick of #4247 to release/3.1.x branch
> Cherry Pick of #4247 to release/3.1.x branch

- python/tutorials/06-fused-attention.py
> Fix ylabel for tutorial 06-fused-attention

- lib/Dialect/TritonGPU/Transforms/Pipeliner/PipelineExpander.cpp
- test/TritonGPU/loop-pipeline.mlir
This mirrors upstream patch https://github.com/llvm/llvm-project/pull/108964
> [Pipeliner] Fixed the epilogue predicate

- third_party/amd/lib/TritonAMDGPUTransforms/StreamPipelineV2.cpp
- manage intermediate data structures
- clean function interfaces
- give consistent naming via data-members
> [AMD][NFC] Encapsulate scheduling/pipelining details in StreamPipeliner class

- python/test/unit/language/test_core.py
- third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/WMMA.cpp
Fix crashes in unit tests for gfx12.
> [AMD] Add missing i16 for wmma and disable some tests

- lib/Dialect/Triton/Transforms/RewriteTensorPointer.cpp
- test/Triton/rewrite-tensor-pointer.mlir
- tl.num_stages lost in translation
> Copy attributes to new loop in RewriteTensorPointer

- include/triton/Conversion/TritonGPUToLLVM/Utility.h
<git-pr-chain>
[Backend] Use symbol table to lookup smem base
Unlikely to make a huge perf difference, but doing a symbol table lookup here
is a bit cleaner.
1. 👉 #4853 👈 **YOU ARE HERE**
1. #4854
1. #4855
> [Backend] Use symbol table to lookup smem base

- include/triton/Dialect/Triton/IR/TritonOps.td
- python/src/ir.cc
<git-pr-chain>
[IR] Add convenience builder function for program id ops
1. 👉 #4855 👈 **YOU ARE HERE**
> [IR] Add convenience builder function for program id ops

- python/triton/language/_utils.py
- python/triton/language/core.py
<git-pr-chain>
[Frontend] Factor out block shape validation function
1. 👉 #4915 👈 **YOU ARE HERE**
1. #4916
> [Frontend] Factor out block shape validation function

- lib/Dialect/TritonGPU/Transforms/F32DotTC.cpp
See #4603.
---
Here is precision/performance comparison before/after this PR (on A100):
<details>
<summary>The script used for testing</summary>
```
import pandas as pd
import torch
import torch.utils.benchmark as benchmark
import triton
import cutlass
dtype = torch.float32
device = "cuda"
loss = torch.nn.MSELoss()
def cutlass_mm(a, b):
assert a.shape[1] == b.shape[0], "Incompatible dimensions"
m, n = a.shape[0], b.shape[1]
d = torch.empty((m, n), dtype=a.dtype, device=a.device)
plan = cutlass.op.Gemm(element=torch.float32, layout=cutlass.LayoutType.RowMajor)
plan.math_operation = cutlass.MathOperation.multiply_add_fast_f32
alpha = 1
beta = 0
plan.run(a, b, d, d, alpha, beta, print_module=False)
return d
@triton.jit
def triton_mm_kernel(
a_ptr,
b_ptr,
c_ptr, …
```
> Fix 3xTF32 precision issues

- python/test/unit/language/test_pipeliner.py
- python/test/unit/runtime/test_cache.py
- python/test/unit/test_debug.py
> [TEST] Use device fixture for unit tests

- python/setup.py
This will make it easier to support other platforms downstream. I hope that such code should not complicate the support of Triton itself.
> [NFC] Make cuda links parameterizable by `system` parameter

- third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp
This commit refactors the AccelerateAMDMatmul patterns in prep for mxfp support so that upcoming changes can be easier to review.
> [AMD] NFC: Refactor AccelerateAMDMatmul patterns

- python/src/interpreter.cc
- python/test/unit/language/test_core.py
> [INTERPRETER] Make sure interpreter works with float16 by reusing NumPy HALF-related code

- .gitignore
- python/setup.py
Example:
```python
>>> sysconfig.get_config_var("EXE")
'.exe'
>>> sysconfig.get_config_var("EXE")
''
```
> Allow windows cuda files to be used in `setup.py`

- python/triton/language/core.py
> Fix formatting  in docs for triton.language.dot

- lib/Conversion/TritonGPUToLLVM/AssertOpToLLVM.cpp
- test/Conversion/tritongpu_to_llvm.mlir
Reverts triton-lang/triton#5035
> Revert "[BACKEND] Add barrier after assert op to avoid race condition"

- lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
- test/TritonGPU/accelerate-matmul.mlir
It's not entirely clear to me whether the previous logic was equivalent to this one, as it was rather obtuse. I think the new one is optimal but I'm happy to run benchmarks to make sure we don't regress.
> [BACKEND] Simplify and comment warp allocation logic in mmav2

- lib/Analysis/Utility.cpp
- lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
- python/test/unit/language/test_core.py
Couple of places where not handling slice layout inputs for reductions. Add support for recursive slice layout in those cases.
> [BACKEND] Fix reduce with slice layout inputs

- third_party/proton/csrc/Proton.cpp
- third_party/proton/csrc/include/Profiler/Profiler.h
- third_party/proton/csrc/include/Session/Session.h
- third_party/proton/csrc/lib/Session/Session.cpp
- third_party/proton/proton/profile.py
- third_party/proton/test/test_api.py
- third_party/proton/test/test_profile.py
Also change the default behavior or `activate` and `deactivate` to apply for all sessions but not only session 0
> [PROTON] Fix proton's support for multiple profiling sessions

- test/TritonGPU/amd/amd-reorder-instructions.mlir
- test/TritonGPU/amd/amd-sched-2nd-load.mlir
- test/TritonGPU/loop-pipeline-hip.mlir
- test/TritonGPU/loop-pipeline.mlir
- third_party/amd/backend/compiler.py
- third_party/amd/include/TritonAMDGPUTransforms/Passes.h
- third_party/amd/include/TritonAMDGPUTransforms/Passes.td
- third_party/amd/lib/TritonAMDGPUTransforms/ReorderInstructions.cpp
- third_party/amd/lib/TritonAMDGPUTransforms/StreamPipelineV2.cpp
- third_party/amd/python/triton_amd.cc
This reverts commit cc25374fa480c0b3e51cf218ed6fe7eb4c50a5bb
due to perf regressions.
> Revert "[AMD][Pipeliner] Improve clustering and add prefetch (#4881)"

- .github/workflows/llvm-build.yml
- .github/workflows/llvm-build/centos.Dockerfile
We likely need it for the PyTorch 2.6 release
> Restore the CentOS 7 build

- python/src/ir.cc
A regular SourceMgrDiagnosticHandler is causing all remarks to be emitted even if the user doesn't ask for it!
> [Triton] Default diagnostic handler only filters for errors

- lib/Dialect/TritonGPU/Transforms/OptimizeAccumulatorInit.cpp
- test/TritonGPU/accumulator-init.mlir
We need scalar select to be able to do this optimization.
> [BACKEND] Add missing precondition in optimize acc init

- lib/Conversion/TritonGPUToLLVM/Utility.cpp
- python/test/unit/language/test_core.py
- python/test/unit/language/test_pipeliner.py
- python/triton/language/core.py
When packing we should have element 0 in the lower bits, until this PR it was in higher bits.
> [MXFP] Fix packing for mxfp4 type

- lib/Dialect/TritonGPU/Transforms/Utility.cpp
- test/TritonGPU/combine.mlir
This is causing some performance regression. I'll investigate and reland it.
Reverts triton-lang/triton#5219
> Revert "Allow Layouts to propogate to local_load"

- lib/Dialect/TritonGPU/Transforms/LoopScheduling.cpp
- test/TritonGPU/loop-schedule.mlir
Don't pipeline the dot accumulator in the default heuristic.
In the finer grain control will allow user to decide.
> [PIPELINER] tweak pipeline heuristic

- lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
- python/src/ir.cc
- third_party/amd/lib/TritonAMDGPUToLLVM/TritonGPUToLLVM.cpp
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TritonGPUToLLVM.cpp
Also cleans up some includes clang thinks are unused.
> [NFC] Cleanup references to unused index dialect

- lib/Dialect/Triton/IR/Ops.cpp
- test/Triton/canonicalize.mlir
Add folding for a transpose of a splat constant.
> [BACKEND] Fold transpose(splat_const)

- lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
Fixes https://github.com/triton-lang/triton/pull/5235/files/de18e21ddf5bf03f17f779fef032d53ea87a53a0#r1858955613
> Fix Blocked FMA path in isLayoutOK

- .github/workflows/llvm-build.yml
We have a couple of PRs that landed in the `llvm-head` branch that are not in `main`.
Merging those into `main` to prevent further divergence between branches.
> Re-align main and llvm-head

- test/Conversion/tritongpu_to_llvm.mlir
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/UpcastMXFPToLLVM.cpp
Integrate code sequence made by @rawnhenry for efficient fp4 upcasting
> [BACKEND] Use an optimized ptx code sequence for fp4 upcasting

- python/test/unit/language/test_core.py
- python/triton/_internal_testing.py
- python/triton/language/core.py
- python/triton/language/semantic.py
> [FRONTEND] Fix bitcast with constexpr dtype

- python/triton/compiler/code_generator.py
In code_generator we previously had a mix of absolute and relative imports (in fact `_utils` was imported from absolutely and relatively). Let's unify to change all the imports to use relative imports since the majority were already.
Along the way I regrouped the import statements to be more clear which imports are from our package vs. system packages.
I also imported semantic directly because it was previously being used implcitly (i.e. `semantic` isn't exported from `language/__init__.py` so just relying on `import ..language` doesn't explicitly import `semantic`).
I'm starting to investigate adding typehints throughout the repo. I started with `code_generator` because they'll inherently play with the frontend of the compiler. I noticed the imports were a little confusing so I decided …
> [FRONTEND] Clean up imports in code_generator.py

- lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
- test/TritonGPU/accelerate-matmul.mlir
Cherry pick of #5277 for 3.2 release
> [BACKEND] Fix and document logic for creating warp shapes in MMAv3

- lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp
- python/test/unit/language/test_core.py
- unittest/Dialect/TritonGPU/LinearLayoutConversionsTest.cpp
There's no reason to disable this one.
> [LAYOUTS] Enable Slice(Dot) LL conversion

- test/TritonGPU/amd/optimize-lds-usage.mlir
- third_party/amd/lib/TritonAMDGPUToLLVM/OptimizeLDSUsage.cpp
- third_party/amd/lib/TritonAMDGPUToLLVM/OptimizeLDSUtility.cpp
Co-authored-by: Sam Ginzburg <ginzburg@fb.com>
(cherry picked from commit f9cdf58276a42b31151debf219c2de1471ed4422)
> [release/3.2.x] [CHERRY PICK] [AMD] Fix issue with rank=1 in tryFitCvtIntoLDS (#5084)

- README.md
Update docs following https://github.com/triton-lang/triton/pull/5127
> [Docs] Update Address Sanitizer README Documentation

- python/test/unit/language/test_core.py
We can have mxfp4, mxfp8; bf16 should be a normal type.
> [Test] NFC: Fix reverted normal_type and mxfp_type

- python/test/backend/test_device_backend.py
- python/triton/runtime/build.py
- third_party/proton/test/test_viewer.py
According to https://docs.python.org/3.9/library/subprocess.html#subprocess.check_call: `If the return code was zero then return, otherwise raise CalledProcessError.`
> [NFC] Remove dead code related to using of `subprocess.check_call`

- include/triton/Dialect/Triton/IR/Dialect.h
- lib/Analysis/Utility.cpp
- lib/Dialect/Triton/IR/Ops.cpp
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- lib/Dialect/TritonGPU/IR/Ops.cpp
- lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
- lib/Dialect/TritonGPU/Transforms/Utility.cpp
- test/Conversion/reduce_to_llvm.mlir
- test/Conversion/tritongpu_to_llvm.mlir
- test/TritonGPU/combine.mlir
- unittest/Dialect/TritonGPU/DialectTest.cpp
This reverts commit c81ed277cb23df37678217368b1d53bba9d072f7.
> Revert "Reverting #5389 (#5528)"

- test/Conversion/tritongpu_to_llvm_hopper.mlir
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/MemoryOpToLLVM.cpp
Unifying lowering path of `local_alloc` with `local_store` for the case shared mem layout has `leadingOffset`.
> Adding support for local_store lowering with stmatrix

- python/test/regression/test_cast_matmul.py
- python/test/unit/language/test_conversions.py
- python/test/unit/language/test_core.py
- python/test/unit/language/test_random.py
- python/test/unit/language/test_tuple.py
- python/test/unit/runtime/test_autotuner.py
- python/test/unit/runtime/test_cache.py
Generalize unit tests for different backends, for example not hard coding `device` with `cuda`.
> [TEST] Generalize unit tests for different backends

- include/triton/Conversion/TritonGPUToLLVM/Utility.h
- include/triton/Dialect/Triton/IR/TritonOps.td
- include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td
- lib/Conversion/TritonGPUToLLVM/Utility.cpp
- lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
- python/src/ir.cc
- python/triton/language/core.py
- python/triton/language/semantic.py
- test/Conversion/tritongpu_to_llvm.mlir
- test/TritonGPU/accelerate-matmul.mlir
- third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/UpcastMXFPToLLVM.cpp
> [FRONTEND][BACKEND] plumb `fast_math` attribute from scaled_dot frontend to LLVM codegen. Ignore NaN when set.

- third_party/amd/lib/TritonAMDGPUToLLVM/UpcastMXFPToLLVM.cpp
Following https://github.com/triton-lang/triton/pull/5582.
> [AMD] Bypass NaN check for fast math scaled dot

- lib/Analysis/AxisInfo.cpp
- lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
- python/src/ir.cc
- test/Analysis/test-alignment.mlir
- test/Triton/vecadd.mlir
- test/TritonGPU/amd/amd-convert-buffer-ops.mlir
- test/TritonGPU/combine.mlir
- test/TritonGPU/matmul.mlir
- third_party/amd/lib/TritonAMDGPUTransforms/ConvertToBufferOps.cpp
IndexCast shouldn't exist at TTIR or TTGIR level
> [NFC] Remove dead code related to IndexCastOp

- lib/Dialect/TritonGPU/Transforms/OptimizeAccumulatorInit.cpp
- test/TritonGPU/accumulator-init.mlir
This fixes https://github.com/pytorch/pytorch/issues/144705
> [cherrypick release/3.2][BACKEND] Fix accumulator init optimization for integer matmuls (#5192)

- README.md
- include/triton/Dialect/Triton/IR/Dialect.h
- include/triton/Dialect/Triton/IR/TritonOps.td
- lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp
- lib/Dialect/Triton/IR/Ops.cpp
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- lib/Dialect/TritonGPU/IR/Ops.cpp
- lib/Dialect/TritonGPU/Transforms/Utility.cpp
- test/TritonGPU/canonicalize.mlir
> [LAYOUTS] Add support for a generic transpose via LLs

- include/triton/Conversion/TritonGPUToLLVM/Utility.h
- lib/Conversion/TritonGPUToLLVM/Utility.cpp
- lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
- python/test/unit/language/test_core.py
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/UpcastMXFPToLLVM.cpp
thanks @rawnhenry for the upcast PTX code!
> [FRONTEND][BACKEND] add mxfp4 x fp16 support on nvidia

- lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
Backward remat creates a lot of dummy convert ops that should be removed before running the hosting phase otherwise we spend a lot of time looking at dummy convert.
This doesn't change the result of the pass but it helps reduce compile time and prevent combinatory explosion.
> [BACKEND] Cleanup IR after backward remat in RemoveLayoutConversions

- .github/workflows/wheels_v2.yml
In order to execute this workflow with ``workflow_dispatch`` event this needs to be part of main
> Add Wheels Build manylinux2014_x86_64 workflow

- lib/Analysis/AxisInfo.cpp
There was a FIXME left here to clean this up that's almost 2 years old.
> [Triton] Remove LLVM dialect handling from AxisInfo

- lib/Dialect/Triton/IR/Ops.cpp
- lib/Dialect/TritonGPU/IR/Ops.cpp
- test/Triton/combine.mlir
- test/TritonGPU/canonicalize.mlir
- test/TritonGPU/optimize-locality.mlir
Reverting due to regressions in internal tests
> Revert "Improve thread locality for reduction ops (#5671)"

- include/triton/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVMBase.h
- lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
- test/Conversion/tritongpu_to_ptx.mlir
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ElementwiseOpToLLVM.cpp
<git-pr-chain>
[NVIDIA] Use native bf16 ops
1. 👉 #5732 👈 **YOU ARE HERE**
1. #5733
> [NVIDIA] Use native bf16 ops

- third_party/proton/proton/hook.py
- third_party/proton/proton/profile.py
- third_party/proton/proton/proton.py
- third_party/proton/test/test_profile.py
- third_party/proton/tutorials/dynamic_net.py
- third_party/proton/tutorials/matmul.py
https://github.com/orgs/triton-lang/projects/6?pane=issue&itemId=95371680
> [PROTON-DEV] Add the instrumentation mode and clean up dependencies

- python/tutorials/09-persistent-matmul.py
- third_party/proton/proton/viewer.py
- third_party/proton/test/test_viewer.py
We show the difference between two profiles on the metric we specify
> [PROTON] Add the `-diff` option to `proton-viewer`

- third_party/proton/csrc/Proton.cpp
- third_party/proton/csrc/include/Session/Session.h
- third_party/proton/csrc/lib/Session/Session.cpp
- third_party/proton/proton/profile.py
- third_party/proton/test/test_lib.py
Fixed PC sampling error in proton when we have `mode`.
> [Proton] Fixed pc sampling error

- README.md
Add a reference to https://github.com/redhat-et/triton-dev-containers which contains a set of Development Containers for Triton. Development containers have the following Key benefits:
- **Consistency**: All developers can work with the same development environment, ensuring uniform behavior across different systems.
- **Isolation**: The container prevents potential conflicts with software  installed on your local machine.
- **Portability**: Easily share the development environment with team members, minimizing onboarding time and setup issues.
including the "tests should be minimal" …
> doc: update readme with dev container info

- lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
That partial revert left a couple auxiliary functions that are not
currently needed.
> [NFC] Finish clean-up of #5834

- include/triton/Dialect/TritonGPU/Transforms/Utility.h
- lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
- lib/Dialect/TritonGPU/Transforms/Utility.cpp
- test/TritonGPU/loop-pipeline-expand.mlir
Make sure we allocate the right number of slices when doing mmav3 pipelining.
> [Pipelinier] Fix mmav3 pipelining

- python/test/unit/language/test_matmul.py
Reduce unnecessary config, re-enable a test and simplify simple_matmul
> [Tests] Re-enable tests and clean up test_matmul

- third_party/amd/include/TritonAMDGPUToLLVM/TargetUtils.h
- third_party/amd/lib/TritonAMDGPUToLLVM/BufferOpsEmitter.cpp
- third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp
- third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp
- third_party/amd/lib/TritonAMDGPUToLLVM/TargetUtils.cpp
- third_party/amd/lib/TritonAMDGPUToLLVM/Utility.cpp
- third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp
- third_party/amd/python/triton_amd.cc
While also here, audit features and enable them for gfx950 when sutiable.
> [AMD] Properly categorize gfx950 in ISA family

- lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp
- lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp
- test/TritonGPU/dot-operands.mlir
- test/TritonGPU/loop-pipeline-blackwell.mlir
- test/TritonGPU/mma-pipeline-blackwell.mlir
- test/TritonNvidiaGPU/invalid.mlir
Make sure the alloc we copy into is mutable and add verifier for it.
> [Blackwell] Set mutable attribute in InjectTMemCopy

- lib/Conversion/TritonGPUToLLVM/Utility.cpp
This PR reverts part of #5645 PR, which increased number of required registers and lead to performance degradation in some tests.
> [AMD][NFC] Partially revert #5645

- third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp
This PR is a re-implementation of the PR #5633, which is for more efficient approach for the type conversion from fp32 to bf16 in the hip backend. It avoid using inline asm, so the problem (`tl.store` is lowered to `global_store_ushort` instead of `global_store_dword`) related to #5633 is gone.
It uses the same number of VGPRs and SGPRs as the main branch, but uses less number of instructions.
> [AMD] Optimize fp32 to bf16 rtne conversion

- include/triton/Dialect/TritonGPU/Transforms/PipeliningUtility.h
- include/triton/Dialect/TritonGPU/Transforms/Schedule.h
- lib/Dialect/TritonGPU/Transforms/LoopScheduling.cpp
- lib/Dialect/TritonGPU/Transforms/Pipeliner/AssignLatencies.cpp
- lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
- lib/Dialect/TritonGPU/Transforms/Pipeliner/PipeliningUtility.cpp
- lib/Dialect/TritonGPU/Transforms/Pipeliner/Schedule.cpp
- test/TritonGPU/loop-schedule.mlir
While doing the prologue+epilogue load pipelining, I found and fixes various bugs and shortcomings in the scheduler and pipeliner. Some of this code is also misc cleanups as well. Pushing them here.
> [Pipeliner] Scheduler and pipeline expander bugfixes and cleanups

- python/src/ir.cc
This makes it easier for users to share reproducer information when a crash happens within a pass.
Whenever a crash happens triton would dump this in the console:
```
module {
tt.func public @add_kernel(%arg0: !tt.ptr<f32> {tt.divisibility = 16 : i32}, %arg1: !tt.ptr<f32> {tt.divisibility = 16 : i32}, %arg2: !tt.ptr<f32> {tt.divisibility = 16 : i32}, %arg3: i32 {tt.divisibility = 16 : i32}) attributes {noinline = false} {
%c1024_i32 = arith.constant 1024 : i32
%0 = tt.get_program_id x : i32
%1 = arith.muli %0, %c1024_i32 : i32
%2 = tt.make_range {end = 1024 : i32, start = 0 : i32} : tensor<1024xi32>
%3 = tt.splat %1 : i32 -> tensor<1024xi32>
%4 = arith.addi %3, %2 : tensor<1024xi32>
%5 = tt.splat %arg3 : i32 -> tensor<1024xi32>
%6 = arith.cmpi slt, %4, %5 : tensor<1024xi32>
%7 = tt.splat …
```
> [DEBUG] Enable dumping reproducer in std::errs by default

- python/test/unit/language/test_pipeliner.py
Another follow up to https://github.com/triton-lang/triton/pull/5475. `local_alloc` count is a bit subtle for blackwell.
> [Blackwell] Fix `test_pipeliner.py` breakage

- test/TritonGPU/amd/amd-sched-2nd-load.mlir
- third_party/amd/lib/TritonAMDGPUTransforms/ReorderInstructions.cpp
This PR excludes more cases (load scalar and 1D tensor) to apply the sinkSecondLoad optimization.
> [AMD] Skip scalar and 1D tensor load for sinkSecondLoad

- test/Conversion/amd/async_ops_to_llvm.mlir
- third_party/amd/backend/compiler.py
- third_party/amd/lib/TritonAMDGPUToLLVM/Utility.cpp
Fix an error in setting the SC1 bit for cache modifiers.
> [AMD]Fix an error in the cache modifier bit setting

- include/triton/Analysis/Utility.h
- lib/Analysis/Utility.cpp
Remove unused variables and functions and simplify some logics
> [NFC][BACKEND] Simplify reduce helpers

- third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp
New architecture has increased shared_mem size.
> [AMD] Update smem size for cdna4

- lib/Dialect/TritonGPU/Transforms/Utility.cpp
- test/TritonGPU/combine.mlir
we were passing the wrong shape
> [BACKEND] Fix propagation through join op

- include/triton/Analysis/Utility.h
- lib/Analysis/Utility.cpp
LLs already cover this and more!
I saw the pass had not been removed yet. I remove it in https://github.com/triton-lang/triton/pull/6006
> [NFC] Kill isBlockedToDotShortcut

- python/test/unit/language/test_core.py
- third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp
Group threads in pairs only if their pointers are adjacent.
> [AMD][Atomic] Fix fp16 atomic operation

- include/triton/Dialect/TritonGPU/Transforms/PipeliningUtility.h
- lib/Dialect/TritonGPU/Transforms/Pipeliner/Schedule.cpp
- lib/Dialect/TritonGPU/Transforms/Pipeliner/SoftwarePipeliner.cpp
- test/TritonGPU/pipeline-lower-loop.mlir
- test/TritonGPU/pipeline-schedule-loop.mlir
Marking a loop with serialized schedule data with an attribute, so getting the maximum scheduling stage is both faster and more reliable.
> [PIPELINER] Adding a marker for loop scheduling serialization

- include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td
- lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp
- lib/Dialect/TritonNvidiaGPU/Transforms/MMALowering.cpp
This sets the right side effects on tmem_alloc in order to have dead code eliminication and CSE kick off.
> [BACKEND] Dead code tmem_alloc that are not mutable

- lib/Dialect/TritonGPU/Transforms/Pipeliner/TC05MMAPipeline.cpp
- test/TritonGPU/mma-pipeline-blackwell.mlir
update the condition to be allowed to pipeline scaled_dot op. This fixes test_matmul.py
> [Blackwell] Fix condition to pipeline scaled_dot

- include/triton/Dialect/TritonGPU/IR/Dialect.h
- include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
- lib/Analysis/Allocation.cpp
- lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/FMADotUtility.cpp
- lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
- lib/Conversion/TritonGPUToLLVM/Utility.cpp
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- test/Analysis/test-allocation.mlir
- test/Conversion/amd/buffer_load_store.mlir
- test/Conversion/tritongpu_to_llvm.mlir
- third_party/amd/lib/Dialect/TritonAMDGPU/IR/Dialect.cpp
- third_party/amd/lib/TritonAMDGPUDialectToLLVM/ExtractSliceOpToLLVM.cpp
- third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/WGMMA.cpp
This function should actually be removed once we have a proper lowering
of SIMD instructions via divideLeft.
> [LAYOUTS] Implement getShapePerCTATile via LLs

- python/triton/runtime/jit.py
Specifically we avoid having an expensive import statement on the hot codepath.
> Improve JIT runtime by 30%

- .github/workflows/llvm-build.yml
- .github/workflows/wheels.yml
- python/setup.py
Cherry-Pick of:
https://github.com/triton-lang/triton/pull/6092
https://github.com/triton-lang/triton/pull/6089
> Cherry-Pick Add LLVM and triton aarch64 Almalinux build

- python/triton/__init__.py
Main branch equivalent: https://github.com/triton-lang/triton/pull/6127
> [release 3.3.x] Bump release version to 3.3

- python/triton/runtime/jit.py
Specifically we avoid having an expensive import statement on the hot codepath.
---------
Co-authored-by: Keren Zhou <kerenzhou@openai.com>
(cherry picked from commit e416604440ae8a05a7585ad9bcbdf5d070a2806d)
> [Release 3.3] [CP] Improve JIT runtime by 30%

- .github/workflows/wheels.yml
- python/setup.py
Cherry-Pick of https://github.com/triton-lang/triton/pull/6141
> Cherry-Pick Remove wheel version suffix from wheels, set fail-fast to false for wheel builds

- include/triton/Dialect/TritonGPU/IR/Dialect.h
- include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
- lib/Analysis/Utility.cpp
- lib/Conversion/TritonGPUToLLVM/HistogramOpToLLVM.cpp
- lib/Conversion/TritonGPUToLLVM/ScanOpToLLVM.cpp
- lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- lib/Dialect/TritonGPU/Transforms/OptimizeThreadLocality.cpp
- third_party/amd/lib/TritonAMDGPUToLLVM/UpcastMXFPToLLVM.cpp
- unittest/Dialect/TritonGPU/DialectTest.cpp
> [LAYOUTS] Kill getThreadsPerWarp & ...WithUniqueData

- include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td
- python/test/unit/blackwell/test_tmem.py
- python/test/unit/language/test_matmul.py
- test/Analysis/test-membar.mlir
- test/Conversion/tritongpu_to_llvm.mlir
- test/TritonGPU/amd/amd-block-pingpong.mlir
- test/TritonGPU/amd/amd-reorder-instructions.mlir
- test/TritonGPU/canonicalize.mlir
- test/TritonGPU/dot-operands.mlir
- test/TritonGPU/loop-pipeline-blackwell.mlir
- test/TritonGPU/loop-pipeline-cuda.mlir
- test/TritonGPU/loop-pipeline-expand.mlir
- test/TritonGPU/loop-pipeline-hopper.mlir
- test/TritonGPU/mma-pipeline-blackwell.mlir
- test/TritonGPU/pipeline-lower-loop.mlir
- test/TritonGPU/samples/descriptor-matmul-pipeline.mlir
- test/TritonGPU/samples/simulated-grouped-gemm.mlir
- test/TritonNvidiaGPU/tma_lowering.mlir
> [TritonGPU] Fix extra space in local_alloc asm format (NFC)

- lib/Dialect/TritonNvidiaGPU/Transforms/TensorMemoryAllocation.cpp
- test/TritonNvidiaGPU/test_tensor_memory_allocation.mlir
tmem allocations needs to be aligned on 4 columns.
> [Blackwell] Fix alignment of tmem allocations

- python/test/unit/language/test_core.py
- third_party/amd/backend/compiler.py
Pick up https://github.com/triton-lang/triton/pull/5726
for the AMD backend.
> [AMD] Enable automatic loop fusion

- third_party/amd/lib/TritonAMDGPUTransforms/CanonicalizePointers.cpp
This code in ifOp conversion clearly doesn't support cases where the origin op has multiple results because the array ref will have only 1 range:
```
rewriter.replaceOpWithMultiple(ifOp, {newIfOp.getResults()});
```
I tried to fix it for a bit but I'm not fully understand the logic of this pass so I'm just skipping it in the unsupported case for now.
> [AMD] Workaround for missing support of pointer canonicalization of ifOp

- python/test/regression/test_cast_matmul.py
Fixes https://github.com/ROCm/triton-internal/issues/423
> [AMD] Enable passing test_cast_matmul cases

- test/Conversion/amd/tritongpu_wmma_dot_to_llvm.mlir
- third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/WMMA.cpp
- Generated intrinsic for wmma calculations
- Generate tied instructions along M axis if possible
- Supported transposed case
- Added lit tests
Measured results on ``./python/tutorials/03-matrix-multiplication.py ``-like test with f16 dot result:
```
M       N       K    rocBLAS  Triton-tied  Triton-not-tied    diff
0    256.0   256.0   256.0   2.882683     2.285724         2.291969  -0.27%
1    384.0   384.0   384.0   8.765187     6.419853         6.376476   0.68%
2    512.0   512.0   512.0  15.533561    12.336188        12.135418   1.65%
3    640.0   640.0   640.0  24.777317    19.562986        19.218064   1.79%
4    768.0   768.0   768.0  30.359896    25.825817        25.973157  -0.57%
5    896.0   896.0   896.0  37.039371    31.884185        31.800316   0.26%
6   1024.0  1024.0 …
```
> [gfx11] Support tied wmma instrucrions

- README.md
> [DOCS] Mention MAX_JOBS in install instructions in README

- README.md
> docs: replaced the link to the Wheels badge

- test/Conversion/amd/tritongpu_to_llvm.mlir
- test/Conversion/amd/tritongpu_to_llvm_rdna.mlir
- third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp
Just a small cleanup to remove intrinsics with ROCDL ops.
> [AMD][BACKEND] Replace intrinsics for ballot and readlane with ROCDL ops

- lib/Dialect/TritonGPU/Transforms/WarpSpecialization/AutomaticWarpSpecialization.cpp
It's broken and needs to be fixed upstream.
> [TritonGPU] Disable integer range analysis

- lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp
- python/test/unit/cuda/test_tensor_descriptor.py
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/MemoryOpToLLVM.cpp
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.cpp
Follow up to the TODO in #6297
> [Layouts] Support stmatrix in two-cta mode

- .github/workflows/create_release.yml
This should enable to distribute sdist with Release notes.
Tesing: https://github.com/atalman/triton/releases/tag/v3.0.0
> Add release workflow to distribute sdist via Release notes

- third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp
Removes `FoldTrueCmpI` from the StreamPipeliner pass because https://github.com/triton-lang/triton/pull/6368 moved it to a separate pass but didn't remove it from the StreamPipeliner.
> [AMD] Remove FoldTrueCmpI from StreamPipeliner

- bin/RegisterTritonDialects.h
- third_party/nvidia/include/Dialect/NVWS/CMakeLists.txt
- third_party/nvidia/include/Dialect/NVWS/Transforms/CMakeLists.txt
- third_party/nvidia/include/Dialect/NVWS/Transforms/Passes.h
- third_party/nvidia/include/Dialect/NVWS/Transforms/Passes.td
- third_party/nvidia/lib/Dialect/NVWS/CMakeLists.txt
- third_party/nvidia/lib/Dialect/NVWS/Transforms/CMakeLists.txt
- third_party/nvidia/lib/Dialect/NVWS/Transforms/LowerWarpGroup.cpp
- third_party/nvidia/test/NVWS/lower_warp_group.mlir
- third_party/nvidia/triton_nvidia.cc
Developed in collaboration with @3gx
> [NVWS] lower nvws.warp_group to ttg.warp_specialize

- third_party/amd/backend/compiler.py
- third_party/amd/backend/driver.py
Add Proton Dialect AMD backend driver code to support intra-kernel profiling scratch buffer
> [PROTON-DEV] Add Proton Dialect AMD backend driver code

- include/triton/Dialect/TritonNvidiaGPU/Transforms/TMAUtilities.h
- test/TritonNvidiaGPU/tma_lowering.mlir
Fix the helper to support both cases when we are rank reducing or expanding
> [BACKEND] Also support rank reducing case in updateEncodingForShape

- lib/Dialect/TritonGPU/Transforms/WarpSpecialization/AutomaticWarpSpecialization.cpp
Looks like the pass is still buggy :(
> Revert enabling createIntRangeOptimizationsPass

- include/triton/Dialect/TritonGPU/IR/LayoutUtilities.h
- include/triton/Dialect/TritonGPU/IR/LayoutUtility.h
- lib/Dialect/TritonGPU/IR/CMakeLists.txt
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- lib/Dialect/TritonGPU/IR/LayoutUtility.cpp
- lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp
- test/TritonGPU/dot-operands.mlir
<git-pr-chain>
[BACKEND] Fix CTALayout in memdesc transpose optimization
1. 👉 #6396 👈 **YOU ARE HERE**
> [BACKEND] Fix CTALayout in memdesc transpose optimization

- include/triton/Dialect/Triton/IR/TritonOps.td
- include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td
- lib/Conversion/TritonGPUToLLVM/FuncOpToLLVM.cpp
- lib/Dialect/Triton/IR/Ops.cpp
- lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp
- test/Analysis/test-membar.mlir
These are some diffs split from other patches that didn't quite make it.
* Adds verifiers for TMA scatter ops
* Some misc code cleanup
> [TritonGPU] Misc cleanups

- README.md
- python/requirements.txt
Cherry-PIck https://github.com/triton-lang/triton/pull/6330 to release branch
> [Cherry-Pick] [Build] Pin cmake < 4

- cmake/llvm-hash.txt
Pick up https://github.com/llvm/llvm-project/commit/1cec5fffd8fddd9d85b516f876093b0e3f0eec5f
> Bump to 1cec5fffd8fddd9d85b516f876093b0e3f0eec5f

- python/test/unit/cuda/test_tensor_descriptor.py
- python/triton/runtime/interpreter.py
<git-pr-chain>
[Interpretor] Support TensorDescriptor arguments
1. 👉 #6464 👈 **YOU ARE HERE**
1. #6465
1. #6475
> [Interpretor] Support TensorDescriptor arguments

- include/triton/Dialect/TritonNvidiaGPU/Transforms/TMAUtilities.h
- lib/Dialect/TritonNvidiaGPU/Transforms/CMakeLists.txt
- lib/Dialect/TritonNvidiaGPU/Transforms/TMAUtilities.cpp
<git-pr-chain>
[NFC] Move TMA helpers out of header files
1. 👉 #6475 👈 **YOU ARE HERE**
> [NFC] Move TMA helpers out of header files

- python/triton/tools/experimental_descriptor.py
- python/tutorials/06-fused-attention.py
- python/tutorials/10-block-scaled-matmul.py
<git-pr-chain>
[TUTORIAL] Replace legacy host side TMA with TensorDescriptor
1. 👉 #6465 👈 **YOU ARE HERE**
1. #6475
> [TUTORIAL] Replace legacy host side TMA with TensorDescriptor

- .github/workflows/integration-tests.yml
- .github/workflows/integration-tests.yml.in
Also increased timeout limit a bit given we need to pull
docker images which takes some time.
> [CI] Switch to use gfx942 runner set

- include/triton/Dialect/Triton/IR/TritonOps.td
This refines the granularity for side effects where possible.
This was split from #6476
> [DIALECT] Improve granularity of Triton dialect op side effects

- include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td
- include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td
- lib/Dialect/TritonGPU/IR/Ops.cpp
This refines the granularity for side effects where possible.
This was split from https://github.com/triton-lang/triton/pull/6476
> [DIALECT] Improve granularity of Triton(NVIDIA)GPU dialect ops

- include/triton/Tools/LinearLayout.h
- lib/Dialect/TritonGPU/IR/Dialect.cpp
Now the duality between forward and backward pass should be crystal
clear
> [LAYOUTS] Use divideLeft on layout inference

- third_party/amd/lib/Analysis/RangeAnalysis.cpp
Minimal change to correct warnings
> Add deduction guide to SmallVector

- lib/Dialect/TritonNvidiaGPU/Transforms/FenceInsertion.cpp
- test/TritonGPU/fence-inserstion.mlir
Prevent crash in the pass although this could still use a lot of cleanups
> [BACKEND] Fix fence insertion analysis

- lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp
- test/TritonGPU/dot-operands.mlir
The pattern to move transpose into memory was making too many assumptions.
> [BACKEND] Fix dot-operand pattern

- lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
Reverts triton-lang/triton#6667
This is causing a regression in an internal OAI workload
> Revert "[BACKEND] backwardRematerialization cost model"

- lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
Tested on both H100 and GB200 on our internal benchmarks
> Re-land cost model with tweaks to avoid perf regression on GB200

- bench/tests/conftest.py
- bench/tests/test_compaction.py
- bench/tests/test_matmul.py
- bench/tests/test_routing.py
- bench/tests/test_swiglu.py
Also fixed a typo in `test_swiglu`
> [BENCH] Use the device fixture for all bench tests

- lib/Dialect/TritonGPU/Transforms/WarpSpecialization/LoadMMASpecialization.cpp
- test/TritonGPU/load-mma-specialization.mlir
this one got lost in the merge
> [Blackwell] Don't forget `translateTMAIndices`

- .github/workflows/llvm-build.yml
- .github/workflows/llvm-build/almalinux.Dockerfile
- .github/workflows/llvm-build/centos.Dockerfile
- scripts/build-llvm-project.sh
see recent failures to build like https://github.com/triton-lang/triton/actions/runs/14864637012/job/41738239612?pr=6586
> [BACKEND] fix inconsistent use of DLLVM_ENABLE_ZSTD

- bench/bench/bench_mlp.py
Different experts do not share the same bias
> [BENCH] Fix out of bound memory access errors when bias is used

- lib/Dialect/TritonGPU/Transforms/WarpSpecialization/PartitionLoops.cpp
- test/TritonGPU/partition-loops.mlir
Ops need to be rematerialized in topological order.
> [Warp Specialization] Fix partition loops capture order

- lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
- lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp
- lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp
- lib/Dialect/TritonNvidiaGPU/Transforms/MMALowering.cpp
- python/test/unit/blackwell/test_tmem.py
- test/Analysis/test-membar-ttng.mlir
- test/Conversion/tritongpu_to_llvm_blackwell.mlir
- test/TritonGPU/dot-operands.mlir
- test/TritonNvidiaGPU/mma_lowering.mlir
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TensorMemoryToLLVM.cpp
Also moving the tmem.cp cases to nvmma layouts so that it can be efficient with TMA
> [BACKEND] More fixes to use NVMMA layout with TMA

- third_party/amd/lib/TritonAMDGPUTransforms/OptimizeEpilogue.cpp
- [x ] This PR does not need a test because NFC.
> [AMD][NFC] using OpPatternRewriter in OptimizeEpilogue

- include/triton/Dialect/TritonGPU/Transforms/Passes.td
- include/triton/Dialect/TritonGPU/Transforms/Utility.h
- lib/Dialect/TritonGPU/Transforms/CMakeLists.txt
- lib/Dialect/TritonGPU/Transforms/Pipeliner/WGMMAPipeline.cpp
- lib/Dialect/TritonGPU/Transforms/Utility.cpp
- lib/Dialect/TritonGPU/Transforms/WGMMAPrefetch.cpp
- python/src/passes.cc
- python/test/regression/test_cast_matmul.py
- test/TritonGPU/WGMMAPrefetch.mlir
- test/TritonGPU/loop-pipeline-hopper.mlir
- third_party/nvidia/backend/compiler.py
This reverts commit 21fd9ebbf248a3da48c5dbfa51b486ab4476f327 as it breaks an internal test
> Revert "[PIPELINER] Pipeline RS WGMMA (#6804)"

- .github/workflows/integration-tests-nvidia.yml
Reverts triton-lang/triton#6816
> Revert "[CI] limit number of threads on gb200"

- lib/Dialect/Triton/Transforms/RewriteTensorDescriptorToPointer.cpp
<git-pr-chain>
[NFC] Small cleanup of tensor descriptor rewrite pass
1. 👉 #6821 👈 **YOU ARE HERE**
1. #6822
> [NFC] Small cleanup of tensor descriptor rewrite pass

- python/test/unit/language/test_core.py
- python/triton/_internal_testing.py
- test/TritonGPU/amd/accelerate-amd-matmul-wmma-gen2.mlir
- third_party/amd/backend/compiler.py
- third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/WMMA.cpp
- third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp
- Enable f8, bf8 dtype for gfx12
- Add related tests
- Fix matmul dtype matcher
> [AMD][gfx12] Enable dot for f8 operands

- third_party/amd/backend/compiler.py
- third_party/proton/csrc/include/Driver/GPU/HipApi.h
- third_party/proton/csrc/lib/Driver/GPU/HipApi.cpp
- third_party/proton/csrc/lib/Profiler/Instrumentation/HipRuntime.cpp
- third_party/proton/dialect/lib/ProtonGPUToLLVM/AllocateProtonGlobalScratchBuffer.cpp
- third_party/proton/test/test_instrumentation.py
This PR gets the final remaining Proton Dialect instrumentation tests passing on AMD
> [PROTON-DEV] Get final remaining Proton Dialect instrumentation tests passing on AMD

- python/test/unit/language/test_core.py
- python/triton/compiler/code_generator.py
- python/triton/language/core.py
> [FRONTEND] .item() as syntactic sugar for .reshape([])

- python/triton_kernels/tests/test_routing.py
- python/triton_kernels/triton_kernels/matmul_ogs.py
- python/triton_kernels/triton_kernels/matmul_ogs_details/metadata.py
This allows unmasked vectorised stores
> [BENCH] 2% speedup from aligning matmul_ogs metadata

- python/tutorials/06-fused-attention.py
This solves the sporadic failures
> [TUTORIAL] Remove invalid config in attention

- include/triton/Dialect/Triton/IR/TritonAttrDefs.td
- include/triton/Dialect/Triton/IR/TritonOps.td
- lib/Dialect/Triton/IR/Ops.cpp
- lib/Dialect/Triton/Transforms/Combine.cpp
<git-pr-chain>
[IR] Remove boundary check and padding option from load and store
These were only used by the block pointer code paths.
1. #6846
1. #6847
1. 👉 #6848 👈 **YOU ARE HERE**
> [IR] Remove boundary check and padding option from load and store

- .gitignore
- test/Conversion/tritongpu_to_llvm_hopper.mlir
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/MemoryOpToLLVM.cpp
As per title.
I'll add transpose + generic support for ldmatrix in a different pr
> [BACKEND] Support vectorisation and arbitrary bitwidth in stmatrix

- CMakeLists.txt
- pyproject.toml
- python/requirements.txt
- setup.py
> Limit supported cmake versions to be the same everywhere

- include/triton/Conversion/TritonGPUToLLVM/TargetInfoBase.h
- include/triton/Tools/LayoutUtils.h
- include/triton/Tools/LinearLayout.h
- lib/Tools/LayoutUtils.cpp
- lib/Tools/LinearLayout.cpp
- test/Conversion/tritongpu_to_llvm.mlir
- test/Conversion/tritongpu_to_llvm_hopper.mlir
- third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.h
- third_party/nvidia/include/Dialect/NVGPU/IR/NVGPUOps.td
- third_party/nvidia/lib/NVGPUToLLVM/NVGPUToLLVMPass.cpp
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/MemoryOpToLLVM.cpp
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.h
We combine the ldmatrix and stmatrix lowering paths, removing all the
previous limitations of the ldmatrix lowering.
> [BACKEND] Generic support for ldmatrix and all its variants

- python/tutorials/02-fused-softmax.py
Set `NUM_GPRS` to `NUM_REGS` by default
> [AMD][Tutorials] Set `NUM_GPRS` to `NUM_REGS` by default

- test/TritonGPU/accelerate-matmul.mlir
platform-independent env variable setting
> Use `env` bultin in `accelerate-matmul.mlir`

- python/src/gluon_ir.cc
- python/test/gluon/test_frontend.py
- python/triton/experimental/gluon/language/nvidia/blackwell/__init__.py
<git-pr-chain>
[Gluon] Add tcgen05_mma and fix non-initialized allocate_tensor_memory
1. 👉 #6998 👈 **YOU ARE HERE**
> [Gluon] Add tcgen05_mma and fix non-initialized allocate_tensor_memory

- include/triton/Dialect/Triton/IR/Interfaces.h
- include/triton/Dialect/TritonGPU/Transforms/Passes.td
- lib/Dialect/Triton/IR/Dialect.cpp
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- lib/Dialect/TritonGPU/Transforms/CMakeLists.txt
- lib/Dialect/TritonGPU/Transforms/Canonicalize.cpp
- python/src/passes.cc
- python/test/backend/test_device_backend.py
- python/test/gluon/test_frontend.py
- python/triton/backends/compiler.py
- python/triton/compiler/compiler.py
- python/triton/experimental/gluon/_runtime.py
- test/TritonGPU/inline.mlir
- third_party/amd/backend/compiler.py
- third_party/nvidia/backend/compiler.py
This PR adds a separate TTGIR optimization pass for code parsed from Gluon directly. Most important is the inliner and basic running TTGIR-level optimizations. 
I added passes that I thought were obviously good to have.
> [Gluon] Add an opt pass pipeline for gluon

- docs/conf.py
To be align with https://github.com/triton-lang/triton/blob/5bf87b477035e3405efd5fb76a094310a751f87d/setup.py#L762
> [DOCS] Update Triton version in `conf.py`

- python/test/unit/language/test_frontend.py
- python/triton/compiler/code_generator.py
This makes `foo.bar += 42` work
> [Frontend] Fix augassign into an attribute

- docs/conf.py
- python/triton/__init__.py
- setup.py
Advance current version 3.3.0 to next 3.4.0
> Advance version 3.3.0->3.4.0

- include/triton/Dialect/TritonGPU/IR/LinearLayoutConversions.h
- include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- lib/Dialect/TritonGPU/Transforms/Utility.cpp
- test/TritonGPU/reduce-data-duplication.mlir
Reland of https://github.com/triton-lang/triton/pull/6565
> [LAYOUTS] Fix mixed precision swizzling (#6565)

- python/triton_kernels/tests/test_matmul.py
- python/triton_kernels/triton_kernels/matmul_ogs.py
- python/triton_kernels/triton_kernels/matmul_ogs_details/_common.py
- python/triton_kernels/triton_kernels/matmul_ogs_details/_p_matmul_ogs.py
- python/triton_kernels/triton_kernels/matmul_ogs_details/opt_flags.py
- python/triton_kernels/triton_kernels/matmul_ogs_details/opt_flags_nvidia.py
* This uses PR #7044.
* Also streamlined "expensive epilogue" handling so that we can specify how expensive it is.
> [KERNELS] Enable 4-way epilogue subtiling for _p_matmul_ogs.

- python/test/unit/runtime/test_cache.py
forgot to add missing test before
> [TEST] Add unit test for kernel name in cache hook

- test/Conversion/cvt_to_llvm.mlir
- test/Conversion/tritongpu_to_llvm.mlir
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.cpp
- third_party/proton/test/test_cmd.py
Reverts triton-lang/triton#7067 this causes functional performance that are under investigation
> Revert "[BACKEND] Create llvm.store when we do not need predication"

- python/src/gluon_ir.cc
- python/test/gluon/test_frontend.py
- python/triton/experimental/gluon/language/_core.py
- python/triton/experimental/gluon/language/_semantic.py
<git-pr-chain>
[Gluon] Add C++ -> gluon layout translation, use to implement permute
1. 👉 #7120 👈 **YOU ARE HERE**
1. #7121
1. #7122
> [Gluon] Add C++ -> gluon layout translation, use to implement permute

- lib/Dialect/TritonGPU/Transforms/Pipeliner/LowerLoops.cpp
- test/TritonGPU/loop-pipeline-blackwell.mlir
Since the new memdesc will be mutable we need to propagate the type.
> [BACKEND] Make sure to propagate the new type when updating memdesc

- third_party/amd/language/hip/libdevice.py
To resolve https://github.com/triton-lang/triton/issues/7135
> [AMD]Support libdevice.round

- python/test/gluon/test_frontend.py
- python/triton/experimental/gluon/language/_standard.py
<git-pr-chain>
[Gluon] Add zeros, zeros_like and full_like
1. 👉 #7151 👈 **YOU ARE HERE**
1. #7152
> [Gluon] Add zeros, zeros_like and full_like

- python/triton_kernels/triton_kernels/matmul_ogs.py
fixes in https://github.com/triton-lang/triton/pull/7119 cover this condition in a way that doesn't require transposition by padding the shape of the TMA descriptor
> [kernels] remove want_n_major condition in persistent matmul

- python/test/gluon/test_frontend.py
- python/triton/compiler/code_generator.py
- python/triton/compiler/compiler.py
- python/triton/experimental/gluon/_runtime.py
- python/triton/experimental/gluon/language/_core.py
- python/triton/language/core.py
* Added `ttgl.static_assert` (and `static_print`)
* Fix binop where RHS is constexpr but LHS is not
* Fix `unwrap_if_constexpr` to recursively unwrap
> [Frontend][Gluon] Make `static_assert` actually work

- test/Conversion/cvt_to_llvm.mlir
- test/Conversion/tritongpu_to_llvm.mlir
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.cpp
- third_party/proton/test/test_cmd.py
Relanding https://github.com/triton-lang/triton/pull/7067
Depends on https://github.com/triton-lang/triton/pull/7170
This allows to create better PTX (and sometimes SASS) and helps hiding a
PTX bug we were hitting.
This PR follows https://github.com/triton-lang/triton/pull/4776
> [RELAND][BACKEND] Create llvm.store when we do not need predication

- python/test/gluon/test_frontend.py
- python/triton/experimental/gluon/language/_core.py
- python/triton/experimental/gluon/language/_semantic.py
`new_alloc_shape` was not being returned
> [Gluon] Fix memdesc_trans alloc shape 

- python/triton_kernels/triton_kernels/matmul_ogs_details/_p_matmul_ogs.py
regresses moe matmul performance
> [kernels] revert bias subtiling changes

- python/test/gluon/test_core.py
- python/test/gluon/test_frontend.py
- python/test/unit/language/test_core.py
- python/test/unit/language/test_pipeliner.py
- python/test/unit/language/test_tensor_descriptor.py
- python/triton/_internal_testing.py
<git-pr-chain>
[NFC] Add is_hopper helper and rename is_hopper -> is_hopper_or_newer
1. 👉 #7224 👈 **YOU ARE HERE**
> [NFC] Add is_hopper helper and rename is_hopper -> is_hopper_or_newer

- lib/Conversion/TritonGPUToLLVM/Utility.cpp
We are seeing some internal regressions.
This reverts commit 336cc1d530fe9df8db610e880330b9fa4de82925.
> Partially Revert "[LAYOUTS] Enable diagonal iteration unconditionally (#7218)"

- test/Conversion/tritongpu_to_llvm_blackwell.mlir
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TensorMemoryToLLVM.cpp
LLVM's `inline_asm` is only allowed to return a struct when the asm has more than 1 result. This also makes unpacked `Nx2xf16` work but `Nx1xf16` still crashes. It can be supported if it is needed.
> [Blackwell] Fix codegen for `tmem_load` of `Nx1xf32`

- test/TritonGPU/amd/amd-canonicalize-pointers.mlir
- third_party/amd/lib/TritonAMDGPUTransforms/CanonicalizePointers.cpp
Propagating divisibility and other discardable atts needs to make sure that the rank for source/destination instructions matches. When the ranks doesn't match it isn't possible to trivially propagate those attributes.
Allow propagation of attributes for same rank and also between rank 1 and scalar.
> [AMD] Fix pointer canonicalizer when propagating discardable attrs

- python/triton/compiler/code_generator.py
> [Frontend] Fix scope enter to do a deep copy of scopes

- include/triton/Conversion/TritonGPUToLLVM/Utility.h
- include/triton/Tools/LinearLayout.h
- lib/Conversion/TritonGPUToLLVM/Utility.cpp
- test/Conversion/tritongpu_to_llvm.mlir
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp
This reverts commit b1880339a2bfcd3bacd6c20bd1d22a9f02007801.
As it regresses for now.
> Revert "[BACKEND] Move cp.async to better lowering sequence (#7304)"

- python/test/unit/language/test_frontend.py
- python/triton/compiler/code_generator.py
> [Frontend] Fix detection of liveouts in conditionals

- docs/meetups/05-01-2025/notes.md
> Notes from 2025-05-01 community meetup

- docs/meetups/03-12-2025/notes.md
Notes for 2025-03-12 community meetup
> Notes from 2025-03-12 community meetup

- lib/Conversion/TritonGPUToLLVM/Utility.cpp
This may produce better codegen in certain circumstances (and according to our benchmarks it at least doesn't make anything worse)
> [LAYOUTS] Use columns as well as diagonals

- third_party/amd/lib/TritonAMDGPUToLLVM/OptimizeLDSUtility.cpp
`createTmpLayout` can return nullptr so we need to check that before directly using it for constructing layout attributes.
> [AMD] Fix crash in OptimizeLDSUtility due to nullptr

- test/Conversion/amd/invalid_concat_op.mlir
- test/Conversion/amd/invalid_extractslice_to_llvm.mlir
- test/TritonGPU/amd/amd-concat-op.mlir
- test/TritonGPU/amd/amd-extractslice-op.mlir
- third_party/amd/lib/Dialect/TritonAMDGPU/IR/Dialect.cpp
- third_party/amd/lib/TritonAMDGPUDialectToLLVM/ConcatOpToLLVM.cpp
- third_party/amd/lib/TritonAMDGPUDialectToLLVM/ExtractSliceOpToLLVM.cpp
- third_party/amd/python/test/test_extract_slice_concat_op.py
This PR:
- permits arbitrary broadcasted register in layouts
- fixes few possible crashes in verifier in case of broadcasted layouts
> [AMD] Support register broadcast in slice/concat ops

- include/triton/Dialect/Triton/IR/TritonTypes.td
- lib/Analysis/Utility.cpp
- lib/Conversion/TritonToTritonGPU/RelayoutTritonGPU.cpp
- lib/Conversion/TritonToTritonGPU/TritonGPUConversion.cpp
- lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
- lib/Dialect/Triton/IR/Ops.cpp
- lib/Dialect/Triton/IR/Types.cpp
- lib/Dialect/Triton/Transforms/ReorderBroadcast.cpp
- lib/Dialect/TritonGPU/IR/Ops.cpp
- lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
- lib/Dialect/TritonGPU/Transforms/Coalesce.cpp
- lib/Dialect/TritonGPU/Transforms/CoalesceAsyncCopy.cpp
- lib/Dialect/TritonGPU/Transforms/DecomposeScaledBlocked.cpp
- lib/Dialect/TritonGPU/Transforms/OptimizeThreadLocality.cpp
- lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
- lib/Dialect/TritonGPU/Transforms/Utility.cpp
- lib/Dialect/TritonGPU/Transforms/WarpSpecialization/OptimizePartitionWarps.cpp
- lib/Dialect/TritonNvidiaGPU/Transforms/OptimizeDescriptorEncoding.cpp
- lib/Dialect/TritonNvidiaGPU/Transforms/OptimizeTMemLayouts.cpp
- lib/Dialect/TritonNvidiaGPU/Transforms/PlanCTA.cpp
- lib/Dialect/TritonNvidiaGPU/Transforms/PromoteLHSToTMem.cpp
- python/src/gluon_ir.cc
- python/src/ir.cc
- third_party/amd/lib/TritonAMDGPUTransforms/CoalesceAsyncCopy.cpp
- third_party/amd/lib/TritonAMDGPUTransforms/OptimizeEpilogue.cpp
Credit to Jeff for pointing out these exist.
> [NFC] Use RankedTensorType's clone and cloneWithEncoding member functions

- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/WGMMA.cpp
The previous code sequence was hitting a bug in ptxas that caused Emiting this new code sequence should be cheaper and saves us from hitting the ptxas bug.
> [release/3.4] "[BACKEND] Workaround for ptxas bug in matrix descriptor arithmetic (#7197)"

- python/triton/tools/tensor_descriptor.py
- python/triton_kernels/triton_kernels/matmul_ogs.py
- python/triton_kernels/triton_kernels/matmul_ogs_details/_matmul_ogs.py
- python/triton_kernels/triton_kernels/matmul_ogs_details/_p_matmul_ogs.py
We are from NVIDIA and have been testing the moe kernels internally. We have seen some strange illegal memory access issue on release/3.4.x, but it's gone on main. After bisection we see this https://github.com/triton-lang/triton/pull/7182 fixes the issue. We think it's important to get this one in release branch so that we can make good use of 3.4 release once it's out.
> [release/3.4] Cherry-pick #7182

- python/tutorials/gluon/01-attention-forward.py
* Implement a turnstile over `gl.exp2` to control access to MFU for D64 to reduce contention between both softmax partitions
* For D64, use FADD2 to compute the row_sum by keeping 2 separate sums
* This triggers spilling in the inner loop for no apparent reason, but subtiling by 4 appears to generate a spilling pattern that tiles the L1 cache, reducing the performance impact
* Switch to FFMA2 for `qk` scale and row_max subtract 
Altogether, D64 is 100-120 TFLOPS faster across the board. fp16 D128 is about 50 TFLOPS faster, and causal D128 fp8 is up to 200 TFLOPS faster
From here, there is line-of-sight to cuDNN-level performance at least for non-causal D64 fp16 and both causal and non-causal D128 fp8. Causal masking for fp16 appears to have a large cost
```
Attention Z=4 H=32 D=64 …
```
> [Gluon][Tutorial] More attention optimizations

- lib/Dialect/TritonGPU/Transforms/Pipeliner/AssignLatencies.cpp
- test/TritonGPU/pipeline-assign-latencies.mlir
This allows user to have more control on what gets pipelined
> [PIPELINER] Make per loop num_stage annotation affect all loads

- lib/Dialect/TritonGPU/Transforms/WarpSpecialization/LoadMMASpecialization.cpp
- test/TritonGPU/load-mma-specialization.mlir
> [Warp Specialization] Tigthen user crit section with acc is not multibuffered

- python/test/unit/language/test_core.py
Cherry-Pick of https://github.com/triton-lang/triton/pull/7477 to fix integration tests
> [Cherry-Pick][TEST] Consolidate input generation for reduce tests 

- lib/Dialect/TritonGPU/Transforms/Pipeliner/SoftwarePipeliner.cpp
- python/src/ir.cc
- python/src/ir.h
- python/triton/compiler/code_generator.py
- python/triton/language/__init__.py
- python/triton/language/core.py
- python/tutorials/09-persistent-matmul.py
- test/Hopper/WarpSpecialization/ws_code_partition.mlir
- third_party/nvidia/backend/compiler.py
- third_party/nvidia/hopper/include/Transforms/Passes.td
- third_party/nvidia/hopper/lib/Transforms/CMakeLists.txt
- third_party/nvidia/hopper/lib/Transforms/WarpSpecialization.cpp
- third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/TaskIdPropagation.cpp
- third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/TaskIdPropagation.h
- third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/WSCodePartition.cpp
- third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/WSDataPartition.cpp
- third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/WSLowerMem.cpp
- third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/WSLowerToken.cpp
- third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/WSTaskIdPropagate.cpp
- third_party/nvidia/triton_nvidia.cc
Including:
- Update pipeline to get GEMM/FA working (#7136)
- Use required layout for buffers (#7284)
- Add back support of async_task
Verified GEMM + WarpSpec and tma_ws TritonBench FA
> Pick WarpSpec PRs and fixes to 3.4 release

- python/triton/tools/tensor_descriptor.py
A dependency on torch was added by mistake.
> [FRONTEND] Remove dependency on torch

- python/triton/experimental/gluon/language/_core.py
- python/tutorials/gluon/01-attention-forward.py
<git-pr-chain>
[Gluon] Add constexpr_function and static_range
These are used in the attention tutorial, but ideally everything should
come from the `gluon.language` module.
1. 👉 #7531 👈 **YOU ARE HERE**
1. #7534
1. #7535
1. #7536
> [Gluon] Add constexpr_function and static_range

- python/triton/experimental/gluon/language/_layouts.py
- python/triton/experimental/gluon/language/nvidia/blackwell/__init__.py
- python/tutorials/gluon/01-attention-forward.py
<git-pr-chain>
[Gluon] Move get_tmem_32x32b_reg_layout into blackwell API
1. #7534
1. 👉 #7535 👈 **YOU ARE HERE**
1. #7536
> [Gluon] Move get_tmem_32x32b_reg_layout into blackwell API

- python/triton_kernels/bench/bench_mlp.py
- python/triton_kernels/triton_kernels/matmul_ogs.py
Fix minor syntax issues on AMD side.
> [Bench][AMD]Fix Syntax In MoE Kernel

- lib/Dialect/TritonGPU/Transforms/HoistTMEMAlloc.cpp
- test/TritonGPU/hoist-tmem-alloc.mlir
This reverts commit 96e91d49f1fa0760594ea65699920dcfa04ed206.
> Revert "[BACKEND] Hoist tmem alloc outside of if (#7568)"

- include/triton/Dialect/TritonGPU/Transforms/Passes.td
- lib/Dialect/TritonGPU/Transforms/HoistTMEMAlloc.cpp
- lib/Dialect/TritonGPU/Transforms/Pipeliner/LowerLoops.cpp
- python/src/passes.cc
- test/TritonGPU/hoist-tmem-alloc.mlir
- test/TritonGPU/pipeline-lower-loop.mlir
- third_party/nvidia/backend/compiler.py
Change the flow to only apply the hoisting out of if after pipelining and warp specialization as this transformation may block muli-buffering.
> [BACKEND] Recommit tmem alloc hoisting out of if

- python/test/unit/language/test_tensor_descriptor.py
> [Testing] Restore tma gather scatter fallback tests

- python/triton_kernels/bench/bench_mlp.py
Weight used by `matmul_og` must be in column-major order on for hopper and earlier architectures with the fp8 type
> [KERNELS] Fix benchmarking `fp8` on hopper

- python/test/unit/language/test_warp_specialization.py
- third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/WSLowerToken.cpp
> [Hopper][Warp Spec] Enable persistent matmul test

- python/triton/experimental/gluon/language/_core.py
- python/triton/experimental/gluon/language/_semantic.py
- python/tutorials/gluon/01-attention-forward.py
> [Gluon][Tutorial] Use autolayout in a few places

- python/tutorials/09-persistent-matmul.py
- third_party/nvidia/include/cublas_instance.h
- third_party/nvidia/triton_nvidia.cc
Useful for test performance of a GEMM implementation.
> [NVIDIA] Expose `cublas.gemm`

- python/tutorials/06-fused-attention.py
Hopper WS doesn't support data partitioning with on-host TMA. Also subtiling causes issues with our data partitioning. We can try explicit data partitioning in the kernel.
> [WS][Hopper] Enable Warpspec for FA with non-causal and on-device TMA

- python/triton_kernels/tests/test_specialize.py
- python/triton_kernels/triton_kernels/numerics_details/mxfp.py
> [TEST] Do not pass tl.constexpr as an argument to a kernel and fix leaking hook

- python/test/conftest.py
- python/triton/_internal_testing.py
- python/triton_kernels/tests/conftest.py
- python/triton_kernels/tests/test_matmul.py
- python/triton_kernels/tests/test_specialize.py
> [kernels][tests] Use fresh_knobs when touching triton.knobs

- .github/workflows/wheels.yml
I believe we are ready to go live with 3.4.0 release
> [Release Only] Add Upload wheels to PyPI for release 3.4.x promotion

- lib/Dialect/TritonNvidiaGPU/Transforms/TensorMemoryAllocation.cpp
- test/TritonNvidiaGPU/test_tensor_memory_allocation.mlir
> [Blackwell] Handle control flow in TMEM allocation

- lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp
> [Dialect] Fix verifier for tmem scales

- include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td
- lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp
- python/src/gluon_ir.cc
- python/test/gluon/test_core.py
- python/test/gluon/test_frontend.py
- python/triton/experimental/gluon/language/nvidia/hopper/__init__.py
- test/Conversion/tritongpu_to_llvm_hopper.mlir
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM.cpp
> [Hopper] Verify WarpGroupDotWaitOp has at least 1 dep

- .github/CODEOWNERS
Should make it easier for me to discover gluon changes.
> [DEV] Add gluon section in CODEOWNERS

- .github/CODEOWNERS
Following https://github.com/triton-lang/triton/pull/7744
> [CODEOWNERS] Linear Layouts

- Makefile
- python/test/unit/language/test_frontend.py
- python/test/unit/language/test_tuple.py
- python/triton/_utils.py
- python/triton/compiler/code_generator.py
- python/triton/experimental/gluon/__init__.py
- python/triton/experimental/gluon/language/__init__.py
- python/triton/language/core.py
- python/tutorials/gluon/01-attention-forward.py
We've realised that mutations expose some weird semantics issues in the language, so at least for now we are disabling all mutations.
> [BC-break][Frontend] Disallow mutations

- .github/CODEOWNERS
Adding automatic reviewers for Proton backend from discussion with @Jokeren
> [PROTON] Update Proton Backend CODEOWNERS

- python/test/unit/language/test_core.py
- third_party/amd/backend/compiler.py
- third_party/nvidia/backend/compiler.py
Fixes https://github.com/triton-lang/triton/issues/7811
> [FRONTEND] Better error for num_cta > 1 on sm < 90

- python/triton/compiler/compiler.py
> Do not handle str signature in ASTSource

- python/triton/compiler/compiler.py
Currently the attention tutorial is failing on gb200. This happens because we only check for too many threads on the first `_init_modules` call. This changes it so that when we raise `OutOfResources` we also set `self._run` to a function that will raise the error. This means we will still raise the error, even if the module has already been loaded.
> [Runtime] Fix out of threads error to raise on every call

- python/triton/__init__.py
<git-pr-chain>
[Frontend] Make triton.next_power_of_2 a constexpr_function
This allows it to be called from kernels with constexpr inputs or from
outside kernels.
1. 👉 #7863 👈 **YOU ARE HERE**
1. #7864
1. #7865
> [Frontend] Make triton.next_power_of_2 a constexpr_function

- include/triton/Dialect/TritonGPU/IR/Dialect.h
- include/triton/Tools/LinearLayout.h
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- lib/Tools/LinearLayout.cpp
- test/Conversion/tritongpu_to_llvm.mlir
- test/Conversion/tritongpu_to_llvm_blackwell.mlir
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TensorMemoryToLLVM.cpp
Reland https://github.com/triton-lang/triton/pull/7831
This new lowering supports all the instructions and loads/stores from/to
arbitrary layouts. It also makes supporting all the available
instructions trivial.
> [RELAND][BACKEND] Implement generic lowering for tcgen05.ld/st

- include/triton/Dialect/Triton/IR/Utility.h
- lib/Dialect/Triton/IR/OpInterfaces.cpp
- lib/Dialect/Triton/IR/Ops.cpp
- lib/Dialect/Triton/Transforms/ArithTypeConversion.cpp
- lib/Dialect/Triton/Transforms/Combine.cpp
- lib/Dialect/Triton/Transforms/LoopAwareCSE.cpp
- lib/Dialect/Triton/Transforms/LoopInvariantCodeMotion.cpp
- lib/Dialect/Triton/Transforms/RewriteTensorDescriptorToPointer.cpp
- lib/Dialect/Triton/Transforms/RewriteTensorPointer.cpp
> [BUILD] Fix warnings to build triton with clang

- .github/workflows/integration-tests-amd.yml
- include/triton/Analysis/Utility.h
- include/triton/Conversion/TritonGPUToLLVM/TargetInfoBase.h
- lib/Analysis/Utility.cpp
- lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
- python/test/regression/test_functional_regressions.py
- test/Conversion/amd/mfma-shortcut.mlir
- test/Conversion/tritongpu_to_ptx_mmav3.mlir
- third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM.cpp
- third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp
- third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.h
- third_party/amd/lib/TritonAMDGPUToLLVM/Utility.cpp
- third_party/amd/lib/TritonAMDGPUToLLVM/Utility.h
- third_party/amd/python/test/test_convert_op_permlane_swap.py
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.cpp
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.h
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/Utility.cpp
Reland https://github.com/triton-lang/triton/pull/7809,
https://github.com/triton-lang/triton/pull/7825,
https://github.com/triton-lang/triton/pull/7861
Add a workaround for ptxas bug and add a regression test
> Reland "byte permutes in intra-warp layout conversion" 

- Makefile
- pyproject.toml
- python/triton/experimental/gluon/language/__init__.py
- python/triton/experimental/gluon/language/_core.py
- python/triton/experimental/gluon/language/_layouts.py
- python/triton/experimental/gluon/language/_math.py
- python/triton/experimental/gluon/language/_standard.py
> [gluon] Remove programmatic imports for the sake of mypy

- third_party/amd/backend/driver.py
Search for libamdhip64 from HIP_PATH env var, hipconfig --path output,
and ROCM_PATH before looking in system-wide ldconfig or /opt/rocm.
The system-wide ROCm path isn't guaranteed to be where the ROCm
install we're building against is located, so follow typical ROCm
lib behavior and look under env paths first.
This is especially important for non-FHS distros like NixOS
where /opt/rocm never exists, but may be useful in more
typical distros if multiple ROCm installs are present
to ensure the right libamdhip64.so is picked up.
---
[hipconfig --path is documented as a recommended approach in the porting guide.](https://github.com/ROCm/hip/blob/cda3fa769bc638e92e571eb6f7fd02e891232588/docs/how-to/hip_porting_guide.rst#compilation)
Env var search seems simpler and matches what ROCm packages …
> [AMD] Search HIP_PATH, hipconfig, and ROCM_PATH for libamdhip64

- python/src/gluon_ir.cc
- python/triton/experimental/gluon/language/nvidia/blackwell/__init__.py
> [GLUON] Remove dead code added by accdident

- python/src/gluon_ir.cc
- python/test/gluon/test_frontend.py
- python/test/gluon/test_lowerings.py
- python/triton/experimental/gluon/language/__init__.py
- python/triton/experimental/gluon/language/_core.py
- python/triton/experimental/gluon/language/_semantic.py
Expose histogram op in gluon. This will be convenient to test more complex layouts.
> [GLUON] Add histogram support

- .github/workflows/build-macos.yml
We were picking the wrong clang after image upgrade.
Solution mostly from chatgpt
> [BUILD] Fix mac build CI

- .github/workflows/llvm-build.yml
Note: no need to merge it
Initial discussion: https://github.com/triton-lang/triton/pull/8051
> Fix LLVM bc773632355b build for Windows

- lib/Dialect/TritonGPU/Transforms/WarpSpecialization/RewritePartitionDependencies.cpp
- test/TritonGPU/rewrite-partition-dependencies.mlir
We use splat/unsplat as we currently don't support allocation of scalars.
> [WS] Support scalar ops across partition

- third_party/proton/common/include/TraceDataIO/TraceWriter.h
- third_party/proton/common/lib/TraceDataIO/TraceWriter.cpp
- third_party/proton/csrc/lib/Data/TraceData.cpp
- third_party/proton/test/test_instrumentation.py
> [PROTON] Add kernel call stack to intra kernel events

- docs/conf.py
- python/triton/__init__.py
- setup.py
Related to https://github.com/triton-lang/triton/issues/8012
> Advance version 3.4.0->3.5.0

- include/triton/Dialect/Triton/IR/TritonOpInterfaces.td
- include/triton/Dialect/TritonGPU/IR/LinearLayoutConversions.h
- lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp
- lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
- lib/Dialect/TritonGPU/Transforms/DecomposeScaledBlocked.cpp
- python/test/unit/language/test_core.py
- python/test/unit/language/test_matmul.py
- test/Conversion/tritongpu_to_llvm_sm120.mlir
- test/TritonGPU/accelerate-matmul.mlir
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM.cpp
- third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/MMAv2.cpp
- unittest/Dialect/TritonGPU/LinearLayoutConversionsTest.cpp
Add a fix for the crash happening on BW. 
Still doing some perf test
> Reapply "[NVIDIA] Add native MXFP FP8 scaled_dot for SM120 (#7918)" (#8029)

- python/test/unit/test_knobs.py
- python/triton/knobs.py
- third_party/proton/csrc/Proton.cpp
- third_party/proton/csrc/include/Utility/Env.h
- third_party/proton/csrc/lib/Profiler/Cupti/CuptiProfiler.cpp
- third_party/proton/csrc/lib/Profiler/RocTracer/RoctracerProfiler.cpp
- third_party/proton/proton/profile.py
- third_party/proton/test/conftest.py
- third_party/proton/test/test_profile.py
In case we want a more succinct call path
> [PROTON] Use the `TRITON_NVTX_ENABLED` env var to optionally turn off nvtx

- lib/Dialect/TritonGPU/Transforms/ReorderInstructions.cpp
- test/TritonGPU/reorder-instructions.mlir
This may increase smem pressure significantly
> [BACKEND] Block hoisting of local_alloc with scalar source

- python/triton_kernels/triton_kernels/roofline.py
> [BENCH] Fix roofline plotting

- include/triton/Dialect/TritonGPU/IR/Dialect.h
- lib/Dialect/Triton/IR/Traits.cpp
- lib/Dialect/TritonGPU/IR/Dialect.cpp
- lib/Dialect/TritonGPU/IR/Ops.cpp
- lib/Dialect/TritonNvidiaGPU/IR/Dialect.cpp
- lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp
- test/TritonGPU/ops.mlir
> [LAYOUTS] Have MemDesc{Trans,Reshape} accept equivalent layouts

- python/triton_kernels/triton_kernels/matmul_ogs.py
- python/triton_kernels/triton_kernels/matmul_ogs_details/_common.py
- python/triton_kernels/triton_kernels/matmul_ogs_details/_matmul_ogs.py
- python/triton_kernels/triton_kernels/matmul_ogs_details/_p_matmul_ogs.py
Updated `matmul_ogs` to optionally fuse all gather / scatter.
python reference impl is added. Test cases will be kept in a separate repo due to some dependencies
> [triton_kernels] fused matmul_ogs + comms

- python/triton/experimental/gluon/language/amd/gfx1250/__init__.py
- third_party/amd/python/test/test_gluon_gfx1250.py
This PR added tests for MXFP GEMM Gluon Kernel for GFX1250.
> [AMD]Add Tests for MXFP GEMM Gluon Kernel for GFX1250

- python/test/gluon/test_frontend.py
- python/triton/experimental/gluon/language/_semantic.py
In this case we reduce down to a scalar. We can just reshape to a 1d tensor.
> [Gluon] Add support for reduce with no axis
