include/triton/Dialect/TritonGPU/IR/Dialect.h, lib/Dialect/TritonGPU/IR/Dialect.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandHelper.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandHelper.h, third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/MMAv2.cpp
This commit changes terminology for matrices that are contiguous along K dimension in memory.
Previously term kMajor is used for such matrices. Since major-minor terminology can be ambiguous
this commit switches to using term kContig for K contiguous matrices, which is hopefully more clear.
=> [NFC] Change term kMajor to kContig

include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td, lib/Dialect/TritonGPU/Transforms/Pipeliner/TMAStoresPipeline.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/TMALowering.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp
All other ops are named with the *Op suffix. Fix the name of this op to align with the rest.
=> [DIALECT] s/TMAStoreWait/TMAStoreWaitOp/g (NFC)

lib/Dialect/TritonGPU/IR/Dialect.cpp, unittest/Dialect/TritonGPU/DialectTest.cpp
This PR implements GetThreadsPerWarpForOperand function for WMMA and MFMA layouts.
=> [AMD] GetThreadsPerWarpForOperand interface

python/test/unit/language/test_core.py, third_party/amd/backend/compiler.py, third_party/amd/backend/driver.py
This change is a follow up to https://github.com/triton-lang/triton/pull/5381 and is intended to add grid synchronization similar to what cooperative groups do for AMD.
This PR adds support for Cooperative Grid Launch for AMD using the HIP API `hipModuleLaunchCooperativeKernel`:
https://rocm.docs.amd.com/projects/HIPIFY/en/latest/tables/CUDA_Driver_API_functions_supported_by_HIP.html
=> [AMD][Launcher] Cooperative Grid Launch for AMD (ie launch_cooperative_grid)

third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp, third_party/amd/lib/TritonAMDGPUTransforms/ConvertToBufferOps.cpp
This is a minor change, when implementing PR #5549 I used: ```rewriter.notifyMatchFailure``` in place of ```return failure();``` as per suggestions to leverage MLIR infra for errors.
We should probably be consistent throughout the file and use the MLIR infra for the other buffer ops.
I don't think this should impact anything and doesn't require any added tests
================================================================================
=> [AMD][Buffer Ops] Leverage MLIR infra for errors in more places

include/triton/Dialect/TritonGPU/IR/Dialect.h
https://github.com/triton-lang/triton/pull/5542/files introduced a dependency on an unordered_map without requiring the unordered_map include path.
This works on some systems currently if other headers include unordered map, but fails on others.
=> Add missing include header

third_party/proton/proton/viewer.py
The `strip` method removes characters that match the input argument, but it does not remove substrings that match the full input. For example, previously, `"num_samples (inc)".strip("inc")` would result in `um_samples` because the character `n` is part of the input argument. Instead of using `strip`, the `replace` method can be used. However, in this case, we can simply output the original metric name (i.e., "num_samples (inc)") since it’s more useful to know whether the metric is inclusive or exclusive.
=> [PROTON] Correct misuse of `strip`

third_party/proton/csrc/lib/Profiler/Cupti/CuptiPCSampling.cpp, third_party/proton/csrc/lib/Profiler/Cupti/CuptiProfiler.cpp, third_party/proton/proton/viewer.py, third_party/proton/test/examples/frame.json, third_party/proton/test/test_viewer.py, third_party/proton/tutorials/matmul.py
This way users can directly open the file using IDEs like vscode and jump to the corresponding lines, by holding the `ctrl` key and click the line on the terminal.
Also, this PR emits an error instead of using workarounds for CUPTI compatibility problems and adds more instructions for using PC sampling in the tutorial.
=> [PROTON] Change the output format of pc sampling lines

python/test/unit/language/test_compile_errors.py, python/triton/compiler/compiler.py
The `filter_traceback` call was commented out during the tuple PR. This just restores it and adds a check in the relevant tests.
=> [FRONTEND] Restore error traceback filtering

include/triton/Conversion/TritonGPUToLLVM/Utility.h, lib/Conversion/TritonGPUToLLVM/Utility.cpp, python/test/unit/language/test_core.py, test/Conversion/tma_to_llvm.mlir, test/Conversion/tritongpu_to_llvm.mlir, test/Conversion/tritongpu_to_llvm_blackwell.mlir, test/Conversion/tritongpu_to_llvm_hopper.mlir, test/Conversion/tritonnvidiagpu_to_llvm.mlir, third_party/nvidia/lib/NVGPUToLLVM/NVGPUToLLVMPass.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ElementwiseOpToLLVM.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/SPMDOpToLLVM.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TMAToLLVM.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/Utility.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/Utility.h
<git-pr-chain>
[NVIDIA] Prefer nvvm intrinsics over custom PTX
For the most part, I expect this will just be a minor cleanup. It is
vaguely possible that this might enable some better codegen.
1. 👉 #5733 👈 **YOU ARE HERE**
=> [NVIDIA] Prefer nvvm intrinsics over custom PTX

python/setup.py, third_party/proton/csrc/include/Driver/Dispatch.h
It will be more consistent since the CUPTI header and library can use the same version.
For roctracer, we don't package the library with triton, so we need to fall back to the system library.
=> [PROTON] Prefer the default library path when loading profiler backends

python/test/unit/language/test_standard.py, python/triton/language/standard.py
This doesn't break functional backward compatiblity as the new semantic is a subset of the what was allowed before but it would break performance backward compatiblity.
The makes it less error prone.
=> [BC Breaking] Make tl.ravel keep element orders by default

test/Conversion/tma_to_llvm.mlir, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp
Follow-up to #5733 which somehow the passed CI and auto-merged, even with this bug. TMA should be using `bulk.commit.group` rather than `commit.group`.
=> [NVIDIA] Use correct commit type for TMA

include/triton/Dialect/TritonGPU/Transforms/Utility.h, lib/Dialect/TritonGPU/Transforms/Coalesce.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp, lib/Dialect/TritonGPU/Transforms/Utility.cpp, test/TritonGPU/coalesce.mlir
Reverts triton-lang/triton#5707
This causes some functional changes that I need to investigate
=> Revert "[Coalesce] Fix the default order to be row major "

lib/Dialect/Triton/Transforms/Combine.cpp, test/Triton/combine.mlir
When reducing a 1D tensor the order of elements doesn't matter. This allows us to use a more relaxed version of reshape.
=> Optimize reduce(reshape_1D)

lib/Analysis/Allocation.cpp, test/Conversion/tritongpu_to_llvm.mlir
Without this, we can get into a situation when the vector loads/stores would exceed the size of the scratch buffer (and trigger an assertion).
Fixes #5745.
=> [BACKEND] Limit vector size to scratch size for convert_layout

include/triton/Dialect/Triton/IR/Traits.h, include/triton/Dialect/Triton/IR/TritonInterfaces.td, include/triton/Dialect/Triton/IR/TritonOps.td, lib/Dialect/Triton/IR/Ops.cpp, lib/Dialect/Triton/IR/Traits.cpp
=> [LAYOUTS] Create a trait that implements Layout equality by comparing the LLs

README.md, python/src/ir.cc, python/test/unit/test_perf_warning.py, third_party/nvidia/backend/compiler.py
This PR enhances the current implementation for emitting diagnostic remarks by introducing a unified handler in `ir.cc`. This handler manages diagnostic information more effectively and disables the emission of IRs unless explicitly requested by the user. The `MLIR_ENABLE_DIAGNOSTICS` environment variable now controls all diagnostic emission settings, accepting one or more values from `{warnings, remarks, stacktraces, operations}`, separated by commas. Detailed usage instructions are available in the README.
Previously, a new default LLVM `SourceManager` was configured in `nvidia/backend/compiler.py` to support remarks, applied in both `make_ttgir` and `make_llir`. However, a custom handler already existed in `ir.cc`, and a more robust design should extend this handler rather than create …
=> [Frontend][Diagnostics] Improve emitting diagnostic information

lib/Dialect/Triton/IR/Ops.cpp, lib/Dialect/TritonGPU/IR/Ops.cpp, test/Triton/combine.mlir, test/TritonGPU/canonicalize.mlir, test/TritonGPU/optimize-locality.mlir
recommit https://github.com/triton-lang/triton/pull/5671
Don't fold allow_reorder reshape ops. This preserves the reshape and importantly the allow_reorder bit so that OptimizeThreadLocality knows it may chose a layout for the reduction in the case when the src and dst shape of the reshape is the same.
Change CanonicalizeConvertFromReshape to run on efficient_layout. This allows removal of the convert layout op between the reshape and reduction.
- …
=> Improve thread locality for reduction ops (#5671)

third_party/proton/dialect/include/Dialect/Proton/IR/Dialect.h, third_party/proton/dialect/include/Dialect/Proton/IR/ProtonOps.td, third_party/proton/dialect/lib/Dialect/Proton/IR/Ops.cpp
This PR is a follow-up of #5677 for proton compiler mid-end support, focusing on op definition. Specifically, we 1. added the tablegen definitions of the proton mid-end operators, 2.  removed attributes of the front-end `RecordOp` (make it a true marker), 3. cleaned up the dialect's macro.
=> [Proton][Dialect] Middle-end Proton operator definitions

lib/Dialect/TritonGPU/IR/Dialect.cpp, lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp, lib/Dialect/TritonGPU/Transforms/Utility.cpp, test/TritonGPU/combine.mlir
This is a re-land of #5610 with a fix to DotOperandEncodingAttr to resolve a crash exposed in internal tests.
At the same time, this slightly alters the implementation of the algorithm to ensure that layouts don't get pushed back out of conditionals by the forward propagation pass. Originally, the goal of hoisting across conditionals was to ensure that cvts in fused inner loops are placed inside the prologue before pipelining peels the prologue and introduces a chain of dependencies.
My guess is that @lezcano's changes to strengthen layout propagation enabled the forward propagation pass to push the conversion back out of the prologue even after pipelining (which is good), but I explicitly disabled hoisting into chains of conditionals, so these didn't balance out. This PR alters the …
=>  Reapply "[Layouts] Propagate layouts into conditionals (#5610)"

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
If wgmma is using operands in registers, it can't be pipelined (overlapping with mma from previous iteration), as we would end up re-using the same registers while mma is still in-flight. For such cases we don't need to increase number of buffers used by operands of such mma.
This change picks a low hanging fruit by not increasing the number of buffers of the register-based operand. We should go a step further and not increase numBuffers for any operand of such mma.
=> [PIPELINE] Limit number of buffers for register operands

.github/workflows/integration-tests.yml, .github/workflows/integration-tests.yml.in, Makefile, README.md, python/requirements.txt, python/test-requirements.txt, third_party/proton/test/instrument.py, third_party/proton/test/test_cmd.py
Now `make test` runs the exact commands used in CI, so there should be no spurious local failures due to the specific `pytest` command used.
=> [DEV] Unify Makefile and cuda CI commands

include/triton/Dialect/Triton/IR/TritonOps.td, lib/Dialect/Triton/IR/CMakeLists.txt, lib/Dialect/Triton/IR/Canonicalize.td, lib/Dialect/Triton/IR/Ops.cpp, test/Triton/combine.mlir
The `getAllowReorder` check was added in #2676, but the canonicalizations are value-preserving so this is not required.
Specifically:
- `reshape(splat) -> splat`, order is irrelevant for splat
- `reshape(reshape) -> reshape`, reshape essentially treats the input as 1d, so the input reshape has no effect.
=> [BACKEND] Canonicalize ReshapeOp even if not allowing reorder

test/TritonGPU/promote-lhs-to-tmem.mlir, test/TritonNvidiaGPU/test_promotion_to_tensor_memory.mlir
In our case, this allows us to successfully run `lit` tests on Windows.
=> Use `env` builtin implementation from LLVM's lit utility for platform independence

python/triton/language/standard.py
The interpreter doesn't support the `_generator` special argument at the moment.
=> [Triton] Change `xor_sum` to use `@jit` (NFC)

third_party/nvidia/backend/compiler.py
This was a temporary workaround during blackwell development, llvm now understands sm_100a and ptx86.
=> [DRIVER] Pass correct SM and PTX versions to llvm

lib/Conversion/TritonGPUToLLVM/Utility.cpp
This PR fixes a typo in the Windows implementation of `__builtin_clz` that was introduced in #5621.
According to [this in-code comment](https://github.com/triton-lang/triton/blob/b3dcc32f387d1d54ccd6cbbbc087296c0539e703/lib/Conversion/TritonGPUToLLVM/Utility.cpp#L12) these Windows implementations should have been copied from [this gist snippet](https://gist.github.com/pps83/3210a2f980fd02bb2ba2e5a1fc4a2ef0). In the snippet however the `clz` implementation additionally [XORs the result of `_BitScanReverse`](https://gist.github.com/pps83/3210a2f980fd02bb2ba2e5a1fc4a2ef0#file-ctz_clz-cpp-L51-L53) in order to convert the result from the <i>most significant bit</i> produced by `_BitScanReverse` to the expected <i>number of leading zeros</i>. I believe the implementation was copied to the …
=> Fix `__builtin_clz` implementation on Windows

python/triton/tools/compile.py
The bug was causing the generated code to have CUBIN array that is twice as large as the actual byte count.
=> [TOOLS] Fixed bug in AOT compiler

third_party/proton/CMakeLists.txt
`error: unknown warning group '-Wreserved-macro-identifier'`, this flag was not defined in `clang-10`
=> [PROTON] Skip warnings caused by legacy clang compilers

include/triton/Dialect/TritonGPU/Transforms/Utility.h, lib/Dialect/TritonGPU/Transforms/Utility.cpp, python/test/unit/language/test_compile_errors.py, test/Conversion/amd/tritongpu_to_llvm.mlir, test/TritonGPU/amd/accelerate-amd-matmul-fma.mlir, test/TritonGPU/amd/accelerate-amd-matmul-wmma-gen1.mlir, third_party/amd/backend/compiler.py, third_party/amd/include/TritonAMDGPUToLLVM/TargetUtils.h, third_party/amd/lib/TritonAMDGPUToLLVM/CMakeLists.txt, third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/FMA.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/TargetUtils.cpp, third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp
This PR:
- Makes AccelerateAMDMatmul pass to emit FMA i8xi8->i32 and fp16xfp16->fp32 cases
- Extends AMD FMA Dot code generation with new v_dot instructions for fp16xfp16 and int8 dtypes
~This PR is a part of PR series. Final goal is to improve efficiency of small dot operations and bypass as much shared memory accesses as possible.~
Rough list of PRs:
=> [AMD] Emit AMD specific intrinsics for dot 

Makefile, python/test/unit/test_debug.py
I had used `.ONESHELL` to allow `cd` to effect the other commands, but it seems this also prevents the error status from propagating from anything but the last command in a rule.
e.g. see https://github.com/triton-lang/triton/pull/5673#issuecomment-2626954515
=> [DEV] Don't use .ONESHELL in Makefile

lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp, test/TritonGPU/combine.mlir
This allows remat to reuse existing values even if they're not dominated by the remat'd value, if we know it's going to be a no-op conversion and its users are dominated by the remat'd value. However, this is quite sketchy and was not implemented correctly.
Disable it for now, although it causes some layouts to not be removed.
=> [Layouts] Remove sketchy remat condition

third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp
Enables the fp32 -> bf16 packed conversions for gfx950
=> [AMD] Add GFX950 fp32 to bf16 Conversion Ops

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp, test/TritonGPU/matmul-loop-pipeline.mlir
The scheduler doesn't pipeline scalar loads but if loads end up in different stages for various other reasons, the pipeline tries to pipeline them and crashes. The pipeliner should be look at the first use of the load based on stages, not just if any use is in a different stage.
=> [Pipeliner] Fix condition for pipelining loads

python/test/unit/language/test_core.py, python/triton/language/core.py, python/triton/language/standard.py, python/triton/runtime/interpreter.py
`tl.sum` can have surprising behaviour when invoked on lower-precision floating point or low bitwidth integer types, such as `tl.sum(i1)` actually computing xor reduce.
To reduce this footgun, this PR adds a `dtype` argument to `tl.sum` (and `tl.reduce`) which optionally casts the input to that dtype before computing the operation. For `tl.sum`, the default dtype is set to `tl.int32` for integers smaller than that and `tl.float32` for floats smaller than that.
=> [BC Breaking] Add output dtype to `tl.sum` with default

python/tutorials/09-persistent-matmul.py
Corrected descriptor kernel to optimally epilogue subtile.
To get optimal subtilling in a persistent kernel, the tile index needs to be recalculated in the epilogue to enable pipelining. This PR adds this in the descriptor kernel, so that epilogue subtiling is chosen more often after autotuning.
=> Tutorial 09 Descriptor Kernel

third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp
While here, also cleaned up some `mlir::`
namespace prefixes.
=> [AMD] NFC: Drop unused constructors in elementwise patterns

lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp, test/TritonGPU/combine.mlir
Hoisting layout conversions into ifs relies on the assumption that the if infrequently executes, but this assumption only makes sense in a loop. A single top-level if in a kernel either executes or it doesn't, and if the hoist is incorrect, it can lead to a slowdown.
=> [LAYOUTS] Don't hoist into ifs outside of loops

lib/Dialect/Triton/IR/Ops.cpp, lib/Dialect/TritonGPU/IR/Ops.cpp, test/TritonGPU/canonicalize.mlir
The folder for TransOp was a bit too aggresive. Sometimes it would
change the representation of a layout for an equivalent one, and that's
not allowed in the current state of things. We move the optimisation we
had to a different canonicalizer.
=> [LAYOUTS] Fix TransOp::fold

python/test/unit/language/test_compile_errors.py
If we expect a warning, we need to use a fresh cache dir; otherwise, no warning will be thrown when the cache is hit.
Also take out interpreter related code from this file.
=> [TEST] Use a fresh triton cache dir for warning tests

python/tutorials/09-persistent-matmul.py
Currently the persistent matmul is 10% slower than non-persistent on blackwell, with this fix it's about 20% speedup vs non-persistent.
=> [TUTORIAL] Apply remat perf fix to non-TMA persistent matmul

include/triton/Dialect/Triton/IR/OpInterfaces.h, include/triton/Dialect/Triton/IR/Traits.h, include/triton/Dialect/Triton/IR/TritonInterfaces.td, include/triton/Dialect/Triton/IR/TritonOpInterfaces.td, include/triton/Dialect/Triton/IR/TritonOps.td, include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td, lib/Dialect/Triton/IR/OpInterfaces.cpp, lib/Dialect/Triton/IR/Ops.cpp, lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp, lib/Dialect/TritonGPU/Transforms/OptimizeAccumulatorInit.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/AssignLatencies.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp, lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/FenceInsertion.cpp, test/Triton/invalid.mlir, third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp, third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp
The Triton MLIR dialect presently has a `DotLike` trait which DotOps have.
The problem with this trait is the way it is currently implemented prevents `scaled_dot` from being verified properly (dimensions are not properly checked at the moment: "TODO: enable back with an interface to support scaled dot.").
This PR refactors the "DotLike" trait into an interface which implements a "verifyDims" function that checks if the dims for the A and B operands are compatible (e.g., something like MxK1 and K2xN; k1==k2; in the simple case).
The initial implementation of DotOpInterface is similar to the prior `DotLike` trait with the exception that it includes the `verifyDims` function which all DotOps must implement---this function just checks whether the dimensions of the A, B inputs match.
In the …
=> [mlir][dialect] Refactor DotLike trait into a DotOpInterface + Enable verification of scaled_dot

lib/Analysis/AxisInfo.cpp
UBSan detected that the shift is happening on an int32 variable, but the shift amount could be larger than what int32 supports.
I believe the change is trivial to require a test, but please advice accordingly if you think there is an appropriate way to capture this.
=> [ANALYSIS] Fixing overflow in AxisInfo.cpp.

third_party/amd/backend/compiler.py
Removes a duplicate definition of use_buffer_ops when loading the `AMDGCN_USE_BUFFER_OPS` environment variable, likely due to a merge conflict.
=> [AMD] Remove duplicate definition of use_buffer_ops

include/triton/Dialect/TritonNvidiaGPU/Transforms/TMAUtilities.h, lib/Dialect/Triton/IR/Ops.cpp, lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp, python/test/unit/cuda/test_experimental_tma.py, python/triton/language/core.py, python/triton/language/semantic.py, python/triton/runtime/jit.py
This adds support for 3, 4 and 5 dimensional tensor descriptors with tests that load and store work correctly. It was surprisingly easy as most of the code was already written generically, there were only a few changes needed to the TMA creation lowering, and a bug-fix for LL conversion of NVMMA encoding with >2 dims.
=> [TensorDescriptor] Support ndim > 2 loads and stores

third_party/amd/backend/compiler.py
We only want to run them if an active variant is requested.
=> [AMD] Avoid unneeded instruction schedule pass runs

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
There is a bug introduced in: [PIPELINE] Relax requirements for wgmma operand register pipelining (#5810)
I was missing mmav5 dot support. Thanks for @peterbell10 for catching that and for @masahi for proposing a fix.
=> [PIPELINE] Including mmav5 dot in shmem pipelining

lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
There are cases where transposing the dot op may cause performance problems. For example, if the accumulator is being used in something like:
```
%206 = ttg.convert_layout %205 : tensor<128x64xf16, #mma> -> tensor<128x64xf16, #ttg.dot_op<{opIdx = 0, parent = #mma, kWidth = 2}>> loc(#loc216)
```
transposing it makes the conversion expensive. This is likely to happen in attention kernels.
=> Disable dot transpose optimization due to perf regressions

lib/Dialect/TritonGPU/Transforms/Utility.cpp, test/TritonGPU/matmul-loop-pipeline.mlir
Lots of our code assumes that `scf.if` has a non-empty else region, but sometimes it can be empty, which typically happens due to one of the `scf.if` canonicalizers. Just make sure to create `scf.if` with non-empty regions.
This was split off from https://github.com/triton-lang/triton/pull/5726 since others were hitting the crash.
=> [Pipeliner] Fix crash in rewriting TMA descriptor updates

test/Conversion/amd/async_ops_to_llvm.mlir, test/Conversion/amd/buffer_load_store.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/BufferOpsEmitter.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/Utility.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/Utility.h
Enables cache control bits based on Triton's `cacheModifier` on gfx950. They are identical compared to `gfx942`.
=> [AMD][BACKEND] Enable cache ctrl bits for gfx950

python/tutorials/09-persistent-matmul.py, python/tutorials/10-block-scaled-matmul.py
Do not `exit` when generating tutorials, which causes the whole documentation pipeline exit.
=> [DOC] Fix generating docs for tutorials

lib/Dialect/TritonNvidiaGPU/Transforms/KeepAccInTMem.cpp, python/test/unit/language/test_matmul.py, test/TritonGPU/blackwell_acc_tmem.mlir
For cases where TMem is constant hoisting the allocation of the loop avoid having to store multiple times.
=> [Blackwell] Hoist constant TMem allocation out of the loop

test/Conversion/amd/fp_to_fp.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/Utility.cpp
Inline assembly can be a blocker for LLVM backend to optimize.
=> [AMD] Use LLVM ops for fp16<->fp32 casts

third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/MFMA.cpp
This PR refactored `DotOpMFMAConversionHelper` by extracting utility functions from `convertDot` to make it easier to be extended in https://github.com/triton-lang/triton/pull/5845.
=> [AMD] Refactor DotOpMFMAConversionHelper

.github/workflows/integration-tests.yml, .github/workflows/integration-tests.yml.in
The CI docker image has been moved from `rocmshared/pytorch` to `rocm/pytorch` so we need to adjust our workflow.
=> [AMD][CI] Switch to rocm hosted docker image

lib/Dialect/Triton/IR/Ops.cpp, lib/Dialect/Triton/Transforms/Combine.cpp, test/Triton/combine.mlir, test/Triton/invalid.mlir
This allows us to implement efficient batch matmul with TMAs. Note that this could be solved by allowing reshapes on shared descriptor and propagating layout but for simplicity we currently do it with a pattern match.
=> [BACKEND] Allow ranked reduced descriptor load

lib/Dialect/TritonGPU/IR/Dialect.cpp, unittest/Dialect/TritonGPU/DialectTest.cpp
For XPU backend, the logic of the common code is slightly changed and some Triton lit tests encounter the problem of an unimplemented function.
=> Implement `DotOperandEncodingAttr::getSizePerThread` with block layout parent

test/Conversion/amd/async_ops_to_llvm.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/Utility.cpp
Adjust mappings to better represent the expected caching behavior and improve the misleading parameter name. `.cg` loads should be different for all types of loads and not just `BufferLoads`.
Note that this function is currently only used by `BufferLoads` and `AsyncCopyGlobalToLocal`.
=> [AMD][BACKEND] Adjust cache modifier mappings

include/triton/Dialect/TritonGPU/IR/LinearLayoutConversions.h, lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp, test/Conversion/amd/ds_transpose.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/MemoryOpToLLVM.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/PatternTritonGPUOpToLLVM.h, third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.h, third_party/amd/lib/TritonAMDGPUToLLVM/TritonGPUToLLVM.cpp, unittest/Dialect/TritonGPU/LinearLayoutConversionsTest.cpp
This PR introduces initial support for using LDS transposed load intrinsics in Triton. It implements selection of ds_read_b64_tr_b16 instruction for mi350 architecture. These intrinsics are designed to handle tensors that are non-k contiguous in LDS, enabling efficient loading in a transposed manner. 
LDS transposed loading only works if:
1. The hardware supports transposed LDS load instructions.
2. The tensor we’re loading is contiguous along the non-K dimension in LDS.
How the compiler handles LDS transpose loads (like the intrinsics and LL we use) depends on two things:
1. The type of data we’re working with.
2. The type of MFMA instruction.
Currently, we only support transpose loads for 16-bit data on gfx950.
TODO: Add support for other data types (e.g., 8-bit types).
TODO : Support …
=> [AMD] MI350 support for ds_read_b64_tr_b16  instruction

third_party/proton/dialect/include/Dialect/ProtonGPU/IR/ProtonGPUOps.td, third_party/proton/dialect/lib/Dialect/ProtonGPU/IR/Ops.cpp
Decouple the `CircularRecordOp` into two ops: `ReadCounterOp` and `CircularStoreOp`. This allows us to schedule to write operations separately. Note that the `scopeId` is an attribute, which should have been assigned with a value. A `name->id` assignment pass will also happen before lowering `ProtonGPURecordOp`. For example:  
`protongpu.record %name` -> 
`protongpu.record %name` + `proton.init_scope{%name, %id}` -> 
`protongpu.read_counter{%id}` + `protongpu.circular_store{%id}` + `proton.init_scope{%name, %id}`
=> [PROTON-DEV] Decouple ProtonGPU RecordOp into two operations

third_party/amd/backend/compiler.py, third_party/amd/lib/TritonAMDGPUTransforms/CanonicalizePointers.cpp
This PR fixes an assert thrown in [DenseMap::copyFrom](https://github.com/llvm/llvm-project/blob/390b82dd4c485ec64cf8a6c52fb73e391792262e/llvm/include/llvm/ADT/DenseMap.h#L435) that looks like this:
```
... Assertion `getNumBuckets() == other.getNumBuckets()' failed.
```
The call to `copyFrom` is via `SmallDenseMap`s copy ctor which fires in our code in the default ctor of [`CanonicalizePointers::FatPointers::FatPtrAttrs`](https://github.com/triton-lang/triton/blob/083731a28defcf54c53f4a16836af3a277f2437e/third_party/amd/lib/TritonAMDGPUTransforms/CanonicalizePointers.cpp#L287) since `FatPtrAttrs` wraps a `llvm::SmallDenseMap<StringRef, Attribute> attributes`.
I have locally verified the fix resolves the issue using @jungpark-mlir reproducer but note, this is a non-deterministic bug. I …
=> [AMD] fix CanonicalizePointers FatPtrAttrs (SmallDenseMap -> DenseMap)

python/test/unit/language/test_core.py, python/triton/runtime/interpreter.py
If two tensors alias, the interpreter will clobber writes when it makes a CPU copy of its backing storage. Identifying this in general is quite difficult, but in most cases aliasing tensors share the same backing storage. If we set up our CPU-side storage to mirror the device, then we can avoid this particular bug in that case. This partially fixes #5791.
=> [INTERPRETER] Improve support for aliased tensors in interpreter

lib/Dialect/TritonGPU/Transforms/Pipeliner/TC05MMAPipeline.cpp
Previous approach for scheduling pre-existing `wait_barrier`s in mmav5 pipelining relies on checking which async ops are they waiting for, and scheduling them to the same stage. This however won't work, if we'll schedule wait to some random stage based on the stage it's operands are scheduled to.
=> [BW][PIPELINE] Skip waits when scheduling downward dependencies in mmav5 pipelining

include/triton/Analysis/Utility.h, lib/Analysis/Allocation.cpp, lib/Analysis/AxisInfo.cpp, lib/Analysis/Utility.cpp, lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandFMA.cpp, lib/Conversion/TritonGPUToLLVM/ScanOpToLLVM.cpp, lib/Dialect/TritonGPU/IR/Dialect.cpp, test/TritonGPU/amd/optimize-lds-usage.mlir
This allows vectorisation on global loads and smem in some cases we didn't use it before, as we now compute the order of the elements looking at the actual LinearLayout associated to the given shape of the tensor, which is quite neat.
We end up touching a few things in the Scan lowering as BlockedLayouts when converted to LinearEncodings may not have the same order on elems/threads/warps. This is a feature, not a bug, as it takes us closer to supporting arbitrary LinearEncodings within the tt.scan op.
=> [LAYOUTS] Implement generically getUniqueContigPerThread

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
This fixes the issue https://github.com/triton-lang/triton/issues/5882
The problem was that even though the load seemed to result in something we can vectorize, changing the order of shared mem prevented use of longer cp.async.
=> [PIPELINE] Always follow the order of blocked layout when creating shared layout for cp.async

lib/Analysis/Utility.cpp, test/Analysis/test-allocation.mlir
It turns out that the previous changes within reduce to support LLs had
already trimmed its shmem memory use to the right size.
=> [BACKEND] Don't allocate shmem for warps with repeated data in tt.scan

python/triton/runtime/jit.py
PyTorch issue: https://github.com/pytorch/pytorch/issues/146945
Functionality in PyTorch that started relying on serializability of `JITFunction`: https://github.com/pytorch/pytorch/pull/146417
I suppose there are different ways to solve this problem, but at least the current lambdas are not necessary and can be easily rewritten.
=> Don't use lambdas in `JITFunction` to make it picklable

python/test/unit/language/test_core.py
As of https://github.com/triton-lang/triton/pull/5475, some test cases in `test_scaled_dot` started to lower to the MMAv5 op. So the assert which looks for v2 or v3 ops has become invalid.
=> [Blackwell] Fix `test_scaled_dot` breakage

python/test/unit/language/test_core.py, python/triton/compiler/code_generator.py, python/triton/language/core.py
`num_stages` and `loop_unroll_factor`'s default values are `constexpr(None)`, so we should unwrap them before checking `if _num_stages is not None`
=> [FRONTEND] Fix default values of `tl.range`

include/triton/Tools/LayoutUtils.h, include/triton/Tools/LinearLayout.h, lib/Dialect/TritonGPU/IR/Dialect.cpp, lib/Tools/LayoutUtils.cpp, lib/Tools/LinearLayout.cpp, unittest/Tools/LinearLayoutTest.cpp
To do so, we compute the supremum on the POSET of ordered strings 
without repetition ordered via the inclusion and 
error out if it does not exist. We break ties to the left.
We do this as this is the natural order for the output dims.
=> [LAYOUTS] Make operator* associative and dimension-order-preserving

third_party/amd/lib/TritonAMDGPUTransforms/BlockPingpong.cpp
I recently did some benchmarking work where I was investigating the impact of the Ping Pong Scheduler on various Triton kernels. One issue that I hit was determining when the Ping Pong Scheduler was actually running and I found myself needing to check the source code and manually verify the code path (by both manually doing calculations and inserting print statements).
Having a Remark in my logs that could clearly indicate that the which ping pong cluster has occurred would be extremely helpful for validating that I am using the Ping Pong Scheduler.
including the "tests should be minimal" …
=> [AMD] Add MLIR Remark Messages when the Ping Pong Scheduler Succeeds

third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TritonGPUToLLVM.cpp
Unfortunately `CeilFloorDivExpandOpsPatterns` is not included in `mlir::arith::populateArithToLLVMConversionPatterns` but still included in `populateConvertToLLVMConversionPatterns`.
https://github.com/llvm/llvm-project/blob/main/mlir/lib/Conversion/ArithToLLVM/ArithToLLVM.cpp#L544
=> [BACKEND] Add arith::CeilFloorDivExpandOpsPatterns

lib/Dialect/TritonGPU/Transforms/Prefetch.cpp, test/TritonGPU/prefetch.mlir
Resolved an issue where triton.compile incorrectly specialized batched matrix multiplication kernels.
Fixes #5620.
Before this is fixed, `tl.dot` with batched (3D) input only works in emulation mode when `os.environ['TRITON_INTERPRET'] = '1'` is set, because `tl.dot` is hardcoded to support only 2D tensors in the prefetch pass.
Full code to verify functionality
```python
import torch
import torch.nn as nn
import triton
from functools import partial
@triton.jit
def _matmul_kernel(a_ptr, b_ptr, c_ptr,
M, N, K,
stride_am, stride_ak, stride_bk, stride_bn, stride_cm, stride_cn,
BLOCK_SIZE_M: tl.constexpr, BLOCK_SIZE_N: tl.constexpr, BLOCK_SIZE_K: tl.constexpr):
pid_m, pid_n = tl.program_id(0), tl.program_id(1)
rm = BLOCK_SIZE_M * pid_m + tl.arange(0, BLOCK_SIZE_M) …
```
=> Fix incorrect kernel compilation in batched matmul (#5620)

test/TritonGPU/amd/amd-convert-buffer-ops-range-analysis.mlir
`stride` is not needed if we don't have it anymore after
https://github.com/triton-lang/triton/pull/5908.
=> [AMD] Fix failing tests due to mid-air collision

lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp, test/TritonGPU/accelerate-matmul.mlir
Not all loads are tensor loads. Check for scalar loads to avoid crashing.
=> [TritonGPU] Fix crash in Accelerate matmul

python/test/unit/language/test_core.py, python/triton/language/semantic.py
Reland https://github.com/triton-lang/triton/pull/5866
Note that this is not so much BC breaking as just throwing a hard error when you would previously get an unexpected behaviour.
=> [RELAND] [BC breaking] [FRONTEND] Throw an error when we would downcast an integral constant to a dtype it does not fit in (#5866)

test/TritonGPU/amd/amd-convert-buffer-ops-range-analysis.mlir, third_party/amd/lib/TritonAMDGPUTransforms/ConvertToBufferOps.cpp
If the LoopLikeOpInterface op doesn't have start/stop/step (e.g. `scf.while`) don't assert false, just don't return a trip count.
=> [AMD] Fix loop trip count for scf.while in ConvertToBufferOps

third_party/amd/include/TritonAMDGPUTransforms/Passes.td
We may emit the UpcastMXFPOp in AMDGPUAccelerateMatmul;
so need to register TritonAMDGPUDialect as a dependency.
=> [AMD]Make AMDGPUAccelerateMatmul depend on TritonAMDGPUDialect

lib/Conversion/TritonGPUToLLVM/ControlFlowOpToLLVM.cpp, python/src/ir.cc, python/test/unit/cuda/test_experimental_tma.py, python/triton/_utils.py, python/triton/compiler/code_generator.py, python/triton/language/core.py, python/triton/language/semantic.py
Currently the frontend assumes every function returns either tensor, tuple of tensor, or void. This refactors it to operate on a generic `base_value` object. The function return uses `base_value._flatten_ir` to extract the mlir handles and generate the yield expression. The caller then uses `base_type._unflatten_ir` to rebuild a frontend value from a list of mlir handles.
I had started this refactoring before for scf ops, but I needed to change the signatures a bit because previously you called `base_value._unflatten_ir` however the caller here only has the type and not a pre-existing frontend value.
=> [Frontend] Support returning tensor descriptor from functions

python/setup.py
See release changes: https://github.com/triton-lang/triton/pull/5405
For release we are not looking for something like :
``
pytorch_triton-3.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
``
not:
``
triton-3.2.0+git35c6c7c6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
``
=> Remove git commit hash in wheel name when building from release branch

test/Analysis/test-alias.mlir, test/Analysis/test-alignment.mlir, test/lib/Analysis/TestAlias.cpp, test/lib/Analysis/TestAxisInfo.cpp
This is more robust because the diagnostics are attached to op locations in the checking of outputs.
=> [Analysis] Use `verify-diagnostics` for print-based tests (NFC)

include/triton/Dialect/Triton/IR/Dialect.h, include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td, include/triton/Dialect/TritonGPU/Transforms/Utility.h, include/triton/Tools/LayoutUtils.h, lib/Dialect/Triton/IR/Ops.cpp, lib/Dialect/TritonGPU/IR/Dialect.cpp, lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp, lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp, lib/Dialect/TritonGPU/Transforms/Utility.cpp, lib/Tools/LayoutUtils.cpp, test/TritonGPU/accelerate-matmul.mlir, test/TritonGPU/combine.mlir, unittest/Dialect/TritonGPU/DialectTest.cpp
There are two parts to this PR:
- Propagate dotOp thru join, when dotOp is in the form of linearLayout (mostly reused @lezcano's logic for fp4ToFp)
- Add rough optimization for shmem -> LL load
Motivation for the second part: currently, shmem load into LL falls back to unswizzled shmem layout in the pipeliner, which results in poor performance.
Not only does the `inline_asm` > `join` > `reshape` path suffer from this, so does `fp4_to_fp`.
I've added some basic swizzling logic for the shmem layout when loading into dotOp-like LL's. As an example, for bf16xfp4 `dot_scaled` on a small M, large N/K shape, with fixed config (8, 128, 256), and `DISABLE_MMA_V3=1`:
* before this shmem optimization: **~160us**
* after this shmem optimization: **~124us**
Similar improvements can be observed for …
=> Propagate DotOp thru Join & improve shmem load into LinearEnc

lib/Analysis/Utility.cpp, test/TritonGPU/accelerate-matmul.mlir
Currently we allow MMAv5 for any multiple of 4 `numWarps`. But in practice, only 4 or 8 are supported according to https://github.com/triton-lang/triton/blob/4f302822d25047a8853b12ced682aeb8b20c90f9/lib/Dialect/TritonNvidiaGPU/IR/Dialect.cpp#L102
=> [Blackwell] Fallback to MMAv2 for numWarps other than 4 or 8

lib/Dialect/TritonGPU/Transforms/Utility.cpp
Partial revert of https://github.com/triton-lang/triton/pull/5924
The changed heuristic to pick the swizzling causes performance regression in some cases. Reverting it for now.
cc: @ggengnv
=> [BACKEND] Revert smem layout heuristic added in PR#5924

test/Conversion/tritongpu_to_llvm.mlir, test/Conversion/tritongpu_to_llvm_blackwell.mlir, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TensorMemoryToLLVM.cpp
Refactors tensor memory message emission to support narrower message widths to alleviate register pressure. 
For example, I found that when using the on device TMA descriptors the additional registers they require was sufficient to push the already very tight register budget over the edge for for fp4 kernels where BLOCK_N=256 is optimal. For BLOCK_N = 256, the epilogue currently emits two tcgen05.ld..32x32b.x128 which each require 128 registers and then spills these to thread local memory in order to cast and pack them into fewer output registers. The result is that the on device TMA descriptor creation runtime is about 40-50% slower than when using host TMA descriptors.
With this PR we emit messages each with a smaller width (fewer repeats), with very little performance degredation. In …
=> [Blackwell] Support narrower TMEM messages and shapes

test/Conversion/tritongpu_to_llvm_blackwell.mlir, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TensorMemoryToLLVM.cpp
Tweak a bit the heuristic picking the tmem messages. The num reg estimation was not considering the number of warpgroups.
This fixes performance regressions.
=> [Blackwell] Fix the math to calculate num reg for tmem load/store

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
Reduction should always be supported by distributed layouts
=> [DIALECT] Take out `supportReduction`

include/triton/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVMBase.h, include/triton/Dialect/TritonGPU/IR/Dialect.h, include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td, lib/Analysis/Utility.cpp, lib/Dialect/TritonGPU/IR/Dialect.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/Utility.cpp, unittest/Dialect/TritonGPU/DialectTest.cpp
There were a couple things left to clean up after https://github.com/triton-lang/triton/pull/5840.
Now we provide a common API in terms of RankedTensorType.
=> [LAYOUTS] Move all get.*ContigPerThread functions to a common API

test/TritonGPU/amd/accelerate-amd-matmul-chain-dot.mlir, third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp
This PR improves the logic regarding warp distribution for FA kernels
1. Always choose warpsPerCTA=[numWarps, 1] for the 1st dot
2. For the 2nd dot, distribute warps along dim0 first, then dim1
This helps register pressure for FA kernel with a large output head size.
=> [AMD][FA] Improve warp distribution for decode attention dot

lib/Dialect/TritonGPU/Transforms/FuseNestedLoops.cpp
Ops in prologue/epilogue can't get hoisted by LICM after the loop is flattened, so LICM the outer loop before. We still don't want to LICM the inner loop because it can significantly increase liveranges.
=> [TritonGPU] LICM outer loop before flattening

third_party/amd/lib/TritonAMDGPUTransforms/BlockPingpong.cpp
Adds LLVM Debug messages when the Ping Pong Scheduler fails to execute due to a reason that is not easily to statically calculate. This was prompted by a kernel that failed due to additional global loads unrelated to the original dot product.
=> [AMD] [DEBUG] Added LLVM Debug messages for when the pingpong scheduler fails

lib/Dialect/TritonGPU/IR/Dialect.cpp, test/TritonGPU/canonicalize.mlir
Even though allow_reorder is set, a reshape is not always a no-op as we may swap a replicated value for a non-replicated one.
=> [BACKEND] Fix condition to do a naive reshape with allow_reorder

include/triton/Conversion/TritonGPUToLLVM/TargetInfoBase.h, lib/Conversion/TritonGPUToLLVM/TypeConverter.cpp, lib/Dialect/Triton/IR/Ops.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.h, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.h
MemDescType support attribute memorySpace, but TypeConverter to LLVM not used, this pull request try to fix it.
=> typeConverter to llvm support addressSpace attribute

include/triton/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVMBase.h, include/triton/Conversion/TritonGPUToLLVM/Utility.h, include/triton/Dialect/TritonGPU/IR/Dialect.h, include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td, lib/Conversion/TritonGPUToLLVM/DecomposeUnsupportedConversions.cpp, lib/Conversion/TritonGPUToLLVM/Utility.cpp, lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp, lib/Dialect/TritonGPU/IR/Dialect.cpp, lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp, lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp, lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp, lib/Dialect/TritonGPU/Transforms/OptimizeThreadLocality.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/TMAStoresPipeline.cpp, lib/Dialect/TritonGPU/Transforms/ReduceDataDuplication.cpp, lib/Dialect/TritonGPU/Transforms/Utility.cpp, lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/PlanCTA.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/TMALowering.cpp, third_party/amd/lib/TritonAMDGPUDialectToLLVM/ExtractSliceOpToLLVM.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandWMMA.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/OptimizeLDSUsage.cpp, third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp, third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp, unittest/Dialect/TritonGPU/DialectTest.cpp
This is in preparation for moving the order to be implemented
generically.
We expose `getDefault.*Order` functions that implement hand-written
order. We expect these functions to be used just in the LinearLayout
creation. Eventually we'll inline them in that file and remove them
completely.
=> [LAYOUTS] [NFC] Make order accept a RankedTensorType

third_party/nvidia/backend/driver.py
Note: This patch is an upstream version of what we use internally at Meta with the goal of reducing our internal patches.
This PR adds platform specific information to the caching backend in order to make sure cached data does not get used incorrectly on a different platform.
While one may say that on-disk local cache is only for that one machine, it is not uncommon that these files get transferred between machines either on purpose or accidental.
=> [Frontend][Cache] Include platform information in the key

include/triton/Dialect/TritonGPU/IR/LinearLayoutConversions.h, lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp, lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp, lib/Dialect/TritonNvidiaGPU/IR/Dialect.cpp, python/test/unit/language/test_matmul.py, test/TritonGPU/accelerate-matmul.mlir, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TensorMemoryToLLVM.cpp
Relax restriction on gen05_scaled_dot op to support 8 warps.
Move the layout used for the storing into tmem to use linear for more flexibility.
=> [Blackwell] Support mxfp with 8 warps

include/triton/Dialect/Triton/IR/TritonOps.td, lib/Dialect/Triton/IR/Ops.cpp, lib/Dialect/Triton/IR/Traits.cpp, lib/Dialect/TritonGPU/IR/Dialect.cpp, test/Triton/invalid.mlir, test/TritonGPU/ops.mlir
Relax the verifier of split/join to allow linear and legacy layouts to be mixed.
=> [BACKEND] Allow mixed of linear layout and legacy in split/join

include/triton/Dialect/TritonGPU/IR/LinearLayoutConversions.h, lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp, test/Conversion/amd/ds_transpose.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/MemoryOpToLLVM.cpp, unittest/Dialect/TritonGPU/LinearLayoutConversionsTest.cpp
Currently, we only enable lowering to ds_read_b64_tr_b8 through int8 matrix multiplication.
The same instruction will be selected for fp8 types. However, due to the lack of support and tests for fp8 on the MI350 architecture, this PR limits transpose reads to int8 only.
=> [AMD] MI350 support for ds_read_b64_tr_b8 instruction for int8 GEMMS

lib/Dialect/TritonGPU/Transforms/Pipeliner/TC05MMAPipeline.cpp, test/TritonGPU/mma-pipeline-blackwell.mlir
MMAv5 pipelining has problem with keeping track of async loads feeding into ops at different pipeline stages. All the corner cases are difficult to maintain and problems with this keep arising. I am disabling the support for pipelining when there are more than one dot ops in the loop. This means in most kernels all the loads will be feeding to the dot op, or some operation preceding, resolving the issue. It also means attention kernels won't be pipelined for now, until we finish integrating mmav5 pipelining pass into the new pipeliner infrastructure.
=> Disabling mmav5 pipelining if there are two or more dots in the loop

bin/RegisterTritonDialects.h, test/Proton/allocate_shared_memory.mlir, third_party/proton/dialect/include/Conversion/ProtonGPUToLLVM/CMakeLists.txt, third_party/proton/dialect/include/Conversion/ProtonGPUToLLVM/Passes.h, third_party/proton/dialect/include/Conversion/ProtonGPUToLLVM/Passes.td, third_party/proton/dialect/lib/ProtonGPUToLLVM/AllocateProtonSharedMemory.cpp, third_party/proton/dialect/lib/ProtonGPUToLLVM/CMakeLists.txt, third_party/proton/dialect/lib/ProtonToProtonGPU/ProtonToProtonGPUPass.cpp
In this PR, we add the support for proton's internal SMEM profiling buffer conversion. This pass happens after `proton-to-protongpu` lowering and after the general triton's `shared-memory-alloc` pass. We basically override the `ttg.shared` attributes and annotate the shared memory alloc op proton inserted.
=> [PROTON-DEV] protongpu shared memory buffer conversion pass

.github/workflows/integration-tests.yml, .github/workflows/integration-tests.yml.in
The ASAN test starts to hang recently. So disable it temporary while working on fixing it.
=> [AMD] Disable ASAN tests while figuring out issues

python/src/ir.cc
Right now, running a Triton kernel with MLIR_ENABLE_DUMP=0 results in the software pipeliner pass printing spurious output due to the dumpIntermediateSteps flag that is set when MLIR_ENABLE_DUMP is neither true nor a function value. This fix checks that the result of isEnvValueBool's tri-state does in fact indicate that the value is not a boolean before setting haveDump to true.
=> Fix enable_debug's handling of false value boolean env vars

test/TritonGPU/amd/accelerate-amd-matmul-mfma-gfx950.mlir, third_party/amd/include/TritonAMDGPUTransforms/MfmaGroup.h, third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/MFMA.cpp, third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp, third_party/amd/lib/TritonAMDGPUTransforms/MfmaGroup.cpp
Try to lower fp8 tl.dot to the new scaled mfma on gfx950. Although we only have access to the fused mfma_scale instruction, there're optimization passes to rewrite mfma_scale to normal mfma if both scales are 0.
If we can't select a proper scaled mfma instruction, it will fall back to normal mfma instructions.
=> [AMD]Lower fp8 tl.dot to scaled mfma on gfx950

lib/Dialect/TritonNvidiaGPU/Transforms/MMALowering.cpp, test/TritonNvidiaGPU/mma_lowering.mlir
Commit https://github.com/triton-lang/triton/commit/5c051063f10a27a98b14d119c3fa7235a623ec17 introduced a bug in scaled mma lowering, where we pick wrong shape for the scale blocks in the tensor memory. This change fixes it.
=> [BE] Fix tmem shape for MMAv5 scales

lib/Dialect/TritonNvidiaGPU/Transforms/MMALowering.cpp, test/TritonNvidiaGPU/mma_lowering.mlir
Reworking the code of the `TCGen5MMAScaleSharedToTmemConversion` so it distributes all the elements from the shared memory in the tensor memory, instead of making assumptions of the number of elements in the tensor memory. This should be more robust, and is handling nvfp4 type (that requires different number of scales along K dimension) correctly.
=> [BE] Handling nvfp4 correctly in mmav5 with shared memory scales lowering

python/test/unit/runtime/test_cache.py, third_party/amd/backend/compiler.py
Updates the AMD compiler backend to optimize the implementation of `is_within_2gb` and gate its invocation behind buffer ops being enabled. From internal testing we found that this check can be expensive and since as part of the cache key it will be executed on every kernel invocation. Therefore I believe it makes sense to add a fast path that avoids it when buffer ops related optimizations are disabled.
This also may have an added benefit that if a kernel cannot benefit from the buffer operations then the kernel won't need to be recompiled because we have unnecessarily changed the keys based on the 2GB threshold and therefore caused a cache miss.
- …
=> [AMD] [FrontEnd] Optimize is_within_2gb and only enable with buffer ops supported

test/TritonGPU/amd/accelerate-amd-matmul-mfma-gfx950.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/MFMA.cpp, third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp
This PR optimized the tt.dot_scaled whose both scales are None on gfx950 in a way same as https://github.com/triton-lang/triton/pull/6038.
=> [AMD]Optimize tt.dot_scaled whose both scales are None on gfx950

test/Conversion/tritongpu_to_llvm_blackwell.mlir, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/MMAv5.cpp
The init_acc argument needs to be set only on the first instruction of the accumulation along k.
=> [BACKEND] Fix lowering of gen5.scaled_dot with init_acc

include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td, lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp, python/test/unit/language/test_matmul.py, test/Analysis/test-membar.mlir
We need more accurate modeling of the memory effect for membar to insert a barrier.
=> [BACKEND] Fix missing barrier before tcgen05.copy

test/TritonGPU/amd/optimize-lds-usage.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/OptimizeLDSUsage.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/OptimizeLDSUtility.cpp
This PR fixes crash of OptimizeLDSUsage pass on layout convert involving LinearEncodingAttr.
=> [AMD] Fix crash in OptimizeLDSUsage on Linear encoding

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
GFX950 supports LDS transpose load instructions, so we need swizzling even when K dimension is not innermost. Also, this PR changes number of banks to 64 for swizzling on GFX950 arch.
Swizzling enabled in this PR is realized trough existing SwizzledSharedEncodingAttr.
This pattern can't resolve (but need to confirm this) all bank conflicts for 64b LDS transpose instructions, so likely we will eventually need to switch to custom swizzling pattern.
=> [AMD] Enable swizzling for m/n contig tensors on GFX950

include/triton/Dialect/Triton/IR/Dialect.h, include/triton/Dialect/Triton/IR/TritonOps.td, lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp, lib/Dialect/Triton/IR/Ops.cpp, lib/Dialect/TritonGPU/IR/Dialect.cpp, lib/Dialect/TritonGPU/Transforms/Utility.cpp, test/Conversion/tritongpu_to_llvm.mlir, test/Triton/invalid.mlir, unittest/Dialect/TritonGPU/DialectTest.cpp
Ensure that the layout restrictions are symmetrical between split and join op.
A join source layout can have multiple matching destination layout but a destination layout has only one matching source layout.
=> [BACKEND] Relax join layout restrictions to match split op.

lib/Dialect/TritonGPU/Transforms/Pipeliner/AssignLatencies.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/PipeliningUtility.cpp
Cleaning up the code after https://github.com/triton-lang/triton/pull/6019
Tested with test_matmul.py and 10-block-scaled-matmul.py
=> [BACKEND] Cleaning up tmem_copy references in pipeliner code

include/triton/Conversion/TritonGPUToLLVM/TargetInfoBase.h, lib/Conversion/TritonGPUToLLVM/PrintOpToLLVM.cpp, python/test/unit/language/print_helper.py, python/test/unit/language/test_subprocess.py, third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.h, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.h
We have to pass along the `isSigned` flag from the conversion to target info because triton int types are defined as signless.
=> [BACKEND] Correctly print unsigned types

third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ConvertWarpSpecializeToLLVM.cpp
This PR eliminated the ambiguous evaluation order in the ConvertWarpSpecializeToLLVM pass, which leads to a failure in lit tests if the compiler is clang 20.
=> Eliminate Ambiguous Function Evaluation Order in ConvertWarpSpecializeToLLVM

test/TritonGPU/amd/amd-range-analysis.mlir, third_party/amd/include/Analysis/RangeAnalysis.h, third_party/amd/lib/Analysis/RangeAnalysis.cpp, third_party/amd/lib/TritonAMDGPUTransforms/ConvertToBufferOps.cpp, third_party/amd/test/lib/Analysis/TestAMDRangeAnalysis.cpp
This PR implements initializing lattice ranges using assumptions, ie things like `tl.assume(K < 128)` initializing K to have integer range `[-smax, 128]`.
Additionally it adds support for range inference for various `tt`/`ttg` ops.
=> [AMD] incorporate `tl.assume` into RangeAnalysis and support more ops

CMakeLists.txt, python/setup.py
This option is not used anywhere
=> [BUILD] Remove `TRITON_BUILD_TUTORIALS` from CMakeLists

third_party/amd/test/lib/Analysis/CMakeLists.txt
Add dependency to the target `TritonAMDGPUTestAnalysis` to fix issue in parallel building.
=> [NFC] Add target dependency in CMake to fix issue in parallel building.

third_party/amd/lib/TritonAMDGPUTransforms/ConvertToBufferOps.cpp
Buffer atomic for f16/bf16 dtypes are lowered to ``@llvm.amdgcn.raw.buffer.atomic.fadd.v2f16`` intrinsics which require its input addr to be 4-bytes alligned. Disable this cases for now until the propper fix is implemented.
=> [Buffer Atomic] Disable f16/bf16 buffer atomic operations

test/Conversion/amd/fdivide.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp
This commit lowered math.fdiv to a truely approximated div operation.
=> [AMD] Add math.fdiv FTZ lowering for f32 inputs

.github/workflows/llvm-build.yml
Builds: ``llvm-a66376b0-almalinux-arm64`` artifact
Test:
```
bin/mlir-tblgen --version
LLVM (http://llvm.org/):
LLVM version 21.0.0git
Optimized build with assertions.
```
Failed use case, trying to run ubunu generated aarch64 binary:
```
../../llvm-a66376b0-ubuntu-arm64/bin/mlir-tblgen --version
../../llvm-a66376b0-ubuntu-arm64/bin/mlir-tblgen: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ../../llvm-a66376b0-ubuntu-arm64/bin/mlir-tblgen)
```
This is required in order to build triton aarch64 Manywheel 2.28
Successful run:  https://github.com/triton-lang/triton/actions/runs/13640751105/job/38129853476?pr=6092
This should unlock adding Manyhwheel 2.28 aarch64 builds. Test PR: https://github.com/triton-lang/triton/pull/6089 which is currently failing (since its …
=> Add LLVM aarch64 Almalinux build

python/test/unit/language/test_core.py
This patch asserts the return value of torch.allclose in test_unary_math. If result y was incorrect, the testcase would fail.
torch.allclose() returns a boolean value. it's not an assertion. 
If we comment out the triton kernel call, it's still can pass.
```
-    kernel[(1, )](x, y, BLOCK=shape[0])
+    #kernel[(1, )](x, y, BLOCK=shape[0])
cd python/test/unit; python -m pytest  ./language/test_core.py::test_unary_math
```
The expected behavior: test failed
cd python/test/unit; python -m pytest  ./language/test_core.py::test_unary_math
including the "tests should be minimal" section. …
=> [TEST] Assert the return value of torch.allclose in test_unary_math

test/TritonGPU/amd/amd-block-pingpong.mlir, third_party/amd/lib/TritonAMDGPUTransforms/BlockPingpong.cpp
Fixes a bug in the PingPong Scheduler where it only attempts to move the load op. If for whatever reason the global load calculation is at all more complex and the local load is located above the global store in the original IR, then the IR won't be fully moved. This fixes this by moving the dependencies of any ops that may fall after the first load. By inspection I don't see any other places that could suffer from this except dots (which I am assuming don't need this) and possibly local load slices.
and using …
=> [AMD] Fix One Cluster Ping Pong Scheduler load movement

test/Conversion/amd/buffer_load_store.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/Utility.cpp
Revert change to `getContiguity` for buffer ops from https://github.com/triton-lang/triton/commit/19f329c1d44754caae6e82e89e26bf946f23fc0f#diff-a215260c9e4709845bbbe406e1ae3535b041667fdc32f9ffc33658399c673fb9R540-R547. The `LL` constructed from the blocked layout has a different order which causes wrong vector sizes for buffer ops.
=> [AMD] Fix wrong buffer vector size due to order query 

lib/Dialect/TritonGPU/IR/Types.cpp, test/TritonGPU/amd/amd-reorder-instructions.mlir, test/TritonGPU/dot-operands.mlir, test/TritonGPU/ops.mlir
I have discussed this bug with @ThomasRaoux in https://github.com/triton-lang/triton/issues/6113. The parser of MemDesc ignores the allocShape during parsing.
This PR fixes the bug.
- [ x] I am not making a trivial change, such as fixing a typo in a comment.
- [ x] I have written a PR description following these
- [ x] I have run `pre-commit run --from-ref origin/main --to-ref HEAD`.
=> Fix the parser of MemDesc

lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
This PR addresses a compilation issue when targeting RTX 5090 GPUs with compute capability 120. Previously, the function getMMAVersionSafe would trigger an assertion failure for compute capabilities beyond 110. This update ensures that GPUs with compute capability of 120 fall under a valid MMA version category, preventing unnecessary assertion failures.
Changes
Updated the compute capability check in getMMAVersionSafe to handle GPUs with compute capability up to 129.
Assigned MMA version {2} for these cases to maintain compatibility with customer's gpus only supporting version 2.
Motivation
Certain GPUs, including models from the NVIDIA 50 series, have a compute capability of 120, which was previously unhandled, causing compilation failures. This fix ensures compatibility with such GPUs. …
=> Fix Compilation Issue for RTX 5090 GPUs with Compute Capability = 120

third_party/amd/lib/TritonAMDGPUTransforms/ConvertToBufferOps.cpp
Buffer atomic for f16/bf16 dtypes are lowered to
``@llvm.amdgcn.raw.buffer.atomic.fadd.v2f16`` intrinsics which require its input addr to be 4-bytes alligned. Disable this cases for now until the propper fix is implemented.
Signed-off-by: joviliast <iveselov.nn@gmail.com>
(cherry picked from commit 3b4d63288cb1a990fcba5ac8e57b253b997d1bc7)
=> [Release 3.3] [CP] [AMD] Disable f16/bf16 buffer atomic operations (#6090)

include/triton/Analysis/AxisInfo.h, lib/Analysis/AxisInfo.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/AssignLatencies.cpp, test/Conversion/amd/buffer_load_store.mlir, test/Conversion/amd/buffer_load_to_local_to_llvm.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/Utility.cpp, third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp
This PR changes the lowering to use the `AxisAnalysis` on the offsets to get the correct vector size for buffer operations. The lowering of buffer operations did not analyze the contiguity of the offset values but was only looking at the layout. This results in wrong vectorization when the offsets are not contiguous per lane (e.g. strided loads). 
It also adds a lit test for strided buffer loads and stores and adjusts some existing buffer operation lit tests to provide enough information for the `AxisAnalysis` to work.
=> [AMD] Use AxisAnalysis for buffer op offsets to compute vector size

python/test/unit/language/test_core.py
After switching to the linear layout based convert layout op handling (specifically `transferWithinBlock `) we discovered an issue in the Intel backend where the LLVM vector type `i1` was not handled properly in a load instruction. The issue was discovered by a torch inductor test, and I did not see anything comparable in the Triton unit tests - the existing 1d convert layout only handles i32 types. I added the boolean type as a separate test since the MLIR is quite different, as are the input types, but I am open to combing with the existing `convert1d` test if that is desirable. Tested on RTX A5000.
=> Add 1d convert layout tests for bool types

third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp
Downcasting Fp32 to OCP Bf8 with round-to-zero is done with software conversion which uses numElement = 4 instead of 2.
=> [AMD]Fix a bug in Fp32->OCP Bf8 conversion with round-to-zero

.github/workflows/wheels.yml, python/setup.py
1. TRITON_WHEEL_VERSION_SUFFIX is not needed.
- For Release builds we want to have only version in suffix
- For nightly git sha256 in suffix
2. Set fail-fast true if aarch64 build fails, x86 builds can still continue
3. Update whl version
=> Remove wheel version suffix from wheels, set fail-fast to false for wheel builds

third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ElementwiseOpToLLVM.cpp
```
cvt with .e4m3x2/.e5m2x2 requires sm89 or higher.
cvt.satfinite.{e4m3x2, e5m2x2}.{f32, f16x2} requires sm_89 or higher.
```
=> [BACKEND] Enable vectorized fp8 cast on Ada GPUs

python/test/unit/language/test_core.py, test/TritonGPU/amd/amd-canonicalize-pointers.mlir, third_party/amd/lib/TritonAMDGPUTransforms/CanonicalizePointers.cpp
`CanonicalizePointers` pass was missing a rewrite pattern for `ConvertLayout` to change it to use the offset of the fat ptr. Without this change the pass will fail if the ptr of the `tt.load` was transformed by a `ConvertLayout`.
Added a lit test for it and a general correctness test for indirect loads and stores.
=> [AMD][BACKEND] Support ConvertLayout in CanonicalizePointers

python/triton/runtime/jit.py
This introduces thorough support for annotations of elementary dtypes and pointers. Annotated kernel arguments can under certain circumstances skip `specialize_impl` leading to faster launch times. This is inspired by the patch provided by @saagarjha in the comments in https://github.com/triton-lang/triton/issues/6064 but we go further by doing the logic statically -- when constructing `dynamic_func` -- rather than at runtime.
We also take this opportunity to do some general code simplification and cleanup, including consistently using "u1" rather than "i1" to denote booleans in the specialisation key.
=> Annotations for elementary dtypes and pointers

include/triton/Dialect/TritonGPU/IR/Dialect.h, include/triton/Dialect/TritonGPU/IR/TritonGPUDialect.td, lib/Dialect/TritonGPU/IR/Dialect.cpp
Linear Encodings are going to be queried a ton. Now, we would now want
to copy a LinearLayout from the LL cache and create a new LinearEncoding
each time we want to query the number of elements or warps. As such, we
cache them.
=> [LAYOUTS] Cache LinearEncoding creation

include/triton/Analysis/AxisInfo.h, lib/Analysis/AxisInfo.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/AssignLatencies.cpp, python/test/unit/language/test_core.py, test/Conversion/amd/buffer_load_store.mlir, test/Conversion/amd/buffer_load_to_local_to_llvm.mlir, test/TritonGPU/amd/amd-canonicalize-pointers.mlir, test/TritonGPU/amd/amd-range-analysis.mlir, third_party/amd/include/Analysis/RangeAnalysis.h, third_party/amd/lib/Analysis/RangeAnalysis.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/BufferOpsEmitter.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/BufferOpsEmitter.h, third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.h, third_party/amd/lib/TritonAMDGPUToLLVM/Utility.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/Utility.h, third_party/amd/lib/TritonAMDGPUTransforms/CanonicalizePointers.cpp, third_party/amd/lib/TritonAMDGPUTransforms/ConvertToBufferOps.cpp, third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp, third_party/amd/test/lib/Analysis/TestAMDRangeAnalysis.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp
[AMD] Fix wrong buffer vector size due to order query  (https://github.com/triton-lang/triton/pull/6114)
----
[AMD][BACKEND] Lower BufferLoadToLocal to ROCDL op (https://github.com/triton-lang/triton/pull/6016)
----
[AMD] Use AxisAnalysis for buffer op offsets to compute vector size (https://github.com/triton-lang/triton/pull/6126)
----
[AMD] Fix f16/bf16 buffer atomic operations properly (https://github.com/triton-lang/triton/pull/6139)
----
[AMD] Feed in tl.assume and support more ops in RangeAnalysis (https://github.com/triton-lang/triton/pull/6022)
----
[AMD] Support ConvertLayout in CanonicalizePointers (https://github.com/triton-lang/triton/pull/6142)
----
[AMD] Use pointee type for buffer op alignment in AxisAnalysis (https://github.com/triton-lang/triton/pull/6145)
=> [Release 3.3][CP][AMD] Apply PRs related to buffer ops (#6114, #6016, #6126, #6139, #6022, #6142, #6145)

include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td, lib/Dialect/TritonGPU/Transforms/Pipeliner/PipeliningUtility.cpp, lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp, test/Conversion/tritonnvidiagpu_to_llvm.mlir, test/TritonNvidiaGPU/ops.mlir, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/BarrierOpToLLVM.cpp
This maps to the `mbarrier.arrive` PTX instruction. This is needed for warp specialization in order to synchronize buffers between warp groups.
=> [TritonGPU] Add `ttng.arrive_barrier`

third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp
Those cannot be predicated and they shouldn't be re-ordered anyway.
=> [AMD] Disable loop pipelining when there is assert or print

test/TritonGPU/amd/amd-block-pingpong.mlir, third_party/amd/lib/TritonAMDGPUTransforms/BlockPingpong.cpp
Keep extra calculation between local_load and dot in correct dependency after the pingpong scheduling.
Two/Four cluster pingpong currently only support the case when immedeiate dot sources are local_loads because it should slice them, no fix needed.
=> [AMD][Backend] Fix one cluster pingpong with extra ops after local_load

include/triton/Dialect/TritonGPU/Transforms/Utility.h, lib/Dialect/TritonGPU/Transforms/Utility.cpp
Using base class makes utility functions easier to reuse.
=> [BACKEND] Replacing IRRewriterBase with OpBuilder in couple of places

lib/Dialect/TritonGPU/Transforms/Pipeliner/PipeliningUtility.cpp, test/TritonGPU/amd/amd-stream-loop-assume.mlir
The AMD backend requires the use of tl.assume to propagate non-negative assumptions. Currently these produce a compile time failure if the tl.assume is located in the main loop body, which is easy to do accidentally if the loop body is given its own function that is subsequently inlined for code quality. It may also be necessary if your assume depends on a result that is loaded in the main loop body.
The test added for this PR doesn't stress a real use case of the tl.assume (that would be much more complicated than is necessary for this bug), but it verifies that the tl.assume will persist, including into any generated epilogue, and that it will not breaking the stream pipeline.
- …
=> [AMD] Allow tl.assume in the main loop body when using the stream pipeliner.

python/triton/language/core.py, python/triton/language/semantic.py, python/tutorials/05-layer-norm.py
1. ​**Fixed `grid` Lambda Function in `LayerNorm`:**
- Modified the `grid` lambda function in the `LayerNorm` class to return a tuple instead of a list to comply with interpreter requirements.
2. ​**Updated Type Annotations:**
- Changed input type annotation of `broadcast_impl_shape` from `List[int]` to `Tuple[int]`.
- Updated return type annotation of `get_block_shapes` from `List[int]` to `Tuple[int]`.
- The interpreter in `interpter.py` requires the `grid` lambda function to return a tuple, and lists were causing errors.
- The type annotations were updated to better reflect the actual types used in the code.
- …
=> Fixed `grid` Lambda Function in `LayerNorm` and type anotation of `broadcast_impl_shape` and  `get_block_shapes`

lib/Dialect/TritonGPU/Transforms/Pipeliner/TC05MMAPipeline.cpp, test/TritonGPU/mma-pipeline-blackwell.mlir
When the scales are from tmem they can still be pipelined as long as the scales are invariant.
=> [Blackwell] Relax the condition to pipeline tc_gen5_mma_scaled

include/triton/Dialect/TritonGPU/IR/Dialect.h, include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td, lib/Analysis/Allocation.cpp, lib/Dialect/TritonGPU/IR/Dialect.cpp, lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp, lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp, lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/LowerLoops.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/TMAStoresPipeline.cpp, lib/Dialect/TritonGPU/Transforms/ReduceDataDuplication.cpp, lib/Dialect/TritonGPU/Transforms/Utility.cpp, test/TritonGPU/optimize-locality.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandWMMA.cpp, third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp, third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp, third_party/amd/python/test/test_extract_slice.py, unittest/Dialect/TritonGPU/DialectTest.cpp
This reverts commit 1217ffc9140c5d10929e07c151a6516d5a2c049e.
We observed some regressions on BW.
=> Revert "[LAYOUTS] Move order to LinearEncoding implementation (#6181)"

test/TritonGPU/amd/amd-range-analysis.mlir, third_party/amd/include/Analysis/RangeAnalysis.h, third_party/amd/lib/Analysis/RangeAnalysis.cpp, third_party/amd/test/lib/Analysis/TestAMDRangeAnalysis.cpp
This PR extends RangeAnalysis to infer range for `tt::SplitOp`. It also adds some useful debug prints that for better reporting when RangeAnalysis successfully infers non-negativity.
=> [AMD] extend RangeAnalysis with support for tt.SplitOp

python/test/unit/language/test_matmul.py
In test_mxfp8_mxfp4_matmul, large block sizes can exceed shared memory limitation with num_stages=3.
Found from internal test.
=> [AMD] Fix test_matmul.py num_stage with large block

python/tutorials/10-block-scaled-matmul.py
Now that TMA load for padded fp4 is supported, update the tutorial for mixed precision (`--format mixed`). ~Either cpasync or device TMA can be used for fp4. To use TMA, set `--mixed-fp4-tma`.~ (UPDATE: Now supports only TMA) Using TMA makes it significantly faster (up to 50%)
If https://github.com/triton-lang/triton/pull/6194 goes in first, I'll drop `_experimental_` here.
=> [Blackwell] Support mixed precision in mxfp tutorial

third_party/amd/backend/compiler.py
This picks up https://github.com/triton-lang/triton/pull/6051
to enable hoisting loop invariant loads in the AMD backend.
=> [AMD] Use -triton-licm to replace general -licm

third_party/proton/csrc/include/Context/Shadow.h, third_party/proton/csrc/lib/Context/Shadow.cpp, third_party/proton/test/test_profile.py
Shadow scopes cannot be shared across sessions. Otherwise, the context source will enter the same scope twice as the thread local stack is registered by two sessions.
Note that concurrent session profiling is important when we want to concatenate profiles from different profilers (e.g., instrumentation & pm sampling).
=> [PROTON] Fix multi-session profiling

python/triton/language/core.py
"_str_to_load_cache_modifier" does not accept "ca", you need to use ".ca" now. updated to reflect that. Also added listing of ".cv", which appears to be new.
=> [DOC] Update `tl.load` cache_modifier documentation to match reality

python/test/unit/language/test_core.py
This doesn't seem to be an issue on the CI, but sometimes without this fix num_warps gets written into the string as an np object `np.int64(4)`, which is then invalid MLIR.
=> [TEST] force num_warps to be an int

python/triton/_internal_testing.py
According to the README, Triton still has support for python 3.9, so using `|` for union notation can't be used yet. This should fix the 3.9 wheel.
=> Replace Python 3.10 union type annotation with typing.Union

test/Conversion/amd/ds_transpose.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/MemoryOpToLLVM.cpp
This PR fixes calculation for largeTileThreshold during LDS transpose instruction lowering. 
For fp8, wider MFMA instructions (scaled MFMA) have a k-dimension that is four times of regular MFMA instructions. For fp16/int8 types k-dimension is two times of wider MFMA instructions.
=> [AMD] Fix test_simple_matmul for gfx950

include/triton/Dialect/Triton/IR/TritonOps.td, lib/Dialect/Triton/IR/Ops.cpp, test/Analysis/test-alignment.mlir, test/Triton/invalid.mlir
Add verifier for BitcastOp and invalid lit test
* Implements a verifier on `tt.bitcast` to ensure the operand and result have matching bit widths.
* Supports pointer–pointer bitcasts, but will reject pointer–non-pointer and mismatched scalar widths.
* Adds a new `lit` test case to `test/Triton/invalid.mlir` that exercises the verifier on invalid bit widths.
* Runs the project’s pre-commit hooks, which reformatted a handful of Python files and `clang-format`d the new C++ code.
- Tests:
- `lit` tests:
After building Triton, run `llvm-lit` over the test suite or `triton-opt --verify-diagnostics` on the updated `test/Triton/invalid.mlir` to see the new verifier error:
```
tt.func public @fn(%arg0: tensor<128xf32>) {
// expected-error @+1 {{Cannot bitcast data-type of …
```
=> Add verifier for BitcastOp and invalid lit test

lib/Dialect/TritonGPU/Transforms/WarpSpecialization/RewritePartitionDependencies.cpp
The reason is unspecified evaluation order.
See also: https://github.com/triton-lang/triton/pull/6175
https://github.com/triton-lang/triton/pull/5678
=> [AMD] Fix rewrite-partition-dependencies lit test

README.md, python/test/unit/cuda/test_tensor_descriptor.py, python/triton/compiler/code_generator.py, python/triton/compiler/compiler.py, python/triton/compiler/config.py, python/triton/language/core.py
This also does a few refactorings:
1. Refactor `mangle_ty(type)` -> `type.mangle()`, and implement for `tensor_descriptor_type`
2. Refactor `type.to_ir` -> `type._flatten_ir_types` which matches the `value._flatten_ir` method, but for types.
3. Updates function signature serialization and deserialization to use the new interfaces.
Also, as part of debugging I updated `TRITON_FRONT_END_DEBUGGING=1` to disable wrapping exceptions in `CompilationError` which makes the stack trace point directly to the guts of the frontend making it far easier to debug.
=> [FRONTEND] Support tensordesc in function call arguments

include/triton/Dialect/TritonGPU/IR/Dialect.h, include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td, lib/Analysis/Utility.cpp, lib/Conversion/TritonGPUToLLVM/HistogramOpToLLVM.cpp, lib/Conversion/TritonGPUToLLVM/ScanOpToLLVM.cpp, lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp, lib/Dialect/TritonGPU/IR/Dialect.cpp, lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp, lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/OptimizeLDSUtility.cpp, unittest/Dialect/TritonGPU/DialectTest.cpp
We remove the manual implementations in favour of the generic LL
implementation
=> [LAYOUTS] Kill getWarpsPerCTA(Attribute) and prefer LinearLayout-based impl

test/Conversion/tritongpu_to_llvm_blackwell.mlir, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/MMAv5.cpp
When we have a lhs of 4bits the K dimension calculated was wrong due to ambiguous meaning of some variable.
=> [BACKEND] Fix wrong K dimension for dot_scaled op

bin/RegisterTritonDialects.h, test/TritonGPU/amd/amd-coalesce-async-copy.mlir, third_party/amd/include/TritonAMDGPUTransforms/Passes.h, third_party/amd/include/TritonAMDGPUTransforms/Passes.td, third_party/amd/lib/TritonAMDGPUTransforms/CMakeLists.txt, third_party/amd/lib/TritonAMDGPUTransforms/CoalesceAsyncCopy.cpp, third_party/amd/python/triton_amd.cc
Adds `TritonAMDGPUCoalesceAsyncCopyPass` to convert the blocked layout of AsyncCopies if they produce non coalesced writes on `GFX9` which is a hardware requirement.
The pass ensures `sizePerThread` of the blocked layout is not greater than the contiguity of the source and mask elements and the support load size.
Support for swizzled shared encodings will be added as a separate PR so the pass skips those `AsyncCopies` for now.
This pass will be required when we add `AsyncCopy` pipelining support in the AMD backend in a later PR.
=> [AMD] Add pattern to enforce coalesced write for async load

third_party/amd/lib/TritonAMDGPUToLLVM/AtomicRMWOpsEmitter.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/AtomicRMWOpsEmitter.h, third_party/amd/lib/TritonAMDGPUToLLVM/CMakeLists.txt, third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp
- Use `select` operation instead of bitwise calculations;
- Split different approaches of atomicRMW lowering to different functions;
- Introduce AtomicRMWEmmiter to manage these approaches;
- Skip runtime checks if contiguaity is proven on the compile time
=> [AMD] Atomic rmw refactor

python/test/unit/language/test_core.py
This PR fixes test_gather_warp_shuffle core python test ir replacement code and introduces proper layouts for hip hardware.
Fixes https://github.com/triton-lang/triton/issues/5396
=> [AMD] Fix test_gather_warp_shuffle test

lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp, test/TritonGPU/amd/accelerate-amd-matmul-mfma-gfx950.mlir, test/TritonGPU/combine.mlir
This PR added DotScaledOp as anchor op to the
RemoveLayoutConversion pass to eliminate
`ttg.convert_layout`.
=> [Backend] Make dot_scaled as anchor in RemoveLayoutConversion

test/Conversion/amd/fp_to_fp.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp
Support Bf8/Fp8->Bf16 conversions with ROCDL wrappers rocdl.cvt.scalef32.pk.bf16.* in gfx950.
=> Enable packed Bf8/Fp8->Bf16 conversions for gfx950

test/TritonGPU/amd/amd-canonicalize-pointers.mlir, third_party/amd/lib/TritonAMDGPUTransforms/CanonicalizePointers.cpp
This PR adds support for `tl.extern_elementwise` and `tl.elementwise_inline_asm` in the `convert-to-buffer-ops` pass.
It also does a little cleanup of the test (removes unnecessary `ttg.target` module attributes).
=> [AMD] support `extern_elementwise` and `elementwise_inline_asm` in `convert-to-buffer-ops`

third_party/nvidia/backend/compiler.py, third_party/nvidia/triton_nvidia.cc
The data layout depends on the flag `nvptx-short-ptr` but this flag was being set after we set the data layout. Since this is a global this was only affecting the first kernel compiled.
=> Fix indeterminism bug in LLVM datalayout

lib/Dialect/TritonNvidiaGPU/Transforms/TensorMemoryAllocation.cpp, test/TritonNvidiaGPU/test_tensor_memory_allocation.mlir
It may happen that two tmem allocations share the same liverange end boundary (if it ends at block bound). This case was not handled properly in the tmem allocation pass, causing tmem overallocation.
=> [BE] Fix for colliding tmem allocation boundaries

third_party/nvidia/include/Dialect/NVWS/IR/NVWSAttrDefs.td, third_party/nvidia/include/Dialect/NVWS/IR/NVWSOps.td, third_party/nvidia/lib/Dialect/NVWS/IR/Ops.cpp, third_party/nvidia/test/NVWS/ops.mlir
This is a fairly simple container op for warp specialization analysis and progressive lowering.
Since it's so simple, the only invalid ir I could come up with were standard parser errors, and it's impossible to hit the the validation error via textual IR, so only valid lit tests this time.
=> [NVWS] Add nvws.warp_group IR

python/triton/runtime/autotuner.py
Some users had expressed a desire to cache autotune results, both to speed up local iteration, and to avoid re-tuning when scaling up to large numbers of GPUs.
This PR caches tuning timings in Triton's cache dir.  Running locally on 03-matrix-multiplication.py, the time of later runs is greatly reduced:
```
% time python ./03-matrix-multiplication.py
...
real    1m59.055s
% time python ./03-matrix-multiplication.py
...
real    0m13.794s
```
The cache key consists of:
* system information (triton source, target info, env vars)
* kernel source code (with dependences)
* the values of the tuning keys (e.g. M/N/K in the matmul example)
* the set of configs requested for tuning (so that we'll re-tune if the user changes tunings)
If any configs have `pre_hook`s defined, we don't try caching at …
=> Cache autotune timings to disk

include/triton/Conversion/TritonToTritonGPU/Passes.td, include/triton/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.h, include/triton/Dialect/TritonGPU/Transforms/Passes.td, include/triton/Dialect/TritonGPU/Transforms/TritonGPUConversion.h, lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp, lib/Conversion/TritonToTritonGPU/CMakeLists.txt, lib/Conversion/TritonToTritonGPU/TritonGPUConversion.cpp, lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp, lib/Dialect/TritonGPU/Transforms/CMakeLists.txt, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/AutomaticWarpSpecialization.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/OptimizePartitionWarps.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/PartitionLoops.cpp, test/Conversion/triton_to_tritongpu.mlir, test/TritonGPU/automatic-warp-specialization.mlir, test/TritonGPU/load-mma-specialization.mlir, test/TritonGPU/optimize-partition-warps.mlir, test/TritonGPU/partition-loops.mlir
PartitionLoops no longer changes the number of warps of the partitions -- they are always left at the default number. A separate pass runs after the important DCE to analyze the IR and determine the number of warps needed. As before, if there are no tensor computations in the partition, the number of warps is set to 1.
However, the pass will now also look at tensor computations and shrink the number of warps. It does this by doing a very rough estimate of the register usage of the partition and comparing it against the pool of available registers given the number of warps. If it can reduce the number of warps, the algorithm iterates to fixed point. This is important, e.g., for TMA gather or scatter ops that can still use tensor ops, but generally small 1D tensors.
This still assumes …
=> [TritonGPU] Add a separate pass for optimizing partition num warps

lib/Dialect/TritonGPU/IR/Ops.cpp, test/TritonGPU/canonicalize.mlir
Changes `CanonicalizeConvertFromConvert` to include the `AsyncToken` when rewriting the `local_load`.
=> [BACKEND] Do not drop local_load's AsyncToken in CanonicalizeConvertFromConvert

README.md, python/requirements.txt
CMake was updated to 4.0 yesterday and it's breaking our macos builds:
https://pypi.org/project/cmake/#history
=> [Build] Pin cmake < 4

include/triton/Tools/Sys/GetEnv.hpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/AssignLatencies.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/LowerLoops.cpp, test/TritonGPU/pipeline-assign-latencies.mlir, test/TritonGPU/pipeline-lower-loop.mlir
Resolving `wait_barrier` placement issue, that was causing functional issues in pipelined attention kernels. There are still some performance regressions in internal attention workloads when running with pipelining enabled, so adding also `ENABLE_MMA_V5_ATT_PIPELINE` env var that controls whether loops with multiple dot ops will be pipelined. Disabled by default, until performance problems are addressed.
=> [PIPELINE][BW] Resolved functional problems with pipelined attention kernels.

include/triton/Dialect/TritonGPU/IR/LinearLayoutConversions.h, include/triton/Dialect/TritonNvidiaGPU/IR/Dialect.h, lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp, lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp, lib/Dialect/TritonNvidiaGPU/IR/Dialect.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/PromoteLHSToTMem.cpp, python/test/unit/language/test_core.py, test/TritonGPU/accelerate-matmul.mlir, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TensorMemoryToLLVM.cpp
When running attention with multiple warpgroups we used to have reduction across warps. Add an optimization to load from tmem with a different layout that allows the reduction to be fully within a warp.
=> [Blackwell] Support tmem_load destination layout friendly to attention

python/test/unit/language/test_core.py, python/triton/language/core.py
In Triton 3.2, the AST parser correctly handles expressions like:
```python
float_minus_inf, float_inf = float("-inf"),  float("inf")
```
However, after the introduction of the tuple class in Triton 3.3.0, these expressions fail to parse correctly. This appears to be a regression in the AST parsing logic.
Expected Behavior:
The parser should continue to support float("inf") and float("-inf") expressions as it did in version 3.2.
Actual Behavior:
In Triton …
=> [Fix] AST parsing fails for float("inf") and float("-inf") in Triton 3.3.0 due to tuple class introduction

third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandWMMA.cpp
In the case of batch dimension is not slowest, return empty value and provoke failure. Linear layout convertor should deal with this case.
Fixed: test_core.py::test_dot3d[8-1-64-64-64-32-32-float16-float32]
=> [AMD][WMMA] Fail in wmma convertor and use linear convertor instead

test/TritonGPU/amd/amd-block-pingpong.mlir
Simplifies the AMD block pingpong to reduce the complexity in extending future tests.
=> [NFC] [AMD] Simplify amd-block-pingpong.mlir tests to omit unused arguments

bin/RegisterTritonDialects.h, python/test/unit/language/test_core.py, test/TritonGPU/amd/amd-fold-true-cmpi.mlir, test/TritonGPU/amd/amd-range-analysis.mlir, third_party/amd/include/Analysis/RangeAnalysis.h, third_party/amd/lib/Analysis/RangeAnalysis.cpp, third_party/amd/lib/TritonAMDGPUTransforms/ConvertToBufferOps.cpp, third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp, third_party/amd/test/lib/Analysis/CMakeLists.txt, third_party/amd/test/lib/Analysis/TestFoldTrueCmpIOp.cpp
~~Waiting on https://github.com/llvm/llvm-project/pull/133151 upstream.~~
This PR adds a pattern that folds "true" `arith.cmpi` operations to `arith.constant true`; e.g.
```mlir
%c0 = arith.constant 0 : i32
%c1024_i32 = arith.constant 1024 : i32
%cmpsge = arith.cmpi sge, %c1024_i32, %c0 : i32
```
->
```mlir
%cmpsge = arith.constant true
```
(after DCE).
The specific use case is "unguarding" the epilogue in pipelined loops (e.g., as produced by `tritonamdgpu-stream-pipeline`). So e.g.,
```mlir
tt.func @assume_matmul(%arg0: index, %arg1: index, %arg2: index, %arg3: !tt.ptr<f16>, %arg4: !tt.ptr<f16>) -> tensor<128x128xf32, #mma> {
...
%20:6 = scf.for ... {
scf.yield ...
}
...
%27 = arith.cmpi sge, %26, %c1 : index
%31 = scf.if %27 -> (tensor<128x128xf32, #mma>) {
%33 = tt.dot %28, %30, %20#2 …
```
=> [AMD] DCE/canonicalize true epilogue conditionals

include/triton/Dialect/TritonNvidiaGPU/Transforms/TMAUtilities.h, test/TritonNvidiaGPU/optimize_descriptor_encoding.mlir
The code was expecting that we needed to rank-reduce the layout, but since we're propagating it backward from the load we're actually increasing the rank of the encoding to match the descriptor rank.
=> [TMA] Fix assignment of unswizzled layouts from rank-reducing loads

python/tutorials/09-persistent-matmul.py
Currently the metadata function assumes all tma kernels are running fp16 which causes the tflops8 metric to not be populated.
=> [TUTORIAL] Fix tflops metric for tma fp8 kernels

third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
Please see equal change for WMMA: https://github.com/triton-lang/triton/pull/6350
=> [AMD][MFMA] Use linear layout for batch-non-slowest 3D conversion

test/Conversion/amd/async_ops_to_llvm.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp
Similar to `BufferLoadToLocal` (https://github.com/triton-lang/triton/pull/6329) we can swizzle the global ptrs of `AsyncCopy` between lanes of a warp to get coalesced writes to lds.
This PR mostly extracts the common code between `BufferLoadToLocal` and `AsyncCopy` and uses it for both Ops.
=> [AMD][BACKEND] Support swizzled shared encodings when lowering AsyncCopy

python/tutorials/09-persistent-matmul.py
This changes the tutorial to try both warp-specialized and non-warp-specialized configs when available. I also updated the verification and benchmark steps to print out incremental progress updates so you can tell the scripts hasn't hanged.
Example output from the middle of a run:
```
M=32, N=32, K=32, verification naive vs:
Torch: ⭕
cuBLAS: ✅
Persistent: ✅
TMA (warp_specialize=False): ✅
TMA (warp_specialize=True): ✅
TMA Persistent (warp_specialize=False): ✅
TMA Persistent (warp_specialize=True): ✅
Tensor Descriptor Persistent (warp_specialize=False): ✅
Tensor Descriptor Persistent (warp_specialize=True): ...
```
We should probably rename this advanced-matmul at this point tbh.
=> [TUTORIAL] Cleanup persistent matmul tutorial

third_party/nvidia/include/cublas_types.h
The header relies on these libraries. Include them so it can be compiled on its own for cleanliness.
=> Make cublas_types.h standalone

test/TritonGPU/amd/amd-block-pingpong.mlir, third_party/amd/lib/TritonAMDGPUTransforms/BlockPingpong.cpp
This moves the final cluster barrier generated by the Ping Pong Scheduler to the end of the for loop. The motivation is the persistent Matmul use case. Consider the iteration under which the epilogue is being executed. Typically the next iteration is also the prologue, so that creates a cluster that looks like this:
```
final_dot_cluster
s_barrier
epilogue ...
prologue ...
first_memory_cluster
s_barrier
```
This PR instead swaps the s_barrier location to ensure the prologue and epilogue are divided evenly across the memory and dot clusters.
```
final_dot_cluster
epilogue ...
s_barrier
prologue ...
first_memory_cluster
s_barrier
```
On my testing on a small set of shapes this seemed to offer about 7% TFLOPs increase for persistent matmul.
In the future it may be useful to characterize the …
=> [AMD] Move last Ping Pong Scheduler cluster barrier to the end of the For Loop

lib/Dialect/TritonGPU/Transforms/Pipeliner/WGMMAPipeline.cpp, test/TritonGPU/loop-pipeline-blackwell.mlir
When combining redundant `AsyncWait` we should include the tokens from the start Op. Otherwise we will drop them when creating the new `AsyncWait`.
The for loop in the adjusted lit test will carry two more `AsyncCommitGroups` because they are no longer remove by canonicalize
=> [BACKEND] Do not drop initial commit group when combining wait ops

lib/Dialect/TritonGPU/Transforms/Pipeliner/LowerLoops.cpp, test/TritonGPU/pipeline-lower-loop.mlir
<git-pr-chain>
1. [Pipeliner] Fix non-dominated use error with TMA loads
We can have cases where a TMA load is used by a LocalAllocOp,
but that allocation's encoding isn't compatible with the TMA and so
this special case was not valid since it ignore the local alloc under
the assumption assume it will be rewriten to use the TMA buffer.
This resulted in LocalLoadOp being inserted after the use by the
LocalAllocOp.
1. Fix all uses of canBeShmemPipelined and rename
1. 👉 #6392 👈 **YOU ARE HERE**
=> [Pipeliner] Fix non-dominated use error with TMA loads

third_party/amd/backend/compiler.py
This commit enables in-thread transpose on by default for gfx942. It will transpose the elements with a thread using registers after global load and before local write in order to maintain good global memory coalescing and wide ds instruction bitwidth and avoid shared memory bank conflicts.
=> [AMD] Turn in-thread transpose for gfx942 on by default

python/tutorials/09-persistent-matmul.py
This was accidentally included in #6374, doesn't seem to change the benchmark numbers too much though, ~20 extra tflops for cublas:
```
├─ 1618.721 849.059 cublas [M=8192, N=8192, K=512]
│  └─ nan 849.059 nvjet_qqhsq_256x256_128x4_2x1_2cta_v_bz_TNT
├─ 1512.257 454.417 matmul_kernel [M=8192, N=8192, K=512]
├─ 1814.302 378.765 matmul_kernel_descriptor_persistent [M=8192, N=8192, K=512]
├─ 1896.133 362.419 matmul_kernel_descriptor_persistent_ws [M=8192, N=8192, K=512]
├─ 1829.098 375.701 matmul_kernel_persistent [M=8192, N=8192, K=512]
├─ 1481.243 463.931 matmul_kernel_tma [M=8192, N=8192, K=512]
├─ 1945.690 353.188 matmul_kernel_tma_persistent [M=8192, N=8192, K=512]
├─ 2074.555 331.249 matmul_kernel_tma_persistent_ws [M=8192, N=8192, K=512]
└─ 1161.908 591.436 matmul_kernel_tma_ws [M=8192, …
```
=> [TUTORIAL] Restore cublas warmup

python/tutorials/09-persistent-matmul.py
Doesn't seem to make any difference to the performance numbers, but does remove some torch kernels from the trace so that's nice.
```
1658.978 3728.050 ROOT
├─ 1615.049 425.495 cublas [M=8192, N=8192, K=512]
│  └─ nan 425.495 nvjet_qqhsq_256x256_128x4_2x1_2cta_v_bz_TNT
├─ 1506.697 456.093 matmul_kernel [M=8192, N=8192, K=512]
├─ 1827.475 376.035 matmul_kernel_descriptor_persistent [M=8192, N=8192, K=512]
├─ 1905.893 360.563 matmul_kernel_descriptor_persistent_ws [M=8192, N=8192, K=512]
├─ 1831.274 375.255 matmul_kernel_persistent [M=8192, N=8192, K=512]
├─ 1483.875 463.108 matmul_kernel_tma [M=8192, N=8192, K=512]
├─ 1955.301 351.452 matmul_kernel_tma_persistent [M=8192, N=8192, K=512]
├─ 2098.157 327.523 matmul_kernel_tma_persistent_ws [M=8192, N=8192, K=512]
└─ 1159.774 592.524 …
```
=> [TUTORIAL] Deactivate proton before warmup

python/test/unit/language/test_pipeliner.py
This test is deterministically failing. I have observed it failing on several unrelated PRs now.
fyi @antiagainst
=> [AMD] Disable failing test

lib/Dialect/TritonGPU/Transforms/Pipeliner/PipelineExpander.cpp
Fix case where a distance one value is defined outside the loop.
TODO: we don't test the expander in our repo, we need to either move to using MLIR one directly or bring the tests into triton repo. Will be done in another PR
=> [Pipeliner] Fix special case in expander

include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td, include/triton/Dialect/TritonNvidiaGPU/Transforms/Passes.h, include/triton/Dialect/TritonNvidiaGPU/Transforms/Passes.td, lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/CMakeLists.txt, lib/Dialect/TritonNvidiaGPU/Transforms/OptimizeTMemSubtiling.cpp, python/test/unit/language/test_matmul.py, test/TritonNvidiaGPU/tmem_subtiling.mlir, third_party/nvidia/backend/compiler.py, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TensorMemoryToLLVM.cpp, third_party/nvidia/triton_nvidia.cc
When loading from tmem we have multiple choices on how to distribute the tensor in registers. If we see that the tensor will be split along N we break up the tmem_load to allow it to be better scheduled.
Also try to sink tmem_load as late as possible to save register pressure. This may need to be tweaked if it causes latency problems.
=> [BACKEND] Improve subtiling code generation when loading from tmem

include/triton/Dialect/Triton/IR/TritonOpInterfaces.td, include/triton/Dialect/Triton/IR/TritonOps.td, include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td, lib/Dialect/Triton/IR/OpInterfaces.cpp, lib/Dialect/Triton/IR/Ops.cpp, lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp, lib/Dialect/TritonGPU/Transforms/DecomposeScaledBlocked.cpp, lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/MMALowering.cpp, python/src/ir.cc, python/test/unit/language/test_matmul.py, python/triton/language/core.py, python/triton/language/semantic.py, test/Conversion/tritongpu_to_llvm_blackwell.mlir, test/TritonGPU/accelerate-matmul.mlir, test/TritonNvidiaGPU/mma_lowering.mlir, third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/MMAv5.cpp
Add a new flag to pick the packing format for fp4 inputs in dot_scaled op. This allows supporting hardware fp4 transpose in blackwell by going through the mixed mode mxfp4 * mxfp8 message. 
Using this path will prevent getting fullt throughput when using dot_scaled mxfp4 * mxfp4.
=> [Feature] Support different packing formats in dot_scaled op

python/test/unit/language/test_core.py, python/triton/language/semantic.py, python/triton/runtime/interpreter.py
Fixes #6376
The software emulation of atomic min/max uses `x >= 0` to test the signbit, which breaks down when `x` is `-0.0` which equals zero but does have the sign bit set .
I fix this by looking at the bit representation of the float and extracting the sign bit directly.
I also fix not_ raising an error in the interpreter from `get_all_ones_value` since `np.bool` doesn't have "int" in the name.
=> [FRONTEND] Fix atomic min/max for float with negative zero

lib/Dialect/TritonGPU/Transforms/HoistTMEMAlloc.cpp
The patch fixes use-after-free error in the recently introduced HoistTMEMAlloc.cpp which was detected by the asan build.
We cannot use iterator to the users after erasing the current user of it.
The solution is to wrap the iterator with make_early_inc_range.  
=> Fix use after free in CombineTMEMLoadAndStore

include/triton/Dialect/TritonGPU/Transforms/PipeliningUtility.h, lib/Dialect/TritonGPU/Transforms/Pipeliner/PipeliningUtility.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/WGMMAPipeline.cpp, third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp
Moved `combineRedundantWaitOps` from `WGMMAPipeline` to `PipeliningUtility` to reuse it in the Streampipeliner.
=> [AMD][BACKEND] Combine redundant AsyncWaits in StreamPipeliner

python/src/ir.cc
Previously, when we performed IR relocation, we didn’t output locations of the ModuleOp.
What we printed to the output stream didn’t include locations, but what we stored in the file still did, resulting in mismatches.
Now that we use a single function to control the format of the output IR, we always output locations.
=> [BACKEND] Standardize IR print options

.github/workflows/wheels.yml
Seeing following error:
https://github.com/triton-lang/triton/actions/runs/14364110492/job/40272734561
```
Uploading distributions to https://upload.pypi.org/legacy/
ERROR    InvalidDistribution: Metadata is missing required fields: Name,        
Version.                                                               
Make sure the distribution includes the files where those fields are   
specified, and is using a supported Metadata-Version: 1.0, 1.1, 1.2,   
2.0, 2.1, 2.2, 2.3.    
```
twine needs to be updated.
=> [release-only] Update twine for release 3.3.x

bin/RegisterTritonDialects.h, test/TritonGPU/amd/amd-update-async-wait-count.mlir, third_party/amd/backend/compiler.py, third_party/amd/include/TritonAMDGPUTransforms/Passes.h, third_party/amd/include/TritonAMDGPUTransforms/Passes.td, third_party/amd/lib/TritonAMDGPUTransforms/CMakeLists.txt, third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp, third_party/amd/lib/TritonAMDGPUTransforms/UpdateAsyncWaitCount.cpp, third_party/amd/lib/TritonAMDGPUTransforms/Utility.cpp, third_party/amd/lib/TritonAMDGPUTransforms/Utility.h, third_party/amd/python/triton_amd.cc
Adds `UpdateAsyncWaitCountPass` to adjusts the wait counts of `AsyncWait` ops to reflect the number of interleaved direct to lds assembly instructions. The LLVM backend cannot infer the dependency between the `AsyncCopies` and the `local_reads` so we emit it from Triton as we have the dependency information via tracing the `AsyncToken`.
The pass ignores global/buffer loads because the actual number of assembly instructions is determined by the LLVM backend. Note that an underestimation does only affect performance but not correctness.
`findMinPathCountInDefChain` is in separate file because we might reuse it for combining `AsyncWaits` in the `StreamPipeliner`.
=> [AMD][BACKEND] Count vmcnt instructions for AsyncWait to emit correct vmcnt

python/src/ir.cc
Otherwise we may see tokens like `dense<__elided__>`
=> [BACKEND] Do not elide element attributes when printing IRs

python/test/unit/language/test_core.py, third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp
- Replace the inline assembly for i32->f32 conversion with LLVM::SIToFpOp to allow potential backend optimizations.
- Enable bf16 conversions in test_core.py.
=> Replace the inline assembly for i32->f32 conversion with LLVM::SIToFpOp

python/test/unit/language/test_matmul.py
Disabled:
- language/test_matmul.py::test_blocked_scale_mxfp
- language/test_matmul.py::test_lhs_in_tmem
- language/test_matmul.py::test_lhs_in_tmem_mxfp
=> [AMD] Disable unsupported matmul tests

include/triton/Dialect/TritonNvidiaGPU/Transforms/TMAUtilities.h, lib/Conversion/TritonGPUToLLVM/FuncOpToLLVM.cpp, lib/Conversion/TritonGPUToLLVM/TypeConverter.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/OptimizeDescriptorEncoding.cpp, python/src/ir.cc, python/test/unit/cuda/test_tensor_descriptor.py, python/triton/language/__init__.py, python/triton/runtime/jit.py, python/triton/tools/experimental_descriptor.py, python/tutorials/09-persistent-matmul.py, test/Conversion/tritongpu_to_llvm.mlir, test/TritonNvidiaGPU/optimize_descriptor_encoding.mlir, third_party/nvidia/backend/compiler.py, third_party/nvidia/backend/driver.c, third_party/nvidia/backend/driver.py
<git-pr-chain>
1. [NVIDIA] Add compiler-controlled host side tensor descriptor API
This adds a new `TensorDescriptor` kernel argument which doesn't rely on
convention, and instead choses the descriptor parameters at compile time
and communicates this to the launcher via the kernel signature in the
ttgir (this is later serialized in the kernel metadata in the cache).
The real `CuTensorMap` object is then created at the last second in the
kernel launcher. We can revisit this with caching if needed to reduce
launch overhead. I was however careful to not introduce any additional
overhead for kernels not using `TensorDescriptor`.
Benchmarks show we achieve the same performance benefits as the previous
host side API (descriptor=device side, tma=host side):
```
1690.079 3659.446 ROOT
├─ 1598.967 …
```
=> [NVIDIA] Add compiler-controlled host side tensor descriptor API

include/triton/Conversion/TritonGPUToLLVM/TargetInfoBase.h, include/triton/Conversion/TritonGPUToLLVM/Utility.h, lib/Conversion/TritonGPUToLLVM/MemoryOpToLLVM.cpp, lib/Conversion/TritonGPUToLLVM/Utility.cpp, test/Conversion/amd/async-ops-alias-scopes.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/BufferOpsEmitter.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/BufferOpsEmitter.h, third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/MemoryOpToLLVM.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.h, third_party/amd/lib/TritonAMDGPUToLLVM/Utility.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/Utility.h
Add all `AsyncLoads`/`BufferLoadToLocal` to a single alias scope and annotate `LocalLoads` to **not** alias with any `AsyncLoads`/`BufferLoadToLocal` if they depend on an `AsyncToken` from an `AsyncWait`. This tells the LLVM backend to no emit conservative waits before those `LocalLoads` and allows us to manually syncronize via `AsyncWait` enabled by https://github.com/triton-lang/triton/pull/6426.
=> [AMD][BACKEND] Add Alias Information to interleave AsyncLoads and LocalReads in pipelined loops

.github/workflows/integration-tests.yml, .github/workflows/integration-tests.yml.in
This takes a lot of space, trying to remove it to see if it helps reducing the amount of cache misses.
Also bump the timeout as gb200 node downloads is very slow.
=> [CI] Remove kernel cache form github cache

test/TritonGPU/amd/accelerate-amd-matmul-wmma-gen1.mlir, test/TritonGPU/amd/accelerate-amd-matmul-wmma-gen2.mlir, third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp
Although wmma supports configurations like
{f16, f16, f16, f16} and {bf16, bf16, bf16, bf16}, use f32 accumulators and results, and convert the result to f16 if required.
This change is needed to provide equivalent behavior across different targets.
fixed gfx11/12:
test_matmul.py::test_simple_matmul[False-4-1-128-128-16-4-float16-float16] test_matmul.py::test_simple_matmul[False-4-1-64-128-32-4-float16-float16] test_matmul.py::test_simple_matmul[False-4-1-32-32-32-4-float16-float16] test_matmul.py::test_simple_matmul[False-4-1-64-16-16-4-float16-float16] test_matmul.py::test_simple_matmul[False-8-1-128-128-16-4-float16-float16] test_matmul.py::test_simple_matmul[False-8-1-64-128-32-4-float16-float16] test_matmul.py::test_simple_matmul[False-8-1-32-32-32-4-float16-float16] …
=> [AMD][WMMA] Disable dot wmma configurations that use f16 as accumulator

test/TritonGPU/amd/amd-range-analysis.mlir
This PR uses `-verify-diagnostics=only-expected` to reduce tests in `amd-range-analysis.mlir`.
=> [AMD][NFC] reduce range-analysis tests

include/triton/Dialect/Triton/IR/TritonOps.td, include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td, include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td, lib/Dialect/Triton/IR/Ops.cpp, lib/Dialect/TritonGPU/IR/Ops.cpp, lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp
This PR cleans up side effect specification to use the `Arg<Type, desc, [effects...]>` trick in ODS, which is a more concise way to specify memory effects. At the same time, many ops are specifying coarser side effects than necessary, and this PR changes them to target a specific SSA operand or result where application.
Most notably, the many ops that access TensorMemory or GlobalMemory were made to have finer grained side effects.
=> [Dialect] Cleanup and improve granularity of side effects

third_party/amd/include/Dialect/TritonAMDGPU/IR/TritonAMDGPUOps.td
This commit refines AMD op side effects Similar to
https://github.com/triton-lang/triton/pull/6476.
=> [AMD] Improve granularity of side effects

lib/Tools/LinearLayout.cpp, test/Conversion/tritongpu_to_llvm_debug.mlir
This PR introduces stronger check for empty layouts in invertAndCompose to fix compiler crashes while running in debug mode.
=> [LinearLayout] Fix crash with debug

lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp, test/TritonNvidiaGPU/membar.mlir
This is a tiny partial revert of #6476, removing the addition `MemWrite<SharedMemory>` on the barrier operand of the MMAv5 ops. This wasn't present before. This is causing extra barriers to be inserted between MMA ops and mbarrier waits.
This was causing large performance regressions across the board. However, as things stand, the compiler can't see interfering memory effects between the MMAv5 ops and barrier waits. We will probably have to model the side effects here in a different way. Technically, the MMAv5 ops don't write or read the barrier, but push a request onto the MMAv5 pipeline.
=> [TritonNVIDIAGPU] Revert MMAv5 write effect on barrier

python/triton/language/standard.py
This improves the runtime of an internal radix sort benchmark by 25%
=> Attempt to simplify tl.sort and tl.flip

test/Conversion/amd/async_ops_to_llvm.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp
Emit a conservative load instead of erroring out if the `vmcnt` is larger than 6 bits (hardware limit).
=> [AMD][BACKEND] Clamp vmcnt instead of erroring out in AsyncWait lowering

python/triton/backends/__init__.py
I'm seeing that #6468 actually broke importing `triton.backend.nvidia.compiler` because the `nvidia` module hasn't been imported. Instead, lets just use importlib to import the package as if by writing a normal python `import` statement.
=> [Backends] Use normal import method instead of file import

python/triton/compiler/compiler.py
Similar to https://github.com/triton-lang/triton/pull/6000 this patch is an upstreamed internal patch at Meta with the goal of reducing our internal patches, cc @jamesjwu the original author.
When running various benchmarks with small kernels we see a non-trivial amount of time spent fetching this property, and memoizing helped.
It might be worth looking into memoizing `get_device_properties`, but I think that'd need a more careful treatment in the driver package in order to properly handle arbitrary backends.
=> [python][compiler] Memoize device max shared memory per device

python/triton/compiler/code_generator.py, python/triton/language/__init__.py, python/triton/language/core.py, python/tutorials/06-fused-attention.py
<git-pr-chain>
[FRONTEND] Cleanup nv_tma_desc_type
This is now dead code, `nv_tma_desc` now only exists in the backend.
1. 👉 #6508 👈 **YOU ARE HERE**
1. #6509
=> [FRONTEND] Cleanup nv_tma_desc_type

include/triton/Dialect/Triton/IR/TritonDialect.td, include/triton/Dialect/TritonGPU/Transforms/PipeliningUtility.h, lib/Dialect/TritonGPU/Transforms/Pipeliner/AssignLatencies.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/PipeliningUtility.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/TestPipelineScheduleLoop.cpp, test/TritonGPU/loop-pipeline-async-latencies.mlir, test/TritonGPU/loop-schedule.mlir
* Converted ad-hoc attribute handling to AttrHelpers to ensure consistency
* Changed `tt_latency` to `tt.latency` in AssignLatencies?
=> [PIPELINER] Use AttrHelper (mostly NFC)

include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td, include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td, lib/Dialect/Triton/IR/Ops.cpp, lib/Dialect/TritonGPU/IR/Ops.cpp, lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp
This is an NFC reland of #6476. I am splitting out the functional changes so that we can narrow done the commit that is causing a bitwise equivalence problem in an internal test.
=> [DIALECT] Clean up memory effect definitions (NFC)

third_party/nvidia/backend/driver.py
This change was introduced in https://github.com/triton-lang/triton/commit/053f98b79076f3e819eb637e61c3b6b1014ad8fe.
=> Remove import-time dependency on PyTorch in nvidia driver.py

test/TritonGPU/amd/amd-canonicalize-pointers.mlir, third_party/amd/lib/TritonAMDGPUTransforms/CanonicalizePointers.cpp
This PR fixes a bug in pointer canonicalization where pointee types with widths K < 32 are canonicalized to offset tensors with elements of width K (which is inappropriate for AMDGPU arches which only support 32b/64b pointer widths).
=> [AMD] fix pointer canonicalization for i16 pointers/pointees

test/Conversion/amd/fp_to_fp.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/UpcastMXFPToLLVM.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/Utility.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/Utility.h
In GFX950, lower arith::TruncFOp to LLVM::FPTruncOp of vector types in order to generate packed conversion instructions v_cvt_pk_[b]f16_f32.
=> Support Fp32->Fp16/Bf16 with packed conversion ops in GFX950

bench/bench/bench_mlp.py, bench/triton_bench/matmul_ogs_details/opt_flags_amd.py, bench/triton_bench/meta.py
This PR fixed the failure of running `bench_mlp.py` on AMD MI300 GPU. 
The script always uses `torch.float8_e4m3fn` but MI300 uses the special torch.float8_e4m3fnuz` type. 
Since now we have two different checks to do on the AMD platform since it would have different behaviors depending on it is CDNA3 or CDNA4, I refactored the code slightly to make it cleaner.
=> [BENCH][AMD] Enable gfx942 for bench_mlp.py

lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp, test/Conversion/amd/ds_transpose.mlir, test/TritonGPU/amd/accelerate-amd-matmul-chain-dot.mlir, test/TritonGPU/amd/mfma-double-rate.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/MFMA.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/MemoryOpToLLVM.cpp, third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp, unittest/Dialect/TritonGPU/LinearLayoutConversionsTest.cpp
For the 2nd dot, operand 0 comes from the result of 1st dot, which has mfma layout. This layout is essentially the same layout as a dotOperand layout with kWidth=4.
However, if double rated mfma is used for 2nd dot, the operand 1 will have kWidth set to 8, which makes it neccessary to use in-warp shuffling for  the layout conversion from #mma to #dotOp for operand 0.
This PR forces the 2nd dot to use kWidth = 4 for both operands and use single rated mfma instructions. The changes are reflected in the tests:
- 1 test in accelerate-amd-matmul-chain-dot.mlir to make sure we set kWidth = 4 for the 2nd dot of chain-dot kernels.
- 4 new tests in mfma-double-rate.mlir to make sure we generate single rated mfma when kWidth=4
- new tests in LinearLayoutConversionsTest to make sure …
=> [AMD] [gfx950] [FA-f16] use single rated mfma for 2nd dot

python/test/unit/language/test_matmul.py
This fixes test failures on AMD gfx950 architecture.
=> [TEST] Check ttng.tc_gen5_mma only for CUDA

bench/tests/test_swiglu.py, bench/triton_bench/numerics.py, bench/triton_bench/swiglu.py
Optimizations, and add support for dynamic number of rows. Existing code was written as a while loop so couldn't pipeline well. By changing to a for loop and explicitly setting num_stages, we increase bandwidth utilization. Dynamic rows will be needed for simulated e sharding.
on H100:
```
-                    "name": "_swiglu_bf16xbf16_8x128 [M = 8192, N = 4096]",
+                    "name": "_swiglu_bf16xbf16_16x128 [M = 8192, N = 4096]",
-                    "time (ns)": 8352191
+                    "time (ns)": 6544317
--
-                    "name": "_swiglu_fp8e4nvxfp8e4nv_8x128 [M = 8192, N = 4096]",
+                    "name": "_swiglu_fp8e4nvxfp8e4nv_32x128 [M = 8192, N = 4096]",
-                    "time (ns)": 8803373
+                    "time (ns)": 4203423
--
- …
```
=> [BENCH] swiglu improvements

third_party/amd/backend/driver.py
Per [the pytorch docs](https://github.com/pytorch/pytorch/blob/21b0ef520d651ed67f6978ac37c8a8a4093819ee/docs/source/notes/hip.rst#checking-for-hip) we should be checking `torch.cuda.is_available()` to verify the driver is active. This is also consistent with the [Nvidia backend](https://github.com/njriasan/triton/blob/e5e5f573a203747f1421944b8fd8cf77dbad83f7/third_party/nvidia/backend/driver.py#L657).
=> [AMD] [BACKEND] Update the is_active check to comply with PyTorch docs 

test/Conversion/tritongpu_to_llvm_blackwell.mlir, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TensorMemoryToLLVM.cpp
In this case, all 8 warps read 1 block at a time, rather than 1 block per warp group.
=> [Blackwell] Fix TMEM lowering when splitM layout has more than 1 block

python/test/unit/runtime/test_autotuner.py, python/triton/runtime/autotuner.py
Fixes https://github.com/triton-lang/triton/issues/6150.
When running on a CPU host, `triton.autotune()` throws an error:
```
RuntimeError: 0 active drivers ([]). There should only be one.
```
This issue was introduced by https://github.com/triton-lang/triton/pull/4496,
which forces the caller to specify `do_bench`. But this may not be easy in a
large codebase.
Default `do_bench` to `triton.testing.do_bench` when there's no GPU. Add a
unit test.
=> [autotuner] Add default do_bench for CPU hosts

python/triton/_internal_testing.py
`'gfx9' in ('gfx950')` would return true per Python syntax. So
fixing it to use exact string match to be clear.
Along the way removed `gfx940` and `gfx941` which was deprecated
and simplified the checks a bit.
=> [AMD] Fix gfx* target check in testing utility

include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td, lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp
This PR is causing a performance regression in internal benchmarks.
OAI Ref: https://buildkite.com/openai-mono/monorepo/builds/1326903#01966844-1afe-481b-a090-42aced175df9
=> Revert "[TritonNVIDIAGPU] Add missing memory effects to some ops (#6518)

python/test/unit/language/test_core.py, third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/FMA.cpp, third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp
This enables the basic usage of bf16 dot2 instruction in CDNA4 arch. 
Calculates 32-bit sum of 16-bit multiplications.
=> [AMD][BACKEND] Enable bf16 dot2 in AMD backend pass

bench/triton_bench/matmul_ogs_details/_ptma_matmul_ogs.py, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/LoadMMASpecialization.cpp
<git-pr-chain>
[Bench][Blackwell] Enable warp specialization for fp8 x mxfp4 bench
This pr-chain brings the performance of the mixed fp8 x mxfp4 MOE kernel
on par with fp8 x fp8 kernel:
* About 10% slower in the dense benchmarks
* About 10% faster in the llama4 benchmarks
Applies a bug fix for padded scale loads in fp8 x mxfp4 mode
ensuring TMA load requirements are met when using the unpacked
fp4 (padded) layout. This only occurs after enabling warp
specialization.
1. #6535
1. 👉 #6537 👈 **YOU ARE HERE**
=> [Bench][Blackwell] Fix warp specialization for fp8 x mxfp4 bench

include/triton/Dialect/TritonGPU/Transforms/PipeliningUtility.h, include/triton/Dialect/TritonGPU/Transforms/Utility.h, lib/Dialect/TritonGPU/Transforms/Pipeliner/LowerLoops.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/PipeliningUtility.cpp, lib/Dialect/TritonGPU/Transforms/Utility.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/TMALowering.cpp
This helper replaces a tensor with the result of `LocalLoadOp` and looks forward at any downstream `LocalAllocOp` users and tries to elide the allocation if the encodings match.
By using it in TMALowering, we can now avoid taking a round trip through registers before using the loaded value e.g. as an wgmma/tcgen05.mma operand.
=> [BACKEND] Factor out replaceUsesWithLocalLoad and use in TMALowering

python/triton/backends/driver.py, third_party/amd/backend/driver.py, third_party/nvidia/backend/driver.py
This is an alternative of #6589, and related to #4809 #6000
We add the Python ABI tag to the filename of each cached C binary, to avoid linking errors when the user switches the Python version.
According to the [comment](https://github.com/triton-lang/triton/pull/4809#issuecomment-2376984522), I move the function `platform_key` to `triton.backends.driver`. The AMD-specific behavior can be implemented on top of this PR if needed.
I think `sysconfig.get_config_var('EXT_SUFFIX')` is the proper way to get the ABI tag. It supports Python 3.9 to 3.13, both Linux and Windows, and many kinds of Python distributions including the embedded and the standalone builds. It also distinguishes cp313 and cp313t ([free-threaded](https://docs.python.org/3/howto/free-threading-python.html)), which we may …
=> Add Python ABI tag to the filename of cached C binary

python/triton/runtime/autotuner.py
Within Meta `triton.Config`s are often pickled (using `torch.package`), which creates some headaches if fields are added or removed.  Adding a `__setstate__` method lets us ensure that a `Config` can be unpickled with an internally-consistent state.
=> [frontend] Add a __setstate__ for Config

python/tutorials/10-block-scaled-matmul.py, third_party/nvidia/backend/driver.py
For FP4 padded format, we need to pass double the shape in the last dimension to represent the number of fp4 elements instead of uint8 elements. However, we were doing this update inplace on the `TensorDescriptor` arugment so the last dim would double in size every time you reused the same descriptor.
Also fixed the mxfp benchmark to leave argument initialization out of the recorded trace.
=> [TMA] Avoid in-place modification of TensorDescriptor arguments

lib/Dialect/TritonGPU/Transforms/Pipeliner/AssignLatencies.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/LowerLoops.cpp
This change enables MMAv5 pipelining for loops with 2 dot ops. This unblocks pipelining of attention forward kernels. MMAv5 pipelining for attention backward (which have more than 2 dots) is still disabled, as there are still cases that regress in performance.
=> [BE][PIPELINE] Enabling mmav5 pipelining for 2 dots in the loop by default

python/test/unit/language/test_core.py, python/triton/language/core.py
`t[None:None]` and `t[None:None:None]` mean the same thing as `t[:]` and `t[::]`, but the former are not literally `None`, but rather constexpr values of `None`.
`_unwrap_if_constexpr` seems to be for this sort of support, and was implemented manually for the `t[None]` case already.
=> Support `None` in getitem slices

python/test/unit/runtime/test_autotuner.py, python/triton/compiler/compiler.py, python/triton/runtime/errors.py, third_party/amd/backend/compiler.py, third_party/amd/backend/driver.c, third_party/nvidia/backend/driver.c
Expose CU_FUNC_ATTRIBUTE_MAX_THREADS_PER_BLOCK to Python as `n_threads` during kernel loading. This allows runtime to check whether num_warps * 32 exceeds the kernel's thread block limit,  making autotune more robust by skipping invalid configs with a clear `OutOfResources` error.
Before this change, the following autotune example failed immediately with RuntimeError: `RuntimeError: Triton Error [CUDA]: invalid argument`:
```python
import torch
import triton
def test_exceed_threads(device):
x = torch.empty(1024, device=device, dtype=torch.float32)
y = torch.empty_like(x)
output = torch.empty_like(x)
configs = [
triton.Config({}, num_warps=128),
triton.Config({}, num_warps=4),
]
@triton.autotune(configs=configs, key=['BLOCK_SIZE'])
@triton.jit
def …
```
=> Expose max_threads_per_block to avoid launch failures and improve autotune robustness

python/test/unit/language/test_warp_specialization.py
Fixes gfx11 internal CI.
disabled:
- test_warp_specialize_tma_matmul
- test_warp_specialize_tma_matmul_persistent
=> [AMD] Disable warp specialization tests for AMD target

python/test/unit/conftest.py, python/test/unit/test_config.py, python/triton/config.py
In https://github.com/triton-lang/triton/pull/6467 I didn't expose `TRITON_HOME` as its own knob, which meant if you wanted to programmatically override it you'd need to override all the `cache.*dir` knobs directly. I've exposed a new `cache.home_dir` knob so that you can programmatically customize all those directories at once.
=> [python][config] Add cache.home_dir config

lib/Dialect/TritonNvidiaGPU/Transforms/TensorMemoryAllocation.cpp, test/TritonNvidiaGPU/test_tensor_memory_allocation.mlir
Prior to the fix, getAlloc will hit an infinite loop. This patch also handles the case where tmemDesc comes from argument of warp_specialize.
=> Fix TensorMemoryAllocation to correctly implement getAlloc

include/triton/Dialect/Triton/IR/TritonOps.td
This fixes bitwise internal determinism tests.
=> [Dialect] Mark Join, Split, and Cat as non speculatable

test/TritonGPU/loop-pipeline-hip.mlir, third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp
Changes the scheduling to place `AsyncWait` in a separate cluster at the start of the schedule if `GlobalLoadStage != LocalLoadStage`. This allows us to reorder the `AsyncCopy` and `LocalLoads` more freely because the `AsyncWait` will always be before both `Ops`.
=> [AMD][BACKEND] Schedule `AsyncWait` in front of `AsyncCopy` and `LocalLoad`

python/triton/_utils.py
Firstly, let me know if I should include the 'new contributors' declaration still-- I can re-add it to this PR and keep it in future PRs, otherwise I'll start eliding it in my PR summary from here on out.
A while ago I brought up the idea of adding typehints to triton. I started following through on that ambition in https://github.com/triton-lang/triton/pull/6467, and want to continue the endeavor here.
I plan to keep taking the 'leafiest' modules and adding typehinting to them. In order to validate types locally I'm using mypy with an lsp connection to neovim. One there's a good amount of typehinting I can go through and add `ignore` statements everywhere there's an error so that we can get typechecking in our pre-commit. For now I'll address type errors ad-hoc as I see them.
=> [python][typehint] Simplify find_paths_if and add typehints to _utils

test/Analysis/test-membar-ttng.mlir, test/Analysis/test-membar.mlir
Splitting the tests allows us to reuse the common tests when adding a custom filter function to `Membar` analysis in the `amdgpu` backend in a follow-up PR.
=> [NFC] Split Membar tests into common and ttng specific files

MANIFEST.in, setup.py
Disable the new backend installing logic for external plugins, since `package_dir` does not accept absolute paths.  Instead, use a hybrid approach where in-tree backends are installed using the new logic and external backends are symlinked.  This implies that source distributions cannot be created when using external plugins.
Fixes #6612
------
=> Use symlinks for external plugins to fix TRITON_PLUGIN_DIRS

include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td, lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp
<git-pr-chain>
[RELAND][TritonNVIDIAGPU] Add missing memory effects to some ops (#6518)
This reverts commit fbfa627c3adadc8e83f56551150e0f138aaddd5a.
It turns out my bisect was junk because the expected values were being
updated in-place after running the test.
1. 👉 #6644 👈 **YOU ARE HERE**
=> [RELAND][TritonNVIDIAGPU] Add missing memory effects to some ops (#6518)

include/triton/Tools/LinearLayout.h, lib/Dialect/TritonGPU/IR/Dialect.cpp
There is a bug in layout inference. Will send a fix in a bit.
Reverting to keep main clean
This reverts commit 2cca24be0350f53770d53536d907d3a263f40f34.
=> Revert "[LAYOUTS] Use divideLeft on layout inference (#6577)"

lib/Dialect/TritonGPU/Transforms/Pipeliner/AssignLatencies.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/LowerLoops.cpp
This reverts #6599 which caused test failures in our internal workloads.
OAI Ref: https://buildkite.com/organizations/openai-mono/pipelines/monorepo/builds/1350297/jobs/0196866c-f642-4feb-99cd-3cb7653c45cf/log
=> Revert "[BE][PIPELINE] Enabling mmav5 pipelining for 2 dots in the loop by default (#6599)"

README.md
https://github.com/triton-lang/triton/pull/6381 updated some building and doc but didn't fix the command to find the proper `compile_commands.json`. `python/build` would contain the old one if user has previously built the project in `./python`, which would not work now, since we now build the project at dir `.`
=> Update README.md for vscode intellisense

bin/RegisterTritonDialects.h, test/Analysis/test-membar.mlir, test/Conversion/amd/amdgpu_membar.mlir, third_party/amd/include/TritonAMDGPUToLLVM/MembarUtility.h, third_party/amd/lib/TritonAMDGPUToLLVM/CMakeLists.txt, third_party/amd/lib/TritonAMDGPUToLLVM/MembarUtility.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/TritonGPUToLLVM.cpp, third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp, third_party/amd/test/lib/Analysis/CMakeLists.txt, third_party/amd/test/lib/Analysis/TestAMDGPUMembar.cpp
`Membar` does not deduce that two shared memory sub views do not alias if they are from the same allocation. When pipelining we therefore get barriers between the `LocalLoad` and the prefetch loads (`AsyncCopy/BufferLoadToLocal`) because they read/write into sub views of the same allocation.
This PR adds a filter function to Membar analysis to avoid those barriers by ignoring the dependency of `LocalLoad` if it consumes an `AsyncToken` from an `AsyncWait`. For such cases the barrier of the `AsyncWait` is enough to correctly synchronize the access.
=> [AMD][BACKEND] Filter barriers in `Membar` between `LocalLoads` and `AsyncCopy` when pipelining

python/test/unit/language/test_core.py
kpack=1 is not relevant and will be rejected by the compiler, disable it in the test.
=> [TEST][AMD] Only check kpack=1 on the cdna4

test/Analysis/test-alignment.mlir
Unless I'm doing something wrong when running `lit test`, I don't think test-alignment.mlir was actually checking any of the remarks.
There were two issues:
1. `-verify-diagnostics` is not added to the triton-opt run command, so the `expected-remark` comments were not executing.
2. `expected-remarks` was misspelled everywhere in this file, instead written as `expeted-remarks`.
This PR fixes the typo and adds `-verify-diagnostics=only-expected` (so that it checks for expected remarks, doesn't _require_ an expected remark for all the remarks that are actually emitted), and it also removes all the failing expected-remarks (replacing them with TODOs). For ease of review, the PR is split into two commits - one which renames `expeted-remark -> expected-remark`, and one which replaces …
=> [TEST] Enable test-alignment.mlir checks & remove failing checks

lib/Dialect/TritonGPU/IR/Dialect.cpp, lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp, test/TritonGPU/combine.mlir
The previous comments regarding divideLeft were wrong. We now explain
the logic properly and we lift an artificial restriction previously
imposed by `getContigPerThread`
=> [LAYOUTS] Improve split inference and fix comments

include/triton/Dialect/TritonGPU/IR/Dialect.h, include/triton/Dialect/TritonGPU/IR/Traits.h, include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td, include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td, include/triton/Tools/LayoutUtils.h, lib/Analysis/Alias.cpp, lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp, lib/Dialect/TritonGPU/IR/Dialect.cpp, lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp, lib/Dialect/TritonGPU/IR/Ops.cpp, lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/LowerLoops.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/MMAv5PipelineUtility.cpp, lib/Tools/LayoutUtils.cpp, python/test/unit/cuda/test_tensor_descriptor.py, test/TritonGPU/dot-operands.mlir, unittest/Dialect/TritonGPU/LinearLayoutConversionsTest.cpp
Adds an op to reshape memdesc types. This allows to support cases where we want to reshape a value loaded from global to shared without going through register.
This also rework the representation of nvmma layout when the memdesc is greater than 2.
We pick a convention that allows us to reshape the non-contiguous dimension of a memdesc.
=> [BACKEND] Support memdesc_reshape to allow different HBM layout for mmav5

include/triton/Dialect/TritonGPU/IR/LinearLayoutConversions.h, lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp, lib/Tools/LinearLayout.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp, unittest/Tools/LinearLayoutTest.cpp
<git-pr-chain>
1. [NFC][Layouts] Cleanup leading offset references + exponential iteration
This does two things, firstly I cleanup outdated references to
"LeadingOffset" in favour of NVMMA and Swizzled encodings.
I also clean up iteration in log space + exponentiation e.g.
```
for (int logI = 0; logI < Log2_32(size); logI++) {
int i = 1 << logI;
}
```
to exponential iteration
```
for (int i = 1; i < size; i *= 2) {
}
```
1. Cleanup new loop
1. 👉 #6665 👈 **YOU ARE HERE**
=> [NFC][Layouts] Cleanup leading offset references + exponential iteration

include/triton/Dialect/TritonGPU/Transforms/Utility.h, test/TritonNvidiaGPU/tma_lowering.mlir
Deleting the alloc op too early maay invalidate the builder insert point. Delay the clean up of the ops.
=> [BACKEND] Fix tma lowering crash due to wrong insert point

test/lit.cfg.py
Internally at Meta we adapt the cmake setup to work with buck. As part of that adaption we rely on this lit cfg file, and in particular rely on the set of tools to be encompassing of all tools that are used by the lit tests. A few tests use `mlir-translate` (see e.g. [`Conversion/gather_to_llvm.mlir`](https://github.com/triton-lang/triton/blob/main/test/Conversion/gather_to_llvm.mlir#L1)), so we need `mlir-translate` in the declared list of tools in the lit cfg file.
N.B. IIUC the cmake setup works because we update `$PATH` to include where `mlir-translate` sits (and buck is a bit persnickety when it comes to `$PATH`)
=> [lit][cfg] Declare mlir-translate in lit config

python/triton/knobs.py
When calling reset (which is implicitly done by `fresh_knobs`) the base_knobs class invokes `knobs`, which in turn invokes the `getattr` implementation. The base implementation for this calls `self.transform`, which is problematic when running these tests on an AMD machine because the `env_nvidia_tool` will call transform and may produce a RuntimeError.
This updates reset to just get the keys from `knob_descriptors`, which avoids this issue.
=> Avoid calling self.knobs during reset

third_party/nvidia/backend/compiler.py
TMA lowering may now remove so unnecessary allocs.
=> Reorder tma lowering pass after fence insertion.

lib/Dialect/TritonNvidiaGPU/Transforms/TensorMemoryAllocation.cpp, test/TritonNvidiaGPU/test_tensor_memory_allocation.mlir
Split from https://github.com/triton-lang/triton/pull/6660
=> [Blackwell] Fix TMEM allocation when captured buffer is not a subview

test/Conversion/tritongpu_to_llvm_blackwell.mlir, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TensorMemoryToLLVM.cpp
The goal of the heuristic here is to never use more than half of the available registers for a TMEM instruction, since each instruction requires all registers to be live at once.
The register use of each message was being calculated incorrectly, sometimes resulting in a larger or smaller narrowing factor. This PR fixes that. It also fixes `getContextualMaxNReg` to return values other than 256...
Also, PTXAS will fail compilation if it detects that TMEM instruction whose register usage plus a fudge factor (seem to be 18 regs) is larger than the `maxnreg` set on the module, not based on dynamic reallocation, so that has to be taken into account.
=> [Blackwell] Fix TMEM message size selection heuristic

test/Conversion/tritongpu_to_llvm_blackwell.mlir, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TensorMemoryToLLVM.cpp
Based on feedback from @csullivan
The heuristic is also supposed to avoid using two `.x128` messages when the total workload size is 256 (elements per thread). Account for that and the reg size of each individual message.
=> [Blackwell] Fix the TMEM message heuristic

.github/workflows/documentation.yml, docs/conf.py, python/tutorials/08-grouped-gemm.py
1. Change the default build directory from `python/` to the root of triton.
2. Update on the CI runners.
3. Increase the relative tolerance of 08-group-gemm tutorial due to its failure on some GPUs using mmav2.
Tested https://github.com/triton-lang/triton/actions/runs/14816446953
=> [DOC] Fix documentation pipeline

python/test/unit/conftest.py
With the new knobs module we have a more pythonic way to setup the cache. Other than being 'pythonic', switching to use knobs ensures the fresh cache will override any previously set cache path (e.g. if you have generic initialization logic which sets up these knobs, which we do have at Meta).
=> [pytest] Use knobs to setup fresh cache for testing

.gitignore, Makefile, scripts/build-llvm-project.sh
I've found using the make commands an absolute delight, but are missing support for building LLVM from source, hence this PR.
In the future we might consider moving the logic in the LLVM workflow into the new script (so that it's KISS to repro a workflow build locally), but that's probably not necessary for now.
cc @plotfi whose build script was a huge inspiration for this
=> [workflow] Add dev-install-llvm target for building LLVM from source

bench/tests/test_swiglu.py, bench/triton_bench/swiglu.py, bench/triton_bench/swiglu_details/_swiglu.py
TMA is no longer needed in this kernel after the convert layout cost model added in https://github.com/triton-lang/triton/pull/6699
Also fix test_swiglu.py. It broke after https://github.com/triton-lang/triton/pull/6703
=> [BENCH] Remove TMA workaround in swiglu

lib/Conversion/TritonGPUToLLVM/AllocateWarpGroups.cpp, lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/LoadMMASpecialization.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/OptimizePartitionWarps.cpp, test/Conversion/allocate_warp_groups.mlir, test/Conversion/triton_to_tritongpu.mlir, test/Conversion/triton_to_tritongpu_4_warps.mlir, test/Conversion/tritongpu_to_llvm.mlir, test/Conversion/warp_specialize_to_llvm.mlir, test/TritonGPU/automatic-warp-specialization.mlir, test/TritonGPU/load-mma-specialization.mlir, test/TritonGPU/optimize-partition-warps.mlir, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ConvertWarpSpecializeToLLVM.cpp
This PR generally improves how the compiler handles dynamic register reallocation for warp specialization.
* Codegen generates `setmaxnreg` both at the entry and exit of the partition regions, even when the number of registers does not change. This somehow makes `ptxas` behave much better, allowing the registers allocated to the load and MMA partitions to drop to `24` as they should be. This should improve register pressure across the board for warp specialized kernels.
* The maximum number of warpgroups is computed across the whole program and each `ttg.warp_specialize` is padded to it. This ensures all warps are always present to surrender registers. This primarily improves the layering between partitioning in the middle end (no longer need the "extra empty warp" hack).
* Handle TMEM …
=> [Backend] Improve how dynamic register reallocation is implemented

python/test/unit/language/test_core.py, python/triton/language/semantic.py
So far we have been checking for pre-defined list of unsupported types, missing that fp8 is generally also not supported in atomic operations.
=> [FE] Error when trying to use atomics with any type smaller than 16b

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td, lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp, lib/Dialect/TritonGPU/IR/Dialect.cpp, lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/OptimizeDescriptorEncoding.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/TMAUtilities.cpp, test/Analysis/test-allocation.mlir, test/Conversion/tritongpu_to_llvm.mlir
<git-pr-chain>
[TMA] Use NVMMA to represent unswizzled case
Currently this is used to ensure the smem allocation is properly aligned. Soon this will also be needed so we can break up the unswizzled case into multiple tma messages to overcome tma's 256 maximum block dimension size.
Closes #6723
1. 👉 #6725 👈 **YOU ARE HERE**
=> [TMA] Use NVMMA to represent unswizzled case

test/Conversion/amd/async-ops-alias-scopes.mlir, test/Conversion/amd/async_ops_to_llvm.mlir, test/Conversion/amd/async_ops_to_llvm_invalid.mlir, test/Conversion/amd/buffer_load_to_local_to_llvm.mlir, test/TritonGPU/amd/amd-coalesce-async-copy.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp
Direct-to-lds loads for smaller than 4 bytes extend their loaded values to 4 bytes before storing to shared memory. Adjusted lit tests from f16 to f32 so they produce >= 4 byte loads.
This is a NFC change because the streampipeliner will pipeline those loads via registers, but we should ensure we do not produce incorrect assembly if that changes in the future.
=> [AMD][BACKEND] Reject AsyncCopyGlobalToLocal/BufferLoadToLocal for less than 4 bytes

include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td, lib/Dialect/TritonGPU/IR/Ops.cpp, lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp, test/TritonGPU/WGMMAPrefetch.mlir, test/TritonGPU/amd/amd-reorder-instructions.mlir, test/TritonGPU/dot-operands.mlir, test/TritonGPU/pipeline-assign-latencies.mlir, test/TritonNvidiaGPU/invalid.mlir, test/TritonNvidiaGPU/test_tensor_memory_allocation.mlir
For both tmem and shared allocs, check that the element types match, the shapes match, and the alloc shape is the same as the initial memdesc shape.
=> [DIALECT] Tighten verifiers of alloc ops

include/triton/Dialect/Triton/IR/TritonOpInterfaces.td
The missing namespace was causing ambiguity issues.
=> [NFC] added missing namespace

include/triton/Tools/Sys/GetEnv.hpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/AssignLatencies.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/LowerLoops.cpp, test/TritonGPU/pipeline-assign-latencies.mlir, test/TritonGPU/pipeline-lower-loop.mlir
Loops with more than 1 dot operation were excluded from mmav5 pipelining up until now. Enable it by default.
=> [PIPELINE] Turning on mmav5 pipelining for all the loops by default

bench/tests/test_swiglu.py, bench/triton_bench/swiglu.py, bench/triton_bench/swiglu_details/_swiglu.py
bench_mlp.py was wrong since it did not pass num_experts to the swiglu. This arg defaulted to zero, causing the kernel to load the wrong slot in the expert data.
Fix this, and remove the num_experts arg so this is more foolproof. We can get the number of experts from the routing data.
=> [BENCH] fix swiglu routing and simplify args

include/triton/Dialect/TritonGPU/Transforms/MMAv5PipelineUtility.h, include/triton/Dialect/TritonGPU/Transforms/PipeliningUtility.h, include/triton/Dialect/TritonGPU/Transforms/Schedule.h, include/triton/Tools/Sys/GetEnv.hpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/AssignLatencies.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/LowerLoops.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/MMAv5PipelineUtility.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/PipeliningUtility.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/Schedule.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/ScheduleLoops.cpp, python/test/unit/language/test_pipeliner.py, test/TritonGPU/loop-pipeline-blackwell.mlir, test/TritonGPU/pipeline-assign-latencies.mlir, test/TritonGPU/pipeline-lower-loop.mlir, test/TritonGPU/pipeline-schedule-loop.mlir
Revert "[PIPELINE] Fix mmav5 `wait_barrier` stage for acc loads before the mma (#6613)"
This reverts commit 5b7b86ae500276dab9460dbd614462450e0c45db.
Revert "[PIPELINE] Turning on mmav5 pipelining for all the loops by default (#6732)"
This reverts commit a58ca0e13aad2fd00e025a14461fd41e24ccdfeb.
=> Revert #6613 and #6732

include/triton/Conversion/TritonGPUToLLVM/Utility.h
After discussion with @Jokeren and @ThomasRaoux removing the check for `rank == 1` from check for `noSwizzling` as not technically correct.
=> [BE] Removing check for rank==1 from previous PR

include/triton/Conversion/TritonGPUToLLVM/Utility.h, python/test/unit/language/test_core.py, python/triton/language/semantic.py, test/TritonGPU/amd/amd-canonicalize-pointers.mlir, test/TritonNvidiaGPU/bf16-atomics.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp
This PR adds BF16 support for atomics, which are less precise but cheaper
BF16 accumulators have proven to be useful in the context of Split-K's where it is necessary to have cheaper atomic accumulation across two SMs (where within an SM the accumulation is handled with more precision).
BF16 Atomics are also needed some of the following AMD related work:
* AMD buffer atomics (ie BufferAtomicRMWOp)
* There is also a for a path to add unit tests for bf16 atomics for AMD's backend
BF16 atomics across A100, H100 and MI300 at: https://godbolt.org/z/jW3EMbxrG
@bertmaher @SamGinzburg @davidberard98 
=> [BACKEND] BF16 atomic_add support

python/test/unit/runtime/test_compilation_listener.py, python/triton/knobs.py
I didn't catch this on https://github.com/triton-lang/triton/pull/6364 -- `Any` is fine, but we know the values are `str` from [`get_group`](https://github.com/triton-lang/triton/blob/b73d59597370a5ea7bd084d0f047516b029d9f4e/python/triton/runtime/cache.py#L26)
=> [typehint][knobs] Specify values in metadata_group as str

include/triton/Dialect/Triton/IR/TritonDialect.td, include/triton/Dialect/TritonGPU/Transforms/MMAv5PipelineUtility.h, include/triton/Dialect/TritonGPU/Transforms/PipeliningUtility.h, include/triton/Dialect/TritonGPU/Transforms/Schedule.h, include/triton/Tools/Sys/GetEnv.hpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/AssignLatencies.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/LowerLoops.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/MMAv5PipelineUtility.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/PipeliningUtility.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/Schedule.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/ScheduleLoops.cpp, python/test/unit/language/test_pipeliner.py, test/TritonGPU/loop-pipeline-blackwell.mlir, test/TritonGPU/pipeline-assign-latencies.mlir, test/TritonGPU/pipeline-lower-loop.mlir, test/TritonGPU/pipeline-schedule-loop.mlir
Previous attempt at reworking `ttng.wait_barrier` placement (https://github.com/triton-lang/triton/pull/6613) and enabling mmav5 (https://github.com/triton-lang/triton/pull/6732) was overly conservative regarding overlapping mmav5 ops with itself in cases where the conditional `tmem_load` was placed in the same stage as the mma op. We can still overlap such cases, we just need to have wait added to the conditional block with `tmem_load`.
This PR addresses this by adding second "latency" kind to the mma op - `tt.self_latency` that expresses what stage should the `wait_barrier` be pushed to.
It also paves the way for enabling the user for independently controlling what stage the users of the mma should be placed (controlling tmem buffer count) and mma self-overlapping.
=> [PIPELINE] Re-enabling mmav5 pipelining after fixing some performance regressions

lib/Dialect/TritonGPU/Transforms/WarpSpecialization/LoadMMASpecialization.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/PartitionLoops.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/RewritePartitionDependencies.cpp, test/TritonGPU/load-mma-specialization.mlir, test/TritonGPU/partition-loops.mlir, test/TritonGPU/rewrite-partition-dependencies.mlir
Ops that have no backward dependency on any other partition are expected to be left in the root partition because it's easier to let later passes deal with rematerialization than for higher-level passes to duplicate and assign explicit stages.
Accidentally assigning partitions to these ops will cause later passes to fail. This also changes those passes to a hard fail because the code generated by WS can be invalid if it isn't split. (The code expects to be run concurrently).
=> [Warp Specialization] Fix accidentally assigning ops to default partition

third_party/amd/backend/driver.py, third_party/nvidia/backend/driver.py
`PyObject_CallObject` returns new reference: https://docs.python.org/3/c-api/call.html#c.PyObject_CallObject.
=> Use `Py_DECREF` after `PyObject_CallObject` call

python/test/unit/language/test_core.py, python/triton/compiler/code_generator.py, python/triton/language/core.py
This commit contains the following frontend enhancements:
1. `tl.reshape(x, [])` works for single-element tensors and returns a scalar. Previously, it was very difficult to produce scalars, and `tl.reshape(x, [])` would throw an error.
2. `if`-statements correctly throw frontend errors if used on multiple-element tensors, and if a multidimensional single-element tensor is provided then we raise a warning (recommending `tl.reshape(x, [])`) and unsplat it to a scalar. Before, the backend would crash in both cases with an inscrutable MLIR error.
3. chained boolean operations such as `(P or Q or R)` are supported, whereas before they would throw frontend errors.
4. in boolean operations, operands with constexpr truth values are handled specially:
- if we are in a conjunction and encounter a …
=> [FRONTEND] Better handling of boolean operators and scalars

bin/RegisterTritonDialects.h, include/triton/Dialect/Triton/Transforms/Passes.h, include/triton/Dialect/Triton/Transforms/Passes.td, lib/Dialect/Triton/Transforms/Combine.cpp, lib/Dialect/Triton/Transforms/LoopInvariantCodeMotion.cpp, lib/Dialect/Triton/Transforms/LoopUnroll.cpp, lib/Dialect/Triton/Transforms/ReorderBroadcast.cpp, lib/Dialect/Triton/Transforms/RewriteTensorPointer.cpp, python/src/passes.cc
Continuation of https://github.com/triton-lang/triton/pull/3971
=> [NFC] Remove uses of deprecated `GEN_PASS_CLASSES` for `Triton/Transforms`

test/lib/Analysis/CMakeLists.txt, test/lib/Analysis/TestAlias.cpp, test/lib/Analysis/TestAxisInfo.cpp, test/lib/Analysis/TestMembar.cpp
New link command: 
```bash
triton/build/cmake.linux-x86_64-cpython-3.10$ time (cmake -E rm -f test/lib/Analysis/libTritonTestAnalysis.a && /usr/bin/ar qc test/lib/Analysis/libTritonTestAnalysis.a  test/lib/Analysis/CMakeFiles/obj.TritonTestAnalysis.dir/TestAlias.cpp.o test/lib/Analysis/CMakeFiles/obj.TritonTestAnalysis.dir/TestAxisInfo.cpp.o test/lib/Analysis/CMakeFiles/obj.TritonTestAnalysis.dir/TestAllocation.cpp.o test/lib/Analysis/CMakeFiles/obj.TritonTestAnalysis.dir/TestMembar.cpp.o lib/Analysis/CMakeFiles/TritonAnalysis.dir/AxisInfo.cpp.o lib/Analysis/CMakeFiles/TritonAnalysis.dir/Allocation.cpp.o lib/Analysis/CMakeFiles/TritonAnalysis.dir/Membar.cpp.o lib/Analysis/CMakeFiles/TritonAnalysis.dir/Alias.cpp.o lib/Analysis/CMakeFiles/TritonAnalysis.dir/Utility.cpp.o …
```
=> Speedup `TritonTestAnalysis` mlir library linking

third_party/proton/common/include/TraceDataIO/ByteSpan.h, third_party/proton/common/include/TraceDataIO/CircularLayoutParser.h, third_party/proton/common/include/TraceDataIO/EntryDecoder.h, third_party/proton/common/include/TraceDataIO/Parser.h, third_party/proton/common/include/TraceDataIO/TraceWriter.h, third_party/proton/common/lib/TraceDataIO/CMakeLists.txt, third_party/proton/common/lib/TraceDataIO/TraceWriter.cpp, third_party/proton/test/unittest/TraceDataIO/CMakeLists.txt, third_party/proton/test/unittest/TraceDataIO/ChromeTraceWriterTest.cpp
This PR adds the trace writer utilities for the chrome tracing. Specifically, it supports dumping a json trace in chrome trace format for a single stream with multiple kernels. Each kernels has a constant gap `kKernelTimeGap`. Due to the limitation of chrome trace, each pid line is a CTA triplet (kernel name, Processor ID, CTA ID). Inside PID,  each TID is a portion of warp events recorded. Here we say portion because we apply a line splitting to avoid chrome tracing corrupts overlapping events. Any overlapping events in the same warp would be placed in a separate TID line. In this implementation, each CTA applies an independent start event offset. As a result, it is only safe to compare events within the same CTA.
=> [PROTON-DEV] Chrome Trace Writer

README.md
The current README instructions for enabling Blackwell support suggest building PyTorch `2.6.0-rc9` from source with `TORCH_CUDA_ARCH_LIST=Blackwell`.
However, when following these steps, the resulting PyTorch installation did not correctly recognize all Blackwell architectures. For instance, when targeting an sm_120 (NVIDIA 5090) GPU, the available architectures were limited:
```
>>> import torch
>>> print(torch.cuda.get_arch_list())
['sm_100']
```
This PR removes the Blackwell installation process section since torch 2.7.0 is released and supports all the blackwell architectures. …
=> Docs: Update PyTorch installation for Blackwell 

cmake/AddTritonUnitTest.cmake, third_party/amd/unittest/Conversion/CMakeLists.txt, third_party/nvidia/unittest/Conversion/TritonGPUToLLVM/CMakeLists.txt, unittest/Analysis/CMakeLists.txt, unittest/Dialect/TritonGPU/CMakeLists.txt, unittest/Dialect/TritonGPU/DialectTest.cpp, unittest/Dialect/TritonGPU/SwizzleTest.cpp
Comparison of the sizes of build artifacts:
Old:
```bash
ls build/cmake.linux-x86_64-cpython-3.10/unittest/Dialect/TritonGPU/ -lh
total 1.8G
drwxr-sr-x 6 jovyan users 4.0K May 11 13:29  CMakeFiles
-rw-r--r-- 1 jovyan users 3.3K May 12 21:16  CTestTestfile.cmake
-rwxr-xr-x 1 jovyan users 440M May 12 21:18  Dialect
-rw-r--r-- 1 jovyan users  387 May 12 21:16 'Dialect[1]_include.cmake'
-rw-r--r-- 1 jovyan users  18K May 12 21:18 'Dialect[1]_tests.cmake'
-rwxr-xr-x 1 jovyan users 438M May 12 21:18  DumpLayoutTest
-rw-r--r-- 1 jovyan users  415 May 12 21:16 'DumpLayoutTest[1]_include.cmake'
-rw-r--r-- 1 jovyan users 2.3K May 12 21:18 'DumpLayoutTest[1]_tests.cmake'
-rwxr-xr-x 1 jovyan users 446M May 12 21:18  LinearLayoutConversions
-rw-r--r-- 1 jovyan users  451 May 12 21:16 …
```
=> [BUILD] Speedup unittests linking

lib/Conversion/TritonGPUToLLVM/AllocateWarpGroups.cpp, test/Conversion/allocate_warp_groups.mlir
Previously, register reallocation occurs only if the worker partitions have a positive register deficiency, which redistributes the extra registers to the default partition. This PR enables worker partitions to steal from the default partition, which enables, for example, two softmax partitions to go up to 192 registers by stealing from the default partition.
=> [Warp Specialization] Allow worker partitions to steal registers from the default partition

include/triton/Dialect/TritonGPU/Transforms/PipeliningUtility.h, lib/Dialect/TritonGPU/Transforms/Pipeliner/PipeliningUtility.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/PartitionLoops.cpp, test/TritonGPU/partition-loops.mlir
This is to support forward attention when the row maxes for each subtile need to be passed from the first pair of softmax partitions to the second pair.
=> [Warp Specialization] Add support for tensor captures into partitioned loops

python/triton/runtime/autotuner.py
When `TRITON_PRINT_AUTOTUNING=1`, we expect `self.bench_time` to be populated if we did not used a cached result for the benchmarking results. There was a codepath that used cached results from the disk, but did not update the flag saying we used cached results, leading to a crash when `self.bench_time` was unset.
=> Fix TRITON_PRINT_AUTOTUNING crash on disk‑cache hits

lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
This PR addresses a compilation issue when targeting RTX 5090 GPUs with compute capability 120. Previously, the function getMMAVersionSafe would trigger an assertion failure for compute capabilities beyond 110. This update ensures that GPUs with compute capability of 120 fall under a valid MMA version category, preventing unnecessary assertion failures.
Changes
Updated the compute capability check in getMMAVersionSafe to handle GPUs with compute capability up to 129.
Assigned MMA version {2} for these cases to maintain compatibility with customer's gpus only supporting version 2.
Motivation
Certain GPUs, including models from the NVIDIA 50 series, have a compute capability of 120, which was previously unhandled, causing compilation failures. This fix ensures compatibility with such GPUs. …
=> [3.3.1 cherry pick] Fix Compilation Issue for RTX 5090 GPUs with Compute Capability = 120 (#6131)

.github/workflows/wheels.yml, docs/conf.py, python/setup.py, python/triton/__init__.py
- Bump version to 3.3.1. 
- Disable publishing to pypi step. so that we don't release it untill we are ready
=> [Release-only] Bump version to 3.3.1 release, turn off publishing to pypi until we needed

include/triton/Dialect/TritonNvidiaGPU/Transforms/TMAUtilities.h, include/triton/Tools/LayoutUtils.h, include/triton/Tools/LinearLayout.h, lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp, lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/OptimizeDescriptorEncoding.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/TMAUtilities.cpp, lib/Tools/LinearLayout.cpp, python/src/ir.cc, python/test/unit/cuda/test_tensor_descriptor.py, python/test/unit/language/test_tensor_descriptor.py, test/Conversion/tritonnvidiagpu_to_llvm.mlir, test/TritonGPU/dot-operands.mlir, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TensorMemoryToLLVM.cpp, unittest/Dialect/TritonGPU/LinearLayoutConversionsTest.cpp
This overcomes the hardware limit that no dimension can exceed 256 within the block size of the TMA descriptor.
=> [TMA] Split large dimensions up into chunks of 256 elements

lib/Conversion/TritonGPUToLLVM/Utility.cpp, test/Conversion/nvgpu_to_llvm.mlir, third_party/nvidia/lib/NVGPUToLLVM/NVGPUToLLVMPass.cpp
This allows a bunch of code to fold away trivially, especially in the MMA and load partitions of warp specialized kernels.
=> [Backend] Codegen warpId to 0 when there 1 contextual warp

unittest/googletest.cmake
To resolve the following warning:
```bash
CMake Deprecation Warning at build/cmake.linux-x86_64-cpython-3.10/_deps/googletest-src/CMakeLists.txt:4 (cmake_minimum_required):
Compatibility with CMake < 3.10 will be removed from a future version of
CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
```
https://github.com/google/googletest/releases/tag/v1.17.0
=> Update `googletest` version up to `v1.17.0`

include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td, include/triton/Dialect/TritonGPU/Transforms/PipelineExpander.h, lib/Dialect/TritonGPU/Transforms/Pipeliner/PipelineExpander.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/SoftwarePipeliner.cpp, test/TritonGPU/loop-pipeline.mlir
We would like to implement epilogue peeling by custom amount of iterations to help with cases where last loop iteration is almost entirely predicated out except for final mmav5 wait.
To avoid adding hard to debug complexity to the expander, we will peel the epilogue after the expansion and resolve the stage predicates manually (masking out the instructions from non-last iterations after the loop, and removing the mask from one-before-last iteration in the loop).
Adding an option to delay resolving the predicate to after the expansion makes such transformation much easier, as we won't need to analyze the arithmetic ops used to build the logical predicates for the ops.
=> [PIPELINE] Implementing expander option to leave stage predicates as an unresolved op

README.md, python/src/passes.cc, python/triton/knobs.py, third_party/amd/backend/compiler.py, third_party/nvidia/backend/compiler.py
Sometimes having minimal module dump without location info clobbering the IR is usefull.
=> Add an option to remove debug info from the module

python/test/unit/language/test_random.py, python/triton/language/random.py
Previously, passing a 64-bit offset to randint4x would cause Philox to use 64-bit arithmetic internally and return 64-bit integer tensors. Not only is this slow and register-hungry, but also it contradicts the description of randint4x that it returns four 32-bit integer tensors. We fix this to use 32-bit Philox even if the offset is 64-bit; the two halves of the offset are used to populate two of the four words in the 128-bit counter.
=> Use 32-bit Philox consistently in randint4x even if offset is 64-bit

README.md, python/src/passes.cc, python/triton/knobs.py, third_party/amd/backend/compiler.py, third_party/nvidia/backend/compiler.py
This reverts #6837.
This option is redundant with the existing `TRITON_DISABLE_LINE_INFO=1` which results in identical IR. However, that option wasn't included in the readme, so I've kept the documentation but just changed the variable name.
=> Revert "Add an option to remove debug info from the module (#6837)"

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td, test/TritonGPU/reduce-data-duplication.mlir
For a small contiguous shape dimension, we could get a division by zero when converting to MMA layout.
=> Fix division by zero in ReduceDataDuplicationPass

python/triton_kernels/bench/bench_mlp.py
Use the first compute bound data point as the end point for the bandwidth-bound line so that it can connect with the compute-bound line. This is visually better espically if we have sparse data points.
Along the way also make the title clear regarding the benchmarked case.
=> [Bench] Make roofline graph lines and title clearer

python/test/unit/language/test_standard.py, python/triton/language/standard.py
Currently, `tl.flip` only supports flipping along the last dimension. We can still use the same algorithm to flip any dimension as long as we tweak where the swaps begin/end.
=> [FRONTEND] Allow arbitrary dim in tl.flip

python/test/unit/language/test_tuple.py, python/triton/language/core.py, python/triton/language/standard.py
* Added two `test_eq` and `test_add`
* Introduced a `_normalize_tuple` function to standardize tuple inputs. Otherwise, if `other` is a constexpr, both `__eq__` and `__add__` methods will fail
* Removed redundant imports of `builtins`
* Fixed a tuple construction issue in the `flip` function that previously requires the `core.tuple([2] * steps)` workaround
=> [FRONTEND] Fix `__eq__` and `__add__` methods in `tl.tuple`

python/test/unit/language/test_tensor_descriptor.py, python/triton/language/semantic.py
Currently we fail in the middle of the tensor descriptor rewrite pass, whereas this pre-empts it and raises the error from the frontend.
=> [Frontend] Improve error when descriptor atomic_{min,max} cannot fallback

test/Hopper/WarpSpecialization/ws_data_partition.mlir, third_party/nvidia/hopper/include/Transforms/Passes.td, third_party/nvidia/hopper/lib/Transforms/CMakeLists.txt, third_party/nvidia/hopper/lib/Transforms/WarpSpecialization.cpp, third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/Utility.h, third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/WSDataPartition.cpp
When multiple consumers are requested to execute the same code region, the compiler determines how to divide the work between them. On Hopper, the compiler will, by default, attempt to split the input tensor A for a dot operation along the M dimension so that each consumer computes half of the output tensor independently. This approach is aka cooperative partitioning. If this split is not advantageous—for instance, if it results in a smaller-than-native wgmma instruction—the compiler will instead attempt to split along the N dimension.
The transformed code for a typical GEMM kernel with a configured tile size [128, 256, 64] will look like below (using source annotations instead of IR for illustration)
```
@triton.jit
def matmul_persistent_ws_kernel(
a_ptr, b_ptr, c_ptr, M, N, K, …
```
=> [hopper][WS] Automatic data partition for multiple consumers

python/triton_kernels/bench/bench_mlp.py, python/triton_kernels/tests/test_matmul.py, python/triton_kernels/tests/test_mxfp.py, python/triton_kernels/triton_kernels/matmul_ogs.py, python/triton_kernels/triton_kernels/matmul_ogs_details/_matmul_ogs.py, python/triton_kernels/triton_kernels/matmul_ogs_details/_p_matmul_ogs.py, python/triton_kernels/triton_kernels/matmul_ogs_details/opt_flags.py, python/triton_kernels/triton_kernels/matmul_ogs_details/opt_flags_nvidia.py, python/triton_kernels/triton_kernels/numerics_details/mxfp.py
This improves utilisation from 28% to 37%.
Edit with https://github.com/triton-lang/triton/pull/6812 we hit 49% util.
We don't try to optimise the upcasting sequence yet but we could do that
if we are willing to add a global scale via a packing/unpacking sequence
by Scott Gray in a future PR.
We also add tests for quantisation in general.
=> [BENCH] Implement value and scale swizzling for Hopper bf16xmxfp4

include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td, lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp, lib/Dialect/TritonGPU/IR/Ops.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/WGMMAPipeline.cpp, test/Analysis/test-alias.mlir, test/Analysis/test-allocation.mlir, test/Conversion/amd/tritongpu_to_llvm.mlir, test/Conversion/tritongpu_to_llvm.mlir, test/TritonGPU/invalid.mlir
We strictly define the semantics of `memdesc_subview` as allowing
arbitrary skips along the 0-th dimension when the subview is
rank-reducing, and otherwise via constant offsets that don't touch the
swizzling pattern.
We implement a generic lowering that lowers arbitrary layouts under
these conditions.
These conditions can be very much relaxed and generalised if needed in
the future.
=> [BACKEND] Define the semantics of memdesc_subview

python/test/unit/language/test_matmul.py, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/MMAHelpers.h, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/MMAv5.cpp
The indexing math was incorrect when accesing tmem as lhs operand.
This fixes some random failures on attention tutorial when BLOCK_M=256 is picked
=> [BACKEND] Fix indexing into TMEM for lhs mma operands

test/Proton/allocate_shared_memory.mlir, test/Proton/proton_to_protongpu.mlir, third_party/proton/common/include/TraceDataIO/TraceWriter.h, third_party/proton/common/lib/TraceDataIO/TraceWriter.cpp, third_party/proton/dialect/lib/ProtonToProtonGPU/ProtonToProtonGPUPass.cpp, third_party/proton/proton/hooks/instrumentation.py, third_party/proton/proton/mode.py, third_party/proton/test/unittest/TraceDataIO/ChromeTraceWriterTest.cpp
This PR adds: 
1. hard cap of default profiler shared memory buffer size: at most 4% of total smem size when estimated occupancy > 1 
2. the optimization mode in `instrumentation.py`. That optimization mode is intended to be the knobs outside the compiler (e.g., trace post processing).
3. change string concat to using json object in the `ChromeTraceWriter`
=> [PROTON-DEV] Better profiler buffer default size and opt mode

lib/Dialect/Triton/Transforms/LoopAwareCSE.cpp, test/Triton/loop_cse.mlir
I made a classic blunder trying to cache context-sensitive DFS. The DFS cache persisting from one context to another was causing miscompiles because operations that were equal in one context are not equal in another.
I just removed the cache for now because properly caching the DFS here is very tricky. If compile time of this pass becomes a problem, we can revisit it.
=> [Triton] Fix LoopAwareCSE by removing the equivalence cache

bin/RegisterTritonDialects.h, include/triton/Dialect/TritonNvidiaGPU/Transforms/Passes.h, include/triton/Dialect/TritonNvidiaGPU/Transforms/Passes.td, lib/Dialect/TritonNvidiaGPU/Transforms/FenceInsertion.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/InterleaveTMem.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/MMALowering.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/OptimizeDescriptorEncoding.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/OptimizeTMemLayouts.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/PlanCTA.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/PromoteLHSToTMem.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/RemoveTMEMTokens.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/TMALowering.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/TensorMemoryAllocation.cpp, third_party/nvidia/triton_nvidia.cc
Continuation of #6785 and #3971
=> [NFC] Remove uses of deprecated `GEN_PASS_CLASSES` for `TritonNvidiaGPU/Transforms`

lib/Conversion/TritonToTritonGPU/TritonGPUConversion.cpp, lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp, test/Conversion/triton_to_tritongpu.mlir
Functions with unstructured control flow passing tensors were not working as the function conversion pattern was converting all the blocks and creating illegal IR.
=> [BACKEND] Fix convert to triton gpu for CF ops

lib/Dialect/TritonGPU/Transforms/Pipeliner/MMAv5PipelineUtility.cpp, test/TritonGPU/pipeline-lower-loop.mlir
For MMAv5 with operands coming from `tmem_alloc` we can potentially push the `wait_barrier` to the next iteration, up to the point the tmem buffer is allocated.
=> [PIPELINE] Improve pipelining for mmav5 with tmem operands

python/test/unit/language/test_core.py, test/Conversion/tritongpu_to_llvm_hopper.mlir, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/MemoryOpToLLVM.cpp
With this we are able to lower pretty much anything that can be lowered to an stmatrix.
We are just missing two niche cases:
- Multi CTA
- Lowering fp8 with stmatrix.trans (you need the first two bases of kReg to be `[[0, 1], [1, 0]]`).
These can be supported in the future if necessary.
Will use this to support `ldmatrix` in the next PR.
=> [BACKEND] Support stmatrix.trans

docs/python-api/triton.language.rst, python/triton/tools/tensor_descriptor.py
Currently a rank mismatch gives an error in the driver when creating the tma descriptor, which makes it hard to track back to the original argument. This just makes the stack trace more useful.
Also add some basic tensor descriptor stuff to the docs.
=> [Frontend] Assert that TensorDescriptor fields have matching rank

lib/Dialect/TritonGPU/Transforms/Pipeliner/AssignLatencies.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/PartitionScheduling.cpp, test/TritonGPU/partition-scheduling.mlir, test/TritonGPU/pipeline-assign-latencies.mlir
* put critical path in the def partition, not the sink, to keep the correction partition small
* don't assign a latency to MMA ops that have read-modify-write, since they won't get double buffered
=> [Warp Specialization] Final couple of fixes

include/triton/Dialect/TritonGPU/Transforms/Utility.h, lib/Dialect/TritonGPU/Transforms/HoistTMEMAlloc.cpp, lib/Dialect/TritonGPU/Transforms/OptimizeAccumulatorInit.cpp, lib/Dialect/TritonGPU/Transforms/Utility.cpp, test/TritonGPU/hoist-tmem-alloc.mlir, test/TritonGPU/loop-pipeline-blackwell.mlir
Noticed that OptimizeAccumulatorInit and HoistTMEMAlloc were both doing some init rewriting and alloc movement, but that HoistTMEMAlloc was initializing tmem values that OptimizeAccumulatorInit had invalidated via use of the useD flag. This PR adds a pattern and a test to remove those as part of HoiseTMEMAlloc.
=> [TMEM] Remove Unneeded Stores

python/triton/language/core.py, python/triton/language/math.py, python/triton/language/semantic.py
<git-pr-chain>
1. [NFC][Easy] Dedup _constexpr_to_value and _unwrap_if_constexpr
These two functions do the exact same thing, choosing the name
`_unwrap_if_constexpr` as it's more explicit that non-constexpr values
are allowed to pass through.
1. Cleanup non-core uses
1. 👉 #6925 👈 **YOU ARE HERE**
=> [NFC][Easy] Dedup _constexpr_to_value and _unwrap_if_constexpr

python/test/unit/language/test_compile_errors.py, python/triton/language/core.py, python/triton/language/semantic.py, python/triton/runtime/interpreter.py, third_party/amd/backend/compiler.py, third_party/nvidia/backend/compiler.py
Also move the warning to be emitted only when the fp8 are used in a dot as this is the only case where there are performance problems.
=> Improve warning about fp8 deprecated format

python/test/unit/language/test_core.py, python/triton/language/standard.py
As mentioned in issue #5897, boolean inputs to `tl.cumsum` were 
producing incorrect results due to the scan operation using i1 (1-bit) 
type internally, creating "cumsum_xor" semantics.
Following the same approach used for `tl.sum` in #5763, introduce type
promotion upstream of lowering.
=> [LANGUAGE] Fix cumsum with bool inputs

lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp
This PR adds defensive return to `chooseMfmaLikeStoreLayout`, otherwise Triton
will simply fail on RDNA GPUs on certain conditions because the input argument
`valType.getEncoding()` cannot be casting to `AMDMfmaEncodingAttr`
=> [AMD] Fix RDNA support in chooseMfmaLikeStoreLayout

python/triton/language/core.py, python/triton/language/standard.py
Follow up of #6927. Include `dtype` and `reverse` parameters to `_add_scan_docstr`.
CC: @lezcano
=> [DOCS] Update scan docstring to include appropriate parameters

include/triton/Tools/Sys/GetEnv.hpp
accorsing to:
https://en.cppreference.com/w/cpp/utility/program/getenv getenv is not thread-safe. It seems to be causing some crash in multi-threaded environment
=> Add mutex around std::getenv

python/tutorials/03-matrix-multiplication.py
Reverts triton-lang/triton#6850 as it breaks on A100 and breaks documentation update
=> Revert "[TUTORIAL][03] use float8_e4m3fn(uz) instead of e5m2 and add PyTorch comparison"

python/triton_kernels/tests/test_matmul.py, python/triton_kernels/triton_kernels/matmul_ogs_details/opt_flags.py
`test_op` sets constraints when calling `matmul_ogs`, which fails because `make_default_opt_flags_amd` requires constrains not to be passed in. This updates `make_default_opt_flags_amd` to accept the constraints without modify the logic for the default behavior.
=> [Test] [AMD] Fix triton_kernels tests to support constraints on AMD

python/test/unit/language/test_frontend.py, python/triton/compiler/code_generator.py
📚 Stacked PRs 📚
* https://github.com/triton-lang/triton/pull/6970
* ➡️ https://github.com/triton-lang/triton/pull/6963
This PR makes `base_value.method` return a BoundJITMethod which keeps `base_value` to be passed as `__self__`.
=> [Frontend] Support binding `self` to `JITFunction` when they are methods

unittest/googletest.cmake
To fix:
```bash
CMake Warning (dev) at /home/runner/.local/lib/python3.10/site-packages/cmake/data/share/cmake-3.31/Modules/FetchContent.cmake:1953 (message):
Calling FetchContent_Populate(googletest) is deprecated, call
FetchContent_MakeAvailable(googletest) instead.  Policy CMP0169 can be set
to OLD to allow FetchContent_Populate(googletest) to be called directly for
now, but the ability to call it with declared details will be removed
completely in a future version.
Call Stack (most recent call first):
unittest/googletest.cmake:18 (FetchContent_Populate)
cmake/AddTritonUnitTest.cmake:1 (include)
CMakeLists.txt:81 (include)
```
=> Update `FetchContent_Populate` -> `FetchContent_MakeAvailable` in `googletest.cmake`

bin/CMakeLists.txt, bin/RegisterTritonDialects.h, include/triton/Dialect/Triton/IR/Utility.h, include/triton/Dialect/Triton/Transforms/LoopPeeling.h, include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td, lib/Dialect/Triton/IR/Utility.cpp, lib/Dialect/Triton/Transforms/CMakeLists.txt, lib/Dialect/Triton/Transforms/LoopPeeling.cpp, lib/Dialect/TritonGPU/Transforms/CMakeLists.txt, lib/Dialect/TritonGPU/Transforms/Pipeliner/AssignLatencies.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/PipeliningUtility.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/SoftwarePipeliner.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/LoadMMASpecialization.cpp, python/test/unit/language/test_matmul.py, test/Triton/loop-peeling.mlir, test/TritonGPU/loop-pipeline.mlir, test/TritonGPU/pipeline-loop-nest.mlir, test/lib/CMakeLists.txt, test/lib/Dialect/CMakeLists.txt, test/lib/Dialect/TestLoopPeeling.cpp
Reintroduce "[PIPELINE] Peel single epilogue iteration after loop expansion #6893"
Fixed the issue that was exposing IMA by using poison values as buffer indices used by speculatively executed async copy.
=> [PIPELINER] Reintroduce epilogue peeling

python/test/unit/language/test_frontend.py, python/triton/compiler/code_generator.py, python/triton/language/core.py, python/triton/runtime/jit.py
📚 Stack PRs 📚
1. ➡️ https://github.com/triton-lang/triton/pull/6988
2. https://github.com/triton-lang/triton/pull/6989
This teaches a few more places in the frontend to treat JITFunction as constexprs. This allows, for example, passing lists of functions as constexprs.
=> [Frontend] Treat JITFunction as constexpr type

python/src/gluon_ir.cc, python/test/gluon/test_frontend.py, python/triton/experimental/gluon/language/_layouts.py, python/triton/experimental/gluon/language/nvidia/__init__.py, python/triton/experimental/gluon/language/nvidia/blackwell/__init__.py, python/triton/experimental/gluon/language/nvidia/hopper/__init__.py, python/triton/experimental/gluon/language/nvidia/hopper/mbarrier.py
<git-pr-chain>
1. [Gluon] Add mbarrier
This implements:
- `ttgl.SwizzledSharedLayout`
- `ttgl.nvidia.hopper.mbarrier.MBarrierLayout` (convenience wrapper for `SwizzledSharedLayout`)
- `ttgl.nvidia.hopper.mbarrier.init`
- `ttgl.nvidia.hopper.mbarrier.invalidate`
- `ttgl.nvidia.hopper.mbarrier.expect`
- `ttgl.nvidia.hopper.mbarrier.wait`
- `ttgl.nvidia.hopper.mbarrier.arrive`
plus aliases in `ttgl.nvidia.blackwell.mbarrier`
Note that I'm keeping this API functional to allow interpreting
any shared allocation as an mbarrier. We can wrap with higher level
APIs at a later date if desired.
1. Add unsaved changes
1. 👉 #6997 👈 **YOU ARE HERE**
1. #6998
=> [Gluon] Add mbarrier

third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp
We need to predicate the `llStore` for the other value based on the initial mask or otherwise we would need to shuffle the other value as well.
`AsyncCopyGlobalToLocal` does this already correctly.
=> [AMD][BACKEND] Fix addresses for other stores from BufferLoadToLocal

python/test/unit/language/test_frontend.py, python/triton/language/core.py
Constexpr fields don't have an IR representation and are carried through the type. Also ensure that they are mangled into the type name.
This PR achieves this by adding a `constexpt_type` that contains the constexpr value itself and makes this the type of `constexpr`. Shoutout to @peterbell10 for the suggestion
=> [Frontend] Allow `@_aggregate` types to contain constexprs

python/test/gluon/test_frontend.py, python/test/unit/language/test_frontend.py, python/test/unit/language/test_module.py, python/test/unit/test_filecheck.py, python/triton/compiler/code_generator.py, python/triton/runtime/jit.py
Without this, calling two different Python jit functions with the same name will cause a name collision.
=> [Frontend] Use full module and qualname when mangling non-kernel function names

include/triton/Dialect/TritonGPU/Transforms/Utility.h, lib/Dialect/TritonGPU/Transforms/HoistTMEMAlloc.cpp, lib/Dialect/TritonGPU/Transforms/OptimizeAccumulatorInit.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/LowerLoops.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/PipeliningUtility.cpp, lib/Dialect/TritonGPU/Transforms/Utility.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/LoadMMASpecialization.cpp, third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp
This API with the `scf::ForOp&` passed by reference is a foot-gun (I shot my foot off this morning...) so this PR refactors to return the new `ForOp` instead.
=> [Utility] fix pass-by-reference `addIterArgsToLoop` API

test/TritonGPU/amd/amd-convert-buffer-ops.mlir, third_party/amd/lib/TritonAMDGPUTransforms/ConvertToBufferOps.cpp
The only supported 16-bit buffer atomic fadd dtype on gfx942 is float16 (BUFFER_ATOMIC_PK_ADD_F16). There seems to be no corresponding instruction for bf16. Without this PR, the following kernel 
```
import torch
import triton
@triton.jit
def atomic_add_bf16(X, BLOCK_SIZE: tl.constexpr):
pid = tl.program_id(axis=0)
block_start = pid * BLOCK_SIZE
t1 = tl.full((BLOCK_SIZE, ), 1, dtype=tl.bfloat16)
offsets = block_start + tl.arange(0, BLOCK_SIZE)
tl.atomic_add(X + offsets, t1)
X = torch.tensor([0, 1] * 256, device='cuda', dtype=torch.bfloat16)
Z = torch.tensor([1, 2] * 256, device='cuda', dtype=torch.bfloat16)
k = atomic_add_bf16[(1,)](X, 2 * 256)
assert (torch.equal(X, Z))
print("Success!")
```
will fail in instruction selection
>~/triton]$ python …
=> [AMD] Remove bfloat16 fadd from buffer atomic RMW conversion

include/triton/Dialect/Triton/IR/TritonOps.td, lib/Conversion/TritonGPUToLLVM/HistogramOpToLLVM.cpp, lib/Dialect/TritonGPU/IR/Ops.cpp, python/src/ir.cc, python/test/unit/language/test_core.py, python/triton/language/core.py, python/triton/language/semantic.py, python/triton/runtime/interpreter.py, test/Triton/ops.mlir, test/TritonGPU/canonicalize.mlir
=> Add support for masked histograms

python/triton/runtime/autotuner.py
Fix #6636
When running auto tuner with `TRITON_PRINT_AUTOTUNING=1`, we could just see the best configuration but not **key**, some user would like to see the **key** if there is multiple combination of **key**.
This PR tries to log more details about key.
=> [LOG] More details log for key when TRITON_PRINT_AUTOTUNING=1

third_party/amd/include/TritonAMDGPUToLLVM/MembarUtility.h, third_party/amd/lib/TritonAMDGPUToLLVM/MembarUtility.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/TritonGPUToLLVM.cpp, third_party/amd/test/lib/Analysis/TestAMDGPUMembar.cpp
Instead of walking the def-chain of the `AsyncToken` inside the membar filter we do it once before running membar analysis. Also makes the branch handling more generic by using `BranchOpInterface` instead of the specific branch instructions.
This also allows us to reuse the information when adding alias information while lowering `LocalLoads` which will be enabled in a follow up PR.
=> [AMD][BACKEND] Refactor Membar filter for LocalLoads synced via AsyncWait

lib/Dialect/TritonNvidiaGPU/Transforms/OptimizeTMemLayouts.cpp, test/TritonNvidiaGPU/tmem_layouts.mlir
This allows the TMEM load to be split into 4 (or even larger pow-of-2)
spearate loads. More smaller loads can decrease register pressure in
matmul loop epilogues.
* Cherry-picked from PR #6566 and applied on top of latest main.
=> [BACKEND] Allow tmem split pass to match splits of tmem subslices

test/Conversion/amd/buffer_load_to_local_to_llvm.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp
If the fastest dim we load elements from hbm is contiguous we can apply the laneOffset to the pointers/buffer offsets to get the swizzled addresses. This only works because we are swapping the elements between lanes and we only swizzle in the fastest dim.
In general this performs better than using ds_bpermute.
=> [AMD][BACKEND] Add optimization to bypass ds_bpermute for direct-to-lds loads

bin/RegisterTritonDialects.h, test/Proton/protongpu_transforms.mlir, third_party/proton/dialect/include/Dialect/ProtonGPU/CMakeLists.txt, third_party/proton/dialect/include/Dialect/ProtonGPU/Transforms/CMakeLists.txt, third_party/proton/dialect/include/Dialect/ProtonGPU/Transforms/Passes.h, third_party/proton/dialect/include/Dialect/ProtonGPU/Transforms/Passes.td, third_party/proton/dialect/lib/Dialect/ProtonGPU/CMakeLists.txt, third_party/proton/dialect/lib/Dialect/ProtonGPU/Transforms/CMakeLists.txt, third_party/proton/dialect/lib/Dialect/ProtonGPU/Transforms/ProtonGPUTransformsPass.cpp, third_party/proton/dialect/triton_proton.cc, third_party/proton/proton/hooks/instrumentation.py, third_party/proton/proton/mode.py
This PR adds a mode to the profiler that allows for more accurate 
measurement of regions using `pl.scope`. Instead of storing the
clock measurements in shared memory just after reading them. 
This extra pass will schedule the storing of the both the 
measured values (start, end) after the measurement for a 
particular region. The pass `ProtonScheduleBufferStorePass`, 
looks for start stores and moves it after the end of `pl.scope` 
so that the stores don't pollute the measurements.
=> [PROTON-DEV] Option to schedule buffer store

third_party/nvidia/backend/compiler.py
Speculative placement of the pass. It needs to run after some IR simplification but before canonicalizer, typically.
=> [Triton] Add SCCP to the end of make_ttgir

python/test/unit/language/test_core.py
Enable f8 cases for test_dot_max_num_imprecise_acc test
=> [AMD][gfx12] Enable f8 cases for test_dot_max_num_imprecise_acc test

include/triton/Dialect/TritonGPU/Transforms/Utility.h, lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp, lib/Dialect/TritonGPU/Transforms/Utility.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/PromoteLHSToTMem.cpp, test/TritonGPU/promote-lhs-to-tmem.mlir
Extend the logic to promote lhs to tmem, until now we were doing it only if the layout allowed copying to tmem but often we can change the layout and the convert_layout will propagate up.
Change the heuritstic to promote to tmem as long as the value doesn't come from a global load, this matches the logic on Hopper.
=> [BACKEND] Promote lhs to tmem more aggressively

test/Conversion/tritongpu_to_llvm_blackwell.mlir, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TensorMemoryToLLVM.cpp
An accounting error meant not enough messages were being emitted when the TMEM message is being broken up.
=> [Blackwell] Fix lowering of packed b16 TMEM ops

python/test/unit/language/test_frontend.py, python/triton/compiler/code_generator.py, python/triton/experimental/gluon/language/_core.py, python/triton/experimental/gluon/language/_semantic.py, python/triton/experimental/gluon/language/nvidia/blackwell/__init__.py, python/triton/experimental/gluon/language/nvidia/blackwell/tma.py, python/triton/experimental/gluon/language/nvidia/hopper/mbarrier.py, python/triton/experimental/gluon/language/nvidia/hopper/tma.py, python/triton/language/core.py, python/triton/language/math.py, python/triton/language/semantic.py, python/triton/runtime/interpreter.py, python/triton_kernels/triton_kernels/matmul_ogs_details/_p_matmul_ogs.py, third_party/amd/language/hip/libdevice.py, third_party/nvidia/language/cuda/libdevice.py, third_party/nvidia/language/cuda/utils.py, third_party/proton/proton/language.py
This changes the builtin calling convention to pass a `_semantic` value instead of `_builder`. So instead of:
```python
def add(x, y, _builder=None):
return semantic.add(x, y, _builder)
```
we now have
```python
def add(x, y, _semantic=None):
return _semantic.add(x, y)
```
The advantage being that `GluonSemantic` can inherit from `TritonSemantic` and share most of the implementation, but override some specifics e.g. broadcasting.
I recommend to view the diff ignoring whitespace changes.
=> [Frontend][NFC] Make semantic a language-specific class

python/src/gluon_ir.cc, python/test/gluon/test_frontend.py, python/triton/experimental/gluon/language/_core.py, python/triton/experimental/gluon/language/_semantic.py, python/triton/language/semantic.py
To make life simple, this assumes that `expand_dims(x, dim)` has a `SliceLayout` with matching dimension as the outermost layout.
=> [Gluon] Implement broadcasting and expand_dims

python/triton_kernels/pyproject.toml
llnl-hatchet depends on numpy 1, causing problems for users who want to use numpy 2. It does not appear to be used within triton_kernels, only elsewhere in the repo.
=> triton_kernels: remove unnecessary dependency on llnl-hatchet

python/test/unit/tools/test_aot.py
Remove duplicate tests and unnecessary synchronization.
On some platforms it reduces the time from 50s to 20s
=> [TESTS] Reduce AOT test time

CMakeLists.txt, python/test-requirements.txt, python/test/unit/test_filecheck.py, python/triton/_filecheck.py, setup.py
The filecheck python dependency isn't available in python3.9. This change removes it in lieu of the llvm FileCheck binary, which is now packaged into the wheel.
=> Use llvm filecheck instead of filecheck python lib.

python/src/gluon_ir.cc, python/src/ir.cc, python/test/gluon/test_frontend.py, python/triton/experimental/gluon/language/_core.py, python/triton/language/semantic.py
* where, maximum, minimum
* add gluon_ir builder for fence_async_shared. Not sure what API to use
* fix `ttgl.warp_specialize` passing constexpr arguments
=> [Gluon] Fix warp_specialize with constexprs, add a few APIs

include/triton/Tools/Sys/GetEnv.hpp, third_party/proton/common/include/TraceDataIO/Parser.h, third_party/proton/common/lib/TraceDataIO/CircularLayoutParser.cpp, third_party/proton/csrc/lib/Profiler/Instrumentation/InstrumentationProfiler.cpp, third_party/proton/dialect/include/Conversion/ProtonGPUToLLVM/Utility.h, third_party/proton/dialect/lib/ProtonGPUToLLVM/ProtonAMDGPUToLLVM/AMDPatternProtonGPUOpToLLVM.cpp, third_party/proton/dialect/lib/ProtonGPUToLLVM/ProtonNvidiaGPUToLLVM/NvidiaPatternProtonGPUOpToLLVM.cpp, third_party/proton/dialect/lib/ProtonGPUToLLVM/Utility.cpp
Move the `circular_store` AMD and NV common code into the `utility` and add an ENV for Proton to print debug info.
=> [PROTON-DEV] Remove redundant lowering code and suppress parser print

.gitignore, python/test/unit/language/test_compile_errors.py, python/test/unit/language/test_frontend.py, python/test/unit/runtime/test_cache.py, python/triton/compiler/code_generator.py, python/triton/runtime/interpreter.py, python/triton/runtime/jit.py, python/triton_kernels/triton_kernels/specialize.py
This enables the code generator to perform name lookup of captured closure variables like it does for globals. I also made  sure add machinery to the runtime that detects invalid modification of closure captures like for globals.
This allows building Zig-style generics in Triton
=> [Frontend] Enable accessing `fn.__closure__` of `@jit` functions like globals

python/triton_kernels/bench/bench_mlp.py, python/triton_kernels/tests/test_matmul.py, python/triton_kernels/triton_kernels/matmul_ogs.py, python/triton_kernels/triton_kernels/matmul_ogs_details/opt_flags.py, python/triton_kernels/triton_kernels/target_info.py
This PR is part of the efforts fixing the tests for the benchmark on AMD gfx950 hardware.
With it now `pytest -s test_matmul.py` has no failures (some tests are skipped for now.)
=> [Bench][AMD] Fix matmul tests for gfx950

python/triton/language/core.py, python/triton/language/semantic.py
If user passes None explicitly to `acc` in tl.dot, it will fail when accessing acc.handle from a constexpr[None].
```
if acc is None:
acc_handle = builder.create_splat(ret_ty.to_ir(builder), _0)
else:
>           acc_handle = acc.handle
E           AttributeError: 'constexpr' object has no attribute 'handle'
```
Test plan:
1. randomly pick a unit test `pytest python/test/unit/language/test_core.py::test_dot[1-32-32-32-4-False-False-add-cols-ieee-float16-float16-1-None]`
2. add None to tl.dot
=> [Bug fix] tl.dot(a, b, None)

test/TritonGPU/amd/amd-canonicalize-pointers.mlir, third_party/amd/lib/TritonAMDGPUTransforms/CanonicalizePointers.cpp
There are scenarios where one can use `ExtractSliceOp` for slicing tensors of pointers. In this scenario, `CanonicalizePointers` pass fails. This PR adds `ConvertExtractSliceOp` rewrite pattern in `CanonicalizePointers` pass to handle the scenario. The lit test is provided.
=> [AMD] Added `ExtractSliceOp` to `CanonicalizePointers`

python/triton_kernels/bench/bench_mlp.py, python/triton_kernels/tests/test_matmul.py, python/triton_kernels/triton_kernels/matmul_ogs.py, python/triton_kernels/triton_kernels/matmul_ogs_details/_common.py, python/triton_kernels/triton_kernels/matmul_ogs_details/_p_matmul_ogs.py, python/tutorials/10-block-scaled-matmul.py, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TensorMemoryToLLVM.cpp
Improves the Triton MOE kernel performance for the mxfp4 block scaled workload with a better layout choice for TMA. This is up to a ~30% boost in performance for some shapes in the roofline sweep. Importantly, with this patch using TMA for scale factors is always faster than traditional loads so we can remove their use for SF. Tutorial 10 is updated to reflect this.
* Use TMA for block scales even when performing W @ X
* Use host TMA descriptors for X, W, and SF in persistent kernel when possible
* Use 2x256 shape for scale factor TMAs
* Also update tutorial 10 to use the faster 5d 2x256xu8 TMA for block scale factors.
=> [KERNELS][TUTORIAL][BLACKWELL] Use optimized TMA layout for block scale factors

python/triton_kernels/triton_kernels/matmul_ogs.py, python/triton_kernels/triton_kernels/matmul_ogs_details/_finalize_matmul.py, python/triton_kernels/triton_kernels/matmul_ogs_details/_matmul_ogs.py
https://github.com/triton-lang/triton/pull/7140 introduced a subtle change in the semantics of `matmul_ogs`. We actually care that the output of rows that have scatter_indx==-1 be zero-initialized because some expert parallelism code may reduce them
also found some missing mask in the AMD implementation, which most likely explains the test failure.
=> [kernels] restore old behavior that output for tokens routed to zero experts should be zero-initialized

include/triton/Dialect/TritonGPU/Transforms/Utility.h, lib/Dialect/TritonGPU/Transforms/Coalesce.cpp, lib/Dialect/TritonGPU/Transforms/Utility.cpp, test/TritonGPU/coalesce.mlir
Try to reland: https://github.com/triton-lang/triton/pull/5707
Taking over https://github.com/triton-lang/triton/pull/4914 due to an inactivity
As discussed there, when there are multiple "contiguity of 1" in the `contiguity` array, doing argsort on it means that the resulting `order` becomes ascending for those elements. In the unit test, `order = [2, 1, 0]` becomes `[0, 1, 2]`, which is odd. This convention seems arbitrary, so it is better to pick the row-major ordering by default in such case to be consistent with the rest of code.
The current convention is "correct", but we get an additional `convert_layout`. Moreover, this order is inherited to the SMEM allocated during SWP, which could be problematic for other ops. For example, in my case I was getting the order `[4, 0, 1, 2, 3]` in …
=> [Coalesce] Fix the default order to be row major  (#5707)

third_party/proton/csrc/lib/Profiler/Instrumentation/InstrumentationProfiler.cpp, third_party/proton/proton/hooks/instrumentation.py, third_party/proton/proton/mode.py, third_party/proton/test/test_profile.py
This PR adds the ability to provide a comma separated list of 
optimizations to mode. We have just `TIME_SHIFT` and `SCHED_STORES`
optimizations for now. `TIME_SHIFT` optimization doesn't support 
handling SCHED_STORES in the current state but can be extended 
to support it. This is being added so that in future when we have more 
such optimizations we can allow users to specify multiple of them 
instead of just one.
Tested this locally with a test script by using different combinations of 
`time_shift` and `sched_stores` in optimizations. Even though using them 
together will produce inconsistent results it was useful to test that the 
ability to provide a list of options.
=> [PROTON-DEV] Support passing a list of optimizations in mode

python/triton/knobs.py, third_party/proton/csrc/include/Driver/Dispatch.h, third_party/proton/proton/profile.py
Other knobs with PATH seem to allow referencing the library directly. This name update clarifies that it must be the parent directory.
=> [Proton] Rename knobs.proton.cupti_path to knobs.proton.cupti_dir to make clear that it should be the parent directory to .so file

python/triton/language/core.py, python/triton/tools/tensor_descriptor.py
base dtype may not be (and doesn't need to be) canonicalizable
=> [PYTHON][TOOLS] simplify construction of tensor descriptor

python/triton_kernels/tests/test_routing.py
All of the routing tests are currently broken on AMD. They fail because some of the reference checks are wrong. This disables the tests until someone can fix them.
=> [AMD] [Testing] Skip routing tests on AMD

python/src/llvm.cc
NVPTX has some suboptimal lowerings like that memset. By doing this, we avoid
hitting these lowerings.
=> [LLVM] Pass NVPTX triple to LibaryAnalysis

setup.py
In tarballs there is not git information and `git` would check every parent folder potentially returning unrelated information.
Verify that `setup.py` is run from a git checkout and bail out otherwise.   
The existence of the `.git` folder should be a good enough indicator for that.
=> Fix version when using source tarballs

python/triton_kernels/tests/test_routing.py
Actually calls `is_hip()` so the tests are properly skipped on AMD.
=> [AMD] Fix typo in disabling AMD tests

setup.py
The command will always fail for source tarballs so run it only in git repositories
Followup to https://github.com/triton-lang/triton/pull/7164 with the same reasoning
=> setup.py: Don't run git command outside git checkout

test/TritonGPU/amd/accelerate-amd-matmul-unsupported.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/MFMA.cpp, third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp
If we cannot match a proper MFMA intrinsic, it pretty much is due to that the element type is not supported. So make the error message more explanatory instead of using fatal error with a vague message.
=> [AMD] Use a proper error message for no matching MFMA intrinsic

include/triton/Dialect/TritonGPU/Transforms/Utility.h, lib/Dialect/TritonGPU/Transforms/Utility.cpp, test/TritonGPU/loop-pipeline-hip.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/FMA.cpp, third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp
fixes a perf regression on gfx942 but preserves functionality for gfx950 (and above).
=> [AMD] Pipeline small tensors w/ registers only on GFX950

third_party/nvidia/backend/driver.py, third_party/nvidia/language/cuda/gdc.py
Description:  
This pull request corrects minor typographical errors in comments and documentation within the CUDA driver and GDC modules. Specifically, it changes "maximum" to "maximum" in the driver comment and corrects "programatic" to "programmatic" in the GDC documentation. These changes improve code readability and maintain consistency in terminology. No functional code changes are included.
=> Fix Typos in Comments and Documentation for CUDA Driver and GDC

include/triton/Dialect/Triton/IR/DiscardableAttributes.h, lib/Dialect/Triton/IR/CMakeLists.txt, lib/Dialect/Triton/IR/DiscardableAttributes.cpp, lib/Dialect/Triton/Transforms/Combine.cpp, lib/Dialect/Triton/Transforms/Combine.td, test/Triton/combine.mlir, third_party/amd/lib/TritonAMDGPUTransforms/CanonicalizePointers.cpp
Combine and canonicalize remove the attributes that relate to alignment so we don't get vectorization of stores in some cases, this allows them to keep it.
These two attributes are important to keep :tt.contiguity tt.divisibility. This PR will also possibly copy more, do we want a allowlist instead?
=> [BACKEND] Preserve DiscardableAttrs in AddPtr combine and canonicalize

include/triton/Conversion/TritonGPUToLLVM/TargetInfoBase.h, include/triton/Tools/GenericSwizzling.h, include/triton/Tools/LayoutUtils.h, include/triton/Tools/LinearLayout.h, lib/Analysis/Allocation.cpp, lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp, lib/Conversion/TritonGPUToLLVM/GatherOpToLLVM.cpp, lib/Conversion/TritonGPUToLLVM/Utility.cpp, lib/Tools/CMakeLists.txt, lib/Tools/GenericSwizzling.cpp, lib/Tools/LayoutUtils.cpp, lib/Tools/LinearLayout.cpp, test/Analysis/test-allocation.mlir, test/Conversion/tritongpu_to_llvm.mlir, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/MemoryOpToLLVM.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.h, unittest/Dialect/TritonGPU/CMakeLists.txt, unittest/Dialect/TritonGPU/SwizzleTest.cpp, unittest/Tools/LinearLayoutTest.cpp
We implement a generic swizzling algorithm by @apgoucher that, given two linear layouts, finds the optimal shared memory layout that maximises read/write vectorisation and, provided that, minimises bank conflicts.
We also implement an algorithm to find the minimum tile size necessary to perform the `convert_layout` given the restrictions above, and we use it to perform the `convert_layout` iteratively.
This PR does not yet implement a lowering to ldmatrix/stmatrix, we'll do that in a future PR.
=> [BACKEND] Implement generic swizzling when lowering `convert_layout`

include/triton/Dialect/TritonGPU/Transforms/Schedule.h, lib/Dialect/TritonGPU/Transforms/Pipeliner/Schedule.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/ScheduleLoops.cpp, test/TritonGPU/pipeline-schedule-loop.mlir
A small bug was caused because backwards stage prop after warp specialization was assuming all latency ops have stages assigned. This is the correct thing to assume but right now the stage can sometimes be dropped for various reasons. Workaround the problem (for now) by ignoring those ops.
This PR also tightens `const` API for CoarseSchedule to help catch bugs like this.
=> [Pipeliner] Fix backward scheduling over `ttg.local_load`

third_party/proton/dialect/triton_proton.cc, third_party/proton/proton/mode.py
We already have the support for sampling_strategy SELECTIVE in 
ConvertProtonToProtonGPUPass. Here, just I'm adding the link to 
python frontend.
=> [PROTON-DEV] Add SamplingStrategy::SELECTIVE for instrumentation

test/Conversion/tritongpu_to_llvm_volta.mlir, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/PatternTritonGPUOpToLLVM.h, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TritonGPUToLLVM.cpp
L2 cache hints are available in PTX only for sm >= 80. This PR will cause cache hints to be ignored for L2 on sm < 80.
Motivation: some Inductor tests are failing on sm75 due to cache hints added in Inductor: e.g. https://github.com/pytorch/pytorch/actions/runs/15712699449/job/44296072018
=> [NVIDIA] L2 cache hints only for sm >= 80

python/tutorials/gluon/01-attention-forward.py
This PR deletes the d64 kernel and only uses the d128 kernel by enabling BLOCK_N=128 for d64 and increasing the number of load buffers, as well as reordering code in the softmax partition to improve performance.
This increases the peak performance up to 770 tflops (780 for non-causal) for DHEAD=64. However, this makes performance for smaller ctx (16k and below) worse than before because the scheduling granularity is worse. This should get fixed when the kernel is made persistent, and this means I don't have to optimize two separate kernels.
DHEAD=128 performance is unchanged.
```
Attention Z=4 H=32 D=64 causal=False:
N_CTX  triton-fp16  cudnn-fp16
0   1024.0   381.658388  480.100511
1   2048.0   569.136004  804.057444
2   4096.0   663.284730  892.582773
3   8192.0   737.043055  939.454979 …
```
=> [Gluon][Tutorial] Merge d64 and d128 attn kernels

python/src/gluon_ir.cc, python/test/gluon/test_frontend.py, python/triton/experimental/gluon/language/_layouts.py, python/triton/language/__init__.py
This PR makes layouts always materialize their CTA layouts so that `BlockedLayout([1], [32], [4], [0]) == BlockedLayout([1], [32], [4], [0], [1], [1], [0])`. This is important especially since layouts raised from MLIR always have CTA layouts attached.
=> [Gluon] Fix linear layout MLIR->Python; fix CTA layout equality

python/test/gluon/test_core.py, python/test/gluon/test_frontend.py, python/triton/experimental/gluon/_runtime.py
Fixes some minor AMD compilation issues.
Some tests in test_frontend are skipped since they hardcode tpw=32 (and some use nvidia layouts), so I'm skipping these tests for now (they should probably be re-enabled in the future for AMD where possible).
=> [gluon] fix some AMD compilation issues + skip tests on AMD for now

python/test/gluon/test_core.py, python/test/gluon/test_frontend.py
I think https://github.com/triton-lang/triton/pull/7215 experienced some weird lint issue where it passed locally (and again in CI?) but failed after an automatic merge into main, not sure what happened.
https://github.com/triton-lang/triton/actions/runs/15734903332/job/44445442478
=> [gluon] fix lint

include/triton/Conversion/TritonGPUToLLVM/Utility.h, lib/Conversion/TritonGPUToLLVM/MemoryOpToLLVM.cpp, lib/Conversion/TritonGPUToLLVM/Utility.cpp, test/Conversion/tritongpu_to_llvm.mlir
We recently heavily optimised the ld/st.shared lowering for
convert_layout. Let's reuse it in other ops for better perf and to have
just one source of truth.
For now we just activate it for NVIDIA's path. Fixing it for AMD should
be easy (and beneficial) but I don't have access to an AMD GPU so...
cc @antiagainst
=> [BACKEND] Share ld/st.shared lowering between convert_layout and local_load/store

include/triton/Analysis/Membar.h, include/triton/Dialect/TritonNvidiaGPU/Transforms/Passes.td, lib/Analysis/Membar.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/CMakeLists.txt, lib/Dialect/TritonNvidiaGPU/Transforms/ProxFenceInsertion.cpp, test/TritonGPU/prox_fence_insertion.mlir, third_party/nvidia/backend/compiler.py, third_party/nvidia/triton_nvidia.cc
When loading data from smem using the generic proxy then writing using the async proxy we need to insert a fence before writing. This case was being missed in our current analysis. This commit hads a new pass to conservatively insert fences in this kind of scenario. We still need the existing insertFence pass as it can be smarter about fence insertion because it runs before lowering of the structured control flow. This pass is meant to be more conservative while the previous pass can optimize better.
Didn't see significant perf regressions so far.
=> [BACKEND] Add a new pass to insert fence.proxy.async for write after read hazard

test/TritonGPU/amd/amd-canonicalize-extract-slice.mlir, third_party/amd/include/Dialect/TritonAMDGPU/IR/TritonAMDGPUOps.td, third_party/amd/lib/Dialect/TritonAMDGPU/IR/Dialect.cpp
Added a canonicalization pattern to `concatOp`. The pattern removes a `concatOp` if it has a single input operand.
This scenario can potentially happen as a result of ops refinement. A corresponding lit-test is included
=> [AMD] Added a canonicalizer to ConcatOp

lib/Dialect/TritonGPU/Transforms/Pipeliner/SoftwarePipeliner.cpp, python/tutorials/09-persistent-matmul.py, third_party/nvidia/backend/compiler.py, third_party/nvidia/hopper/include/Transforms/Passes.td, third_party/nvidia/hopper/lib/Transforms/CMakeLists.txt, third_party/nvidia/hopper/lib/Transforms/WarpSpecialization.cpp, third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/TaskIdPropagation.cpp, third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/TaskIdPropagation.h, third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/WSCodePartition.cpp, third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/WSDataPartition.cpp, third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/WSLowerToken.cpp, third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/WSTaskIdPropagate.cpp, third_party/nvidia/triton_nvidia.cc
Builds and runs for GEMM with matmul_kernel_persistent_tma_ws_cooperative (i.e 2 consumer groups doing computation + epilogue, one producer group doing loads).
Performance will be tuned in a followup diff.
We set num_stages to 0 after WarpSpec to disable SWP. Also SWP is updated to bail out if there is no loop with num_stages >= 1.
=> [Hopper][WS] Update pipeline to get GEMM/FA working

include/triton/Dialect/TritonGPU/Transforms/Utility.h, lib/Dialect/TritonGPU/Transforms/Utility.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/OptimizeDescriptorEncoding.cpp
Moves `getTiedArgs` into `TritonGPU`/`Utils` for other passes to use.
=> [NFC] Move getTiedArgs into TritonGPU utils

test/TritonGPU/amd/amd-fold-true-cmpi.mlir, third_party/amd/lib/Analysis/RangeAnalysis.cpp
I made a mistake and didn't check the input/output types of the `arith.cmpi` so in some cases FoldTrueCmpI might fold tensors (e.g., masks). So we should guard against that.
=> [AMD] guard FoldTrueCmpI from tensors

README.md
The make target `dev-install-llvm` was added in #6709 to streamline the process of building custom LLVM and installing Triton using it. 
While I was building Triton, I encountered the glibc version mismatch issue (e.g., #7088, #6747, #3397), and I found the script super useful to build LLVM from source, so I suppose it would be useful to mention it on README.
=> [README] Mention `make dev-install-llvm` for custom LLVM build

lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp, lib/Dialect/TritonGPU/IR/Ops.cpp, test/TritonGPU/invalid.mlir
Before we were simply discarding the block during the lowering.
=> [BACKEND] Error when using CGA>1 on memdesc_subview

include/triton/Conversion/TritonGPUToLLVM/Utility.h
Description:
Just delete duplicate `i32_ty,i64_ty` macro definitions in `include/triton/Conversion/TritonGPUToLLVM/Utility.h`.
=> Delete duplicate macro definitions

python/src/gluon_ir.cc, python/triton/experimental/gluon/language/_semantic.py, python/triton/experimental/gluon/language/nvidia/blackwell/__init__.py, python/tutorials/gluon/01-attention-forward.py
* Pass `m_i` through tensor memory
* Use `FMUL2` instructions in correction partition
* For `DHEAD=128`, subtile `p` production in the softmax partition
* This allows us to scrounge a few extra registers for the correction partition (200->192)
* This allows ptxas to overlap the f32 to f16 downcast with the exp
* Reduce the number of instructions needed to apply causal masking
* Each element is produced with IADD3, conditional, and FSEL
=> [Gluon][Tutorial] Optimize attention kernel

test/Conversion/tritonnvidiagpu_to_llvm.mlir, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TMAToLLVM.cpp
A fence is currently missing after TMA update. Adding extra instruction to force the fence to be materialized.
Patch provided by @mbrookhart
=> [BACKEND] Add workaround for TMA device side descriptor race condition

test/Hopper/WarpSpecialization/ws_code_partition.mlir, third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/WSCodePartition.cpp, third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/WSLowerMem.cpp
When creating buffers, the layout required should be decided by the consumer. We were using mma layout previously and it broken the case where consumer wasn't actually a dot op.
=> [hopper][WS] Use required layout for buffers

lib/Conversion/TritonGPUToLLVM/Utility.cpp
This restores some of the code cleanliness improvements from 7218 without affecting functionality. Largely this is to keep a smaller bisectable diff to study the benchmark impacts of relanding 7218.
There is a slight functional change here -- we have the more liberal pattern-matching approach introduced by 7218 -- but I've tested on the internal benchmarks and it doesn't affect perf.
=> [NFC] Partially Revert "Partially Revert "[LAYOUTS] Enable diagonal iteration unconditionally (#7218)" (#7245)"

include/triton/Dialect/TritonGPU/Transforms/Schedule.h, lib/Dialect/TritonGPU/Transforms/Pipeliner/Schedule.cpp
Lately I've been working on AMD's pipelining and I've been looking at schedule dumps. They're great but unfortunately (due to `DenseMap`) not deterministic. This PR makes `opToStageAndCluster` a `MapVector` instead (which produces deterministic dumps).
=> [Pipelining] make schedule.dump deterministic

lib/Dialect/TritonGPU/Transforms/WarpSpecialization/LoadMMASpecialization.cpp, test/TritonGPU/load-mma-specialization.mlir
@ThomasRaoux fixed this for synchronous code but warp specialization needs to generate this when it splits the loop.
=> [Warp Specialization] Fix WAR async+generic proxy for warp spec

test/Conversion/tritongpu_to_llvm_volta.mlir, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/PatternTritonGPUOpToLLVM.h, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TritonGPUToLLVM.cpp
L2 cache hints are available in PTX only for sm >= 80. This PR will cause cache hints to be ignored for L2 on sm < 80.
Motivation: some Inductor tests are failing on sm75 due to cache hints added in Inductor: e.g.
https://github.com/pytorch/pytorch/actions/runs/15712699449/job/44296072018
=> [release 3.4] "[NVIDIA] L2 cache hints only for sm >= 80 (#7219)"

include/triton/Analysis/Membar.h, include/triton/Dialect/TritonNvidiaGPU/IR/Dialect.h
Fixes the `'mlir::MembarOrFenceAnalysis' has virtual functions but non-virtual destructor` warning that occurs due to adding a virtual function to the `MembarOrFenceAnalysis` base class. This error fails our `-Werror` check because we do not disable `non-virtual-dtor`.
I also fixed `warning: field 'numCols' will be initialized after field 'numRows'` since it showed up in my error trace, but this is not a warning that prompts errors, so there may be other locations where this warning is occurring.
=> Fix compiler warnings from Membar virtual function change

python/test/unit/language/test_core.py, third_party/amd/lib/TritonAMDGPUToLLVM/AtomicRMWOpsEmitter.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/AtomicRMWOpsEmitter.h, third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp
When using packed atomic ops, there are a few conditions to meet. The PR: https://github.com/triton-lang/triton/pull/6258 to refactor these checking added a condition to skip checking the condition and it introduced a bug (it missed the case that even lane tid access addresses not 4-byte aligned), so we need to always do that check. This PR is to change to always run `checkpairs`. 
=> [AMD] Always turn on `CheckPairs` to used packed fp16/bf16 atomic instructions

lib/Dialect/TritonGPU/IR/Dialect.cpp, test/TritonGPU/combine.mlir
The existing check was too loose because `SliceEncoding` will remove any unnecessary broadcasting in the register dimension, so you can have the parent encoding being split-able but it won't split to the same encoding as the slice encoding. In the test case this happens by having `sizePerThread=4` in the split dimension.
=> [Layouts] Fix split op backward propagation from slice encoding

lib/Dialect/Triton/Transforms/LoopAwareCSE.cpp, test/Triton/loop_cse.mlir
Turns out operations can have more than one result.
=> [Triton] Fix loop aware CSE not checking op result index

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td, lib/Dialect/TritonGPU/IR/Dialect.cpp
Swizzling is always disabled for Wmma's B operand, it should be disabled only when k dimension is not contiguous.
Both vectorSize, perPhase and maxPhase are now determined using a heuristic approach.
=> [AMD] Improve shared layout for Wmma's operands

python/test/unit/runtime/test_cache.py, python/triton/runtime/jit.py
This reverts #7332 as it essentially made the disk cache useless. Any function that calls another function lists it as a global value, and when printed that function includes the pointer to the python object which is not stable across different runs. Thus the cache always misses.
=> Revert "Include constexprs in cache keys, fixes #7322 (#7332)"

python/triton/runtime/autotuner.py
Fixes https://github.com/triton-lang/triton/pull/7306#issuecomment-3014002383
=> [Runtime] Fix triton_key import in autotuner disk caching

python/build_helpers.py
Current Triton uses a fixed build directory `f"cmake.{plat_name}-{sys.implementation.name}-{python_version}"` when installing with `pip install .`, when the same python is used, regardless of the venv target or source code version. This creates conflicts when
* Users switches Triton source version but did not clean the build directory.
+ This is a little hard to notice since most `pip install .` will use a temporary directory to build
* Users installing …
=> Allow out-of-tree build with environment variable TRITON_BUILD_DIR.

include/triton/Dialect/TritonGPU/Transforms/Schedule.h, lib/Dialect/TritonGPU/Transforms/Pipeliner/AssignLatencies.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/ScheduleLoops.cpp, test/TritonGPU/loop-pipeline-hip.mlir, test/TritonGPU/loop-pipeline.mlir, third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp
This PR exposes (via header) core pipelining utilities/helpers:
```c++
bool hasGpuBarriers(scf::ForOp forOp);
bool isSafeToPipeline(scf::ForOp forOp);
llvm::MapVector<Operation *, std::pair<int, Operation *>>
loadOpsToIndirectionLevel(scf::ForOp forOp, bool pipelineWithoutDot,
triton::ModuleAxisInfoAnalysis &axisInfoAnalysis,
int numStages, bool filterSmall = true);
void scheduleDistanceOneDependencies(scf::ForOp forOp,
CoarseSchedule &schedule);
void scheduleRemainingToLastStage(scf::ForOp forOp, CoarseSchedule &schedule,
CoarseSchedule::Cluster afterPrologue);
```
They are directly useable by AMD's pipeliner. 
Note, this is basically NFC for AMD because AMD's pipeliner simply had copy-paste of the same functions from ~last year (specifically somewhere around prior to this …
=> [AMD] expose core pipeliner utilities and integrate in AMD pipeliner

third_party/amd/backend/driver.c, third_party/amd/backend/driver.py
This commit switches the HIP backend to use hipGetProcAddress to query HIP symbols. This addresses the issue we had regarding hipGetDeviceProperties.
Note prepares for upcoming ROCm 7 release. It also drops support for ROCm 5 effectively.
=> [AMD] Use hipGetProcAddress to query HIP symbols

third_party/amd/backend/driver.c
It's dropped in https://github.com/triton-lang/triton/pull/7350 accidentally.
=> [AMD] NFC: Add back useful comments regarding HIP_SYMBOL_LIST

python/test/unit/runtime/test_cache.py, python/triton/runtime/jit.py
See #7332, this reinstates the change where constexprs are included in kernel cache keys, but only includes constexprs, and doesn't include the `id(var_dict)` which is nonpredictable. (from: `self.used_global_vals[(node.id, id(var_dict))] = (copy.copy(val), var_dict)`)
=> Include constexprs in cache keys, fixes #7322, reverts #7344

python/test/unit/language/test_core.py, third_party/amd/lib/TritonAMDGPUToLLVM/AtomicRMWOpsEmitter.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/AtomicRMWOpsEmitter.h, third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp
When using packed atomic ops, there are a few conditions to meet. The PR: https://github.com/triton-lang/triton/pull/6258 to refactor these checking added a condition to skip checking the condition and it introduced a bug (it missed the case that even lane tid access addresses not 4-byte aligned), so we need to always do that check. This PR is to change to always run `checkpairs`.
(cherry picked from commit 36b347301e182e7cfea862caa6805aa8cf4045ec)
Don't know if thing below is applicable to a cherry-pick, but I copied it from the original PR.
including the "tests should be minimal" …
=> [release/3.4] "[AMD] Always `CheckPairs` for packed fp16/bf16 atomic instructions (#7326)"

test/TritonGPU/amd/amd-fold-true-cmpi.mlir, third_party/amd/lib/Analysis/RangeAnalysis.cpp
Cherry-pick of 7281, original description:
I made a mistake and didn't check the input/output types of the arith.cmpi so in some cases FoldTrueCmpI might fold tensors (e.g., masks). So we should guard against that.
=> [release/3.4] "[AMD] guard FoldTrueCmpI from tensors (#7281)"

lib/Dialect/TritonGPU/Transforms/Utility.cpp, test/TritonGPU/accelerate-matmul.mlir
This patches a bug (https://github.com/pytorch/pytorch/issues/156028) which was introduced by #7066.
PromoteLHSToTMem.cpp, and is intended to extend it to support all MemDescViewTrait ops. However, in this refactor, support for tt.TransOp was dropped, changing the behavior of AccelerateMatmul.cpp.
This PR adds tt::TransOp back into the set of ops supported by comesFromLoadOrBlockArg.
i.e.:
* behavior before #7066: comesFromLoadOrBlockArg tracks loads past: ttg::ConvertLayoutOp, **tt::TransOp**
* behavior after #7066: comesFromLoadOrBlockArg tracks loads past: ttg::ConvertLayoutOp, ttg::MemDescSubview, ttg::MemDescTransOp, ttg::MemDescReshapeOp, ttg::MemDescReinterpretOp
* behavior after this PR: comesFromLoadOrBlockArg tracks loads past: ttg::ConvertLayoutOp, **tt::TransOp** …
=> [release/3.4] "[BACKEND] support tt::TransOp in comesFromLoadOrBlockArg (#7343)"

python/test/unit/language/test_conversions.py, third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp
Fix downcast to float8e5 on MI300.
This PR re-writes the following software conversions:
- FP16 -> FP8E5 RTNE
- FP32 -> FP8E5 RTNE
- BF16 -> FP8E5 RTNE
It adds additional steps for conversion to handle subnormal values and saturation mode.
=> [AMD] Fix downcast to float8e5 on MI300

python/test/unit/language/test_conversions.py
With https://github.com/triton-lang/triton/pull/7361,
these tests are now passing.
=> [AMD] Enable more passing fp8 downcast clamping tests

python/triton_kernels/tests/test_routing.py, python/triton_kernels/triton_kernels/routing.py, python/triton_kernels/triton_kernels/routing_details/_expt_data.py, python/triton_kernels/triton_kernels/routing_details/_routing_compute.py
This improves end-to-end routing performance by about 30%:
- fp32 logits: 22.8us --> 18.0us
- fp16 logits: 17.3us --> 12.2us
by a combination of several optimisations, including liberally fusing kernels in order to reduce the total number of launches from 7 to 4. Now, we only have four obligatory kernel launches:
- `_topk_forward`
- `_sum_bitmatrix_rows`
- `_combined_routing_memset`
- `_combined_routing_compute`
although in an expert-sharding world there are extra kernels inserted between `_topk_forward` and `_sum_bitmatrix_rows` in order to mutate the bitmatrix and update the other data structures produced by `_topk_forward`.
=> [BENCH] Routing improvements

third_party/amd/backend/driver.c
=> Fix gcc error: "did you forget to ‘#include <stdbool.h>’?"

python/test/unit/language/test_conversions.py
This change removes the default `cuda` value from the `device` argument in `test_typeconvert_downcast_clamping`.  Giving it a default value prevents you from setting it via the commandline.
=> Fix test_typeconvert_downcast_clamping 

python/triton_kernels/triton_kernels/reduction_details/reduce_bitmatrix.py, python/triton_kernels/triton_kernels/routing.py, python/triton_kernels/triton_kernels/topk_details/_topk_forward.py
This reduces routing runtime from 12.3us to 11.8us by tweaking block sizes and conditionally unrolling a loop if the number of iterations is small.
=> [BENCH] make MoE routing another 4% faster

lib/Conversion/TritonGPUToLLVM/Utility.cpp
There are several places in the codebase where we use the trick introduced in PR #4213 of calling `applyLinearLayout` once with the lane/warp/block indices and then XORing with many values (one for each register) obtained from `ll.apply`.
We begin by refactoring it out of the `emitIndices` function and will proceed to address the other places that this is used in the codebase.
Remarkably, the whole commit was written by GPT-4.5, requiring only very minimal feedback.
=> [NFC] Refactor XOR trick into helper function

python/test/unit/language/test_core.py, python/triton/language/standard.py, python/triton/runtime/interpreter.py
Related issue: #6635
I found `tl.max()` method didn't take `nan` as its output when there is any `nan` in the input tensor, but both `torch.max` and interpreter will output `nan` if it existed in the input.
it looks like:
```
tl.max("nan", "inf") = "inf"
torch.max("nan", inf") = "nan"
```
I thought it may bring some data consistency issue with torch, just like the issue I mentioned above.
<details>
<summary> Simple repro </summary>
```
import triton
import torch
@triton.jit
def max_kernel(X_ptr, Y_ptr, BLOCK_SIZE: tl.constexpr):
offsets = tl.arange(0, BLOCK_SIZE)  # [0, 1, ..., 63]
x = tl.load(X_ptr + offsets)        # Load 64 elements
max_val = tl.max(x, axis=0)         # Compute max across all 64 elements
if tl.program_id(0) == 0:
tl.store(Y_ptr, max_val) …
```
=> [INTERPRETER]  Fix tl.max consistency issue

include/triton/Conversion/TritonGPUToLLVM/Utility.h, lib/Conversion/TritonGPUToLLVM/Utility.cpp, lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp, test/Conversion/amd/tritongpu_to_llvm.mlir
For padded layouts introduced by https://github.com/triton-lang/triton/pull/7212 we need to add the padding to the base ptr of the resulting subview.
=> [BACKEND] Apply padding to memdesc_subview for PaddedSharedEncoding

python/test/unit/language/test_compile_errors.py, third_party/nvidia/backend/compiler.py
The original sizes (16 on N) are unnecessarily high
=> [NVIDIA] Update min_dot_sizes

include/triton/Conversion/TritonGPUToLLVM/Utility.h, include/triton/Tools/LinearLayout.h, lib/Conversion/TritonGPUToLLVM/Utility.cpp, test/Conversion/tritongpu_to_llvm.mlir, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp
Reopening https://github.com/triton-lang/triton/pull/7304
In this PR we rehash the lowering of cp.async to reuse the previous
optimisations.
=> [BACKEND] Move cp.async to better lowering sequence

lib/Conversion/TritonGPUToLLVM/Utility.cpp, test/Conversion/amd/tritongpu_to_llvm.mlir
We make the following modifications to `getSmemVecAddr`:
- replacing add with `_xor`;
- hoisiting the `_xor` out of the `applyLinearLayout`;
- fusing the two `applyLinearLayout`s together;
- vectorising the whole `getSmemVecAddr` function.
The combination of these changes enables us to avoid calling `applyLinearLayout` inside a loop within the function `emitTransferBetweenRegistersAndShared` and hopefully get better IR that leads to superior runtime performance.
=> [BACKEND] vectorise getSmemVecAddr

lib/Dialect/TritonGPU/IR/Ops.cpp, python/test/unit/language/test_core.py, test/TritonGPU/memdesc-subview-split.mlir
The current implementation allows one to split MemDescSubviewOp along a single dimension which may be not enough in some cases (e.g., ops refinement). We only need to forbid splitting subview along the swizzling pattern.
cc: @lezcano
Closes https://github.com/ROCm/triton-internal/issues/913
=> [AMD] Loosed constraints for MemDescSubviewOp

python/test/unit/language/test_core.py
Fix flaky `test_globaltimer ` on AMD introduced in #7282.
> FYI this may have added some flakiness to the CI - I have a failure here: https://github.com/triton-lang/triton/actions/runs/16141967476/job/45551308988?pr=6788 where rerunning it with no other changes resolved the issue. I also see that another submitted PR with unrelated changes has seen the same issue (https://github.com/triton-lang/triton/actions/runs/16139472771/job/45543368457) but runs after this are passing
_Originally posted by @vwbaker in https://github.com/triton-lang/triton/issues/7282#issuecomment-3048922698_
=> [WIP] Skip flaky `test_globaltimer` on gfx90a

python/test/gluon/test_frontend.py, python/triton/experimental/gluon/language/nvidia/blackwell/__init__.py, python/triton/language/semantic.py
In case mbars are provided to `blackwell.tcgen05_mma` while predicates are missing we need to convert python bools to ir values.
=> [GLUON] Fix and test for an issue with default mbar predicates for MMAv5

python/src/ir.cc, python/test/gluon/test_frontend.py
We are calling `ir.value()` in the `async_copy_global_to_shared`, however the default constructor for `value` was never defined, leading to a crash.
=> Fix ir generation for ttg.async_copy_global_to_local without mask

lib/Analysis/AxisInfo.cpp, test/Analysis/test-alignment.mlir
When `rhs` has a contiguity > 1, it's difficult to specialize conditions to get optimal divisibility estimates.
For example, `[128, 128 128, ..., 128] % [0, 1, 2, 3, ...] = [0, 0, 0, 2, ...]`
=> [ANALYSIS] Fix the divisibility of rem op with pessimistic analysis

python/tutorials/03-matrix-multiplication.py, third_party/amd/backend/compiler.py
- update AMD HIP autotune configs 
- add tl.assume for strides and pid_m and pid_n to enable buffer load for AMD backend.
- change matrix instruction default value
- [x ] I am not making a trivial change, such as fixing a typo in a comment.
- [x ] I have written a PR description following these
- [x ] I have run `pre-commit run --from-ref origin/main --to-ref HEAD`.
- [x ] This PR does not need a test because `FILL THIS IN`.
- [x ] I have not added any `lit` tests.
and using the instructions it generates is not …
=> [AMD] Update configs and add assume in matmul tutorial

python/src/llvm.cc, third_party/amd/backend/compiler.py, third_party/amd/python/triton_amd.cc
Architectures with the architected SGPRs feature (Just gfx12 for now) don't use sX registers for the program id,
but read from registers ttmp9 (X) and ttmp7(Y[15:0], Z[31:16]). As a result, the upper 16 bits of ttmp7 need to be masked when reading Y. This can be omitted when Z is not used. optimize_module infers this from existence of @llvm.amdgcn.workgroup.id.z() and creates the attribute `amdgpu-no-workgroup-id-z` for the backend.
`test_core.py:test_zero_strided_tensors` doesn't read Z, but still has thread blocks on that axis. I don't think we know for sure during compilation which dispatch dimensions are going to be used. We can query this feature directly from LLVM and just set all dimensions as used. This does not increase register pressure, because these registers are reserved …
=> [AMD] Correctly mask program_id(1) for architected SGPRs

setup.py
On my machine, I have libc 2.34 (suggesting I can use ubuntu-x86), but glibcxx 3.4.29 (the llvm build on ubuntu 22.04 bakes in a dependency on GLIBCXX >= 3.4.30). This env variable (TRITON_LLVM_SYSTEM_SUFFIX) would allow a user to specify ubuntu-x86, centos-x86, almalinux-x86, etc. to specify one of the prebuilt LLVM packages.
See also: #7431, which tries to automatically identify the llvm package based on GLIBCXX versions.
=> [build] TRITON_LLVM_SYSTEM_SUFFIX to allow user-specified prebuilt llvm system

python/test/unit/language/test_annotations.py, third_party/amd/backend/driver.py, third_party/nvidia/backend/driver.py
Fix #6176
```python
@triton.jit
def kernel(ptr, val: tl.float16):
tl.store(ptr, val)
ptr = torch.tensor([0.0], device="cuda:0")
kernel[1,](ptr, 42.0)
print(ptr)  
```
The issue is caused by naively passing a Python float to a Triton kernel that accepts `tl.float16`
Before this PR, the conversion chain for the float input looks like the following: 
```
PyArg_ParseTuple             incorrectly passed to
PyFloat ================> float      ----------!!!----------> kernel that accepts tl.float16  
```
This PR always makes `PyArg_ParseTuple` to parse Python float to C double, and then calls [`PyFloat_Pack{2,4,8}`](https://docs.python.org/3/c-api/float.html#pack-functions) to convert it to its proper storage type. 
```
PyArg_ParseTuple          PyFloat_Pack{2,4,8}                        passed …
```
=> [FRONTEND] Fix floating points argument passing 

python/test/unit/language/test_core.py
Our CI hit an overflow issue in reduce test case with Triton Interpreter.
```
FAILED language/test_core.py::test_reduce1d[4-1-1-sum-int32-32] - triton.runtime.errors.InterpreterError: InterpreterError("OverflowError('Python integer -4736833654 out of bounds for int32')")
FAILED language/test_core.py::test_reduce1d[4-1-1-sum-int32-64] - triton.runtime.errors.InterpreterError: InterpreterError("OverflowError('Python integer -17340316748 out of bounds for int32')")
FAILED language/test_core.py::test_reduce1d[4-1-1-sum-int32-128] - triton.runtime.errors.InterpreterError: InterpreterError("OverflowError('Python integer -15950412024 out of bounds for int32')")
FAILED language/test_core.py::test_reduce1d[4-1-1-sum-int32-512] - triton.runtime.errors.InterpreterError: …
```
=> [NFC] Limit the range of integers so that the sum does not overflow in reduce test case

include/triton/Analysis/Utility.h, include/triton/Dialect/TritonGPU/IR/Dialect.h, include/triton/Dialect/TritonGPU/IR/LinearLayoutConversions.h, lib/Analysis/Allocation.cpp, lib/Analysis/AxisInfo.cpp, lib/Analysis/Utility.cpp, lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp, lib/Conversion/TritonGPUToLLVM/GatherOpToLLVM.cpp, lib/Conversion/TritonGPUToLLVM/MemoryOpToLLVM.cpp, lib/Conversion/TritonGPUToLLVM/Utility.cpp, lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp, lib/Dialect/Triton/IR/Traits.cpp, lib/Dialect/TritonGPU/IR/Dialect.cpp, lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp, lib/Dialect/TritonGPU/IR/Ops.cpp, lib/Dialect/TritonGPU/Transforms/CoalesceAsyncCopy.cpp, lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp, lib/Dialect/TritonNvidiaGPU/IR/Dialect.cpp, third_party/amd/lib/Dialect/TritonAMDGPU/IR/Dialect.cpp, third_party/amd/lib/TritonAMDGPUDialectToLLVM/ConcatOpToLLVM.cpp, third_party/amd/lib/TritonAMDGPUDialectToLLVM/ExtractSliceOpToLLVM.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/Utility.cpp, third_party/amd/lib/TritonAMDGPUTransforms/CoalesceAsyncCopy.cpp, third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp, third_party/amd/lib/TritonAMDGPUTransforms/UpdateAsyncWaitCount.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/MemoryOpToLLVM.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TensorMemoryToLLVM.cpp
This PR is an NFC that mostly improves readability and usability.
There are a few places where we bend ourselves backward to pass the
full type to `toLinearLayout` tho. This is because this PR is in
preparation for the next PR where we fix `memdesc_subview` at large. To
be able to do this, we need the `allocationShape` from `MemDescType` to
create the associated `LinearLayout`, so this was the cleanest way to
make sure we don't introduce any subtle error.
=> [NFC] Make `toLinearLayout` take a `RankedTensorType` or `MemDescType`

python/src/gluon_ir.cc, python/test/gluon/test_frontend.py, python/triton/experimental/gluon/language/_core.py, python/triton/experimental/gluon/language/_semantic.py
This flag causes the frontend to check that the layout conversion ends up being trivial, i.e. at most registers are reordered within a lane. This is useful when writing kernels and managing layout restrictions of different ops that happen to work out to being trivial without having to worry about accidental performance regressiosn.
=> [Gluon] Add `assert_trivial` flag to `ttgl.convert_layout`

python/test/unit/language/test_frontend.py, python/triton/runtime/jit.py
This PR changes the dependencies finder to not infinitely loop when the unspecialized call graph has a cycle. This allows a function to recurse on a specialized version of itself. This allows neat patterns when writing code, i.e. progressively splitting an arbitrary tensor down to N elements, etc.
=> [Frontend] Enable specialized recursion

third_party/proton/test/unittest/util/trace_gen.py
https://github.com/triton-lang/triton/pull/7475 enforced Gluon semantic to be enabled by default, which results in the following error:
```py
def loop_kernel():
for k in range(0, 20):
pl.enter_scope("r0")
^
Unsupported semantic type: <class 'triton.language.semantic.TritonSemantic'>. Supported semantics are: {<class 'triton.experimental.gluon.language._semantic.GluonSemantic'>}
```
This PR attempts to fix that.
=> [PROTON-DEV] Enable Triton semantic for `trace_gen.py`

third_party/amd/backend/driver.py, third_party/nvidia/backend/driver.py
Fix issue found by @anmyachev  at https://github.com/triton-lang/triton/pull/7439
> Should it be like: `_PyFloat_Pack2(f, (unsigned char *)&result, 1);`? (this is how it is implemented in https://github.com/python/pythoncapi-compat/blob/b541b98df1e3e5aabb5def27422a75c876f5a88a/pythoncapi_compat.h#L488)
> 
> I see the following issue with current approach:
> 
> ```shell
> python/test/unit/language/test_annotations.py /tmp/tmp9qfrehja/main.cpp:148:5: error: no matching function for call to '_PyFloat_Pack2'
>   148 |     _PyFloat_Pack2(f, (void*)&result, 1);
>       |     ^~~~~~~~~~~~~~
> /home/jovyan/.conda/envs/xpu/include/python3.10/floatobject.h:87:17: note: candidate function not viable: cannot convert argument of incomplete type 'void *' to
>       'unsigned char *' for 2nd argument
> …
```
=> [FRONTEND] Fix PyFloat_Pack2 casting

include/triton/Dialect/Gluon/Transforms/Passes.td, include/triton/Dialect/TritonGPU/Transforms/Passes.td, lib/Dialect/Gluon/Transforms/CMakeLists.txt, lib/Dialect/Gluon/Transforms/Canonicalize.cpp, lib/Dialect/Gluon/Transforms/Inline.cpp, lib/Dialect/Gluon/Transforms/ResolveAutoEncodings.cpp, lib/Dialect/TritonGPU/Transforms/CMakeLists.txt, python/src/passes.cc, python/test/gluon/test_frontend.py, python/triton/_filecheck.py, python/triton/experimental/gluon/language/_core.py, python/triton/experimental/gluon/language/_semantic.py, test/Gluon/auto_encoding.mlir, third_party/amd/backend/compiler.py, third_party/nvidia/backend/compiler.py
<git-pr-chain>
[Gluon] Broadcast auto with concrete layouts
This also makes `arange` return auto layout by default, so you can do
for example:
```python
xidx = gl.arange(0, 32)[:, None]
yidx = gl.arange(0, 16)[None, :]
off = xidx * x_stride + yidx * y_stride
off = gl.convert_layout(off, concrete_layout)
```
I also fixed `filecheck_test` to disable the overflow sanitizer, as it
can cause lit tests to fail if the check statements match with the
overflow sanitizer ops.
1. #7489
1. #7490
1. 👉 #7491 👈 **YOU ARE HERE**
=> [Gluon] Broadcast auto with concrete layouts

lib/Target/LLVMIR/CMakeLists.txt, python/src/passes.cc, python/test/unit/language/test_tensor_descriptor.py, test/Conversion/nvgpu_to_llvm.mlir, test/Conversion/tritongpu_to_llvm.mlir, test/Conversion/tritongpu_to_llvm_hopper.mlir, third_party/nvidia/backend/compiler.py, third_party/nvidia/include/Dialect/NVGPU/IR/NVGPUOps.td, third_party/nvidia/lib/NVGPUToLLVM/NVGPUToLLVMPass.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/BarrierOpToLLVM.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/MemoryOpToLLVM.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.cpp
This change replaces some NVGPU ops with the corresponding NVVM ops. It aligns with previous discussions in PR #7420.
For some op like NVGPU::FenceAsyncSharedOp, there is no corresponding Intrinsic, and LLVM will also generate PTX. However, in the long run, I think it is better to hand over the responsibility of generating code to LLVM instead of hard coding PTX at the NVGPU layer.
The ConvertNVVMToLLVMPass has been added to the pipeline and build system so that NVVM ops are correctly lowered to LLVM IR.
and …
=> [NVIDIA] Replace some NVGPU ops with equivalent NVVM ops (part 2)

include/triton/Dialect/Gluon/IR/CMakeLists.txt, include/triton/Dialect/Gluon/IR/Dialect.h, include/triton/Dialect/Gluon/IR/GluonOps.td, lib/Dialect/Gluon/IR/CMakeLists.txt, lib/Dialect/Gluon/IR/Dialect.cpp, lib/Dialect/Gluon/Transforms/ResolveAutoEncodings.cpp, python/src/gluon_ir.cc, python/test/gluon/test_frontend.py, python/triton/_filecheck.py, python/triton/experimental/gluon/language/_core.py, python/triton/experimental/gluon/language/_semantic.py, test/Gluon/auto_encoding.mlir, test/Gluon/invalid_auto_encoding.mlir
<git-pr-chain>
[Gluon] Add dedicated set_auto_layout op
Instead of reusing `ttg.convert_layout`, this changes auto layouts
to only propagate from the gluon.set_auto_layout operation. Not only
does this make the purpose a bit clearer, it also allows us to:
1. Prevent DCE by making it impure, so you can ignore the return value
and it will still set the encoding.
2. Express an allowed conversion without creating a conflict, e.g.:
```python
a = ...
ttgl.set_auto_layout(a, layout)
ttgl.store(ptrs, ttgl.convert_layout(a, ptrs.layout))
```
which does the computation in one layout and the store in
another.
1. 👉 #7504 👈 **YOU ARE HERE**
=> [Gluon] Add dedicated set_auto_layout op

test/Conversion/tritonnvidiagpu_to_llvm.mlir, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/BarrierOpToLLVM.cpp
When the `wait_barrier` predicate ends up being true, either generated from Gluon or for some other optimization, generate the non-predicated version of the instruction, which is slightly more efficient due to 1 less branch. I observed a speedup of like 3 TFLOPS on the attention kernel because of this. It was stable and reproducible and not just noise.
=> [Backend] Check if `wait_barrier` is a constant true

third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp
Splits `createAndScheduleAsyncCopy` and `createAndScheduleStreamCopy` to make it reusable if we want to schedule the ops differently in a future PR.
=> [AMD][NFC] Refactor createAndSchedule* in stream pipeliner into two functions

python/test/unit/language/test_annotations.py, third_party/amd/backend/driver.py, third_party/nvidia/backend/driver.py
Fix #6176
```python
@triton.jit
def kernel(ptr, val: tl.float16):
tl.store(ptr, val)
ptr = torch.tensor([0.0], device="cuda:0")
kernel[1,](ptr, 42.0)
print(ptr)
```
The issue is caused by naively passing a Python float to a Triton kernel that accepts `tl.float16`
Before this PR, the conversion chain for the float input looks like the following:
```
PyArg_ParseTuple             incorrectly passed to
PyFloat ================> float      ----------!!!----------> kernel that accepts tl.float16
```
This PR always makes `PyArg_ParseTuple` to parse Python float to C double, and then calls
[`PyFloat_Pack{2,4,8}`](https://docs.python.org/3/c-api/float.html#pack-functions) to convert it to its proper storage type.
```
PyArg_ParseTuple          PyFloat_Pack{2,4,8}                        passed to …
```
=> [release/3.4] [FRONTEND] Fix floating points argument passing  (#7439)

.github/workflows/integration-tests-nvidia.yml
gb200 is broken at the moment, this should allow the rest of CI to still run.
=> [CI] Continue running CI when gb200 errors out

python/triton/experimental/gluon/language/_layouts.py, python/tutorials/gluon/01-attention-forward.py
<git-pr-chain>
[Gluon] Add NVMMASharedLayout constructor with default swizzle choice
This mirrors the attribute builder here:
https://github.com/triton-lang/triton/blob/1031dc78060fc5f63c3fbcdd04d495d2428bc862/include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td#L480
1. 👉 #7534 👈 **YOU ARE HERE**
1. #7535
1. #7536
=> [Gluon] Add NVMMASharedLayout constructor with default swizzle choice

include/triton/Dialect/TritonGPU/Transforms/Utility.h, lib/Dialect/TritonGPU/Transforms/Utility.cpp, test/TritonGPU/loop-pipeline-hip.mlir, test/TritonGPU/loop-pipeline.mlir, third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp
Further refactoring of Streampipeliner.cpp to use more common pipeliner functionality: `triton::createAllocation`, `triton::createSingleBufferView`, `triton::replaceWithSharedLoad` and a bit of general cleanup.
Overall NFC except:
- The order of LocalDealloc is reversed now
- The memdesc of the subview additionally includes the allocSize
Also we had no lit test checking that the LocalLoad consumes the AsyncToken so I adjusted one to include the check.
=> [AMD][BACKEND] Refactor Streampipeliner to use more common functions

include/triton/Conversion/TritonGPUToLLVM/Utility.h, include/triton/Tools/LayoutUtils.h, lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp, lib/Conversion/TritonGPUToLLVM/MemoryOpToLLVM.cpp, lib/Conversion/TritonGPUToLLVM/Utility.cpp, lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp, lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp, lib/Tools/LayoutUtils.cpp, lib/Tools/LinearLayout.cpp, python/test/unit/language/test_core.py, test/Conversion/amd/tritongpu_to_llvm.mlir, test/Conversion/tritongpu_to_llvm.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandHelper.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandHelper.h, third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandWMMA.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/MMAHelpers.h, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/MMAv5.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/WGMMA.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/MemoryOpToLLVM.cpp, unittest/Tools/LinearLayoutTest.cpp
Layouts coming from `memdesc_subview` are at heart affine layouts.
This is because partial evaluation of a linear map on some variables
gives you an affine map. More concretely, if `c` is a constant
and `x` is a variable, we have that `A(x ^ c) = A(x) ^ A(c)` where
`A(c)` is a constant. In `memdesc_subview`, `A` is the map from the
matrix into shared memory (the inverse of the shared memory linear layout)
and `c` are the offsets given in the IR of `memdesc_subview`.
Previously `memdesc_subview` would advance the pointer as `ptr += A(c)`.
This is incorrect, as the actual formula for the address is given by
`ptr + (A(c) ^ A(x))`, so we compensated for this when computing the
address by substracting the offsets and adding them as an xor …
=> [BACKEND] Don't accumulate the offsets from memdesc_subview on the base

third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp
Mostly moves code around to reduce the dependencies between functions and further splits up functions doing more than one thing (`createAndSchedule*`,` preprocessAndBuildSchedule`). This will also allow us to use more common pipeliner functionality in a future PR, e.g. `createAsyncCopy`.
=> [AMD][BACKEND] Refactor stream pipeliner to better encapsulate functions

include/triton/Dialect/TritonNvidiaGPU/Transforms/Utility.h, lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/CMakeLists.txt, lib/Dialect/TritonNvidiaGPU/Transforms/Utility.cpp, test/NVWS/invalid.mlir, test/NVWS/lower_aref.mlir, test/NVWS/ops.mlir, third_party/nvidia/include/Dialect/NVWS/IR/Dialect.h, third_party/nvidia/include/Dialect/NVWS/IR/NVWSAttrDefs.td, third_party/nvidia/include/Dialect/NVWS/IR/NVWSOps.td, third_party/nvidia/include/Dialect/NVWS/IR/NVWSTypes.td, third_party/nvidia/lib/Dialect/NVWS/IR/Ops.cpp, third_party/nvidia/lib/Dialect/NVWS/Transforms/LowerAref.cpp
* Update arefs ops to align with [`nvws`](https://github.com/triton-lang/triton/tree/aref_auto_ws) branch.
* Update lower_aref pass to:
    -  threads aref-index through control flow ops (aref-index is used to compute both stage and mbarrier phase)
    -  lowers arefs to mbarriers
    -  [TODO]: add support for `tma_load` aref lowering, and lowering `nvws::arrive_barrier` will be added in subsequent PRs enabling e2e functionality
* Updated lit-tests
cc: @masahi, @htyu, @manman-ren, @jeffniu-openai 
and using the …
=> [WS] Update aref ops and lower_aref pass 

lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp, test/Conversion/amd/convert_layout.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/OptimizeLDSUsage.cpp
This PR:
- Enables ConvertLayoutOp general swizzling for AMD
- Introduces simple heuristic in OptimizeLDSUsage so we use padding based swizzling only if it is required to reduce LDS consumption
- Adds AMD specific ttg->llvm conversion pattern to process forced padding separately from general swizzling
=> [AMD] Enable General Swizzling ConvertLayoutOp

third_party/amd/backend/driver.py, third_party/nvidia/backend/driver.py
`ldconfig -p` can cause failures on EKS / Ubuntu where ldconfig on /bin/sh is not guaranteed to produce valid utf-8. Just ignore the bad bytes and parsing is still ok.
This was the error:
```
libs = subprocess.check_output(["/sbin/ldconfig", "-p"]).decode()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 60334: invalid continuation byte
```
Slightly trivial but causing major failures forcing us to parse ldconfig elsewhere with a parser that can handle bad utf-8?
including the "tests should be minimal" section. …
=> [BACKEND] Ignore bad bytes in ldconfig -p

third_party/amd/backend/compiler.py, third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp
Disable merging async_wait when pipelining with num_stages=3.
This is to avoid incorrect operation order by combineRedundantWaitOps.
=> [AMD][BACKEND] restrict merging async_wait in streamPipeliner

docs/getting-started/installation.rst
I noticed the install commands on [the docs](https://triton-lang.org/main/getting-started/installation.html#python-package) are outdated (executing them as-is gives `triton/python does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.`).
This PR updates those instructions to match those currently in the readme, specifically:
- Install from `pip install -e python`  to `pip install -e .`
- Wheels from `CPython 3.8-3.12 and PyPy 3.8-3.9.` to `CPython 3.9-3.13.` (match readme)
- Removes the nightly installation instruction
- Tests to the new `make dev-install; make test; make test-nogpu` setup
- `/python/test` for end-to-end …
=> [DOC] Update install instructions in docs

python/triton_kernels/triton_kernels/matmul_ogs.py
This check is already done in the swizzling/unswizzling function so no
need to repeat it here.
=> [KERNELS] Remove incorrect check

python/triton/knobs.py
We're currently updating the internal Triton version at Meta, and one of the things that process has flushed out is that there has been some regression in compile time since 3.2. One of the main culprits is `NvidiaTool.from_path`; we call it all the time under the hood, and each time it spawns a subprocess just to check the version. The benchmark I'm using is a torch.compiled'd model with ~300 kernels, and this change saves about 10% off of the overall compile time.
I don't have strong feelings on how defensive to be here. I picked a middle-of-the road level where I guard `PATH`, but don't go crazy guarding against every conceivable level of magic. (I think the existing knobs unit tests are pretty representative of what one might expect of "reasonable" behavior, but let me know if you'd …
=> Cache NvidiaTool.from_path

python/triton/runtime/jit.py
Triton calls `inspect.getsource/getsourcelines` a fair amount during compilation. The second call in `JITFunction.__init__` is completely redundant since `getsource` just calls `getsourcelines` under the hood, and caching the source lines on `JITFunction` also lets you skip the calls in `get_jit_fn_file_line`. `getsource` is quite expensive, so this saves >5% of the overall compile time. (Sadly, I think this is the last of the easy compile time wins.)
=> Remove redundant calls to inspect.getsource

python/triton_kernels/tests/test_tensor_details/test_layout_hopper.py
This test was merged with AMD CI failing and it's now blocking merges. See #7591
=> [KERNELS] Skip test_upcast_mxfp4_to_bf16 on AMD

python/test/unit/language/test_compile_only.py
After #7521 this test could fail when TRITON_DISABLE_LINE_INFO=0 The CI sets TRITON_DISABLE_LINE_INFO=1 so variable names wouldn't be generated and the test would pass just with the \d+ regex.
An example is this:
```
; this one is ok
%14 = tt.load %9 : tensor<64x64x!tt.ptr<f16>, #blocked1> loc(#loc9)
; with variable name regex fails
%a = tt.load %a_ptr_9 : tensor<64x64x!tt.ptr<f16>, #blocked1> loc(#loc26)
```
Other tests seem to be already using \w so they are ok.
=> [Tests] Improve regex for test_compile_only_dot

python/triton_kernels/bench/bench_mlp.py
`opt` is empty for if the testing platform is rocm. I suppose we don't do layout conversion in this case.
=> [KERNELS] Fix `bench_mlp.py` for AMD

lib/Dialect/TritonGPU/Transforms/Pipeliner/PipeliningUtility.cpp, test/TritonGPU/loop-pipeline-combine-waits.mlir, third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp
`combineRedundantWaitOps` did skip over branches/loops, so if we end up with something like:
```mlir
ttg.async_wait
scf.for
....
scf.yield
ttg.async_wait
```
we merge the async_waits in the prologue and epilogue because we do not find a `ttg.commit_group` in between. This PR stops the forward search if we encounter a branch/loop. I can also walk through all successor blocks if we think this is worth the effort.
This problem was not triggered before because the `ttg.async_wait` was scheduled in the same stage as its user(s) so we ended up with no `ttg.async_wait` in the prologue or there was another prefetch after it in the prologue.
Since https://github.com/triton-lang/triton/pull/7458 we might place the `ttg.async_wait` in the previous stage compared to its user(s) so we might end up …
=> [BACKEND] combineRedundantWaitOps should not combine across loops/branches

test/TritonGPU/loop-pipeline-hip.mlir, third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp
NFC: Groups all scheduling related function to a namespace to prepare for additional scheduling variants.
=> [NFC][AMD][BACKEND] Group scheduling functions in StreamPipeliner

third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp
This conversion can lead to an overflow when subtracting 1 when the signed bit is set. Change to uint32. This is caught when running Conversion/amd/fp_to_fp.mlir with asan
=> Fix f32->f8 overflow

docs/programming-guide/chapter-3/debugging.rst
The URL pointing to the AMD ROCm AddressSanitizer documentation was outdated, leading to a "Page Not Found" error.
This PR updates the hyperlink to the correct and current documentation page, ensuring users can access these important debugging resources for AMD GPUs.
---
  [rules](https://cbea.ms/git-commit/#why-not-how).
  - [ ] I have added tests.
  - [x] This PR does not need a test because **it only fixes a broken hyperlink in the documentation and does not alter any code functionality.**
  - [x] I have not added any `lit` tests.
  - [ ] The `lit` tests I have added follow these [best practices](https://mlir.llvm.org/getting_started/TestingGuide/#filecheck-best-practices),
    including the "tests should be minimal" …
=> docs: Fix broken link for ROCm AddressSanitizer

include/triton/Dialect/TritonGPU/Transforms/PipeliningUtility.h, lib/Dialect/TritonGPU/Transforms/Pipeliner/PipeliningUtility.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/SoftwarePipeliner.cpp, third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp
This PR prepares the infrastructure for handling masked operations in AMD backend, by moving MaskOp handling functions into the shared pipeline utilities in order to utilize them.
Fixes: https://github.com/ROCm/triton-internal/issues/1016
=> [AMD]: Use ttg.mask operator in AMD backend

include/triton/Dialect/TritonNvidiaGPU/IR/Dialect.h, include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOpInterfaces.td, lib/Dialect/TritonNvidiaGPU/IR/Dialect.cpp, lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp, lib/Dialect/TritonNvidiaGPU/Transforms/TensorMemoryAllocation.cpp, python/test/gluon/test_frontend.py, python/test/unit/blackwell/test_tmem.py, python/triton/experimental/gluon/language/_core.py, python/triton/experimental/gluon/language/nvidia/blackwell/__init__.py, test/Conversion/tritongpu_to_llvm_blackwell.mlir, third_party/nvidia/lib/NVGPUToLLVM/NVGPUToLLVMPass.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TensorMemoryToLLVM.cpp
There are a few restrictions: the subslice has to be at least 64x2. This is enforced by the fact that you can't actually construct the right layout for this at the moment. The second restriction is the N for the split must be even, otherwise it slices into one of the 64x2 chunks.
=> [Backend] Allow splitting block_m=64 TMEM along N

lib/Dialect/TritonGPU/Transforms/HoistTMEMAlloc.cpp, test/TritonGPU/hoist-tmem-alloc.mlir
When we have multiple tmem load being sinked to the same point we could run into an infinite loop and have the pattern not converge.
=> [BACKEND] Make sure tmem load sink pattern converges

python/triton_kernels/triton_kernels/compaction_details/_masked_compaction.py
```
tl.where with a non-boolean condition is deprecated and will error out in a future triton release. Got int64
```
=> [KERNELS] Fix warnings from `tl.where`

third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/FMA.cpp, third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp
This PR fixes language/test_matmul.py::test_simple_matmul failures for fp64 on RDNA4. 
There were 4 failing test cases of the form test_matmul.py::test_simple_matmul[float64 - float64], These failures were specific to the RDNA4 backend and are now resolved by this PR.
=> [AMD] Fix matmul unit test failure on RDNA4

third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TensorMemoryToLLVM.cpp
Somehow optimizing this code when we know the number of warp groups is 1 results in major performance regressions...
=> [Blackwell] Fix perf regression

python/triton_kernels/tests/test_matmul.py, python/triton_kernels/triton_kernels/matmul_ogs.py, python/triton_kernels/triton_kernels/matmul_ogs_details/_finalize_matmul.py, python/triton_kernels/triton_kernels/matmul_ogs_details/_matmul_ogs.py, python/triton_kernels/triton_kernels/matmul_ogs_details/_p_matmul_ogs.py, python/triton_kernels/triton_kernels/matmul_ogs_details/opt_flags.py, python/triton_kernels/triton_kernels/numerics_details/mxfp.py, python/triton_kernels/triton_kernels/numerics_details/mxfp_details/_downcast_to_mxfp.py, python/triton_kernels/triton_kernels/tensor.py
Not (yet) optimized matmul with mxfp8 act input and output (e.g., mxfp8 act input/output not supported with persistent kernel yet).
A few noteables:
* Not working with Hopper swizzling (but is working with Blackwell weight value/scale swizzling)
* Reusing actual_scale that is used for flexscale to pass mx scale in a couple of places not to grow number of arguments
=> [rfc] mxfp act in and out matmul (not for persistent kernel yet)

lib/Conversion/TritonGPUToLLVM/Utility.cpp
https://github.com/triton-lang/triton/pull/7636 changed function signature but https://github.com/triton-lang/triton/pull/7460 wasn't picking  it up before landing.
=> [Backend] Fix build due to mid air collision

test/Conversion/cvt_to_llvm.mlir, test/Conversion/gather_to_llvm.mlir, test/Conversion/gather_to_llvm_warp1.mlir
We split the gather file into two to be able to use different modules
for different warp sizes and be able to pipe them to opt.
=> [TESTING] Reenable two lit tests

.github/workflows/integration-tests-amd.yml
This helps to isolate GPUs used for different
CI job runs to avoid out of memory issues.
=> [CI][AMD] Add env-file for better GPU isolation

test/NVWS/lower_aref.mlir, test/TritonGPU/rewrite-partition-dependencies.mlir, third_party/nvidia/include/Dialect/NVWS/Transforms/Passes.td, third_party/nvidia/lib/Dialect/NVWS/Transforms/LowerAref.cpp
* add support for multiple consumers group for a single producer in `lower-aref` pass
- [ X I have run `pre-commit run --from-ref origin/main --to-ref HEAD`.
=> [NVWS] add support for multiple consumers in aref-lowering

third_party/proton/csrc/lib/Profiler/RocTracer/RoctracerProfiler.cpp
In apiCallback() function case HIP_API_ID_hipStreamBeginCapture is missing a 'break' and causing unintentional fall-through to HIP_API_ID_hipLaunchKernel.
- [x ] I have written a PR description following these
- [] This PR does not need a test because ``.
=> Fix the missing 'break' in RoctracerProfiler

include/triton/Dialect/Triton/IR/TritonOps.td, lib/Dialect/Triton/IR/Ops.cpp
The upstream LLVM has deprecated ArrayRef(std::nullopt_t).  This CL
migrates away from that.
=> Migrate away from llvm::ArrayRef(std::nullopt_t)

python/triton_kernels/bench/bench_mlp.py
=> [KERNELS] Fix roofline plots for kernels that are only compute-bound

third_party/amd/backend/driver.py, third_party/nvidia/backend/driver.py
We recently fixed this for XPU backend, maybe it will be useful for other backends.
=> Use int8_t C++ type for bool kernel args

include/triton/Dialect/TritonInstrument/IR/CMakeLists.txt, include/triton/Dialect/TritonInstrument/IR/Dialect.h, include/triton/Dialect/TritonInstrument/IR/TritonInstrumentAttrDefs.td, include/triton/Dialect/TritonInstrument/IR/TritonInstrumentOps.td, lib/Conversion/TritonInstrumentToLLVM/CMakeLists.txt, lib/Conversion/TritonInstrumentToLLVM/InstrumentationToLLVM.cpp, lib/Dialect/TritonInstrument/IR/Dialect.cpp, lib/Dialect/TritonInstrument/IR/Ops.cpp, lib/Dialect/TritonInstrument/Transforms/ConcurrencySanitizer.cpp, python/test/gluon/test_consan.py, test/Conversion/tritoninstrument_to_llvm.mlir, test/TritonGPU/consan.mlir
This PR covers three main changes to Concurrency Sanitizer:
1. Adding support for Tensor Memory - implementation between shared and tensor memory is 95% common
2. Adding support for writes tracked by multiple buffers and tcgen05_commit. Commit mechanism is generic and is modeled fairly close after HW - any 'outstanding' write (one that hasn't been waited on yet) is started to be tracked by a barrier when the commit is called.
3. Implicit HW pipelining of tcgen05 operations. For now modeled loosely, by creating a class of ops that are "hwPipelined", and these ops do not assert when they write to a mem being written by another "hwPipelined" op. This is in general overly optimistic, as hw pipelining is not commutative, and also dependent on the operands. We can decide if we need to make this …
=> [ConSan] Add support for Tensor Memory

lib/Dialect/TritonGPU/Transforms/WarpSpecialization/RewritePartitionDependencies.cpp, test/TritonGPU/rewrite-partition-dependencies.mlir
There are realistic cases where this should be more than 1, but let's fix it to 1 for now since that's what happens in practice.
=> [Warp Spec] Always use 1 buffer for SSA partition dependencies

Makefile
The previous command (`$(realdir .llvm-project/build)`) works only if .llvm-project/build already exists. The new command will get the absolute path of the directory in which the Makefile exists, and then append `.llvm-project/build`.
=> [build] fix local llvm build when .llvm-project/build doesn't exist

lib/Dialect/TritonGPU/Transforms/WarpSpecialization/Partition.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/PartitionScheduling.cpp, test/TritonGPU/partition-scheduling.mlir, test/TritonGPU/rewrite-partition-dependencies.mlir
This PR adds a small optimization step to partitioning that transforms
```mlir
%x = producer() partition=0
%y = broadcast %x : <Axf32> -> <AxBxf32> partition=0
use(%y) partition=1
```
Into
```mlir
%x = producer() partition=0
%y = broadcast %x : <Axf32> -> <AxBxf32> partition=1
use(%y) partition=1
```
To reduce the amount of shared memory needed.
=> [Warp Spec] Optimize partitioning by hoisting above broadcasts

python/triton/runtime/_allocation.py, third_party/nvidia/backend/driver.py
This changes the allocator state to a `ContextVar` which is thread-local, so calling it from different threads won't cause a race.
Note that this does mean you won't inherit allocators in child threads, and instead would need to set it in each thread independently. For most use cases this is probably fine though.
=> [Runtime] Make `set_allocator` thread safe

python/test/unit/runtime/test_bindings.py, python/triton/_filecheck.py, python/triton/compiler/compiler.py, python/triton/experimental/gluon/_runtime.py
This allows us avoid duplicating target parsing logic in different places, e.g., when in Gluon we don't need to parse it again from backend options.
=> [Backend] Pass GPUTarget to make_ir

lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp, test/Conversion/amd/tritongpu_to_llvm.mlir
https://github.com/triton-lang/triton/pull/7622 introduced `ttg.memdesc_index` which applies a constant offset to the base pointer of the smem object. For padded layouts we need to add padding based on the offset, similar to what https://github.com/triton-lang/triton/pull/7404 did for the old subview operation.
I also adjusted the lit test to check we actually generate padding from the ttg.memdesc_index. The previous version did not fail because it matched the lowering of the `ttg.local_load/store` as well.
=> [BACKEND] Apply padding when lowering ttg.memdesc_index 

test/Conversion/amd/buffer_load_to_local_to_llvm.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp
We can only bypass ds_bpermute to apply the swizzling if lanes loading the same row read a contiguous chunk of memory from HBM, which we cannot infer when lowering to LLVM.
The current selection does only check if the elements for each lane are contiguous which is not strict enough.
=> [AMD][BACKEND] Remove bypass permute optimization for AsyncCopy

include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td, python/test/gluon/test_frontend.py, python/triton/_filecheck.py, python/triton/runtime/jit.py
This changes all gluon frontend tests to use `run_parser`. To achieve this, I also expand `run_parser` to support kernel arguments and non-blackwell targets.
This also allows us to test with the gfx1200 hip target which also has 32 threads per warp.
Closes #7667
=> [Gluon][Tests] Make frontend tests independent of the active target

lib/Dialect/Triton/Transforms/Combine.cpp, lib/Dialect/Triton/Transforms/Combine.td
=> [BACKEND] Rewrite tablegen combine into cpp patterns

python/triton/runtime/interpreter.py
Ref: https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__TENSOR__MEMORY.html#group__CUDA__TENSOR__MEMORY_1ga7c7d2aaac9e49294304e755e6f341d7
Note there is a formatting error in the docs, all tensor descriptors regardless of dtype need to satisfy:
```cpp
globalStrides[0] = globalDim[0] * elementSizeInBytes(tensorDataType) + padding[0];
for (int i = 0; i < tensorRank - 1; i++) {
globalStrides[i] = globalStrides[i – 1] * (globalDim[i] + padding[i]);
assert(globalStrides[i] >= globalDim[i]);
}
```
=> [TensorDesc] Add extra stride validation to interpreter

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td, include/triton/Dialect/TritonNvidiaGPU/IR/Dialect.h, lib/Dialect/TritonGPU/IR/Dialect.cpp, lib/Dialect/TritonGPU/IR/Ops.cpp, lib/Dialect/TritonNvidiaGPU/IR/Dialect.cpp, lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp, python/test/gluon/test_frontend.py, test/Analysis/test-membar.mlir, test/TritonGPU/canonicalize.mlir, test/TritonGPU/inline.mlir, test/TritonGPU/invalid.mlir, test/TritonGPU/load-mma-specialization.mlir, test/TritonGPU/optimize-partition-warps.mlir, test/TritonGPU/pipeline-assign-latencies.mlir, test/TritonGPU/pipeline-schedule-loop.mlir, test/TritonNvidiaGPU/canonicalize.mlir, test/TritonNvidiaGPU/invalid.mlir, test/TritonNvidiaGPU/membar.mlir, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TensorMemoryToLLVM.cpp
This is a laundry list of cleanups that I finnally found time to power through. This makes the compiler crash less.
- Cleanup ttg attr interface methods
- Reorganize some code
- Verify SliceEncodingAttr dim and parent rank
- Verify local_store/load/alloc reg operand matches the rank of the shared layout
- Verify tmem_store/load/alloc reg operand is 2D
- Verify that the layout of TMEM reg operands are TMEM compatible
- A few other random things
=> [Dialect] Layout attr cleanup and tighten invariants

lib/Dialect/Gluon/Transforms/ResolveAutoEncodings.cpp, python/triton/language/__init__.py, test/Gluon/auto_encoding.mlir, test/Gluon/invalid_auto_encoding.mlir
In the failing example we have:
```mlir
%0 = tt.make_range {end = 8192 : i32, start = 0 : i32} : tensor<8192xi32, #gluon.auto_encoding>
%1 = tt.reshape %0 : tensor<8192xi32, #gluon.auto_encoding> -> tensor<64x128xi32, #gluon.auto_encoding>
%2 = gluon.set_auto_layout %1 : tensor<64x128xi32, #gluon.auto_encoding> -> tensor<64x128xi32, #blocked>
```
which currently fails with the error:
```python
/root/code/triton/test.py:43:52: error: 'tt.reshape' op Found conflicting encodings for value
gl.arange(0, BLOCK_M * BLOCK_N).reshape((BLOCK_M, BLOCK_N)),
```
The issue is that we propagate the blocked layout backwards to get a linear layout for the `make_range` result, then the algorithm propagates that layout forward to the `reshape` result. However, it infers a linear layout and errors because it …
=> [Gluon] Fix auto_encoding for ops which may infer multiple layouts

python/triton/runtime/interpreter.py
Apparently the documentation is just straight up wrong.
=> Revert: [TensorDesc] Add extra stride validation to interpreter (#7713)

python/test/gluon/test_frontend.py, python/triton/experimental/gluon/language/_core.py, python/triton/experimental/gluon/language/_standard.py
PR #7646 changed `gl.full` to default to auto layout but not `gl.zeros`.
PR #7589 changed `gl.convert_layout` to set the layout on auto layouts, which breaks code such as:
```python
a = ... # some auto layout
gl.set_auto_layout(a, compute_layout)
gl.store(..., gl.convert_layout(a, store_layout))
```
=> [Gluon] Fix auto layout inconsistencies

python/src/gluon_ir.cc, python/test/gluon/test_frontend.py, python/triton/experimental/gluon/language/amd/_layouts.py
Add more verification for AMDMFMALayout in Gluon so the verification rules are aligned with the verification rules in AMDMfmaEncodingAttr.  
With this change, if there are some invalid inputs in the gluon code, the error will be identified earlier.
=> [AMD][Gluon] Tighten up verification for AMDMFMALayout

third_party/nvidia/backend/driver.py
This PR is the third in a series of contributions aiming at reducing the launch overhead of Triton kernels ran without CUDA Graphs. A latency profiler script shared offline currently puts the main branch at a latency of around `27.16 us` (on a AMD EPYC 7413 24-C system) which can be reduced via several contributions in different places.
This PR comes with minor improvements in the NVIDIA driver backend (for `getPointer` in particular). By caching the string representations of `"data_ptr"` (and `"tma_desc_cpu_ptr"`) manually, one can switch from using `PyObject_GetAttrString` to `PyObject_GetAttr` which saves a bit of time and for several tensor inputs can accumulate up to `0.5 us` or more.
With the shared latency script in particular, the latency goes down to `26.80 us` (from `27.16 us`). …
=> [IMP][Launch Latency] slightly improved NVIDIA driver backend

include/triton/Dialect/TritonGPU/IR/Dialect.h, include/triton/Dialect/TritonGPU/IR/LinearLayoutConversions.h, include/triton/Dialect/TritonGPU/IR/TritonGPUDialect.td, lib/Conversion/TritonGPUToLLVM/Utility.cpp, lib/Dialect/TritonGPU/IR/Dialect.cpp, lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp, lib/Dialect/TritonGPU/IR/Ops.cpp, lib/Dialect/TritonGPU/IR/Types.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/PipeliningUtility.cpp, third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp, unittest/Dialect/TritonGPU/DialectTest.cpp, unittest/Dialect/TritonGPU/LinearLayoutConversionsTest.cpp
We don't need to pass both allocationShape and shape after
https://github.com/triton-lang/triton/pull/7515
=> [NFC] Just take one shape in `toLinearLayout`

third_party/amd/tools/hip/compile.cpp
=> [AMD] Add needed profile_scratch to AOT compile

python/test/unit/cuda/test_tma_descriptor.py, python/triton/tools/ragged_tma.py
This allows us to use higher-dimensional TMA descriptors to emulate ragged-batching support with automatic bounds checking.
=> [FRONTEND] Support for ragged TMAs

include/triton/Dialect/Triton/IR/Utility.h, lib/Analysis/AxisInfo.cpp, test/Analysis/test-alignment.mlir
And also simplifies gcd invocation and lifts `kMaxDivisor` into a constant expression
=> [ANALYSIS] Fix divisibility estimation for min/max/select ops

python/triton_kernels/tests/test_matmul.py, python/triton_kernels/triton_kernels/matmul_ogs.py
empty 2d tensors are viewed as 3D with a leading 1 dimension which leads to computed strides that are invalid with TMA
=> Disable TMA for empty tensors

include/triton/Dialect/TritonGPU/Transforms/Partition.h, include/triton/Dialect/TritonGPU/Transforms/PipeliningUtility.h, lib/Dialect/TritonGPU/Transforms/Pipeliner/PipeliningUtility.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/LoadMMASpecialization.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/Partition.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/PartitionLoops.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/PartitionScheduling.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/RewritePartitionDependencies.cpp, test/NVWS/insert_aref.mlir, test/NVWS/lower_aref.mlir, test/TritonGPU/load-mma-specialization.mlir, test/TritonGPU/partition-loops.mlir, test/TritonGPU/partition-scheduling.mlir, test/TritonGPU/rewrite-partition-dependencies.mlir, third_party/nvidia/include/Dialect/NVWS/IR/NVWSOps.td, third_party/nvidia/lib/Dialect/NVWS/Transforms/LowerAref.cpp
* Final `wait_barrier`s are now assigned to a partition it was used inside the loop, to move them inside the `ttng.warp_group`. If it was not used inside the loop, assign it to a partition with arrive (like in matmul case). This change is necessary to enable automatic phase computation in the `lower-aref` pass, when `aref`s will be used for TMEM ownership transfer in a subsequent PR.
* Add `ttg.warp_specialize.tag` attribute to a warp-specialized loop, and to ops with assigned partitions outside the loop, to see which partitioned ops outside the loop belong to which warp-specialization part of the code.
* Now that all `try_wait`s are inside partitions, we can remove the `aref.destroy` op and let the `lower-aref` pass insert the `inval_barrier` right after the `ttng.warp_group` op. Aref …
=> [NVWS] Assign final try_wait to a partition.

python/triton_kernels/triton_kernels/matmul_ogs_details/_finalize_matmul.py
The product of `row * outN` could overflow in int32. To avoid this, we perform the offset multiplication in int64 instead
=> Cast index to int64 in finalize_matmul

python/test/conftest.py, python/triton/_internal_testing.py, python/triton_kernels/tests/conftest.py
This is a quite interesting problem.
Long story short, without the PR we cannot clean up variables set in the tests.
And running `pytest test_knobs.py` after applying the following diff will fail
```
diff --git a/python/test/unit/test_knobs.py b/python/test/unit/test_knobs.py
index ba2c8517c..808198076 100644
--- a/python/test/unit/test_knobs.py
+++ b/python/test/unit/test_knobs.py
@@ -117,6 +117,10 @@ def test_env_updated(fresh_knobs, monkeypatch):
assert os.environ["TRITON_HOME"] == "/foo/bar"
+def test_none():
+    assert "TRITON_HIP_LOCAL_PREFETCH" not in os.environ
+
+
```
=> [TEST] Use two different monkey patch objects for environment variable restore

third_party/nvidia/hopper/lib/Transforms/WarpSpecialization/WSCodePartition.cpp
In ~50% of test runs I was getting failures in `test/Hopper/WarpSpecialization/ws_code_partition.mlir`'s `_matmul_layernorm_persistent_one_producer_one_consumer_one_epilog` test, with the following error:
> assertion failed at third_party/llvm/llvm-project/llvm/include/llvm/ADT/DenseMap.h:1290 in pointer llvm::DenseMapIterator<mlir::Channel *, llvm::SmallVector<mlir::Channel *>, llvm::DenseMapInfo<mlir::Channel *>, llvm::detail::DenseMapPair<mlir::Channel *, llvm::SmallVector<mlir::Channel *>>, true>::operator->() const [KeyT = mlir::Channel *, ValueT = llvm::SmallVector<mlir::Channel *>, KeyInfoT = llvm::DenseMapInfo<mlir::Channel *>, Bucket = llvm::detail::DenseMapPair<mlir::Channel *, llvm::SmallVector<mlir::Channel *>>, IsConst = true]: Ptr != End && "dereferencing end() iterator" …
=> [Hopper][WS] Fix UB in channel sorting

python/test/unit/runtime/test_launch.py, python/triton/compiler/compiler.py, python/triton/knobs.py, third_party/proton/proton/hooks/hook.py, third_party/proton/proton/hooks/instrumentation.py, third_party/proton/proton/hooks/launch.py
This allows tracking potential timeout in the driver when loading a kernel
Breaks backward compatibility as it changes the hook name and signature
=> [BC breaking][FRONTEND] Add hooks around kernel loads

test/TritonGPU/amd/optimize-lds-usage.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/OptimizeLDSUsage.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/OptimizeLDSUtility.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/OptimizeLDSUtility.h
This PR optimizes the `optimize-lds-usage` pass by improving layout selection strategy for convert-layout operations. The changes include:
- Removed hardcoded preference for padded layouts in the AMD-specific LDS optimization pass
- Enhanced `estimateResourcesForReplacement` method to calculate memory requirements for both padded and swizzled layouts
- Modified layout selection logic to prefer swizzled layouts when LDS limits allow, falling back to padded layouts only when necessary
The `optimize-lds-usage` pass previously enforced padded layouts based on the assumption that "padded conversion seems more friendly with this optimization." While this approach reduced LDS consumption, it came with significant performance penalties:
- Hundreds of additional LLVM IR lines generated for padded …
=> [AMD] Improve layout selection in optimize-lds-usage pass to prefer swizzled layouts

python/triton/language/target_info.py, python/triton_kernels/triton_kernels/target_info.py
This moves some target_info functions from kernels into the language. I also update `current_target()` to return `None` when there is no supported device found, which allows the target function to be called e.g. at import time.
=> [LANG] Expand tl.target_info and fail gracefully on CPU

python/test/unit/language/test_core.py, python/triton/compiler/compiler.py, python/triton/language/core.py
Also removed `other`'s annotation because it violates [Liskov substitution principle](https://stackoverflow.com/questions/56860/what-is-an-example-of-the-liskov-substitution-principle): `It’s unsafe to override a method with a more specific argument type`
=> [INTERPRETER] Support dtype and constexpr comparison

lib/Dialect/TritonGPU/IR/LinearLayoutConversions.cpp, lib/Dialect/TritonGPU/IR/Types.cpp, lib/Tools/LayoutUtils.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TensorMemoryToLLVM.cpp
We now add support for `TensorMemoryScalesEncoding` in `toLinearLayout`
and we reuse the generic lowering to lower it.
=> [BACKEND] Always lower tcgen05.ld/st via generic LinearLayout code

include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td, python/test/gluon/test_frontend.py, python/test/unit/language/test_core.py, test/Analysis/test-alias.mlir, test/Analysis/test-allocation.mlir, test/Analysis/test-membar.mlir, test/Conversion/amd/amdgpu_membar.mlir, test/Conversion/amd/tritongpu_to_llvm.mlir, test/Conversion/tritongpu_to_llvm.mlir, test/NVWS/lower_aref.mlir, test/TritonGPU/amd/amd-block-pingpong-chained-dots.mlir, test/TritonGPU/amd/amd-block-pingpong.mlir, test/TritonGPU/amd/amd-fold-true-cmpi.mlir, test/TritonGPU/amd/amd-range-analysis.mlir, test/TritonGPU/amd/amd-reorder-instructions.mlir, test/TritonGPU/amd/in-thread-transpose.mlir, test/TritonGPU/consan-negative.mlir, test/TritonGPU/consan.mlir, test/TritonGPU/invalid.mlir, test/TritonGPU/load-mma-specialization.mlir, test/TritonGPU/loop-pipeline-async-latencies.mlir, test/TritonGPU/loop-pipeline-blackwell.mlir, test/TritonGPU/loop-pipeline-hopper.mlir, test/TritonGPU/loop-pipeline.mlir, test/TritonGPU/memdesc-subview-split.mlir, test/TritonGPU/pipeline-lower-loop.mlir, test/TritonGPU/promote-lhs-to-tmem.mlir, test/TritonGPU/samples/descriptor-matmul-pipeline.mlir, test/TritonNvidiaGPU/interleave_tmem.mlir, test/TritonNvidiaGPU/test_tensor_memory_allocation.mlir
=> [IR] Improve memdesc_index printing to make it obvious what operand is the index

python/build_helpers.py, setup.py
This is a following up PR of #7347, which the new env var `TRITON_BUILD_DIR` was added to allow moving `f"cmake.{plat_name}-{sys.implementation.name}-{python_version}"` to an alternative location. However, a few directories are still using the in-source location `build/`.
This PR completes the relocation of these remaining directories.
=> Complete out-of-tree build with environment variable TRITON_BUILD_DIR

python/test/conftest.py, python/test/unit/runtime/test_cache.py, python/test/unit/test_knobs.py, python/triton_kernels/tests/conftest.py, python/triton_kernels/tests/test_specialize.py
These are not environment variables and thereby cannot be automatically reset by `knobs.reset`
=> [TEST] Reset `jit_cache_hook` and `jit_cache_hook` in the `fresh_triton_cache` fixture

test/CMakeLists.txt
Fix a typo in CMAKE_CURRENT_SOURCE_DIR.
=> Fix a typo in CMAKE_CURRENT_SOURCE_DIR variable.

include/triton/Dialect/TritonInstrument/IR/TritonInstrumentOps.td
Add the description of auxiliary tensors and improve description of ops to tell how the checks are actually performed.
=> [ConSan] Improve comments in TritonInstrumentOps.td

python/test/unit/test_debug.py, python/triton/language/core.py, python/triton/language/semantic.py
Add `mask=mask` to `tl.device_assert`
Frequently in Triton kernels, data is loaded with a mask. The data outside the mask has unknown value. This makes it frustrating to write `tl.device_assert`s. In particular, I have to use this pattern: `tl.device_assert((data == 1337) | ~mask)`. This works fine; it's just a little unpleasant, and you have to remember that `==` has lower precedence than `|`. With this PR, you can instead write `tl.device_assert(data == 1337, mask=mask)`.
Representative example:
```py
import torch
import triton
torch.set_default_device("cuda")
@triton.jit
def kernel(data_ptr, len):
BLOCK_SZ: tl.constexpr = 32
mask = tl.arange(0, BLOCK_SZ) < len
data = …
```
=> Add mask to tl.device_assert

lib/Dialect/TritonGPU/Transforms/WarpSpecialization/AutomaticWarpSpecialization.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/LoadMMASpecialization.cpp, test/NVWS/assign_stage_phase.mlir, test/NVWS/lower_aref.mlir, test/TritonGPU/load-mma-specialization.mlir, third_party/nvidia/include/Dialect/NVWS/Transforms/Passes.td, third_party/nvidia/lib/Dialect/NVWS/Transforms/AssignStagePhase.cpp, third_party/nvidia/lib/Dialect/NVWS/Transforms/CMakeLists.txt, third_party/nvidia/lib/Dialect/NVWS/Transforms/LowerAref.cpp, third_party/nvidia/lib/Dialect/NVWS/Transforms/Utilities.cpp, third_party/nvidia/lib/Dialect/NVWS/Transforms/Utilities.h, third_party/nvidia/triton_nvidia.cc
* Reorder `partition-loops` and `lower-aref` passes
* Split `lower-aref` to `lower-aref` and `assign-stage-phase` passes
* the split separates concerns, as `assign-stage-phase` is more complex pass and testing/debugging can be focused on correctness stage/phase assignment w/o added complexity of `aref->mbarrier` lowering. 
* `assign-stage-phase` uses enterOp token to assign same stage variable that enterOp uses to exitOp, instead of previously having separate stage for enterOps/exitOps.
*  `lower-aref` testing verifies correctness of `aref->mbarrier` lowerings
* in `load-mma-specialization` don't place final `waitOp` inside ws-region, revert to original behavior before https://github.com/triton-lang/triton/pull/7757, as that change causes perf regression with this pR.  Keeping ws.tag to …
=> [WS] reorder partition-loops and lower-aref

include/triton/Conversion/TritonGPUToLLVM/Utility.h, include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td, lib/Conversion/TritonGPUToLLVM/Utility.cpp, lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp, python/test/gluon/test_core.py, test/Analysis/test-membar-ttng.mlir, test/Conversion/tritongpu_to_llvm.mlir, test/Conversion/tritongpu_to_llvm_blackwell.mlir, test/TritonNvidiaGPU/invalid.mlir, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/LoadStoreOpToLLVM.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TensorMemoryToLLVM.cpp
Stacked PRs:
* __->__#7937
* #7936
--- --- ---
Many ops were using `smemObj.getBase()` without applying the offsets to
get the part of smem to read to write. This is incorrect since the
offsets may be nonzero. This PR fixes as many of these issues I could
identify and adds tests for this.
=> [Backend] Fix various issues with smem base offsets

third_party/amd/backend/compiler.py
True16 is a new LLVM feature that causes numerous deterministic and non-deterministic test failures. Disabling for now so that we have a known good state on main.
=> [AMD] Disable True16 on gfx11

python/triton_kernels/tests/test_matmul.py, python/triton_kernels/triton_kernels/matmul_ogs.py, python/triton_kernels/triton_kernels/matmul_ogs_details/opt_flags.py, python/triton_kernels/triton_kernels/matmul_ogs_details/opt_flags_details/opt_flags_nvidia.py
This reverts commit f1872edd63272725db847c20308ca6859fe5c08c.
PR #7897 was triggering fp8 matmul issues which might be due to something else, but we decided to revert it while we investigate.
* Only reverted the part that changed block size logic (kept other small bug fixes).
=> Revert "[KERNELS] Improve block sizes for batched matmul_ogs with small m/n/k. (#7897)"

python/triton/runtime/jit.py
To handle recursion we need to set a placeholder cache_key, this can cause problems when this function is called from multiple threads.
=> Make cache_key computation thread safe

lib/Analysis/Utility.cpp, python/test/unit/language/test_matmul.py, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/WGMMA.cpp
This prevent generating miscompiles for cases where the N dimension is too small. Technically we could support N=8 but it would require padding the shared memory.
=> [BACKEND] Restrict MMAV5/MMV3 usage for N < 16 and fix no-swizzle case

lib/Dialect/TritonGPU/IR/Dialect.cpp, python/test/unit/language/test_core.py, python/triton/_internal_testing.py, test/TritonGPU/invalid-attributes.mlir, third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp
I saw some occasional test failures, but after disabling True16, tests seem to pass fine.
=> [AMD] Enable dot_scaled on gfx11

lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp
This PR tries to fix this Triton build error when running `pip install .`:
```
2025-08-30T17:46:31.6279959Z       FAILED: [code=1]
2025-08-30T17:46:31.6280341Z       lib/Dialect/TritonNvidiaGPU/IR/CMakeFiles/TritonNvidiaGPUIR.dir/Ops.cpp.o
2025-08-30T17:46:31.6280801Z       /usr/bin/g++-13 -DGTEST_HAS_RTTI=0
2025-08-30T17:46:31.6281256Z       -I/tmp/triton/build/cmake.linux-x86_64-cpython-3.10/lib/Dialect/TritonNvidiaGPU/IR
2025-08-30T17:46:31.6281755Z       -I/tmp/triton/lib/Dialect/TritonNvidiaGPU/IR
2025-08-30T17:46:31.6282097Z       -I/tmp/triton/include -I/tmp/triton/.
2025-08-30T17:46:31.6282472Z       -I/github/home/.triton/llvm/llvm-064f02da-ubuntu-x64/include
2025-08-30T17:46:31.6282926Z       -I/tmp/triton/build/cmake.linux-x86_64-cpython-3.10/include …
```
=> Fix missing return at end of strMMADTypeKind function

python/tutorials/gluon/02-layouts.py
- Previously, orders were incorrectly described.
- This makes the layout visualization and explanation consistent with the actual implementation.
=> [Gluon] Fix description in layout explanation in gluon tutorial

python/test/unit/language/test_matmul.py, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/WGMMA.cpp
Also tighten the precision check to catch subtle fp8 precision diff
=> [BACKEND] Fix matrix descriptor for no-swizzle case

python/test/gluon/test_frontend.py, python/triton/experimental/gluon/language/amd/cdna3/__init__.py, python/triton/experimental/gluon/language/amd/cdna4/async_copy.py
Support scalar other value for following ops:
- `amd.cdna3.buffer_load`
- `amd.cdna4.async_copy.buffer_load_to_shared` 
- `amd.cdna4.async_copy.global_load_to_shared`
We will explicitly convert scalar other to a tensor and cast to match the pointer type.
=> [AMD][GLUON] Support scalar other value for loads

include/triton/Dialect/TritonGPU/Transforms/Utility.h, lib/Dialect/TritonGPU/Transforms/Coalesce.cpp, lib/Dialect/TritonGPU/Transforms/Utility.cpp, test/TritonGPU/loop-pipeline-hip.mlir, third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp
Determine if it is safe to bypass LDS for dot operands.
Normally, dot operation operands are consumed in the dot MFMA layout,
which is not coalesced. To better utilize global memory bandwidth,
operands are usually loaded in a coalesced "blocked" layout and then
rearranged through LDS.
However, certain optimizations allow dot operands to be preshuffled in
global memory. In that case, the operands can be loaded efficiently
(in a coalesced way) and consumed directly by the dot operation.
When preshuffling is used, a sequence of transpose and reshape ops
must be applied to the operand.
To verify that preshuffling was done correctly and the final layout
remains coalesced, we start from the dot MFMA layout and apply the
inverse of each transpose/reshape op (while ignoring convert_layout
ops) …
=> [AMD] Add bypassLDS feature to StreamPipeline

python/test/unit/language/test_core.py, third_party/amd/include/TritonAMDGPUToLLVM/TargetUtils.h, third_party/amd/lib/TritonAMDGPUToLLVM/BufferOpsEmitter.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/TargetUtils.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/Utility.cpp, third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp
RDNA4 is currently treated as RDNA3. This patch splits the current family into an RDNA3 and an RDNA4 family. Behavior should be unchanged.
=> [AMD] Add ISAFamily for RDNA4

lib/Dialect/Triton/Transforms/Combine.cpp, test/Triton/combine.mlir
This restores the legacy guard from Combine.td: we only fold `addf(dot, bias)` 
into `dot(..., C=bias)` when `maxNumImpreciseAcc == 0`. Without this, 
`use_fast_accum=False` kernels were silently rewritten into the fast-accum 
form, causing accuracy drift in FP8 tests. This change ensures precise 
accumulation semantics are preserved while keeping the optimization enabled 
when imprecise accumulation is allowed.
=> Restore maxNumImpreciseAcc guard for AddFOp

lib/Dialect/TritonGPU/Transforms/FuseNestedLoops.cpp, test/TritonGPU/fuse-nested-loops.mlir
When we are peeling out the outer loop remove the warp specialization flag so that the specialized loop doesn't get warp specialized
=> [BACKEND] Clear out warp_specialize attr when peeling out outer loop

lib/Dialect/Triton/Transforms/Combine.cpp, test/Triton/combine.mlir
This restores the legacy guard from Combine.td: we only fold `addf(dot, bias)`
into `dot(..., C=bias)` when `maxNumImpreciseAcc == 0`. Without this, `use_fast_accum=False` kernels were silently rewritten into the fast-accum
form, causing accuracy drift in FP8 tests. This change ensures precise accumulation semantics are preserved while keeping the optimization enabled
when imprecise accumulation is allowed.
(cherry picked from commit 0ce5d77990ed4daef13665a568c7ea108de4e4e1)
- …
=> [release/3.5] Restore maxNumImpreciseAcc guard for AddFOp (#8056)

include/triton/Dialect/TritonGPU/Transforms/DecomposeScaledBlocked.h, lib/Dialect/TritonGPU/Transforms/DecomposeScaledBlocked.cpp
Exposed and Refactored DecomposeScaledBlocked pass so that it can be used by other backends.
Modifications include:
- Moved the pass definition to a header file.
- Made `cvtDotOperand` a member method to be reused later.
- Made `getTransposeOrder` a static method.
This is one of a series of PRs to decompose scaled dot on AMD backend.
=> [NFC]Expose DecomposeScaledBlocked Pass

test/Conversion/amd/async_ops_to_llvm.mlir, test/Conversion/amd/async_ops_to_llvm_invalid.mlir, test/TritonGPU/amd/amd-coalesce-async-copy.mlir, test/TritonGPU/amd/amd-update-async-wait-count.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp, third_party/amd/lib/TritonAMDGPUTransforms/CoalesceAsyncCopy.cpp, third_party/amd/lib/TritonAMDGPUTransforms/UpdateAsyncWaitCount.cpp
Adds support for padded shared layouts to `AMDCoalesceAsyncCopy`, `UpdateAsyncWaitCount` and the lowering of `ttg.async_copy_global_to_local`/`amdgpu.buffer_load_to_local`.
=> [AMD][BACKEND] Support padded shared layouts with direct-to-lds loads

python/triton_kernels/tests/test_matmul.py, python/triton_kernels/triton_kernels/matmul_ogs.py, python/triton_kernels/triton_kernels/matmul_ogs_details/opt_flags.py, python/triton_kernels/triton_kernels/matmul_ogs_details/opt_flags_details/opt_flags_nvidia.py
This reverts commit 0a2e3a391cbb9e13d29bf12a2a0005e358102d74.
(Verified that this is still faster on GB200 on top of recent fixes.)
=> Reapply "[KERNELS] Improve block sizes for batched matmul_ogs with small m/n/k (#7897)"

third_party/proton/common/lib/TraceDataIO/CircularLayoutParser.cpp
Fixed the miscalculated event size that each warp captured for reporting the overflow warning.
=> [Proton] Fix proton intra kernel profiling buffer overflow warning

python/src/specialize.cc, python/test/unit/runtime/test_specialize.py
- should address regression discovered introduced in #7771 
- adds unit-test which ideally covers all supported specializations to spot other edge cases sooner (currently not exhaustive for dtypes and descriptor layouts)
=> [Fix] fallback in specialize even for native types

README.md, python/test/unit/test_knobs.py, python/triton/knobs.py, third_party/nvidia/backend/compiler.py
This PR sets the default value of the ptxas_options knob to be the value of the `PTXAS_OPTIONS` environment variable.
We need this option when we want to apply extra ptxas options across a range of Triton kernels, without changing their call sites.
=> [BACKEND][NVIDIA] Update ptxas_options knobs default value

python/src/ir.cc, python/test/unit/language/test_reproducer.py, third_party/amd/backend/compiler.py, third_party/nvidia/backend/compiler.py
Currently MLIR reproducers for each pass pipeline run overrides the previous `TRITON_REPRODUCER_PATH` path. This change allows for including a reproducer suffix when calling pm.run() to allow for retaining all previously run pipeline reproducers prior to the most recently run pass pipeline.
This is important to add because with multiple pipelines, it is necessary to retain all previous pipelines reproducers to reproduce the full compilation sequence. 
=> [BACKEND] Retain mlir reproducer temporaries from prior run pass pipelines

python/test/gluon/test_frontend.py, python/triton/experimental/gluon/language/__init__.py, python/triton/experimental/gluon/language/_core.py, python/triton/experimental/gluon/language/_semantic.py
This is a function which returns a constexpr of the current contextual number of warps. This returns the value passed as `num_warps=` when called from a regular function, but this also works inside warp specialized regions and returns the number of warps in the current partition.
cc @aeng-openai
=> [Gluon] Add `ttgl.get_num_warps` metafunction

lib/Conversion/TritonGPUToLLVM/Utility.cpp, lib/Dialect/TritonGPU/IR/Dialect.cpp, lib/Dialect/TritonGPU/IR/LayoutUtility.cpp, lib/Dialect/TritonGPU/IR/Ops.cpp, lib/Dialect/TritonGPU/IR/Types.cpp, python/test/gluon/test_core.py, test/Conversion/amd/tritongpu_to_llvm.mlir, test/TritonGPU/invalid.mlir, test/TritonGPU/memdesc-subview-split.mlir, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/MemoryOpToLLVM.cpp
This PR supports padded layout in MemDescSubsliceOp and adds few related tests.
=> [Backend] Fix MemDescSubsliceOp verifier and LLVM conversion for padded layout

python/src/specialize.cc
In our case, it also breaks Windows build.
=> Remove `#include <unistd.h>` from `specialize.cc` as unused

include/triton/Dialect/TritonGPU/Transforms/Partition.h, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/LoadMMASpecialization.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/Partition.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/PartitionBuilder.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/PartitionLoops.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/PartitionScheduling.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/RewritePartitionDependencies.cpp, test/NVWS/assign_stage_phase.mlir, test/NVWS/insert_aref.mlir, test/NVWS/lower_aref.mlir, test/TritonGPU/load-mma-specialization.mlir, test/TritonGPU/partition-loops.mlir, test/TritonGPU/partition-scheduling.mlir, test/TritonGPU/rewrite-partition-dependencies.mlir, third_party/nvidia/lib/Dialect/NVWS/Transforms/AssignStagePhase.cpp, third_party/nvidia/lib/Dialect/NVWS/Transforms/InsertAref.cpp, third_party/nvidia/lib/Dialect/NVWS/Transforms/LowerAref.cpp, third_party/nvidia/lib/Dialect/NVWS/Transforms/Utilities.cpp, third_party/nvidia/lib/Dialect/NVWS/Transforms/Utilities.h
`WarpSchedule` is renamed to `PartitionSet`, since it is now just a container of created partitions. It no longer owns a mapping between ops and partitions, which are now done exclusively by free functions like `setPartition`, `getPartitionIds` etc which only looks at the op
Other notable changes
* Partition attributes are now a set (represented as `array<i32>`).
* The concrete instance of "root partition" is gone but the code still uses the term to refer to ops belonging to all partitions. 
* At the beginning of `PartitionLoops`, unannotated ops, including those within if or reduce ops, are annotated with their parent partitions.
=> [WS] Rework partition representation

lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp, lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp, test/TritonGPU/dot-operands.mlir
Simplify the code that re-order trans and alloc operation and make sure it keeps the layout decided by accelerate matmul
=> [BACKEND] Simplify and fix trans(alloc) optimization

setup.py
Triton version information can only contain one plus-character. The plus-character is used for distinguishing additional version suffix information from the base major.minor.patch version scheme.
Version information is constructed in the setup.py in a following way:
version = 3.5.0 + get_git_version_suffix() + os.environ.get("TRITON_WHEEL_VERSION_SUFFIX", "")
Here the get_git_version_suffix() will return "" for release builds and "+" for other builds. Version can also contain only a one plus-character, otherwise error is thrown.
If we set
os.environ["TRITON_WHEEL_VERSION_SUFFIX"] = "+rocmsdk20250806"
1) For release builds the version would be: "3.5.0+rocmsdk20250806" that is OK.
2) For development builds the version would be: "3.5.0+githash+rocmsdk20250806" which is not OK
because the …
=> Version suffix should contains only one plus-character even when TRITON_WHEEL_VERSION_SUFFIX is used

third_party/proton/csrc/include/Profiler/Cupti/CuptiProfiler.h, third_party/proton/csrc/include/Profiler/GPUProfiler.h, third_party/proton/csrc/include/Profiler/Instrumentation/InstrumentationProfiler.h, third_party/proton/csrc/include/Profiler/Profiler.h, third_party/proton/csrc/include/Profiler/Roctracer/RoctracerProfiler.h, third_party/proton/csrc/include/Session/Session.h, third_party/proton/csrc/lib/Profiler/Cupti/CuptiProfiler.cpp, third_party/proton/csrc/lib/Profiler/Instrumentation/InstrumentationProfiler.cpp, third_party/proton/csrc/lib/Profiler/RocTracer/RoctracerProfiler.cpp, third_party/proton/csrc/lib/Session/Session.cpp, third_party/proton/test/test_api.py
Different modes usually require different metrics to be collected. For instance, one mode may use PC sampling while another uses timing.
If two concurrent sessions share the same profiler instance, it becomes difficult to attribute different metrics to each session. Therefore, it is better to disable it.
=> [PROTON] Do not allow concurrent profiling with different modes

include/triton/Dialect/TritonGPU/Transforms/Partition.h, include/triton/Dialect/TritonGPU/Transforms/PartitionBuilder.h, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/AutomaticWarpSpecialization.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/LoadMMASpecialization.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/Partition.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/PartitionBuilder.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/PartitionLoops.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/PartitionScheduling.cpp, lib/Dialect/TritonGPU/Transforms/WarpSpecialization/RewritePartitionDependencies.cpp, test/NVWS/assign_stage_phase.mlir, test/NVWS/lower_aref.mlir, test/TritonGPU/load-mma-specialization.mlir, test/TritonGPU/partition-loops.mlir, third_party/nvidia/lib/Dialect/NVWS/Transforms/AssignStagePhase.cpp, third_party/nvidia/lib/Dialect/NVWS/Transforms/InsertAref.cpp, third_party/nvidia/lib/Dialect/NVWS/Transforms/InsertTmemAref.cpp, third_party/nvidia/lib/Dialect/NVWS/Transforms/LowerAref.cpp
* all ops, except parent ops (if/reduce), are annotated with partition sets after `partition-scheduler`
* patch up downstream passes to handle this properly
* partition set of a parent op is inferred in `partition-loop` pass; also infers partitions set for each result
* extend `partition-loop` to partition if-stmt across different partition when loops are split
* patch `lower-mma-specialization` to annotate all ops, and patch unit test
* patch up remainig passes to play well with requirement that all ops must be annotated in ws-loops
* there are few remaining issues before `aref-tmem-insertion` can be enabled and `load-mma-specialzation` disabled, which is subject of subsequent PR
=> [WS]: partition-scheduler annotates all ops + fixes

python/triton/experimental/gluon/language/_core.py
This avoids potentially confusing error messages when there is just one argument and it isn't passed as `(arg,)`
=> [Gluon] Wrap `warp_specialize` arguments in tuple if necessary

lib/Dialect/TritonInstrument/IR/Utility.cpp, lib/Dialect/TritonInstrument/Transforms/ConcurrencySanitizer.cpp, test/TritonGPU/consan.mlir, third_party/nvidia/backend/compiler.py
This PR introduces two functional and one performance improvement.
1) Identifying if an allocation is used as a multibuffer is currently done with IR tracking in ConSan - we check if the allocation is being used by `subview_index`. There was a missing case, as we were not tracking values into the WarpSpecializeOp, interpreting multibuferred allocations as regular ones. This PR fixes this issue.
2) For tcgen5 mma with barrier (so doing commit implicitly) we were emitting `track_visible_reads/writes` only for tensor core buffers, so consan was only tracking status of TC buffers accessed by mma op. This meant for example that if partition A waited for mma issued by partition B, A still couldn't legally write to mma's operands, even though waiting for mma to finish should be enough for it to …
=> [ConSan] Fixes for Warp Specialization support

third_party/amd/lib/TritonAMDGPUTransforms/CanonicalizePointers.cpp
Fix https://github.com/ROCm/triton-internal/issues/1224
The problem is an asserion arising from python/triton_kernels/bench/bench_mlp.py.
The root cause in short is that, the patten-matching code tres to use a value, say x, which is already mapped to y (by patten-matching framework), as a key to populate map (not maintained by rewrite framework). It should have used y for map index.
The problem can be depicted as following, consider two ops
1: r = op1 ...
2: ... op2 r, ...
The patten-matching rule tries to replace op1's result r with {a,b}
s1: rewriter.replaceOpWithMultiple(op1, {a, b})
s2: key = {a, b}
s3: local-map[key] = something_awesome.
However, at this moment, b is already mapped to c. when op2 is visited. The information associated with op2.operand0 is {a, c} instead of {a, b}. If …
=> [AMD] Fix assertion in CanonicalizePointers

third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp, third_party/amd/lib/TritonAMDGPUTransforms/CoalesceAsyncCopy.cpp
`CDNA1` and `CDNA2` do not have support to load from HBM to shared memory.
=> [AMD][BACKEND] Disable direct-to-lds loads on CDNA1 and CDNA2

third_party/amd/lib/TritonAMDGPUTransforms/CanonicalizePointers.cpp
Follow the previous PR https://github.com/triton-lang/triton/pull/8276.
Sorry for being sloppy, before I made the previous PR. I was wondering if condition "remapped != nullptr" is really necessary. I remove it and run the test, everything is fine; however, I forget to add it back. Before I go to sleep, I check today's PR and find this issue.
I think it might still need this condition to be safe. Sorry about that.
=> [AMD] Fix assertion in CanonicalizePointers 2

include/triton/Analysis/AxisInfo.h, lib/Analysis/AxisInfo.cpp, test/Analysis/test-alignment.mlir, test/TritonGPU/automatic-warp-specialization.mlir, test/TritonGPU/loop-pipeline-blackwell.mlir, test/TritonGPU/loop-pipeline-hip.mlir, test/TritonGPU/loop-pipeline-hopper.mlir, test/TritonGPU/loop-pipeline.mlir, test/TritonGPU/pipeline-assign-latencies.mlir, test/TritonGPU/pipeline-lower-loop.mlir
Two previous have been fixed.
1. Hints annotated on scalar operations were not taken effective previously.
2. In mlir, there were a lot of mismatch between tensor ranks and hint ranks.
=> [ANALYSIS] Fix hint analysis in axis info

test/TritonGPU/amd/amd-optimize-dot-operands.mlir, third_party/amd/lib/TritonAMDGPUTransforms/OptimizeDotOperands.cpp, third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp
This PR fixed the pattern match in shared layout deduction for scale in a decomposed scaled dot, to unlock pipelining via lds.
Resoved https://github.com/ROCm/triton-internal/issues/1204
=> [AMD]Pipeline Scale in Decomposed Scaled Dot via LDS

include/triton/Dialect/TritonInstrument/IR/TritonInstrument.md, include/triton/Dialect/TritonInstrument/IR/TritonInstrumentOps.td, include/triton/Dialect/TritonInstrument/IR/Utility.h, lib/Conversion/TritonInstrumentToLLVM/InstrumentationToLLVM.cpp, lib/Dialect/TritonInstrument/IR/Utility.cpp, lib/Dialect/TritonInstrument/Transforms/ConcurrencySanitizer.cpp, python/test/gluon/test_consan.py, test/Conversion/tritoninstrument_to_llvm.mlir, test/TritonGPU/consan.mlir
Adding deadlock detection to ConSan.
To detect deadlocks we first need to keep track of the barrier state - we introduce `barrierState` count and phase aux structure that encodes information about phase, init_count and current_count. We then instrument barrier inits and arrivals - init set up init_count = current_count = cout; phase = 0. Arrival decrements current_count and if it hits 0, flips the phase and re-sets current_count. We treat TMA and TC commits as barrier arrivals with count=1.
With that information we can then check if all the threads are waiting (which constitutes a deadlock). To do that we instrument entries and exits from barrier_wait. We introduce `waiting` aux structure, that keeps track of waiting threads, and mapping to which barrier they are waiting on. When issuing …
=> [ConSan] Deadlock Detection

lib/Dialect/TritonGPU/IR/Dialect.cpp, third_party/amd/include/TritonAMDGPUTransforms/WmmaGroup.h, third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/WMMA.cpp, third_party/amd/lib/TritonAMDGPUTransforms/WmmaGroup.cpp, third_party/amd/python/test/test_gluon_gfx1250.py
Previously we only have 2 wmma v3 instructions:
- bf16 * bf16 -> fp32
- bf8 * bf8 -> fp32 k=64
This PR extends to cover the following wmma v3 instructions:
- fp32 * fp32 -> fp32
- fp16 * fp16 -> fp32
- fp8 * fp8 -> fp32 k=64/128
- fp8 * bf8 -> fp32 k=64/128
- bf8 * fp8 -> fp32 k=64/128
- bf8 * bf8 -> fp32 k=128
=> [AMD] Add more wmma data types

bin/RegisterTritonDialects.h, include/triton/Dialect/TritonGPU/Transforms/PipeliningUtility.h, lib/Dialect/TritonGPU/Transforms/Pipeliner/PipeliningUtility.cpp, lib/Dialect/TritonGPU/Transforms/Pipeliner/SoftwarePipeliner.cpp, test/TritonGPU/amd/amd-pipeline-chained-dots.mlir, test/TritonGPU/amd/amd-stream-lds-layout-selection.mlir, test/TritonGPU/amd/amd-stream-loop-assume.mlir, test/TritonGPU/loop-pipeline-combine-waits.mlir, test/TritonGPU/loop-pipeline-hip.mlir, test/TritonGPU/loop-pipeline.mlir, third_party/amd/backend/compiler.py, third_party/amd/include/TritonAMDGPUTransforms/Passes.td, third_party/amd/lib/TritonAMDGPUTransforms/BlockPingpong.cpp, third_party/amd/lib/TritonAMDGPUTransforms/CMakeLists.txt, third_party/amd/lib/TritonAMDGPUTransforms/Pipeline.cpp, third_party/amd/lib/TritonAMDGPUTransforms/PipelineUtility.h, third_party/amd/lib/TritonAMDGPUTransforms/ScheduleLoops.cpp, third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp, third_party/amd/python/triton_amd.cc
This PR refactored StreamPipeliner, with following modifications:
- exposed some structures in header
- splitted StreamPipeliner into 2 passes
- `TritonAMDGPUScheduleLoops`: to generate schedule. It keeps most of the functionality of StreamPipeliner. In the following PR it will be further trimmed to only schedule global load and compute.
- `TritonAMDGPUPipeline`: eventually it contains: `lowerLoops` to allocate lds and schedule async loads, and `expandLoops` to mechanically expand loops according to schedule. At the point of this PR, it will only contain `expandLoops`.
- splitted `expandLoops` out of `StreamPipeliner`, into a separate Pipeline pass
- renamed StreamPipeline.cpp to ScheduleLoops.cpp to better reflect its purpose
- changed name of passes in lit tests accordingly
It's part of …
=> [AMD]Split Loop Expansion from StreamPipeliner

third_party/amd/backend/compiler.py
`wave_per_eu` indicates how many waves are supposed to execute per eu (SIMD) simulteneously. Value 0 means compiler decides how many waves are assigned to each SIMD; Value 1 indicates only 1 wave per SIMD. Value 1 will impact small kernels like the `vector_add` since there can be far more than 1 wave executing simultaneously per SIMD. So, by default, it makes more sense for the compiler to decide the numbers of wave per eu unless user specifies that.  
The default value 1 actually affects the perf numbers of the tutorial example `01-vector-add.py`. Memory bandwidth regressed to 3.3TB/s with `wave_per_eu=1`, and it increases to 5.3TB/s with `wave_per_eu=0`. This PR changes the default value from 1 to 0.
- …
=> [HIP] change default value of `waves_per_eu` to 0

setup.py
Currently we're getting a deprecation warning when building triton:
> Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
The fix is to pass an explicit filter mode to `extractall`.
=> [Build] Fix deprecation warning from TarFile.extractall

include/triton/Tools/Sys/GetEnv.hpp, python/test/gluon/test_consan.py
Make the TRITON_ENABLE_EXPERIMENTAL_CONSAN cache invalidating and add tests verifying that there is no collision between consan enabled and disabled.
=> [ConSan] ConSan env var should be cache invalidating

.github/workflows/build-macos.yml, .github/workflows/create_release.yml, .github/workflows/documentation.yml, .github/workflows/integration-tests-amd.yml, .github/workflows/integration-tests-nvidia.yml, .github/workflows/llvm-build.yml, .github/workflows/pre-commit.yml, .github/workflows/runner-preparation.yml, .github/workflows/wheels.yml
Updating Actions should be safe as all runners you use are at least version 2.328.0.
=> Bump actions/setup-python from 5 to 6

test/lib/Proton/CMakeLists.txt
- [ x] I have run `pre-commit run --from-ref origin/main --to-ref HEAD`.
- [x ] This PR does not need a test because `It fix random build failure`.
=> [PROTON] Fix TestScopeIdAllocation.cpp random build failure

python/triton_kernels/triton_kernels/routing.py
(Calls to storage() caused issues when using FakeTensor.)
=> [KERNELS] Change routing code to avoid storage().

python/triton/experimental/gluon/language/_core.py, python/triton/experimental/gluon/language/_semantic.py
I'm not a fan of using `isinstance` here as it leads to an inconsistency. Say we want to pass a single argument `x` that happens to be a tuple of tensors, then that has to be passed as `(x,)` or otherwise the tuple will be interpreted as a list of arguments to pass to the worker function. 
The original PR (#8269) justified this as improving the error message, so I also add a validation check with a better error message if you forget to pass a tuple.
=> [Gluon] Require warp_specialize default_args and worker_args be tuples

python/triton_kernels/tests/test_mxfp.py, python/triton_kernels/triton_kernels/numerics_details/mxfp.py, python/triton_kernels/triton_kernels/numerics_details/mxfp_details/_upcast_from_mxfp.py
Need to clamp since due to rounding, we can have overflow that was within
the range before quantization.
e.g., 3.3895e+38 -> log2(3.3895e+38 / max_fp8e4m3=448) ~= 119.17 -> round
up to 120 + exp_bias=127 -> scale=247
3.3895e+38 / 2**120 ~= 254.9976 -> round to 256 in fp8e4m3fn
Dequantization: 256 * 2**120 > 3.4e38 overflowing 3.38953139e38
=> [mxfp] handle values close to max correctly w/o overflow

third_party/amd/lib/TritonAMDGPUTransforms/ScheduleLoops.cpp
The `load` op is erased in `convertDistributedOpEncoding` so we should get the MLIR context from the `newOp` when setting op attributes. Interestingly, I found this issue only because the `loop-pipeline-hip.mlir` lit test crashed with bad access on my Mac laptop (ARM). On Linux/x86 the test runs fine w/ and w/out this fix.
=> Get MLIRContext from `newOp`, not the deleted `load`

test/Conversion/amd/ds_transpose.mlir, third_party/amd/lib/TritonAMDGPUToLLVM/MemoryOpToLLVM.cpp
The minimal interval restricts the number of contiguous elements in shared memory for padded layouts.
=> [AMD][BACKEND] Limit vec size for ds_read_tr + padded layouts by min interval

test/Conversion/amd/async_ops_to_llvm.mlir, test/Conversion/amd/minmax.mlir, test/TritonGPU/amd/amd-conditional-barrier.mlir, third_party/amd/include/Dialect/TritonAMDGPU/IR/TritonAMDGPUAttrDefs.td, third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp, third_party/amd/lib/TritonAMDGPUToLLVM/PatternTritonGPUOpToLLVM.h, third_party/amd/lib/TritonAMDGPUToLLVM/TritonGPUToLLVM.cpp
In the current implementation we reset mode register every time when we perform FP conversion to FP8 data type. We modify F16_OVFL flag which also effects clamping during conversions of the FP16 data type. In fact, the flag should be inserted only one (e.g., at the beginning of a kernel). This PR addresses this issue. It moves the manipulation with the mode register to a dedicated rewrite pattern. The new pattern gets initialized with an `AMD::ISAFamily` instance. Note, the the layout of bits in mode register may vary from architecture to architecture.
- No new tests are added. The old ones cover the changes in the source code
=> [AMD] FP Conversion refactoring

lib/Dialect/TritonGPU/IR/Dialect.cpp, lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp, python/test/gluon/test_core.py, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/MMAHelpers.h, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/MMAv5.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/DotOpToLLVM/WGMMA.cpp, third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TensorMemoryToLLVM.cpp
We fix a bug we had in the matrix descriptor lowering. We also add
comprehensive gluon tests for the `swizzling=0` case. To do so, we allow
`wgmma` to accept `SharedLinearLayout` when it takes a shared memory
argument.
While testing all the cases for `swizzling=0` we found a `ptxas` bug in some of them.
For now, we disable `ptxas` optimisations in some of the test cases to work around this.
=> [BACKEND] Fix swizzling=0 support for matrix descriptors and generalize wgmma lowering

python/src/ir.cc, python/test/unit/language/test_line_info.py, python/triton/language/core.py
The `tl.map_elementwise` op currently gets created with an unknown location. This can cause the `llvm.di_scope` pass to fail if the `tl.map_elementwise` lowering creates a call op. 
The location gets lost during setup of the op, so just save/restore it during the code gen.
=> Fix unknown location for map_elementwise op.

include/triton/Dialect/TritonGPU/Transforms/Utility.h, lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp, lib/Dialect/TritonGPU/Transforms/Utility.cpp, test/TritonGPU/combine.mlir
When we construct a slice, we correctly only consider rematerialisations
that dominate the use in question. However, when rewriting the slice, we
allow any rematerialisation, including one that might not dominate the
users we want to rewrite.
To address this, record the set of rematerialisations that we permitted
while constructing the slice, and reuse them when rewriting the slice.
This ensures that both operations consider the same set of valid
rematerialisations.
Note that it is important that they are the same, because slice creation
stops once it encounters a valid rematerialisation, so the inputs to the
value we are looking up will not be in the slice.
This addresses the crash in https://github.com/triton-lang/triton/issues/8257.
- …
=> Persist valid rematerialisations from slice creation
