lib/CMakeLists.txt

Fix the hard-coded include path to one that respects the `CMAKE_INSTALL_PREFIX`.

Fix include path destination

---

lib/CMakeLists.txt

Projects that only depend on the clBLAS routines implemented by
ISAAC do not have any other clBLAS dependency than ISAAC. However, they
need the clBLAS header files installed. This fix makes it so that such
projects only need to install ISAAC.

Copy clBLAS header files upon install

---

lib/api/blas/clBLAS.cpp
lib/jit/generation/elementwise_1d.cpp
lib/jit/generation/elementwise_2d.cpp
lib/jit/generation/reduce_1d.cpp
lib/jit/generation/reduce_2d.cpp
lib/jit/generation/tools/arguments.hpp
lib/jit/generation/tools/loop.hpp
lib/jit/syntax/engine/object.cpp

Hi @ptillet 
We used clBLAS test suite to test the functional correctness of current ISAAC code and found that there are two points that ISAAC blas code didn't align with blas api standard.
1, negeative inc for vector; 2, clblasConjTrans on parameters.
This patch supported negative inc for vector and clblasConjTrans, and can pass all the clblas correctness test.

Negative inc of vector && clblasConjTrans supported

---

.ci/azure-pipelines.yml
.ci/build-wheels.yml
docs/getting-started/installation.rst
python/setup.py

The solution proposed in the previous #77 can create namespace conflicts when `triton` and `triton-nightly` have both been pip installed. Therefore, this PR is moving nightly releases to pre-releases in the main triton index.

[CI] Changed triton-nightly to --pre triton

---

python/triton/ops/blocksparse/matmul.py

In the backward pass for the blocksparse matmul op, a 'variable referenced before assignment' error would occur whenever either the A or B tensors don't need input grad. This PR fixes that crash.

Fix variable referenced before assignment error in sparse matmul backward

---

lib/codegen/selection/generator.cc
python/src/triton.cc
python/triton/code_gen.py
python/tutorials/01-vector-add.py

An example can be found in triton/python/tutorical/01-vector-add.py
```python
print(kernel.asm('ptx'))
```

Allow triton.code_gen.Binary to print asm.

---

python/triton/ops/blocksparse/matmul.py

The blocksparse matmul op seems to have been intended to work for tensors with less than 3 or 4 dimensions, since there's a `_pad_shape` function made explicitly to unsqueeze the input tensors to work with the kernel. But this `_pad_shape` function only padded sparse tensors up to 3 dimensions, while the lookup table-creating functions and kernel itself actually assume that all input tensors always have 4 dimensions. This caused a crash whenever a 3-dimensional sparse tensor was used as an input.
This PR fixes the crash by simply changing `_pad_shape` to always pad tensors to 4 dimensions. Also, I removed some local variables that my IDE said were not being used by anything, and after removing them the code still seems to work as expected.

Fix crash in sparse matmul for tensors w/ less than 4 dims

---

lib/driver/dispatch.cc
python/bench/bench_cross_entropy.py
python/triton/language.py
python/triton/testing.py

* Load libcuda.so.1 if libcuda.so is not there. Error if both aren't
there.
* Multiple grad_to_none
* Benchmark dataframe printed along with name

[GENERAL] Minor improvements

---

include/triton/ir/module.h
lib/ir/module.cc
python/src/triton.cc
python/triton/code_gen.py

Inline functions didn't restore scope of parents. Also some control flow
structure still had the scoping semantics of C++

[PYTHON] Fixed bug in scoping mechanism

---

include/triton/ir/builder.h
lib/codegen/pass.cc
lib/codegen/selection/generator.cc
lib/ir/builder.cc
lib/ir/dispatch.cc

* Now using unordered instead of ordered float (fixes NaN issues)
* Bool -> int32 now converts to 1 rather than -1
* Reduce extend arguments to 32-bits if possible

[LANG] Minor semantic changes

---

docs/programming-guide/chapter-2/related-work.rst

Hey, this fixes some math / citation / typo issues on the related work page.
Also, the figure `polyhedral-iteration.png` is wrong (i < j should be i > j) and most importantly doesn't match the code of the for loop and following equation.
Should the figure be updated to match the text, or the text be updated to match the figure?

[DOCS] Fix related work

---

include/triton/ir/basic_block.h
include/triton/ir/function.h
include/triton/ir/instructions.h
include/triton/ir/module.h
include/triton/ir/value.h
lib/codegen/pass.cc
lib/ir/print.cc

* SlotTracker-based IR printer for both `module`, `function`, `basic_block`, and `instruction`.
* Examples:
* mod->print(std::cout)
* func->print(std::cout)
* bb->print(std::cout)
* instr->print(std::cout) 
* Compared with the original `ir::print()`, the new IR printer can record indices of values. `instruction::print(std::ostream &os)` can be called directly without calling `ir::print(mod, std::cout)` first.
* Add `const` accessors in `module`, `function`, and `basic_block`

Better IR printer

---

python/triton/code_gen.py

Change: `@heuristics` decorator to `@triton.heuristics`. This code example shows up in the [documentation](https://triton-lang.org/python-api/generated/triton.heuristics.html) as well. 
Error when using just `@heuristics`:
```
NameError                             Traceback (most recent call last)
<ipython-input-7-1ac8acb536e2> in <module>
7 #     key=['n_cols'],
8 # )
----> 9 @heuristics(values={'BLOCK_SIZE': lambda args: 2 ** int(math.ceil(math.log2(args[4])))})
10 @triton.jit
11 def softmax_kernel(
NameError: name 'heuristics' is not defined
```

@heuristics decorator docs. 

---

python/triton/__init__.py
python/triton/code_gen.py

- Add a cache_version kwarg to triton.jit, so users can invalidate caches (for changes that do not affect the source of the function itself)
- Add a` __repr__` to JITFunction, so we don't include memory addresses in our cache key
- Include triton version, nvcc version, ptxas version in cache name, compute capability in cache key
- Don't rely on file mtimes for staleness
- Use tuples instead of frozensets for order guarantee
- Sort meta_key

[FRONTEND] Add cache_version to triton.jit

---

python/triton/code_gen.py

In #306, I added the key to the cache data, so we can introspect to
investigate cache misses. Unfortunately, the key isn't pickleable,
so just add the str version instead.

[FRONTEND] fix for unpickleable keys

---

CMakeLists.txt
lib/codegen/selection/generator.cc
lib/driver/llvm.cc
python/setup.py
python/test/unit/language/test_core.py

This pr adds functionality for a basic load operator which allows us to execute unary and binary opreators. The only binary operator that doesnot work is the remainder(%) operator.
To check this pr
0. enter a rocm docker container 
``` alias drun='sudo docker run -it --rm --network=host --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --ipc=host --shm-size 16G --device=/dev/kfd --device=/dev/dri' ```
``` drun rocm/pytorch ```
1. clone and check out this branch
```git clone -b rocm_bin_op_pr_2 https://github.com/micmelesse/triton```
2. build triton with the following steps 
```cd python ```
```pip install --verbose -e .```
3. test with 
```
pytest --capture=tee-sys --verbose python/test/test_language.py::test_empty_kernel
pytest --verbose …
```

enable unary and most binary operators

---

python/test/unit/runtime/test_comm.py

My p2p matrix looks like this, and it seems like it was not handled correctly:
```
GPU0	GPU1	
GPU0	X	NS	
GPU1	NS	X
```
`skipif` does check for empty device lists, but the `get_*_devices` functions never used to return them.

Fixed p2p tests failing when there are no supported p2p devices

---

lib/codegen/selection/generator.cc
python/requirements-test.txt
python/setup.cfg
python/src/pybind11/detail/internals.h
python/test/unit/language/test_core.py
python/test/unit/language/test_random.py
python/triton/code_gen.py
python/triton/language/__init__.py
python/triton/language/core.py
python/triton/language/random.py

- Fix some whitespace.
- Make an undeclared dependency on `pytest` explicit.
- Fix deprecated `description-file` use.
- `#ifdef` out a deprecated `PyEval_InitThreads` call.
- Use a slightly different numpy invocation in `test_random.py` to quiet down overflow warnings in tests.
- Fix a deprecated cast in `test_core.py`.
- Suppress a warning about `visit_Constant` in Python 3.9+; we can't migrate yet because it'd break Python 3.6 and 3.7.
- Use chained exceptions for `CompilationError` rather than rolling our own; it makes the error messages nicer.
- Add a `__str__` for `tl.dtype` to make debugging kernels easier; it lets you `print` a dtype to see what type was inferred.
- Fix a few bad escapes.

minor accumulated style and warning fixes

---

include/triton/ir/type.h
python/triton/code_gen.py
python/triton/language/core.py

- Don't override `self.args` in `CompilationError`, and show the line number and column in error messages. This causes it to generate an easier-to-read backtrace.
- Better `__str__` on `TensorWrapper`, `dtype`, and `block`.

better stringification

---

python/src/triton.cc

The legacy print call will assign names (e.g., %10) to values, which can be undesirable in some cases.

Replace the legacy print call in triton.cc with the SlotTracker-based one

---

lib/ir/dispatch.cc
python/test/unit/language/test_core.py
python/triton/code_gen.py
python/triton/testing.py

- Promote 16-bit floating-point `/` and `%` to 32-bit; we have to anyway.
- Do not force result of integer binary operations to be the LHS type. There used to be a bug in pytorch that did this, which Triton matched, but that bug is fixed now.
- When testing signed integer operations, use random numbers from the full range of the type.
- Add an optional `seed` argument to `triton.testing.random` so binary operations are not tested with both sides equal when the LHS and RHS have the same type.
- Fix a bad `CompilationError` invocation.
- Fix a warning suppression that causes tests to fail if you run them with `-W error` on python 3.8.

signed-integer math fixes and testing

---

python/src/triton.cc
python/test/unit/runtime/test_cache.py
python/triton/code_gen.py

Added an additional `repr` argument to the cache hook, which represents a human-readable string representation of the signature and argument attributes associated with the compiled binary.

[FRONTEND] Better cache hook

---

include/triton/ir/type.h
lib/ir/dispatch.cc
lib/ir/instructions.cc
python/src/functions.h
python/src/triton.cc
python/test/unit/language/test_core.py
python/triton/language/core.py

- `BF16TyID` was missing a repr implementation.
- Throw a better exception on impossible casts.
- Add a few assertions. Tested with a debug build.
- Add `pointer_dtype.__str__` to aid kernel debugging.

add missing bfloat16 repr and improve assertions

---

python/requirements-test.txt
python/test/unit/language/test_core.py
python/triton/testing.py

Since numpy supports unsigned integers, and pytorch doesn't, this will make it easier to test unsigned integer support.
This adds an explicit requirement for numpy in tests, but we already required scipy, so it was already an implicit dependency.

use numpy for reference results in test_core.py

---

include/triton/ir/builder.h
include/triton/ir/context_impl.h
include/triton/ir/type.h
lib/ir/builder.cc
lib/ir/context.cc
lib/ir/dispatch.cc
lib/ir/type.cc
python/src/triton.cc
python/test/unit/language/test_core.py
python/test/unit/language/test_random.py
python/triton/code_gen.py
python/triton/language/core.py

A forthcoming PR will update the RNG to use these types.
Also:
- Add tests for the `//`, `<<`, and `>>` operators.
- Change `TensorWrapper` to unwrap objects when the resulting object would be simpler.
- Clean up `throw_unreachable`, since it was triggering compiler warnings.

uint8, uint16, uint32, and uint64 in kernels

---

.github/workflows/documentation.yml
.github/workflows/integration-tests.yml
docs/getting-started/installation.rst
python/requirements-test.txt
python/setup.py
python/test/regression/test_performance.py
python/tutorials/02-fused-softmax.py
python/tutorials/03-matrix-multiplication.py
python/tutorials/04-low-memory-dropout.py
python/tutorials/05-layer-norm.py
python/tutorials/README.rst

- Fix meta-parameter usage on tutorials.
- Install tutorial dependencies on CI.
- Switch from `requirements-test.txt` to `extras_require` for test dependencies, and also use it for tutorial dependencies.
- Make some performance tests deterministic.

fix tutorials for v2.0

---

python/triton/ops/blocksparse/matmul.py
python/triton/ops/blocksparse/softmax.py

Modifications:
- Remove unnecessary loop in make_lut functions for speedup.
- Add support for CUDA and torch.bool layout. CPU and torch.long layout remains supported.
- CUDA layout gives better speed for large layout.
- Boolean layout can help save memory, and users are free from manual bool-to-long transformation.
Code is tested.

[OPS][BLOCKSPARSE] Remove unnecessary loop and add CUDA bool layout support

---

python/triton/language/random.py

Make sure offset dtype is always uint32 before calling uint32_to_uniform_float

[FRONTEND][RANDOM] Fix bug in uniform random number generation

---

include/triton/external/CUDA/cuda.h
python/src/triton.cc
python/triton/code_gen.py
python/triton/language/core.py

Now Triton doesn't generate aligned(N) for pointers that point to memory regions whose size is not aligned to N bytes

[FRONTEND] Alignment fix-up

---

python/triton/language/random.py

The unsigned int PR definitely improved our RNG. However, it requires
different floating point arithmetics which, means the results are not
bit-wise identical to how they were before. This commit revives backward
compatibility, but we should change it back to the "right" way later.

[FRONTEND][RANDOM] Improved backward compatibility of RNG

---

include/triton/ir/type.h

Not sure what compiler you  typically use, but I cannot get triton v2.0 to `pip install -e .` with GCC 9 or 10 without this, std::logic_error cannot be resolved (which does look like a legit error, see [cppreference](https://en.cppreference.com/w/cpp/error/logic_error))

[minor][v2.0] Hotfix for gcc compilation

---

lib/codegen/selection/generator.cc
python/test/unit/language/test_core.py

Main design decision is what to do with fp16 values that have the first bit of their exponent set since they're not representable in the triton fp8 format. I chose to convert to garbage values. Only other plausible option would be to convert to the largest fp8 value. My guess is anyone using this functionality has already scaled their fp16s to be in the range of fp8s so they don't care what happens.

Add fp16 to fp8 conversion

---

lib/driver/llvm.cc

Bug: "ret" value is destroyed when a failing "ptxas --version" is run
overwriting the previous valid "ret" value.
Fix: keep rets only for those runs which are successful. Pick the first
one
https://github.com/openai/triton/issues/486

Bugfix in ptxas path.

---

python/bench/bench_blocksparse.py
python/test/unit/language/test_core.py

[1] I notice that for `matmul` and `softmax` we should provide an `device` kwarg, otherwise it may raise error because device is missing. So I add `device="cuda"` for the benchmark script.
[2] I also find that, in `test_core.py`, you use a new feature which is not supported by a low version python. You use [f-strings support =](https://docs.python.org/3/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging), which is available only for python>=3.8. To be compatible with low versions, I remove this new feature, and just use the plain f-strings instead.

provide device kwarg, and fix f-string incompatibility for py<3.8

---

python/triton/code_gen.py
python/triton/language/core.py

With fast (200 ns) get_stream function soon to be available from pytorch this shaves off approx 25-30 us from function launch, but even without that function due to caching device properties we are saving ~15-20us.

faster jit function launch

---

python/src/triton.cc

Without this binding, the following test fails
```
import torch
import triton
@triton.jit
def lookup_directly(input_ptr_ptr, output_ptr):
input_ptr = tl.load(input_ptr_ptr)
input_ptr = input_ptr.to(output_ptr.dtype, bitcast=True)
input = tl.load(input_ptr)
tl.store(output_ptr, input)
def test_lookup_directly():
input_tensor = torch.ones((1), dtype=torch.float32, device="cuda")
input_ptr = input_tensor.data_ptr()
input_ptr_tensor = torch.full(
(1,), fill_value=input_ptr, device="cuda", dtype=torch.long
)
output_tensor = torch.empty_like(input_tensor)
grid = (1,)
lookup_directly[grid](
input_ptr_ptr=input_ptr_tensor, output_ptr=output_tensor, num_warps=1
)
print(output_tensor)
if __name__ == "__main__":
test_lookup_directly()
```
with the error:
```
... snip ... …
```

Add binding for create_int_to_ptr

---

python/test/unit/language/test_core.py
python/triton/language/semantic.py

Fixes #544. Note, this is a bc-breaking change if someone indeed relied on fp values less than 1 to be converted to `False`

fix bool conversion of floating types

---

python/setup.py
python/triton/code_gen.py

This prevents potential conflicts with other users on shared machines.

[PYTHON] move ephemeral files to homedir

---

python/bench/bench_matmul.py

UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc').

Fix pytorch warning. 

---

docs/python-api/triton.language.rst
python/triton/language/core.py

I also found many some functions (e.g., `shl`) in `semantic.py` are not documented. May need to take another pass to fix the documentation later.

Separate atomic cas from other atomic operations since operands are very different

---

lib/codegen/selection/generator.cc
python/test/unit/language/test_core.py

There are two potential problems.
```
in_ord = in_layout->to_mma() ? out_ord : in_ord;
out_ord = out_layout->to_mma() ? in_ord : out_ord;
```
I'm not sure if the above line was written on purpose? If `in_layout->to_mma() == True`, `in_ord=out_ord`, then if `out_layout->to_mma() == True`, `out_ord = in_ord = out_ord`. So `out_ord` is unchanged.
The second problem is that we shouldn't use vectorized shared memory store if the input is in a transposed order, specifically for this [case](https://github.com/Jokeren/triton-samples/blob/main/transpose-2d.py).
Besides, I think probably we could tune the performance in the future with thread/layout reassociation. For instance, in layout convert, if we want as many vectorized shared memory loads as possible, we can adjust the thread/layout mapping …

Fix layout convert for non-contiguous input

---

python/triton/language/semantic.py

Improved error messages when the arguments of `arange` are not annotated with `tl.constexpr`.

Added type check in semantic arange

---

python/triton/ops/matmul_perf_model.py

On a V100 I was getting:
```
File "/home/circleci/project/torchdynamo/output_graph.py", line 341, in call_user_compiler
compiled_fn = self.compiler_fn(gm, self.example_inputs())
File "/home/circleci/project/torchinductor/compile_fx.py", line 118, in compile_fx
return compile_fx_inner(gm, example_inputs, wrap=wrap, cudagraphs=cudagraphs)
File "/home/circleci/project/torchinductor/compile_fx.py", line 145, in compile_fx_inner
return cudagraphify(
File "/home/circleci/project/torchinductor/compile_fx.py", line 179, in cudagraphify
model(*inputs)
File "/home/circleci/project/torchdynamo/optimizations/python_key.py", line 168, in call_fn
return inner(*params_flat, *args)
File "/tmp/torchinductor_circleci/e3/ce32oubh7w7iwszqqbgpirjkej5ybhnhfufejzlzg3h5isfza3eo. …
```

Add missing args to get_simd_tflops()

---

python/setup.py

This should make https://github.com/openai/triton/pull/562 work with `setup.py install` / `pip install` rather than just `setup.py develop`.
Our CI was failing with:
```
>       name, asm, shared_mem = _triton.code_gen.compile_ttir(backend, generator.module, device, num_warps, num_stages, extern_libs)
E       RuntimeError: Failed to load extern lib libdevice at /home/circleci/project/env/lib/python3.8/site-packages/triton/language/libdevice.10.bc
env/lib/python3.8/site-packages/triton/code_gen.py:1320: RuntimeError
```

Include triton/language/libdevice.10.bc in package data

---

lib/codegen/selection/generator.cc
lib/ir/constant.cc
python/test/unit/language/test_core.py
python/test/unit/operators/test_cross_entropy.py
python/triton/language/semantic.py
python/triton/ops/cross_entropy.py
python/tutorials/06-fused-attention.py

* [FRONTEND] Check if bf16 is supported. If it's not supported, cast value to fp32.
* [CODEGEN] Use int16 as the storage type for bf16. Manually select add, mul, sub for bf16. Manually select bf16 constant.
* [OP] Fix type casting for cross_entropy's bwd kernel.
---
Thanks to @samsamoa for the original proposal and @tomconerlyanth for providing bf16 tests.

Better bf16 support

---

python/src/triton.cc
python/test/unit/runtime/test_cache.py
python/tutorials/03-matrix-multiplication.py

Draft proposal to update the cache logic. 
Testing cases and document are incomplete.
By revisiting the caching logic, my understanding is that we should update a binary/kernel whenever the following characteristics are changes:
1. The signature of the kernel's source code.
2. The signatures of inlined JIT functions being called.
3. The signatures of outlined JIT functions being called.
4. The length of any non-constexpr variables.
5. The number of variables.
6. The value of constexpr variables.
7. The alignment, date type, and ptr length of tensors.
8. The number of warps and stages.
This patch tries to fix a corner case of characteristics 3 (C3).

Refresh cache when the source code of outlined functions are changed

---

lib/ir/type.cc

[BACKEND][IR] Fixed up internal dtype size for booleans (1bit -> 8bit)

---

python/test/unit/language/test_core.py
python/triton/language/core.py
python/tutorials/06-fused-attention.py

Triton was failing on this pattern:
```
def kernel0(in_ptr0, in_ptr1, out_ptr0, out_ptr1, ks0, xnumel, rnumel, XBLOCK : tl.constexpr, RBLOCK : tl.constexpr):
xoffset = tl.program_id(0) * XBLOCK
xindex = xoffset + tl.reshape(tl.arange(0, XBLOCK), [XBLOCK, 1])
...
x2 = xindex % (32 // ks0)
x2_next = xindex // (32 // ks0)
```
With the error:
```
File "/home/jansel/triton/python/triton/code_gen.py", line 437, in visit_BinOp
return getattr(rhs, fn)(lhs, _builder=self.builder)
AttributeError: 'tensor' object has no attribute '__rfloordiv__'
```

[FRONTEND] Add missing rfloordiv

---

python/test/unit/language/test_random.py
python/triton/language/random.py

The previous version of `tl.rand()` could generate 1.0.  Looking at the docstrings I don't think this was intentional and doesn't match `torch.rand()`
cc @ngimel

[FRONTEND] Make tl.rand() 1-exclusive

---

python/src/triton.cc

Small QOL change when using the Python builder/module API

Expose `module.print` in pybind

---

include/triton/ir/instructions.h
include/triton/ir/metadata.h
include/triton/ir/module.h
lib/codegen/analysis/align.cc
lib/ir/metadata.cc
python/src/triton.cc
python/triton/language/core.py
python/triton/language/semantic.py

Now `tl.multiple_of` and `tl.max_contiguous` can accept n-d integer values as hints. Hints' length must match inputs' rank.

Allow multiple_of and max_contiguous to accept n-d values

---

python/src/triton.cc

Redo of #651 against master. Fixes #525 by catching CUDA error when we check pytorch tensor size and rethrowing a more informative error that says why we failed.

Improve error message for CPU tensors

---

.github/workflows/integration-tests.yml
include/triton/Conversion/TritonGPUToLLVM/PtxAsmFormat.h
include/triton/driver/dispatch.h
lib/Conversion/TritonGPUToLLVM/PtxAsmFormat.cpp

This PR is to add GitHub Actions runners to the CI for better coverage.
1. A `self-hosted` runner deployed by OpenAI cannot be used for an external repository, so a developer cannot locally test a change by creating a PR to, for example, my own repository (like https://github.com/shintaro-iwasaki/triton/pull/2).  To run a test, draft/WIP PRs need to be created, making the official GitHub repository messy.
2. Setting of `self-hosted` is not public, so a developer is not sure if the problem is in the self-hosted machine or his/her code.
3. Build for macOS is currently broken (at least, on GitHub)
This PR adds the default GitHub runners (`macos-latest` and `ubuntu-latest`) to CI.
1. I can test my change using my forked GitHub repository without creating a PR (though it's not complete since …

[Triton-MLIR] add GitHub CI runners

---

python/tests/test_cast.py
python/triton/compiler.py
python/triton/language/core.py
python/triton/language/semantic.py

This PR solves the cast issue that appears in some tutorial code.
The frontend cannot compile the following code because `tensor<f32>` returned by `tl.max(row, axis=0)` was not cast properly to `tensor<256xf32>`, which is the type of `row`.
```py
import triton
@triton.jit
def softmax_kernel(
output_ptr, input_ptr,
BLOCK_SIZE: tl.constexpr
):
col_offsets = tl.arange(0, BLOCK_SIZE)
row = tl.load(input_ptr + col_offsets)
row_minus_max = row - tl.max(row, axis=0) # <=================== This line
tl.store(output_ptr + col_offsets, row_minus_max)
if __name__ == "__main__":
output = triton.compile(softmax_kernel, "*fp32,*fp32", device=0, constants={'BLOCK_SIZE': 256}, output="ttir")
print(output)
```
This PR fixes this issue by fixing/extending the implicit broadcast …

[Triton-MLIR][FRONTEND] Fix the implicit broadcasting rule

---

python/test/unit/runtime/test_cache.py
python/triton/runtime/autotuner.py
python/triton/runtime/jit.py
python/triton/utils.py

Reverts openai/triton#671
It seems like for some reason this caused out-of-memory errors on some of our internal workloads. I'm reverting this so that HEAD can be used in production at OpenAI, and I will work on digging into this issue asynchronously.

Revert "Add .warmup() for triton.jit()"

---

README.md

Initial wording dates from a time where nobody knew Triton, and comparing it to CUDA helped differentiate it from other existing DSLs. But nowadays this comparison doesn't make much sense; Triton is its own thing, and some people may even still be more productive in CUDA than Triton -- language preferences are subjective after all.

[DOCS] Improved README.md wording

---

python/triton/compiler.py

@ngimel figured this one out. 
The errors we were seeing from cudagraphs capture were coming from `cuStreamGetCtx` which is not allowed while a stream is capturing.
It appears the result of `cuStreamGetCtx()` isn't even used, so I believe it can just be removed.

Fix issue breaking cudagraphs

---

python/test/unit/runtime/test_cache.py
python/triton/runtime/autotuner.py
python/triton/runtime/jit.py
python/triton/utils.py

This revives #671 , removing the static functions (and calls to `warmup` once the grid is fixed).

Add warmup for triton.jit()

---

python/src/pybind11/attr.h
python/src/pybind11/buffer_info.h
python/src/pybind11/cast.h
python/src/pybind11/chrono.h
python/src/pybind11/complex.h
python/src/pybind11/detail/class.h
python/src/pybind11/detail/common.h
python/src/pybind11/detail/descr.h
python/src/pybind11/detail/init.h
python/src/pybind11/detail/internals.h
python/src/pybind11/detail/type_caster_base.h
python/src/pybind11/detail/typeid.h
python/src/pybind11/eigen.h
python/src/pybind11/embed.h
python/src/pybind11/eval.h
python/src/pybind11/functional.h
python/src/pybind11/gil.h
python/src/pybind11/iostream.h
python/src/pybind11/numpy.h
python/src/pybind11/operators.h
python/src/pybind11/options.h
python/src/pybind11/pybind11.h
python/src/pybind11/pytypes.h
python/src/pybind11/stl.h
python/src/pybind11/stl/filesystem.h
python/src/pybind11/stl_bind.h

This PR updates the version of pybind11 to 2.10.0 (the latest stable).
This PR upgrades pybind11 as follows to fix #687:
```sh
cd python/src
rm -rf pybind11
wget https://github.com/pybind/pybind11/archive/refs/tags/v2.10.0.zip
unzip v2.10.0.zip && mv pybind11-2.10.0/include/pybind11 .
```
I would appreciate any feedback from you.
- Is `git submodule` better?
- Should it only apply to Triton (or Triton-MLIR)?
- Should I add build tests with Clang?
```sh
$ cd python
$ clang --version
clang version 14.0.0 (Red Hat 14.0.0-1.module_el8.7.0+1142+5343df54)
...
$ CC=clang CXX=clang++ with-proxy pip3 install -e '.[tests]'
...  
/home/siwasaki/triton/python/src/pybind11/pybind11.h:1009:9: error: no matching function for call to 'operator delete'
::operator delete(p, s, std::align_val_t(a)); …
```

[pybind11] Update pybind11 to 2.10.0

---

.github/workflows/integration-tests.yml
lib/Dialect/Triton/Transforms/Combine.cpp
lib/Dialect/TritonGPU/Transforms/Pipeline.cpp
test/Triton/combine.mlir

1. In Triton-MLIR's combine pass, I didn't check if `getDefiningOp()` returns `nullptr` or not. Unlike `dynamic_cast`, `llvm::dyn_cast` fails if `nullptr` is passed. The first two commits fix this issue and add tests to check the behavior.
2. `Pipeline` transformation in TritonGPU-MLIR uses a wrong index to access the `mask` argument of `insert_slice_async`. The last commit fixes this issue.
(Note that the these issues are found to try to compile the tutorial matmul code.)

[Triton-MLIR] Fix a few minor issues

---

python/triton/runtime/jit.py

I suspect this was the cause of the "new compiles even on a warm cache" behavior I was seeing, though haven't 100% confirmed it.
Python `set()` iteration order is nondeterministic when you create a new process.  So the same args could produce different `instance_descriptor`s and have false cache misses.

Reduce number of compiles in JITFunction

---

lib/driver/llvm.cc
python/src/triton.cc
python/test/unit/runtime/test_cache.py
python/triton/compiler.py

This allows compiling in a subprocess.
I'm not seeing a ton of speedup from this, but figure it is a good change anyway.

Make triton.compile work without a cuda context

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
test/TritonGPU/coalesce.mlir

Example:
```
auto encoding = triton::gpu::BlockedEncodingAttr::get(
&getContext(), {8, 32}, {2, 2}, {1, 0}, 2);
//shape = [32 x 8], order = [1, 0], sizePerThread=[2, 2], numWarps=2
```
Expected output:
```
//#triton_gpu.blocked_layout<{
//  sizePerThread = {2, 2}
//  threadsPerWarp = {8, 4}
//  warpsPerCTA = {2, 1}
//}>
```
Incorrect output by the current branch
```
//#triton_gpu.blocked_layout<{
//  sizePerThread = {2, 2}
//  threadsPerWarp = {16, 2}
//  warpsPerCTA = {2, 1}
//}>
```

[Triton-MLIR] Fix threadsPerWarp derivation in BlockedEncodingAttr

---

lib/codegen/transform/inline.cc
python/test/unit/language/test_core.py

If a function that has a phi-node (e.g., for loop) is called, compilation fails because of `IndexError: map::at`.  This can prevent the user from modularization of Triton kernels (e.g., for fusion, we write two functions and call them in another function).
```py
@triton.jit
def matmul_and_something(...)
matmul(...) # matmul code (e.g., one in a tutorial) contains a loop and thus a phi-node in Triton-IR,
something(...)
```
Modify `inliner.cc` by fixing the following two:
- Previously, the inliner assumes that, before an instruction, all of its operands appear (and thus are created). It is true in terms of SSA except for a phi node. Let's replace operands of the new instructions once we generate all the new instructions.
- `replace_uses_of_with()` does not replace incoming basic blocks of …

[CODEGEN] Fix an inliner to call a function with a phi-node

---

python/triton/compiler.py

`ttir` and `llir` seem to have similar size to `ptx` IR in text format, each taking 10-30KB per triton function. So I suppose it's not a big issue by loading them into memory?

[RUNTIME] Dump llvm, ttir, and sass to help debugging

---

python/test/unit/language/test_core.py
python/triton/compiler.py

On my system `whereis libcuda.so` (which is used in `libcuda_dir()` in `compiler.py`) returns multiple locations (one is for 32 bit version of library, the other for 64 bit).
`libcuda_dir()` currently only uses the last location returned, and this leads to linker errors when running triton if the last location is not the one needed.
This updates the compiler command to use all locations and makes triton work again in my system.

Support environments with multiple cudalibs

---

python/triton/compiler.py

Use environment variable `CUDA_HOME` with default value `/usr/local/cuda` for `cu_include_dir`
#731

remove fixed cu_include_dir

---

.gitignore
CMakeLists.txt
python/setup.py
test/CMakeLists.txt

Prefix Triton specific CMake options with `TRITON_`
Replace `STANDALONE_` prefix with `TRITON_` prefix in test dependencies
(also including my `.gitignore` fix from main)

Add TRITON Prefixes

---

CMakeLists.txt

This change enables `CMAKE_INCLUDE_CURRENT_DIR` when building Triton.

enable current-dir inclusion

---

include/triton/codegen/analysis/align.h
include/triton/codegen/analysis/axes.h
include/triton/codegen/selection/generator.h
include/triton/ir/builder.h
include/triton/ir/enums.h
include/triton/ir/instructions.h
include/triton/ir/visitor.h
lib/codegen/analysis/align.cc
lib/codegen/analysis/axes.cc
lib/codegen/selection/generator.cc
lib/ir/builder.cc
lib/ir/instructions.cc
python/src/triton.cc
python/test/unit/language/test_dequantize.py
python/triton/language/core.py
python/triton/language/semantic.py

implemente a dequantize instruction in triton
```
def dequantize(input, scale, shift, nbit, dst_ty=float16, _builder=None):
```
input is nbit (8, 4, or 2) integers packed into int16s or int32s. scale and shift are float16 scalars. For example, for nbit = 8, input is of type int32. The instruction will convert [{int8_0, int8_1, int8_2, int8_3}, {int8_4, int8_5, int8_6, int8_7}, ...] (every four int8s packed into one int32) to  scale * [int8_0, int8_1, int8_2, int8_3, int8_4, int8_5, int8_6, int8_7, ..., ] + shift in float16s. If the size of input is N, the size of output is 4 * N. Similarly for int4 and int2, eight int4s are packed into one int32 and eight int2s are packed into one int16. See test file https://github.com/yuguo68/triton/blob/dequantize_inst/python/test/unit/language/test_deq …

[RFC] triton dequantize instruction

---

lib/codegen/selection/generator.cc
python/test/unit/language/test_core.py

Init a potential fix for mov.u8 which is not supported by ptx for now. Use mov.u16 instead and cast it to u8.

[Backend] Fix for mov.u8 

---

docs/getting-started/installation.rst

When building for windows, I got an error because a submodule dependency here wasn't initiliaized: https://github.com/openai/triton/tree/master/deps

Update installation.rst to fix windows build error

---

include/triton/ir/instructions.h
lib/codegen/selection/generator.cc
lib/ir/instructions.cc
python/triton/language/libdevice.py
python/triton/tools/build_extern.py

Fix two problems in libdevice and external dispatch:
1. Use static triton types (e.g., tl.int32) instead of creating new types. Otherwise, `tl.int32` and `tl.dtype('int32')` are not the same thing.
2. The name of an extern inst should be empty but not the symbol name of the inst. TTIR generator will assign names automatically. Otherwise, we have the same variable name when there are multiple same extern insts. 
Before the PR:
```bash
__nv_exp = extern_elementwise f64<1024> %11;
__nv_exp = extern_elementwise f64<1024> %11;
```
After the PR:
```bash
%12 = extern_elementwise f64<1024> %11;
%13 = extern_elementwise f64<1024> %11;
```

[FRONTEND] Fix libdevice

---

python/setup.py

I noticed the `check-triton` target has been remove in [PR#790](https://github.com/openai/triton/commit/bb0f9235d182c88851aab5e3d1819b8e17350769#diff-33394812ba204689144fd2f80832db83853ba1cb32403edb4e15fe4893e675fdL18).
But the `call` is still reserved in [setup.py](https://github.com/openai/triton/blob/triton-mlir/python/setup.py#L131), this will trigger a error `make: *** No rule to make target 'check-triton'.  Stop.`

[Triton-MLIR][FRONTEND] Remove the dangling `check-triton` call in setup.py

---

python/triton/compiler.py

In ```torch._inductor```, we [convert 0d CPU tensor to scalar during triton codegen](https://github.com/pytorch/pytorch/pull/87329), so need add missing triton support for bf16/fp16/fp64.

Add bf16/fp16/fp64 support for ty_to_cpp

---

include/triton/Analysis/Allocation.h
include/triton/Conversion/TritonGPUToLLVM/PtxAsmFormat.h
include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Analysis/Allocation.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
python/tests/test_reduce.py

This PR is now ready for code review.
What is done in this PR:

[Triton-MLIR][Backend] Add ReduceOpConversion into TritonGPUToLLVM conversion

---

test/CMakeLists.txt

This change adds back in the Triton test target to cmake. i've renamed it to check-triton-lit-tests.
@ptillet , this shouldn't add the lit target to the default build target as per the llvm cmake files (see code snippet below from `AddLLVM.cmake`)
Please let me know if there's additional validation i can run (or you'd like to run) before merging.
```cmake
function(add_lit_target target comment)
<snip>
set_target_properties(${target} PROPERTIES EXCLUDE_FROM_DEFAULT_BUILD ON)
endfunction()
```

Add Back Test Target

---

include/triton/Dialect/Triton/Transforms/Passes.h
lib/Dialect/Triton/IR/Dialect.cpp
python/setup.py
python/src/triton.cc
python/tests/test_core.py
python/triton/compiler.py
python/triton/language/core.py

This adds a `DialectInlinerInterface` to the Triton dialect. This, along with a few other minor semantic changes, fixes our tests on call instructions. Also added the option to provide use an "LLVM_SYSPATH" environment variable to link against locally build of LLVM; this was useful for debugging this issue.

[FRONTEND] Fixed inliner and got more tests to pass

---

README.md

Copied from here https://triton-lang.org/master/getting-started/installation.html but generally useful to have on main page

Add install from source instructions

---

python/tests/test_math_ops.py
python/triton/language/libdevice.py
python/triton/tools/build_extern.py

- Unifying several interfaces with different types to a single one, e.g. `fsub_ru` and `dsub_ru` -> `sub_ru`;
- Minor bug fix: `fast_pow` is incorrectly classified into the `pow` interface, of which arguments are the same as `powf`;
- Explicit interfaces for casting functions, e.g. decoupling `ll2float_ru` to `ll2float_ru` and `ull2float_ru`;
- Removing interfaces that are not in NVIDIA's official documents, e.g. `fmaf_ieee_rn`, which is confusing together with `fmaf_rn`.

[Triton-MLIR][Frontend] Interface fixes for libdevice

---

python/triton/language/libdevice.py
python/triton/tools/build_extern.py
python/tutorials/07-libdevice-function.py

- Unifying several interfaces with different types to a single one, e.g. `fsub_ru` and `dsub_ru` -> `sub_ru`;
- Minor bug fix: `fast_pow` is incorrectly classified into the `pow` interface, of which arguments are the same as `powf`;
- Explicit interfaces for casting functions, e.g. decoupling `ll2float_ru` to `ll2float_ru` and `ull2float_ru`;
- Removing interfaces that are not in NVIDIA's official documents, e.g. `fmaf_ieee_rn`, which is confusing together with `fmaf_rn`.
Note that this PR for the master branch is different from #829, which is for the MLIR branch.

[Frontend] Interface fixes for libdevice

---

lib/codegen/pass.cc
python/test/unit/language/test_core.py
python/test/unit/operators/test_blocksparse.py
python/test/unit/operators/test_matmul.py

This PR clarifies which features are supported on P100 via its tests, though Pascal is not officially and fully supported by Triton.
- Skip unsupported tests on P100.
- Atomic RMW
- `tl.dot()` (perhaps not all patterns, but basically most `tl.dot()` tests do not work on P100).
- Add an explicit error if shared memory size >= 64K on P100.
- Otherwise it causes `Invalid CUDA argument` error at `cuLaunchKernel()`, but this error is not very straightforward to understand. Instead of this generic CUDA argument error, this PR makes Triton show an error during codegen when `sm < 70`. This check happens in C/C++ so won't add an overhead in Triton's Python runtime.
- 3 tests (see below) are currently failing, but these are not marked as skipped because any codegen update in the future can change …

Better NVIDIA Pascal GPU Support

---

lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
test/Conversion/tritongpu_to_llvm.mlir

add atomic without mask
TritonGPU
```
#blocked0 = #triton_gpu.blocked<{sizePerThread = [1], threadsPerWarp = [32], warpsPerCTA = [4], order = [0]}>
module attributes {"triton_gpu.num-warps" = 4 : i32} {
func @atomic(%arg0 : tensor<256x!tt.ptr<f32>, #blocked0>, %arg1 : tensor<256xi1, #blocked0>, %arg2 : tensor<256xf32, #blocked0>) {
%0 = "tt.atomic_rmw" (%arg0, %arg2, %arg1) {atomic_rmw_op = 5 : i32} : (tensor<256x!tt.ptr<f32>, #blocked0>, tensor<256xf32, #blocked0>, tensor<256xi1, #blocked0>) -> tensor<256xf32, #blocked0>
return
}
}
```
LLVM
```
#blocked = #triton_gpu.blocked<{sizePerThread = [1], threadsPerWarp = [32], warpsPerCTA = [4], order = [0]}>
module attributes {"triton_gpu.num-warps" = 4 : i32, triton_gpu.shared = 0 : i32} {
llvm.mlir.global external @global_smem() {addr_space = …
```

[Triton-MLIR][Backend]add atomic rmw without mask

---

include/triton/Conversion/TritonGPUToLLVM/PtxAsmFormat.h
lib/Conversion/TritonGPUToLLVM/PtxAsmFormat.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
unittest/Conversion/TritonGPUToLLVM/PtxAsmFormatTest.cpp

This PR does
1. Add `onlyBindMLIRArgs` argument to `PTXInstrCommon::call` method to support passing in a whole PTX code snippet
2. Refine the APIs and simplify the code usage.

[Triton-MLIR][BACKEND] Refine ptxbuilder

---

lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
python/tests/test_gemm.py

This PR fix the problem of TN/NT GEMM correctness when no SCF involved. I'll continue to clean up getLinearIndex/getMultiDimIndex in a uniformed way which should be benifical to avoid different kinds of order issues. This is not fully done yet, just merge to sync the code.

[Triton-MLIR][Backend] Fix convert_layout blocked->shared in non-default order

---

python/triton/tools/build_extern.py

Ran mypy over `build_extern.py`, cleaned up type annotations.
Found a fixed a bug where `ExternLibrary(format=)` was being ignored.

Fix ExternLibrary(format=) bug; type annotate build_extern.py

---

python/triton/runtime/jit.py

The previous `{i}` was silently expanding to the `i` from the enumeration loop on `regular_args` (when it wasn't empty).

Fix format double substitution bug: `{i}` => `{{i}}`

---

lib/Target/LLVMIR/LLVMIRTranslation.cpp
lib/Target/PTX/PTXTranslation.cpp

We have been seeing the following error message for a while:
> NO target: Unable to find target for this triple (no targets are registered)
Seems that it's not necessary to setup the target triple at that point, so we can just take it out to get rid of the error message.
Variable names have been changed to the camel style.

[Triton-MLIR] Fix warnings and variable names

---

lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp

- Remove the unnecessary `static` in the anonymous namespace
- Remove several unnecessary functions
- Several simple rewrites to make code more clear

[Triton-MLIR][BACKEND] tiny code cleanup

---

include/triton/Analysis/Membar.h
include/triton/Dialect/Triton/IR/TritonOps.td
include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td
python/tests/test_gemm.py

Try to add proper side effects for triton operations. 
The CSE pass could fail, hang, or output incorrect IRs for unknown reasons, if side effects are not defined properly.
For instance, suppose we have two shared memory tensors:
```
%a = triton_gpu.alloc_tensor shape0, share_encoding0
%b = triton_gpu.alloc_tensor shape0, share_encoding0
```
The CSE pass will consider `%a` and `%b` are the same thing and eliminate one of them, resulting in mysterious outcomes.

[Triton-MLIR] Fix side effects

---

python/triton/compiler.py

Fix lookup bug where a ctime may not yet be loaded for a given ir.
```
if ir == ext:
next_module = parse(fn)
elif os.path.exists(path) and\
>                   os.path.getctime(path) == metadata["ctime"][ir]:
E                   KeyError: 'ttir'
triton/compiler.py:1425: KeyError
===== short test summary info =======
FAILED tests/test_reduce.py::test_reduce1d[max-int32-128] - KeyError: 'ttir'
```

[Triton-MLIR][RUNTIME] Fix ir metadata lookup bug

---

python/triton/compiler.py

Make `ptxas` search a bit broader to include `/usr/bin/ptxas`, installed by the lambda stack repo versions:
https://lambdalabs.com/lambda-stack-deep-learning-software
```
$ lsb_release -d
Description:	Ubuntu 22.04.1 LTS
$ dpkg-query -S /usr/bin/ptxas 
nvidia-cuda-toolkit: /usr/bin/ptxas
$ apt info nvidia-cuda-toolkit
Package: nvidia-cuda-toolkit
Version: 11.6.2-0lambda3
```

[Triton-MLIR][RUNTIME] Add /usr/bin/ptxas as a search path

---

lib/Conversion/TritonGPUToLLVM/Utility.h

Reference https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL59-CPP.+Do+not+define+an+unnamed+namespace+in+a+header+file

[Triton-MLIR][BACKEND] Remove static and unnamed namespace in Utility.h

---

include/triton/Analysis/AxisInfo.h
include/triton/Dialect/TritonGPU/IR/Dialect.h
include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td
lib/Analysis/AxisInfo.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
lib/Conversion/TritonToTritonGPU/TritonToTritonGPU.cpp
lib/Dialect/Triton/IR/Ops.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/Pipeline.cpp
python/src/triton.cc
python/tests/test_gemm.py
test/Conversion/tritongpu_to_llvm.mlir

1. Improve pipline's comment
2. Decompose insert_slice_async when load vector size is not supported
3. Add a test that could fail our gemm code
Copy my comments here:
There's a knob that may cause performance regression when decomposition has been performed. We should remove this knob once we have thorough analysis on async wait. Currently, we decompose `insert_slice_async` into `load` and `insert_slice` without knowing which `async_wait` is responsible for the `insert_slice_async`. To guarantee correctness, we blindly set the `async_wait` to wait for all async ops.
There are two options to improve this:
1. We can perform a dataflow analysis to find the `async_wait` that is responsible for the `insert_slice_async` in the backend.
4. We can modify the pipeline to perform the decomposition …

[Triton-MLIR][BACKEND] Refactor decompose insert_slice_async

---

.github/workflows/integration-tests.yml
lib/Dialect/TritonGPU/Transforms/Combine.cpp
python/tests/test_gemm.py

This PR
- Fix numWarps>1 hang issue
- add existing test cases in test_gemm.py to CI, and add a common flag `valid_on_Volta` to determine whether the test case should be activated on Volta or just skip.
- Currently, the column-major cases are disabled.
- Add test_core.py and other tests to Volta CI
- the `test_printf.py` failed.

[Triton-MLIR][BACKEND] Refine v100 tests and fix mmav1 numwarps>1 hang issue

---

lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
lib/Conversion/TritonToTritonGPU/TritonToTritonGPU.cpp
lib/Dialect/TritonGPU/Transforms/Combine.cpp
lib/Dialect/TritonGPU/Transforms/Prefetch.cpp
python/tests/test_matmul.py
python/tests/test_vecadd.py
python/triton/compiler.py
python/triton/language/core.py
python/triton/language/semantic.py
python/triton/ops/matmul.py
python/triton/ops/matmul_perf_model.py
python/triton/testing.py

1. Handle induction variable when step is negative
2. Restore async_wait that accidentally deleted
3. Add missing induction variable in prefetch
4. Add device property functions

[Triton-MLIR][BACKEND][FRONTEND] Fix problems with test_matmul

---

.github/workflows/integration-tests.yml
CMakeLists.txt
lib/Conversion/TritonToTritonGPU/TritonToTritonGPU.cpp
python/setup.py

Enable assertions by a new CMake build type `TRITON_REL_BUILD_WITH_ASSERTS`.

[CI] Enable assertions for CI

---

lib/Conversion/TritonGPUToLLVM/DotOpHelpers.h
lib/Dialect/TritonGPU/Transforms/Combine.cpp
test/TritonGPU/combine.mlir

Continue the work https://github.com/openai/triton/pull/990
The `versionMinor` in MmaEncodingAttr holds some states of DotOp's operands in Volta, while such operands will be modified by some patterns, making the states out-of-date.
This PR helps to correct the states.
It adds three new patterns:
1. `CollectMmaToUpdateForVolta` helps to collect and build a map holding the MmaEncodingAttr instances with wrong states and create new correct ones for them,
2. `UpdateMMAVersionMinorForVolta` helps to replace the Ops generating the wrong MmaEncodingAttr instances with new correct ones, currently it supports the following Ops
a. `convert_layout[X -> mma]`
b. `arith.constant SplatAttr : !tensor<mma>`
c. `dot ... : !tensor<mma>`
This PR chooses the mapping way to bypass the IR walk complexity from …

[OPTIMIZER] Update the versionMinor in MMA layout for volta

---

lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.h
lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.h
lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.h
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.h
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.cpp
test/Conversion/tritongpu_to_llvm.mlir

1, add explicit value cache in emitting indices calculation;
2, move the indices calculation emitting logics into ConvertTritonGPUOpToLLVMPatternBase to avoid the redundant build cost by templates. Refer to the discussion in this thread by @LyricZhao : https://triton-lang.slack.com/archives/C042VBSQWNS/p1671336755922969

[Backend] Add value cache in emitting indices calculation and some refinement

---

python/setup.py

This fixes an errors when trying to compile triton on some systems:
If your system has multiple versions of python3 installed, then previous CMake would fail when trying to verify Python3 is installed. Adding the `-DPython3_EXECUTABLE:FILEPATH` argument to CMake invocation fixes this. Note that you can't do this with an environment variable because you need the `:FILEPATH` part for it to work, and this can only be given with a `-D` argument to cmake.

Fixed error when compiling in systems with multiple versions of python installed

---

include/triton/Dialect/Triton/IR/TritonOps.td
lib/Analysis/Alias.cpp
lib/Analysis/Allocation.cpp
test/Analysis/test-alias.mlir
test/Analysis/test-allocation.mlir
test/Analysis/test-membar.mlir

Also add tests for `tt.trans`.

[Backend] Use post-order traversal for liveness numbering

---

python/triton/language/semantic.py

Currently Triton returns tensors with the input types rather than i32 when doing reduce argmax/argmin.

Fix argmin/max output type

---

python/examples/copy_strided.py

fixing example: signature is kwarg in compile

[Example] Fix the compile function in copy_strided.py

---

CMakeLists.txt

It seems that Triton compiled with GCC 8.x used on, for example, CentOS Stream 8, cannot be executed because of the following run-time error.
```sh 
$ lit build/$(ls build)/test
...
...
ImportError: /home/siwasaki/triton/python/triton/_C/libtriton.so: undefined symbol: _ZNKSt10filesystem7__cxx114path11parent_pathEv
```
This is because old GCC runtime library (in my case, GCC 8.x's `libstdc++`) does not contain `libstdc++fs`, according to https://github.com/mgbellemare/Arcade-Learning-Environment/issues/406.  Perhaps Ubuntu18 also uses old GCC (though its EOL is this April), so this might not be a CentOS Stream-specific issue.
This PR fixes the issue by explicitly linking this `libstdc++fs` library.  This PR makes Triton buildable and executable in such …

[Build] Support GCC 8.x to build Triton

---

lib/Target/PTX/PTXTranslation.cpp
python/triton/compiler.py

Identical to PR #1038 but based on `master` instead of `triton-mlir`.
---
Summary:
LLVM 14 supports newer PTX and SM versions than LLVM 11 (the backend prior to the MLIR rewrite). This patch updates `PTXTranslation.cpp`and `compiler.py` to reflect that.
`PTXTranslation.cpp`:
- Makes a distinction between PTX version and Compute Capability
- Max PTX version is 7.5 (unchanged)
- Max Compute Capability is 8.6 (new, previously effectively limited by max PTX version)
- No longer limits the Compute Capability by the PTX version - Prior to this patch the PTX version was used (appended to `sm_`) - This should hopefully allow generation of better code for newer GPUs
`compiler.py`:
- Adds support for CUDA releases which provide PTX versions newer than 7.4
- PTX selection logic refactored to take …

feat: Update PTX/SM support for LLVM14 (PR #1038 redux)

---

python/src/triton.cc
python/test/unit/language/test_core.py

Code snippet from a case in torchbench.
```Python
@triton.jit
def kernel(in_ptr0, out_ptr0, xnumel, rnumel, XBLOCK : tl.constexpr, RBLOCK : tl.constexpr):
xnumel = 2
rnumel = 77
xoffset = tl.program_id(0) * XBLOCK
xindex = xoffset + tl.arange(0, XBLOCK)[:, None]
xmask = xindex < xnumel
rbase = tl.arange(0, RBLOCK)[None, :]
_tmp1 = tl.zeros([XBLOCK, RBLOCK], tl.int64) + -9223372036854775808
```

[BACKEND] Support int64 constant

---

python/test/unit/language/test_core.py
python/triton/compiler.py

Always raise an exception when JITFunction's argument is not on cuda.
For exampe:
`# raise exception`
`_kernel[grid](a, b.cpu())`

Raise an expection when pytorch tensor is not on a cuda device

---

python/test/unit/language/test_core.py
python/triton/language/core.py

To check if a variable is equal to one of many values, combine the values into a tuple and check if the variable is contained in it instead of checking for equality against each of the values. This is faster, less verbose, and more readable.

Fix: replaced comparison operator with in 

---

python/triton/tools/aot.py

The exit or quit functions don't exist at top-level if python is started with the **-S flag**, and will raise an error. Use **sys.exit()** instead.
**sys.exit()** is guaranteed to work, regardless of the interpreter options.

Fix: replaced unsafe exit with sys.exit

---

CMakeLists.txt

In the case when `TRITON_BUILD_PYTHON_MODULE` is set to `OFF`, the `triton` target ends up having no sources, which triggers a CMake configuration error.
Fix this by only generating the target when building with python module support.

Fix build config when not building python module

---

lib/Analysis/CMakeLists.txt

The `TritonAnalysis` target depends on `TritonTableGen` through including `Triton/IR/Dialect.h`, which itself includes `Triton/IR/Dialect.h.inc` generated by `TritonTableGen`.
Without it, the build might fail (seems to be happening inconsistently, due to multithreaded builds) with:
```
Building CXX object
lib/Analysis/CMakeFiles/obj.TritonAnalysis.dir/AxisInfo.cpp.o
In file included from ./include/triton/Analysis/AxisInfo.h:8,
from ./lib/Analysis/AxisInfo.cpp:6:
.include/triton/Dialect/Triton/IR/Dialect.h:12:10: fatal error:
triton/Dialect/Triton/IR/Dialect.h.inc: No such file or directory
12 | #include "triton/Dialect/Triton/IR/Dialect.h.inc"
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
I can reproduce it consistently if I use the "Unix Makefiles" build …

Add dependency to TritonTableGen in TritonAnalysis

---

python/src/triton.cc

The same function is redefined in lines [645-650](https://github.com/openai/triton/blob/master/python/src/triton.cc#L645-L650) and [1174-1179](https://github.com/openai/triton/blob/master/python/src/triton.cc#L1174-L1179), compared these 2 definitions, looks like we should remove the code in lines 645-650.

[BACKEND] Remove duplicate def for create_get_program_id

---

include/triton/Analysis/Allocation.h

Since we need to get the address/reference of each entry, it is not appropriate to use DenseMap here because rehashing on DenseMap will reallocate buckets and change addresses of entries. Unlike DenseMap, associative containers in STL do not change references to existing entries when other entries are inserted or deleted.
https://stackoverflow.com/questions/61771352/will-it-change-the-address-of-a-existed-keys-value-when-inserting-new-keys

[BACKEND] Change DenseMap to std::map in Allocation

---

python/setup.py

Otherwise it fails with
```
File "/scratch/ezyang/work/c/triton/python/setup.py", line 147, in build_extension
"-DLLVM_EXTERNAL_LIT=" + lit_dir,`
TypeError: can only concatenate str (not "NoneType") to str
```
Signed-off-by: Edward Z. Yang <ezyang@meta.com>

Still build even if lit is not installed on user's system

---

python/triton/compiler.py

Makes error reported in https://github.com/pytorch/pytorch/issues/90377 a bit easier to understand

Raise runtime error if C compiler is not found

---

lib/Dialect/TritonGPU/Transforms/Prefetch.cpp

Update prefetch width.
Before this PR: 16
After this PR: 16 (fp16/bf16), 32(int8/fp8), 8 (tf32)
The new prefetch width works better with i8/f8/tf32 tensor cores.

Fix prefetch

---

python/setup.py
python/triton/compiler.py

Define `TRITON_PACKAGE_CUDA_DEPS` to package `ptxas` and `cuda.h` into the wheel package. In that case bundled `cuda.h` will be used if one could not be found in the path.
Also bundled `ptxas` will be used unless one decides to opt out by defining `TRITON_IGNORE_BUNDLED_PTXAS`.

Add ability to bundle CUDA dependencies

---

lib/Conversion/TritonGPUToLLVM/DotOpHelpers.h
lib/Conversion/TritonGPUToLLVM/TypeConverter.h
lib/Dialect/TritonGPU/Transforms/Prefetch.cpp

Use i32 as the storage type for <2xi16> and <4xi8>, as NVPTX inserts extra integer instructions for vector int types.
Performance before this PR: (8192x8192x8192-TN input)
bf16: 222 TFLOPS
i8:     339 TOPS
After this PR:
bf16: 272 TFLOPS
i8:      548 TOPS

Fix bf16 i8 matmul performance

---

include/triton/Analysis/Utility.h
lib/Analysis/Utility.cpp
lib/Dialect/TritonGPU/Transforms/Combine.cpp

`multiRootTopologicalSort` is faster than `mlir::topologicalSort` because it prunes nodes that have been visited before.

[BACKEND] Replace `mlir::topologicalSort` with a custom implementation

---

python/test/unit/language/test_core.py
python/triton/language/semantic.py
python/triton/runtime/autotuner.py
python/triton/runtime/jit.py

It is unnecessary to use a comprehension just to loop over the iterable and create a list/set/dict out of it. Python has a specialized set of tools for this task: the list/set/dict constructors, which are faster and more readable.
for ex :
https://github.com/openai/triton/blob/b5d32896b1f89fc44a82f8df3bb010934c53f4f5/python/triton/language/semantic.py#L505

[FRONTEND] Removed unnecessary comprehension

---

python/triton/language/extern.py
python/triton/language/semantic.py

Using range(len(...)) is not pythonic. 
Python does not have not index-based loops. Instead, it uses collection iterators. Python has a built-in method enumerate which adds a counter to an iterable. Using this, you can access the counter and the value from the iterable at the same time. It is therefore recommended to replace range(len(...)) with enumerate(...).
for ex 
https://github.com/openai/triton/blob/5bcf60a5c07997c018e1c3d1f8808ed283159f53/python/triton/language/extern.py#L68
https://github.com/nishantsikarwar/triton/blob/f62d556fff86299a608cfe9981bf6bac65340f95/python/triton/language/extern.py#L68

[FRONTEND] Replaced range with enumerate calls

---

python/triton/compiler.py

Since the llir IR is a string when it is first generated, it should also be a string when we fetch it from the cache.
The original read_bytes() implementation is causing a pytorch 2.0/inductor unit test failure:
`python3 -bb test/inductor/test_torchinductor.py -v CudaTests.test_elu_cuda`
When the test is run with the -bb flag, attempts to convert a byte array to a string result in an error.

Fix restoration of llir IR from cache to give a string.

---

python/src/triton.cc

Currently, multi-threading is only allowed during PTX->cubin compilation, but not for LLVM->PTX or TTIR->LLVM conversion.

[BUILD] Allow multi-threading during compilation

---

include/triton/Dialect/Triton/IR/TritonOps.td

The order of the input encoding is permuted to form the output encoding.
For example:
```
#A_SHARED = #triton_gpu.shared<{vec = 2, perPhase = 2, maxPhase = 4, order = [1, 0]}>
#A_SHARED_T = #triton_gpu.shared<{vec = 2, perPhase = 2, maxPhase = 4, order = [0, 1]}>
%b = tt.trans %tensor : (tensor<16x32xf16, #A_SHARED>) -> tensor<32x16xf16, #A_SHARED_T>
```

[BACKEND] Hotfix to remove SameOperandsAndResultEncoding for the trans operation

---

python/triton/language/semantic.py

Otherwise, the construction of the exception crashes during string concatenation.

[FRONTEND] Fix error message when atomics are not supported for a given dtype

---

python/test/unit/language/test_core.py

Current `test_core.py` try to find `libdevice.bc` in common system paths, however, it failed on my machine because my CUDA is not installed in `/usr/local/`. We have another builtin `libdevice.bc` in `triton.language.libdevice`. This PR links to this one to avoid errors.

Change `libdevice.bc` Path in Core Tests

---

python/setup.py

Prevents excessive hyphens from causing build errors on non-Windows machines.

[Build] Prevent excessive hyphens from causing build errors.

---

python/triton/language/semantic.py

Check dot operands at early stage before lowering so that users can understand the errors.
We cannot enforce the `SameOperandsElementType` checks in the IR definition because *C* can have a different element type than *A* or *B*.
Example:
```Python
def _kernel(a, b, c, d, e, i0_shape: tl.constexpr, i1_shape: tl.constexpr, i2_shape: tl.constexpr, i3_shape: tl.constexpr, i0_BLOCK: tl.constexpr, i2_BLOCK: tl.constexpr, i1_BLOCK: tl.constexpr, i3_BLOCK: tl.constexpr):
i0 = tl.program_id(0)
d_ptrs = ((((d + ((i0 * i0_BLOCK) * i2_shape)) + (0 * i2_BLOCK)) + (tl.arange(0, i0_BLOCK) * i2_shape)[:, None]) + tl.arange(0, i2_BLOCK)[None, :])
i3 = 0
_shared0 = tl.zeros([i0_BLOCK, i3_BLOCK], tl.float32)
for i2 in range((i2_shape // i2_BLOCK)):
_shared1 = tl.zeros([i0_BLOCK, i2_BLOCK], tl.float32)
for …
```

[FRONTEND] Check if the data types of *A* and *B* in the dot op have the same data type

---

python/test/unit/language/test_core.py
python/triton/language/core.py
python/triton/language/semantic.py

Previously it was always using logical right shift, which gives wrong results for signed inputs.

[FRONTEND] For __rshift__ operator, use arithmetic right shift if dtype is a signed int.

---

python/setup.py

When the user specifies third-party packages using system env like `PYBIND11_SYSPATH`,  the `test_file_path` should be set after `package_dir` is updated.
This happens when the user wants to use custom pybind11 or llvm by setting system env like:
```Bash
$export PYBIND11_SYSPATH=.../python3.10/site-packages/pybind11/
$export LLVM_SYSPATH=.../llvm/build/install/
$cd triton/python
$python setup.py develop
```

[FRONTEND] Fix bug when the `_SYSPATH` is set.

---

python/setup.py

`package_data` is no longer referenced from anywhere.
Use `third_party/**/*` wildcard to package contents of subfolders

Remove unused global var

---

lib/Analysis/Membar.cpp
lib/Target/LLVMIR/LLVMIRTranslation.cpp

If Triton is shipped as shared library inside python package, search for `libdevice.10.bc` relative to this library installation path: Triton package installation looks as follows
```
triton/
_C/libtriton.so
third_party/cuda/lib/libdevice.10.bc
```
Test plan:
```sh
CXX=g++-9 pip install git+https://github.com/malfet/triton@5a0fe18751bc15c7035916de55e0892e63c3db77#subdirectory=python
```
And run following:
```python
import torch
def foo(x: torch.Tensor) -> torch.Tensor:
return torch.sin(x) + torch.cos(x)
if __name__=="__main__":
x = torch.rand(3, 3, device="cuda")
x_eager = foo(x)
x_pt2 = torch.compile(foo)(x)
print(torch.allclose(x_eager, x_pt2))
```

Search for `libdevice` relative to shared library

---

python/triton/compiler.py

This will removed unused private functions after we've inlined everything. That's important because TritonToTritonGPU doesn't know how to lower tensor arguments.

[FRONTEND] Now using symbol-dce in `optimize_triton_ir`

---

python/test/unit/language/test_core.py
python/triton/compiler.py

no longer raise exception when the pointer is on "cpu" but also accessible from within kernels (e.g., pinned memory)

[FRONTEND] fixed pinned memory exception behavior

---

python/triton/ops/matmul.py
python/tutorials/03-matrix-multiplication.py

For the new MLIR backend, this appears to increase matmul perf significantly in many cases.
The TTIR changes:
<details closed>
<summary>Old</summary>
<br>
```
module {
func public @matmul_kernel_0d1d2d3d4d5d6d7c8d9c10d11c(%arg0: !tt.ptr<f16> {tt.divisibility = 16 : i32}, %arg1: !tt.ptr<f16> {tt.divisibility = 16 : i32}, %arg2: !tt.ptr<f16> {tt.divisibility = 16 : i32}, %arg3: i32 {tt.divisibility = 16 : i32}, %arg4: i32 {tt.divisibility = 16 : i32}, %arg5: i32 {tt.divisibility = 16 : i32}, %arg6: i32 {tt.divisibility = 16 : i32}, %arg7: i32 {tt.divisibility = 16 : i32}, %arg8: i32 {tt.divisibility = 16 : i32}) {
%c32_i32 = arith.constant 32 : i32
%cst = arith.constant dense<32> : tensor<128x32xi32>
%c32 = arith.constant 32 : index
%c0 = arith.constant 0 : index
%c128_i32 = arith.constant …
```

Changed for loop to iterate by 1 in matmuls

---

python/triton/compiler.py

creating dynamically a module named `launcher` may conflict with other modules named the same in the user's environment.

[FRONTEND] launcher module is now renamed from `launcher` to `__triton_launcher`

---

lib/Conversion/TritonGPUToLLVM/DotOpHelpers.cpp

While doing it incorrectly works at the moment, this will cause a validation error once we rebase Triton closer to LLVM head, since validation for some LLVM Dialect ops got stricter.
Specifically, if we remove the shared memory space attribute, a subsequent bitcast tries to add it back, which is illegal.

Correctly propagate address spaces through GEP

---

python/triton/runtime/autotuner.py

Minor bug: AutoTuner currently throws the following error when certain configs go OutOfResources (e.g. the matmul example when testing on GPUs with less shared memory). 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-7-e8822053f6d7>](https://localhost:8080/#) in <module>
2 a = torch.randn((512, 512), device='cuda', dtype=torch.float16)
3 b = torch.randn((512, 512), device='cuda', dtype=torch.float16)
----> 4 triton_output = matmul(a, b)
5 torch_output = torch.matmul(a, b)
6 print(f"triton_output={triton_output}")
1 frames
[/content/triton/python/triton/runtime/autotuner.py](https://localhost:8080/#) in run(self, *args, **kwargs)
79                 bench_end = …
```

Fix AutoTuner error when OutOfResources

---

CMakeLists.txt
python/setup.py

Make cmake happier, it doesn't like multiple target_link_library definitions for the same name.
Use find_package instead on Windows for dlfcn-win32. 
Set LLVM_SYS_PATH on Windows for python setup.
Debug build almost working, AlwaysCreate error thrown still.

Windows and cmake compatibility.

---

python/triton/language/semantic.py

This pull request addresses a crash that occurs when casting to a tl.constexpr type in the frontend. 
More info and repro code available in: https://github.com/openai/triton/issues/1221

[Frontend] fix crash on cast when dest is constexpr

---

lib/Dialect/TritonGPU/Transforms/Combine.cpp
lib/Target/PTX/PTXTranslation.cpp
python/src/triton.cc

To support sm_89 without warnings
Confirmed with @ptrblck that it works. 
This reverts commit 3e8d83b7cc11b1d26e7f1fb7f0022d03aa2377ae.

Revert "Minor fix to support sm_90 (#1125)"

---

python/triton/language/core.py
python/triton/language/semantic.py

Fix issue https://github.com/openai/triton/issues/244
Check `end` is greater than `start`.
Check if the range can fit in `int32`.
Check the number of elements less than or equal to `TRITON_MAX_TENSOR_NUMEL = 131072`.

[FRONTEND] Add error messages for arange

---

python/triton/compiler.py

Per issue https://github.com/openai/triton/issues/1228.  I believe we are potentially exposed when a Triton executor (Pytorch for example) links in two or more `triton_.so` shared objects and each has a stub for `_launch`.
This fix ensures the `_launch` function is tied locally to the calling `__triton_launcher` and can't be misused by another library.

Ensure __triton_launcher calls right _launch.

---

lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h

The function calculates the swizzled address to **store** (not load), so we should use `outOrder` instead of `inOrder`. Current tests do not cover this case, but at NVIDIA, we have a case related to `sm_90` that could trigger. Already discussed in the Slack channel with @Jokeren.

[Backend] Fix a bug in swizzling store

---

CMakeLists.txt

This is to solve https://github.com/openai/triton/issues/1236
This commit hides the symbols of the shared libraries for `libtriton.so`, so that when other object link against `libtriton.so`, it won't have confilct.
This PR didn't handle the case in MacOS, but there is a possible way to use `exported_symbols_lists` to export a whitelist symbols as [mxnet/CMakeLists.txt](https://github.com/apache/mxnet/blob/b84609d3fc73d20929c114eab95faaa56e6c5ede/CMakeLists.txt#L740). I put here in case anyone needs it.

[Build] Strip the static libraries symbol from the triton shared library

---

python/examples/copy_strided.py

Small cleaning of an example calling an old API to display generated IR

fix: remove unnecessary argument to example

---

python/triton/compiler.py

Should fix https://github.com/pytorch/pytorch/issues/95523 
cc @ngimel

Fix cuda dir path to point to the cuda.h shipped with third_party/cuda/

---

lib/Analysis/AxisInfo.cpp

Feels very wrong, and probably not the right way to do this. But otherwise `scf.if` doesn't get initialized since the merge to llvm-head. Suggestions are welcome 😅

[ANALYSIS] initializing operand axisinfo state (if necessary) before visiting operation

---

python/triton/language/semantic.py

For reduction ops, `Max/Min/Sum`, we have a param axis. Ideally, it should be in the range of (-rank,rank) where rank = len(shape(tensor)).
For now, Triton didn't check it and just compile into a tl.Tensor with probaly error axis.  If axis is not correct, triton will be crashed in line `pm.run(mod)` within function `optimize_ttgir`. It's unfriendly for users to know where is error from.
With this check, we can hanle negtive axis, and checked if it's valid.

[FRONTEND] Add check for axis of reduction op

---

python/triton/compiler.py

We are benchmarking the performance of triton kernels generated by torch inductor. Some metrics like register usage and register spill are very helpful. Those information are already available in triton but not exposed.
Add this tiny PR to expose them thru CompiledKernel's attributes.
Let me know if I should have created an issue first :)
cc @ngimel  @Chillee

expose the register usage and spill information thru CompiledKernel

---

python/test/unit/language/test_core.py
python/triton/language/semantic.py

Commonly used in atomic_rmw ops

[FRONTEND] Fix cast when both `src_ty` and `dst_ty` are of block_type

---

lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
python/test/unit/language/test_core.py

For some reasons, we still have arith::SelectOp before the ConvertTritonGPUToLLVM pass. So we will need the conversion from arith::SelectOp to LLVM::SelectOp.
For now, we can't rely on MLIR's ArithToLLVM pattern because MLIR's patterns don't know what to do with Triton types (e.g., Triton pointer types).

Add arith::SelectOp => LLVM::SelectOp conversion

---

python/triton/runtime/autotuner.py

Fixed several typos in `python/triton/runtime/autotuner.py`

[DOC] Fix typos in comments

---

include/triton/Conversion/Passes.td
lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp

The dialect of created ops needs to be part of dependent dialects.

[BACKEND] Fix `triton-convert-arith-to-index`.

---

CMakeLists.txt

I observed that when compiling with gcc8, stdc++fs linker flag isn't
passed to enough targets.  I couldn't figure out the correct target
to add the linker flag to, so I'm just mashing it everywhere.
Signed-off-by: Edward Z. Yang <ezyang@meta.com>

Mash stdc++fs into more targets

---

python/test/unit/language/test_core.py
python/triton/compiler.py

This is cherry-picked from #1305
If you call a `JITFunction` twice in the same kernel, first with `int32` then with `uint32`, the second call will treat the unsigned value as signed. This passes through MLIR without error because MLIR uses the same types for both, but different operation calls will be generated so you may silently get the wrong result.

Mangle signed and unsigned integer types differently

---

python/triton/runtime/jit.py

Fixed `JITFunction.__init__` to mark args as constexpr only when the annotation is actually `tl.constexpr`, rather than treating any annotated arg as constexpr.

`JITFunction`: infer constexpr arg only if annotated as such

---

python/triton/ops/blocksparse/matmul.py

This PR applies a minor patch that removes unnecessary masks in `_dsd_kernel()`.
`offs_bn` is defined as follows and not updated after that.
```py
offs_bn = pid_m * TILE_N + tl.arange(0, TILE_N)
offs_bn = tl.max_contiguous(tl.multiple_of(offs_bn % DS0, TILE_N), TILE_N)
```
Because `offs_bn = offs_bn % DS0`, this mask is always `True`.
```py
b = tl.load(pb, mask=offs_bn[None, :] < DS0)
```
This PR removes this mask (as well as explicit `mask=True`).

[ops/blocksparse] remove unnecessary mask

---

lib/Analysis/AxisInfo.cpp

Before this PR, loops' induction variables' (IV) alignment info is lost.
For example:
```
for n in range(0, K, BLOCK):
x = base + n
^--  Triton doesn't know n is always a multiple of BLOCK
```
This PR fixes this.

Infer the alignment info of loops' induction variables

---

python/triton/compiler.py

This addition allows explanatory messages upon assertion failures:
```python
@triton.jit
def my_single_block_kernel(
matrix_extent: tl.constexpr,
block_size: tl.constexpr,      # must be >= extent (single block)
matrix: Tensor,
...
):
tl.static_assert(matrix_extent <= block_size, 
f"`matrix_extent` should not be more than the block size ({block_size}), but is {matrix_extent}")
```
Yielding, when called incorrectly:
```
AssertionError: `matrix_extent` should not be more than the block size (32), but is 57
```

enhancement: support f-strings in compiler with `constexpr` conversion

---

include/triton/Dialect/Triton/IR/TritonOps.td
lib/Dialect/Triton/IR/Ops.cpp
test/Triton/combine.mlir

These eliminate no-op reshapes, and simplify some combinations of view ops into a single view. e.g. viewing a splat becomes a single splat.

Add canonicalize/fold for ExpandDimsOp, ViewOp and BroadcastOp

---

python/test/unit/runtime/test_cache.py
python/test/unit/runtime/test_launch.py
python/triton/compiler.py

Fixes a bug that causes Triton to leak 32 bytes on every kernel
invocation.
Also solves https://github.com/pytorch/pytorch/issues/96937
(cherry picked from commit 1d2871d0d1e68bfc005580ad9dfa4de1aa6b975e)

[RUNTIME] Fix memory leak in (#1358)

---

lib/Dialect/TritonGPU/IR/Dialect.cpp

We can do that because `cat` reorders elements anyways

[OPTIMIZER] Canonicalize `convert_layout(cat: #layout1) -> #layout2` as `cat: #layout2`

---

lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
python/test/unit/language/test_core.py

after offset shifting, exponent compensate should not be forgotten
also add back some comments from `legacy_backend`

[BACKEND] Fix wrong conversion from float8e4m3 <> float16

---

lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
python/test/unit/language/test_core.py

exponent compensate should be 0x3800(112) instead of 0x3000(96)
also add a mantissa bit for float16 conversion to round to nearest float8e5m2

[BACKEND] Fix wrong conversion from float8e5m2 <> bfloat16

---

.pre-commit-config.yaml

`pre-commit run --all-files` currently produces a diff of 2400 lines making `pre-commit` unusable. This seems to be because it runs on the entire codebase, not just the files listed in the arguments e.g. it shouldn't run on `docs/conf.py` or `test/lit.cfg.py` but does.

Fix pre-commit to only run on intended files

---

docs/python-api/triton.language.rst
lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
python/src/triton.cc
python/test/unit/language/test_core.py
python/triton/language/core.py
python/triton/language/semantic.py

This generates identical PTX for floating point, but for integer types the resulting PTX is much better. For example `tl.abs` for int16 currently generates
```mlir
cvt.s32.s16 %r1, %rs2;
neg.s16     %rs4, %rs2;
setp.lt.s32 %p4, %r1, 0;
selp.b16    %rs3, %rs4, %rs2, %p4;
```
After, it becomes a single `abs.s16` instruction.
This also improves LLVM's ability to optimize floats. e.g. `abs(t) * abs(t)` is optimized to `t * t` now which didn't happen before.

[FRONTEND][BACKEND] Lower `tl.abs` to `math::Abs{I,F}Op`

---

.github/workflows/integration-tests.yml

While not currently a vulnerability, using this option can introduce risks of supply chain attacks, where an attacker adds a malicious package into the default public repository with the same name as one that you are installing. The best practice is to instead use --index-url when a package is not available in the default repo, so I've updated to use this option instead.
For full disclosure, this is currently causing Microsoft's internal security checks to fail when building triton (which is why I care about this theoretical issue/best practice).

Avoid using EXTRA_INDEX_URL in pip install

---

include/triton/Conversion/TritonGPUToLLVM/AsmFormat.h
include/triton/Conversion/TritonGPUToLLVM/GCNAsmFormat.h

This PR address the remaing issues from #1312. It does the following
*  LLVM String Join
* adds comment to GCNBuilder Class

[ROCM] Enable ROCM Backend #1.5: Address Remaining Comments from #1312

---

python/test/unit/runtime/test_launch.py
python/triton/runtime/jit.py

One of the possible optimizations for kernel launch overhead. Basically, we are trying to avoid having to run `hasattr` and `isinstance` for each argument, by adding typehints to the kernel definition. Also, added a unit test to regression to make sure we keep the launch overhead within an expected range.

[FRONTEND] Added typehints support to speedup triton kernel launch

---

python/triton/runtime/jit.py

For a kernel like this:
```
import triton, torch
def my_special_activation(x): return x * 5
@triton.jit
def _kernel(x):
my_special_activation(x)
_kernel[(1,)](torch.zeros(1))
```
Error message before:
```
File "/usr/lib/python3.8/ast.py", line 371, in visit
return visitor(node)
File "/usr/local/lib/python3.8/dist-packages/triton/runtime/jit.py", line 63, in visit_Call
assert isinstance(func, JITFunction)
AssertionError
```
Error message after:
```
File "/usr/lib/python3.8/ast.py", line 371, in visit
return visitor(node)
File "/usr/local/lib/python3.8/dist-packages/triton/runtime/jit.py", line 62, in visit_Call
assert isinstance(func, JITFunction), f"Function {func.__name__} is being called from a Triton function but is not a Triton function itself. Decorate it with @triton.jit to fix …
```

More friendly error message when non-Triton function is called from Triton function

---

python/triton/compiler.py

This fixes the problem indicated in #1443

`CodeGenerator.statically_implemented_functions`: fixed incorrect hacky initialization

---

python/setup.py

On some machines, the amount of available RAM might not be enough to compile Triton with `2 * num_cpus` parallelism. For example, CircleCI's `large` instance can't handle Triton compilation as is due to insufficient memory.
Instead, I propose to take PyTorch's approach where we can define a [`MAX_JOBS` env var](https://github.com/pytorch/pytorch/blob/0e4ddc2b40e8f8172bea66dc3bce50ab369eaa54/tools/setup_helpers/cmake.py#L366-L368) that gives the user the possibility to reduce (or increase) the parallelism during compilation.

Add option to specify number of compilation threads during Triton compilation

---

python/triton/runtime/__init__.py

The Autotuner is a handy utility. By allowing external access to the Autotuner, users can overwrite some functions (e.g., `run`) to load/store best configurations, initialize tensors based on configuration values, and change benchmarking standard (e.g., based on bytes instead of time).

[FRONTEND] Expose Autotuner to users

---

python/test/unit/language/test_core.py
python/triton/language/core.py
python/triton/language/semantic.py
python/triton/ops/flash_attention.py

Maybe we do want to support `exp` for fp16 and bf16 as an exception? Since there is a hardware intrinsic on NVIDIA GPUs.
fp16 requires >= sm_75
bf16 requires >= sm_90

[FRONTEND] Data type specification for math functions

---

python/triton/compiler/compiler.py
python/triton/compiler/make_launcher.py
python/triton/runtime/cache.py
python/triton/runtime/driver/cuda.py
python/triton/runtime/driver/hip.py

The changes here come with a few separate bits:
- Allow replacing the cache manager with an ENV variable to make it pluggable
- Make the `make_path` api private since its leaking some internal bits of the cache and allowing file access. Use a get operation instead.
- For the `compile` operation we have a several files part of a single compile pipeline that are small, this can be not the most performant with remote caches. Also some operations like `_triton.get_shared_memory_size` only work when everything is cached or none(or some key ones aren't). They segfault otherwise. So grouping these as an entity avoids that.

Allow cache manager to be overridden, and tweak apis to easier work with remote caches

---

include/triton/Dialect/TritonGPU/IR/Dialect.h
lib/Analysis/Allocation.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
lib/Dialect/TritonGPU/Transforms/Utility.h

https://mlir.llvm.org/docs/DefiningDialects/AttributesAndTypes/
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#f16-for-in-parameters-pass-cheaply-copied-types-by-value-and-others-by-reference-to-const
```
The C++ Attribute and Type classes in MLIR (like Ops, and many other things) are value-typed. 
This means that instances of Attribute or Type are passed around by-value, 
as opposed to by-pointer or by-reference. 
The Attribute and Type classes act as wrappers around internal storage objects that are uniqued within an instance of an MLIRContext.
```

[Refine] remove const ref of mlir::Attribute

---

python/triton/ops/blocksparse/matmul.py

When the language model grows really large, the axis 1 of the origin grid shape (`c.shape[1]`, correspond to the number of nonzero elements in the layout) will be larger than 65536, exceeds the cuda limit and results in `[CUDA]: invalid argument`.
This PR is moving the axis 1 of the origin grid to axis 0, as the limit for axis 0 is 2^31 - 1.
Thank you for your time on reviewing this PR :)

[ops/blocksparse] Fix grid shape for large lm

---

README.md

This make it easier for those working from tarball releases or clones to know where the upstream project is located.

Include link to github project in README

---

bin/CMakeLists.txt
bin/RegisterTritonDialects.h
bin/triton-opt.cpp
bin/triton-reduce.cpp

[`mlir-reduce`](https://mlir.llvm.org/docs/Tools/mlir-reduce/) is a tool to reduce the complexity of bug reproducers written in mlir. Similar to `triton-opt`, `triton` needs to have its own version with the dialects registered properly for it to work.

Add triton version of mlir-reduce

---

lib/Dialect/TritonGPU/Transforms/Pipeline.cpp

This triggers an assertion introduced in https://reviews.llvm.org/D147883

Fix invalid access of op result

---

python/triton/compiler/compiler.py

When running python 3.8, I've found that process creation gets slower over time (e.g. after creating a CUDA context, it can take 50-300ms per subprocess.run), and we do one of these calls to `ptxas --version` for every kernel, so a model with thousands of kernels can end up spending substantial time just calling ptxas redundantly.

Cache path to ptxas

---

python/triton/runtime/jit.py

Works with `__future__` annotations and also avoids having to import torch just for the sake of type annotations.

[FRONTEND] Now using strings for annotations

---

lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
python/test/unit/language/test_core.py
python/triton/language/core.py

`argmin`/`argmax` is currently only tested in 1d and when we enable the tests for 2d it reveals a few bugs.

Enable tests for argmin/max and fix some bugs

---

python/triton/language/core.py

Some math ops accept inputs of different types (e.g., tl.math.jn).
We don't want to cast the scalar types of input operands of those math ops.

Fix type checking in extern_elementwise

---

include/triton/Dialect/TritonGPU/IR/Dialect.h
include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandFMA.cpp
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMMAv1.cpp
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMMAv2.cpp
lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/MMAv2.cpp
lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
lib/Conversion/TritonGPUToLLVM/TypeConverter.cpp
lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp

This is a prerequisite for updating the semantics of SliceEncodingAttr.

[BACKEND] Decomposed getElemsPerThread to return a vector of the per-dim elements per thread

---

python/triton/compiler/compiler.py

Change the usage of LRU cache decorator from @functools.lru_cache to @functools.lru_cache().
The former raises an error TypeError('Expected maxsize to be an integer or None' for Python 3.7 or older.

Make lru_cache compatible for Python 3.7 or older

---

.github/workflows/integration-tests.yml
python/setup.py

Fixes #1545
`build_temp` is a temporary directory which `distutils` used to keep in the `./build` directory, but when `pyproject.toml` is present `pip` now puts it in `/tmp` and removes it at the end of the build.
Instead, this creates a new permanent directory like `python/build/cmake.linux_x86_64-cpython-3.8` (the old name but with cmake instead of temp).
While I was looking at the verbose pip output, I also noticed a bunch of warnings like
```
Python recognizes 'triton/runtime.backends' as an importable package,
but it is not listed in the `packages` configuration of setuptools.
'triton/runtime.backends' has been automatically added to the distribution only
because it may contain data files, but this behavior is likely to change
in future versions of setuptools (and therefore is …
```

[BUILD] Use a persistent directory for cmake

---

python/tutorials/03-matrix-multiplication.py

In matmul tuto, one of the config in autotune doesn't work on A100 (use too much resources).
If we comment every config but:
```python
triton.Config({'BLOCK_SIZE_M': 128, 'BLOCK_SIZE_N': 256, 'BLOCK_SIZE_K': 64, 'GROUP_SIZE_M': 8}, num_stages=4, num_warps=4),
```
It leads to on A100:
```python
...
raise OutOfResources(self.shared, max_shared, "shared memory")
triton.runtime.autotuner.OutOfResources: out of resource: shared memory, Required: 196608, Hardware limit: 166912. Reducing block sizes or `num_stages` may help.
```
reducing num stages to 3 works but is very slow.
Best param for this block size seems to be stage=3, warps=8

fix: change num warps / stages in matmul tuto

---

python/triton/runtime/cache.py

We have had complaints/issues randomly where a zombie python process is holding this lock. We don't need it since renames are atomic on posix. So refactor this to make temp files unique and then use replace (https://docs.python.org/3/library/os.html#os.replace )

Don't hold a file lock

---

lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
python/triton/language/semantic.py

Related to #1271 . I am currently working on adding support for Pre-volta GPUs in Triton.

Do not run AccelerateMatmul on pre-Volta GPUs

---

python/test/unit/language/test_core.py
python/triton/language/core.py
python/triton/language/math.py
python/triton/tools/build_extern.py

The current main would fail on `math.scalbn` because we implicitly cast the first argument from `int32` to `float32`, while the function only accepts `int32` as the first argument and `float32` as the second argument.
So we update the type matching logic as follows:
1. Check if there's a type tuple that matches the types of the input arguments
2. If yes, we don't allow arithmetic check.
3. If not, we will do arithmetic check to implicitly cast types among arguments.
4. If we still don't find a corresponding function that accepts the casted types, throwing an error.

[FRONTEND] Refine arithmetic checks and corresponding tests for extern_elementwise 

---

python/test/unit/runtime/test_cache.py

To avoid puzzling segment fault problems caused by multiprocessing, this PR:
- Uses "spawn" instead of "fork".
- Define the `instance_descriptor` namedtuple globally.
- Make the `kernel_sub` JITFunction defined by the child process only.

[TEST] Fix test cache

---

python/triton/compiler/compiler.py

Closes https://github.com/openai/triton/issues/1556 https://github.com/openai/triton/issues/1512
The current hash used for caching the cubin does not include the architecture. This leads to the following error when compiling against one arch and running against another (with no code changes to trigger a recompilation).
```
RuntimeError: Triton Error [CUDA]: device kernel image is invalid
```
Was not sure what unit tests would be appropriate here (if any)

add architecture to hash to avoid invalid image on cubin load

---

python/test/unit/language/test_core.py
python/triton/compiler/code_generator.py

If `node.func` is an `ast.Attribute`, it won't cause an early return. (Not sure if I interpret it correctly)
https://github.com/openai/triton/issues/1591

[FRONTEND] Fix calling local variables’ attribute functions in the if statement

---

python/src/triton.cc

Formatting of the diff is not the best. I only indented the whole function, moved the creation of the py::bytes and the return out of the scope and declared and assigned the cubin variable appropriately. Everything else is unchanged.
Today it triggers the following error on CPython debug build:
```
Fatal Python error: _PyMem_DebugMalloc: Python memory allocator called without holding the GIL
Python runtime state: initialized
```

[RUNTIME] Ensure we hold the GIL before calling into CPython API in cubin binding

---

python/triton/__init__.py
python/triton/compiler/compiler.py
python/triton/language/semantic.py

make torch optional to fix circular dependency issue

fix: make torch optional

---

lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
test/Conversion/tritongpu_to_llvm.mlir

[BACKEND] Updated predicate for atomic ops

[BACKEND] Updated predicate for atomic ops

---

python/setup.py

circular dependency is causing troubles now that our interpreter depends on torch 2.0 ...

[SETUP] Removing `torch` as a test dependency

---

python/triton/runtime/autotuner.py

Hi
https://triton-lang.org/main/python-api/generated/triton.autotune.html
The format looks strange on the official documentation pages:
I guess that is not what you expected. Add lines in docstrings will fix the docs:

fix docstrings for sphinx docs

---

.github/workflows/wheels.yml

Ideally you would also build source distributions so that it is in principle possible to build `triton` on other platforms, but building `musllinux` wheels would at least help with openai/whisper#1328.
I suspect you will also get people showing up at some point asking for `aarch64` wheels as well. It might be worth taking a look at the [`cibuildwheel` output matrix](https://cibuildwheel.readthedocs.io/en/stable/#what-does-it-do) to see what you are comfortable with shipping (particularly if you aren't shipping source distributions).

Build wheels for musllinux

---

python/test/unit/language/assert_helper.py
python/triton/language/semantic.py

This sometimes happens in TorchInductor. See https://github.com/pytorch/pytorch/pull/100880. 
More generally, it's useful to be able to write `tl.device_assert(False, msg)`.

Add support for scalar conditions in `device_assert`

---

python/triton/compiler/code_generator.py

`noinline` can be None, False, or True, so we have to check the callee in the first two cases.

[FRONTEND] Hotfix for `contains_return_op`

---

python/test/unit/runtime/test_cache.py
python/test/unit/runtime/test_subproc.py
python/triton/language/semantic.py

This breaks multiprocess compilation

don't call set_device in tl.dot

---

lib/Analysis/CMakeLists.txt
lib/Conversion/TritonToTritonGPU/CMakeLists.txt
lib/Dialect/Triton/IR/CMakeLists.txt
lib/Dialect/Triton/Transforms/CMakeLists.txt
lib/Dialect/TritonGPU/IR/CMakeLists.txt
lib/Dialect/TritonGPU/Transforms/CMakeLists.txt
lib/Target/LLVMIR/CMakeLists.txt
test/lib/Analysis/CMakeLists.txt
unittest/Analysis/CMakeLists.txt

These were currently missing, though building *with static linking* would still work since only the final binaries need all referenced symbols to be present in that case. These dependencies are required to produce self-contained dynamic libraries though.
My way of finding these dependencies has been rather manual: build with BUILD_SHARED_LIBS=ON (which requires to use an LLVM distribution that was built with the same flag, as well as some temporary changes to make the default visibility of symbols public) and then check with `ldd -r` if all symbols can be resolved. Concretely, I used this snippet:
find . -name "*.so.17git" | \
while read line
do
echo; echo; echo $line
LD_LIBRARY_PATH=$(find . -name "*.so.17git" | xargs dirname
| xargs realpath | tr "\n" :)$LD_LIBRARY_PATH \
ldd -r $line | …

Add missing CMake link-time dependencies.

---

include/triton/Analysis/Utility.h
include/triton/Dialect/TritonGPU/IR/Dialect.h
lib/Analysis/Allocation.cpp
lib/Analysis/Utility.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/IR/Traits.cpp
lib/Dialect/TritonGPU/Transforms/Prefetch.cpp
lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp

This breaks a cyclic dependency between TritonAnalysis and TritonGPUIR (see #1649).

Move isSharedEncoding to TritonGPUIR.

---

python/triton/runtime/jit.py

Triton runtime currently relies on KeyError to check whether a kernel has been compiled. This results in somewhat confusing backtraces when running the kernel crashes, as the stack traces includes not only the actual crash, but also the stack trace for the original KeyError which was caught.

[NFC] Do not use exceptions do guide control flow in compilation runtime

---

python/triton/compiler/code_generator.py

As stands if you have a for loop with bounds that are not ints, it will fail with the inscrutable error `'dtype' object has no attribute 'int_bitwidth'`. This is confusing. Instead, we can assert for loop lower and upper bounds be ints, so we can get a much nicer error: `TypeError('For loop bounds and step must all be ints, are (int32, fp32, int32)')`.
Old error traceback:
```
File "/root/triton/python/triton/compiler/code_generator.py", line 1033, in ast_to_ttir
generator.visit(fn.parse())
File "/root/triton/python/triton/compiler/code_generator.py", line 933, in visit
return super().visit(node)
File "/usr/lib/python3.8/ast.py", line 371, in visit
return visitor(node)
File "/root/triton/python/triton/compiler/code_generator.py", line 227, in …
```

Assert that for loop bounds must be ints

---

include/triton/Dialect/Triton/IR/TritonOps.td
lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
lib/Dialect/Triton/IR/Dialect.cpp
lib/Dialect/Triton/IR/Ops.cpp
lib/Dialect/Triton/Transforms/Combine.cpp
lib/Dialect/Triton/Transforms/RewriteTensorPointer.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
python/setup.py

This depends on a [pending LLVM release](https://github.com/ptillet/triton-llvm-releases/pull/10).
* Implement setCalleeFromCallable in CallOp.
* Cast type to ShapedType for various getters.
* Improve TritonDialect::materializeConstant due to breaking change in constructor of arith::ConstantOp.
* Add OpaqueProperties argument in inferReturnTypes.

Update LLVM to 17.0.0 (c5dede880d17) and port changes.

---

lib/Dialect/TritonGPU/Transforms/Utility.cpp
python/test/unit/language/test_core.py
python/triton/language/semantic.py
python/triton/runtime/jit.py

`bool` is a subclass of `int`, so `isinstance(bool_var, int) == True`, and a `bool` constant will be converted to an `int` constant.
In triton specifically, if a bool var is treated as an integer, it prevents us using the `logical_and` operator which requires both operands have the same bit length. 
> Cannot bitcast data-type of size 32 to data-type of size 1
By differentiating int and bool, it allows us to make the syntax more close to native python. We can now use `if bool_var and condition` to check the truthiness, and `if bool_var is True` to check identity.

[FRONTEND] Differentiate between bool and int in the frontend

---

include/triton/Dialect/Triton/IR/TritonOps.td
test/Conversion/triton_ops.mlir

Ideally the MLIR generator should detect the ambiguity and error out.
Fixes #1683

[FRONTEND] Fix tt.print printer format

---

include/triton/Dialect/TritonGPU/IR/TritonGPUDialect.td
lib/Analysis/AxisInfo.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
lib/Dialect/TritonGPU/Transforms/Pipeline.cpp
lib/Target/LLVMIR/LLVMIRTranslation.cpp

Also try to switch APIs access to the new upstream APIs that separate explicitly the access to "discardable" and "inherent" attributes (the latter being stored in properties now).
Generic accessors like `getAttr()` `setAttr()` `setAttrs()` are much more expensive and to be avoided.

Switch the TritonGPU dialect to use MLIR Properties (NFC)

---

python/test/unit/language/assert_helper.py
python/test/unit/language/test_subprocess.py
python/test/unit/runtime/test_cache.py
python/triton/compiler/code_generator.py
python/triton/runtime/jit.py

- If `TRITON_DEBUG=True`, all triton functions will be compiled in the debug mode.
- Otherwise, a triton function `f`'s debug flag is either `True`, `False` or `None` (default).
- If `True`, `f` is compiled in the debug mode.
- If `False`, `f` is compiled in the normal mode.
- If `None`, `f` is compiled based on its caller's debug flag. The root (kernel) function's debug flag can also be set through the `compile` function.
cc @ngimel , @Chillee

[FRONTEND] Correct the debug syntax

---

lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp

Otherwise it will trigger errors using llvm compiled with assert enabled.

[BACKEND] Don't erase an op that has been replaced

---

CMakeLists.txt
python/src/triton.cc

In addition to printing Triton module to string, and an option to print it in bytecode format (https://mlir.llvm.org/docs/BytecodeFormat/)

Add a method to serialize Triton module to MLIR bytecode

---

python/test/unit/language/test_core.py
python/triton/language/core.py

When comparing to the expected slides, using the `==` operator will dispatch to the component of the slice. If the user writes `a[10:20]` these are `triton.constexpr` instances, and the `__eq__` operator which is implemented as: `return constexpr(self.value == other.value)`. At this point the access to `.value` on the provided `None` yields an exception that isn't very friendly to the user.
I am not sure if the implementation of `constexpr` should be hardened instead?

Fix checks for valid slice and avoid hitting an obscure exception.

---

include/triton/Dialect/Triton/IR/TritonAttrDefs.td
include/triton/Dialect/Triton/IR/TritonOps.td
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
python/src/triton.cc
python/test/unit/language/test_core.py
test/Analysis/test-alignment.mlir
test/Conversion/tritongpu_to_llvm.mlir
test/Triton/rewrite-tensor-pointer.mlir
test/Triton/vecadd.mlir
test/TritonGPU/combine.mlir
test/TritonGPU/matmul.mlir

Also catch out-of-bounds indices at constructio and throw a proper error in the frontend.
Finally, let's make the IR a bit prettier:
%0 = tt.get_program_id {axis = 0 : i32} : i32
becomes:
%0 = tt.get_program_id x : i32
Fixes #1718

[FRONTEND][BACKEND] Hardened get_program_id axis by making it an enum attribute

---

lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.cpp
lib/Dialect/TritonGPU/Transforms/Pipeline.cpp
python/test/regression/test_functional_regressions.py

Support the following three cases:
1. Operands of `load` depend on induction variables before `load`s.
2. Mixed use of induction variables and offset to update the `ptr`.
3. Cross iteration (>1) dependency values.

[BACKEND] Pipeline pass rewrite part 1: functionality fixes

---

.github/workflows/wheels.yml
utils/nightly.pypirc

This reenables nightly builds and uploads them to a public AzDO, where you can use pip to install a specific version or the latest as normal. For example: `python -m pip install -i https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/Triton-Nightly/pypi/simple/ triton-nightly`

[PUBLISHING] Enable nightlies on Azure DevOps

---

include/triton/Conversion/TritonToTritonGPU/Passes.td
include/triton/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.h
include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
include/triton/Dialect/TritonGPU/IR/TritonGPUDialect.td
include/triton/Dialect/TritonGPU/Transforms/TritonGPUConversion.h
lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.cpp
lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
lib/Dialect/TritonGPU/Transforms/Coalesce.cpp
lib/Dialect/TritonGPU/Transforms/TritonGPUConversion.cpp
python/src/triton.cc
test/Conversion/triton_to_tritongpu.mlir

Add a configurable parameter for the number of threads per warp for other GPU. Like: Intel GPU.
Make it default to be 32 not change code logic on the CUDA/AMD GPU.
Note: The Intel GPU GenX ISA is explicit SIMD and can support variant number of threads lane per HW execution unit.

[BACKEND] Add a configurable parameter for the number of threads per warp

---

python/test/unit/language/test_core.py
python/triton/language/core.py

Not just syntactic sugar for successive max + argmax but also avoids computing the max twice

[FRONTEND] min/max now accept `return_indices` argument

---

lib/Conversion/TritonGPUToLLVM/CMakeLists.txt
lib/Dialect/TritonGPU/IR/CMakeLists.txt

This reflects a change upstream in llvm/llvm-project@61223c49d, which renamed that target.

[BUILD] Update CMake target name MLIRGPU{Ops => Dialect}.

---

python/triton/testing.py

In particular, sometimes this was failing with:
```
RuntimeError: quantile() input tensor must be either float or double dtype
```
Fixes https://github.com/pytorch/pytorch/issues/103054
Signed-off-by: Edward Z. Yang <ezyang@meta.com>

Force quantile tensors to be float; prevents accidents

---

include/triton/Analysis/Utility.h
include/triton/Dialect/TritonGPU/IR/Dialect.h
lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
python/test/unit/language/test_core.py

`tl.cat(tensor<64>, tensor<64>) -> tensor(128)`, because it concatenates elements into a single thread, if number of threads is 128, each thread should own at least 2 elements. 
With this PR, we also disable remat of the cat op in some cases.

[BACKEND] Fix` tl.cat` when the number of threads > the size of a tensor

---

python/triton/language/semantic.py

This makes it easier to figure out what's going on when you get these error messages.

Improve `tl.dot` error messages

---

lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp

https://reviews.llvm.org/D152814
The API of `RewriterBase::replaceOp` was extended and a fix is needed so that the called function is not ambiguous.
This change is compatible with both the old and the new API.

Integration fix for MLIR change D152814

---

python/triton/common/backend.py
python/triton/compiler/code_generator.py
python/triton/compiler/compiler.py
python/triton/debugger/debugger.py
python/triton/debugger/memory_map.py
python/triton/debugger/tl_lang.py
python/triton/language/__init__.py
python/triton/language/core.py
python/triton/language/random.py
python/triton/ops/blocksparse/matmul.py
python/triton/ops/blocksparse/softmax.py
python/triton/ops/cross_entropy.py
python/triton/ops/flash_attention.py
python/triton/ops/matmul.py
python/triton/ops/matmul_perf_model.py
python/triton/runtime/jit.py
python/triton/testing.py
python/triton/tools/aot.py

The idea behind this change is that it allows for continued use of Triton 2.0.0 under Torch Inductor, but also allows the main branch (2.1.0) to be used at the same time in the same scripts.  
With absolute imports only 1 version can be used at a time.
All files in triton/python/triton are changed to use relative imports over absolute imports.  The trickiest file was runtime/jit.py where I switched to use `__spec__` in the JITFunction here: https://github.com/IzzyPutterman/triton/blob/iputterman/relative-imports/python/triton/runtime/jit.py#L324
https://github.com/IzzyPutterman/triton/blob/iputterman/relative-imports/python/triton/runtime/jit.py#L398
And again in the jit.py file to compare against the triton module
https://github.com/IzzyPutterman/triton/blob/iputterman/relative-imports/py …

Switch absolute imports to relative imports in Triton

---

lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp
test/Conversion/tritongpu_to_llvm.mlir

Eviction lowering was missing when lowering store to inline ptx. This allows user to control this parameter from python.

Add lowering of eviction policy to store lowering

---

python/test/unit/language/test_core.py
python/triton/compiler/code_generator.py

Example:
```
if static_a == 0 and static_b == 1:
...
```
The return value of `static_a == 0` should be `constexpr(True)` but not `True`, otherwise the bool object (True/False) doesn't have the `logical_and` method.

[FRONTEND] Fix binary compare op on constexprs

---

.github/workflows/Dockerfile
.github/workflows/llvm-build.yml

This patch adds a GitHub workflow yaml file and a Docker file to build
LLVM for the commit hash specified in the llvm-hash.txt file in the
llvm-head branch.  If the tests run successfully, the built artifacts
are uploaded to Azure blob storage and their URL is available in the CI
logs.  These artifacts can then be used in the python/setup.py script
for fetching the necessary LLVM binary objects while building Triton.

[CI] add workflow for building, testing, and uploading LLVM artifacts

---

lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h

arith.trunc op is not allowed to use index type. This causes the IR to fail the verifier.
This doesn't cause a compilation failure as index are lowered to i32 in the same pass. 
However this creates intermediate IR that fails verifier which can make things harder to debug.

[BACKEND] Fix invalid intermediate IR in GPU to LLVM

---

python/triton/runtime/autotuner.py

This is a very quick change that allows the configs' pre-hooks to see the values in the config itself.  This is useful if we'd like to allocate intermediate tensor and the shape depends on tile size.

Allow pre-hook in autotuner configs to access config kwargs

---

lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp
test/TritonGPU/dot-operands.mlir

This happens in situations where the input IR only has a single operand to tt.dot that is produced by triton_gpu.convert_layout.

[OPTIMIZER] Fix invalid cast in OptimizeDotOperands

---

python/triton/runtime/jit.py

It seems that patch #1773 introduced a bug, since the `lhs` object doesn't necessarily have a `__name__` attribute.
I'm hitting this if I modify the matmul tutorial
(gflegar/triton@442b00f4d):
```
File "/home/gflegar/triton/python/triton/runtime/jit.py", line 74, in visit_Attribute
if lhs is None or lhs.__name__ == "triton":
AttributeError: 'Tensor' object has no attribute '__name__'
```
I think the idea of that patch was to remove the need to import triton by replacing `lhs is triton` with `lhs.__name__ == "triton"`. This patch should have the same behavior as the original code, but withouth failing if `lhs` doesn't havea `__name__` attribute.

[FRONTEND] Fix missing attribute access in DependenciesFinder

---

lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp

In upstream, llvm/llvm-project@71d50c89 introduced a new overload to that function, which made one call to that function ambiguous. This commit disambiguates the call.

[BACKEND] Make call to RewriterBase::replaceOp compatible with overload.

---

lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp
test/TritonGPU/dot-operands.mlir

The existing code would only move one of the operand layout convert since after the transformation the IR would fail the pre-condition that both operands needs to be blocked to dot operands.

[OPTIMIZER] Support move op after layout cvt for both dot operands

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp
lib/Dialect/TritonGPU/Transforms/Pipeline.cpp
test/TritonGPU/dot-operands.mlir

Since the kWidth optimization was happening during software pipelining it was skipped in case pipelining wasn't applied.
This also improve separation of concerns.

[OPTIMIZER] Separate out kWidth layout optimization from pipelining pass

---

python/setup.py

This can be used by IDEs to figure out how to correctly compile individual sources and offer semantic code completion.

[BUILD] Export compile commands

---

python/triton/runtime/autotuner.py

Adds an option to adjust warmup and repetition time for autotuning.  It should default to old values and have no effect on current kernels.  
This is useful for bigger kernels where runtime might be a sizable fraction 100ms and lead to less warmup and more variance during benchmarking.

Allow user to adjust warmup and repetition time for autotuning

---

lib/Target/LLVMIR/CMakeLists.txt

That library makes use of the dladdr function, so it eventually needs to be linked with -ldl, which may not be done automatically. This commit adds a link dependency to `${CMAKE_DL_LIBS}`, which is CMake's way of specifying that library in a portable way.

[CMAKE] Add link dependency to dl for TritonLLVMIR.

---

lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp
test/Conversion/tritongpu_to_llvm.mlir

Based on the the tensor encoding we may pick a different element type. Make sure the logic for constant lowering considers that when picking the type.

[BACKEND] Fix type mismatch for constant matrix

---

lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp
python/test/unit/language/test_core.py
test/Conversion/tritongpu_to_llvm.mlir

Since the type expected for mma encoding is i32 when lowering f16 splat we need to pack f16 constants into a i32 value. This allows re-enabling the constant matmul unit test.

[BACKEND] Enable lowering of f16 constant matmul

---

lib/Dialect/TritonGPU/Transforms/ReorderInstructions.cpp
test/TritonGPU/reorder-instructions.mlir

The pass was moving Convert op up without checking that it doesn't break ssa rule.

[BACKEND] Prevent invalid reordering in ReorderInstruction pass

---

include/triton/Analysis/Utility.h
lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/ScanOpToLLVM.cpp
python/test/unit/language/test_core.py

This relax the restriction in the scan lowering to support layout where we scan along a dimension which isn't the fastest moving one. This is done by relaxing how we accesses elements during scanning and allow elements to be strided.

[BACKEND] Support scan on dimensions other that fastest moving one

---

python/triton/language/core.py

As mentioned in #1769, we set file name, function name to 'unknown' and lineno to 0 if frame is None

Fix tl.device_assert compilation error

---

.github/workflows/integration-tests.yml

We need to split the CI into two jobs, nvidia (PR blocking) and third-party (PR non-blocking). This way we can guarantee that artifacts are uploaded for any PR that gets merged into `main`, and that `compare artifacts` job can just wait on the artifacts-uploading job.

[CI] Split integration tests into two jobs

---

python/test/unit/language/test_core.py
python/triton/compiler/code_generator.py

We've already updated the mapping between name and tensor before visiting each compound statement in the while op. As a result, any overwritten name gets up-to-date values updated in the while loop. And any unchanged livein names hold the original tensors.

[FRONTEND] Remove unnecessary replace in while op's after block

---

lib/Dialect/TritonGPU/Transforms/ReorderInstructions.cpp
test/TritonGPU/reorder-instructions.mlir

Change the logic to be able to re-order more cases. Instead of pulling the convert of operand 0 we sink the convert of operand 1 so that even if operand 0 has some dependency that don't dominate operand 1 we can still apply the re-ordering.

[BACKEND] Improve re-ordering of of dot operand convert ops #1897

---

.github/workflows/integration-tests.yml
python/test/unit/operators/test_cross_entropy.py

Run most of the pytest in parallel, this allows to speed up CI from 36min to 10min for A100 and 22min to 6min for H100. Some tests still need to run serially like runtime tests.

Enable parallel pytest in CI for CUDA

---

include/triton/Dialect/TritonGPU/IR/Dialect.h
lib/Analysis/AxisInfo.cpp
lib/Analysis/Utility.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
python/test/unit/language/test_core.py

Fix calculation of unique number of threads within a warp. We need to consider the number of elements per thread in the calculation. Also change the layout test to integer sum in order to catch bugs with unique data as max reduction may hide those kind of problems.

[BACKEND] Fix reductions when number of unique element is smaller than layout

---

python/src/triton.cc
python/test/unit/language/test_core.py

Calling `tl.full` with an unsigned dtype currently fails with the error:
```
AttributeError("'triton._C.libtriton.triton.ir.builder' object has no attribute
'get_uint8'")
```
This PR defines those functions rather than changing the calls to the signed versions so that we can use an unsigned argument type in C++ and avoid overflow for large uint64 values.

[FRONTEND] Fix tl.full with unsigned dtypes

---

lib/Dialect/Triton/Transforms/RewriteTensorPointer.cpp

will be skipped again when proper codegen for TMAs exists

[FRONTEND] don't skip block_ptr rewrite on H100

---

python/triton/language/core.py

"Expected type 'SupportsIndex', got 'constexpr' instead" is no longer reported.

[FRONTEND] Fix a inspection warning

---

lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
python/test/unit/language/test_core.py
test/Conversion/tritongpu_to_llvm.mlir

The code generated by LLVM ends up using 15 SASS instructions, while the inline PTX added here only uses 8. It might be possible to reduce this down to 6 if NVIDIA optimizes ptxas to use the byte selector in I2F for all bytes (right now, we still have some bit manipulation code generated for 2 out of 4 bytes).
This change improves the performance of mixed precision matmul kernel with M=N=K=4096, where one operand is casted from s8 to bf16 from 140 TFlop/s to 165 TFlop/s on A100-40GB.
Also refactors the ElementwiseOpConversionBase template to support vectorized operations, reducing the boilerplate needed for existing, and this new vectorized cast; and extends the casting test to process more than one element (so vectorized casts can be properly tested).

[BACKEND] Vectorize s8 to bf16 casts

---

python/src/triton.cc

Another follow up with the relative imports this time dealing with the bindings.  
Issue:  If one runs `import triton` and `import <module>.triton` where triton is a pip installed package of version 2.0.0 and <module>.triton contains a local copy of latest main, one gets 
```
Traceback (most recent call last):                                                                                                                                                                                                                                                             
File "<stdin>", line 1, in <module> …
```

Use local bindings in triton.cc

---

python/test/unit/tools/test_aot.py
python/triton/tools/compile.c
python/triton/tools/compile.h
python/triton/tools/compile.py
python/triton/tools/link.py

This PR addresses the following issues encountered when using AOT kernels in our project:
1. When different signatures are set for the same Triton kernel, it can result in C functions with the same name. This is problematic because C does not support function overloading.
2. Currently, the AOT kernel always compiles with `num_warps=1`, as indicated [here](https://github.com/openai/triton/pull/1939/files#diff-293af646f671d3a895c453a8b175754e9d4ec4fc855bb939ffa4d6e9e91b07c6L83). However, the generated function includes a `numWarps` argument, which can cause errors when the specified value does not match.
To resolve these issues, this PR does the following modifications:
1. Adds an 8-char hash key as a suffix to the generated function's signature. This ensures that different function names …

Hot fix for AOT

---

python/test/unit/language/test_core.py
python/triton/runtime/jit.py

Fixes the case where setting default values for arguments in a kernel function signature results in a generated kernel wrapper function without these default values.
For example:
```
@triton.jit
def kernel(x, y, z=3):
...
...
kernel[grid](x,y)
```

[FRONTEND] Add support for default args in kernel wrappers

---

python/test/unit/language/test_core.py
python/triton/compiler/code_generator.py

The process of visiting twice the body of the while didn't restore properly the insertion point, and was leaking the dummy block.

Fix AST IR generation for while loop nested inside other SCF

---

test/Triton/combine.mlir

The only difference between the two RUNs is `FileCheck`, which should be needed.

Remove unnecessary lit command from combine.mlir

---

lib/Analysis/AxisInfo.cpp
test/Analysis/test-alignment.mlir

If you call `result = load(x, mask)` where `x` and `mask` have some constancy properties, then you can infer some constancy properties for `result`.

AxisInfoVisitor for LoadOp constancy calculation

---

python/triton/common/build.py

`triton` uses `whereis` command to find `libcuda.so`, which is intended to find binary, source, and manual page files. When `libcuda.so` is not properly setup, the `whereis` command ends up with `/usr/share/man/man7/libcuda.7`, which is not the place to look for.
This PR uses `ldconfig -p` to reliably find `libcuda.so`.
In my case, I find that I have a `libcuda.so.1` file, but it is not linked to `libcuda.so`. Therefore `ld` cannot find the library to link. After creating the linking, I was able to run `triton` successfully.
Therefore, I improve the code by first invoking `ldconfig -p`, and checking `libcuda.so` strings first. These might be possible library to link against. If the literal `libcuda.so` file is not found, then I raise an error and tells the user that a possible fix is to …

improve the process of finding libcuda.so and the error message

---

python/tutorials/06-fused-attention.py

Uses FlashAttention-2 if available, otherwise acts as before (if FlashAttention-1 is available, that is used, otherwise the FlashAttention reference benchmark is not run).
I decided to keep the same name for the imported function, but feel free to make me change that.

[TUTORIALS] Support FlashAttention-2 reference

---

python/test/unit/tools/test_aot.py
python/triton/tools/compile.h
python/triton/tools/compile.py
python/triton/tools/link.py

- Change test_aot.py to actually use equal_to_1 hint
- In the client function, equal_to_1 parameters are not specialized, because AOT clients may not know the details of Triton argument specialization, they still want to use the same parameter list as they write the Triton kernel. The generated kernels has specialized argument list, the generated dispatcher code will make sure the correct arguments from the original full argument list are passed.
- Fixed a bug in _match_suffix in link.py. Previously it assumes each parameter has a suffix of either ‘d’ or ‘c’, but in fact sometimes a parameter doesn’t have a suffix, like 0d1d2d34c56c78c

Fix some issues in equal_to_1 hint

---

include/triton/Dialect/NVGPU/IR/NVGPUOps.td
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/WGMMA.cpp
lib/Dialect/NVGPU/ToLLVMIR/NVGPUToLLVMIR.cpp
lib/Hopper/HopperHelpers.c
python/test/unit/language/test_core.py

Also fixes a bug exposed in convertLayout lowering for float16. We shouldn't be using cvt.pack.sat.u16.s32 to pack 16bits values as this needs to take a 32bits register. Also this prevented optimization at llvm ir level.

[BACKEND] Support MMA V3 with float16 accumulator

---

python/setup.py

We are interested in having python wheels for triton built for Linux arm64 platforms, such as NVIDIA's Grace CPU.
This change is fairly simple, however:
- It requires a linux arm64 build of LLVM to be available (see MR here: https://github.com/ptillet/triton-llvm-releases/pull/15)
- For now my changes use the LLVM build hosted here: https://github.com/acollins3/triton-llvm-releases/releases/tag/llvm-17.0.0-c5dede880d17
- The Triton release process will need to be updated to include arm64 wheels. Is this something you have time to work on @ptillet? It would be difficult for me to update this part without more access permissions.
With these changes, I managed to build a set of python wheels and have hosted them here for us to use in the meantime: …

Linux arm64 support

---

python/triton/compiler/compiler.py

Rename "rocm" -> "hip", to comply with other uses in compiler.py.

[ROCM] fix device_type name

---

lib/Target/LLVMIR/LLVMIRTranslation.cpp

No functional changes intended, and it might slightly speed up the build.
This allows a downstream Bazel build of Triton to avoid building a number of dialects and passes that Triton doesn't need.

Include only necessary MLIR conversion passes, rather than all of them.

---

lib/Analysis/Utility.cpp
test/Conversion/tritongpu_to_llvm.mlir

`getScratchSizeInBytes` was assuming that the size of all types in bits is
a multiple of 8. If it is not, it would return 0. This caused a bug for boolean
(i1) type, where the reduction lowering would attempt to use shared memory,
which was not assigned to the op.
Fix this issue by setting the number of bytes per element to `ceil(bits / 8)`.

[BACKEND] Fix crash in reductions on i1

---

python/triton/runtime/jit.py

libtriton.so is pretty large these days and hashing it is slow. Switching the hash from md5 to sha1 shaves close to 300ms off the time for me (as well as being a better hash, for whatever that's worth).
As far as I could tell, sha1 is the fastest stable hash in the Python standard library, including things like zlib.crc32

[FRONTEND] improve speed of computing version_key

---

lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/Utility.cpp

This was causing the IR to fail verification in the intermediate steps. Also remove another unnecessary cast.

[BACKEND] Remove invalid indexCast ops

---

lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
python/src/triton.cc
python/triton/language/core.py
python/triton/language/math.py

maximum used to generate a cmp/sel even for floating point types. Always using max op allows better code quality and avoids having different behavior than tl.math.max

[FRONTEND] Refactor min/max to unify tl.maximum and tl.math.max

---

include/triton/Conversion/TritonGPUToLLVM/Passes.td
include/triton/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.h
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.cpp
lib/Target/LLVMIR/LLVMIRTranslation.cpp

For example, when given `--convert-triton-gpu-to-llvm="is-rocm=true"`, `ConvertTritonGPUToLLVMPass` should generate ROCM-compatible LLVM. Before this PR, transformation options passed in command line are not respected.

[TritonGPUToLLVM] Correct the usage of option passing

---

bin/triton-translate.cpp
include/triton/Conversion/TritonGPUToLLVM/Passes.td
include/triton/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.h
include/triton/Target/LLVMIR/LLVMIRTranslation.h
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.cpp
lib/Target/LLVMIR/LLVMIRTranslation.cpp
lib/Target/PTX/PTXTranslation.cpp
python/src/triton.cc
python/triton/compiler/compiler.py
test/Conversion/tritongpu_to_llvm.mlir

Before this PR, the determination of `TritonGPUToLLVMIRPass` to generate NVVM-compatible LLVM or ROCDL-compatible LLVM is controlled by a boolean `isROCM`. This method is hard to scale. 
This PR changes it to use an enum instead, where new target can be added easily when needed.

Use enum instead of bool to select target

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Conversion/TritonGPUToLLVM/DotOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/MMAv2.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp

Replace the Turing version for the dot operation from following Volta version to following Ampere version.
Update code generator to produce two m16.n8.k8 MMAs for Turing instead of one m16.n8.k16 MMA we have for Ampere.

Enable transpose for float16 on sm75

---

python/test/unit/language/test_core.py

Disable tf32 if run on sm75 and below
Fix the pattern match to compare the generated ptx against if run on sm75

[TESTS] Fix tl.dot test on sm75

---

lib/Dialect/TritonNvidiaGPU/Transforms/WSPipeline.cpp
python/test/unit/hopper/test_persistent_warp_specialized_gemm.py

For warp specialized persistent kernel, the instruction sequence for Warp Groups are
```
// warp group 0
for wave in 0..num_waves:
idx = wave * num_inner_loop_steps;
for k_tile_idx in 0..num_k_tiles:
mbarrier.wait EB[idx];
W0;
mbarrier.arrive FB[idx];
idx++;
```
```
// warp group 1
for wave in 0..num_waves:
idx = wave * num_inner_loop_steps;
for k_tile_idx in 0..num_k_tiles:
mbarrier.wait FB[idx];
R0;
mbarrier.arrive EB[idx];
idx++;
```
then this would form a sequence of morally-strong relations W0 -> R0 -> W1 -> R1 in causality order.
But if GEMM K is small than K-TileShape, then the num_inner_loop_steps of persistent kernel is 0. The buffer id and mbarrier id will always be 0 in this case. And it may form W0 -> W1 -> R0 -> R1 order, which is contradicts with the atomicity --
"If a read …

[OPTIMIZER] Fix Warp Specialized kernel launch failure

---

python/src/triton.cc

https://github.com/openai/triton/issues/2138

[FRONTEND] Emit warning if the result of `tl.advance` is unused

---

python/triton/testing.py

A [recent PR](https://github.com/openai/triton/pull/2036/files#diff-447aaa7319f4083423e0d1ce5ecbf440e7efe60b5bc527b38f82e982280b98d3) changed the behavior of `triton.testing.Benchmark`, causing the x-axis to be incorrect and the dataframe to contain strings instead of values.
This PR improves the behavior to correctly handle the single `x_name` use case while also supporting the new multiple `x_name` with different values use case. I also added some type annotations and updated the docstring for clarity.
To test this I made one vanilla test case that fits the most common single `x_name` pattern, and another from [the use case added in the above-mentioned PR](https://github.com/openai/triton/pull/2036/files#diff-8230ecf751625890f518ea30c064b509c1275be1c3b990a3b621d48aaa854771R149-R174) …

[FRONTEND] Fix benchmark plotting

---

include/triton/Dialect/Triton/IR/TritonOps.td
lib/Dialect/Triton/IR/Ops.cpp
test/Triton/canonicalize.mlir

This folds `tl.arange(x, x + 1)` into a constant. This shows up for example when autotuning and one of the block sizes gets set to 1.

[OPTIMIZER] Add folder for MakeRangeOp

---

lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
test/TritonGPU/combine.mlir

Handle more cases of hoisting convert above ext op. If there are multiple ext op in the slice but only one requires inserting a convert we can still apply the optimization.

[BACKEND] Extend hoisting of convert op above ext ops

---

python/triton/ops/flash_attention.py

I'm not sure if this was a typo or if I'm missing something. To me code like
```
(offs_n[:, None] * stride_vk + offs_k[None, :] * stride_vn)
```
seems off.
In case this is a typo I made this PR to correct it. This PR should have no functional changes.
If this is not a typo would you mind explaining the reasoning behind these variable names?

Swap `stride_vn` and `stride_vk` in flash attention

---

python/triton/compiler/make_launcher.py
python/triton/runtime/backends/cuda.c
python/triton/runtime/backends/hip.c

The use of the opaque GIL state APIs should mean that the PyErr_SetString is now safe, regardless of whether the caller has the GIL or not.

Fix GIL handling in error conditions

---

lib/Conversion/NVGPUToLLVM/NVGPUToLLVMPass.cpp
lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp

The predicate of Store Tiled op was not set which caused a lot of perf drop due to duplicated memory traffic in epilogue.

Fix predicate for store tiled op

---

python/triton/ops/flash_attention.py
python/tutorials/06-fused-attention.py

This bug previously existed and I verified it in previously nightly release of triton (20230714). 
However, according to new benchmarks, this bug no longer exists on Triton main. See: https://github.com/google/jax/pull/17328#issuecomment-1705010065

[OPS] Remove unnecessary perf bug workaround

---

python/setup.py

Current setup.py could not clean the build directly because the default build directly has been changed in `CMakeBuild`. This PR is to clean build directly in this regard.

Clean build directly when executing python setup.py clean

---

lib/Dialect/TritonGPU/Transforms/Coalesce.cpp

Remove unnecessary templates and simplify the mapping of operations to encoding.

[BACKEND][NFC] Simplify coalescing pass

---

python/triton/runtime/autotuner.py

This change seems to have been unintentionally reverted in the hopper PR: https://github.com/openai/triton/commit/38d767ea93ae31c949b68baa50429f7a7e1b0cc1
Adding it back.

Revert unintentional change

---

lib/Analysis/Utility.cpp
python/test/unit/language/test_core.py

This can happen when the CTA shape is larger than the tensor shape along the non-axis dim during scanOp lowering.

Make sure `getAxisBlockStride` does not return 0

---

python/test/regression/test_functional_regressions.py
python/test/unit/hopper/test_persistent_warp_specialized_gemm.py
python/test/unit/language/test_block_pointer.py
python/test/unit/language/test_core.py
python/test/unit/operators/test_blocksparse.py
python/test/unit/operators/test_cross_entropy.py
python/test/unit/operators/test_flash_attention.py
python/test/unit/operators/test_inductor.py
python/test/unit/operators/test_matmul.py

Prior to this PR, matmul on sm_89 (RTX 4070) (`test/unit/operators/test_matmul.py::test_op`) would result in test failure due to too strict atol/rtol. 
To avoid having to choose strictness ourselves, and to have better defaults based on dtype, use the non-deprecated torch testing util.
See: https://github.com/pytorch/pytorch/issues/61844
Replace: https://github.com/openai/triton/pull/2242

[TESTS] replace deprecated `torch.testing.assert_allclose`

---

lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/WGMMA.cpp
python/triton/runtime/backends/cuda.c

This PR fixes a few very minor compilation issues found in internal deployment at Meta.  It looks like nit-picking, but it'd be really appreciated if it could be addressed in OSS Triton (to reduce differences from OSS), and we believe these changes are not bad in general.  Neither performance nor functionality is affected by this PR.
1. Type cast in `python/triton/runtime/backends/cuda.c`. Implicit `void *` -> `cuuint{32,64}_t *` cast is not allowed by many compilers (with certain flags).  It'd be nice to add an explicit cast (like `backends/hip.c`).
2. Inconsistent include path specification in `lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/WGMMA.cpp`.  Unlike other `DotOpToLLVM/*.cpp`, include paths used in `WGMMA.cpp` are not relative.  This is problematic in some compilation settings …

[Build] Fix very minor compilation problems

---

python/test/unit/language/test_core.py
python/triton/language/core.py
python/triton/language/semantic.py

This fixes a few bugs related to scalar tensors:
- `tl.full([], fill_value, dtype)` fails with `TypeError('0d block_type is forbidden')`
- `scalar[None]` fails with `TypeError("'constexpr' object is not iterable")`
- `scalar[None, None]` fails with `AttributeError("'dtype' object has no attribute 'shape'")`
- `scalar.shape` returns `[1]` instead of 0-dim `[]`
- Also related, `tl.zeros_like(scalar)` returns a 1d tensor instead of another scalar

[FRONTEND] Fix expand_dims and tl.full to handle scalar tensors

---

python/triton/runtime/jit.py

Add PyTorch fp8 dtypes (https://github.com/pytorch/pytorch/blob/8025b193a966a6d8e3afc9c03a54e577bc04eb3d/torchgen/api/types/types.py#L50-L51) to Triton.

[Easy] Add PyTorch fp8 dtypes to Triton

---

lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp

This is needed for forward-compatibility with MLIR that now has "inherent" and "discardable" attributes (https://mlir.llvm.org/OpenMeetings/2023-02-09-Properties.pdf) and the ExternElementwiseOp attrs do not propagate with the current `addNamedAttrs` implementation.

[NFC] Create explicit conversion pattern for ExternElementwiseOp in TT->TTGPU pass

---

lib/Dialect/Triton/Transforms/ReorderBroadcast.cpp
lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
test/Triton/reorder-broadcast.mlir
test/TritonGPU/combine.mlir

Try to move broadcast ops after arithmetic and convert ops in order to reduce the amount of work needed.

[BACKEND] Optimization to sink broadcast ops

---

python/test/unit/language/test_core.py
python/test/unit/tools/test_aot.py
python/triton/compiler/compiler.py

- Support memory space for pointers (e.g., `!tt.ptr<f32, 1>`).
- Support parsing function attribute, though not used yet.

[FRONTEND] Accommodate new triton IR format

---

lib/Target/LLVMIR/LLVMIRTranslation.cpp

Move the optimization to remove phi of struct later in the optimization pipeline to avoid interfering with CFG optimization.

[BACKEND] Move struct optimization down the LLVM pipeline

---

.gitignore

Otherwise, these files show up in `git status` under
python/triton/third_party/cuda/bin/.

Add cuobjdump and nvsisasm to gitignore.

---

README.md

On my machine, when I try to `pip install cmake` outside a virtualenv,
it gets mad at me and tells me to use apt.  Which doesn't quite work for
some reason.  Anyway maybe this is simple to Python people, but perhaps
worth mentioning.  Especially because we have `.venv` in gitignore
already.

Add build instrs for running in a virtualenv.

---

.github/workflows/integration-tests.yml

reverts openai/triton#2310 as recent changes to Triton-IR have broken third-party backends

Revert "Update integration-tests.yml"

---

.github/workflows/integration-tests.yml
README.md
python/pyproject.toml
python/setup.py

I noticed that I was not getting much parallelism when building Triton
on my local machine.  After switching from make to ninja, I get a whole
lot more parallelism, and the from-scratch build runs much faster.
On my local machine, I ran:
$ rm -rf python/build; time pip install -e python
- Before(make):   999.11s user 124.67s system  484% cpu 3:51.90 total
- After (ninja): 1539.75s user 187.06s system 2052% cpu 1:24.14 total
On my machine (granted, I have a lot of cores), the speedup is
(3 * 60 + 51) / (1 * 60 + 24) = 2.7x.

Use ninja for builds.

---

python/triton/language/semantic.py

Fixes: https://github.com/openai/triton/issues/2302

[FRONTEND] Explicitly forbid `dot(.., out_dtype=bfloat16)`

---

python/triton/compiler/compiler.py

XPU does not need to set the stages in compiler.py and relies on the setting of the following.
```Python
arch["num_warps"] = num_warps
arch["num_stages"] = num_stages
arch["num_ctas"] = num_ctas
```
In view of this, this PR deletes the logic of explicitly setting the stages in the compiler.py.
cc @EikanWang , @chengjunlu

Fix xpu stages logic

---

python/triton/ops/matmul.py

Previously on matmul, if inputs are int8, output was also int8.
This commit fixes the overflow problem with int32 output.
#2296

[FRONTEND] fix matmul int8 overflow issue

---

lib/Dialect/Triton/Transforms/RewriteTensorPointer.cpp
lib/Dialect/TritonGPU/Transforms/Pipeline.cpp
lib/Dialect/TritonGPU/Transforms/Prefetch.cpp

Some duplicate functions on `scf.for` have been removed in llvm/llvm-project#66512. This PR works with and without llvm/llvm-project#66512.

Integration fixes for llvm/llvm-project#66512

---

lib/Dialect/Triton/Transforms/ReorderBroadcast.cpp
lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
test/Triton/reorder-broadcast.mlir
test/TritonGPU/combine.mlir

Improve patterns that sync broadcast to reduce the arithmetic density and also hoist convert on top of expand_dims to do less work.
This address comments in https://github.com/openai/triton/pull/2274

[BACKEND] Relax patterns to move sink broadcast and hoist convert

---

python/triton/compiler/make_launcher.py

This was regressed by #2185 because we didn't realise CUDA_CHECK macro could do Python calls (similar to what led to #2225). I think the PyErr_Occurred got removed in that PR because there was missing error handling before the call to _launch, so it looked like it was just in the wrong place.
It looks like there are also potentially a couple places in cuda.c that can return with error set, e.g. getDeviceProperties, memAlloc, memcpyHtoD, memFree, tensorMapEncodeTiled etc, but those are all pre-existing and not affected by recent changes.

[FRONTEND] Fix Python error handling in launch

---

lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
lib/Dialect/TritonGPU/Transforms/Pipeline.cpp

llvm/llvm-project#66754 extends the `LoopLikeOpInterface`: the signature of `getLoopBody` has changed. `ForOp::getRegion` can be used instead.
This change works with and without llvm/llvm-project#66754.

Integration fixes for llvm/llvm-project#66754

---

.pre-commit-config.yaml

Google uses clang-format at LLVM HEAD.  clang-format's formatting is not
stable, so we want to minimize the difference between the pre-commit
clang-format and HEAD to minimize differences with Google's formatter.
In practice, it appears that there are no relevant changes to the
formatting, so this is a nop.  :shrug:
Tested by running `pre-commit run --all-files`.

Switch pre-commit clang-format to v16.0.6.

---

lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp
python/test/unit/language/test_core.py
python/triton/language/semantic.py

This fixes a few bugs I've encountered
- `atomic_add` with int64/uint64 `Operation .add requires .u32 or .s32 or .u64 [...] for instruction 'atom'`
- `atomic_min/max` with float64 -> `ValueError('Cannot bitcast data-type of size 64 to data-type of size 32')`
- `atomic_min/max` with float32 returns the old value as int32

[FRONTEND][BACKEND] Fix various atomic_rmw bugs

---

lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/MMAv2.cpp
python/test/unit/language/test_core.py

Replace a single mma.sync.aligned.m16n8k32.row.col.satfinite.s32.s8.s8.s32 instruction that is used on Ampere with 4 x mma.sync.aligned.m8n8k16.row.col.satfinite.s32.s8.s8.s32 instructions for Turing
Extracted the Turing-int8, Turing-fp16 and Ampere to separate functions.
Somehow I messed up with my previous PR, so just open a new one.

Implement dot for int8 on Turing

---

python/triton/language/core.py

Hi
`function_type` does not have a `name` field, which leads to an error when debugging with gdb.

Fix core.dtype.__repr__

---

include/triton/Dialect/TritonGPU/Transforms/Utility.h
lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
test/TritonGPU/accelerate-matmul.mlir

When there is a chain of mma ops we want to pick the same shape to avoid conversions. This improves the detection going through for loops.
This fixes a crash in tutorial bw attention.
We might want to change this logic and convert the format to allow more efficient MMA at some point.

[BACKEND] Improve decision of MMA dimension on H100

---

.github/workflows/integration-tests.yml
.gitmodules

This PR leverages the plug-in system to add a shared middle-layer to Triton.
Currently the middle layer is not complete but has enough functionality to demonstrate how it can work. The general idea is that Triton IR is lowered into an MLIR core dialect to allow it to be both shared across Triton targets as well as allow back-ends to be shared with other languages.
The basic intended architecture looks like this:
[Triton IR] -> [Middle Layer] -> [HW specific IR]
The middle-layer uses MLIR's Linalg and Tenor Dialects for operations on Triton block values. Operations on Triton pointers use the Memref Dialect.
To include the shared middle-layer in your Triton build do `export TRITON_CODEGEN_TRITON_SHARED=1` before invoking your build. Once it is part of the build it can be leveraged in two …

Add Shared Middle Layer to Triton via Plug-In

---

python/triton/runtime/jit.py

Hi,
I'm adding some features to `triton.runtime.jit.JITFunction_make_launcher` and found it is hard to debug it:
1. The inlined Python code is hard to inspect in my editor.
2. My debugger fails to step into these inlined codes.
In response, I've introduced some code to solve these issues. My modifications include:
~~1. Refactoring the launcher's inline Python code, ensuring it only relies on the "self" object.~~
~~2. Add a utility method that generates a temporary file to create a launcher when debugging kernel in main module~~
Using a closure to hold the launcher's body
Because this features might be good to others, I have initiated this Pull Request. 
~~Tests are yet to be added; if this submission might be accepted, I will add it later.~~
Since this change is a refactor, no new test …

[FRONTEND] using closure to create jit launcher

---

python/triton/tools/compile.py

`out_path.with_suffix` (penultimate line) fails if out_path is string.

Fix out_path parsing in AOT compiler

---

.gitignore

Vscode or clangd can create indexing cache for symbol resolutions. Those files should be ignored by git.
I'm basically cloning what is done in the LLVM repo.

Git ignore clangd and vscode index files.

---

lib/Analysis/AxisInfo.cpp
test/Analysis/test-alignment.mlir

Previously ExpandDims always inserts 1 as the new divisibility, which makes writing (x * stride)[:, None] far more slower than (x[:, None] * stride). A better divisibility can be afforded by computing the GCD of the old dims. Now the two code above are equally fast. E.g. the conv inductor in pytorch may be faster.

[OPTIMIZER] Calculate a proper divisibility for ExpandDims

---

python/tutorials/01-vector-add.py
python/tutorials/02-fused-softmax.py
python/tutorials/03-matrix-multiplication.py

This reverts commit 99af23f6f4368c62fa23e7acad925f65d85a734e.
`quantiles` shouldn't be the problem. The documentation workflow failed because of other issues.

Revert "[TUTORIALS] Remove unneeded quantiles parameter (#2408)"

---

lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp

Fix bugs in https://github.com/openai/triton/pull/2415. cc @htyu 
Previously corresponding tests failed on H100 with latest torch version. It passed CI because CI doesn't use latest torch, so the tests were skipped.

Fix PTX issues in bf16 / fp8_e4m3 conversion

---

lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
python/test/unit/language/test_core.py

clipping float8e4b15 to +-1.875 is a bad idea because these are represented as 0x7f and 0xff, which are +- nan on H100 for float8e4nv. We lose two values but this will make compatibility with float8e4nv way less painful. (it will just be a matter of adjusting the bias)

[FRONTEND][BACKEND] changed float8e4b15 clipping semantics from +-1.875 to +-1.75

---

.github/workflows/wheels.yml
python/src/triton.cc

emitting warnings from C++ code requires "#include pybind11/exec.h" which is not compatible with pypy. I think using the python interpreter form C++ is a bad idea in general... but we probably don't care much about pypy wheels anyway

[CI] disable pypy wheel

---

lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
test/Conversion/divide-by-0.mlir
test/Conversion/tritongpu_to_llvm.mlir

It was possible for multiDimWarpId[1] to be 0 which then gets translated into a `urem 0, 0` and results in an unreachable when going through llvm, an empty kernel, and nans.  This PR uses ceiling to clamp the result to be >=1.
chsigg is working on a fix to lower the unreachable in llvm to a trap (https://github.com/llvm/llvm-project/pull/67478).

Fix division by 0 pathway

---

lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
lib/Conversion/TritonGPUToLLVM/Utility.h

```
import triton
import torch
ir = """
#blocked = #triton_gpu.blocked<{sizePerThread = [1, 4], threadsPerWarp = [2, 16], warpsPerCTA = [4, 1], order = [1, 0], CTAsPerCGA = [1, 1], CTASplitNum = [1, 1], CTAOrder = [0, 1]}>
#blocked1 = #triton_gpu.blocked<{sizePerThread = [1, 4], threadsPerWarp = [4, 8], warpsPerCTA = [4, 1], order = [1, 0], CTAsPerCGA = [1, 1], CTASplitNum = [1, 1], CTAOrder = [0, 1]}>
#shared = #triton_gpu.shared<{vec = 1, perPhase = 1, maxPhase = 1, order = [1, 0], CTAsPerCGA = [1, 1], CTASplitNum = [1, 1], CTAOrder = [0, 1], hasLeadingOffset = false}>
module attributes {"triton_gpu.compute-capability" = 86 : i32, "triton_gpu.num-ctas" = 1 : i32, "triton_gpu.num-warps" = 4 : i32, "triton_gpu.threads-per-warp" = 32 : i32} {
tt.func public …
```

[BACKEND] Fine-tune SharedMemoryObject definition and fix related problems

---

lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp

```
import triton
import torch
ir = f"""
#blocked = #triton_gpu.blocked<{{sizePerThread = [1, 4], threadsPerWarp = [4, 8], warpsPerCTA = [4, 1], order = [1, 0], CTAsPerCGA = [1, 1], CTASplitNum = [1, 1], CTAOrder = [0, 1]}}>
#blocked1 = #triton_gpu.blocked<{{sizePerThread = [1, 4], threadsPerWarp = [2, 16], warpsPerCTA = [4, 1], order = [1, 0], CTAsPerCGA = [1, 1], CTASplitNum = [1, 1], CTAOrder = [0, 1]}}>
#blocked2 = #triton_gpu.blocked<{{sizePerThread = [1, 1], threadsPerWarp = [32, 1], warpsPerCTA = [1, 4], order = [0, 1], CTAsPerCGA = [1, 1], CTASplitNum = [1, 1], CTAOrder = [0, 1]}}>
#shared = #triton_gpu.shared<{{vec = 1, perPhase = 1, maxPhase = 1, order = [1, 0], CTAsPerCGA = [1, 1], CTASplitNum = [1, 1], CTAOrder = [0, 1], hasLeadingOffset = false}}>
module attributes …
```

[Backend] fix a bug in lowering ExtractSliceOp from TritonGPU to LLVM

---

lib/Target/PTX/PTXTranslation.cpp

We've seen cases where the entire kernel is poisoned due to division-by-zero, resulting in a single `unreachable` instruction at the LLIR level. Emit this instruction as `trap` (instead of dropping it) so that the kernel doesn't run successfully without writing any outputs.

[BACKEND] Lower to PTX with `trap-unreachable`

---

docs/python-api/triton.language.rst
python/triton/language/core.py

- Move atomic_cas and atomic_xchg to "atomic ops" section of
documentation.
- Don't talk about the `cmp` operand for operations which don't have
it.
- Document the `sem` operand.
- :code:`foo` and ``foo`` don't work inside a :type: annotation,
apparently.  (They are rendered literally, instead of being treated
as a formatting command.)  Get rid of them.
- Format the bulleted lists in the load/store operations as intended.

Improve docs for atomic and load/store operations.

---

lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
test/Conversion/tritongpu_to_llvm_hopper.mlir

On Hopper we can use native fp8 conversion ops that are significantly more efficient.
Improves epilogue in matmul. 8192x8192x512xf8 goes from 567 TFlops to 630 TFlops (the kernel is highly latency bound but this is a good proxy for epilogue performance)

[BACKEND] Use native fp8 convert ops when possible

---

include/triton/Dialect/NVGPU/IR/NVGPUOps.td
include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td
lib/Conversion/NVGPUToLLVM/NVGPUToLLVMPass.cpp
lib/Conversion/TritonGPUToLLVM/DotOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/WGMMA.cpp
lib/Dialect/TritonGPU/Transforms/Pipeline.cpp
lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
lib/Dialect/TritonNvidiaGPU/Transforms/WSPipeline.cpp
test/Conversion/tritongpu_to_llvm_hopper.mlir
test/NVGPU/test_wgmma.mlir
test/TritonGPU/fence-inserstion.mlir
test/TritonGPU/wspipeline.mlir

Fix dependencies in wgmma_wait op to prevent the scheduler from moving it past the uses of wgmma accumulator. We need to explicitly represent the dependency between the wait and the accumulator uses otherwise LLVM is free to re-order those.
This allows us to remove a workaround to prevent the re-ordering. We can also remove the wait op added in the loop during pipelining.
Also fix the descritpor calcuation for wgmma, we should calculate the same descriptor for the whole warpgroup.
Added a workaround for a bug that was exposed by different timing due to those changes. We shouldn't insert operations between the loop and async_wait or we may have race conditions.

[BACKEND] Fix multiple bugs in WGMMA

---

lib/Target/LLVMIR/LLVMIRTranslation.cpp

This is causing functional failures in pytorch workload. Disabling it until I figure out the problem.

[BACKEND] Disable BreakPhiStruct pass

---

lib/Dialect/TritonNvidiaGPU/Transforms/WSMaterialization.cpp
lib/Dialect/TritonNvidiaGPU/Transforms/WSMutex.cpp
lib/Dialect/TritonNvidiaGPU/Transforms/WSPipeline.cpp
python/triton/compiler/compiler.py
test/TritonGPU/wsmaterialization.mlir
test/TritonGPU/wsmutex.mlir

This is just for Warp Specialization kernels on Hopper. Replace DivOp and RemOp with SelectOp and AndOp/XorOp.

[OPTIMIZER] remove divOp and remOp from gemm math loop

---

lib/Dialect/TritonGPU/Transforms/Pipeline.cpp
lib/Dialect/TritonNvidiaGPU/Transforms/WSPipeline.cpp
test/TritonGPU/wspipeline.mlir

Based on discussion this is needed to make sure there is no race condition when reading shared memory.

[BACKEND] Add back dot.wait when generating async_dot

---

lib/Dialect/TritonGPU/Transforms/Pipeline.cpp
test/TritonGPU/loop-pipeline.mlir
test/TritonGPU/matmul.mlir

The pipeliner was overallocating shared memory for the inputs
for current schedule. This reduces the shared memory usage to only
what is needed.
Note that improving membar analysis could allow taking advantage of
allocating extra buffers to remove barriers.

[Pipeliner] Allocate less shared memory when possible

---

CMakeLists.txt

The previous change still didn't link libstdc++fs into libtriton.so, which caused the runtime error: undefined symbol _ZNKSt10filesystem7__cxx114path11parent_pathEv
`link_libraries(stdc++fs)` should be placed before `add_library`.
This PR Makes the link_libraries(stdc++fs) global for all targets in the CMake project. By doing so, we ensure that the stdc++fs library is consistently linked to all targets, addressing potential build issues on old linux OS like debian10 which uses GCC8.3.0 as the default C/C++ compiler.

[Build] Makes the link_libraries(stdc++fs) global for all targets in the CMake project.

---

bin/triton-translate.cpp
include/triton/Target/PTX/PTXTranslation.h
lib/Target/PTX/PTXTranslation.cpp
python/src/triton.cc
python/test/unit/language/test_core.py
python/triton/compiler/compiler.py
python/triton/runtime/interpreter.py
python/triton/runtime/jit.py

By default, ptxas will enable fusion of mul/add to fma instructions. The backend was also being configured unconditionally to enable this on conversion from LLVM IR to PTX. This commit adds an option which can be used to disable the FP fusion behavior in both locations.

[FRONTEND] add option to disable fp mul/add fusion

---

README.md
python/setup.py

There was a mismatch in the llvm link name

[BUILD] Fix macos x86 build

---

include/triton/Dialect/TritonGPU/IR/Dialect.h
lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
test/TritonGPU/canonicalize.mlir

When propagating layout we were generating a view op with mismatching total number of element per threads. Lowering such op would require exchanging data across threads.
This change prevents the optimizer from generating such cases. This may require further optimizations in the future.

[BACKEND] Fix unsupported view op created during optimizations

---

python/triton/runtime/cache.py

I think there's no guarantee that `/tmp/triton/*/*.json` existing means that the corresponding `/tmp/triton/*/*.cubin` file also exists.

[RUNTIME] Filter out paths that don't exist in json group cache

---

python/test/unit/language/print_helper.py

<git-pr-chain>
1. Make kernel_static_print test work when called twice.
This test is checking that a message is printed when the kernel is compiled.
But the test had nothing to force the kernel to be compiled every time you ran
the test.  So after you ran it once, the test would fail every time until you
cleared the cache.
1. 👉 #2518 👈 **YOU ARE HERE**
1. #2520

Make kernel_static_print test work when called twice.

---

include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td
lib/Analysis/AxisInfo.cpp
lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
lib/Dialect/TritonGPU/Transforms/TritonGPUConversion.cpp
lib/Dialect/TritonNvidiaGPU/Transforms/PlanCTA.cpp
lib/Dialect/TritonNvidiaGPU/Transforms/RewriteTensorPointer.cpp
python/test/unit/language/test_core.py
test/Analysis/test-alignment.mlir
test/Conversion/triton_to_tritongpu.mlir
test/Conversion/tritongpu_to_llvm.mlir
test/Triton/print.mlir
test/Triton/vecadd.mlir
test/TritonGPU/coalesce.mlir
test/TritonGPU/combine.mlir
test/TritonGPU/loop-pipeline.mlir
test/TritonGPU/rewrite-tensor-pointer.mlir
test/TritonGPU/wsdecomposing.mlir
test/TritonGPU/wspipeline.mlir
test/TritonNvidiaGPU/ws-feasibility-checking.mlir

Now that the bug related to attribute is fixed in MLIR we can use arith ops for cmp and select ops.

[BACKEND] Remove ttg.cmp and ttg.select and replace by arith op

---

python/setup.py

<git-pr-chain>
Add TRITON_BUILD_WITH_ASAN envvar.
Note that asan doesn't work with programs that use the GPU, so this is
only useful for running tools like triton-opt.
I was not able to get msan working.  libstdc++'s std::string
implementation seems to use uninitialized memory in a way that seems
safe but triggers an msan error.  I tried and gave up on switching to
libc++ and teaching msan to ignore this error.
1. #2531
1. 👉 #2533 👈 **YOU ARE HERE**
1. #2532

[BUILD] Add TRITON_BUILD_WITH_ASAN envvar

---

python/triton/runtime/autotuner.py

When input tensors' `dtype` changes, autotuning should (in general) be run again. At least two reasons for this:
1. The best-performing config on one `dtype` may not be the best for others (e.g., index `dtype` change from `i32` to `i64` may lead to heavier arithmetics).
2. A valid config for one `dtype` may be invalid for another (e.g., block sizes picked for `fp8` may be too large and lead to shared memory OOM with `fp32`).
Currently, input `dtype`s are not included in the autotining cache key, leading to the cached config on one input tensors' `dtype` be reused for all others. In this PR, the `dtype`s of all inputs having a `dtype` property are appended to the cache key. This should invalidate the cache on `dtype` change.

[FRONTEND] Add input dtypes to autotuning key

---

python/setup.py

<git-pr-chain>
Add TRITON_BUILD_WITH_ASAN envvar.
Note that asan doesn't work with programs that use the GPU, so this is
only useful for running tools like triton-opt.
I was not able to get msan working.  libstdc++'s std::string
implementation seems to use uninitialized memory in a way that seems
safe but triggers an msan error.  I tried and gave up on switching to
libc++ and teaching msan to ignore this error.
1. 👉 #2537 👈 **YOU ARE HERE**
1. #2531
1. #2532

[BUILD] Add TRITON_BUILD_WITH_ASAN envvar.

---

lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.h
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
python/test/unit/language/print_helper.py
python/test/unit/language/test_subprocess.py
python/triton/language/semantic.py

<git-pr-chain>
[BACKEND] Improve printf.
Previously, we printed all of a GPU thread's values in a single printf()
call, and this, plus the user-specified prefix, was all we printed.
This caused a few problems.
- nvptx printf can only handle 32 arguments; if you pass more than
that, it prints garbage.  So if a thread had more than 32 values, you
couldn't print them, issue #2486.
- The order of the values within the Triton program (GPU thread block)
is an implementation detail -- it depends on the layout the compiler
assigns to a tensor.  So this also prevented you from interpreting
the printed output.
To address this, we now print the Triton pid and multi-dimensional
Tensor index for each value.  And each value gets its own line to avoid
passing too many args to printf.
Example output:
``` …
```

[BACKEND] Improve printf.

---

lib/Dialect/TritonGPU/Transforms/Pipeline.cpp
python/test/unit/operators/test_flash_attention.py
test/TritonGPU/pipeline-hopper-remove-wait.mlir

**Performance on H100 SXM5 HBM3**
SM: 1830 MHZ
-[BATCH]-[N_HEADS]-[D_HEAD]-[mode]-[casual]-[seq_par]
fused-attention-batch4-head48-d64-fwd-True-True:
N_CTX    Before      After
0  1024.0  0.124135  0.120228
1  2048.0  0.391899  0.378483
2  4096.0  1.381547  1.340469
3  8192.0  5.182845  5.013851
fused-attention-batch4-head48-d64-fwd-True-False:
N_CTX    Triton     After
0  1024.0  0.124390  0.120371
1  2048.0  0.392177  0.379371
2  4096.0  1.380980  1.337169
3  8192.0  5.191552  5.013165
fused-attention-batch4-head48-d64-fwd-False-True:
N_CTX    Triton     After
0  1024.0  0.159597  0.153621
1  2048.0  0.563483  0.540353
2  4096.0  2.141308  2.053801
3  8192.0  8.244150  7.886597
fused-attention-batch4-head48-d64-fwd-False-False:
N_CTX    Triton     After
0  1024.0  0.160086  0.153992
1 …

remove extra wgmma_wait_group in flash attentinon

---

.flake8

<git-pr-chain>
[BUILD] Disable W503 in flake8 config.
It seems that by default, flake8 warns on both "linebreak occurred before
binary operator" (W503) and "linebreak occurred *after* binary operator"
(W504).  You...kind of have to pick one of these.  :)
According to the docs, W503 is deprecated, so we disable that one.
https://www.flake8rules.com/rules/W503.html
1. 👉 #2555 👈 **YOU ARE HERE**
1. #2556

[BUILD] Disable W503 in flake8 config.

---

.pre-commit-config.yaml
python/pyproject.toml
python/triton/ops/flash_attention.py
python/triton/runtime/__init__.py
python/triton/runtime/autotuner.py
python/triton/runtime/cache.py
python/triton/runtime/driver.py
python/triton/runtime/errors.py
python/triton/runtime/interpreter.py
python/triton/runtime/jit.py

We're in the process of incrementally converting from autopep8 + flake8 + isort to ruff, on a directory-by-directory basis.
The motivation to switch away from autopep8 is that I can't get it to
wrap long lines, even with -aaa.  This seems to be a known problem,
https://github.com/hhatto/autopep8/issues/497.
See more details about alternatives tried in
https://github.com/openai/triton/pull/2557.

Apply `ruff` pre-commit to python/triton/runtime.

---

python/triton/runtime/jit.py

<git-pr-chain>
[FRONTEND] Refactor jit.py.
The goal is to simplify the code and make it more flexible before we
change the kernel launch syntax to
`kernel[grid, compiler_flags(...)](...)`.
The main changes here are:
- Get rid of the eval'ed code in make_launcher.  We can do everything
using bind().
- Add KernelParam and KernelArg classes, letting us get rid of the
parallel arrays/dicts indexed by parameter index.
- Get rid of duplicated kernel launch code in the cache-hit/cache-miss
branches.
1. 👉 #2556 👈 **YOU ARE HERE**

[FRONTEND] Refactor jit.py.

---

.github/workflows/integration-tests.yml

<git-pr-chain>
Use clang+lld in CI builds.
This is significantly faster.
1. 👉 #2564 👈 **YOU ARE HERE**

Use clang+lld in CI builds.

---

python/pyproject.toml
python/test/unit/language/test_core.py

This PR https://github.com/openai/triton/pull/2555 disabled `W503` (means line breaks can now occur before a binary operator). 
The change surprisingly didn't take any effect nor required any style changes in `triton` main `pre-commit` stage. But our `triton-shared` [pipeline run](https://github.com/microsoft/triton-shared/actions/runs/6710459100/job/18236352821) (see `Check pre-commit` stage) picked this up correctly and complained about formatting issues. I'm not entirely sure what could be the cause for such difference, but if we also disable `W503` in `pyproject.toml` then the rule is picked up correctly.

[BUILD] Disable W503 in pyproject.toml

---

.pre-commit-config.yaml
python/pyproject.toml
python/test/unit/language/test_core.py
python/triton/runtime/__init__.py

[FRONTEND] Enable ruff linter instead of flake8.
This fixes a few issues automatically, and also flagged two issues to
fix manually in test_core.py: We had two duplicate function names!  One
of these function bodies was a duplicate, so I deleted it.  The other
function body was not a duplicate, so I gave it a new name.
AIUI all of these errors should have been picked up by flake8.  I'm
confused why it wasn't working.  Anyway this is working, and it's faster
than flake8, so it seems like an improvement in all dimensions.

Enable ruff linter instead of flake8

---

python/test/unit/language/test_core.py
python/triton/compiler/code_generator.py

This implements the ternary operator in Triton for dynamic values, fixing https://github.com/openai/triton/issues/1989.
I did not take the approach discussed in https://github.com/openai/triton/pull/2100 b/c I wasn't sure how to implement it.
I implemented the ternary by following `visit_if_scf` as closely as possible. This resulted in a bit of code duplication, so let me know if you want me to extract out common methods, etc.
Note: This PR is not ready to merge, there are at least 2 TODOs left, and I want to add an additional test. I'm opening it, since I think it makes sense to get feedback on the general approach before writing anymore code.
I ran tests locally, and I (think) I didn't spot any regressions. Hard to be sure, because the Triton tests don't all pass by default on my …

[FRONTEND] Implement ternary operator for dynamic values

---

lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp

This was a workaround for a bug exposed in test_core when generating ext_load in NVPTX. The backend bug seems fixed in latest LLVM upgrade so removing the workaround.

[BACKEND] Remove workaround for NVPTX bug after LLVM upgrade

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
python/triton/compiler/compiler.py
python/tutorials/06-fused-attention.py
test/TritonGPU/loop-pipeline-hopper.mlir

This allow pipelining when a load is used by multiple dot in a loop.
Relax the condition to pipeline dot operands for mma v3 case. This improves performance for the bwd pass from 260TF to 275TF. However this expose a performance problem due to the wmma pipelining as ptxas will now fall back to serial wgmma. A follow up PR will fix a bug in how we emit wgmma_wait during pipelining and will bring performance to 335TF

[OPTIMIZATION] Enable pipelining for bwd flash attention

---

include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td
lib/Conversion/TritonGPUToLLVM/DotOpToLLVM.cpp
lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
lib/Dialect/TritonNvidiaGPU/IR/Ops.cpp
lib/Dialect/TritonNvidiaGPU/Transforms/WSPipeline.cpp
test/TritonGPU/loop-pipeline-hopper.mlir

Patch based on @donproc findings and suggested optimization.
Emitting multiple wait op may confuse ptxas and cause it to fallback to a conservative mode.

[BACKEND] Prevent emitting multiple dot_wait after pipelinied loop

---

lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.cpp
test/Conversion/tritongpu_to_llvm_hopper.mlir

Implementing fix described here:
https://github.com/openai/triton/issues/2586#issuecomment-1791413591.
When there is a splat->shared, we get the following unreachable:
```
getElemsPerThread is not supported for shared layout
UNREACHABLE executed at lib/Dialect/TritonGPU/IR/Dialect.cpp:830!
```
This can happen on H100s when you splat a scalar to a dot op as described in https://github.com/openai/triton/issues/2586.
Decompose the splat->shared to splat->blocked->shared.

[BACKEND] Decompose splat to shared memory

---

python/test/unit/language/test_core.py
python/triton/compiler/code_generator.py

Reverting part of [this](https://github.com/openai/triton/pull/2496) PR, due to [this](https://github.com/openai/triton/issues/2617) issue

[FRONTEND] Reverting constexpr propagation on assignment.

---

lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/WGMMA.cpp
python/test/unit/language/test_core.py

The existing workaround was causing a crash in matmul tutorial on h100 and was causing performance regression on flash attention backward.

[BACKEND] Better workaround for ptxas bug

---

python/triton/language/core.py

Fixes https://github.com/openai/triton/issues/2628
TLDR is `frame.f_back` can be `None` if `frame` is the topmost frame. This happens when compile is called from child processes started with the `spawn` method

[FRONTEND] Fix device_assert AttributeError

---

python/triton/common/build.py

Depending on the setup, sometimes it's much easier to explicitly specify the libcuda source instead of having ldconfig look it up. I was debating between using CUDA_HOME or other more commonly used env setups, but made it extremely explicit for the PR -- happy to update to any other env / mechanism. Thanks!

[tiny] Allow explicitly specifying a libcuda source

---

python/test/unit/runtime/test_autotuner.py
python/triton/runtime/autotuner.py

- Reduce number of repetitions in the test
- Allow prune by `early_config_prune` without a perf model
- Cover early prune mode and prune by a perf model mode with tests

[FRONTEND] Improve autotuner

---

.pre-commit-config.yaml

Google has merged the custom change we were relying on, so we no longer need to use my branch.
Also I unthinkingly deleted the branch in my repo and broke things for @jsh_20, and anyone else who tried to install our pre-commits in the past two days.  I've restored the branch so people shouldn't hit this issue, but anyway it's better to be on mainline.

Switch yapf pre-commit back to public Google repo.

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
python/tutorials/06-fused-attention.py
test/TritonGPU/loop-pipeline.mlir
test/TritonGPU/matmul.mlir

Improves performance from 129TF to 149TF on backward attention pass on A100.
This relax some pre-condition of pipelining and allow pipelining cases where a load is used in multiple dot ops.

[BACKEND] Enable pipelining for bwd attention pass on A100

---

.github/workflows/wheels.yml
README.md
python/setup.py

This fixes three issues.
1. We had a clbuttic bug [1].  The wheel script was running `sed` over
setup.py and modifying all instances of `version=`.  But really it only
meant to modify the `version=` inside the setup() call.
Fixed this by using explicit envvars.
2. The job would OOM during build, because the builder "only" has 32GB of RAM.  I limited parallelism to 4 jobs, and now it seems to work consistently.
3. The builder was running out of disk space due to stale docker containers.  AFAICT cibuildwheel normally deletes the container, but it doesn't if e.g. it crashes or OOMs.  Now we delete all the docker containers at the beginning of the build step.
The build step of the nightly build job now completes. 
https://github.com/openai/triton/actions/runs/6857343607.  The full job doesn't …

Attempt to fix nightly wheel build.

---

lib/Dialect/TritonNvidiaGPU/Transforms/RewriteTensorPointer.cpp
test/TritonGPU/rewrite-tensor-pointer2.mlir

<git-pr-chain>
[BACKEND] Fix layouts in nvgpu RewriteTensorPointer.
This pass was creating invalid IR.  In particular, it would create an
rank-N tensor with a rank-M layout, where N != M.
It "happened to work" because a later pass (probably remove layout
conversions?) was fixing it up.
Example of invalid IR: https://github.com/openai/triton/pull/2622#issuecomment-1803139094
This was caught by an IR-verifier rule I'm working on that specifically
checks that the rank of a layout matches that of its tensor.
1. 👉 #2634 👈 **YOU ARE HERE**
1. #2660
1. #2622

[BACKEND] Fix layouts in nvgpu RewriteTensorPointer.

---

include/triton/Dialect/Triton/IR/TritonOps.td
lib/Dialect/Triton/IR/Ops.cpp
test/Conversion/tritongpu_to_llvm.mlir
test/Triton/verify-make-range.mlir

<git-pr-chain>
Add verifier for MakeRangeOp.
Checks that the op returns a 1D tensor of i32s.
I also removed "TODO: should have ConstantLike as a trait" from the op.
AFAICT, ConstantLike should only be used for ops that we *always* want
to fold.  But we only want to fold MakeRangeOp when it's "small", in the
current implementation 1 element.  If I mark the op as ConstantLike, it
seems to get unconditionally folded, and fold() must always succeed
(otherwise MLIR asserts).
1. 👉 #2660 👈 **YOU ARE HERE**
1. #2622

Add verifier for MakeRangeOp.

---

.github/workflows/compare-artifacts.yml
.github/workflows/documentation.yml
.github/workflows/integration-tests.yml
.github/workflows/llvm-build.yml
.github/workflows/test-backends.yml
.github/workflows/torch-inductor-tests.yml
.github/workflows/wheels.yml

I was hogging the H100 machine today with a build that ran forever.  As
penance, I've added timeouts to all our actions.  I set the timeouts to
be roughly 2x as long as a job normally takes.

Add timeouts to github actions.

---

lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp

We incorrectly used the op source instead of adaptor in conversion to LLVM

[BACKEND] Fix conversion bug for ConvertLayout

---

lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
test/TritonGPU/combine.mlir

Improve the workaround to not insert ops between loop and wait op. The long term fix is not trivial and this will allow us to have things working in the meantime.

[BACKEND] Prevent inserting convert layout between loop and wait op

---

include/triton/Dialect/TritonGPU/IR/Attributes.h
include/triton/Dialect/TritonGPU/IR/CMakeLists.txt
include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
include/triton/Dialect/TritonGPU/IR/TritonGPUInterfaces.h
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMMAv1.cpp
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMMAv2.cpp
lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/MMAv1.cpp
lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/MMAv2.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/OptimizeThreadLocality.cpp
lib/Dialect/TritonNvidiaGPU/Transforms/RewriteTensorPointer.cpp

This PR is for [Generalize TritonGPU dialect](https://github.com/openai/triton/issues/2639)
1.Add TritonGPU_AttrTrait, DistributedEncodingTrait and MmaEncodingTrait as the interface for other vendor to extend. 2.Move the NV special API like: MMAv1 and MMAv2 to MmaEncodingAttr from the DotOpEncodingAttr. Generalize the DotOpEncoding.

[BACKEND] To generalize TritonGPU dialect for GPU of different vendors

---

include/triton/Dialect/TritonGPU/IR/Dialect.h
lib/Analysis/Alias.cpp
lib/Analysis/Allocation.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/IR/Traits.cpp
lib/Dialect/TritonGPU/Transforms/Prefetch.cpp
lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
lib/Dialect/TritonNvidiaGPU/IR/Traits.cpp
lib/Dialect/TritonNvidiaGPU/Transforms/FenceInsertion.cpp
test/TritonGPU/canonicalize.mlir

In `TritonGPU` phase, under `CanonicalizeConvertFromConvert` pattern, `cvt(view) -> cvt` always runs as long as the `view` is consider as inexpensive, regardless of the encodings of the operand/result.
In `TritonGPUToLLVM` phase, `ViewOp` is converted to unpacking and packing operations, which requires the element type to match between unpacking and packing. However, different encodings might use different element types, which makes it unsafe for `view` to change encoding unconditionally.

Fixes a bug in `ConvertLayoutOp` canonicalization patterns.

---

include/triton/Dialect/Triton/IR/Traits.h
include/triton/Dialect/Triton/IR/TritonInterfaces.td
include/triton/Dialect/Triton/IR/TritonOps.td
include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td
include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.cpp
lib/Dialect/Triton/IR/Traits.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonNvidiaGPU/Transforms/WSMaterialization.cpp
python/src/triton.cc
python/triton/compiler/compiler.py
test/Analysis/test-alias.mlir
test/Analysis/test-allocation.mlir
test/Analysis/test-membar.mlir
test/Conversion/tritongpu_to_llvm.mlir
test/TritonGPU/canonicalize.mlir
test/TritonGPU/combine.mlir
test/TritonGPU/loop-pipeline.mlir
test/TritonGPU/prefetch.mlir
test/TritonGPU/verify-blocked-layout.mlir

<git-pr-chain>
1. Add verifier for triton_gpu.blocked layout.
Checks that:
- The rank of the layout matches the rank of the tensor it's applied to.
- The tensor's threads-per-warp, warps-per-cta, and ctas-per-cga all
match the module.
- The layout's rank is self-consistent.
- The layout's `order` and `CTAOrder` fields are permutations of
0..(rank-1).
Unfortunately it seems we cannot unittest the verifiers on the
attributes themselves.  When one of these verifiers fails, we get an
assert() failure. :shrug:
Many lit tests ran afoul of this verifier.  I fixed them manually.  In
looking through them, I suspect many tests still contain invalid slice
layouts, which are not being verified in this PR.
1. Add back broken tests in combine.mlir.
1. Fix combine.mlir tests.
I somewhat arbitrariliy …

Add verifier for triton_gpu.blocked layout.

---

lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp
test/TritonGPU/dot-operands.mlir

Summary: Fix https://github.com/openai/triton/issues/2655 When there is a Select Op after a Load Op, the type of the operands for the Select Op will be different, we can't use the same newCvtTy for all the operands when creating ConvertLayoutOp.

[OPTIMIZER] Fix MoveOpAfterLayoutConversion to bail out when there is a Select Op

---

.github/workflows/documentation.yml

5m does not seem sufficient; jobs sometimes are timing out, e.g.
https://github.com/openai/triton/actions/runs/6998821726/job/19037291030.
Increase to 20m.

Increase documentation workflow timeout.

---

lib/Dialect/TritonGPU/Transforms/Utility.cpp
test/TritonGPU/combine.mlir

Suppose we have a loop which yields an operand which lives outside the
loop, i.e. is loop-invariant.  Moreover, suppose the same operand in
iter_args is never used.
%init = ...
%x = ...
%y = for iter_args(%unused = %init) {
yield %x
}
return %y
Previously, we would declare that operand 0 of the yield is "dead" and
replace it with `yield %init`.  This is obviously not correct.
The way this happened was:
- ForOpDeadArgElimination iterates over the forOp's results, in this
case just [%y].
- We notice that %y is used, so it's not dead.  We call markLive(%x),
where %x is the yielded value that corresponds to %y.
- %x is not defined in the loop body, so markLive skips it.
- Therefore at the end of the function, operand 0 of the yield is
considered dead.  We change it to `yield %init`, so it can …

[BACKEND] Fix bug in ForOpDeadArgElimination.

---

include/triton/Dialect/NVGPU/IR/NVGPUOps.td
include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td
lib/Conversion/NVGPUToLLVM/NVGPUToLLVMPass.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMBase.h
lib/Dialect/TritonNvidiaGPU/Transforms/PlanCTA.cpp
lib/Dialect/TritonNvidiaGPU/Transforms/WSFeasibilityChecking.cpp
lib/Dialect/TritonNvidiaGPU/Transforms/WSMaterialization.cpp
lib/Target/LLVMIR/LLVMIRTranslation.cpp
python/test/unit/hopper/test_persistent_warp_specialized_gemm.py
python/triton/language/core.py
python/triton/runtime/backends/cuda.c
python/triton/runtime/driver.py

- Improve the logics of determining splitM&splitN
- Add necessary support for persistent kernels with NUM_CTAS>1
- Add canonocal warp id query operation to help cse and licm before nvgpu2llvm pass.
- Add warning info for fallback of warp specialized kernels

[Hopper] Update CGA->CTA tiling heuristic and add support for persistent kernels to improve performance of warp specialized kernels with NUM_CTAS>1

---

docs/python-api/triton.language.rst
python/triton/language/core.py

It's not an iterator.  :)
Also minor fix to grammar in docs.

[DOCS] Don't include multiple_of under `Iterators`.

---

lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
test/TritonGPU/combine.mlir

There is a corner case that may cause some use of extf source to be incorrectly replaced when hoisting extf op.
Instead we should only map the use of extf we are replacing with the new convert layout op.

[BACKEND] Fix hoisting of convert on top of extf

---

python/triton/language/core.py

This affects how the docs are rendered into HTML.

Fix whitespace in rst docs.

---

include/triton/Dialect/NVGPU/IR/NVGPUOps.td
lib/Conversion/NVGPUToLLVM/NVGPUToLLVMPass.cpp
lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/WGMMA.cpp
test/NVGPU/test_wgmma.mlir

Avoid using extra op and long sequence of inline ptx to create descriptor that is mostly constant.
Also add the base address late to expose more oportuinity for LICM since the base address is usually the only changing part in matmul loop.

[BACKEND] Refactor wgmma descriptor creation

---

.github/workflows/llvm-build.yml

See also https://github.com/wkpark/triton/actions/runs/7043295043 (downloadable artifacts found at the bottom of the page)

[BUILD] Enable llvm-build for windows

---

lib/Dialect/Triton/Transforms/Combine.td
python/test/unit/language/test_line_info.py

If not specified, MLIR will by default generate a fused location combining the locations of the inputs, which may confuse ptxas to yield weird line mapping that maps `mma` to two different lines.
e.g.,  before this commit
```
//## File "/home/keren/code/triton/python/test/unit/language/test_line_info.py", line 69
/*06c0*/                   PRMT R29, R18, 0x654, R37 ;
/*06d0*/                   IMMA.16832.S8.S8.SAT R4, R8.ROW, R6.COL, R12 ;
//## File "/home/keren/code/triton/python/test/unit/language/test_line_info.py", line 72
/*06e0*/                   STL.64 [R1], R26 ;
//## File "/home/keren/code/triton/python/test/unit/language/test_line_info.py", line 67
/*06f0*/                   IADD3 R37, P0, R1, c[0x0][0x20], RZ ;
/*0700*/                   IMAD.X R36, RZ, RZ, c[0x0][0x24], P0 ; …
```

[LINEINFO] Specify explicit locations when ops are combined

---

lib/Dialect/TritonGPU/Transforms/Utility.cpp
test/TritonGPU/combine.mlir

The yield operand might live outside the loop, e.g.
```
%init = ...
%x = ...
%y = for iter_args(%unused = %init) {
yield %x
}
```
When %init is the same as %x; in this case, we can still mark the operand as dead.

[TRANSFORM] Fix a special case in ForOpDeadArgElimination

---

lib/Analysis/AxisInfo.cpp
test/Analysis/test-alignment.mlir

We should use the rank of the underlying tensor to get the correct propagation.

[BACKEND] Handle correctly the rank of ptr of tensor in axis info

---

python/test/unit/hopper/test_persistent_warp_specialized_gemm.py
python/triton/compiler/backends/cuda.py
python/triton/compiler/code_generator.py
python/triton/compiler/compiler.py
python/triton/runtime/driver.py
python/triton/runtime/jit.py
python/triton/tools/compile.py

remove unused symbols and move driver functions to appropriate namespace

[FRONTEND] clean-up runtime/jit.py

---

python/test/unit/operators/test_matmul.py
python/triton/ops/__init__.py
python/triton/ops/matmul.py

In this PR we are simplifying matmul test without changing the behavior.
It's the first PR from splitting https://github.com/openai/triton/pull/2718. Follow ups will be adding the `output_dtype` parameter and adding the bf16, int8 matmul test.
Basically:
- I clean/refactor files a bit.
- rename `dot_out_dtype` to `acc_dtype` because it was confusing for me
- I added `supported_acc_dtypes` for the allowed types in relation of the types of the operands a and b.

Make matmul test easier to understand 

---

python/triton/language/core.py

Make "return a dummy dtype" the Official Workaround for inline asm that
doesn't want to return anything.
Per the decision in
https://github.com/openai/triton/pull/2761#issuecomment-1841898134.

[FRONTEND] Update inline_asm_elementwise comment.

---

python/triton/compiler/__init__.py

Undefined symbols removed:
- `get_arch_default_num_warps`
- `get_arch_default_num_stages`
@ptillet

Fix for #2752 - Removing undefined symbols

---

lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/WGMMA.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp
python/test/unit/language/test_core.py

Enable a shortcut from the output of MMA to the input operand A for another MMA operation for bfloat16
Issue: https://github.com/openai/triton/issues/2745

Enable mma shortcut for the first operand in dot op for bfloat16 on H100

---

python/test/unit/operators/test_matmul.py
python/triton/ops/matmul.py

In this PR we are allowing to manually set acc_dtype and output_dtype in matmul test.
They are:
- `acc_dtype`: So users of the test class can specify the type used internally in the dot, and not the one set by default given the two types. There are several restrictions for these types anyway.
- `output_dtype`: The return type of the matmul. I included a few tests in the case of making a dot with two float16.
I also had to modify test_matmul to use a small range of values to prevent numerical issues. In the case of testing with two `float16` and `acc_dtype` `float16`, since I can't force torch to use `float16` internally (it uses `float32`), I was having precision issues when comparing the results with triton.

[TESTS] Allow user defined output_dtype and acc_dtype in matmul tests

---

python/test/unit/hopper/test_persistent_warp_specialized_gemm.py
python/triton/runtime/backends/cuda.c
python/triton/runtime/driver.py

This is needed for CUDA 11 support, which we'd like to have in the PyTorch 2.2 release.
Original commit message:
In case cuda 11 drivers are still used on some systems, we shouldn't call TMA and block cluster related functions directly. Instead, we can dynamically lookup the handles to avoid compatibility issues.

Cherry-pick "[RUNTIME] Implement dynamic loading with defineGetFunctionHandle for CUDA version compatibility (#2771)"

---

python/triton/runtime/jit.py

We want to skip hashing any called functions that are defined by triton itself, but some users put their kernels in directories named "triton", which confuses this check.  Since apparently triton is sometimes installed as a submodule (really?) we try to figure out the "root" name of the triton module and look for that instead.

When computing cache keys, be more strict about checkint the module name

---

python/triton/ops/matmul_perf_model.py

By reading the current clock, our analytical calculations can vary while we're evaluating different configs.  It turns out the choice of config is very sensitive to the clock, such that a slight throttling can make us reject very good configs, in favor of very bad ones.
A reproducer can be found here:
https://gist.github.com/bertmaher/8ff5e9631666846fff55d81326cacb4d
```
$ python thermal_throttle.py
chosen config BLOCK_M: 128, BLOCK_N: 256, BLOCK_K: 32, SPLIT_K: 1, num_warps: 8, num_ctas: 1, num_stages: 3, enable_warp_specialization: False, enable_persistent: False
tflops/s: 107.92460196062149
$ python thermal_throttle.py --preheat
chosen config BLOCK_M: 32, BLOCK_N: 32, BLOCK_K: 32, SPLIT_K: 1, num_warps: 2, num_ctas: 1, num_stages: 6, enable_warp_specialization: False, …
```

Use max clock for analytical calculations of peak flops

---

include/triton/Dialect/Triton/IR/TritonAttrDefs.td
include/triton/Dialect/Triton/IR/TritonOps.td
lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.cpp
lib/Dialect/Triton/IR/Ops.cpp
python/src/triton.cc
python/test/unit/language/test_core.py
python/triton/language/core.py
python/triton/language/semantic.py
test/Conversion/tritongpu_to_llvm_hopper.mlir

* Adding an optional `fp_downcast_rounding` argument to `tensor.to()` method. It defaults to `None`, as rounding is not required for anything than downcasting operations. When downcasting without specifying this argument, it defaults to `rtne` which is the existing default behavior.
* All f32->f16 conversions with RTNE rounding go through `arith::TruncFOp` as they were, while RTZ versions go through `triton::FpToFpOp` which is intended to handle all custom fp conversions (not only fp8)

Adding RTZ rounding mode for f32->f16, f32->bf16 and f32->f8e5 conversions

---

python/test/unit/language/test_conversions.py

Integrating @apgoucher's work for testing floating point conversions in triton. Small additions from me include support for different rounding modes.
Second attempt, using triton types this time.
Co-authored-by: apgoucher [apgoucher@openai.com](mailto:apgoucher@openai.com)

Conversion tests implementation

---

python/test/unit/language/test_block_pointer.py
python/triton/language/semantic.py

This makes tl.store with block pointer match the behavior of the ptr case and implicitly cast the value to the type pointer.

[FRONTEND] Allow implicit cast in tl.store with block pointer

---

lib/Dialect/TritonNvidiaGPU/Transforms/RewriteTensorPointer.cpp
test/TritonGPU/rewrite-tensor-pointer.mlir

Prevent generating invalid IR by making sure we don't create padding value when the load is not masked.

[BACKEND] Fix invalid IR generated in RewriteTensorPointer pass

---

python/triton/compiler/backends/cuda.py

When annotated with ".target sm_80, debug" in a ptx file, `ptxas` is not able to apply compiler optimizations.
To validate, adding "-O3" to the compilation command would report conflicts between the "debug" constraints and the optimization flag.
To fix the problem, this PR converts `.target sm_<arch>, debug`  to `.target sm_<arch>` before applying ptxas.

[BACKEND] Hotfix for perf regression

---

python/tutorials/05-layer-norm.py

👋  There's currently a (minor) issue in the LN tutorial where if M is smaller than GROUP_SIZE_M parts of _dw/_db will contain uninitialised memory which is later summed into the final dw/db.

Resolve uninitialized memory access when M< GROUP_SIZE_M in LN tutorial

---

lib/Dialect/TritonNvidiaGPU/Transforms/WSPipeline.cpp

Disable async launch dots when numstage == 1

[Hopper] Fix hang issue for warp specialized kernel when numstage=1

---

python/triton/ops/matmul_perf_model.py

By reading the current clock, our analytical calculations can vary while we're evaluating different configs. It turns out the choice of config is very sensitive to the clock, such that a slight throttling can make us reject very good configs, in favor of very bad ones.
A reproducer can be found here:
https://gist.github.com/bertmaher/8ff5e9631666846fff55d81326cacb4d
```
$ python thermal_throttle.py
chosen config BLOCK_M: 128, BLOCK_N: 256, BLOCK_K: 32, SPLIT_K: 1, num_warps: 8, num_ctas: 1, num_stages: 3, enable_warp_specialization: False, enable_persistent: False
tflops/s: 107.92460196062149
$ python thermal_throttle.py --preheat
chosen config BLOCK_M: 32, BLOCK_N: 32, BLOCK_K: 32, SPLIT_K: 1, num_warps: 2, num_ctas: 1, num_stages: 6, enable_warp_specialization: False, enable_persistent: …
```

[Release-2.2.x] Use max clock for analytical calculations of peak flops

---

lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.cpp
lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
test/TritonGPU/accelerate-matmul.mlir

Do decomposition of non native dot op right after mma layout assignment. This will allow following pass to potentially clean up some conversions and avoid generating bad convert layout ops.

[BACKEND] Move dot op decomposition early to allow better clean

---

bin/CMakeLists.txt

Meet building error
```
ld.lld: error: undefined symbol: llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>::AnalysisManager()
>>> referenced by triton-llvm-opt.cpp:47 (/home/triton/work/triton/bin/triton-llvm-opt.cpp:47)
>>>               bin/CMakeFiles/triton-llvm-opt.dir/triton-llvm-opt.cpp.o:(std::_Function_handler<llvm::Error (llvm::Module*), (anonymous namespace)::makeOptimizingPipeline()::$_0>::_M_invoke(std::_Any_data const&, llvm::Module*&&))
ld.lld: error: undefined symbol: llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>::AnalysisManager()
>>> referenced by triton-llvm-opt.cpp:49 (/home/triton/work/triton/bin/triton-llvm-opt.cpp:49)
```

[BUILD] Add missing LLVMAnalysis library for triton-llvm-opt target

---

python/triton/common/build.py

If `libcuda.so` can not be found using `ldconfig -P`, check if `LD_LIBRARY_PATH` environment variable is defined and search for it there
Test plan: https://colab.research.google.com/drive/16Kd88j-nFS4iMI-UfJS5rukH42L6UuyP?usp=sharing
Fixes https://github.com/openai/triton/issues/2507

[FRONTEND] Handle `LD_LIBRARY_PATH`

---

python/triton/common/build.py

cherry-pick into release/2.2.x branch.
If `libcuda.so` can not be found using `ldconfig -P`, check if `LD_LIBRARY_PATH` environment variable is defined and search for it there
Test plan:
https://colab.research.google.com/drive/16Kd88j-nFS4iMI-UfJS5rukH42L6UuyP?usp=sharing
Fixes https://github.com/openai/triton/issues/2507

[FRONTEND] Handle LD_LIBRARY_PATH

---

bin/CMakeLists.txt
bin/triton-lsp.cpp

Solves https://github.com/openai/triton/issues/2898 .
With the [MLIR VS Code](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-mlir) plugin, here is how the result looks like:
Further efforts require managing the file extension to be `.mlir` rather than `.ttlr`.

[UTILS] add triton language server for IDE highlight

---

python/triton/runtime/jit.py

Try to fix https://github.com/openai/triton/issues/2899 .

[Python Code] Update jit.py to delay the import of InterpretedFunction to avoid being dependent on numpy by default

---

CMakeLists.txt

Cmake requires that you either specify PUBLIC/PRIVATE keyword in target_link_libraries, or you don't. Mixing two methods is not supported.

[FRONTEND][BUILD] Fix for the build issue coming from mixing two methods of defining target link libraries

---

.github/workflows/test-backends.yml

This PR https://github.com/openai/triton/pull/2887 removes `third_party/triton_shared`, and the corresponding test should be removed. Otherwise it will fail (and now it indeed fail) all the CI tests.

[CI] remove shared middle-layer lit tests as the plugin does not exist now

---

lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
test/Conversion/tritongpu_to_llvm_hopper.mlir

On Hopper when storing mma tensor to shared memory we can use stmatrix to reduce the number of store intrusctions. This give a very small improvements to the epilogue for fp16 output. It will later be combined with cp.async.bulked to improve performance further.

[BACKEND] Use stmatrix when converting mma layout to distributed

---

lib/Dialect/TritonGPU/IR/Dialect.cpp

`DistributedEncodingTrait::getCTAOrder()` returns a SmallVector by value, which is deleted as soon as it is assigned to `ref`. `ref` then becomes a dangling reference.
To prevent that, we now use a vector instead of an array reference.

Fix use-after-free detected by address sanitizer

---

include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td
lib/Analysis/Alias.cpp
lib/Analysis/Allocation.cpp
lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/TritonGPUToLLVMPass.cpp
lib/Dialect/TritonNvidiaGPU/Transforms/MaterializeLoadStore.cpp
test/Conversion/tritongpu_to_llvm_hopper.mlir
test/TritonGPU/fence-inserstion.mlir

Also update AMD submodule to remove dependency between AMD and this op.
Changing the name will allow us to add support for StoreAsync with consistent naming

[NFC][BACKEND] Rename nvidia_gpu StoreAsyncOp to StoreAsyncTMAOp

---

bin/CMakeLists.txt
bin/RegisterTritonDialects.h
python/src/ir.cc
python/test/unit/language/test_reproducer.py
test/Triton/reproducer.mlir

This PR is a work in progress and depends on https://github.com/llvm/llvm-project/pull/75421 so only can be landed after Triton bumps it's llvm hash.
This PR makes it possible to dump an MLIR reproducer when setting the env var TRITON_REPRODUCER_PATH to some mlir file path (`export TRITON_REPRODUCER_PATH=$(PWD)/triton-reproducer.mlir`). The reproducer can then be run using triton-opt like so: `triton-opt  --run-reproducer ./triton-reproducer.mlir`
TritonLLVMIR has been added as a link dependency for the bin triton tools because that is needed for properly registering the enable-line-info pass (which gets inserted into the pass pipeline if `export TRITON_DISABLE_LINE_INFO=1` is not set). The enable-line-info pass is also added for registration in RegisterTritonDialects.h as well. …

[BACKEND] Adding optional environment variable for dumping reproducer mlir files

---

python/triton/testing.py

This PR adds the `save_precision` argument to `benchmark.run()`, and makes its default value 6 (which is somewhat arbitrary, but seems reasonable).  Right now it is not user configurable, and has an unusually low default of `.1f`.
**Context:**
I was using the benchmarking capability, and found that the CSV which was being generated had unacceptably low precision (`.1f`).  This was after I had run a long-ish benchmarking session, and I was surprised that many of my benchmarks had an inference time of 0.
For the benchmarks I am performing, I need a higher degree of precision.  I do not think the downsides of higher precision, namely larger file sizes for the CSVs is relevant compared to the downsides of losing data.  By making the value configurable, this gives us the best of both worlds.

[TESTING] Added precision option to benchmark CSV data saving

---

.github/workflows/test-backends.yml
.gitmodules
python/test/unit/language/test_core.py

this pr
* updates the amd backend submodule from https://github.com/ptillet/triton.git to https://github.com/ROCmSoftwarePlatform/triton
* the main change is
*  https://github.com/ROCmSoftwarePlatform/triton/pull/464
* it fixed an issue where most of the unit tests broke on the ptillet branch
* there are also some changes for testing on our fork
* https://github.com/ROCmSoftwarePlatform/triton/pull/455
* https://github.com/ROCmSoftwarePlatform/triton/pull/458
* this pr also enables [the AMD backend tests](https://github.com/openai/triton/actions/runs/7548608469/job/20551027680) on this repo
* finally we are skipping some unit tests that broke with the new backend. We are working on fixing them.

[AMD] Update submodule

---

.github/workflows/integration-tests.yml

Our tests are currently failing on CI, but we can't tell what's going
wrong, because the test process times out before pytest prints its
summary of what failed.
Pass -vvv so we get incremental output of each test that runs.

[CI] Pass -vvv to pytest.

---

include/triton/Tools/Sys/GetEnv.hpp
python/src/llvm.cc
third_party/nvidia/backend/compiler.py

Adding an environment variable named `DISABLE_LLVM_OPT` to disable llvm optimizations. The pre-optimized LLVM IR dump is useful for investigating LLVM issues.

Disabling LLVM optimization under a switch

---

include/triton/Dialect/Triton/IR/TritonOps.td
lib/Dialect/Triton/IR/Ops.cpp
test/Triton/canonicalize.mlir

<git-pr-chain>
[IR] Fix two bugs in ExpandDimsOp::canonicalize.
* Don't assume that the input to broadcast is a tensor.  Scalars are
also allowed (although IMO they should not be, because that's
what splat is for).
* Don't drop the encoding.  Previously, if we matched this pattern after
adding encodings, we'd drop the encoding on the new canonicalized
operation, resulting in invalid IR.
1. 👉 #2975 👈 **YOU ARE HERE**

[IR] Fix two bugs in ExpandDimsOp::canonicalize.

---

third_party/nvidia/backend/driver.py

When there's more than 2 backends, checking hip isn't present isn't enough to decide whether the nvidia backend should be active.

Update CudaDriver is_active condition

---

python/setup.py

Summary: Follow the examples in https://github.com/openai/triton/pull/2982 and make sure backends symlinks are created properly when installing with bdist_wheel

[SETUP] Fix a missing backend issue when running bdist_wheel

---

.github/workflows/test-backends.yml
python/test/unit/language/test_core.py
python/triton/language/core.py

* this pr primarly fixes the shift op test for AMD
* the test was bitshifting beyond the bitwidth of the type which causes undefined behavior
* we added a warning in the op but it only works in the case where shifting value is known at compiletime
* minor fix for test_convert1d
* skip new filp_op which is causing the backend test to fail

[AMD] Shift op test and other fixes

---

.github/workflows/test-backends.yml

* this pr adds the ablility to run the AMD backend test with a command `/run-amd-tests`

[AMD] trigger AMD ci jobs with comment

---

.github/workflows/test-backends.yml

* this is a follow up to https://github.com/openai/triton/pull/3003. It does the following
* checks out the pull request when ci jobs starts with a `/run-amd-tests` comment
* limit the comment trigger to AMD jobs only 
* other backend ci jobs follow the default behavior as before. They can be started either manually or when push to main

[AMD] run ci on pull requests

---

lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp

<git-pr-chain>
[IR] Clean up OptimizeDotOperands (NFC)
- Improve variable names
- Tighten up code
- Write comments explaining what the patterns do
I found a number of issues with MoveOpAfterLayoutConversion, but I
left them as TODOs in this PR.
1. 👉 #3021 👈 **YOU ARE HERE**

[IR] Clean up OptimizeDotOperands (NFC)

---

lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp

Minor refactor of helpers to make them more consistent by only propagating when the dst/src encoding can be inferred from the src/dst encoding and handle convert layout explicitly in the forward propagation

[BACKEND][NFC] Minor refactor of inferDstEncoding/inferSrcEncoding

---

include/triton/Dialect/Triton/IR/TritonOps.td
lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
lib/Dialect/Triton/IR/Ops.cpp
test/Triton/invalid.mlir

Fixes a TODO, and lets us improve the error messages we get when you
type an invalid asm op -- now it's a nice compile error instead of a
crash.

Add a verifier for ElementwiseInlineAsmOp.

---

python/test/unit/language/test_core.py

This PR skips test_trans_2d and test_trans_4d unit tests.
These test are not supported on AMD yet.

[AMD] Temporary disable new test_trans_ tests

---

python/test/unit/language/test_core.py
third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp

This PR cleans up some tests and reenables more dot tests

[AMD] Cleanup AccelerateAMDMatmulPass and enable more tests

---

.github/workflows/test-backends.yml
python/test/unit/language/test_core.py

this pr is a follow up to 
- https://github.com/openai/triton/pull/2996
- https://github.com/openai/triton/pull/3005
it does the following
- applies a fix to `test_bin_op_constexpr` with `<<` and `>>` that was applied to `test_shift_op`. It limits the random shifting value to a range between 0 and the bitwidth
- fixes an issue where the logic to checkout the pr code when triggered from a comment was failing. Thank you to @OctoSabercat for suggesting a solution
- to ensure the logic works I have made a toy repo with this logic
- [triggered from main](https://github.com/micmelesse/test_ci/actions/runs/7672726431/job/20913857574)
- uses the `Checkout` step and prints `README.md` in [main](https://github.com/micmelesse/test_ci/blob/main/README.md)
- [triggered from …

[AMD] fix test_bin_op_constexpr failures & checkout pr issue

---

lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp
test/TritonGPU/dot-operands.mlir

Hoisting dot_operand layout through arith.select crashes the compiler due to propagating the layout to the mask input, which is of i1 type. Also hoisting further up the mask's parents will probably be of integer type. The crash happens during ConvertTritonGPUToLLVM pass.
2 examples where the crash happen:
- arith.cmpi -> broadcast -> layout_conv -> arith.select (dot_op layout) -> dot.
In this example the crash would happen due to SharedToDotOperandMMAv2.cpp assuming that the bit-width is at least 8 when computing elemBytes. It also assumes the types are mma-compatible (for Ampere for example mma16816) which don't include int type when doing floating dot.
- arith.cmpi -> layout_conv -> broadcast -> arith.select (dot_op layout) -> dot.
This example requires allowing HoistLayoutConversion to …

Exclude arith.select from hoisting for dot_operand layout

---

python/test/unit/language/test_core.py
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandFMA.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/FMA.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/MFMA.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/ReduceOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/ScanOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/TritonGPUToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/TritonGPUToLLVMBase.h
third_party/amd/lib/TritonAMDGPUToLLVM/TypeConverter.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/TypeConverter.h
third_party/amd/lib/TritonAMDGPUToLLVM/Utility.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/ViewOpToLLVM.cpp

A few commits were added recently that are needed in the AMD backend
- https://github.com/openai/triton/commit/5baa3c1a221a6397769d40acca126d3f1832064e
- https://github.com/openai/triton/commit/7afddce963e9290368b80cf5710d9ae69229a3ed
This PR adds propagates this code to the AMD backend. 
This also includes a small fix to how the moduleOp is retrieved in `commonShflSync`

[AMD] Fix and Enable Scan 2D op test

---

include/triton/Analysis/Utility.h
lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/Utility.cpp
lib/Conversion/TritonGPUToLLVM/Utility.h
lib/Dialect/Triton/IR/Ops.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/Utility.h
unittest/Analysis/UtilityTest.cpp

<git-pr-chain>
[Utility] Improve some utility functions.
- Given `template <typename T> foo(ArrayRef<T>)`, I don't want you to
have to type out `foo(ArrayRef(val))`.  You should be able to call it
as simply `foo(val)`.
Previously I accomplished this by writing overloads like
foo(ArrayRef<unsigned>)
foo(ArrayRef<int>)
but this is verbose, especially when foo takes *two* ArrayRef
arguments.  I figured out a better way to do it, making use of
ArrayRef's CTAD.  It's sort of like concepts, actually...
- Add some additional utilities:
isPermutationOfIota
isConsecutive
join
- Remove reorder() function, in favor of applyPermutation().  It's a bit
more verbose, but I think it gets the point across more clearly, and
it plays well with e.g. inversePermutation().
1. 👉 #3049 👈 **YOU ARE HERE**
1. …

[Utility] Improve some utility functions.

---

lib/Analysis/AxisInfo.cpp
test/Analysis/test-alignment.mlir

1. We didn't handle `eq` and `ne` modifiers properly. If only one of the operand is a constant, we cannot infer the constancy of the result.
2. We can remove the restriction that one of the operand must be all contiguous. 
If operand `a` is constant, operand `b` could be partially contiguous.
Take `gcd` as the greatest common divisor of `a`'s divisibility, `b`'s divisibility, and `b`'s contiguity.
We can divide `b` into segments of length `gcd`.
For each segment, if `a`'s value doesn't fall into it, the constancy would be simply `gcd`.
Otherwise, `a` can only be the start of the segment, and therefore we could check the modifiers to see if we could assign `gcd` as the constancy.

[ANALYSIS] Improve AxisInfo Analysis for `cmpi` ops

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
include/triton/Dialect/TritonGPU/IR/TritonGPUDialect.td
lib/Dialect/Triton/IR/Traits.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
test/Analysis/test-allocation.mlir
test/Analysis/test-membar.mlir
test/Conversion/triton_to_tritongpu.mlir
test/TritonGPU/accelerate-matmul.mlir
test/TritonGPU/coalesce.mlir
test/TritonGPU/combine.mlir
test/TritonGPU/dot-operands.mlir
test/TritonGPU/loop-pipeline-hopper.mlir
test/TritonGPU/loop-pipeline.mlir
test/TritonGPU/optimize-locality.mlir

<git-pr-chain>
[IR] Improvements to CTALayout.
- Ensure all layouts have a nonempty CTALayout.  (Previously, you could
have an empty CTALayout on an op, which would lead to "fun" crashes
inside the compiler.)
- Make CTALayout optional in textual IR.
If a module has only one CTA per CGA, then none of the CTALayout
layout options matter, and we can avoid printing them.
- Add documentation for CTALayout, mostly written by @qliu93.
1. 👉 #3050 👈 **YOU ARE HERE**

[IR] Improvements to CTALayout.

---

lib/Dialect/TritonGPU/Transforms/Utility.cpp
test/TritonGPU/combine.mlir

scanOp currently only supports blocked layout.

[BACKEND] Prevent propagation of unsupported layout to tt.scan

---

third_party/nvidia/backend/compiler.py

Sometime back in https://github.com/openai/triton/pull/1166 the environment variable to set the location of libdevice.10.bc was added.
Recently in the backend cleanup to move more Nvidia specifics to third_party it was lost to the code churn
(https://github.com/openai/triton/pull/2844).
This PR brings it back so that dependent projects that use Triton but place their libdevice file in a different location than the default can continue to work.

[BACKEND] Re-introduce TRITON_LIBDEVICE_PATH envvar to Nvidia backend

---

lib/Dialect/TritonGPU/IR/Dialect.cpp

Another bug from 8e61b7212e7d32c85f448490260c6293d2f1885a.  Sorry :(

Get rid of extra comma in stringified #shared encoding.

---

python/src/llvm.cc

Summary: export LLVM_IR_ENABLE_DUMP=1 run
python vector-add.py | grep "IR Dump"
will show all the IRs after each llvm pass, including llvm passes in optimize_module and translate_to_asm.

[DEBUG] Enable print-after-all with env variable LLVM_IR_ENABLE_DUMP

---

lib/Analysis/Allocation.cpp
test/Conversion/tritongpu_to_llvm.mlir

When convert layout transpose elements we cannot vectorize both loads and stores. Deciding to only vectorize one would cause extra bank conflicts on the non-vectorized one that cause performance slowdown.

[BACKEND] Prevent vectorization in convert_layout transposes

---

python/test/unit/language/test_core.py
python/triton/compiler/code_generator.py

https://github.com/openai/triton/commit/855ac8f02ed98c9ad5c4f4e270c7ef2062062d95 has replaced `semantic.trans` with `semantic.permute` and changed the set of required parameters. 
This updates `CodeGenerator.visit_Attribute` accordingly.

[FRONTEND] Fix code_generator, replace semantic.trans with semantic.permute

---

lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
test/TritonGPU/combine.mlir

See comment in code; if we don't do this, we can miss optimization
opportunities.
While we're here, also some minor NFC cleanups in Dialect.cpp.

[IR] Mark permuting reshapes as layout roots.

---

include/triton/Dialect/Triton/IR/TritonTypes.td
include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td
lib/Dialect/Triton/IR/Ops.cpp
test/Triton/invalid.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/TritonGPUToLLVMPass.cpp

If we tweak how we define TT_Tensor, MLIR can see that it's always a
RankedTensorType.  Then suddenly all our generated functions know this,
and we don't have to cast to RankedTensorType everywhere!!!
This isn't a global cleanup, just a demonstration.
Already found a bug, namely that TritonGPUOps.td defined
InsertSliceAsyncOp's src as PtrLike, but (based on the code) it actually
must be PtrTensor.

[IR] Eliminate need for .cast<RankedTensorType>() in most places.

---

include/triton/Dialect/Triton/IR/TritonOps.td
python/test/unit/language/test_core.py

Fixes https://github.com/openai/triton/issues/2657

Allow associative_scan with different dtypes

---

lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/MMAv2.cpp
lib/Conversion/TritonGPUToLLVM/DotOpToLLVM/WGMMA.cpp
lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
lib/Dialect/Triton/IR/Ops.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
lib/Dialect/TritonGPU/Transforms/Prefetch.cpp
lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp

These are unnecessary now that we've taught tablegen which of our ops
accept RankedTensorType, 70dd60538e73784cf75a190b43f2e80011d22855.
Also get rid of some unnecessary namespace qualifications.

[IR] Get rid of some now-unnecessary cast<RankedTensorType>.

---

third_party/amd/backend/driver.py
third_party/nvidia/backend/driver.py

Triton hooks no longer accept `compiled_kernel` arguments. Instead, `metadata` is passed to include environmental variables, compilation options, and debug flags.

[BACKEND] Fix misnomers 

---

lib/Analysis/Allocation.cpp
lib/Analysis/AxisInfo.cpp
lib/Analysis/Utility.cpp
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/HistogramOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/LoadStoreOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/MakeRangeOpToLLVM.cpp
lib/Dialect/Triton/Transforms/Combine.cpp
lib/Dialect/Triton/Transforms/ReorderBroadcast.cpp
lib/Dialect/Triton/Transforms/RewriteTensorPointer.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp
lib/Dialect/TritonGPU/Transforms/OptimizeThreadLocality.cpp
lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
lib/Dialect/TritonGPU/Transforms/ReorderInstructions.cpp
lib/Dialect/TritonNvidiaGPU/Transforms/PlanCTA.cpp
python/src/ir.cc
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/TritonGPUToLLVM.cpp
third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp
third_party/amd/lib/TritonAMDGPUTransforms/RemoveLayoutConversions.cpp
third_party/amd/lib/TritonAMDGPUTransforms/ReorderInstructions.cpp
third_party/amd/lib/TritonAMDGPUTransforms/StreamPipeline.cpp

- Eliminate mlir:: and triton:: in a few files, starting with the worst
offenders.
- Replace op.getResult().getType() with op.getType().
- Write out some `auto` types to better match MLIR's coding conventions.
The overall goal is to (incrementally) make our code more concise.  We reduce
the 13kloc touched here to 11kloc, for a 1.2x improvement!  (It's a sus metric,
but still.)

NFC cleanups to C++ code.

---

.git-blame-ignore-revs

I've been making some big NFC changes, and these can clog up `git blame`.  Add
a file that lists "uninteresting" revisions.  You can (optionally!) instruct
git to ignore the revs in here during blame.
I got this list of commits by looking through the list of Triton commits that
touch 30+ files.  ChatGPT wrote the following bash script for me.
git log --pretty=format:"%H" --name-only | \
awk -v N="30" '
/^[0-9a-f]{40}$/ {
if (count > N) print hash;
hash=$0; count=0;
}
NF { count++ }
END { if (count > N) print hash }
' | xargs git show --stat

Add .git-blame-ignore-revs.

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp

In the Pipeliner, TMA support required detection if the `InsertSlice` was TMA or non-TMA kind, as for TMA we weren't supposed to insert `AsyncWait`s. Without TMA, we can simplify `minOverHistories` function that does not have to handle special case anymore.

[BACKEND] Simplifying minOverHistories as there is no TMA support

---

python/test/unit/language/test_core.py
third_party/amd/backend/compiler.py

The `has_public_visibility()` check, which does:
`return fn->getVisibility() == llvm::GlobalValue::DefaultVisibility;`
doesn't seem to work in this context. I tried a few other APIs (`getVCallVisibility()`, `llvm::Function::isDeclarationForLinker()`) to get the public function, but those weren't helping.
We already check kernel[0] here and that looks to always be the public function, so we'll just drop this `has_public_visibility()` check.
There was no actual problem with the noinline attribute. The assert there was causing the fail.

[AMD] Fix and enable noinline unit test

---

README.md
include/triton/Dialect/Triton/IR/Dialect.h
include/triton/Dialect/Triton/IR/TritonOps.td
lib/Conversion/TritonGPUToLLVM/ViewOpToLLVM.cpp
lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
lib/Dialect/Triton/IR/Ops.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
python/src/ir.cc
python/test/unit/language/test_core.py
python/triton/language/__init__.py
python/triton/language/core.py
python/triton/language/semantic.py
test/Triton/invalid.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/ViewOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUTransforms/RemoveLayoutConversions.cpp

Also remove experimental_interleave.  This is now equivalent to join + reshape.
The eventual intent is to remove the concat op and instead implement it using join+reshape.
Also add some additional tips to README.

[IR] Implement join and split ops.

---

third_party/amd/backend/compiler.py
third_party/amd/backend/driver.py

-Set up warp size 32 for gfx10/11, 64 for gfx9
-Set attribute warp_size after instantiation to avoid defining by user
-Fix kernel launching hardcode

[AMD][Navi] Set up Warp Size depending on the architecture

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
test/TritonGPU/loop-pipeline.mlir

Non-pipelined loads of distance from the pipelined loads should be scheduled to the same stage that the pipelined loads are. Due to bug in the code they were scheduled to the stage after that, which might have caused performance problems.

[BACKEND] Fixing the stages of loads distance 1

---

include/triton/Tools/Sys/GetEnv.hpp
python/src/ir.cc

This prevents crashes in test_core.py due to too many diagnostics emitted in https://github.com/llvm/llvm-project/pull/78228 It should also speed up compile times, as we can use multithreading, and avoid handling diagnostic messages.

[DEBUG] Only print out diagnostic messages if an environment variable is set

---

.github/workflows/documentation.yml
.github/workflows/integration-tests.yml
.github/workflows/test-backends.yml

Tests run in about 6m on a warm test runner, but
https://github.com/openai/triton/actions/runs/7967953226/job/21751471651?pr=3154
shows that 20m is not enough on a cold runner.  (At least, I *think* that's
the problem here.)
Now that we have auto-restarts of runners, we care more about test runs on
cold runners.

Increase test timeouts to 30m.

---

python/triton/compiler/code_generator.py
python/triton/compiler/compiler.py
python/triton/compiler/errors.py

- Report errors in nested @triton.jit'ed functions properly.
Before, errors would only be reported in the top-level function.  If a nested
function had an error, we'd only point to the top-level call that
transitively leads to the function with the error.
- After fixing the above, tracebacks get unweildy, because you have *multiple*
30+-frame tracebacks for each level of nesting.
But most of these tracebacks are in code_generator.py, which is not relevant
to the error.  It would be like if when regular Python code raised an
exception, we reported not just the stacktrace in Python, but also the trace
of the Python interpreter when it encountered the error!
We now exclude code_generator.py and ast.py, making the stacks much more
manageable.
- Print a newline between the file:line and the …

[FRONTEND] - Three improvements to tracebacks.

---

python/test/unit/language/test_core.py
python/triton/language/semantic.py

* this pr fixs a bug with `atomic-rmw` op where `float64` values are not cast to the appropriate `int64` type.

[FRONTEND] fix atomic_rmw

---

lib/Analysis/Allocation.cpp
python/triton/compiler/compiler.py
test/Analysis/test-allocation.mlir

To be able to write IR tests correctly we need to make sure we skip the optimization associated with the first stage.
This restore the behavior of `compile` before the front end refactoring.

[FRONTEND] Skip optimization of the first stage when compiling from IR

---

python/test/unit/language/test_compile_errors.py
python/test/unit/language/test_core.py
python/triton/compiler/code_generator.py

<git-pr-chain>
[Frontend] More fixes to compilation error reporting.
- Failed tl.static_assert's were generating an extra stackframe; get rid of
this.
- We were not reporting the correct location for errors in unary and binary
ops.
- Nested functions were not handled properly, despite my last attempt.
Now with tests!
1. 👉 #3181 👈 **YOU ARE HERE**
1. #3182

[Frontend] More fixes to compilation error reporting.

---

python/test/unit/language/test_core.py

Support "trans" epilogue for asymmetrical tensors.
Example of crash: M==16, N==64, i.e. z_tri of shape [16, 64]

Fix trans epilogue in test_dot

---

python/test/unit/language/test_core.py
python/triton/language/core.py

<git-pr-chain>
[Frontend] Let tl.expand_dims handle "real" scalars.
It handled 0D tensors, but not e.g. python int's.
1. 👉 #3186 👈 **YOU ARE HERE**
1. #3187

[Frontend] Let tl.expand_dims handle "real" scalars.

---

.github/workflows/documentation.yml
docs/conf.py
docs/python-api/triton.language.rst
python/test/unit/language/test_line_info.py
python/triton/language/core.py
python/triton/language/standard.py

<git-pr-chain>
[Docs] Fix docs build and improve docs.
Docs build fixes:
1. Seems like something changed with Sphinx, so now we need to install
additional packages.  Failing build:
https://github.com/openai/triton/actions/runs/8034012588/job/21945072822
2. Disable grouped-gemm tutorial, which currently hits an assertion in the
compiler. :(
3. Re-enable build for other tutorials, which seem to be working.  There's a
comment about disabling them because they don't work on V100, but the docs
build runs on A100, so I don't expect that should be a problem.
4. Don't fail the build if examples fail to build on non-Linux platforms.
Examples require a GPU, so they won't work on macos.  Letting the build
continue when they fail lets you build the docs on a mac, which is nice for
local changes.
Docs …

[Docs] Fix docs build.

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
test/TritonGPU/loop-pipeline.mlir

When a load has multiple uses in software pipelining they may require different shared layout. Make sure the layout created is compatible with all uses, otherwise skip pipelining the load.

[BACKEND] Prevent creating incompatible shared layouts in pipeliner

---

lib/Dialect/Triton/Transforms/Combine.cpp
lib/Dialect/Triton/Transforms/Combine.td
test/Triton/combine.mlir

Add addptr(addptr(%ptr, %idx0), %idx1) pattern again with constraint which makes sure that both element type of offset should be same.

[OPTIMIZATION] Fix addptr combine pattern

---

include/triton/Tools/Sys/GetEnv.hpp
lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
python/src/ir.cc

This patch uses TRITON_ENABLE_LLVM_DEBUG to enable LLVM's debug flag so that LLVM_DEBUG blocks can be enabled when running the Triton Python runtime.
I did have to add a workaround for getNumWarps for now, but once it is determined why a LLVM_DEBUG block is hitting getNumWarps before num_warps is set it should be dropped.

[DEBUG] Add support for a Triton envvar to enable LLVM's -debug/llvm::DebugFlag

---

python/test/unit/language/test_core.py
python/triton/language/core.py
python/triton/language/standard.py
python/triton/runtime/interpreter.py

<git-pr-chain>
[Frontend] Add member fns on tensor, and let us omit tuples in reshape etc.
Three QoL changes to the Triton language.
1. For most tl.foo functions which take one tensor, add a function tensor.foo
that does the same thing.  For example, instead of `tl.permute(x, (2,1,0))`,
you can write x.permute((2,1,0)).
2. Allow tl.trans to take a list of dimensions, making it a near-synonym for
tl.permute.
3. For functions that take a shape or a list of dims, allow the shape/dims to
be passed as individual args.
This applies to tl.broadcast_to, tl.reshape, tl.permute, tl.reshape, and
tl.trans, and to the equivalent functions on tl.tensor.
Probably the hardest thing about this was making Sphinx generate nice-looking
docs.
All three of these changes make the Triton language closer to torch …

[Frontend] Add tensor.permute(2,1,0) etc.

---

.github/workflows/llvm-build.yml

I'm not able to push LLVM binaries built from this branch to Azure unfortunately, because it relies on branch filtered Entra ID now, allowing only `llvm-head` and `main`. So I'll push it to main and then update the storage from there.

[BUILD] Fix several minor LLVM build issues

---

include/triton/Analysis/AxisInfo.h
include/triton/Analysis/Utility.h
include/triton/Conversion/TritonGPUToLLVM/Utility.h
include/triton/Dialect/Triton/IR/Utility.h
lib/Analysis/Allocation.cpp
lib/Analysis/Utility.cpp
lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
lib/Dialect/Triton/IR/Ops.cpp
lib/Dialect/Triton/IR/Traits.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/Coalesce.cpp
lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
python/src/ir.cc
unittest/Analysis/UtilityTest.cpp
unittest/Dialect/TritonGPU/DialectTest.cpp

This is done to reduce the dependency from Triton IR to TritonGPUAttrDefsIncGen.
This was discussed in https://github.com/openai/triton/pull/3200. I moved more than was strictly needed to drop the `#include triton/Analysis/Utility.h` from Trition IR since I thought the original file had a pretty clear divide between generic functions and ones that require touching Triton's own classes.

Move generic utility functions from Analysis to Triton IR

---

.github/workflows/llvm-build.yml

fixing a simple issue on LLVM workflow runner

[BUILD] Removing x86 target for ubuntu arm64

---

lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
python/src/ir.cc
python/triton/language/__init__.py
python/triton/language/math.py
third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ElementwiseOpToLLVM.cpp

Fma was removed during math refactor, bringing it back to math module.

Adding FMA to triton math

---

test/Conversion/dedup-by-constancy.mlir
test/Conversion/divide-by-0.mlir
test/Conversion/tritongpu_to_llvm.mlir
test/Triton/reproducer.mlir
third_party/amd/include/TritonAMDGPUToLLVM/Passes.h
third_party/amd/include/TritonAMDGPUToLLVM/Passes.td
third_party/amd/lib/TritonAMDGPUToLLVM/TritonGPUToLLVMPass.cpp
third_party/nvidia/include/TritonNVIDIAGPUToLLVM/Passes.h
third_party/nvidia/include/TritonNVIDIAGPUToLLVM/Passes.td
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TritonGPUToLLVM.cpp
third_party/nvidia/triton_nvidia.cc

This PR removes definition and uses of Target enum with NVidia/AMD targets.

Remove Target enum

---

lib/Dialect/Triton/Transforms/Combine.cpp
lib/Dialect/Triton/Transforms/Combine.td
test/Triton/combine.mlir

This reverts commit 6c5c50f0ffafc9fca7613dfd015ecceada4dd04c.
This commit caused a crash in our internal workloads. I'll provide an example of the IR causing the crash shortly.

Revert "[OPTIMIZATION] Fix addptr combine pattern (#3148)"

---

python/src/ir.cc

A user is hitting this with a complex case that I haven't been able to
reproduce or reduce, but anyway it's totally reasonable for us to have a check
here so we raise a nice error back to Python.
While we're here, update the types of exceptions thrown to be more Pythonic,
https://pybind11.readthedocs.io/en/stable/advanced/exceptions.html.

[Frontend] Don't crash if fn.args(idx) is out of range.

---

python/triton/language/core.py

The previous polyfills didn't work because you can't call a `@builtin` function
from another builtin.
Thanks to @apgoucher for pointing this out.

[Frontend] Fix polyfills for _experimental_{split,join}.

---

python/triton/language/math.py

Dirty-ish legalization for fma argument types. It follows what we are doing for other ternary ops (clamp). We deserve better legalization for multi-arg ops, I'll take a look at it as a follow-up.

[FRONTEND] Legalization for fma argument types

---

python/test/backend/test_device_backend.py
python/triton/runtime/build.py

subprocess.check_call throws on failure instead of returning non-zero.
This fallback is required in conda environments, since `CFLAGS` is how the system headers are setup (eg, `CFLAGS=... -I $CONDA_PREFIX/include`). In particular, python <3.9 has a `#include <crypt.h>` line in `Python.h`: https://github.com/python/cpython/commit/9626ac8b7421aa5fc04a30359521d24f40105141
An alternative is to respect CFLAGS in the build for the setuptools avoidance.

fix: correctly fallback to setuptools

---

include/triton/Dialect/TritonGPU/Transforms/Utility.h
lib/Dialect/TritonGPU/Transforms/OptimizeThreadLocality.cpp
lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
test/TritonGPU/combine.mlir
third_party/amd/lib/TritonAMDGPUTransforms/RemoveLayoutConversions.cpp

This allows the remove layout conversion pass to rematerialize values through an `scf.if` block. This is done by adding new return types to the if block and letting the `IfOp` canonicalization patterns remove any resulting dead code. 
Testing this also uncovered a quirk in the `ForOp` rematerialization process. It calls `replaceForOpWithNewSignature` which eagerly replaces all users of the pre-exiting for-loop. However, we can get the case like:
```mlir
%1 = scf.for ... {
%2 = scf.for ... {
scf.yield ...
}
scf.yield %2
}
```
The inner for loop `%2` is rewritten before the outer yield, so when `rewriteSlice` checks `slice.count(operand)` it can never match because the operand has been updated to the new loop, but the slice still has the old loop result.
I fix this by delaying the …

[OPTIMIZER] Allow rematerializing through scf.if ops

---

lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
test/TritonGPU/combine.mlir

Layout can be converted into tt.assert to avoid unnecessary layout conversion.

[BACKEND] Add support for propagating convert op to tt.assert

---

.github/workflows/test-backends.yml
python/test/unit/language/test_core.py

This PR enables AMD backend CI, specifically
- The self-hosted node is MI210 (gfx90a)
- The runner brings up a docker on the server and run tests
- Add "TODO" to tests that are WIP
- Fixed some tests related to warpSize and layout

[AMD] Enable AMD backend CI

---

python/test/backend/test_device_backend.py
python/triton/compiler/compiler.py
python/triton/runtime/cache.py
python/triton/runtime/jit.py
third_party/amd/backend/compiler.py
third_party/amd/backend/driver.py
third_party/nvidia/backend/driver.py

It's a better hash than e.g. md5, and using it consistently makes it more likely to avoid cargo-cult uses of md5.  See discussion on https://github.com/openai/triton/pull/3224

[easy][nfc] Consistently use sha256 for hashing

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
lib/Dialect/TritonGPU/IR/Dialect.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/MFMA.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/TypeConverter.cpp

This PR updates SharedToDotOperandMFMA.cpp and MFMA.cpp.
- SharedToDotOperandMFMA.cpp is up to date with triton-mlir as of today, which includes changes until https://github.com/ROCm/triton/pull/482
- Fixed issue with opaque pointers
- Fixed API for `getMFMAElemsPerInstrForOperands` and `getMFMARepForOperands`
- MFMA.cpp is synced with triton-mlir@6bb04d, which includes changes until https://github.com/ROCm/triton/pull/469
Note to @binarman: changes in other files from https://github.com/ROCm/triton/pull/469 are not included in this PR. We can bring up the support for mfma 64x4 and 4x64 later.

[AMD] Refactor SharedToDotOperandMFMA 

---

python/triton/runtime/cache.py

Adds a redis-based one as an initial implementation, but it should be straightforward to extend with more impls.

[FRONTEND] Add support for using remote cache managers

---

lib/Conversion/TritonGPUToLLVM/ScanOpToLLVM.cpp
python/test/unit/language/test_core.py

more than one numScanBlocks along scan axis (#3017)

[Backend] Fix bug in ScanOp lowerring when one thread and one warp but more than one numScanBlocks along scan axis (#3017)

---

lib/Dialect/TritonGPU/IR/Dialect.cpp
test/Conversion/amd/tritongpu_wmma_dot_to_llvm.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/CMakeLists.txt
third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/WMMA.cpp

-Add WMMA conversion logic for dot operation
-Fix helper hunctions for WMMA layout
-Add lit test for WMMA dot operation conversion

[AMD][Navi31] Convert WMMA dot op to LLVM

---

lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
python/test/unit/language/test_core.py

When sizePerThread is larger than tensor's shape, only unique elements will be stored in smemShape when accumulatePartialReductions, so when read out reduced values, we need to modulo srcShape/smemShape to get replicated elements for oversize elements.

[BACKEND] Fix bug in loadReductionAndPackResult (#3013)

---

third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.cpp

Resolves the TODO left in `matchReduxKind` from #3263, which broke reductions on GPUs without Redux operations.

[BACKEND] Fix reductions on pre-sm80 GPUs

---

python/src/llvm.cc

`StandardInstrumentations::registerCallbacks` reads the llvm registered options, so in order for it to enable printing, the `print-after-all` needs to be already set when it is being invoked.
This fixes the lack of IR dumps for optimization passes.

[DEBUG] Fix `LLVM_IR_ENABLE_DUMP` for LLVMIR optimization passes

---

test/Conversion/triton_ops.mlir
test/TritonGPU/accelerate-matmul.mlir
test/TritonGPU/loop-pipeline.mlir
test/lit.cfg.py

It's quite easy to unexpectedly use a match from a different CHECK-LABEL in a lit test, which is likely not what the author intended.
Prevent this from happening by invoking FileCheck with variable scopes enabled (and fix the failures detected this way). This also makes the file check use in Triton consistent with upstream MLIR.

[TEST] Use LABEL scopes in lit tests

---

python/triton/language/core.py

Add an environment variable that allows us to use ieee f32 by default. This makes it simpler to check for precision problems.

[FRONTEND] Add an environment variable to control TF32 default

---

python/triton/runtime/__init__.py

https://github.com/openai/triton/pull/2934 added `RedisRemoteCacheBackend` but did not add the symbol to `__init__.py`. Let's also add there so that we can refer to it via full path instead of having to `from ... import RedisRemoteCacheBackend`.

[Easy][FRONTEND] Expose `RedisRemoteCacheBackend` in `__init__.py`

---

test/Conversion/amd/fp_to_fp.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp

This commit fixes failure in python/tutorials/03-matrix-multiplication.py for FMA cases,
also fixes mixed dot for FMA cases.
Tested on Navi31

[AMD] ElementwiseOpToLLVM: Do not convert types if they are equal

---

python/test/backend/test_device_backend.py
python/triton/runtime/build.py

This reverts commit 375fee087e408d645a9c30bb1424f16fd148d97c.
Reverting this PR as it causes error in our internal tests. It reaches this error in `python3.11/site-packages/setuptools/_distutils/core.py `
```
def run_commands(dist):
"""Given a Distribution object run all the commands,
raising ``SystemExit`` errors in the case of failure.
This function assumes that either ``sys.argv`` or ``dist.script_args``
is already set accordingly.
"""
try:
dist.run_commands()
except KeyboardInterrupt:
raise SystemExit("interrupted")
except OSError as exc:
if DEBUG: 
sys.stderr.write("error: {}\n".format(exc))
raise 
else:
raise SystemExit("error: {}".format(exc))
except (DistutilsError, CCompilerError) as msg:
if DEBUG:
raise
else:
raise SystemExit("error: " + str(msg))
return dist
```

Revert "fix: correctly fallback to setuptools (#3219)"

---

lib/Dialect/TritonGPU/Transforms/ReorderInstructions.cpp
test/TritonGPU/reorder-instructions.mlir

The user_begin() function cannot guarantee a definite order, so when there are multiple users for convert_layout, it might be sunk between two users, resulting in a dominance error.

[BACKEND] do not sink conver_layout for multi users

---

include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td
lib/Analysis/AxisInfo.cpp
lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
lib/Dialect/TritonGPU/Transforms/Coalesce.cpp
lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
test/TritonGPU/loop-pipeline-hopper.mlir
test/TritonGPU/pipeline-hopper-remove-wait.mlir

<git-pr-chain>
[Backend] Clean up MMAv3 part of MatmulLoopPipeline.
The MMAv3 pipelining code needed some love and comments.
There are some minor functional changes in here.  For example, the old
code relied on a particular order of op.users(), and I'm not convinced
it was correct.
Once you unravel the code, what it needs to do is a lot less complicated
than what it was doing.  Indeed, despite the fact that I added a ton of
comments, it's roughly the same length as before.
The changes to the test are cosmetic.  Previously we emitted tt.dot and
assumed it would eventually becdome ttng.dot_async in a later pass (or
at least during codegen).  Now we explicitly convert some tt.dot's to
ttng.dot_async so we can have an explicit wait and thread the results
through.
There's more cleanup that can …

[Backend] Clean up MMAv3 part of MatmulLoopPipeline.

---

python/test/unit/runtime/test_jit.py
python/triton/runtime/jit.py

This PR adds pre run hooks to JITFunction in order for user to do analysis/error detection or any other pre hook operation they would like to do prior to execution of the kernel.
For PyTorch, the specific use case we have is being able to provide better error messages when a FakeTensor (our tracing tensors) are passed into the a Triton Kernel.
In addition our use case, these pre run hooks should provide generic functionality to users.

[Easy][FRONTEND] Add pre run hooks to JITFunction

---

lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
test/TritonGPU/combine.mlir

<git-pr-chain>
[NVGPU] Propagate layouts through DotWait ops.
https://github.com/openai/triton/pull/3301 converts some tt.dot ops into
ttng.dot_async+wait.  We need to propagate layouts through these the same way
we propagate them through regular tt.dot ops.  Otherwise...well, eventually we
create unsupported IR, trying to convert from blocked to MMAv3 dot-operand
layout, which we canot do.
This fixes an OAI-internal test.
1. 👉 #3324 👈 **YOU ARE HERE**
1. #3316

[NVGPU] Propagate layouts through DotWait ops.

---

lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
test/TritonGPU/combine.mlir

<git-pr-chain>
[NVGPU] Allow layout propagation through TransOp.
This is a revival of https://github.com/openai/triton/pull/3097, which I now
realize I need for some int4 matmul work I'm doing.
Previously this caused performance problems / running out of shmem on A100, but
it seems that https://github.com/openai/triton/pull/3261 (or perhaps something
else) fixed it.  This now has no performance delta on our internal performance
tests on A100 or H100.
1. 👉 #3316 👈 **YOU ARE HERE**

[Backend] Allow layout propagation through TransOp.

---

python/test/unit/language/test_core.py
third_party/amd/backend/compiler.py
third_party/amd/lib/TritonAMDGPUTransforms/RemoveLayoutConversions.cpp

This change is to fix the unit test `test_locality` for the AMD backend.

[AMD] fix unit test `test_locality`

---

.github/workflows/compare-artifacts.yml
.github/workflows/documentation.yml
.github/workflows/integration-tests.yml
.github/workflows/test-backends.yml
.github/workflows/torch-inductor-tests.yml
.github/workflows/wheels.yml

[OpenSSF Scorecard Report](https://securityscorecards.dev/viewer/?uri=github.com/openai/triton) shows zero score for "Token-Permissions", which can be easily fixed by adding a top level permissions to the existing workflows.
This report can be also generated locally with
```
$ docker run --rm gcr.io/openssf/scorecard:stable  \
--show-details --checks Token-Permissions --repo=openai/triton --format json | jq -r '.checks[].details[]' | grep -e '^Warn:'
Warn: no topLevel permission defined: .github/workflows/compare-artifacts.yml:1
Warn: no topLevel permission defined: .github/workflows/documentation.yml:1
Warn: no topLevel permission defined: .github/workflows/integration-tests.yml:1
Warn: no topLevel permission defined: .github/workflows/test-backends.yml:1
Warn: no topLevel permission …
```

Add top level permissions to the workflows

---

third_party/amd/backend/compiler.py

On Fedora the ROCm linker is the system linker, /opt/rocm does not exist. So check if the linker exists before passing it back. Add a fallback to the sytem linker.
Raise an exception if neither are found.

Add a fallback to the location of the ROCm linker

---

python/triton/compiler/compiler.py

I'm trying to maximize the number of (distributed) cache hits I'm getting on kernels, and dictionary iteration order seems like a possible randomizing factor.
I don't think there's *technically* a problem here, because Python now guarantees insertion ordering and I don't see a way the ordering here could vary, since they're argument-index ordered.
But it also feels like a reasonable sort of belt-and-suspenders protection against this being randomized, and this sort should be low-cost since it's just done at kernel compile time.

[frontend] Sort signature/constants when hashing

---

python/test/unit/conftest.py
python/test/unit/language/conftest.py
python/test/unit/operators/conftest.py

When trying to run the unit tests from the top level directory, was getting:
```
ValueError: option names {'--device'} already added
```
since this was defined in both `operators` and `language` tests.

[tests] Move --device argument up a level

---

python/test/unit/language/test_core.py

The latest main branch seems working fine for all cases in test_reduce, so turn on them for amd backend.

[AMD] turn on reduce tests with `argmax/argmin`

---

lib/Dialect/Triton/Transforms/Combine.cpp
lib/Dialect/Triton/Transforms/Combine.td
test/Triton/combine.mlir

Add addptr(addptr(%ptr, %idx0), %idx1) pattern again with constraint which makes sure that both element type of offset should be same.

Recommit [OPTIMIZATION] Fix addptr combine pattern (#3148)

---

python/test/unit/language/test_core.py

This reverts commit 9a83624e49413c67ac6584623bedaaed929ad02a.

Revert "turn on reduce tests with `argmax/argmin` (#3333)"

---

python/triton/runtime/cache.py

https://github.com/openai/triton/pull/2934 have changed some of the FileCacheManager methods into a private interface, while `_has_file` method is still being used by the Override functionality. Exposing the method again. (An alternative is to call private `_has_file` from the override, which would be OK too, since it is debug only thing).

[DEBUG] Override fix - Turn FileCacheManager.has_file back into an interface method

---

include/triton/Conversion/TritonGPUToLLVM/Utility.h
lib/Conversion/TritonGPUToLLVM/Utility.cpp

-Add emitWmmaOffsetForCTA
-Add emitBaseIndexForWmmaLayout
-Add emitOffsetForWmmaLayout
-Fix some helper methods

[AMD][Navi31] Add emitIndices logic for WMMA layout

---

third_party/amd/lib/TritonAMDGPUToLLVM/CMakeLists.txt
unittest/CMakeLists.txt
unittest/Conversion/TritonGPUToLLVM/CMakeLists.txt
unittest/Conversion/TritonGPUToLLVM/DumpLayout.cpp
unittest/Conversion/TritonGPUToLLVM/EmitIndicesTest.cpp

Allows to test emmitting indices from different layouts. Valid also for AMD target device.

[AMD]Enable EmitIndicesTest

---

lib/Conversion/TritonGPUToLLVM/TypeConverter.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
python/test/unit/language/test_core.py
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/MFMA.cpp

This PR is to fix the unit test `test_dot_without_load` by by changing dot op from `vector<vector<type>>` to `vector<type>`, so the constantOp can be converted to mfma `dot_op` with existing lowering code.

[AMD backend] Fix unit test `test_dot_without_load` 

---

include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td
include/triton/Dialect/TritonNvidiaGPU/IR/TritonNvidiaGPUOps.td
lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
test/TritonGPU/loop-pipeline-hopper.mlir

<git-pr-chain>
1. [NVGPU] Allow async dots in an additional case.
Previously a dot could be async if the only use of its value from iteration i-1
was an async or sync dot.
We relax this to allow arbitrary uses of the value from iteration i-1 so long
as those uses come after a synchronous dot.  This better matches the original
code before I rewrote it in https://github.com/openai/triton/pull/3097.
To make this easier to reason about, I convert all MMAv3 dots to dot_async.
The synchronous dots just have a wait immediately after.
While we're here, we also thread dependencies properly through dot_wait ops.
Now that all MMAv3 dots are dot_async, this is a lot easier to do.
1. Add memdesc's as operands of the dot_wait instruction.
1. Fix crash that was happening in RemoveLayoutConversions.
1. 👉 …

[NVGPU] Allow async dots in an additional case.

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
test/TritonGPU/loop-pipeline-hopper.mlir

<git-pr-chain>
Relax check for synchronous dots in matmul loop pipeliner.
Previously we were checking for a sync dot at the beginning or end of the loop;
if we found one, we could omit the final async wait in the loop.  But actually
this is too strict: A sync dot *anywhere* inside the loop is sufficient (sketch
of the proof in the code).
1. 👉 #3353 👈 **YOU ARE HERE**

Relax check for synchronous dots in matmul loop pipeliner.

---

python/test/unit/language/test_core.py
python/triton/language/core.py

While working on adding `triton.language.dtype` to PyTorch, I discovered that `triton.language.float32` emits `triton.language.fp32` which I assume is done in order to be consistent with numpy and torch; however, this results in an un-evaluable expression as `triton.language.fp32` does not correspond to anything.
I thought of adding aliases to float32 as fp32 but that meant duplicating bunch of dtypes. This solution seems cleaner.

[FRONTEND] Fix triton.language.dtype repr

---

python/triton/language/standard.py

When running with assertions (`TRITON_DEBUG=1`), there was a compilation issue in the min and max functions in standard.py. Previously,  to check whether the datatype was an integer, a function call to `input.dtype.is_integer_type()` was made, but this function call does not exist as a part of dtype. This has now been replaced with the appropriate function call `input.dtype.is_int()`.

[FRONTEND] Fix assertion containing incorrect function call in min/max

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp

There are two tests that failed under AddressSanitizer:
* test/TritonGPU/loop-pipeline.mlir
* python/test/regression/test_functional_regressions.py
with an error: 
```
==8475==ERROR: AddressSanitizer: heap-use-after-free on address 0x50c000bd0be0 at pc 0x557b03278847 bp 0x7ffd69b2c4a0 sp 0x7ffd69b2c498
READ of size 8 at 0x50c000bd0be0 thread T0
#0 0x557b03278846 in getNextOperandUsingThisValue [third_party/llvm/llvm-project/mlir/include/mlir/IR/UseDefLists.h:43](https://cs.corp.google.com/piper///depot/google3/third_party/llvm/llvm-project/mlir/include/mlir/IR/UseDefLists.h?l=43&ws=aliia/3018&snapshot=215):58
#1 0x557b03278846 in operator++ [third_party/llvm/llvm-project/mlir/include/mlir/IR/UseDefLists.h:322](https://cs.corp.google.com/piper///depot/google3/third_party/llvm/llvm-project/m …
```

[BACKEND] Fix heap-use-after-free in createAsyncCopy

---

lib/Conversion/TritonGPUToLLVM/TypeConverter.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
python/test/unit/language/test_core.py
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/MFMA.cpp

This PR is actually fix the regression in the reverted PR: https://github.com/openai/triton/pull/3338, which caused a regression for the test `test_masked_load_shared_memory`. The reason is for type used in packing dot_op for bfloat16. We  should use the type `i16` for `bf16` when packing dot_op for mfma.  
This time I ran all the tests in `test_core.py` locally, and all work fine.

[AMD backend] fix `test_dot_without_load`

---

bin/RegisterTritonDialects.h
lib/Conversion/TritonGPUToLLVM/TypeConverter.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
test/Conversion/amd/decompose-unsupported-conversions.mlir
test/Conversion/amd/tritongpu_wmma_dot_to_llvm.mlir
third_party/amd/lib/TritonAMDGPUToLLVM/DecomposeUnsupportedConversions.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/WMMA.cpp
third_party/amd/lib/TritonAMDGPUTransforms/RemoveLayoutConversions.cpp

TypeConverter:
-Support WMMA dot operand type;
DecomposeUnsupportedAMDConversions:
-Replace `wmma -> dot_op` with `wmma -> blocked -> dot_op`; RmoveLayoutConversion:
-Do not propagate WMMA layout if it is not a chain dot case.

[AMD][Navi31] WMMA related fixes

---

python/triton/compiler/compiler.py
third_party/amd/backend/compiler.py
third_party/amd/backend/driver.py
third_party/nvidia/backend/compiler.py
third_party/nvidia/backend/driver.py

Previously, we could compile Triton kernels on non-gpu hosts. However, it started to fail recently once we switch to the latest version of Triton.
In our workload, we have a way to compile all relevant Triton kernels beforehand (AOT), and then launch/run these kernels on gpu hosts, so kind of build and run are two separate processes.
This PR is trying to make Triton compile work again on non-gpu hosts.

Make compile-only work on non-gpu hosts

---

lib/Analysis/Utility.cpp
lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp
lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp
python/test/unit/language/test_core.py
test/Conversion/tritongpu_to_llvm_hopper.mlir
test/TritonGPU/dot-operands.mlir
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ConvertLayoutOpToLLVM.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/Utility.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/Utility.h

Implement layout conversion invented by Ganesh Bikshandi and Jay Shah described in the following paper:
https://research.colfax-intl.com/wp-content/uploads/2023/12/colfax-flashattention.pdf
This will allow us generating full fp8 attention kernel by having chain of dots in fp8 without going through shared memory.

[BACKEND] Add support converting MMAV3 accumulator layout to fp8 dot_operand

---

third_party/nvidia/backend/compiler.py

Calling subprocess is slow sometimes (depends on python version, size of CUDA context, etc.) and _path_to_binary doesn't change.

[frontend] Cache _path_to_binary

---

python/test/unit/language/test_core.py
third_party/amd/backend/compiler.py
third_party/amd/backend/driver.py

Fix AMD backend failure caused by https://github.com/openai/triton/pull/3362 and https://github.com/openai/triton/pull/3370

[AMD] Make target a list instead of a tuple for HIP backend

---

python/test/unit/language/test_core.py
third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp

Here we map PreciseSqrtOp and PreciseDivOp to LLVM instructions for the AMD backend.
These "Precise" ops are currently defined as round-to-nearest-even which is the default rounding mode in the LLVM instructions for the AMD backend. 
Alternatively we could call into the AMD `ocml.bc`. This works for sqrt but `__ocml_div_{rm}_f32` is currently unimplemented.
If further "Precise" math ops are added with different rounding modes or otherwise don't map to LLVM ops, we can revisit this.

[AMD] Map PreciseSqrtOp and PreciseDivFOp to LLVM instructions

---

python/triton/runtime/cache.py

Adds a redis-based one as an initial implementation, but it should be straightforward to extend with more impls.

[CherryPick] [FRONTEND] Add support for using remote cache managers (#2934)

---

lib/Dialect/TritonGPU/Transforms/Utility.cpp
test/TritonGPU/combine.mlir
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ConvertLayoutOpToLLVM.cpp

Add some extra heuristic to the convert layout backward propagation to consider convet_layout that are known to be no-ops. In this kind of cases we want to make sure we don't assume that folding it with another convert would be free.

[BACKEND] Tweak convert_layout backward propagation

---

include/triton/Analysis/Utility.h
lib/Analysis/Utility.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
test/TritonGPU/amd/accelerate-amd-matmul-wmma.mlir
third_party/amd/backend/compiler.py
third_party/amd/include/TritonAMDGPUTransforms/Passes.h
third_party/amd/include/TritonAMDGPUTransforms/Passes.td
third_party/amd/lib/TritonAMDGPUTransforms/AccelerateAMDMatmul.cpp
third_party/amd/python/triton_amd.cc

-Transform dot
-Transform dot operands to required layouts
-Support datatypes convertion
-add lit test for AccelerateAAMDMatmul pass for WMMA case

[AMD][Navi31] Support WMMA transformations in AccelerateAMDMatmul pass

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
test/TritonGPU/loop-pipeline-hopper.mlir

<git-pr-chain>
Don't crash in MatmulLoopPipeline in the presence of an early return.
1. 👉 #3393 👈 **YOU ARE HERE**

Don't crash in MatmulLoopPipeline in the presence of an early return.

---

python/triton/runtime/jit.py

Add more helpful error message on the rare events of function signature mismatch with cached kernel.

[CACHE] Adding RuntimeError on signature mismatch with the cached function

---

python/test/unit/runtime/test_cache.py
python/triton/runtime/jit.py

Adding helpful error message on mismatching name during preloading a kernel.

[CACHE] Verify that when preloading a kernel its name matches what we have in specialization_data

---

lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
test/TritonGPU/accelerate-matmul.mlir

- The core dump is caused by mixing layout of different ranks when determining mma layout by looking at def-use slice. I simply filter out mma layouts of different rank in the slice.

[BACKEND] Fix compiling time core dump in AccelerateMatmul (#3382)

---

python/triton/runtime/interpreter.py

I've debugged some kernels with `TRITON_INTERPRET=1` and discovered missing typecasts in the interpreter backend for `int32` and `bool`/`int1`.

[INTERPRETER] adding missing typecasts

---

lib/Conversion/TritonGPUToLLVM/ScanOpToLLVM.cpp
python/test/unit/language/test_core.py

When inling scan-op's body bb, tt.yield's result could have an illegal type, so we should use the remapped value from ConversionPatternRewriter, rather than the value itself.

[BACKEND] Add support for bf16 in scan op

---

python/setup.py

We have experienced intermittent forever hangs during triton installation, specifically when downloading the nvidia dependencies. This developer has found that `request.urlopen` not having a set timeout can potentially lead to this issue: https://github.com/mesonbuild/meson/issues/4087
I have set the timeout to 5 minutes which should be enough to download each individual dependency while also preventing the forever hang.

[SETUP] Set max timeout when downloading nvidia dependencies

---

.github/workflows/integration-tests.yml
python/setup.py
python/src/triton.cc
python/test/unit/hopper/test_persistent_warp_specialized_gemm.py
python/test/unit/runtime/test_bindings.py
python/test/unit/runtime/test_subproc.py
python/test/unit/tools/test_aot.py
python/triton/__init__.py
python/triton/common/backend.py
python/triton/compiler/__init__.py
python/triton/compiler/backends/cuda.py
python/triton/compiler/code_generator.py
python/triton/compiler/compiler.py
python/triton/compiler/utils.py
python/triton/language/core.py
python/triton/language/extra/cuda.py
python/triton/language/semantic.py
python/triton/runtime/driver.py
python/triton/runtime/jit.py
python/triton/tools/compile.py

Cherry pick a few PRs to make PyTorch 2.3 work with Triton 2.2.x . Also this makes sure some python bindings needed by user defined triton kernel exists in the triton branch.

cherry pick #2701, #2736, #2756, #3191

---

lib/Conversion/TritonToTritonGPU/TritonToTritonGPUPass.cpp
python/src/ir.cc
python/test/unit/language/test_core.py
python/triton/language/semantic.py
python/triton/runtime/interpreter.py
third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ElementwiseOpToLLVM.cpp

This reverts commit 235d5d86bdcc3031000bd51daff18f5b9f34c98d.
This causes a failure in one of our internal test (it seems like this change the numeric precision even though I don't think it should). It will be investigated next week as OAI is on a break this week. 
Sorry for the inconvenience.

Revert "[FRONTEND] Emit NegFOp for unary minus operator (#3394)"

---

lib/Analysis/Membar.cpp

We found an issue when linking `TritonAnalysis` without first fully building triton.
```
In file included from ~/triton/lib/Analysis/Membar.cpp:6:
In file included from ~/triton/include/triton/Conversion/TritonGPUToLLVM/Utility.h:8:
~/triton/include/triton/Dialect/NVGPU/IR/Dialect.h:32:10: fatal error: 'triton/Dialect/NVGPU/IR/Dialect.h.inc' file not found
#include "triton/Dialect/NVGPU/IR/Dialect.h.inc"
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
ninja: build stopped: subcommand failed.
```
So `Membar.cpp` includes `Utility.h` from `TritonGPUToLLVM` which in turns needs `NVGPU` and its tablegen files. `TritonAnalysis`'s cmake doesn't list neither `TritonGPUToLLVM` nor `NVGPU` as dependencies, hence the linker error. Technically we should have `TritonAnalysis` …

[BUILD] Fix linker error in Membar.cpp

---

python/test/unit/language/test_core.py
python/triton/language/core.py
python/triton/runtime/interpreter.py

This is a simple and general version that matches the underlying triton implementation when reducing within a single thread. `numpy.func` is not used because its reduce op only supports binary inputs, but triton's `combine_fn` can have arbitrary number of inputs.

[INTERPRETER] Support generic reduce

---

python/test/unit/language/test_core.py
python/triton/language/math.py
python/triton/runtime/interpreter.py

`binary_op_type_legalization` does broadcasting, we just need to use the results.
I also improve `_test_binary` to check both the left and right argument can be broadcasted.

[FRONTEND] Fix broadcasting of `tl.math.div_rn`

---

lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
test/Conversion/tritongpu_to_llvm.mlir

As is, is_int_min_poison isn't getting set correctly; the LLVM constant being passed to the builder is being interpreted as a C++ bool, so it's always true. Set it correctly and add mlir test to ensure this.

Correctly set is_int_min_poison

---

python/triton/runtime/interpreter.py

Getting errors with these in the latest version of triton.

[Interpreter] Add exp and log to the interpreter.

---

python/triton/runtime/jit.py

There is a bug introduced in latest triton code where AttributeError is getting thrown if kernel function args has same name as global variable. See the below example for more clarity
```
import torch
import triton
@triton.jit
def kernel(
out, adj, num_rows,
WG_SIZE : tl.constexpr
):
zero_indices = tl.zeros((WG_SIZE,), dtype=adj.dtype.element_ty)
if __name__ == '__main__':
device = torch.device('cuda')
num_rows, num_indices, heads = 16, 16, 16, 4
adj = torch.zeros(num_rows + 1, dtype=torch.int32, device=device)
out = torch.empty((num_indices,heads), dtype=e_src.dtype, device=e_src.device)
launch_grid = (num_rows * heads // 256,)
kernel[launch_grid](out, adj, num_rows, 256) 
```
Error it throws something like below
`    return getattr(lhs, node.attr) …

[FRONTEND] Fix arg name conflict bug

---

include/triton/Dialect/TritonGPU/IR/TritonGPUAttrDefs.td
test/TritonGPU/reduce-data-duplication.mlir
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMMAv2.cpp

Currently swizzling is disabled for the transposed operand when vecWidth != kWidth. I also believe the old comment there is no longer correct as this will also disable cases other than int8. I modified the condition such that it allows swizzling to happen in all scenarios, but with a restriction on perPhase such that it conforms to the assumptions made in SharedToDotOperandMMAv2.cpp.

Modify disabled mixed-precision mma swizzling to be enabled with different configuration

---

.github/workflows/documentation.yml
.github/workflows/integration-tests.yml
.github/workflows/test-backends.yml
.github/workflows/torch-inductor-tests.yml

1. Resolve GH actions warnings due using deprecated versions of checkout, v2 (node.js 12; EOL) and v3 (node.js 16; EOL), by upgrading to checkout v4 (node.js 20).
2. add -f (force) flag to rm cmds bc it always completes successfully (return 0) even if file/folder is not found. Without the force flag, "file not found" error causes the cmd to return 1 (fail) when the objective was technically met.

[CI] Update Github actions to node.js 20

---

third_party/amd/backend/compiler.py

Resolves an error observed as part of inductor support bring-up for AMD when running unit test's via PyTorch's run_test.py due to the addition of `-bb` flag in pytest which forbids string/bytes comparisons.
```
File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_inductor/triton_heuristics.py", line 208, in precompile
compiled_binary, launcher = self._precompile_config(
File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/_inductor/triton_heuristics.py", line 365, in _precompile_config
binary = triton.compile(*compile_args, **compile_kwargs)
File "/root/triton/python/triton/compiler/compiler.py", line 229, in compile
key = f"{triton_key()}-{src.hash()}-{backend.hash()}-{options.hash()}-{str(sorted(get_env_vars().items()))}"
File …
```

[AMD] Treat version as string avoid string/bytes comparison

---

third_party/nvidia/backend/compiler.py

A call to split() on a file path string results in a truncated path if the latter has spaces in it, then the target binary is not found. It was an unnecessary step.

Handle file paths with spaces (#3305)

---

python/triton/language/core.py

Without `f` it's not an f-string and as such the error message would just be a literal passed to exception constructor, which is not very helpful.

[core] Fix error message formatting.

---

include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td
include/triton/Dialect/TritonGPU/IR/TritonGPUTypes.td

Small clean up to keep Ops and Types in separated .td files.
Also remove `TTG_Type` because there is an identical class  `TTG_TypeDef` in `TritonGPUTypes.td`.

[BACKEND] Move TTG_AsyncToken type to TritonGPUTypes.td

---

python/triton/language/core.py

This change ensures that `name` cannot get out of sync with `__str__` and `__repr__`, since all of the fields are technically mutable and can be changed at any time. This also comes with a potential performance benefit of computing this f-string only once instead of computing it on each `__str__`/`__repr__` invocation.
It would be even better to also to make this class immutable, but it's a separate story.

[FRONTEND] Keep pointer_type name and its __str__ in-sync.

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/OuterLoopPipeline.cpp
test/TritonGPU/loop-pipeline.mlir

We cannot hoist a triton_gpu.local_alloc op if its init argument is declared in the same scope as local_alloc's containing for loop.

[Backend] hoist ttg.local_alloc only if its valid

---

python/triton/language/semantic.py

Using generators makes code a bit more pythonic and more efficient, although efficiency is not a big deal here due to low cardinality.

[FRONTEND][NFC] Simplify reduction function.

---

python/triton/language/semantic.py

It's more idiomatic and efficient.

[FRONTEND][NFC] Use list comprehension to build new_args.

---

python/triton/compiler/compiler.py

Fixes bug introduced in: https://github.com/openai/triton/commit/1ecbc27a8169cd47ef81e061789f05b913a740b1
Reproed via dynamo with a manually updated pin 
`test_functions.py` running test `test_triton_kernel_various_args` creates constants of ` {'RANDOM_SIZE': 0, 5: 128}` which breaks this hashing.
A simple step to first string the keys, and then sort works.
cc: @bertmaher @jlebar @ptillet

Fix mixed key constants breaking sorted_constants for hashing ASTSource

---

include/triton/Dialect/Triton/IR/Utility.h
lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
python/test/unit/language/test_core.py
test/TritonGPU/loop-pipeline.mlir

<git-pr-chain>
Allow pipelining more loads indirectly used by a dot.
Previously if a load was used indirectly by a dot but there were non-unary
operations between the load and the dot, we couldn't pipeline it.
Also clean up some TODOs.
1. 👉 #3415 👈 **YOU ARE HERE**

Allow pipelining loads that don't feed directly into tl.dot.

---

include/triton/Conversion/TritonGPUToLLVM/Utility.h
test/Conversion/tritongpu_to_llvm.mlir

The type bf16 is converted to i16, but extract_element still uses bf16. Use i16 in extract_element to fix the error: invalid element type in packLLEElements

Fix mismatching type when lowering Local Load of bf16

---

.gitignore

It's common to use different suffixes to the build
directory when directly compilng from C++.

Ignore build-*/ directories

---

lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/ElementwiseOpToLLVM.cpp

This commit moves duplicated elementwise op conversion patterns from the third-party amd and nvidia directories into the common conversion library.

[backend] NFC: unify common elementwise op conversion patterns

---

include/triton/Conversion/TritonGPUToLLVM/Utility.h
lib/Conversion/TritonGPUToLLVM/ReduceOpToLLVM.cpp
lib/Dialect/TritonGPU/IR/Dialect.cpp
python/test/unit/language/test_core.py

Added few fixes to enable reduction with different input layouts (including Mfma). Disabled test_dot for now as my fixes exposed a bug that needs to be addressed (requires relying on `layout.getOrder()` to determine the order of threads/warps rather than assumptions).

[TESTING][BACKEND] Enable test_reduce_layouts on hip

---

include/triton/Dialect/TritonGPU/IR/TritonGPUOps.td
lib/Dialect/TritonGPU/IR/Dialect.cpp
lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
test/Analysis/test-membar.mlir
test/TritonGPU/loop-pipeline.mlir

<git-pr-chain>
[IR] Add verifier for MemDescSubviewOp.
Also fix MatmulLoopPipeline, which was generating invalid code because it
assumed 2D tensors.
1. 👉 #3473 👈 **YOU ARE HERE**

[IR] Add verifier for MemDescSubviewOp.

---

python/test/unit/language/test_core.py

This test has some accuracy issue. Please see:
https://github.com/openai/triton/issues/3474

[test] disable test_atomic_cas for rocm

---

python/test/unit/hopper/test_gemm_fusion.py
python/triton/language/core.py
python/triton/language/semantic.py
python/triton/language/standard.py

Emit a deprecation message for tl.view.
As stated in https://github.com/openai/triton/issues/2829, the reorder bit in tl.view is confusing, make it explicit in tl.reshape.

Add a parameter reorder to existing tl.reshape

---

third_party/amd/backend/compiler.py

Code object v4 will be deprecated:
https://rocm.docs.amd.com/en/docs-5.0.2/CHANGELOG.html#warning-compiler-generated-code-object-version-4-deprecation
Code object v5 is the default version in the LLVM pinned by Triton:
https://github.com/llvm/llvm-project/blob/4017f04e/llvm/lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.cpp#L36
Making it consistent redues the risk of running into version mismatch issues.

[backend][amd] Use code object v5

---

python/src/llvm.cc
third_party/amd/backend/compiler.py
third_party/nvidia/backend/compiler.py

This avoids creating a separate linker each time to link a device library to avoid the overhead of internal tracking.

[backend] Use one linker to link all external libraries

---

third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandHelper.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandHelper.h
third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/MFMA.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/WMMA.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/ElementwiseOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/PatternTritonGPUOpToLLVM.h
third_party/amd/lib/TritonAMDGPUToLLVM/SPMDOpToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.h
third_party/amd/lib/TritonAMDGPUToLLVM/TritonGPUToLLVM.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/Utility.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/Utility.h

This is following better practice to avoid polluting and potential symbol collison. Along the way, also dropped various `using` clauses that are in header files or unused in cpp files.

[backend][amd] NFC: nest AMD namespace inside mlir::triton

---

python/triton/language/core.py

Inductor may generates kernel using tl.atomic_add https://gist.github.com/shunting314/cf8b9aae822621f59a30247139984cb6 . Latest triton does not work if the mask is None. The reason is when triton check if mask is None, it's a `tl.constexpr(None)` being checked.
cc @jansel @htyu @Jokeren

[FRONTEND] Make atomic op work with None mask again

---

python/src/llvm.cc
third_party/amd/backend/compiler.py

https://github.com/openai/triton/pull/3493 moved the AMD backend to use code object v5. But that reveals some issues that we still need to investigate and resolve. For now switch back to v4.
Though we need to be consistent by attaching the LLVM module attribute `amdhsa_code_object_version`, given that's what the AMDGPU LLVM backend is trying to query:
https://github.com/llvm/llvm-project/blob/6f44bb77/llvm/lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.cpp#L166-L173 If missing it will fallback to use v5, which was happening before https://github.com/openai/triton/pull/3493.
And FWIW, the magic string used to be `amdgpu_code_object_version`: https://github.com/llvm/llvm-project/pull/79905. The last LLVM bump https://github.com/openai/triton/pull/3463 picked up the renaming patch.

[backend][amd] Switch back to code object v4 and be consistent

---

third_party/amd/backend/compiler.py

This commit adjusts optimization passes a bit:
* Invoke canonicalization and cse after initial conversion to LLVM dialect in MLIR. This makes it possible to pick up canonicalization in other dialects (e.g., scf) before fully going down to LLVM dialect, which has not much canonicalization by design, or LLVM proper.
* First attach kernel attributes then link in external libs and run general LLVM optimize. Those kernel attributes may affect how optimizations are done.

[backend][amd] Reorder and adjust optimization passes

---

include/triton/Conversion/TritonGPUToLLVM/Utility.h
lib/Conversion/TritonGPUToLLVM/Utility.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp

Add more backend independent utilities, also edit 2 existing macros to use variable arguments
Previously, the addrspacecast macro would swap the parameters ->
#define addrspacecast(**val__, type__**)                                           \
rewriter.create<LLVM::AddrSpaceCastOp>(loc, **type__, val__**)
Once I changed the macro to use variable arguments, third_party/amd/lib/TritonAMDGPUToLLVM/LoadStoreOpToLLVM.cpp would break because it expected the arguments to be in the opposite order, which is why that file had to be edited for this change to work.

Added/edited LLVM utilities

---

include/triton/Dialect/TritonGPU/Transforms/Utility.h
lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp
lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
lib/Dialect/TritonGPU/Transforms/OptimizeDotOperands.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
python/triton/language/extra/cuda/__init__.py
python/triton/language/extra/cuda/utils.py
test/TritonGPU/dot-operands.mlir
third_party/nvidia/backend/compiler.py

Multiple fixes to allow pipelining to happen when generating a matmul with fp8e4b15 inputs. Also clean useless code in the frontend.

[FRONTEND][BACKEND] Cleanup and re-enable optimization with fp8e4b15

---

include/triton/Conversion/TritonGPUToLLVM/Utility.h
lib/Conversion/TritonGPUToLLVM/ConvertLayoutOpToLLVM.cpp
lib/Conversion/TritonGPUToLLVM/MemoryOpToLLVM.cpp

<git-pr-chain>
[Backend] Remove extra call to emitIndices.
storeDistributedToShared and loadSharedToDistributed both accepted a list of
indices and then didn't use them.  (Instead, they create the indices
themselves, lower in the callstack.)
Remove these, which removes a bunch of unneded IR.
While we're here, we also fix incorrect use of `static` in Utility.h.
1. 👉 #3529 👈 **YOU ARE HERE**

[Backend] Remove extra call to emitIndices.

---

include/triton/Dialect/TritonGPU/Transforms/Utility.h
lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp
lib/Dialect/TritonGPU/Transforms/Utility.cpp
python/test/unit/hopper/test_gemm.py
test/TritonGPU/accelerate-matmul.mlir

This changes the `wgmma`  instruction shape based on the total number of warps.
Instead of always using the largest version of `wgmma`, it honors
the user's `numWarps` hint, and uses a smaller `wgmma` shape to
distribute the work to all warps, rather than having some of them
idle.
Using m's shape, it calculates how many warps will be used in the m
dimension, then see how many are left for the n dimension. Then, it
chooses the largest N such that it is still evenly distributed.
This resolves issue https://github.com/openai/triton/issues/2662.

[OPTIMIZER] Take numWarps into account for  Hopper mma op

---

python/test/unit/language/test_core.py
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandHelper.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandHelper.h
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandMFMA.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/ConvertLayoutOpToLLVM/SharedToDotOperandWMMA.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/DotOpToLLVM/MFMA.cpp

This commit Changes wave layout within a CTA to follow 'order' property of MFMA layout.
Additionally, this commit fixes some typos found in AMD code.

[AMD] Fix AMD dot tests

---

third_party/amd/backend/compiler.py
third_party/amd/python/triton_amd.cc

We don't care about these Clang and OpenCL version details..

[backend][amd] Add step to cleanup version metadata in bitcode

---

python/triton/runtime/autotuner.py

For our application, we wanted to investigate when, how often, and for how long the triton autotuner is triggered (to asses the impact on the latency of the application).  
Therefore, we implemented a simple report flag to the autotuner decorator:
```python
@triton.autotune(
configs=[...],  
key=[...],
report=True,  # new, optional
)
@triton.jit
def fused_add_rmsnorm_triton(...
```
If this flag is set to true, the autotuner will print the following statement, every time a new autotune run is triggered:
```
Autotuner for function JITFunction(__main__:fused_add_rmsnorm_triton) finished after 4.15s; best config selected: BLOCK_N_SIZE: 512, num_warps: 8, num_ctas: 1, num_stages: 3;
```
There are no prints if a cached configuration is used. 
(We thought this could be also a helpful feature for …

[AUTOTUNER] adding simple report flag for autotuner runs

---

python/triton/language/core.py
third_party/nvidia/backend/driver.c
third_party/nvidia/backend/driver.py

This lets Triton programs that device_print a lot of data avoid truncation.

[CUDA] Add set_printf_fifo_size Python function.

---

python/triton/runtime/cache.py

On a distributed setting, processes from different nodes may have the same PID. If the seed for `random` is also set, the random number is also the same, which may finally lead to collision (actually happened on my cluster).
Changing the random number to `uuid` avoids such collision.

[RUNTIME] Replace random number with UUID

---

lib/Dialect/TritonGPU/Transforms/Pipeliner/MatmulLoopPipeline.cpp
test/TritonGPU/loop-pipeline.mlir

This PR fixes #3454
Previously, we included all LoadOp(s) into opInfo, whose contents are used for pipelining. However, this approach causes issues when we decide to not pipeline some LoadOps. Particularly, those LoadOps that are excluded will end up with an inconsistent state which violates the relevant integrity checks, and cause ICEs.
We fix the issue by only including LoadOps that are valid for pipelining.

[Backend] Only consider valid LoadOps for pipelining

---

include/triton/Conversion/TritonGPUToLLVM/Utility.h

<git-pr-chain>
[Backend] Assert if we hit known-broken case with small #mma shapes.
1. 👉 #3549 👈 **YOU ARE HERE**

[Backend] Assert if we hit known-broken case with small #mma shapes.

---

.github/workflows/integration-tests.yml
include/triton/Conversion/TritonGPUToLLVM/PatternTritonGPUOpToLLVM.h
include/triton/Conversion/TritonGPUToLLVM/TargetInfoBase.h
lib/Conversion/TritonGPUToLLVM/AssertOpToLLVM.cpp
python/test/unit/language/assert_helper.py
python/test/unit/language/test_subprocess.py
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.cpp
third_party/amd/lib/TritonAMDGPUToLLVM/TargetInfo.h
third_party/amd/lib/TritonAMDGPUToLLVM/TritonGPUToLLVM.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.cpp
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TargetInfo.h
third_party/nvidia/lib/TritonNVIDIAGPUToLLVM/TritonGPUToLLVM.cpp

This commit adds support for device assert in the AMD
backend. This creates a new virtual method on `TargetInfo`
so that we can specialize for different backends, given
that on AMD side we don't have the same lowering flow:
right now `__assert_fail` is not supported in the AMDGPU
backend; it's in the runtime. 
https://github.com/ROCm/clr/commit/7137a296ddab93708a245955cd6a7357922975cc
Instead we need to layer it on top of print and do trap
afterwards.

[backend][amd] Add support for device assert
